### ISSUE TITLE
[META] Move contrib module Date Basic into core

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1063]
Attempting to fulfill issue #478 Add date (field) module to core using https://github.com/backdrop-contrib/date_basic
- [x] Date api module faulty check on system date. #1064
- [x] Date module test producing error report #1065
- [x] Date module - incorrect display of finish date. #1066
- [x] Date module - incorrect default date with pop-up widget. #1067
- [x] Date module - undefined function date_get_timezone_db() #1068
- [x] Date module - Travis failure #1069
- [x] Date module - property of non-object #1070
- [x] Date module - views api #1073
- [x] Date module - attempt to edit field causes error #1074
- [x] Date module - incorrect date display #1097
- [x] Date module - date popup jQuery wvega option #1098

**Comment by klonos** [comment]
All tasks complete! Anything else?

**Comment by Graham-72** [comment]
I don't think there is anything more for me to do. I have kept the contrib module 'Date Basic' updated with these same changes and have just made a release of it, so that it is available if anyone wants to make use of it - as I am doing on a couple of sites under development. So maybe there is nothing more to do until @quicksketch takes a look at it?

I guess what will be needed is a PR that can merge Date Basic including its history, which is something I couldn't work out how to do and needs someone with a lot more Github skill than my elementary abilities.

**Comment by docwilmot** [comment]
Good work sir.

**Comment by quicksketch** [comment]
Confirmed that all these sub-issues have been resolved. All modules have been merged back into Date (or a core .inc file) in the current PR. Let's move this back over to main issue at https://github.com/backdrop/backdrop-issues/issues/478. Great job!
