### ISSUE TITLE
[META] Port Drupal 7.38 Issues to Backdrop

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1080]
- [x] | https://github.com/backdrop/backdrop/pull/1166 | [98bd112](http://drupalcode.org/project/drupal.git/commit/98bd1123eae143d97e5274544fc03abd6d289f20) | [Issue #2425325 by cleaver, JacobSanford: Batch API example code has wrong finished callback](http://drupal.org/node/)
- [x] n/a | https://github.com/backdrop/backdrop-issues/issues/159 | [49908ed](http://drupalcode.org/project/drupal.git/commit/49908edcf7742f6807d72b3b42a9413d95dd1c31) | [Issue #667058 followup by TwoD: Fix "JavaScript" typo in sites/all/libraries/README.txt.](http://drupal.org/node/)
- [x] | https://github.com/backdrop/backdrop/pull/1166 | [dc84091](http://drupalcode.org/project/drupal.git/commit/dc84091add715ca4abe4aa80fc32d27fe155ad4c) | [Issue #2500101 by David_Rothstein: sites/all/modules/README.txt should not imply that clearing caches always works after moving a module to a new subdirectory](http://drupal.org/node/)
- [x] | - | [5cb79b4](http://drupalcode.org/project/drupal.git/commit/5cb79b4b217e9aa315d61284398cce132c28bea4) | Drupal 7.38 (security fixes)

command used: git log 18c5da5028b7c3ba985e598bb8df45613285d437.. --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"

---

not sure I got that command right; looks OK; @jenlampton can you give it a glance and see if it looks like the right commits to you?

**Comment by quicksketch** [comment]
That looks right to me. Not a lot of changes in that release other than the security fixes (on which we coordinated the issues that affected Backdrop), see https://backdropcms.org/SA-CORE-2015-003.

The git command doesn't actually set up the links properly, we usually go back through and run a regex in Sublime Text to fix the issue links, or just go through them and make the links by hand.

**Comment by serundeputy** [comment]
thanks!

maybe click off the ones that are moot for backdrop for posterity.
and if any are not moot we (backdrop community) can knock them off.

**Comment by quicksketch** [comment]
Cool, checked off the last item and removed the first (just reverting the version string in bootstrap.inc). The README for libraries I cross-referenced our existing libraries issue.

**Comment by klonos** [comment]
Setting the milestone so that this issue does not fall off of our radar for the next release. If we cannot get everything ported, we can always push to the 1.2.4 :wink:

**Comment by quicksketch** [comment]
Only 2 commits that apply to Backdrop from this release. I made a PR at https://github.com/backdrop/backdrop/issues/1166.
