### ISSUE TITLE
[META] CKEditor/Rich text editor followups

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1087]
This issue summarizes follow-ups to the new WYSIWYG/rich text editor issue https://github.com/backdrop/backdrop-issues/issues/101.

Todo:
- [ ] #1093 - [UX] CKEditor: Replace the "Add a caption" checkbox with a "Caption" field
- [ ] #1222 - Add a teaser break plugin
- [x] #1259 - Custom block content not updated if you are switched to Source mode before saving the block.
- [ ] #1307 - Add a file/image browser
- [ ] #1585 - Add token support in upload directory definition
- [x] #1595 - CKEditor links do not handle aliases
- [x] #1926 - Prevent URLs or email addresses turning into links (partly editor related)
- [ ] #2054 - Retain aspect ratio when resizing images (option, set by default)
- [x] #2071 - Add a spell-check plugin
- [x] #2176 - [UX] CKEditor block element formats drop-down: Change "Normal" to "Paragraph"
- [ ] #2476 - [UX] - CKeditor: Allow fail-safe adding of external links
- [ ] #2980 - [UX] Allow the use of the `<small>` tag
- [ ] #2658 - [D8 feature parity] CKEditor: Allow Image Styles to be used with inline images
- [x] #3354 - [UX] CKEditor: Consider adding the Auto Grow plugin
- [x] #3356 - [UX] CKEditor: Include the Balloon Toolbar plugin introduced in 4.8, and start using it.
- [x] #3357 - CKEditor: consider the new Autocomplete plugin (introduced in 4.10) for addition to core.
- [ ] #3383 - URLs added in the image caption are not converted to links (although the text filter allows it)
- [ ] #4233 - CKEditor - Provide default styles

Done:
- [x] #1032 - [UX] New text format configuration UI.
- [x] #1089 - [UX] Open long filter tips in a dialog and rework the contents
- [x] #1777 - Add a custom link plugin (or port the Drupal 8 one)
- [x] #2072 - Add a file as an option for link source
- [x] #938 - [UX] Collapse the input format options fieldset on node edit forms
- [x] #1088 - Allow uploading an image.
- [x] #1091 - Ship with a text editor enabled out of the box
- [x] #1125 - Cannot insert an image into CKEditor when editing a custom block through Layouts
- [x] #1199 - Bug: Images are not uploaded automatically, need the button to be pushed.
- [x] #1206 - [UX] CKEditor: Allow to browse and enter links of local paths (content, users etc.).
- [x] #1231 - Bug: Cannot add the `Anchor` button
- [x] #1350 - Bug: CKEditor insisting on converting line breaks into paragraphs
- [x] #1373 - Bug: Image files removed by garbage collection
- [x] #1560 - Update to latest version of CKeditor
- [x] #1586 - Add a link to an image.
- [x] #1975 - Editor disappears when AJAX runs on node form
- [x] #2142 - Bug: add back missing link buttons
- [x] #2148 - Add format drop-down by default
- [x] #2174 - Bug: Cannot add the `Strike` button
- [x] #2386 - [UX] Restore browser based spellcheck
- [x] #2630 - Upload images in CKEditor via Drag and Drop or Clipboard Paste

**Comment by docwilmot** [comment]
re #938 I feel if we get the "filter tips" in a modal as planned, the text format selection area will be completely acceptable without the collapsed fieldset, so is it worth the extra click then?

**Comment by klonos** [comment]
I've updated the list to add a couple of issues reported by @Graham-72, fixed a minor typo and removed a duplicate entry (issue 1125).

**Comment by Graham-72** [comment]
Please may I register a plea that these CKEditor issues now become high priority. You have done a brilliant job with release 1.3.0 for which I am very grateful, but CKEditor is a large part of the face of Backdrop to my end users, and if there are things it cannot do or gets wrong my end users are not impressed.

**Comment by gifad** [comment]
:+1:  to @Graham-72 post : The missing Save button and plugin, the missing Autogrow plugin, are not understandable by my end users; they'd say it's not serious.
Ok, this is trivial to implement in a custom module, but not every one in small non-profit organisations have the option to write a single line of php (or the dozen of javascript lines to size the CKEditor area to the useable screen height)...

**Comment by quicksketch** [comment]
Moving this to 1.5.0 for further work. We upgrading CKEditor in 1.4.0 to version 4.5.9. We still have several items needing addressing.

**Comment by docwilmot** [comment]
Just a note, this is not the kind of thing I can handle, so I cant lend a hand here. But it would be great if this could be actually assigned to someone (or someones, since that's now possible), so that it doesnt just sit. I'm not sure (I hope I'm not being too presumptuous) how many of us are able to actually handle this. Would be great to see a show of hands here before we run out of time again.

**Comment by jenlampton** [comment]
I'm removing the bullet for "Add the ability to reuse an existing image on managed file elements" since I don't really understand what that means. Are we talking about building a new managed file form element that would allow the same toggle between autocomplete / file browser / view? Just like we already have in the CKEditor image dialog?

**Comment by Graham-72** [comment]
> create an issue with an explanation

I now have tried to do this at issue #2056 'CKEditor - add the ability to reuse an existing image'.

**Comment by jenlampton** [comment]
We already have an issue for that in our list: https://github.com/backdrop/backdrop-issues/issues/1307

**Comment by Graham-72** [comment]
:+1:

**Comment by quicksketch** [comment]
As a meta, I'm moving this to 1.6.0. GitHub recently added "Projects" to help grouping large tasks and track their statuses. It might replace this concept of "Meta issues" like this one. I started a test one to see it in action: https://github.com/backdrop/backdrop-issues/projects/1#card-40427

**Comment by klonos** [comment]
Well, more features might be added to GitHub projects and they might eventually evolve to be suitable for our meta-issues, but at the moment they do not provide the very useful "x of y tasks completed" overview status that issues do. So, in the meantime I've re-ordered the list of the children issues in the issue summary to be ascending (was random). It helps to spot any issues listed twice (or more) 😄

**Comment by olafgrabienski** [comment]
Checked 2148 in the list, which was fixed for 1.5.0.

**Comment by quicksketch** [comment]
Checked off #1231 and #1350, which were also fixed in 1.5.0.

**Comment by jenlampton** [comment]
Pushing this master meta off to 1.7, there are some sub-iussues that will get in by 1.6, and they have been tagged appropriately.

**Comment by olafgrabienski** [comment]
I've added some CKeditor related issues in the checklist which were missing (1206, 1595, 1926, 2176).

**Comment by quicksketch** [comment]
We will have knocked off #2630 and #1206 in 1.7.0.

I'm not sure if we should keep bumping this to the next minor release, but honestly I like having it accessible/findable there. Bumping to 1.8.0 for now.

**Comment by jenlampton** [comment]
I'm going to bump the milestone for the meta to 1.9, I agree I like having it in focus for people looking for our priorities.

**Comment by jenlampton** [comment]
bumping milestone.

**Comment by quicksketch** [comment]
Knocked out #2072 in 1.10.

**Comment by jenlampton** [comment]
bumping milestone.

**Comment by klonos** [comment]
@jenlampton this is a meta-issue. Should we just change the milestone to `1.x-future` to avoid having to bump it every time?

**Comment by klonos** [comment]
Done 😄
