### ISSUE TITLE
Convert all admin listings to views

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1101]
This is an issue that will allow us to track the progress of...
Put [admin_views](https://www.drupal.org/project/admin_views) in core

Administrative pages:
- [x] [Replace admin/people with a View](https://github.com/backdrop/backdrop-issues/issues/149) in user module
- [x] [Convert admin/content to a View](https://github.com/backdrop/backdrop-issues/issues/150) in node module
- [ ] [Convert admin/content/comments to a View](https://github.com/backdrop/backdrop-issues/issues/549)

**Comment by klonos** [comment]
What was wrong with the meta-issue? Cant we use that one instead of opening a new issue here?

**Comment by klonos** [comment]
@jenlampton: Do you still feel that we need a separate issue for this task? Or is it simply in order to have a milestone set for it (the parent meta-issue has no milestone set yet)?

**Comment by quicksketch** [comment]
I think we should just use the existing meta at https://github.com/backdrop/backdrop-issues/issues/151 as well. Let's close this and consolidate over there.
