### ISSUE TITLE
[META] Theme System Cleanup

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#125]
In order to make the theme system make more sense to people, it will need a lot of cleanup:
- [x] https://github.com/backdrop/backdrop-issues/issues/193 | META: Removal of the process layer
- [x] https://github.com/backdrop/backdrop-issues/issues/195 | META: Merge templates that should use loops
- [x] https://github.com/backdrop/backdrop-issues/issues/200 | META: Markup cleanup / HTML5
- [x] https://github.com/backdrop/backdrop-issues/issues/207 | META: CSS review and cleanup
- [x] https://github.com/backdrop/backdrop-issues/issues/211 | META: JS review and cleanup

**Comment by jenlampton** [comment]
Closing this issue for now, we will come up with a new meta for Backdrop 2.0!
