### ISSUE TITLE
[META] Terminology improvements

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#127]
I want to propose some improvements for Backdrop's UI.  Below is a list of ideas I'd like to run by a larger group for consensus.  I'm summarizing here so people can get the big picture.
### Product-wide Terminology Updates

Product-wide terminology updates will replace one term, globally, with another.  This involves User Interfaces, URLs, Code, and Documentation.
- [x] #773 | Rename "People" to "User accounts" | [d.o](https://drupal.org/node/1409992)
- [x] #771 | Use "Edit" / "Configure" consistently and correctly in drop-buttons
- [x] #772 | Use "Default" / "Overridden" / "Custom" consistently for config state (views, layouts, etc)
- [x] #774 | Rename "View modes" to "Display modes" (avoid confusion with views)
- [x] #2162 | Change `Front page` to `Home page` in core
- [ ] #203 | Rename "taxonomy" to "Categorization" in the user interface
- [ ] #4222 | Rename Vocabulary and Terms
- [ ] #xx | Eliminate confusing words in the User Interface: node / entity / bundle
### Menu Clean Up
- [x] #224  |   Remove the "Navigation" menu
- [x] #302  | Rename the "Management" menu to "Administration"
- [x] #303  | Rename the "User menu" menu to "Account menu"
- [x] #304 | Rename the "Main menu" menu to "Primary Navigation"
### Admin Bar Updates

Toolbar-only changes serve to help get users to the pages they are looking for more easily, but do _not_ attempt to rename concepts from Drupal.
- [x] https://github.com/backdrop/backdrop-issues/issues/209 | Rename "Modules" to "Functionality" | [d.o](https://drupal.org/node/1167458)

**Comment by clickbox** [comment]
I feel like "Appearance" could be changed to "Themes". It seems like appearance is used for describing what the Themes are instead of just saying here is the Themes page. 

"Appearance" links to your theme settings page and so does "Themes" so that is at least redundant, if not intentional.

**Comment by jenlampton** [comment]
@clickbox This was an intentional change in D7 for UX improvement.  The average person-on-the-street doesn't know what the word "themes" means, but they do know what "Appearance" means. We want them to say "yes, appearence, I want that" and then stumble onto the themes page. That's training them to know what themes are. By providing both links, you also meet the needs for people who know what themes are. We did the same thing to the Functionality/modules links in Backdrop - since this appearance/themes change was so successful.

**Comment by clickbox** [comment]
That makes sense. You can change the name of it in the menu settings too I suppose, if you have a personal preference.

**Comment by Dinornis** [comment]
Perhaps these issues can be added to the `Admin Interface improvements` list?
* https://github.com/backdrop/backdrop-issues/issues/1703
* https://github.com/backdrop/backdrop-issues/issues/2508
