### ISSUE TITLE
[META][UX] Improve the process of installing projects.

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1288]
Sub-tasks:
- [x] #2200 [UX] Project Installer: Submodules not available to be enabled during the last step.
- [ ] #2193  [UX] Project Installer: On each cron run, pull and cache locally a project list from b.org
- [x] #3177 [UX] Project installer: Dependencies installed one at a time instead of all together in a single go
- [x] #3142 [UX] Project installer: No "Enable modules"/"Finish without enabling" buttons if there is at least one module with unmet dependency
- [ ] #3178 [UX] Project Installer: Pre-select checkboxes in the "Enable modules" step
- [ ] #3245 [UX] Hide "Run Database Updates" / next steps if there are no next steps
- [x] #3246 [UX] Project Installer: "Select versions" step: checkbox labels in the project releases list should not be rendered as links.
- [ ] #5442 | [UX] Project Installer: Provide steps indicator on narrow screens

### Original issue summary

---
## The neglected process of installing and enabling a module

Here is my process when installing and enabling a new module
1. Go to the install page ("/admin/modules/install"), drop the module URL and click "install"
2. Land on the "Installation success page"
   
   ![enablemodule](https://cloud.githubusercontent.com/assets/14132746/10231291/8f646ede-6847-11e5-9351-52daab397277.png)
3. Click "Enable newly added modules" which takes me to the modules list.
4. Scroll down the module listing page to my module entry (or search but sometimes I forget the module's name. Hey, it's a brand new module)
5. Click on the checkbox to enable my new module
6. Scroll all the way down to the bottom of the page, and then click "save configuration"
7. Done

Such a tedious and annoying process.
## Ideally what the new process should look like
1. Go to the install page ("/admin/modules/install"), drop the module URL and click "install"
2. Land on the "Installation success page" that presents me with 3 options under Next Steps
   - **"Install another module"** Keep the same as before. Why? You may have a bunch of modules you want to install one after another and you'll worry about enabling and configuring later.
   - **"Turn on the module X now"** This is a new link that basically does steps 3-7 in one shot. Why this feature? Sometimes you're only installing one module and this speeds up the process a lot. Plus, I am used to Wordpress having this. And it just makes sense.
   - **"« Return to list of modules"** This is the same as "Enable newly added modules" except reworded. The use case? When you are done installing lots of modules, you'll now want to go check them out. Also, if good if you install one module but don't want to enable it right away.
3. Click the new option called, "Turn on the module X now" and get redirected to the modules list
4. Done. No extra work needed. +1 for efficiency & UX.
## Suggestions Summarized

Basically, 
- [ ] Rename "Enable newly added modules" option to "« Return to list of modules" on the success page 
  - Move this option to the bottom of the list
- [ ] Add a new option called "Turn on the module X now" where X is the module you just installed. 
  - When clicked, it enables the module automatically and returns you to the module listing
  - Make this the second option under "Install another module"
  - If by some chance there is some dependencies issues, then either don't show this option or replace with simple text (e.g. "Can't turn on module X in one shot because it requires other modules or some other issue.")
- [ ] Also, as a bonus, on the module listing page, rename "Save configuration" to "Save changes"
  
  ![save](https://cloud.githubusercontent.com/assets/14132746/10232503/c6ba48fc-684e-11e5-8a8b-1de6cda6c461.png)
  Configuration? WTF?
- [ ] Remove the link "Administration pages" since it serves no real purpose while in the process of installing modules. The link "« Return to list of modules" serves that purpose of returning to the admin page

**Comment by quicksketch** [comment]
>  Add a new option called "Turn on the module X now" where X is the module you just installed. 

This would work for most modules, though some modules include a second (or third) sub-module within them. In such cases, do you think we should omit this option and provide a description instead? e.g. This package contained multiple modules. Visit the modules page to enable these new modules.

Or would displaying a form on the page with checkboxes or something be better?

**Comment by sutibun** [comment]
Description would probably be better... maybe something along the lines of

> Because Module X may rely on the presence of other modules, provide additional submodules and/or require special tinkering, please look at the module entry to turn it on.

Just like with dependency issues, there are probably other cases where it's better for the user to look closer at the module list. This is aimed for those simple modules that don't need much thinking.

Oh, I forgot to mention

- [ ] Remove the link "Administration pages" since it serves no real purpose while in the process of installing modules. The link "« Return to list of modules" serves that purpose of returning you to the admin page

Added it above.

**Comment by klonos** [comment]
You know that we could convert the "Install from a URL" field to a multi-line text box that could install multiple module/theme/layout URLs. Right?

...this way, people can create text files with a list of their most-regularly used projects that they could copy-paste in the text box and save them the trouble of having to revisit the same page and go through the same steps multiple times. It would even support "recipe" collections where people writing tutorials could provide lists of projects for others to copy-paste and be done with it. We save people not simply one step or two, but dozens :wink: 

Similarly, we could allow multiple uploads with the "Upload a module, theme, or layout archive to install" widget.

...that way, we allow people to have a folder of saved, downloaded projects (could as well be custom modules or themes - not only contrib) instead of text lists. Cool hah?

The "Installation completed successfully" screen could then provide a list of checkboxes (some sort of a stripped-down and customized version of the modules page) with only the projects that the user just installed. Saying "Select which projects you want to enable". That could solve the issue of multiple sub modules etc. Right?

I wanted to file an issue for this for some time now. Thanx @sutibun for beating me to it :wink:

**Comment by klonos** [comment]
> Or would displaying a form on the page with checkboxes or something be better?

That, yes. Sorry, had the tab open for some time typing my thoughts. Nate beat me to it too.

**Comment by sutibun** [comment]
> Or would displaying a form on the page with checkboxes or something be better?

oh wait, hehe didn't see @quicksketch's last suggestion till @klonos mentioned it

Change my mind, let's go with the checkboxes. I like that idea better... have copy maybe saying

> Would you also like to enable these submodules as well?

or better yet:

> Would you also like to turn on these extra features provided by the X module

I like your ideas @klonos. A lil' advanced but maybe we can add them in the "Install a project" page ("admin/modules/install") Maybe deemphasized visually since it's for more experienced users

![install](https://cloud.githubusercontent.com/assets/14132746/10237232/4a6cf184-6874-11e5-8f82-3c52d5c85ebf.png)

Maybe similarly provide small sized links below called "Batch install'

**Comment by sutibun** [comment]
@klonos I just find these so annoying and it's so apparent I can't stand it... I wonder if because most Drupal users are developers and they use drush that these things get neglected. I'm just on a vendetta to clear these issues that has plagued Drupal. Since I am not a developer or know too well how Drupal works inside, I can freely focus on the outside.

> The "Installation completed successfully" screen could then provide a list of checkboxes (some sort of a stripped-down and customized version of the modules page) with only the projects that the user just installed. Saying "Select which projects you want to enable". That could solve the issue of multiple sub modules etc. Right?

That's gold. The other part I hate is having to scroll or search for the module I just installed.

**Comment by docwilmot** [comment]
This will all be moot when we merge Project Browser to core:
- no need to copy paste module URLs
- can install multiple modules at once
- installs dependencies
- already includes the "enable the installed modules" feature you mention

Download and test please.

I wonder if maybe as part of the port we could try and dovetail the manual project install process into the Project Browser process. So after you click to upload the zip file or copy/paste the URL, you land on the PB page that checks dependencies and asks you to enable etc and continue from there.

**Comment by klonos** [comment]
> This will all be moot when we merge Project Browser to core...

I wanted to mention this in my comment previously, but wasn't sure if we intent to have Project Browser *replace* the current "Install a project" page or *compliment* it.

You know, the way I propose having a text box instead of a text field (to allow multiple projects to be copy-pasted from a text list) plus making the upload widget accept multiple files. That covers the tutorial/recipe, all-in-a-single-go use case. I don't see a way to do this with the Project Browser. Sure, multiple project selection and installation will be possible, but selecting these will still be a multi-step process (depending on the amount of the projects to be installed). You know... search, tick to add in the installation queue, search again, add in the installation queue... repeat. Or will the Project Browser have some way to accept multiple search arguments in order to allow selecting a list of projects somehow?

**Comment by sutibun** [comment]
I won't have time to play with Project Browser (working to transfer one of my sites to Bd) but if what you say is true

>- no need to copy paste module URLs
>- can install multiple modules at once
>- installs dependencies
>- already includes the "enable the installed modules" feature you mention

then that sounds really nice.

Thinking like a fox
-----

> Sure, multiple project selection and installation will be possible, but selecting these will still be a multi-step process

I also suspect Project Browser won't help with this.

I haven't seen Project browser or know too much about it but maybe that's a good thing. I've given this installation issue some thought while busy today and I've come up with different level of awareness of users when it comes to extension installations.

1. **Browser:** Wants to discover something new
  - User basically goes through module list (either via [bdcms.org](https://backdropcms.org/modules) or project browser) and installs the ones they like
  - Since wants a module only AFTER they discover it, installing one by one is fine.
2. **Word of mouth:** Learns from others
  - User learns of a module's existence from friends or online articles or, in asking for help, user gets recommended a module.
  - Since only dealing with a few modules at a time, installing them one by one is ok and possibly preferred.
3. **Experience:** Have a concrete goal in mind
  - The user already knows what to build and the exact modules needed to do so
  - Either the user has experience with Bd OR user gets told exactly all the modules they need to build what they want.
  - Given they know the modules needed, installing one by one is actually a hindrance.

The Unseen Project Browser re-imagined
----

Given my ignorance, here is my vision

### Project browser homepage + others

My imagined project browser homepage would cater to new users ... meaning **the focus is on optimizing for a great browsing experience** with popular module listings, editor picks, etc. Why? Most normal users won't know what is an extension and providing a tailored experience would help with UX.

![project-browser](https://cloud.githubusercontent.com/assets/14132746/10261241/496a92ba-6954-11e5-829e-2eebeef9936a.png)

I guess you could also have categories for each extensions like modules for writers, modules for dev, etc. I didn't have enough time to think this browsing page out but you get a rough idea. Note there are other pages on top specific for themes, layouts, and modules. All these pages for the most part will take care of the "1. browser" mentioned in my list.

However, take note that on top of the page **there will always be a search form on the top right.** This caters to those that already know the module they want and where browsing may be a slight hindrance. ("2. Word of mouth" in my list)

### Outside of the Project browser but integrated

Now for the more "3. Experienced" in my list, you could integrate the current installation page but improve on it. I pretty much swiped @klonos' good ideas. Take a look below

![adv-install](https://cloud.githubusercontent.com/assets/14132746/10261245/521d5be0-6954-11e5-8b73-753afe07bc8a.png)

Although, I do believe we should focus heavily on new users, we SHOULDN'T forget those who are more experienced as well. Adding "advanced" on the tab will keep newbies away but allow advanced users to have a great Bd experience.

On the left, you simply paste the extension URL one per line and Bd will install them for you at once. On the right side, you could alternatively upload the extension yourself. There's a button to keep adding more upload forms.

**Comment by klonos** [comment]
I'm sorry my dear monkey. I must missed your (rather lengthy as always) presentation of another mockup. I do like the idea of categories and having a "Featured" (for new projects that gain rapid adoption) and "Popular" (all-time, most-installed) section. It's how for example [AMO](https://addons.mozilla.org) works for mozilla addons...

- they have a slider with "Mozilla’s Pick of the Month!", "First time with Add-ons?" and "Worry-free browsing" (that shows 3 of their security-related addons):

![amo-addon_slider](https://cloud.githubusercontent.com/assets/2423362/13552632/4d8ec542-e3bf-11e5-8c52-32d7dce70fa2.gif)

- and they have filters for "Featured", "Most Popular", "Top Rated" as well as by category. Also specific sections for "Featured Extensions", "Up & Coming Extensions" and "Featured Themes"

I really like their design and they have a design where they seem to re-use similar sections in their in-browser addon selector:

![firefox-addons](https://cloud.githubusercontent.com/assets/2423362/13552679/32fb28ea-e3c1-11e5-87f3-fab8ef77419d.png)

**Comment by klonos** [comment]
...in general I would like to preserve the classic page where people add projects to their site as an option when we implement the project browser. And I once again like the mockup by our monkey friend that includes the "Install from URL" multi-line text box as well as the multiple file upload widget (#1380):
