### ISSUE TITLE
[META] Port relevant Drupal 7.40 issues to Backdrop

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1331]
- [x] | N/A | [4cc037d](http://drupalcode.org/project/drupal.git/commit/4cc037d4dd9b52ee59eecb3bbf1795c75c0ead5a) | [Issue #1260938 by dawehner, David_Rothstein, flaviovs, Fabianx, pfrenssen, boran, jelo, neclimdul, scorchio, Berdir, vijaycs85: D6 to D7 update can fail on duplicate files in system update #7061](http://drupal.org/node/1260938)
- [x] | https://github.com/backdrop/backdrop/pull/1167 | [e575b47](http://drupalcode.org/project/drupal.git/commit/e575b47da2f00016ee62d169ecdfaf09e8cb4cd5) | [Issue #2388255 by dawehner, pwolanin, hussainweb, greggles: Limit PDO MySQL to executing single statements if PHP supports it](http://drupal.org/node/2388255)
- [x] | https://github.com/backdrop/backdrop/pull/1167 | [47d24ed](http://drupalcode.org/project/drupal.git/commit/47d24ed171bcb4c6aca409ce8af0844a06520f5c) | [Issue #2364629 by gaurav.goyal, cilefen, dcam: After deletion of built-in administrator role the default admin role is not shown as disabled](http://drupal.org/node/2364629)
- [x] | https://github.com/backdrop/backdrop/pull/1167 | [c9d1889](http://drupalcode.org/project/drupal.git/commit/c9d188950508f104a8115ec7a78335607d9b6037) | [Issue #462950 by pwolanin, Pere Orga: Mitigate the security risks that come from IE, Chrome and other browsers trying to sniff the mime type](http://drupal.org/node/462950)
- [x] | https://github.com/backdrop/backdrop/pull/1167 | [3c8b182](http://drupalcode.org/project/drupal.git/commit/3c8b182b79850c497b24c79c1c3e56999b3da12a) | [Issue #2263365 by donquixote, smccabe, longwave, alexpott, joelpittet, Fabianx, mikeytown2, joseph.olstad, sun: Second loop in module_implements() was being repeated for no reason (performance improvement)](http://drupal.org/node/2263365)
- [x] | https://github.com/backdrop/backdrop/pull/1167 | [e105186](http://drupalcode.org/project/drupal.git/commit/e105186172a34f4c3ba05af594e34dfa63083b72) | [Issue #496170 by stefan.r, chx, Fabianx, jbrauer, David_Rothstein, roderik, rwohleb, pounard, kenorb, Jose Reyero, joelpittet, catch: module_implements() cache can be polluted by module_invoke_all() being called (in)directly prior to full bootstrap completion](http://drupal.org/node/496170)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [56bbd4b](http://drupalcode.org/project/drupal.git/commit/56bbd4ba0165c8c8f902ee6ebde66a4d5fdfb1a0) | [Issue #2017433 by LinL, BarisW, coredumperror: The documentation for hook_ranking() is wrong](http://drupal.org/node/2017433)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [c60d7b0](http://drupalcode.org/project/drupal.git/commit/c60d7b098a9db9abd9a8de3b6f125df3a2bfda24) | [Issue #2205271 by trobey, jhedstrom, hass, alexpott, chx, joachim, jhodgdon: Add an optional project namespace for dependencies](http://drupal.org/node/2205271)
- [x] | N/A | [ab4064e](http://drupalcode.org/project/drupal.git/commit/ab4064e9ae9071a01f3e65446608f17d1f565daf) | [Issue #2470525 by berenddeboer, osman: statistics_node_view overwrites #attached JavaScript](http://drupal.org/node/2470525)
- [x] | N/A | [d488eb1](http://drupalcode.org/project/drupal.git/commit/d488eb129f4d65334ed999d12012ea8380992248) | [Issue #2376239 by david_garcia, dobe: "format" field in table "date_format_locale" should be case sensitive](http://drupal.org/node/2376239)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [f754836](http://drupalcode.org/project/drupal.git/commit/f7548361a664b6cb2fffc4e23a2a1a6620addd80) | [Issue #1973262 by cilefen, Matt V., David_Rothstein, Anybody, Rob230: User pages display incorrect title instead of "Menu link title" when link paths are added to a default menus](http://drupal.org/node/1973262)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [6379101](http://drupalcode.org/project/drupal.git/commit/6379101933142e2eeaea2f4eb41f4d32a9e47531) | [Issue #2511306 by ElusiveMind, JeroenT, leolando.tan, cilefen, charginghawk: Error: Call to a member function getElementsByTagName() in filter.module when filter_dom_serialize() is passed an empty document.](http://drupal.org/node/2511306)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [e88bbea](http://drupalcode.org/project/drupal.git/commit/e88bbeaa083c9d8309b6879259c460ca977410f3) | [Issue #619542 by dcrocks, bfroehle, catch, amontero, jayeshanandani, malcomio, JohnAlbin, olamaekle: Malformed theme .info files break menu_router generation](http://drupal.org/node/619542)
- [x] | N/A | [6924406](http://drupalcode.org/project/drupal.git/commit/692440692862d42f6ec4b2c4fec6e06c9b72e169) | [Issue #1275978 by pillarsdotnet, Zgear, cck, dcam: The thousand_separator for numeric fields should default to '' (nothing) instead of ' ' (space)](http://drupal.org/node/1275978)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [dc264c5](http://drupalcode.org/project/drupal.git/commit/dc264c53d9d63103b35e6a2edfb6b0128d2e2480) | [Issue #2233929 by alexpott, Dave Reid, Berdir, YesCT: drupal_set_time_limit should not be able to change the time limit if it's already unlimited](http://drupal.org/node/2233929)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [890d98a](http://drupalcode.org/project/drupal.git/commit/890d98ac96b578206733236ecc23acaf57585454) | [Issue #2483025 by joshi.rohit100, dcam: Remove 'has_body' and 'body_label' from drupalCreateContentType()](http://drupal.org/node/2483025)
- [x] | https://github.com/backdrop/backdrop/pull/1174 | [3d1be9b](http://drupalcode.org/project/drupal.git/commit/3d1be9b5ca8cf7baadeb2e86665c080526d805cf) | [Issue #2342667 by claudiu.cristea, Dave Reid, ndobromirov: Cron and batch processing of queues are not accepting callables](http://drupal.org/node/2342667)
- [x] | N/A | [a70cff3](http://drupalcode.org/project/drupal.git/commit/a70cff3ed4a9cb2ff11164314bcad74e22b45ce7) | [Issue #890934 by sandipmkhairnar, reglogge: Garland uses $vars instead of $variables](http://drupal.org/node/890934)
- [x] | N/A | [e344d46](http://drupalcode.org/project/drupal.git/commit/e344d465b2e8c7dd4e812dbecfd29a10c6f2066e) | [Issue #1737714 by legovaer, rlhawk: Help text does not display when editing an image effect](http://drupal.org/node/1737714)
- [x] | N/A | [6901ef7](http://drupalcode.org/project/drupal.git/commit/6901ef70aa6466cbd30e8633b88b91c678b0f825) | [Issue #2486643 by AlexKirienko: Undefined index: nid in main() in statistics.php](http://drupal.org/node/2486643)
- [x] | N/A | [8ee4f5a](http://drupalcode.org/project/drupal.git/commit/8ee4f5accb4571020fdc86f952388810301a8d9c) | [Issue #1514088 by DamienMcKenna: Minor comment formatting inconsistencies in cache.inc](http://drupal.org/node/1514088)
- [x] | https://github.com/backdrop/backdrop/pull/1175 | [69b1ff8](http://drupalcode.org/project/drupal.git/commit/69b1ff814b49cb6bb8c0108df77e3ef18852ec81) | [Issue #1719280 by GuyPaddock, Robin Millette: Undefined index warning in user_menu_link_alter() when manually adding a "user" path as a shortcut](http://drupal.org/node/1719280)
- [x] | N/A | [f33147e](http://drupalcode.org/project/drupal.git/commit/f33147e9b49facc6c6fc93c25a6f9fab992843b6) | [Issue #2254235 by AohRveTPV, mahtoranjeet, er.pushpinderrana, yogen.prasad, ashutoshsngh, Manjit.Singh, Charles Belov, nod_, droplet: Don't include leading and trailing spaces in password strength](http://drupal.org/node/2254235)
- [x] | https://github.com/backdrop/backdrop/pull/1175 | [c515c14](http://drupalcode.org/project/drupal.git/commit/c515c14dadab747b7fb02af04723be2435dff6b8) | [Issue #1520716 by lokapujya, djdevin, David Lesieur, cwells, jhedstrom: "Files displayed by default" not respected](http://drupal.org/node/1520716)
- [x] | https://github.com/backdrop/backdrop/pull/1175 | [e67dfa5](http://drupalcode.org/project/drupal.git/commit/e67dfa572cde8575162c03594c168183efda0849) | [Issue #2060553 by jhodgdon, sivaji@knackforge.com, manningpete: Test that searching for HTML entities works as expected](http://drupal.org/node/2060553)
- [x] | N/A | [6c6088e](http://drupalcode.org/project/drupal.git/commit/6c6088e492d93b1475eb629430cc33af62dc5d70) | [Issue #2494403 by tonystar: $field_types is not initialized in drupal_schema_field_types()](http://drupal.org/node/2494403)
- [x] | https://github.com/backdrop/backdrop/pull/1175 | [f09fb9e](http://drupalcode.org/project/drupal.git/commit/f09fb9ec7c506f12d7f2498faa1a3f3d51d16547) | [Issue #1845104 by dcam, longwave, thehong, er.pushpinderrana, martin_q, David_Rothstein: drupal_set_message('0') results in no output rather than outputting "0"](http://drupal.org/node/1845104)
- [x] | N/A | [d2900ab](http://drupalcode.org/project/drupal.git/commit/d2900abc52256190275b1ed7c3d75e88d14c48c4) | [Issue #1534490 by msonnabaum, bigjim, David_Rothstein, pounard, Dave Reid: Make block cache cids alterable](http://drupal.org/node/1534490)
- [x] | https://github.com/backdrop/backdrop/pull/1175 | [00206a4](http://drupalcode.org/project/drupal.git/commit/00206a4d7f87981b3b1212942ce65f371c0cb3ae) | [Issue #1647440 by chrisrockwell, Dave Reid, greggles: Fix PHP notice if invalid format ID requested at filter/tips/format-id](http://drupal.org/node/1647440)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [6e6c3db](http://drupalcode.org/project/drupal.git/commit/6e6c3dba67cda8b218befae00422d361b3990942) | [Issue #2455057 by michaellenahan, jhodgdon, jelo: Fix fast 404 settings for private image files](http://drupal.org/node/2455057)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [21932a5](http://drupalcode.org/project/drupal.git/commit/21932a5f8a7ea90cd9251b9db7196b495c6842c3) | [Issue #2477641 by opdavies, markpavlitski, pguillard, sivaji@knackforge.com, kaypro4, gyuhyon, edutrul, yoroy: One-time login link failure messages are misleading because they are not marked as errors](http://drupal.org/node/2477641)
- [x] N/A | [c2d06db](http://drupalcode.org/project/drupal.git/commit/c2d06db1234580248b9b6475113f3ee1cc0b08ab) | [Issue #2538640 by rrrob, dawehner: Add theme_debug to default.settings.php](http://drupal.org/node/2538640)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [186368f](http://drupalcode.org/project/drupal.git/commit/186368f1c98ef0bba70473aabf135026c7e722de) | [Issue #2500717 by afi13, cilefen, evilfurryone: Sort entries in the site status report page alphabetically, BUT case-insensitively](http://drupal.org/node/2500717)
- [x] | N/A| [5663123](http://drupalcode.org/project/drupal.git/commit/566312388ac7fdfd24bfa3c98e85d5c26eb4776c) | [Issue #2559335 by epophoto, cilefen, andrewmk: password-hash.sh is hardcoded to use "/usr/bin/php"](http://drupal.org/node/2559335)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [830fdea](http://drupalcode.org/project/drupal.git/commit/830fdeac5a7e176a66443e4975bf9ca58d1a18ab) | [Issue #2163209 by mgifford, David_Rothstein, andrewmacpherson, talhaparacha, dcam, Charles Belov, davidhernandez, jwhitsit: Add alternate text to file icon](http://drupal.org/node/2163209)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [792aca6](http://drupalcode.org/project/drupal.git/commit/792aca6823966f0d464ed05388dbf813d103285d) | [Issue #2392109 by jacob.embree, sumitmadan, ByronNorris, dcmul, ckaotik, jhedstrom: Filter: Allow plus sign in email addresses](http://drupal.org/node/2392109)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [ab86fe4](http://drupalcode.org/project/drupal.git/commit/ab86fe4810a2ec33386ec702e16f257feef3f45e) | [Issue #2313085 by tkuldeep17: Can't add class to user picture by template_preprocess_user_picture as class attribute has hard coded in user picture tpl file](http://drupal.org/node/2313085)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [f12effc](http://drupalcode.org/project/drupal.git/commit/f12effc70c835e77bfdea394214df9247533d319) | [Issue #1592688 by jgtrescazes, tstoeckler, eric.chenchao, fietserwin, Heine, stefan.r, Dmitriy.trt, lachezar.valchev, bogdan khrupa: #states can cause the form "required" mark to appear more than once on the same element](http://drupal.org/node/1592688)
- [x] | N/A | [183a425](http://drupalcode.org/project/drupal.git/commit/183a425c551969d4f56b04766fca82819a2a7b15) | [Issue #2508055 by Dave Reid, David_Rothstein, hussainweb: Add support for autoloading Traits](http://drupal.org/node/2508055)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [3b96a7d](http://drupalcode.org/project/drupal.git/commit/3b96a7d9124037c9e6f2e43ba5dd2de89175580b) | [Issue #2512210 by trgreen17, naveenvalecha, David_Rothstein, jhodgdon, liberatr: SimpleTest - WebTestBase method creates binary-text files when the intention was to create text files, and text file creation is broken](http://drupal.org/node/2512210)
- [x] | N/A | [21598ba](http://drupalcode.org/project/drupal.git/commit/21598ba65ef45a088204278f96ee61d443f0bb17) | [Issue #2581743 by carstenG: Missing space in block module](http://drupal.org/node/2581743)
- [x] | N/A | [e719d5c](http://drupalcode.org/project/drupal.git/commit/e719d5cfe23d9b319bdb064f15dcd53eb6fc2070) | [Issue #1576552 by jhedstrom, jcisio, markie: Prevent PHP notices in path_node_insert/update if $node->path is defined but $node->path['alias'] is not](http://drupal.org/node/1576552)
- [x] | N/A | [2fd22bd](http://drupalcode.org/project/drupal.git/commit/2fd22bd09f6be148c6b5f7ec888c15f910c940ed) | [Issue #955658 by Refineo, dswier, steinmb, emorency, filijonka, yched, Bevan: Undefined index: module in FieldInfo::prepareInstanceDisplay()](http://drupal.org/node/955658)
- [x] | https://github.com/backdrop/backdrop/pull/1176 | [63358df](http://drupalcode.org/project/drupal.git/commit/63358dff31f8ecdd9eb00a61de1122123ff6f1d7) | [Issue #2350033 by murrayw, kenorb: drupal_http_request thinks 201 through 206 status codes are an error](http://drupal.org/node/2350033)
- [x] | N/A | [d3e0221](http://drupalcode.org/project/drupal.git/commit/d3e02219e85bc9335aef13ad7cb668025a7cba11) | [Issue #2513646 by pwolanin, naveenvalecha, alexpott: Role name is unescaped on block admin via JS](http://drupal.org/node/2513646)
- [x] | N/A | [ff246eb](http://drupalcode.org/project/drupal.git/commit/ff246ebcc9b67f7a47ad52529ae81a60a3269305) | [Issue #2146643 by quicksketch: Speed up drupal_parse_info_format() 3x and reduce memory 95%](http://drupal.org/node/2146643)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [793788f](http://drupalcode.org/project/drupal.git/commit/793788fc2539211a539ffd8f1868c13932153353) | [Issue #2369675 by FMB, pstewart, jhodgdon: Document that SearchQuery does not support orderBy in queries outside of addScore](http://drupal.org/node/2369675)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [e835365](http://drupalcode.org/project/drupal.git/commit/e8353656924be31725e6293f411d5413c5966eb1) | [Issue #2480805 by JacobSanford, eiriksm, jhodgdon: The function doc block for image_style_deliver is missing a parameter](http://drupal.org/node/2480805)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [7933ac4](http://drupalcode.org/project/drupal.git/commit/7933ac459dd752a07896aa7f8b8073020df7e0fc) | [Issue #2488750 by lalweil: Typo in DatabaseConnection::query](http://drupal.org/node/2488750)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [6df7656](http://drupalcode.org/project/drupal.git/commit/6df765676a35f8f7ed471ef29394d44233f6d61f) | [Issue #2195183 by cleaver, zopa, elgordogrande, sandykadam, jhodgdon, joachim, Eda: document Batch API callbacks as callback implementations](http://drupal.org/node/2195183)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [cb7888f](http://drupalcode.org/project/drupal.git/commit/cb7888f53db00c184dfd947ffae210f9bb737ba1) | [Issue #2325055 by darol100, joshi.rohit100, jhodgdon, Bevan: hook_prepare() example is not useful](http://drupal.org/node/2325055)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [c053db6](http://drupalcode.org/project/drupal.git/commit/c053db68bfbd0278caef0681010d5b3655e260fb) | [Issue #2510674 by er.pushpinderrana, joachim, cilefen: menu_get_item() should say that $path is optional and what the default is](http://drupal.org/node/2510674)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [9c5cd0c](http://drupalcode.org/project/drupal.git/commit/9c5cd0c6064ff569b750277248832405e61f931e) | [Issue #2530872 by orbmantell, TravisCarden: Improve documentation of drupal_get_schema() and drupal_get_schema_unprocessed()](http://drupal.org/node/2530872)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [7a18687](http://drupalcode.org/project/drupal.git/commit/7a18687e5c840a0a1b20acee45c52620aeff1d35) | [Issue #2512582 by dorficus, jhodgdon, joachim: theme_link() parameters missing detail](http://drupal.org/node/2512582)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [29c287b](http://drupalcode.org/project/drupal.git/commit/29c287b54b307dc80993069a9c1bcd96389861c2) | [Issue #2140157 by rbp, jhodgdon, joachim: menu return constants not properly explained - MENU_NOT_FOUND, MENU_ACCESS_DENIED](http://drupal.org/node/2140157)
- [x] | https://github.com/backdrop/backdrop/pull/1177 | [d1bef53](http://drupalcode.org/project/drupal.git/commit/d1bef535d728de708795b0469f62358f65b4fa42) | [Issue #2538158 by joyceg: Clarify in which file hook_modules_installed should be implemented](http://drupal.org/node/2538158)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [35d6361](http://drupalcode.org/project/drupal.git/commit/35d6361b0890a9b6ae6ba17e6f1816aaab981773) | [Issue #2550219 by Pravin Ajaaz, jhodgdon, Anybody: hook_user_cancel_methods_alter() should say 'access' rather than '#access'](http://drupal.org/node/2550219)
- [x] | N/A | [eea00f9](http://drupalcode.org/project/drupal.git/commit/eea00f936e9f7360f2490da6633a396395e817c1) | [Issue #1842528 by cferthorney, owenpm3, jhodgdon: description of  hook_user_categories() is incorrect](http://drupal.org/node/1842528)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [e7d67c7](http://drupalcode.org/project/drupal.git/commit/e7d67c7258c8b3b5e14d81371b3285002c28e643) | [Issue #2549879 by cbiggins, cilefen: Small grammatical error in bootstrap.inc](http://drupal.org/node/2549879)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [8b0f1c7](http://drupalcode.org/project/drupal.git/commit/8b0f1c71c519acc70617faf836336014af925cb7) | [Issue #2115737 by darol100, owenpm3, rhuffstedtler, andythomnz, jemandy, ijf8090, zealfire, er.pushpinderrana, jhodgdon, corbacho, spitcher, abenamer, holingpoon, ay1n: Make the text in modules, themes, and profiles README.txt files more user-friendly](http://drupal.org/node/2115737)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [7ec9916](http://drupalcode.org/project/drupal.git/commit/7ec991628cec7dfd56e162bf5ca65ae214c46c38) | [Issue #2393569 by talhaparacha, vbouchet: document which of hook_entity_info() 'entity keys' get filled in and what the defaults are](http://drupal.org/node/2393569)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [5d6340b](http://drupalcode.org/project/drupal.git/commit/5d6340b7e3e9b8e4038da4ddc13e92b01a165ba0) | [Issue #911352 by Liam Morland, Sylvain Lecoy, Joe Murray, Crell: Document that foreign keys may not be used by all drivers](http://drupal.org/node/911352)
- [x] | N/A | [bc9cd7d](http://drupalcode.org/project/drupal.git/commit/bc9cd7d58181d0fb6c63680ec7fca05a1ec42962) | [Issue #2583743 by jcnventura: Correct required version of SQLite in INSTALL.txt](http://drupal.org/node/2583743)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [29035c8](http://drupalcode.org/project/drupal.git/commit/29035c844a54cb894fc24b84be65065b2a41c85a) | [Issue #1816008 by Kuldip Gohil, cam8001, jhodgdon, peterx: drupal_cron_run() @return parameter documentation incorrect, should specify that the function returns TRUE or FALSE](http://drupal.org/node/1816008)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [36e2726](http://drupalcode.org/project/drupal.git/commit/36e272668176d98460c0ca572fcf14c173015500) | [Issue #2579625 by laurencemercer: Typo in file_validate_image_resolution() doc](http://drupal.org/node/2579625)
- [x] | https://github.com/backdrop/backdrop/pull/1179 | [??] 
(http://drupalcode.org/project/drupal.git/commit/405e86103c4aaf258b412699c15c1812f1dd0ae2) | [Issue #1862250 by amanire, Ivan Zugec, Novitsh, joates, sdstyles, yoroy, joshi.rohit100, acabouet, rpayanm, klonos, dahousecat, Daniel_Rose, HeimdallJHM, cluther, vineet.osscube, joachim, Stalski, Bojhan, chris_h: The "Trim length" format description is confusing/not clear to Drupal newcomers](http://drupal.org/node/1862250)

---

git log 731dfac.. --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"

I couldn't figure out how to get the `nid`s in there; i'm not as cool as @jenlampton :bow: 

UPDATE: NIDs added. :smile:

**Comment by quicksketch** [comment]
Thanks @serundeputy!

> I couldn't figure out how to get the `nid`s in there; i'm not as cool as @jenlampton :bow: 

I use this regex in Sublime Text:

Find: `(.*?Issue #)(\d+)(.*?)/node/(.*)`
Replace: `$1$2$3/node/$2$4`

**Comment by klonos** [comment]
Setting the milestone so that this issue does not fall off of our radar for the next release. If we cannot get everything ported, we can always push to the 1.2.4 :wink:

**Comment by jenlampton** [comment]
I think I got all the relevant ones :)

**Comment by quicksketch** [comment]
>  Issue #2538640 by rrrob, dawehner: Add theme_debug to settings.php. 

In Backdrop, `theme_debug` is a config-stored value in `system.core.json`, so putting this in settings.php won't work. We have an issue to add support for theme_debug in devel.module: https://github.com/backdrop-contrib/devel/issues/4. As such I skipped this issue when merging @jenlampton's PRs.

**Comment by quicksketch** [comment]
> backdrop/backdrop#1179 | 8b0f1c7 | Issue #2115737 by darol100, owenpm3, rhuffstedtler, andythomnz, jemandy, ijf8090, zealfire, er.pushpinderrana, jhodgdon, corbacho, spitcher, abenamer, holingpoon, ay1n: Make the text in modules, themes, and profiles README.txt files more user-friendly

I found some inconsistencies here in the README.md files that were added. We don't support `sites/all/*` directories at all. I committed a docs follow-up at https://github.com/backdrop/backdrop/commit/7d20f3033e3d075373422b44c44d44bf620a47d6.

**Comment by quicksketch** [comment]
That's all of them! Thanks @jenlampton for totally rocking these!!
