### ISSUE TITLE
Administration UI elements that need a design review

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#139]
r5yn in the Drupal queue has done some amazing work on making a new consistent UI for the Seven theme. We should work on doing the same work for Backdrop CMS. 

We should use the list below as list of things we should evaluate. Do they need a design update?  If so, let's incorporate those changes into our styleguide, and go from there.
- [x] https://github.com/backdrop/backdrop-issues/issues/221 | [the installer](https://drupal.org/node/1337554)
- [x] [System icons](https://drupal.org/node/2083947)
- [x] [Vertical tabs](https://drupal.org/node/1989488)
- [x] [Messages](https://drupal.org/node/1986408)
- [x] [Progress Bar](https://drupal.org/node/1989480)
- [x] [Pager](https://drupal.org/node/2016867)
- [x] [Tabs](https://drupal.org/node/1490402)
- [x] [Recent log messages](https://drupal.org/node/2070323)
- [x] [Tables](https://drupal.org/node/1986400)
- [x] [Buttons](https://drupal.org/node/1986074)
- [x] [Throbber](https://www.drupal.org/node/1974928)
- [x] [Image Fields](https://drupal.org/node/2115469)
- [x] [File Fields](https://drupal.org/node/2113931)
- [x] [Textfields & Textareas](https://drupal.org/node/1986418)
- [x] https://github.com/backdrop/backdrop-issues/issues/293 | [Password strength indicator](https://drupal.org/node/2247049)
- [x] [Dropbuttons](https://drupal.org/node/1989470)
- [x] [Font](https://drupal.org/node/1986082)
- [x] [Select elements](https://drupal.org/node/2207391)
- [x] https://github.com/backdrop/backdrop-issues/issues/485 | [Status report](https://drupal.org/node/665790)
- [x] https://github.com/backdrop/backdrop-issues/issues/2631 | [Ckeditor skin](https://drupal.org/node/2161699)
- [x] https://github.com/backdrop/backdrop-issues/issues/930 | [Views](https://drupal.org/node/2022297)
- [x] https://github.com/backdrop/backdrop-issues/issues/990 | [Admin navigation lists](https://drupal.org/node/2016875)
- [x] https://github.com/backdrop/backdrop-issues/issues/991 | [Updater](https://drupal.org/node/2169765)
- [x] https://github.com/backdrop/backdrop-issues/issues/992 | [Contextual links](https://drupal.org/node/2078803)
- [ ] https://github.com/backdrop/backdrop-issues/issues/993 | [Modal dialog](https://drupal.org/node/2113911)
- [ ] https://github.com/backdrop/backdrop-issues/issues/994 | [Search/filter component](https://drupal.org/node/2160545)

These issues collected from [d.o](https://drupal.org/project/issues/search/drupal?text=&assigned=&submitted=&project_issue_followers=&issue_tags_op=%3D&issue_tags=styleguide)
The main D8 issue is at: https://drupal.org/node/1986434

**Comment by jenlampton** [comment]
Just an FYI that we are likely to have our own style guide changes based on the style guide we are developing over at https://github.com/backdrop-ops/styleguide.  They may or may not map one-to-one with the changes that went into Drupal 8.

**Comment by docwilmot** [comment]
Heres a soapbox moment:
The way I see it we dont have *an* admin theme, we have a default admin theme - Seven.
Wordpress requires effort to change the admin theme; Joomla is easier, but their admin theme requires lots of customization. With Backdrop/Drupal though, changing the admin theme is easy as pie, and really, in my experience, *any* theme "looks" good as an admin theme. Some page elements may not work as well (tables and buttons for eg), but everything works.
So to get to the point, this should not be an issue for "admin theme Style Guide changes" but "Seven style guide changes". An issue for "admin theme Style Guide" would be something which gives advice on *what to consider when designing an admin theme*. For e.g.:
* Use full width - because XX element breaks with narrow screens"
* Include tabledrag.js - because XXX"
* Buttons must be XX width because mobile
* etc.

Thats what our "Admin Style Guide" should be, and Seven should be the prototype theme for these recommendations.

**Comment by jenlampton** [comment]
I agree with most of that (only we should remove Seven and have these style guide changes applied to whatever we decide to call our new admin theme :). I would like to mention though, that if we do a good enough job with our default admin theme - people may not change it.

Back in Drupal 6 every site I built had it's own admin theme.  These days, an admin theme is a nice-to-have because most of the time people can make do with Seven. 

When that happens, I'd also like Backdrop's admin to have Backdrop branding, so that it feels distinctly different from anything else.

**Comment by jenlampton** [comment]
I'm stealing this issue back.... It's now just a list of things we should review and see if we need a change.  @dariusgarza once you review the element go ahead and check the box.  Don't worry about the #xx since we may not have issues for all these things in Backdrop, they may all end up getting all fixed at once :)

**Comment by dariusgarza** [comment]
#364 Icon font issue - 

The Free Software Foundation says that it's ok to distribute fonts with OFL license, such as font awesome alongside GPL software packages. 

Here's snippet from a thread about this:

> 
Question: 1.2 Can the fonts be included with Free/Libre and Open
Source Software collections such as GNU/Linux and BSD distributions
and repositories?

> Answer: Yes! Fonts licensed under the OFL can be freely included
alongside other software under FLOSS (Free/Libre and Open Source
Software) licenses. Since fonts are typically aggregated with, not
merged into, existing software, there is little need to be
concerned about incompatibility with existing software licenses.
You may also repackage the fonts and the accompanying components in
a .rpm or .deb package (or other similar packaging formats or
installers) and include them in distribution CD/DVDs and online
repositories. (Also see section 5.9 about rebuilding from source.)
It is OK to distribute fonts licensed under the terms of the SIL OFL 1.1alongside a GPL licensed work. What we mean by "alongside" is that the font and
the program would be considered "separate works" under the terms of the GNU GPL,
because they aren't combined in any way, but simply aggregated. It is often the case
that a program (such as a word processor) can make use of makes use of a particular
font without the font being considered part of the Program or the font and program
being considered a single combined work.

full post: https://github.com/FortAwesome/Font-Awesome/issues/1124

**Comment by dariusgarza** [comment]
Seems like the only issue that's open without an #xx is the icon font
one....but it's a doozy ;)

**Comment by jenlampton** [comment]
yeah licensing isn't an issue for backdrop, I think it's just depending on an external library that's an issue, but that's why we have the other issue to debate it.  @dariusgarza  can you do a quick design review of all the items in the list, and check the boxes if either 1) we've redesigned it in the new styleguide or 2) the current style is good enough as-is? If you don't know what something is or don't know where to find it add a note here and we can steer you it the right direction.

**Comment by olafgrabienski** [comment]
Added a link to the CKEditor skin checklist item. (https://github.com/backdrop/backdrop-issues/issues/2631)
