### ISSUE TITLE
[META] Blocks Blocks Blocks

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1427]
Meta issue to help keep track of all the block related issues and initiatives, including converting the existing custom blocks into fieldable entities and creating a new type of custom text block that can be added to layouts and saved in config.

Issues for implementing content blocks and custom blocks:
- [x] Make reusable blocks into stand-alone blocks 
- [x] #100 ~~Add fieldable, reusable blocks system~~ Add a system of page-less nodes
- [x] #1099 Add a custom [text] block
- [ ] #1277 [META] [UX] Improve the overall creation and placement of custom blocks experience.
- [x] #1428 Export reusable custom blocks to configuration 
- [x] #1515 Make stand-alone blocks into reusable blocks
- [ ] #3995 [WP][UX] Dashboard: Collapsible blocks 
- [ ] #3996 [WP][UX] Dashboard: Dismissible blocks

Issues around adding blocks to layouts:
- [x] #778 ~~[UX] Move node/add to content/add so additional entities like blocks can be listed there~~ Nixed per #1428.
- [x] #1276 ~~Move custom block list to admin/content/block~~ Nixed per #1428.
- [ ] #1277 [UX] Improve the overall creation and placement of custom blocks experience
- [ ] #1360 [UX] Link to the Layouts admin page from the Custom blocks admin page.

Issues around block titles
- [ ] #692 [UX] Make block titles required and allow them to be hidden.
- [ ] #1522 [UX] Move 'Admin label' field below others on Add block form
- [ ] #1889 [UX] *Always* include the "View: [view_name]: [block_display_name]" as the default admin label for blocks provided by views.
- [ ] #2288 [UX] Replace the default description of custom blocks with an excerpt from the block content.
- [ ] #2483 [UX] Consider replacing the block title type drop-down with an always required (and unique) block title field.
- [x] #2723 Change where layouts obtains the title and description for a views block.
- [ ] #3916 [UX] Blocks: Make the "Custom title" field required.
- [x] #4558 [UX] Allow *all* blocks to have an admin label

Other block-related issues:
- [ ] #198 Move menu blocks into menu module (out of system.module)
- [ ] #212 Remove the block cache from Backdrop
- [x] #449 Create a list of blocks and the modules that provide them
- [x] #570 Automatically remove blocks from layouts when a module is uninstalled
- [x] #796 Convert page template elements into movable layout blocks
- [x] #845 Add Menu Block features to core (feature parity with D8).
- [x] #1076 Add ability to add "existing node" to a layout 
- [x] #1100 Add blocks for adding individual fields from entities
- [x] #1228 In Dynamic block it adds unnecessary classes
- [x] #1280 Allow Non-Region Layout UI regions
- [x] #1340 [UX] Rename labels in add block page?
- [x] #1373 Image files uploaded through custom block wysiwyg are removed by garbage collection 
- [ ] #2254 [UX] Prefix all menu block admin labels with "Menu:"
- [ ] #2640 [UX] Make it clear in the manage blocks UI that title-only custom blocks without content will not be rendered.
- [ ] #2667 [DX] the CSS class block-layout-custom-block disappears when a block becomes reusable
- [x] #3994 [UX][WP] Dashboard block: Welcome to Backdrop CMS
- [x] #5248 [UX] Create interface to organize Custom Blocks
- [x] #6773 
- [ ] #6622 
- [x] #6531 
- [ ] #2320

**Comment by quicksketch** [comment]
:+1: Thanks for making this meta @mikemccaffrey.
