### ISSUE TITLE
[META] Convert listings to Views

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#151]
We should convert the core listings into views.  Converting the following lists to views requires:
1) Click together an identical view in Backdrop. 
2) Add it's config file to the appropriate module.
3) Provide an upgrade path for those D7 sites that were using the non-view alternative.
### Conversions

Pages:
- [ ] #162 | Convert /node to a view (converted to a layout + a default view)
- [ ] #145 | Convert /taxonomy/term/% to a view
- [ ] #669 | Remove the settings for RSS

Blocks:
- [ ] #146 | Convert "Recent content" block to a View in comment module
- [ ] #330 | Convert "Recent comments" block to a View in comment module
- [x] #147 | Remove "Who's new" block from user module
- [x] #148 | Remove "Who's online" block from user module

Administrative pages:
- [x] #149 | Convert admin/people with a View in user module
- [x] #150 | Convert admin/content to a View in node module
- [ ] #549 | Convert admin/content/comments to a View in comment module
- [ ] #3735 | Convert admin/content/book to a View in book module

Other things:
- [ ] #547 | Remove views-more.tpl.php (use theme_more_link instead)

### Upgrade paths

Providing an upgrade path is not necessarily a novice task, but the code examples below should get you close.  Please note, the code below has not been tested and is here for reference purposes only :)

1) Write an update hook for the appropriate module in it's .install file.

2) Assemble the data needed for the view.
- read in the values of the config file for the view
- json_decode so you get a PHP array
- var dump the contents of the PHP array
- copy/paste this array and hard code it as `$data`.

```
// Remove below this line after the array is generated.
$file = file_get_contents('path/to/views.view.whatever.json');
$view = json_decode($file);
print backdrop_var_export($view);
// Remove above this line after the array is generated.
$data = array(
  'hardcoded' => 'stuff goes here',
);
```

3) Check the associated variable settings for the view (if there are any)
- if there aren't any, or if they aren't set, do nothing.
- if they are set, update the appropriate parts of the `$data` array.
- if the display is a block, also check if the block was in use. If so, make sure the enabled part of `$data` is set to TRUE.

4) Save the view to config.

```
// Save the view as config.
$config = config('views.view.'. $machine_name);
$config->setData($data);
$config->save();
```

5) delete associated variables, if any exist.

```
update_variable_del('whatever');
```
### Related

Relevant issues needed for some conversions:
- [x] #143 | Dropbutton Handler
- [x] #142 | Implement "Simple" Views Bulk Operations (VBO)

Relevant Drupal.org issue: [[Meta] Convert core listings to Views](https://drupal.org/node/1823450)

**Comment by tarekdj** [comment]
@quicksketch it's better to use ``` var_export($view); ``` the output is cleaner than ```var_dump()```.

**Comment by tarekdj** [comment]
@quicksketch I think it's update_variable_del() not variable_del() ?

**Comment by quicksketch** [comment]
> @quicksketch it's better to use var_export($view); the output is cleaner than var_dump().

Thanks! And actually we should use `backdrop_var_export`, as that will format the export according to our own coding standards. Updated the docs.

> @quicksketch I think it's update_variable_del() not variable_del() ?

Also correct. Updated.

**Comment by quicksketch** [comment]
Marked https://github.com/backdrop/backdrop-issues/issues/1101 duplicate of this one.

**Comment by klonos** [comment]
The fact that the "Who's new" and "Who's online" blocks are missing has been brought up on Gitter today. Perhaps we should consider shipping core with a view that includes those 2 blocks?
