### ISSUE TITLE
Merge in changes from Drupal 7.42

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1600]
- [x] | N/A | [405e861](http://drupalcode.org/project/drupal.git/commit/405e86103c4aaf258b412699c15c1812f1dd0ae2) | [Issue #1862250 by amanire, Ivan Zugec, Novitsh, joates, sdstyles, yoroy, joshi.rohit100, acabouet, rpayanm, klonos, dahousecat, Daniel_Rose, HeimdallJHM, cluther, vineet.osscube, joachim, Stalski, Bojhan, chris_h: The "Trim length" format description is confusing/not clear to Drupal newcomers](http://drupal.org/node/1862250)
- [x] | N/A | [e5b9ebb](http://drupalcode.org/project/drupal.git/commit/e5b9ebba1790e85a83053dc492e1be4225e4a916) | [Issue #2411917 by chaunceyt: Fix _block_rehash() performance issue](http://drupal.org/node/2411917)
- [x] | N/A | [bdd6ba5](http://drupalcode.org/project/drupal.git/commit/bdd6ba5a6a2f901a7903491cff66d2a1e43ec76e) | [Issue #2598062 by eiriksm: theme_links contains > 80 character inline comment lines](http://drupal.org/node/2598062)
- [x] | N/A | [c661e1c](http://drupalcode.org/project/drupal.git/commit/c661e1ced49b0db715a3a601c4ba3dfc78fb349d) | [Issue #2601116 by heykarthikwithu: Remove various unused variables from the Poll module](http://drupal.org/node/2601116)
- [x] | https://github.com/backdrop/backdrop/pull/1233 | [111d400](http://drupalcode.org/project/drupal.git/commit/111d400ae9ef36cd2714cf07ea6cf155348ff050) | [Issue #2530652 by da_cloud, jhodgdon, cilefen, marbard: Cannot use the search block again if an error occured in the previous search](http://drupal.org/node/2530652)
- [x] | N/A | [193adfa](http://drupalcode.org/project/drupal.git/commit/193adfa8e386928cfd1e5994c483ad399a7e45a7) | [Issue #2594585 by Xano, dcam: Use entity_uri() when linking to nodes on the admin/content page](http://drupal.org/node/2594585)
- [x] | N/A | [b55c9f9](http://drupalcode.org/project/drupal.git/commit/b55c9f96de9073c8c5f07cc95c83b39d137187ca) | [Issue #1289336 by jthorson, JimmyAx, marcingy, David_Rothstein, no_commit_credit, drumm, matglas86, rooby, xjm, cristiroma, brockfanning, Damien Tournoud: Calling node_view for the same node with multiple view modes on the same page during node preview does not correctly attach fields](http://drupal.org/node/1289336)
- [x] | https://github.com/backdrop/backdrop/pull/1235 | [7126a14](http://drupalcode.org/project/drupal.git/commit/7126a14cbaa320f7250a4cd06b36d8b97c6e1c88) | [Issue #2547691 by snehi, er.pushpinderrana, visabhishek, ipun.amin, edxxu, jhodgdon, cilefen, ttkaminski: Fix documentation typo regarding #theme_wrappers](http://drupal.org/node/2547691)
- [x] | https://github.com/backdrop/backdrop/pull/1236 | [dd3004f](http://drupalcode.org/project/drupal.git/commit/dd3004f88462db00e7bb28c908fd353b249ad99b) | [Issue #2156405 by Everett Zufelt, maximpodorov, rudiedirkx, jygastaud: Remove unnecessary static variable which can cause a Javascript error on user edit pages on multi-step forms.](http://drupal.org/node/2156405)
- [x] | N/A | [d270faa](http://drupalcode.org/project/drupal.git/commit/d270faa4da407450203bfa198202fea915914288) | [Issue #2632284 by eiriksm, brianV: Fix code style issues in block.module](http://drupal.org/node/2632284)
- [x] | https://github.com/backdrop/backdrop/pull/1237 | [27e511b](http://drupalcode.org/project/drupal.git/commit/27e511be2fd829730082dd0e14e2bb2b01915991) | [Issue #2611274 by felribeiro, joachim, joshi.rohit100, anchal29: missing docs for DrupalWebTestCase::xpath() $arguments param](http://drupal.org/node/2611274)
- [x] | https://github.com/backdrop/backdrop/pull/1265 | [e580607](http://drupalcode.org/project/drupal.git/commit/e58060723aaade42413eab197eb43d00a9b7ec15) | [Issue #1414508 by droplet, KimNyholm, mglaman, kid_icarus, David_Rothstein, mgifford, Cottser: update system.tar.inc to latest Archive_Tar (Pear)](http://drupal.org/node/1414508)
- [x] | https://github.com/backdrop/backdrop/pull/1252 | [2551236](http://drupalcode.org/project/drupal.git/commit/25512367f8b371c311454707f85e04776a528236) | [Issue #2599326 by Blanca.Esqueda, David_Rothstein: Fix autocomplete functionality on servers that are not configured to automatically recognize index.php](http://drupal.org/node/2599326)
- [x] | https://github.com/backdrop/backdrop/pull/1238 | [7dfe657](http://drupalcode.org/project/drupal.git/commit/7dfe6574133c527e1509622a0316d787b53da953) | [Issue #2596899 by bburg: Remove unnecessary DISTINCT from node access rebuild query to work around a MySQL bug](http://drupal.org/node/2596899)
- [x] | N/A | [109a6ed](http://drupalcode.org/project/drupal.git/commit/109a6ed98ecf32b21ff1474eb85193fed1cdf1db) | [Issue #2627524 by lokapujya: Change absense to absence in test assertion message](http://drupal.org/node/2627524)
- [x] | N/A | [116f6ec](http://drupalcode.org/project/drupal.git/commit/116f6ec5089bf184d395a670248c41f2a2354169) | [Issue #2619816 by AshwiniPatil: Fix code style problem with array spacing in taxonomy_help()](http://drupal.org/node/2619816)
- [x] | https://github.com/backdrop/backdrop/pull/1264 | [d77ba6e](http://drupalcode.org/project/drupal.git/commit/d77ba6e7a8794aae5f46f3fed728c725b2e24e18) | [Issue #1328014 by eiriksm, superspring, jhedstrom, alexpott, franz, chx, phillamb168: Fix PDOException in the dblog module when saving a link URL with non-standard characters](http://drupal.org/node/1328014)
- [x] | https://github.com/backdrop/backdrop/pull/1240 | [f0b44bd](http://drupalcode.org/project/drupal.git/commit/f0b44bd9934251f383a0dc14920b71a52b40bec6) | [Issue #2251019 by PietM, jhodgdon, mgifford: User wildcard search doesn't work](http://drupal.org/node/2251019)
- [x] | https://github.com/backdrop/backdrop/pull/1252 | [d641314](http://drupalcode.org/project/drupal.git/commit/d641314cc6157d7b164ccc2587f7b9eb4f568c1f) | [Issue #2545480 by gryp, morgantocker, Crell, kevinquillen: Don't use the ANSI SQL mode since it has different meanings for different MySQL versions (and breaks MySQL 5.7 support in Drupal 7)](http://drupal.org/node/2545480)
- [x] | https://github.com/backdrop/backdrop/pull/1241 | [03cbe65](http://drupalcode.org/project/drupal.git/commit/03cbe6517b64b7b22fb1bbcf3e753634d178cb0d) | [Issue #1891228 by eiriksm, logaritmisk, joelpittet, stefan.r, StefanPr, mariancalinro: image_style_deliver can create invalid headers](http://drupal.org/node/1891228)
- [x] | https://github.com/backdrop/backdrop/pull/1252 | [50c9b28](http://drupalcode.org/project/drupal.git/commit/50c9b281548c18f09f03625a7bd41acc296a18c1) | [Issue #1919338 by catch, bradjones1, mpdonadio, David_Rothstein, Cottser, Jalandhar, shnark, das-peter, swentel, bblake, JvE, dewalt, Damien Tournoud, jwilson3: Select widget (from the options module) prone to double encoding](http://drupal.org/node/1919338)
- [x] | https://github.com/backdrop/backdrop/pull/1242 | [f0d5910](http://drupalcode.org/project/drupal.git/commit/f0d59102f528a9c66b1c3355bb6b2ee48f8b0282) | [Issue #1443308 by cilefen, joseph.olstad, mikeytown2, joelpittet, btopro, alexpott, jonhattan, marcingy, stewsnooze, Fabianx, pounard, tstoeckler, penyaskito: Add static cache to module_load_include()](http://drupal.org/node/)
- [x] | https://github.com/backdrop/backdrop/pull/1243 | [dbef1ac](http://drupalcode.org/project/drupal.git/commit/dbef1acd9520dee6c8ee71d7d0f0dd2129cba068) | [Issue #1946090 by pjonckiere, alex-mo, rpayanm: _drupal_wrap_mail_line() does not force-wrap too long words after 996 characters](http://drupal.org/node/1946090)
- [x] | N/A | [aa755ed](http://drupalcode.org/project/drupal.git/commit/aa755ed3763f5aa442c3a399981b7c5d6590f515) | [Issue #2392153 by mparker17, hussainweb, chris.smith, alexpott, dawehner: Disallow composer.json and composer.lock from being indexed](http://drupal.org/node/2392153)
- [x] | https://github.com/backdrop/backdrop/pull/1244 | [11e1856](http://drupalcode.org/project/drupal.git/commit/11e18568f951cb431b0e0e6514767f2516e0d75b) | [Issue #1559506 by finnydobson, JuliaKM, snehi, anil280988, priya.chat, laranajim, jhodgdon, alexpott: Query alter docs need some clarification](http://drupal.org/node/1559506)
- [x] | https://github.com/backdrop/backdrop/pull/1263 | [e6e00e8](http://drupalcode.org/project/drupal.git/commit/e6e00e8444caa3dce647ce46b01256084ce2048c) | [Issue #1191290 by klausi, David_Rothstein, Fabianx: system_cron() should not invoke hook_flush_caches() on every cron run](http://drupal.org/node/1191290)
- [x] | N/A | [70aafba](http://drupalcode.org/project/drupal.git/commit/70aafbab880d9c67b91cb3c18c01b3e13a60df8b) | [Issue #2622012 by walangitan, snehi, Shreya Shetty, rashid_786, joachim, jhodgdon: Fix documentation errors in language_default()](http://drupal.org/node/2622012)
- [x] | https://github.com/backdrop/backdrop/pull/1245 | [98229c4](http://drupalcode.org/project/drupal.git/commit/98229c422aeb43337c8930b03cf651b8660b8c83) | [Issue #2645544 by Liam Morland: Improve documentation for module_disable() and related functions](http://drupal.org/node/2645544)

Complete release notes: https://www.drupal.org/drupal-7.42-release-notes

This list is being compiled by viewing the Git history of Drupal 7 and assembling a list from each commit number. 

For a complete list in this range, use the command 
`git log 12c09ce6..98229c42 --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"`

**Comment by serundeputy** [comment]
>  | #xx | 405e861 | Issue #1862250 by amanire, Ivan Zugec, Novitsh, joates, sdstyles, yoroy, joshi.rohit100, acabouet, rpayanm, klonos, dahousecat, Daniel_Rose, HeimdallJHM, cluther, vineet.osscube, joachim, Stalski, Bojhan, chris_h: The "Trim length" format description is confusing/not clear to Drupal newcomers

@klonos (your D7 issue :smile: ) are you thinking straight up parity with this one?  
here is D7;
<img width="1285" alt="screen shot 2016-02-05 at 6 22 10 pm" src="https://cloud.githubusercontent.com/assets/6763671/12862000/9268c72c-cc35-11e5-99e1-f1d4262541af.png">

**Comment by serundeputy** [comment]
>- [ ] | #xx | [e5b9ebb](http://drupalcode.org/project/drupal.git/commit/e5b9ebba1790e85a83053dc492e1be4225e4a916) | [Issue #2411917 by chaunceyt: Fix _block_rehash() performance issue](http://drupal.org/node/2411917)

I see no evidence of `_block_rehash` in backdrop `1.x`

```
geoff@gspmbp backdrop (1.x) $ grep -rin _block_rehash .
geoff@gspmbp backdrop (1.x) $
```

I think moot; if someone agrees check it off in OP; N.A.

**Comment by serundeputy** [comment]
>- [ ] | #xx | [bdd6ba5](http://drupalcode.org/project/drupal.git/commit/bdd6ba5a6a2f901a7903491cff66d2a1e43ec76e) | [Issue #2598062 by eiriksm: theme_links contains > 80 character inline comment lines](http://drupal.org/node/2598062)

There is just one comment >80 cols in `theme.inc`:

```
*       array(
 *         'data' => array('Cell 1', array('data' => 'Cell 2', 'colspan' => 2)), 'class' => array('funky')
 *       )
 *     );
```
but that is a code example so I'm inclined to let it go ... if some one agrees mark this on NA and check off in OP.

**Comment by serundeputy** [comment]
> - [ ] | #xx | [193adfa](http://drupalcode.org/project/drupal.git/commit/193adfa8e386928cfd1e5994c483ad399a7e45a7) | [Issue #2594585 by Xano, dcam: Use entity_uri() when linking to nodes on the admin/content page](http://drupal.org/node/2594585)

I see no use of `node_admin_nodes` in the backdrop codebase:

```
geoff@gspmbp backdrop (1600/2594585/use_enity_uri_for_node_links) $ grep -rin node_admin_nodes .
geoff@gspmbp backdrop (1600/2594585/use_enity_uri_for_node_links) $
```

I think this one can be checked off as NA.

**Comment by serundeputy** [comment]
>  -[ ] (http://drupalcode.org/project/drupal.git/commit/b55c9f96de9073c8c5f07cc95c83b39d137187ca) | [Issue #1289336 by jthorson, JimmyAx, marcingy, David_Rothstein, no_commit_credit, drumm, matglas86, rooby, xjm, cristiroma, brockfanning, Damien Tournoud: Calling node_view for the same node with multiple view modes on the same page during node preview does not correctly attach fields](http://drupal.org/node/1289336)

Backdrop has no Preview button on `post`s so I think this one is NA and can be checked off.

**Comment by jenlampton** [comment]
Wow @serundeputy  fantastic work :)  I'm going through your NAs now and confirming / checking these last few off.

In the future, as you create a PR can you please replace the `#xx` on each bullet with a link to the PR so they are easy to find? Also, all code review & thoughts about the issue should be added onto the PR and not into the meta issue here (unless of course no PR is necessary).  That way if someone picks up one of those PRs to work on all they need will be in the comment thread there :)

**Comment by jenlampton** [comment]
> #xx | 2551236 | Issue #2599326 by Blanca.Esqueda, David_Rothstein: Fix autocomplete functionality on servers that are not configured to automatically recognize index.php

I think we still need this one. We don't have the profile module so that test doesn't need to be updated, but we can add this other fix in form.inc.

**Comment by jenlampton** [comment]
Great job @serundeputy almost all your NA suggestions were spot-on!  A of your comments about specific issues I moved into various PRs so we could examine them further:
* https://github.com/backdrop/backdrop/pull/1252
* https://github.com/backdrop/backdrop/pull/1253

**Comment by jenlampton** [comment]
It looks like there's maybe one or two #xx's left in the list now. We're almost there!  I took a look at updating system.tar.inc but it may be a doozy. Not sure if you are working on that one or not @serundeputy but let me know if you are so we don't duplicate work.

**Comment by serundeputy** [comment]
Ha! @jenlampton  yeah I looked at it and thought the same thing.
I'm not working on it and would like to focus on redirects, so please have at it.

**Comment by klonos** [comment]
> @klonos (your D7 issue :smile: ) are you thinking straight up parity with this one?
>...
>I think this one might be moot.

Well, we have D7 parity, but not D8...

D7/Backdrop:

> If the summary is not set, the trimmed Body field will be shorter than this character limit.

D8:

> If the summary is not set, the trimmed Body field will end at the last full sentence before this character limit.

I think that the D8 version makes things clearer.

**Comment by quicksketch** [comment]
Looking great here! I merged all the completed PRs and rerolled a few that had minor fails. @serundeputy is finishing up the PR for image style fixes, leaving only the updated TarArchive class issue (https://www.drupal.org/node/1414508). This one has a lot of subjective code in it, notes about differences from D8 and how Drupal deviates from the upstream PEAR version. I'll file a PR for that one with the code-based changes and rewrite the docblocks to be sensible for Backdrop, which won't need the D8 porting notes in it.

**Comment by serundeputy** [comment]
Thanks @quicksketch!
* image styles is completed: https://github.com/backdrop/backdrop/pull/1241


> D8:

> If the summary is not set, the trimmed Body field will end at the last full sentence before this character limit.
> >I think that the D8 version makes things clearer.

@klonos I think we should file a separate issue for this as there are enough moving parts in this meta.

**Comment by quicksketch** [comment]
Great job @serundeputy and @jenlampton! All PRs have now been merged. I double-checked the not-applicable issues and they all don't apply to Backdrop as claimed. So we're all done here. Thanks!
