### ISSUE TITLE
[meta] Convert test variables to the state system

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#163]
In https://github.com/backdrop/backdrop-issues/issues/141, we introduced the state system for storing environment-specific settings that A) don't have a UI and B) aren't ever moved between sites. Testing variables fit into both of these categories, so they can all be converted to use state_set/get() instead of variable_set/get(). Here's a listing of all the testing variables I could locate:
- [x] block_test_content
- [x] entity_cache_test_label
- [x] node_access_test_private
- [x] image_module_test_file_download
- [x] locale_test_domain
- [x] locale_test_content_language_type
- [x] locale_test_language_types
- [x] locale_test_language_negotiation_info
- [x] locale_test_language_negotiation_info_alter
- [x] node_test_node_access_all_uid
- [x] file_test_hook_file_url_alter
- [x] test_verbose_module_hooks
- [x] dependency_test
- [x] dependencies (this variable should be renamed to something more specific)
- [x] update_script_test_requirement_type
- [x] update_test_xml_map
- [x] update_test_system_info
- [x] update_test_update_status
- [x] test_dynamic_access_argument1
- [x] test_dynamic_access_argument2
- [x] views_test_views_data_count
- [x] views_test_schema
- [x] views_test_views_data
- [x] views_test_views_plugins
- [x] test_email_collector https://github.com/backdrop/backdrop/pull/128

For this trivial set of conversions, independent issues shouldn't be necessary. After filing a PR for one (or multiple) of these variables, please update the issue and link to the most current PR next to each item.
