### ISSUE TITLE
[META] [UX] Backdrop First Run UX

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1663]
We're talking about a lot of high level changes to the site builder experience, want to make sure we think of these as a whole and how they work together.
- [x] New theme #1361
- [x] Front page layout #1042
- [ ] Default content with menu items (a switch in install profile to disable this?)
  - [ ] Default content & Blocks
  - [ ] Default views (with Views Responsive Grid features?)
- [ ] Example Theme with all core templates (maybe contrib?)
- [ ] Install Profile for Example Content
- [ ] Getting started module
  - [ ] Tutorials/documentation to go with getting started items
- [x] New layouts in core #698
- [ ] Tour module in core #89
## Current designs we're working with

These could totally change, in case anyone wants to try something different.
### Logged in

![image](https://cloud.githubusercontent.com/assets/5607236/13161958/51abbb88-d66f-11e5-8479-5344b177ccf0.png)
#### Logged in, Get started pane open

![image](https://cloud.githubusercontent.com/assets/5607236/13161476/f415388a-d66b-11e5-8230-4e0e3502f910.png)
### Logged out

![image](https://cloud.githubusercontent.com/assets/5607236/13161484/00095f2c-d66c-11e5-8e1d-e1ecc1bf83cd.png)
#### Logged Out, Login box open

![image](https://cloud.githubusercontent.com/assets/5607236/13161507/32c1e146-d66c-11e5-81ed-ffef74b9646c.png)

**Comment by wesruv** [comment]
Running into an issue while working on this stuff.

The `block-system-header` is a total headache. Being able to have a menu in the same block as the logo, slogan and site name, and having that menu default to the account menu is a nightmare.

From a design perspective, not many people put the account menu next to their logo. That'd be reserved for the main menu.

Even if we defaulted to the main menu, it feels really inconsistent to have a block that kind of has a block inside of it.

I'd much rather have the default config have a block with logo/slogan/site-name, a main menu block, and an account block. Each block would have a single function, have it's own space, and it'd feel more consistent.

Can we update the default install profile to be something more like this and deprecate the menu in block-system-header in v 2?

**Comment by klonos** [comment]
It always seemed kinda funny to me why we have a single, magic "Header" block that includes a bunch of things that could/should be individual blocks themselves. It makes quite a few assumptions that lead to a UX with very limited flexibility when it comes to where people can place/move things.

Having said that, @wesruv you might be interested in #1704

**Comment by wesruv** [comment]
I suuuper want that too!

**Comment by klonos** [comment]
Then please do voice that on that issue :wink:

**Comment by Bojhan** [comment]
One thing I would recommend is not to intermix the "tutorial" part in the actual demo theme. Learning from D6 mistakes here.

If its in the demo theme we know that people 1) get frustrated they lose the steps, 2) are unsure what is part of the system and just part of this demo theme, 3) don't find the actual way to functionality and are only able to do it through links in the demo. 

Ideally you have a tour, or similar concept to expose steps as to where to go.

**Comment by wesruv** [comment]
Thanks for the insight @Bojhan, I think we were on track... I definitely did not have those specific points in mind, and those are some *very* good points.

The plan is to make it a stand alone module, that could be easily disabled/extended/etc. Even talk about making it a to-do list module and this Getting started checklist could be some default config that's part of an install profile (if not the default, we've discussed a tutorial/walkthrough profile).

Point 3 is especially interesting... I think we'll need to do some thinking/testing to make sure we're "teaching how to fish", probably won't get that right on the first try.

**Comment by BWPanda** [comment]
Anything still actionable and relevent here, or should we close?

**Comment by klonos** [comment]
There are still some pretty good ideas here (will need child-issues created for each one of them, as time permits and people have the energy/time to work on them).
