### ISSUE TITLE
[META] CMI conversions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#169]
The basic idea of configuration management is that functionality assembled on a development environment should be able to be deployed on a different (staging or production) environment. The configuration should be stored in version-controlled files and stored with code, rather than being mixed with content in the database.

This issue contains the complete list of all conversions to configuration management. 
### STATES
- [x] https://github.com/backdrop/backdrop-issues/issues/163 | [8337955](http://drupalcode.org/project/drupal.git/commit/8337955d4890b4112fdb62ee1d2855aafe624c04) | [Issue #1175054 by msonnabaum, chx, sun, tim.plunkett, arlinsandbulte, beejeebus: Add a storage (API) for persistent non-configuration state.](http://drupal.org/node/1175054)
### VARIABLES
- [x] https://github.com/backdrop/backdrop-issues/issues/170 | [D8: META Convert all variables to CMI](https://drupal.org/node/1775842)
- [x] https://github.com/backdrop/backdrop-issues/issues/412 | Convert search settings to CMI
### SYSTEMS
- [x] https://github.com/backdrop/backdrop-issues/issues/168 | [D8: Convert Actions to CMI](https://drupal.org/node/1846172)
- [x] https://github.com/backdrop/backdrop-issues/issues/171 | [D8: Convert Nodes types to CMI](https://drupal.org/node/111715)
- [x] https://github.com/backdrop/backdrop-issues/issues/172 | [D8: Convert Text Formats to CMI](https://drupal.org/node/1779026)
- [x] https://github.com/backdrop/backdrop-issues/issues/173 | [D8: Convert Contact categories to CMI](https://drupal.org/node/1588422)
- [x] https://github.com/backdrop/backdrop-issues/issues/174 | [D8: Convert Vocabularies to CMI](https://drupal.org/node/1552396)
- [x] https://github.com/backdrop/backdrop-issues/issues/175 | [D8: Convert Languages to CMI](https://drupal.org/node/1754246)
- [x] https://github.com/backdrop/backdrop-issues/issues/176 | [D8: Convert Menus to CMI](https://drupal.org/node/1814916)
- [x] https://github.com/backdrop/backdrop-issues/issues/177 | [D8: Convert User roles to CMI](https://drupal.org/node/1479454)
- [x] https://github.com/backdrop/backdrop-issues/issues/178 | [D8: Convert Field API to CMI](https://drupal.org/node/1735118)
- [x] https://github.com/backdrop/backdrop/pull/376 | https://github.com/backdrop/backdrop-issues/issues/179 | [D8: Convert Date formats to CMI](https://drupal.org/node/1571632)
- [x] https://github.com/backdrop/backdrop-issues/issues/2 | [D8: Convert Image styles to CMI](https://drupal.org/node/1782244)
### POSTPONED CONVERSIONS (for now)
- [x] #86 | [D8: Convert block instances to CMI](https://drupal.org/node/1871696) (replaced by layouts)
### CMI D8 Issues for review (oldest to newest)
- [x] | #xx | [c16a978](http://drupalcode.org/project/drupal.git/commit/c16a978c2a95854619ae4fb52df3a41f8f958820) | [Issue #1497088 by acrollet: Fixed Empty configuration values should return an empty string instead of an empty array.](http://drupal.org/node/1497088)
- [x] | N/A | [08351fa](http://drupalcode.org/project/drupal.git/commit/08351faac4dff2074a5e473fa23bd337fae5d590) | [Issue #1497132 by alexpott, pcambra, marcingy: Provide a generalised function to update variables from Drupal 7 to Drupal 8's configuration management system.](http://drupal.org/node/1497132)
- [x] | N/A | [7be4a6a](http://drupalcode.org/project/drupal.git/commit/7be4a6abcbc2befc7eb554b0024cf9d7fa2bbb38) | [Issue #1444766 by acrollet, amateescu: Determine method for automatically cleaning up configuration after a module is uninstalled.](http://drupal.org/node/1444766)
- [x] | N/A | [68eecef](http://drupalcode.org/project/drupal.git/commit/68eecef413fed33cfdac787c66309e4bb511b722) | [Issue #1497132 by alexpott, pcambra, marcingy: follow-up for generalized function to update variables from Drupal 7 to Drupal 8's configuration management system.](http://drupal.org/node/1497132)
- [x] | N/A | [1a095dd](http://drupalcode.org/project/drupal.git/commit/1a095dd60231adcff8e895ac9f70105d2a4b8039) | [Issue #1512676 by swentel: Fixed Simpletest doesn't clean up the config directories generated by the configuration .](http://drupal.org/node/1512676)
- [x] | N/A | [86eb32d](http://drupalcode.org/project/drupal.git/commit/86eb32d3e3d05c7c956301bbd14595be63e3a52f) | [Issue #1517138 by marcingy: Fixed Simpletest does not create configuration folder causing test failures.](http://drupal.org/node/1517138)
- [x] | N/A | [7a48959](http://drupalcode.org/project/drupal.git/commit/7a4895992ef3b1da7f636e7fc9ff04ae204e49ab) | [Issue #1466092 by webbykat, damiankloip, Bojhan: Fixed Configuration manager is missing module description.](http://drupal.org/node/1466092)
- [x] | N/A | [5e65498](http://drupalcode.org/project/drupal.git/commit/5e65498a34cb2767aeff1c8af2953074e617b6ed) | [Issue #1517138 by sun: Follow-up for SimpleTest does not create configuration folder causing test failures.](http://drupal.org/node/1517138)
- [x] | N/A | [bb691f6](http://drupalcode.org/project/drupal.git/commit/bb691f62d7c521579837f0853cd5053ec742ace2) | [Issue #1567812 by sun: Remove 'Verified' from configuration class names.](http://drupal.org/node/1567812)
- [x] | https://github.com/backdrop/backdrop/pull/341 | [747e01c](http://drupalcode.org/project/drupal.git/commit/747e01ca532daf15eb7b221f969695db4b9f777c) | [Issue #1493098 by jcisio, pcambra, Pol, wamilton, Rok Žlender, beejeebus: Convert cron settings to configuration system.](http://drupal.org/node/1493098)
- [x] | https://github.com/backdrop/backdrop/pull/344 | [26aaa9f](http://drupalcode.org/project/drupal.git/commit/26aaa9fbde2d3b9aaa0406742e123d45c9d7f6ff) | [Issue #1496462 by acrollet, cosmicdreams, Niklas Fiekas | heyrocker: Convert RSS publishing settings to configuration system.](http://drupal.org/node/1496462)
- [x] | N/A | [b08c8b4](http://drupalcode.org/project/drupal.git/commit/b08c8b478eeb733ea700f871662b10482c7859e1) | [Issue #1464944 by heyrocker, alexpott, David_Rothstein, ksenzee: Fixed Installation of configuration system fails in some cases.](http://drupal.org/node/1464944)
- [x] | N/A | [4f50bc1](http://drupalcode.org/project/drupal.git/commit/4f50bc1c6905314ff47f702b92f2b6d054fa4100) | [Issue #1599554 by sun, dww, effulgentsia: Tutorial/guidelines for how to convert variables into configuration.](http://drupal.org/node/1599554)

For reference, here is the meta issue from [drupal.org](https://drupal.org/node/1802750)
