### ISSUE TITLE
[META][UX] Improve the Find Content (/admin/content) view.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1694]
- [x] #551 | The "Admin Content" title and the "Find content" menu item should be changed to "Manage content".
- [ ] #1695 | Reorder the filter widgets to be consistent with the columns.
- [ ] ??? | Change the "Published" filter "Status" and the options instead of yes/no, be published/unpublished/scheduled (to accommodate for #857).
- [ ] ...

...over in the [d.org issue](https://www.drupal.org/node/2001922), some people suggested the following that we should perhaps consider:
- [ ] ??? | Add an author autocomplete filter
- [ ] ??? | Change the title search filed to be searching in the body as well
