### ISSUE TITLE
META Convert all variables to CMI

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#170]
We will need to convert all of the variables (that aren't now states) into config.

A master list of all variables from Backdrop CMS will be added here, and we should work to eliminate as many as we can in this single issue. Any variables that prove to be particularly tricky can be broken off into their own sub-issues, as identified here.

SUB ISSUES
- [x] | https://github.com/backdrop/backdrop/pull/341 | [f193db2](http://drupalcode.org/project/drupal.git/commit/f193db251f94e8d54b28712d9dc07a89cfa582df) | [\- Patch #1493098 by sun, jcisio, pcambra, Pol, wamilton, Rok Žlender, beejeebus: convert cron settings to configuration system.](http://drupal.org/node/1493098)
- [x]  | https://github.com/backdrop/backdrop/pull/343 | [4b6bdbb](http://drupalcode.org/project/drupal.git/commit/4b6bdbb1ddb8dd7f8a50dcbb574d5f66a93747ae) | [Issue #1496542 by cosmicdreams, sun, chx, vasi1186, aspilicious, alexpott, nadavoid, Pedro Lozano, disasm, andypost | heyrocker: Convert site information to config system.](http://drupal.org/node/1496542)
- [x] | https://github.com/backdrop/backdrop/pull/344 | [48d139a](http://drupalcode.org/project/drupal.git/commit/48d139aed1ecf7764c7d9d03ef76d3e7fca7826c) | [Issue #1496462 by acrollet, sun, cosmicdreams, Niklas Fiekas, aspilicious: convert RSS publishing settings to configuration system.](http://drupal.org/node/1496462)
- [x] | https://github.com/backdrop/backdrop/pull/344 | [1746681](http://drupalcode.org/project/drupal.git/commit/1746681619e6e754a229b7826f619d2415e6865a) | [Issue #1496462 by acrollet, sun, cosmicdreams, Niklas Fiekas, aspilicious: convert RSS publishing settings to configuration system.](http://drupal.org/node/1496462)
- [x] | https://github.com/backdrop/backdrop/pull/345 | [CMI: Convert search settings to configuration system](https://drupal.org/node/1496510)
- [x] | https://github.com/backdrop/backdrop/pull/346 | [cd22464](http://drupalcode.org/project/drupal.git/commit/cd224643ba8c751638c3ff66ead08bdb429db7bf) | [Issue #1496458 by swentel, pcambra, n3or, kbasarab, sun, marcingy: Convert maintenance mode settings to configuration system.](http://drupal.org/node/1496458)
- [x] | #217 | [70f048b](http://drupalcode.org/project/drupal.git/commit/70f048bbe588b6beedad21f94ea6a1a21cd8c818) | [\- Patch #1704530 by alexpott: convert contact module variables to configuration system.](http://drupal.org/node/1704530)
- [x] | https://github.com/backdrop/backdrop/pull/348 | [3ed4690](http://drupalcode.org/project/drupal.git/commit/3ed46905f342d489c80f6ce118310bcbfe833fa4) | [\- Patch #1710512 by n3or: Convert update settings to configuration system.](http://drupal.org/node/1710512)
- [x] | https://github.com/backdrop/backdrop/pull/347 | [7155e01](http://drupalcode.org/project/drupal.git/commit/7155e01f77e58241558259307b52c192d9db3f58) | [\- Patch #1697170 by tobiasb, nick_schuch, adamdicarlo, dagmar: convert menu_configure() to new configuration system.](http://drupal.org/node/1697170)
- [x] | https://github.com/backdrop/backdrop/pull/347 | [96e7984](http://drupalcode.org/project/drupal.git/commit/96e79846a187dd5cfae31240bf1dbf645693c04f) | [\- Patch #1697170 by tobiasb, nick_schuch, adamdicarlo, dagmar: convert menu_configure() to new configuration system.](http://drupal.org/node/1697170)
- [x] | https://github.com/backdrop/backdrop/pull/351 | [ed1d937](http://drupalcode.org/project/drupal.git/commit/ed1d937f56e60afd65e92e32d80c90fc8fd85422) | [Issue #1493108 by marcingy, sun, Mike Wacker, kbasarab, Berdir, Rok Žlender, cosmicdreams, alexpott: Convert logging and error settings to configuration system.](http://drupal.org/node/1493108)
- [x] | https://github.com/backdrop/backdrop/pull/346 | [34573dd](http://drupalcode.org/project/drupal.git/commit/34573dde97d13dc0e4e2fc15f73236671af7c1a4) | [Issue #1496458 by swentel, pcambra, n3or, sun, kbasarab, marcingy, no_commit_credit: convert maintenance mode settings to configuration system.](http://drupal.org/node/1496458)
- [x] | https://github.com/backdrop/backdrop/pull/352 | [7e571b9](http://drupalcode.org/project/drupal.git/commit/7e571b97cfe7ec2033ccc82a572d296862c53306) | [\- Patch #1703164 by chriscalip, kbasarab, no_commit_credit, aspilicious: Fixed Convert book settings to the new configuration system.](http://drupal.org/node/1703164)
- [x] | https://github.com/backdrop/backdrop/pull/353 | [1600511](http://drupalcode.org/project/drupal.git/commit/16005119bcd8a341f3803a595e8216cdb11993a1) | [Issue #1496534 by cosmicdreams, alexpott, aspilicious, kim.pepper, acrollet, dagmar, beejeebus, wizonesolutions | heyrocker: Convert account settings to configuration system.](http://drupal.org/node/1496534)
- [x] | https://github.com/backdrop/backdrop/pull/354 | [5efb185](http://drupalcode.org/project/drupal.git/commit/5efb185fbdf0149702823e5fb4a3daaf240ee843) | [Issue #1705748 by n3or, tim.plunkett, sun, xjm, boombatower: Convert simpletest settings to configuration system.](http://drupal.org/node/1705748)
- [x] | https://github.com/backdrop/backdrop/pull/355 | [83a91f4](http://drupalcode.org/project/drupal.git/commit/83a91f426569a4986abd988f4fffecb558382b14) | [Issue #1757566 by alexpott, aspilicious: Convert user account e-mail templates to configuration system.](http://drupal.org/node/1757566)
- [x] | https://github.com/backdrop/backdrop/pull/356 | [ff4df09](http://drupalcode.org/project/drupal.git/commit/ff4df099d466e94c4dc6b37e8f4684674af52485) | [Issue #1777490 by kim.pepper: convert failed login settings to new configuration system.](http://drupal.org/node/1777490)
- [x] | https://github.com/backdrop/backdrop/pull/357 | [49bb1d9](http://drupalcode.org/project/drupal.git/commit/49bb1d9ad0ed10a970eeebf86154625fe7301bd9) | [Issue #1788084 by andyceo, sun: Convert actions variable(s) to CMI.](http://drupal.org/node/1788084)
- [x] | https://github.com/backdrop/backdrop/pull/358 | [c397029](http://drupalcode.org/project/drupal.git/commit/c3970294554664c6005b95cb4ae74bb6f3a961c4) | [Issue #1804346 by 8thom, aspilicious: Convert authorize variables to config system.](http://drupal.org/node/1804346)
- [x] | #173 | [f63cdc3](http://drupalcode.org/project/drupal.git/commit/f63cdc388b6766d24e7a9a59eff0b129f8814e68) | [Issue #1588422 by andypost, disasm, sun, dawehner, vasi1186, alexpott, tim.plunkett, larowlan, Gábor Hojtsy: Convert contact categories to configuration system.](http://drupal.org/node/1588422)
- [x] | N/A | [9481d3b](http://drupalcode.org/project/drupal.git/commit/9481d3b59ad3d63c1e660d23f8fadee0deeae9b6) | [Issue #1602372 by dawehner: Convert views settings to config.](http://drupal.org/node/1602372)
- [x] | https://github.com/backdrop/backdrop/pull/379 | [18bb815](http://drupalcode.org/project/drupal.git/commit/18bb81596d5c596b88fe0c4ff6897412438c25e3) | [Issue #1705650 by damiankloip, aspilicious: Fixed Convert core variables to the config system.](http://drupal.org/node/1705650)
- [x] | N/A | [0c44c89](http://drupalcode.org/project/drupal.git/commit/0c44c8968667899205d0d736ee18a43fff8f0989) | [Issue #1824712 by cam8001, alexpott: Convert xri_proxy_resolver() variable to CMI config system.](http://drupal.org/node/1824712)
- [x] | https://github.com/backdrop/backdrop/pull/361 | [8deaba4](http://drupalcode.org/project/drupal.git/commit/8deaba40a24436c3b2ecacdfe51c2f1a5a0f4f4e) | [Issue #1714462 by n3or, sun, Gábor Hojtsy: Convert language negotiation settings to configuration system.](http://drupal.org/node/1714462)
- [x] | https://github.com/backdrop/backdrop/pull/359 | [86ef492](http://drupalcode.org/project/drupal.git/commit/86ef4929699b4df48e33149e2f7a9391d58fee51) | [Issue #1829308 by aspilicious: Convert variables in menu.inc to config and state.](http://drupal.org/node/1829308)
- [x] | https://github.com/backdrop/backdrop/pull/359 | [bfee596](http://drupalcode.org/project/drupal.git/commit/bfee59685f198a8792a76df343e23faeb9400f3d) | [Issue #1829308 by aspilicious: Convert variables in menu.inc to config and state.](http://drupal.org/node/1829308)
- [x] | https://github.com/backdrop/backdrop/pull/353/ | [be488fb](http://drupalcode.org/project/drupal.git/commit/be488fb299b21f14560d8642df3344160fffe973) | [Issue #1814558 by LinL: Convert user_password_reset_timeout() variable to use config system.](http://drupal.org/node/1814558)
- [x] | N/A | [a2c97c9](http://drupalcode.org/project/drupal.git/commit/a2c97c9b7f4ae6b842975b21dfc0fe8b5b046ce5) | [Issue #1824768 by vijaycs85: Convert drupal_test_email_collector() variable to CMI system.](https://www.drupal.org/node/1824768)
- [x] | https://github.com/backdrop/backdrop/pull/360 | [0a9ed3f](http://drupalcode.org/project/drupal.git/commit/0a9ed3f86b1db2afc7e0d319141feb5ad7e640d2) | [Issue #1798880 by andyceo, LinL, mtunay: Convert teaser_length() to use configuration system.](http://drupal.org/node/1798880)
- [x] | https://github.com/backdrop/backdrop-issues/issues/416 | [b066678](http://cgit.drupalcode.org/drupal/diff/?id=b0666783f523d078caf50c3b0963e0e9a6e6f2b2) | [Convert "mail_system" variable to config](http://drupal.org/node/1821420)
- [x] | https://github.com/backdrop/backdrop-issues/issues/417 | Use dedicated update functions instead of variable_get/set/del() in update hooks.

For reference, here is the same issue from [drupal.org](https://drupal.org/node/1775842)
