### ISSUE TITLE
[META][DX] CMI: Introduce "export config" links throughout the admin UI that open a modal with the code ready to be copied.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1833]
This came up as an idea in #1788 

As a quick solution in that issue, we introduced "export view" action links in the views UI and had them go to the already existing single config export page (`/admin/config/development/configuration/single/export`) with the proper values for the "Configuration group" and "Configuration name" drop-down menus pre-populated. This issue here is a follow-up to improve on that feature.

The goals of this issue here are:
- [ ] introduce "export config" links in the admin UI for other exportable things:
  - [ ] Configuration
  - [ ] Field instances
  - [ ] Fields
  - [ ] Image styles
  - [ ] Layouts
  - [ ] Menus
  - [ ] Node types
  - [ ] Text formats
  - [ ] User roles
  - [ ] Views
  - [ ] Vocabularies
- [ ] introduce a generic modal to be used when any "export config" link is clicked. Ideas for this modal include:
  - [ ] pre-selecting the entire text ready to be copied
  - [ ] perhaps have a "download code" link that saves the code to a file with the appropriate format/extension (`view_name.view.inc` for example for views).

**Comment by olafgrabienski** [comment]
Closing as duplicate of #2960.
