### ISSUE TITLE
[META][UX] Killer menu features.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1839]
This is a list of UX issues that are related to menus. Implementing these features will make us stand out when compared to Drupal and aim to cause the same awe and respect as layouts.
- [x] #225 | Make menu items translatable in core.
- [ ] #434 | [META][UX] Provide a menu-centric workflow for creating the website structure (à la content_menu).
  - [ ] #422 | [UX] Allow menu items to be created even if no page exists at that path.
- [x] #845 | Add Menu Block features to core (feature parity with D8).
- [ ] #1006 | [UX] Allow bulk-adding/editing vocabulary terms and menu items.
- [ ] #1840 | [UX] Merge Special Menu Items module functionality in core (allow `<nolink>` and `<separator>` menu items).
- [x] #1457 | [UX] Provide responsive drop-down menus out of the box.
- [x] #1841 | Add icons to the Admin Bar
- [ ] #3819 | Allow adding (font-)icons to menu items
- [ ] #3820 | [UX] Layouts: Allow menu "source" to be changed from within any menu block

Not killer-features but resolving annoyances compared to the respective Drupal UX:
- [ ] #475 | [UX] Clean up & simplify the menu administration by merging the "List links" and "Edit menu" operations into a single administration page.
- [ ] #732 | [UX] Allow bulk deleting menu links.
- [x] #1793 | Menu items: Do not replace the menu item path alias with the respective node ID.
- [ ] #1278 | [UX] Remove the menu settings page
- [x] #2007 | [UX] Menus: convert the "Path" text field to an autocomplete field.
- [ ] #3029 | [UX] Add a user-friendly parent menu browser in the content add/edit form.
- [ ] #4465 | Allow limiting access to menu items per-role
- [ ] #4466 | [D9][UX] Remove the weight field from the menu item edit form and the node edit form

Not killer-features per se, but for "marketing purposes":
- [ ] #1842 | [UX] Allow the admin bar to be docked in various sides of the screen (feature parity with D8).

Feel free to add more issues with menu-related feature requests.

**Comment by wesruv** [comment]
Going to help with this, starting with responsive menu out of the box.

**Comment by biolithic** [comment]
Keep in mind void menu exists in contrib

**Comment by klonos** [comment]
@wesruv :+1: ...let me know when you have a sandbox or private repo branch you want testing and feedback for.

@biolithic thanx, I wasn't aware of void_menu. Sounds like its features could/should be merged in special_menu_items:

> Based off of the work done in special_menu_items and menu_firstchild

...I'm particularly interested in this:

> ...The benefit to using this module over special_menu_items for this is that your menus will not require any additional styling to account for the added span tags used by special_menu_items,...

So the issue here IIUC is that special_menu_items adds span tags that make it harder for the menu items provided by it to work out of the box with themes.

> ...and will be W3C valid because every anchor must have an href attribute.

This statement is not true : https://w3c.github.io/html/links.html#links-created-by-a-and-area-elements

> NOTE
> The `href` attribute on `<a>` and `<area>` elements is not required; when those elements do not have `href` attributes they do not create hyperlinks.

**Comment by biolithic** [comment]
I've just used Void Menu module for projects, that's all.

**Comment by klonos** [comment]
Forgot to tick the "drop-down menus out of the box" task of the list 😉
