### ISSUE TITLE
[META] Various other theme system cleanup tasks

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#196]
Various other theme system cleanup tasks are balow.
- [x] https://github.com/backdrop/backdrop/pull/309 | Remove region specific template suggestions for blocks [d.o](https://drupal.org/node/1968360)
- [x] https://github.com/backdrop/backdrop-issues/issues/327 | Rework theme settings to use CMI
- [x] https://github.com/backdrop/backdrop-issues/issues/130 | Remove global theme settings
- [x] https://github.com/backdrop/backdrop-issues/issues/301 | Remove the "ok" css class

**Comment by quicksketch** [comment]
We're out of time to complete this for 1.0.0. The issue for #131 | Make only one theme "active" at a time we need to push to 2.x. #484 | Update all preprocess docblocks "Prepares variables for ..." we can do at any time.
