### ISSUE TITLE
[META] consolidate theme functions and templates

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#197]
There are many similar or related theme functions and template files that should be removed or consolidated.  This here is a list of things we should do for Backdrop (that were either done in D8 or started)
_Master list of all cleanup and notes is in [this google doc.](https://docs.google.com/spreadsheets/d/1qULY4IeKkO6GqjZchkiiMn4xJk-YfN6-XWj4bX6aR0o/edit?usp=sharing)_

### Remove template files
- [ ] https://github.com/backdrop/backdrop-issues/issues/547  | Remove views-more.tpl.php (use theme_more_link instead)
- [x] https://github.com/backdrop/backdrop/pull/257 | Remove region.tpl.php
- [x] https://github.com/backdrop/backdrop-issues/issues/546 | Remove book-all-books-block.tpl.php
- [x] N/A | Remove book-export-html.tpl.php See: https://github.com/backdrop/backdrop-issues/issues/242
- [x] N/A | Remove book-node-export-html.tpl.php See: https://github.com/backdrop/backdrop-issues/issues/242
- [x] N/A | Remove user-picture.tpl.php See related: https://github.com/backdrop/backdrop-issues/issues/243

#### Form element containers
- [ ] #xx | Remove theme_date (call theme_container instead)
- [ ] #xx | Remove theme_textfield (add [theme_input](https://api.drupal.org/api/drupal/core%21includes%21form.inc/function/theme_input/8) and call it instead)
- [ ] #xx | Remove theme_button (call theme_input instead)
- [ ] #xx | Remove theme_checkbox (call theme_input instead)
- [ ] #xx | Remove theme_email (call theme_input instead)
- [ ] #xx | Remove theme_file (call theme_input instead)
- [ ] #xx | Remove theme_hidden (call theme_input instead)
- [ ] #xx | Remove theme_image_button (call theme_input instead)
- [ ] #xx | Remove theme_image_button (call theme_input instead)
- [ ] #xx | Remove theme_password (call theme_input instead)
- [ ] #xx | Remove theme_radio (call theme_input instead)
- [ ] #xx | Remove theme_submit (call theme_input instead)
- [ ] #xx | Remove theme_tel (call theme_input instead)
- [ ] https://github.com/backdrop/backdrop-issues/issues/545 | Make all forms theme suggestions, e.g. form__[form_id] and form--[form-id].tpl.php
- [x] https://github.com/backdrop/backdrop/pull/227 | Remove theme_system_compact_link() entirely. | [d.o](http://drupal.org/node/1833932)
- [x] https://github.com/backdrop/backdrop/pull/229 | Remove theme_book_title_link() use l() instead | [d.o](https://drupal.org/node/1222248)

#### item lists
- [ ] #xx | Remove theme_links() and call theme('item_list__links') instead. | [d.o](http://drupal.org/node/311011)
- [ ] #xx | Remove theme_task_list() and call theme('item_list__tasks') instead. | [d.o](http://drupal.org/node/1222254)
- [ ] #xx | Remove all specific menu link theme functions, use theme_menu() with suggestions instead. | [d.o](http://drupal.org/node/1777332)

#### tables
- [ ] #xx | Remove theme_image_style_list() and call theme('table__image_styles') instead. | [d.o](http://drupal.org/node/2035897)
- [ ] #xx | Remove theme_image_style_effects() and call theme('table__image_styles__effects') instead. | [d.o](http://drupal.org/node/2035903)
- [ ] #xx | Remove theme_book_admin_table and call theme('table__book_admin') instead. | [d.o](http://drupal.org/node/2035905)

#### pages
- [ ] #xx | Remove theme_maintenance_page and call theme('page__maintenance') instead.

## Completed
- [x] https://github.com/backdrop/backdrop/pull/324 | Remove theme_checkboxes (call theme_container instead)  | [d.o](http://drupal.org/node/2041845)
- [x] https://github.com/backdrop/backdrop/pull/324 | Remove theme_radios  (call theme_container instead)  | [d.o](http://drupal.org/node/2041825)

**Comment by jenlampton** [comment]
I have added a change record for theme_checkboxes and theme_radios: https://docs.backdropcms.org/change-records/functions-theme_radios-and-theme_checkboxes-have-been-removed
