### ISSUE TITLE
[META] Install profiles

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1998]
Install profiles are discussed in the following issues:

- [x] #156 Make the "Minimal" install profile hidden
- [ ] #519 Create placeholder content when running standard install profile
- [ ] #632 Hide "Choose profile" step unless there's a custom profile installed?
- [ ] #1591 Allow install profiles to be run after site creation

**Comment by klonos** [comment]
@mikemccaffrey So, if I get this right, with the various issues filed recently, you are proposing as a general plan to:

a) make the minimal profile (its tasks) be the default thing without providing any options (#1999)
b) bring back the profile selection page during installation (#2000)
c) other (optional) profiles will be adding things on top of (what used to be) the minimal profile
d) we make it possible to run profiles after installation (#1591)

Right?

a) makes total sense to me. It would include only whatever is *absolutely necessary* in order to have a minimal CMS. The hard thing is to ensure that nothing "surplus" gets in. We need to be very strict about this. This would be what people used to call "mini core" in drupal-land I guess.

b) would increase the installation time (at least the perceived installation time). Perhaps in combination with d) we could have it be the very last page. That way, it won't be part of the installer. I'd be more of a "Backdrop is installed! What do you want to do with it?" thing.

So in essence:

**installation** (db, credentials etc) -> **basic configuration** (profile selection) -> **site building** (adding modules, creating content types, layouts etc and general tweaking via the admin UI)

...with the profile selection being an optional thing.

I think I like this approach. It will differentiate us from Drupal + improve the UX I think.

May I propose one thing though: we should try to make profiles be something like feature sets or site recipes (like blog, forum, eshop, CRM etc) and also allow multiple of them to be selected. Overlapping things between profiles (like modules to be enabled) would be queued and executed only once.

**Comment by klonos** [comment]
...ticked off #519 from the list. Added #2555
