### ISSUE TITLE
[META] HTML5 for Backdrop

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#200]
We need to triple check that we have all the HTML5 hotness that's in Drupal 8. 

Someone will need to review each issue mentioned in the following d.o issues and check the date the patch was committed to D8.  If it was before our fork date (Feb 29th, 2012) then we have the change, and nothing else needs to be done.  If it was committed after that date, however, then we'll need to include it here to be sure we get the changes.
### General HTML5 changes

(http://drupalcode.org/project/drupal.git/commit/ae5cc6f8f40604987274799978e065bd5820d07b) | [d.o](https://drupal.org/node/2067915)
(http://drupalcode.org/project/drupal.git/commit/8fd2b4779ec83c3e44a8caac65300b96e3a52ab8) | [d.o](http://drupal.org/node/625958)
- [x] https://github.com/backdrop/backdrop/pull/386 | Issue #1468582 by Schnitzel, lewisnyman, dcmouyard, alanburke, tstoeckler, edward_or, janusman: Add mobile friendly meta tags to the html.tpl.php. | [bf6a8a1a](http://drupalcode.org/project/drupal.git/commit/bf6a8a1a8e991c33dd770a0e83b83ee34c6b5e20) | [d.o](https://drupal.org/node/1468582g)
- [x] N/A | Issue #1717090 by BarisW, barraponto: Fixed Remove the http-equiv='cleartype' meta tag. | [94143f22](http://drupalcode.org/project/drupal.git/commit/94143f223ae648f336b99627e0582650affe9b82) | [d.o](https://drupal.org/node/1717090)
- [x] https://github.com/backdrop/backdrop/pull/222 | Issue #1974422 by ericduran: Update to latest html5shiv library. | [6f2f1b7](http://drupalcode.org/project/drupal.git/commit/6f2f1b73f2d1e2b00e5e964e2143ae5f95f1f322) | [d.o](http://drupal.org/node/1974422)
- [x] https://github.com/backdrop/backdrop/pull/221 | Issue #1943142 by jessebeach: Add the main element to the list of HTML5 elements that get set to display block. | [12df490](http://drupalcode.org/project/drupal.git/commit/12df490cbde04fd089f49ba3c767174a317621fd) | [d.o](http://drupal.org/node/1943142)
- [x] N/A | Issue #1436814 by gary4gar, webchick: switch to HTML5 for Fast 404 'Not found' pages. | [a2ee8c1](http://drupalcode.org/project/drupal.git/commit/a2ee8c1e4055399d9d4a308f860b740a86dde402) | [d.o](http://drupal.org/node/1436814)
- [x] N/A | Refactor block-admin-display-form.tpl.php | [d.o](https://drupal.org/node/1221718)
- [x] N/A | add the 'browsers' option to drupal_add_js() | [d.o](https://drupal.org/node/865536)
- [x] N/A | Add a theme_datetime() function to consistently theme dates and datetimes | [d.o](https://drupal.org/node/1183250)
- [x] N/A | Add mobile friendly meta tags to the html.tpl.php [d.o](https://drupal.org/node/1468582)
### Re-factor templates / theme functions to use HTML5 elements

Review <a href="https://drupal.org/node/1193054">this list</a>
- [x] https://github.com/backdrop/backdrop/pull/219 | Convert page.tpl.php & maintenance-page.tpl.php to HTML5 | [cc7c70e](http://drupalcode.org/project/drupal.git/commit/cc7c70e) | [d.o](https://drupal.org/node/2011578)
- [x] https://github.com/backdrop/backdrop/pull/213 | Issue #1190206 by cosmicdreams: Convert taxonomy-term.tpl.php to HTML5. | [d.o](https://drupal.org/node/1190206)
- [x] N/A | Convert book-all-books-block.tpl.php to HTML5 | [d.o](https://drupal.org/node/1189832)
- [x] N/A | Convert book-export-html.tpl.php to HTML5 | [d.o](https://drupal.org/node/1189834)
- [x] N/A | Convert book-navigation.tpl.php to HTML5 | [d.o](https://drupal.org/node/1189828)
- [x] N/A | Convert book-node-export-html.tpl.php to HTML5 | [d.o](https://drupal.org/node/1221724)
- [x] N/A | Convert comment.tpl.php to HTML5 | [d.o](https://drupal.org/node/1189816)
- [x] N/A | Convert comment-wrapper.tpl.php to HTML5 | [d.o](https://drupal.org/node/1229434)
- [x] N/A | Convert html.tpl.php to HTML5 | [d.o](https://drupal.org/node/1077566)
- [x] N/A | Convert node.tpl.php to HTML5 | [d.o](https://drupal.org/node/1077602)
- [x] N/A | Convert user-profile.tpl.php to HTML5 | [d.o](https://drupal.org/node/1190214)
### Themes
- [x] https://github.com/backdrop/backdrop/pull/218 | Issue #1179764 by mjohnq3, mbrett5062, tim.plunkett: Convert Bartik to HTML5. | [d.o](http://drupal.org/node/1179764)
- [x] https://github.com/backdrop/backdrop/pull/213 | Issue #1913692 by mgifford: Convert Seven to HTML5. | [d.o](http://drupal.org/node/1913692)
### Form API support for new HTML5 elements

Review <a href="https://drupal.org/node/1183606">this list</a>
- [x] https://github.com/backdrop/backdrop/pull/247 | Issue #1174640 by Niklas Fiekas, aspilicious, ericduran, cosmicdreams, amateescu, tim.plunkett: Added new HTML5 FAPI element: number. | [d.o](http://drupal.org/node/1174640)
- [x] https://github.com/backdrop/backdrop/pull/247 | Issue #1174646 by aspilicious, ericduran, Niklas Fiekas: Added new HTML5 FAPI element: range. | [d.o](http://drupal.org/node/1174646)
- [x] https://github.com/backdrop/backdrop/pull/247 | Issue #1519720 by Niklas Fiekas: Remove element_validate_integer() and element_validate_integer_positive() in favor of the new number element type. | [d.o](http://drupal.org/node/1519720)
- [x] https://github.com/backdrop/backdrop/pull/247 | Issue #1519852 by Niklas Fiekas: Use the new number FAPI element for the number field textfield widget. | [1fd8114](http://drupalcode.org/project/drupal.git/commit/1fd8114910135ae93a28fe47ee8b5b134dbf4346) | [d.o](http://drupal.org/node/1519852)
- [x] https://github.com/backdrop/backdrop/pull/247 | Issue #1527988 by Niklas Fiekas: Fixed Missing or legacy number validation.[d.o] | [055716f](http://drupalcode.org/project/drupal.git/commit/055716fe39abffc39612fe06b815f87e068fca65) | (http://drupal.org/node/1527988)
- [x] https://github.com/backdrop/backdrop/pull/242 | Issue #1174628 by Dave Reid, Niklas Fiekas, ericduran, Jacine: Add new HTML5 FAPI element: search. | [d.o](http://drupal.org/node/1174628)
- [x] https://github.com/backdrop/backdrop/pull/308 | Issue #1445224 by Niklas Fiekas, sun, Tor Arne Thune: Add new HTML5 FAPI element: color. | [d.o](http://drupal.org/node/1445224)
- [x] https://github.com/backdrop/backdrop/pull/211 | Issue #1174630 by Dave Reid, Niklas Fiekas, ericduran, xjm: Added new HTML5 FAPI element: url. | [d.o](http://drupal.org/node/1174630)
- [x] N/A  | Issue #1174620 by Niklas Fiekas, Dave Reid, ericduran: Added new HTML5 FAPI element: email. | [d.o](http://drupal.org/node/1174620)
- [x] https://github.com/backdrop/backdrop/pull/228 | Issue #1540174 by Niklas Fiekas, attiks: Fixed Some attributes not allowed for the new HTML5 input elements. | [3e88616](http://drupalcode.org/project/drupal.git/commit/3e8861682a4ae6b2bd1129473104be37b63695ac) | [d.o](http://drupal.org/node/1540174)

RELATED ISSUES
- Detials vs Fieldsets: https://github.com/backdrop/backdrop-issues/issues/324
- HTML5 #required https://github.com/backdrop/backdrop-issues/issues/325
- More HTML5 elements for dates https://github.com/backdrop/backdrop-issues/issues/326
