### ISSUE TITLE
Drupal 7.44 to 7.50 commits: crossport or mark as NA.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#2013]
- [x] | NA | [6b6bc1b](http://drupalcode.org/project/drupal.git/commit/6b6bc1b7fd69de28c490c976101d255b3f79d409) | [Issue #2678822 by DamienMcKenna, David_Rothstein, stefan.r: Drupal 7.43 regression: When an anonymous user submits a form with an un-uploaded file that leads to a validation error, the file is lost on the next correct submission](http://drupal.org/node/2678822)
- [x] | https://github.com/backdrop/backdrop/pull/1461 | [c273ce5](http://drupalcode.org/project/drupal.git/commit/c273ce5f4e3b041d6d5761ec1ba9dce6aa9c2542) | [Issue #2418209 by chintan.vyas, lucastockmann, jacob.embree: Replace user facing strings that use drupal.org as example of an external url](http://drupal.org/node/2418209)
- [x] | https://github.com/backdrop/backdrop/pull/1460 | [aa232a2](http://drupalcode.org/project/drupal.git/commit/aa232a21eba0139ee62c6172e6a7790f80c8d100) | [Issue #2470145 by David_Rothstein, rbmboogie, tbradbury, johnpicozzi, talhaparacha, ifrik, darol100: Fix text for update manager checkbox for disabled extensions](http://drupal.org/node/2470145)
- [x] | https://github.com/backdrop/backdrop/pull/1486 | [a10a1cf](http://drupalcode.org/project/drupal.git/commit/a10a1cfc3f0257debfedd72600bed17d50de5fc9) | [Issue #2640344 by rafaolf, mohit_aghera, GrigoriuNicolae, jhodgdon: Document how to make hook_search_info() titles translatable](http://drupal.org/node/2640344)
- [x] | https://github.com/backdrop/backdrop/pull/1487 | [c3bf748](http://drupalcode.org/project/drupal.git/commit/c3bf7484b38a1821c1631033217c4290a591c0de) | [Issue #611294 by swentel, klausi, David_Rothstein, tsphethean, jenlampton, attiks, yched, sun, benjy, dcam: Added a new "administer fields" permission for trusted users to use the field UI.](http://drupal.org/node/611294)
- [x] | https://github.com/backdrop/backdrop/pull/1885 | https://github.com/backdrop/backdrop/pull/1466  | [ebd9325](http://drupalcode.org/project/drupal.git/commit/ebd9325ec7f3d2e7b401b2af7802433c13fc7566) | [Issue #2514136 by pwolanin, David_Rothstein, Fabianx, greggles: Add default clickjacking defense to core](http://drupal.org/node/2514136)
- [x] | https://github.com/backdrop/backdrop/pull/1486 | [a95cb56](http://drupalcode.org/project/drupal.git/commit/a95cb56beb3a58fc7f86dda22eaa800e78f259da) | [Issue #2395385 by DamienMcKenna: simpletest fatal error when creating a non language neutral node and not specifying a node body](http://drupal.org/node/2395385) (this was actually N/A)
- [x] | https://github.com/backdrop/backdrop/issues/1474 | [65b71ab](http://drupalcode.org/project/drupal.git/commit/65b71ab7435256a5a124f8ccb93fc008b565dc2b) | [Issue #2646280 by Elijah Lynn, pietmarcus: Remove IE pre-check and post-check Cache-control headers](http://drupal.org/node/2646280)
- [x] | https://github.com/backdrop/backdrop/pull/1486 | [9bf8fdf](http://drupalcode.org/project/drupal.git/commit/9bf8fdfd4c9b882bec537f660026eae46b0233bc) | [Issue #2712993 by MustangGB, klausi: Can't override the same CSS files multiple times](http://drupal.org/node/2712993)
- [x] | N/A | [8472395](http://drupalcode.org/project/drupal.git/commit/84723952f214e5a2252af6f8d67462651b012d8a) | [Issue #2460833 by jackbravo, colinmccabe, checker, Alan D., twistor: _drupal_session_destroy() should return boolean](http://drupal.org/node/2460833)
- [x] | https://github.com/backdrop/backdrop/pull/1486 | [1a7642e](http://drupalcode.org/project/drupal.git/commit/1a7642eed3620272e864fcd7c27d69b7903eb9f2) | [Issue #2663746 by twistor, MustangGB: Array to string conversion in trigger.test for PHP 7](http://drupal.org/node/2663746)
- [x] | N/A | [d100499](http://drupalcode.org/project/drupal.git/commit/d100499e0a3c2bcd98e111df9e38dc624f447be9) | [Issue #2663752 by twistor, DamienMcKenna, ParisLiakos, sdstyles, Berdir: Undefined string index 0 in DrupalTestCase::getAbsoluteUrl() in PHP 7](http://drupal.org/node/2663752)
- [x] | https://github.com/backdrop/backdrop/pull/1486 | [d51a63f](http://drupalcode.org/project/drupal.git/commit/d51a63f6f4ff30169b1e0d05f9ce503590f04c56) | [Issue #2718323 by Liam Morland, jhodgdon: In drupal_http_request(), mention http_build_query()](http://drupal.org/node/2718323)
- [x] | https://github.com/backdrop/backdrop/pull/1486 | [33eab62](http://drupalcode.org/project/drupal.git/commit/33eab62b7291895b6fd0beafb7348966d904e0cf) | [Issue #2718179 by dagmar: Better documentation for suspicious encoded string in dblog tests](http://drupal.org/node/2718179)
- [x] | [4536453](http://drupalcode.org/project/drupal.git/commit/4536453d81166099eda98f8a7db3b8de3c50c086) | [Issue #2718323 by Liam Morland, jhodgdon: In drupal_http_request(), mention http_build_query()](http://drupal.org/node/2718323)
- [x] | https://github.com/backdrop/backdrop/pull/1886 | [d11d1c2](http://drupalcode.org/project/drupal.git/commit/d11d1c268a6852c8593f505dbdb1e2a3f42b2627) | [Issue #376391 by mimran, snehi, pietmarcus, jhodgdon: Document that module_invoke_all / ModuleHandlerInterface::invokeAll reindexes arrays](http://drupal.org/node/376391)
- [x] | https://github.com/backdrop/backdrop/pull/1886 | [c872c60](http://drupalcode.org/project/drupal.git/commit/c872c60b67dd0e62da7dc6f25fc2a6fc38734b7b) | [Issue #2660240 by Kgaut: Typo in menu.inc](http://drupal.org/node/2660240)
- [x] | https://github.com/backdrop/backdrop/pull/1886 | [1af0eb4](http://drupalcode.org/project/drupal.git/commit/1af0eb4b5ea154602d6f9605b515912ff46e39af) | [Issue #2694731 by nicrodgers: user_access(): incorrect documentation](http://drupal.org/node/2694731)
- [x] | N/A | [2647403](http://drupalcode.org/project/drupal.git/commit/26474037f5198e5911b130caf45ebd2641f8eb06) | [Issue #2756209: Add the new Drupal 7 co-maintainers to MAINTAINERS.txt](http://drupal.org/node/2756209)
- [x] | https://github.com/backdrop/backdrop/pull/1477 | [3a2b4f5](http://drupalcode.org/project/drupal.git/commit/3a2b4f50ed9ebec894bdd5f4249142856c145b5a) | [Issue #2371861 by DuaelFr, YesCT, pietmarcus, Gábor Hojtsy, tucho: Strings including tokens in href or src attributes cannot be translated due to safeness check incompatibilities](http://drupal.org/node/2371861)
- [x] | https://github.com/backdrop/backdrop/pull/1477| [3677ac5](http://drupalcode.org/project/drupal.git/commit/3677ac5bef5478a827db15aade03f40f9f078687) | [Issue #2371861 followup by David_Rothstein: Strings including tokens in href or src attributes cannot be translated due to safeness check incompatibilities](http://drupal.org/node/2371861)
- [x] | N/A | [a8c1ebd](http://drupalcode.org/project/drupal.git/commit/a8c1ebd8d77d1f1fdf6e4f5a05f9c706d67f54bf) | [Issue #2634840 by brianV: Add index on uid and module columns to authmap](http://drupal.org/node/2634840)
- [x] | https://github.com/backdrop/backdrop/pull/1886 | [b0fbd62](http://drupalcode.org/project/drupal.git/commit/b0fbd62b380fe179ea024d44905434245916a900) | [Issue #2311305 by donutdan4114, stefan.r, Polonium, rpayanm, tadityar, Fabianx, Dave Reid: getPrefixInfo() calls wrong function to get the connection info](http://drupal.org/node/2311305)
- [x] | https://github.com/backdrop/backdrop/pull/1886 | [09de859](http://drupalcode.org/project/drupal.git/commit/09de859518874ed5f1417c0b910efed98b5e3d52) | [Issue #1364694 by gielfeldt: MemoryQueue::createItem does not return TRUE](http://drupal.org/node/1364694)
- [x] | https://github.com/backdrop/backdrop/pull/1886 | [2503818](http://drupalcode.org/project/drupal.git/commit/2503818cfbbc93f029bacdb88183c85df5447501) | [Issue #2669568 by soaratul: Docblock typo in file_download_headers](http://drupal.org/node/2669568)
- [x] | https://github.com/backdrop/backdrop-issues/issues/6426 | [f7d2f47](http://drupalcode.org/project/drupal.git/commit/f7d2f47e9ed15ce7840ffafa105a0ea80a46eeca) | [Issue #889772 by tuutti, stefan.r, opdavies, Sutharsan, Perignon, pjcdawkins, joachim, das-peter, YesCT, David_Rothstein, Zerdiox, hussainweb, Fabianx, mgifford, xjm: Following a password reset link while logged in leaves users unable to change their password](http://drupal.org/node/889772)
- [x] | N/A | [d516757](http://drupalcode.org/project/drupal.git/commit/d51675754bb45b1f0352caecebcbdb333a3c708d) | [Issue #1713662 by nod_, Eric_A, treyhunner, sun, basvredeling: Introduce .editorconfig to auto-configure editors that support it](http://drupal.org/node/1713662)
- [x] | https://github.com/backdrop/backdrop/pull/4462 | [1fea8c8](http://drupalcode.org/project/drupal.git/commit/1fea8c83c9bcd26b709f709ac05470fcd97f001f) | [Issue #2491353 by pfrenssen, pietmarcus, znerol, David_Rothstein: Cookies from previous tests are still present when a new test starts](http://drupal.org/node/2491353)
- [x] | backdrop/backdrop#1443 | [f0e660b](http://drupalcode.org/project/drupal.git/commit/f0e660bda88537a4fa3d91c77a113044a8f4b766) | [Issue #2551981 by jthorson, Mixologic, Fabianx, David_Rothstein: Add --directory option to run-tests.sh test discovery](http://drupal.org/node/2551981)
- [x] | N/A | [8f7f28b](http://drupalcode.org/project/drupal.git/commit/8f7f28b6d9e045669d5dff29d50dbc9412f65db8) | [Issue #2189345 by benjy, sanduhrs, Mile23, joshtaylor, jbekker, David_Rothstein, klausi, sun, zaporylie, pfrenssen, jsacksick, jibran, Mixologic, znerol, Xano, alberto56: run-tests.sh should exit with a failure code if any tests failed](http://drupal.org/node/2189345)
- [x] | https://github.com/backdrop/backdrop/pull/4460 | [7543eae](http://drupalcode.org/project/drupal.git/commit/7543eae758df91a217e646438c992af1ee69e4a8) | [Issue #2364343 by damien_vancouver, criz, ksenzee, Neograph734, joegraduate, k_zoltan, droplet, pounard, jp.stacey, ciss, corbacho, TravisJohnston: Fix robots.txt to allow search engines access to CSS, JavaScript and image files](http://drupal.org/node/2364343)
- [x] | N/A | [44e1b4f](http://drupalcode.org/project/drupal.git/commit/44e1b4f0e6802512e2ee6209c9c748ab64fd9db9) | [Issue #2717633 by mikeytown2, twistor, scor, Fabianx, MustangGB: PHP 7 hook_rdf_mapping() ['mapping']['rdftype'] failing in rdf.test: RDF type is present on post](http://drupal.org/node/2717633)
- [x] | N/A | [84539bd](http://drupalcode.org/project/drupal.git/commit/84539bd50189b667522bc2c3195a5ab972b1023c) | [Issue #412808 by Berdir, rupertj, beejeebus, sun, PieterDC, scottalan, catch: Handling of missing files and functions inside the registry](http://drupal.org/node/412808)
- [x] | N/A | [4d5d300](http://drupalcode.org/project/drupal.git/commit/4d5d30045f2aa59468f3d550c4fc4fd76780961e) | [Issue #2660754 by twistor, David_Rothstein: Invalid numeric comparison in OpenIDTestCase::testConversion()](http://drupal.org/node/2660754)
- [x] | N/A | [4cdb4c5](http://drupalcode.org/project/drupal.git/commit/4cdb4c5c14c3f5f1684a956668b8ec8bf85ba869) | [Add grouped entries for PHP 5.4 and 7 test failures to CHANGELOG.txt.](http://drupal.org/node/)
- [x] | N/A | [b6939aa](http://drupalcode.org/project/drupal.git/commit/b6939aad7ec5b8e8ed1afed7228ea46560c3e3dd) | [Issue #2660766 by David_Rothstein, twistor: UpgradePathTaxonomyTestCase::testTaxonomyUpgrade() doesn't properly test field settings](http://drupal.org/node/2660766)
- [x] | N/A | [d833cb7](http://drupalcode.org/project/drupal.git/commit/d833cb7c1427d09226d8733e382cf34ae34a7722) | [Issue #2660762 by twistor: TrackerTest::testTrackerNewComments() sets the node title incorrectly](http://drupal.org/node/2660762)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [0dcc87a](http://drupalcode.org/project/drupal.git/commit/0dcc87a087f714ba4a936087dbc81465f63e8b1d) | [Issue #2633334 by orbmantell, e._s, catch, TravisCarden: Unsigned int vs. int mismatch between node.nid and history.nid](http://drupal.org/node/2633334)
- [x] | NA | [a1f2672](http://drupalcode.org/project/drupal.git/commit/a1f2672faa333f637b3c82f9278063ac34034cc0) | [Issue #2674028 by catch: Add page callback to admin/people/create menu item](http://drupal.org/node/2674028)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [11dac6e](http://drupalcode.org/project/drupal.git/commit/11dac6e10f2e1cff4bef398ea5090bde40a8fec2) | [Issue #1732906 by peterpoe, Ken Ficara, forestgardener, eesquibel, minax.de: Uninitialized variable in number_field_formatter_settings_form](http://drupal.org/node/1732906)
- [x] | N/A | [df75f7c](http://drupalcode.org/project/drupal.git/commit/df75f7c3152aa39c6303aba0d5db4c295c2f960a) | [Issue #2640888 by IRuslan, kala4ek: Broken link on image toolkits conf page when no toolkits are installed](http://drupal.org/node/2640888)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [4fb5e50](http://drupalcode.org/project/drupal.git/commit/4fb5e5068d51a3dabd2ce25e24d8138e581032b0) | [Issue #2669704 by eiriksm, jhodgdon: Missing function doc comments in user.pages.inc](http://drupal.org/node/2669704)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [4f9fcc6](http://drupalcode.org/project/drupal.git/commit/4f9fcc6271dc669094746a5ce378d75e05022809) | [Issue #2676472 by micaelamenara, dagmar, jhodgdon: docs for t() and related functions don't explain how context works](http://drupal.org/node/2676472)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [3588007](http://drupalcode.org/project/drupal.git/commit/35880070129c58ecdf9eea58ad475d1df7ffb1ce) | [Issue #1622964 by felribeiro, snehi, ar-jan, Girish-jerk, jhodgdon, joachim, jp.stacey, stefan.r: docs for EntityFieldQuery::fieldCondition are really sparse](http://drupal.org/node/1622964)
- [x] | N/A | [90cff29](http://drupalcode.org/project/drupal.git/commit/90cff29b4da41249758e1feabf2306ae5fd853b3) | [Issue #1388664 by akoepke, chirhotec, klokie, lOggOl: Blog module conflicts with other URL routes beginning with "blog/"](http://drupal.org/node/1388664)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [bc48446](http://drupalcode.org/project/drupal.git/commit/bc484461947fc09edae80e7aa7d10161a745a061) | [Issue #1327728 by Darren Oh, Josh Waihi, cspitzlay, c960657: ip_address() fails when client request IP and proxy IP are the same](http://drupal.org/node/1327728)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [15da2e8](http://drupalcode.org/project/drupal.git/commit/15da2e8c43e274aee837bbf1dea1c905f95f4e5e) | [Issue #2563751 by borisson_, rocketeerbkw, cilefen, pietmarcus, NikitaJain, imanol.eguskiza, pjonckiere: Password field errors on user create/edit/login when password is (literally) 0](http://drupal.org/node/2563751)
- [x] | https://github.com/backdrop/backdrop/pull/1888 | [5009eff](http://drupalcode.org/project/drupal.git/commit/5009eff28be145d0f4218dd60a9ab07eaf7dfe13) | [Issue #2749489 by pwolanin: Write test for the User module security issue from SA-CORE-2016-002](http://drupal.org/node/2749489)
- [x] | N/A | [e06da1d](http://drupalcode.org/project/drupal.git/commit/e06da1d7c35b2117d2086ee0dc277b3383a6cedc) | [Issue #1116326 by s_leu, yannickoo, dawehner, nod_, pwolanin, David_Rothstein, ksenzee, realityloop, miro_dietiker, broeker, mariagwyn, Christian DeLoach: Support admin overlay in exposed forms](http://drupal.org/node/1116326)
- [x] | https://github.com/backdrop/backdrop/pull/2001 | [5e71cae](http://drupalcode.org/project/drupal.git/commit/5e71caebfdd7022de21cc4ba541891a94a9ff592) | [Issue #2578173 by Peacog, David_Rothstein, maximpodorov, marvin_B8, andypost, alexpott, tatisilva: Increase menu title maxlength to 255 in forms containing menu items](http://drupal.org/node/2578173)
- [x] | https://github.com/backdrop/backdrop/pull/2001 | [6c75ac1](http://drupalcode.org/project/drupal.git/commit/6c75ac1f3f9add9df41d9b29d9ddfb09f326b086) | [Issue #2393461 by David_Rothstein, mpv, maciej.zgadzaj, Sagar Ramgade, davic, Fabianx: format_xml_elements() does not allow unencoded values](http://drupal.org/node/2393461)
- [x] | N/A | [86fc546](http://drupalcode.org/project/drupal.git/commit/86fc546837ba1a0499f200c7550679721f72bba7) | [Issue #2393461 followup by nevergone: format_xml_elements() does not allow unencoded values](http://drupal.org/node/2393461)
- [x] | N/A | [f68a354](http://drupalcode.org/project/drupal.git/commit/f68a354ff8d3b72eb6d8a7ef34b0370b9487e817) | [Issue #2393461 followup by Sagar Ramgade: format_xml_elements() does not allow unencoded values](http://drupal.org/node/2393461)
- [x] | N/A | [206c7c1](http://drupalcode.org/project/drupal.git/commit/206c7c1b40495842f013e086675173d15a7ad12f) | [Issue #1081266 by stefan.r, jeroen.b, mikeytown2, David_Rothstein, tsphethean, mfb, joseph.olstad, marcelovani, Kars-T, joelpittet, Fabianx, catch, fgm, das-peter, alexpott, emcniece, oriol_e9g, sun, corbacho, klausi, mgifford, onelittleant, Peter Bex, Spleshka, beejeebus, Berdir, pwaterz, SocialNicheGuru, sylus, Wim Leers, heyyo, joshtaylor, swentel, alanburke, dagmar, alexmoreno, kenorb, EvanSchisler, Mark Theunissen, bmateus, andypost, Lukas von Blarer, ChristophWeber, nicholas.alipaz, arosboro, askibinski, dawehner, DerekL, ExTexan: Avoid re-scanning module directory when a filename or a module is missing](http://drupal.org/node/1081266)
- [x] | https://github.com/backdrop/backdrop/pull/2001 | [f68bbb9](http://drupalcode.org/project/drupal.git/commit/f68bbb9a7dcb657b1a4c4587de2dac93fd3f5f1e) | [Issue #1458824 by idebr, JvE, therealssj, mayaz17, cwoky, Henrik Opel, lokapujya, kevinquillen, presleyd, nod_, jbeuckm, botris, mistermoper, gcardinal: Ajax doesn't work with Tableselect with checkboxes](http://drupal.org/node/1458824)
- [x] | https://github.com/backdrop/backdrop/pull/2001 | [56940cd](http://drupalcode.org/project/drupal.git/commit/56940cd4fbfe4bde63415e206ae63c478d0c72ed) | [Issue #1645156 by attiks, tstoeckler, talhaparacha, amontero, Carsten Müller, Albert Volkman, Gábor Hojtsy, David_Rothstein, leschekfm, vasi1186, dcam, catch, Sweetchuck, Fabianx, nicrodgers: URL generation only works on port 80](http://drupal.org/node/1645156)
- [x] | https://github.com/backdrop/backdrop/pull/2001 | [b042085](http://drupalcode.org/project/drupal.git/commit/b0420854d4029b7d3559c892c05b1fa6b212ae83) | [Issue #2502263 by hgoto, David_Rothstein, klausi, ckng, rhclayto: Drupal 7.36 regression: hidden field textarea #default_value is ignored](http://drupal.org/node/2502263)
- [x] | N/A | [c759414](http://drupalcode.org/project/drupal.git/commit/c75941414e97c88cf05f7be3ee0bd54e9dbaa466) | [Issue #2747679 by david_garcia, pashupathi nath gajawada, izaaksom: Ajax form callbacks can only be global functions](http://drupal.org/node/2747679)
- [x] | https://github.com/backdrop/backdrop/pull/2001 | [3c6803f](http://drupalcode.org/project/drupal.git/commit/3c6803ffb11a20091362eeccc2e048fe248d42b7) | [Issue #2759899 by Fabianx: drupal_get_schema_versions() does report wrong data the first time a test is run](http://drupal.org/node/2759899)
- [x] | https://github.com/backdrop/backdrop/pull/2001 | [6303a15](http://drupalcode.org/project/drupal.git/commit/6303a1567195c2b31da87bb67b6346b2dd907e3a) | [Issue #2760609: Allow the use of callbacks instead of global functions in the Form API](http://drupal.org/node/2760609)
- [x] | N/A | [c371d42](http://drupalcode.org/project/drupal.git/commit/c371d42cad46a6aeee911aac4de7d1b6155adc33) | [Add issue #2760609 and relevant change record to CHANGELOG.txt.](http://drupal.org/node/2760609)
- [x] | N/A | [bc60c92](http://drupalcode.org/project/drupal.git/commit/bc60c9298a6b1a09c22bea7f5d87916902c27024) | [Issue #2488180 by stefan.r, stovak, pwolanin, David_Rothstein, Noe_, typhonius, KhaledBlah, joelpittet, Fabianx, geerlingguy, nithinkolekar, mikeytown2, jduhls, scuba_fly, travelvc, hass: Support full UTF-8 (emojis, Asian symbols, mathematical symbols) on MySQL and other database drivers when they are configured to allow it](http://drupal.org/node/2488180)
- [x] | N/A | [b2bf69c](http://drupalcode.org/project/drupal.git/commit/b2bf69c77d5420fc22f28c85ed82af2b83c11073) | [Add change records to CHANGELOG.txt, and small wording changes.](http://drupal.org/node/)
- [x] | N/A | [5473c95](http://drupalcode.org/project/drupal.git/commit/5473c95994aaf4e6b367100822635223d8fc85eb) | [Rearrange items in CHANGELOG.txt for Drupal 7.50 to be in a more logical order.](http://drupal.org/node/)
- [x] | N/A | [3705166](http://drupalcode.org/project/drupal.git/commit/37051665886eb0cba6e75047c104c2791a6beb2f) | [Issue #2393461 CHANGELOG.txt entry should be for Drupal 7.50 (not Drupal 7.40).](http://drupal.org/node/2393461)
- [x] | N/A | [4b96aef](http://drupalcode.org/project/drupal.git/commit/4b96aef1d9a154114c798a6a4957c91200cda845) | [Rearrange CHANGELOG.txt a bit more.](http://drupal.org/node/)
- [x] | N/A | [d04427f](http://drupalcode.org/project/drupal.git/commit/d04427f818f69724033823251a9bd465bf4bde94) | [Various fixes to CHANGELOG.txt in preparation for Drupal 7.50.](http://drupal.org/node/)
- [x] | N/A | [d2d2c5f](http://drupalcode.org/project/drupal.git/commit/d2d2c5f3b42b0312a7f98b7470eae191aedfc678) | [Issue #2761285 by MegaChriz: _drupal_session_write() does not always return a boolean](http://drupal.org/node/2761285)
- [x] | N/A | [ab6e1a0](http://drupalcode.org/project/drupal.git/commit/ab6e1a0af22d816e5709f392e4d21156394cdd8f) | [Fix typo in Drupal 7.50 CHANGELOG.txt.](http://drupal.org/node/)
- [x] | N/A | [78cba77](http://drupalcode.org/project/drupal.git/commit/78cba776f30a32a67d780bfdadd37cc4594f3a81) | [Issue #2762393 by stefan.r, MustangGB, David_Rothstein: Skip error triggering for missing files if the files are empty or "default"](http://drupal.org/node/2762393)
- [x] | N/A | [4d154b4](http://drupalcode.org/project/drupal.git/commit/4d154b4c818f1a82e5d33611a3af8d6f7383980a) | [Drupal 7.50](http://drupal.org/node/)

Separately:
* https://github.com/backdrop/backdrop-issues/issues/2844| [b2bd3e0](http://drupalcode.org/project/drupal.git/commit/b2bd3e0d7364367245cc1ad1486adc908107658b) | [Issue #2215369 by fietserwin, Lowell, mondrake, mr.baileys, David_Rothstein, kristofferwiklund, TwoD, bradjones1, svanou, kristiaanvandeneynde, Fabianx: Various bugs with PHP 5.5 imagerotate(), including when incorrect color indices are passed in](http://drupal.org/node/2215369)

---

git command: 

```
git log 7.44..7.50 --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"
```
REGEX: Find: `(Issue #)(\w\w+)(.*?)(node\/)` Replace: `$1$2$3$4$2`

**Comment by klonos** [comment]
Thanx for putting the list together @serundeputy. You beat me to it 😄 

I'm still on vacation with my girls, so not much time, but I'll try my best to grab any low-hanging fruits and also review others' PRs. Note that my reviews should be considered only a second-pair-of-eyes look-through though.

**Comment by klonos** [comment]
> I think this is NA for backdrop since files are auto-uploaded when we select them.

Yep, that is the case. Good call on setting this to NA.

**Comment by Gormartsen** [comment]
This issue is in 1.4.3 milestone. But 1.4.3 was released 17 days ago.
@serundeputy maybe you mean 1.4.4 ?

**Comment by jenlampton** [comment]
@klonos @serundeputy some of these issues are marked as completed (the box is checked) but there is still a `#xx` in the description of the issue, indicating that there should be a backdrop pull request (but it has not yet been created).

I'm here at the sprint and wanted to get people working on this issue, is it worth going through all of those and seeing if they were marked completed inadvertently?

**Comment by serundeputy** [comment]
@jenlampton looks like you guys have already started going though them. sprint++;

**Comment by jenlampton** [comment]
> Moot; https://github.com/backdrop/backdrop/pull/1034/commits/977cfd7397862df9334784e4b190a35ab31f333b Thanks @jenlampton 

This isn't actually moot, I did some work on that other D7 issue recently and realized that I missed one of the strings. Committed a new PR to address this same update at https://github.com/backdrop/backdrop/pull/1473

**Comment by jenlampton** [comment]
Yep @serundeputy I decided it was worth doing for myself anyway, good for me to know what went into 1.50 :)

**Comment by klonos** [comment]
I wish I had time to grab some of these 😞

**Comment by quicksketch** [comment]
All PRs that have been filed for this have either been merged or reviewed. We'll probably get 1.4.4 out tomorrow and continue any remaining items for the next bugfix release. Feature-items such as the new field permissions, X-Frame-Options, and the full UTF-8 database support will go into 1.5.0 (1.x) as we get them finished.

**Comment by jenlampton** [comment]
Returning to this issue. 

Change record ready: https://api.backdropcms.org/node/44961

**Comment by klonos** [comment]
I left a couple of comments on the PR @jenlampton

**Comment by klonos** [comment]
...btw, I get "access denied" when trying to access unpublished change records on api.b.org. Can someone please fix that for me so that I can be able to review. Thanx in advance.

**Comment by klonos** [comment]
Perhaps I can pick some of these. Have we been consistently ticking off of the list those that we have already merged?

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/1886 RTBC 👍

**Comment by klonos** [comment]
Left comments in https://github.com/backdrop/backdrop/pull/1887/files (`drupal*` -> `backdrop*`)

**Comment by klonos** [comment]
...also a review for https://github.com/backdrop/backdrop/pull/1888

**Comment by quicksketch** [comment]
Thanks @klonos for the reviews. I've merged the ready ones. https://github.com/backdrop/backdrop/pull/1887 and https://github.com/backdrop/backdrop/pull/1888 need work.

**Comment by opi** [comment]
Simple PR to address [Drupal's 2364343](https://drupal.org/node/2364343): https://github.com/backdrop/backdrop/pull/1974

**Comment by klonos** [comment]
RTBC @opi's PR ^^

**Comment by klonos** [comment]
@jenlampton do you have the capacity to take a look at the 2 PRs mentioned by @quicksketch a couple of comments above? I have left some comments in them (mostly `drupal` to `backdrop` renames).

**Comment by jenlampton** [comment]
sure, looking now.

**Comment by jenlampton** [comment]
I pushed one last PR for these commits: https://github.com/backdrop/backdrop/pull/2001 The only one I couldn't immediately figure out is `Various bugs with PHP 5.5 imagerotate(), including when incorrect color indices are passed in` because we already made a bunch of changes to GD support in Backdrop. I was tempted to try to add the test and see if Backdrop has the same problems, but even the way the tests work is a little different. So, in the hopes to get as many of these in as possible I opened another issue were we can work on that separately: https://github.com/backdrop/backdrop-issues/issues/2844

**Comment by quicksketch** [comment]
The remaining two PRs, https://github.com/backdrop/backdrop/pull/1887 and https://github.com/backdrop/backdrop/pull/1888 have failing tests. Getting really close here!

**Comment by jenlampton** [comment]
The remaining two PRs have been updated and are ready for review again.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/1885 (click jacking defense) into 1.x only, as this introduces a minor API difference. I updated the [change record](https://api.backdropcms.org/node/44961) to reflect the version being 1.9.0.

**Comment by quicksketch** [comment]
And https://github.com/backdrop/backdrop/pull/1888 has now been merged as well! It had one failing test for which I pushed a final update. Merged into 1.x and 1.8.x.

Looks like that's the final one for this issue. Great job on completing these tough last ports! I'll be so happy to announce these ports complete during the next weekly meeting. :smile:

**Comment by klonos** [comment]
Based on @jenlampton's PR which I've closed, I've filed 3 separate PRs for the things we missed:
- https://github.com/backdrop/backdrop/pull/4460
- https://github.com/backdrop/backdrop/pull/4461
- https://github.com/backdrop/backdrop/pull/4462

I've updated the issue summary, and for visibility I removed the "fixed" label and changed the milestone to the next bug fix release.

**Comment by quicksketch** [comment]
Shoot, I hoped we could close out this issue, but there are some issues with https://github.com/backdrop/backdrop/pull/4461.

I did merge https://github.com/backdrop/backdrop/pull/4460 and https://github.com/backdrop/backdrop/pull/4462, which both looked good.

So we have just one lingering issue here. Maybe 1.28.2 :crossed_fingers:

**Comment by klonos** [comment]
Reopening for that last remaining issue to stay within our radar

**Comment by quicksketch** [comment]
The last issue in this was actually ported in a dedicated issue: https://github.com/backdrop/backdrop-issues/issues/6426 and was completed back in Backdrop 1.28.3. Yay, we can finally close this one.
