### ISSUE TITLE
[meta] Comments

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#2047]
This is a meta issue for comments:

- [ ] #330 Convert "Recent comments" block to a view
- [ ] #336 "Administer comments and comment settings" should be split into two permissions
- [ ] #549 Convert admin/content/comments to a View
- [ ] #1262 [UX] Add the "Comment fields" and "Comment display" links to the operations dropbutton in the content type admin page and also the respective admin menu items.
- [ ] #1274 [UX] Reflect the status of the comment settings in the "Comment fields" and "Comment display" tabs and offer connect-the-dots links to enable them.
- [ ] #1472 [UX] Allow comments to be (truly, entirely) disabled on a per-content type basis.
- [ ] #2046 Store entity bundle in comment table

**Comment by cptX** [comment]
Please add also this to the list:
Comment titles should be removed from presentation and from database if not used
https://github.com/backdrop/backdrop-issues/issues/4967

**Comment by stpaultim** [comment]
@cptX - Done. I'm not sure who has access to edit the original issue, but if you have access you should feel free to edit any list like this yourself. If not, then just ask as you did. Thanks!
