### ISSUE TITLE
[META] CSS review of cleanup from Drupal 8

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#207]
I don't think we want to include all of the new css changes that were introduced in Drupal 8. This issue is a meta where we can review all the CSS changes in D8 and decide what cleanup we would like to do for Backdrop. These commits are ordered OLDEST to NEWEST. Important issues are indicated in **bold**, below.

For reference:
- [Backdrop CSS standards](http://backdropcms.org/develop/css-standards) \* may need to be updated after this issue
- [Drupal CSS standards](https://drupal.org/node/1887918)

Specific Backdrop issues in the list below (#xx)  have not been created yet. If we need a separate sub issue they will be linked here when they are created.  If not, we can link to a PR, or mark the issue as N/A.
- Status: Either " [ ] " or "- [x] "
- Issue: The Backdrop Issue number, or N/A if we are not pursuing the same change in Backdrop.
- Commit: The Drupal 8 commit ID
- Drupal Issue(s) and summary: Commit message, linked to the d.o issue.

Status | Issue | Commit | Drupal Issue(s) and summary
- [x] | [938baf7](http://drupalcode.org/project/drupal.git/commit/938baf76b4ce9f18f30cdb26311b9ee909e61962) | [Issue #1322794 by scor: follow up patch fixing the 'No newline at end of file' in ie-rtl.css and ie.css.](http://drupal.org/node/1322794)
- [x] https://github.com/backdrop/backdrop/pull/191 | [a56a6ba](http://drupalcode.org/project/drupal.git/commit/a56a6badd01e4b2af123fd1e2bb48be2e9dc9b07) | [Issue #1663192 by Manuel Garcia, Rob Loach: Clean up taxonomy css.](http://drupal.org/node/1663192)
- [x] https://github.com/backdrop/backdrop/pull/387 | [ff2eaca](http://drupalcode.org/project/drupal.git/commit/ff2eaca55236cd0a524a7cb6e04d63c96c0521a2) | [Issue #1003168 by Ralf, jbrown, schnippy: dblog css classes consistent with php constants.](http://drupal.org/node/1003168)
- [x] https://github.com/backdrop/backdrop/pull/192 | [3e6f4a3](http://drupalcode.org/project/drupal.git/commit/3e6f4a3abd33d353abfcfeb6ceb416813adb6f4a) | [Issue #1662956 by guy_schneerson: Clean up css in Book.](http://drupal.org/node/1662956)
- [x] https://github.com/backdrop/backdrop/pull/192 | [3757dcb](http://drupalcode.org/project/drupal.git/commit/3757dcbe25d0e3a20e213dbd376321ea5b974c66) | [Issue #1662976 by mjonesdinero: Clean up css in Field.](http://drupal.org/node/1662976)
- [x] https://github.com/backdrop/backdrop/pull/251 | [6e8a223](http://drupalcode.org/project/drupal.git/commit/6e8a223b15aee5a666ff80d609af120c9b2453b8) | [Issue #1276908 by jessebeach, nod_, moshe weitzman, lewisnyman, webchick: Fixed Administrative tables are too wide for smaller screens.](http://drupal.org/node/1276908)
- [x] https://github.com/backdrop/backdrop/pull/323  | [90b9f67](http://drupalcode.org/project/drupal.git/commit/90b9f678d9e3274f5e8af17e1d15e1a24291c581) | [Issue #1800304 by dawehner: Fixed The css for responsive tables on bartik contains old class names.](http://drupal.org/node/1800304)
- [x] N/A | [4c4b4a7](http://drupalcode.org/project/drupal.git/commit/4c4b4a79cb53e8e1a34bebc71c19d74d7ecc79b8) | [Issue #1608878 follow-up by tim.plunkett: Move Dropbutton CSS to dropbutton.base.css from node.admin.css.](http://drupal.org/node/1608878)
- [x] N/A | [6e0f3ff](http://drupalcode.org/project/drupal.git/commit/6e0f3ffe82a798a4865d01435eccb95ead9383c0) | [Issue #1757170 by slv_ | aspilicious: Fixed Move views_cache().test.css and views_cache().test.js to the correct folder (and fix the test).](http://drupal.org/node/1757170)
- [x] N/A | [a351e0e](http://drupalcode.org/project/drupal.git/commit/a351e0ee4a4bd65bea145f2fc24ddd23bef8a062) | [Issue #1754316 by dead_arm: Use the MODULE.base.css standard.](https://drupal.org/node/1754316)
- [x] https://github.com/backdrop/backdrop/pull/265 | [cabaa7b](http://drupalcode.org/project/drupal.git/commit/cabaa7bd4cb8f44d8f113e2063dc56243ef1641b) | [Issue #1778806 by tim.plunkett: Remove views_clean_css_identifier() in favor of drupal_clean_css_identifier().](http://drupal.org/node/)
- [x] https://github.com/backdrop/backdrop/pull/197 | [5708184](http://drupalcode.org/project/drupal.git/commit/570818447a47975ab005ee933b478650f01aae68) | [Issue #1663044 by Manuel Garcia, barraponto: Clean up css in Image.](http://drupal.org/node/1663044)
- [x] https://github.com/backdrop/backdrop/pull/388 | [b90c07c](http://drupalcode.org/project/drupal.git/commit/b90c07c181e71f6f8ac5f605f472d32134deb71e) | [Issue #1663130 by droplet, Risse, Rob Loach, barraponto, dnotes: Clean up css in Locale.](http://drupal.org/node/1663130)
- [x] https://github.com/backdrop/backdrop/pull/381 | [a3067d6](http://drupalcode.org/project/drupal.git/commit/a3067d6af17814603ad438d15ca2534b23897723) | [Issue #1662986 by _Cedric_, Rob Loach, Albert Volkman, barraponto: Clean up css in Field UI.](http://drupal.org/node/1662986)
- [x] N/A | [b08c448](http://drupalcode.org/project/drupal.git/commit/b08c448389724969d782c18d597bc9b5d8ee3f16) | [Issue #1811828 by dawehner, tim.plunkett: Use #attached to find the css/js of a view.](http://drupal.org/node/1811828)
- [x] N/A | [bced82e](http://drupalcode.org/project/drupal.git/commit/bced82e4191cf968a13098afae4b994b8ce5ddf9) | [Issue #1662990 by mjonesdinero, daniel92, brenda003: Clean up css in File.](http://drupal.org/node/1662990)
- [x] https://github.com/backdrop/backdrop/pull/331 | [473df01](http://drupalcode.org/project/drupal.git/commit/473df01aad4804ec671ca32c17f005fe6d63dc46) | [Issue #1662974 by barraponto, droplet, Albert Volkman, nitvirus, roborn, David Hernández: Clean up css in dblog.](http://drupal.org/node/1662974)
- [x] N/A | [71176ec](http://drupalcode.org/project/drupal.git/commit/71176ec3f243295c2e86b09dbc2ca0a708b4a314) | [Issue #1799124 by Cottser: locale-rtl.css is out of sync with locale.admin.css, is never included due to incorrect filename.](http://drupal.org/node/1799124)
- [x] https://github.com/backdrop/backdrop/pull/278 | [bc24fb0](http://drupalcode.org/project/drupal.git/commit/bc24fb050750576819dd30d3fe1719e7124879e3) | [Issue #1663174 by Albert Volkman, oresh: Clean up system main css.](http://drupal.org/node/1663174)
- [x] https://github.com/backdrop/backdrop/pull/279 | [8f039f0](http://drupalcode.org/project/drupal.git/commit/8f039f0cf124b975583cdf19c4a18c5d16b7ba0a) | [Issue #1021622 by amateescu, dags, K3vin: Fixed Improper escaping of CDATA for inline css.](http://drupal.org/node/1021622)
- [x] https://github.com/backdrop/backdrop/pull/281 | [578aa1d](http://drupalcode.org/project/drupal.git/commit/578aa1d1fb26cc1484d26ccaec29b5ea3087f5ea) | [Issue #1978036 by echoz: Clean up css in vertical tabs.](http://drupal.org/node/1978036)
- [x] N/A | [d00049d](http://drupalcode.org/project/drupal.git/commit/d00049dc74cff364c01932138a3ee0e122d3c86e) | [Issue #1968430 by oresh: Added Clean up css and markup for Tour module .](http://drupal.org/node/1968430)
- [x] https://github.com/backdrop/backdrop/pull/294 | [81ed3ec](http://drupalcode.org/project/drupal.git/commit/81ed3ecb0f6d92ca851c41d75b1d0902dee1116b) | [Issue #2003564 by manarth: Remove drupal_add_css() from block.module — use #attached.](http://drupal.org/node/2003564)
- [x] https://github.com/backdrop/backdrop/pull/394 | [2432c02](http://cgit.drupalcode.org/drupal/commit/?id=2432c02) | <strong>[Issue #1987066 by Kevin Morse, JohnAlbin, rteijeiro, echoz, ry5n: Rename files to match CSS file naming convention.](https://drupal.org/node/1987066)</strong>
- [x] https://github.com/backdrop/backdrop/pull/295 | [9708795](http://drupalcode.org/project/drupal.git/commit/970879581a648291fff540f5323ec9ed8b35b520) | [Issue #2012526 by mcjim: Remove drupal_add_css() from book.module — use #attached.](http://drupal.org/node/2012526)
- [x] N/A | [3360502](http://drupalcode.org/project/drupal.git/commit/336050289082cd877d71c147781d686e0e121827) | [Issue #2009584 by rteijeiro, ry5n: Fixed Allow double underscores to pass through drupal_clean_css_identifier() as per new CSS standards.](http://drupal.org/node/2009584)
- [x] N/A | [9c173cf](http://drupalcode.org/project/drupal.git/commit/9c173cfe7a695bddb5fc1c06ffb97d42439ef594) | [Issue #2005616 by mikeker: Views should use ['#attached']['library'] rather than ['#attached']['css'].](http://drupal.org/node/2005616)
- [x] N/A | [a2ed2bb](http://drupalcode.org/project/drupal.git/commit/a2ed2bbcbfe22aaccc51c4085d759c0ec6426607) | [Issue #2021073 by echoz: Remove Seven's ie.css.](http://drupal.org/node/2021073)
- [x] https://github.com/backdrop/backdrop/pull/334 | [bfba7b8](http://drupalcode.org/project/drupal.git/commit/bfba7b8de929c12715ad0e2e3d5ebe899f9ed9ad) | [Issue #2015789 by fubhy, echoz, rteijeiro, LewisNyman, penyaskito: Remove language_css_alter() (RTL stylesheets) in favor of HTML 'dir' attribute.](http://drupal.org/node/2015789)
- [x] https://github.com/backdrop/backdrop/pull/393 | [e5b1973](http://drupalcode.org/project/drupal.git/commit/e5b197370604e193d9d7ce9bfaa493601343cd5b) | [Issue #2010636 by mcjim, Wim Leers, typhonius: Remove drupal_add_css() and drupal_add_js() from color.module — use #attached.](http://drupal.org/node/2010636)
- [x] N/A | [862b4d6](http://drupalcode.org/project/drupal.git/commit/862b4d63478a2ba1344b4f192c3fefeaff28abed) | [Issue #2008270 by mcjim, typhonius: Remove drupal_add_css() from _drupal_maintenance_theme() — use #attached.](http://drupal.org/node/2008270)
- [x] https://github.com/backdrop/backdrop/pull/300 | [656b342](http://drupalcode.org/project/drupal.git/commit/656b3422e3ce9e7b5168f6061510acce4d78a0c1) | [Issue #2057317 by echoz: Cleanup recently patched qualified selector css.](http://drupal.org/node/2057317)
- [x] N/A | [fedfd49](http://drupalcode.org/project/drupal.git/commit/fedfd496b0ed6044e98322e3c798592c45ea5b1d) | [Issue #2029451 by R.Hendel: Fixed to general css in the views UI.](http://drupal.org/node/2029451)
- [x] N/A | [de2c020](http://drupalcode.org/project/drupal.git/commit/de2c020cb57bf568ef4a4db7cb26d3c00e2d1540) | [Issue #2059719 by mdrummond: Fixed Content translation admin CSS file not renamed from translation_entity().admin.css.](http://drupal.org/node/2059719)
- [x] N/A | [ec9b2e8](http://drupalcode.org/project/drupal.git/commit/ec9b2e800cf75b976baa56f25f200ae9d7a1c398) | [Issue #1969916 by Tim Bozeman, Wim Leers, Cottser, nod_: Fixed Remove drupal_add_js()/css from seven.theme.](http://drupal.org/node/1969916)
- [x] https://github.com/backdrop/backdrop/pull/334 | [79abddb](http://drupalcode.org/project/drupal.git/commit/79abddbee8de1c93efe6f1e55af8dbd2ebff8444) | [Issue #2085673 by Wim Leers: Remove all remaining '-rtl.css' references.](http://drupal.org/node/2085673)
- [x] N/A | [ded8dc7](http://drupalcode.org/project/drupal.git/commit/ded8dc77d25fbb80fc51bca9f0a2c397375ae98f) | [Issue #2040269 by Tim Bozeman, RunePhilosof, typhonius, Cottser: Remove drupal_add_css() from bartik.theme.](http://drupal.org/node/2040269)
- [x] N/A | [0eb6d08](http://drupalcode.org/project/drupal.git/commit/0eb6d0832f471853a06a0f1f1973723959bcef7d) | [Issue #2096593 by Wim Leers: Remove drupal_add_css() from system.module.](http://drupal.org/node/2096593)
- [x] N/A | [a68a2e2](http://drupalcode.org/project/drupal.git/commit/a68a2e239b2279927ba3ca8d827bd3fa4ecb25eb) | [Issue #2095311 by Wim Leers: Remove drupal_add_css() from update.module.](http://drupal.org/node/2095311)
- [x] N/A | [5868f29](http://drupalcode.org/project/drupal.git/commit/5868f29f19d7e9f445c18316724d43cb0e9d7249) | [Issue #2095329 by Wim Leers: Remove drupal_add_css() from batch system.](http://drupal.org/node/2095329)
- [x] | [4c6309c](http://drupalcode.org/project/drupal.git/commit/4c6309c6f89923955651fb95333cd23d96e01b13) | [Issue #2096577 by Wim Leers, vijaycs85: Remove drupal_add_css() from views.module.](http://drupal.org/node/2096577)
- [x] https://github.com/backdrop/backdrop/pull/265 | [9547904](http://drupalcode.org/project/drupal.git/commit/954790465dd32964fcf2074fdb071f01ca634343) | [Issue #2073123 by dsdeiz, maartendeblock | xtfer: Drupal_clean_css_identifier() allows invalid CSS identifiers.](http://drupal.org/node/2073123)
- [x] N/A | [f392d38](http://drupalcode.org/project/drupal.git/commit/f392d38ee8f9a0cf027c28e2a23b23272ee0d97e) | [Issue #2096591 by mr.baileys, vijaycs85, Wim Leers: Remove drupal_add_css() from the theme system.](http://drupal.org/node/2096591)
- [x] N/A | [ff4a8e9](http://drupalcode.org/project/drupal.git/commit/ff4a8e9fc750c8dac4c9a2663cd561ace8ef2ff1) | [Issue #2095335 by Wim Leers, vijaycs85: Remove drupal_add_css() and drupal_add_js() from the ajax system.](http://drupal.org/node/2095335)
- [x] N/A | [a3d8888](http://drupalcode.org/project/drupal.git/commit/a3d8888369f3fc31e74720452d2718e089a77cb2) | [Issue #2008270 by typhonius, mcjim, Wim Leers, vijaycs85, mr.baileys, JohnAlbin: Remove drupal_add_css() from template_preprocess_maintenance_page() — use #attached.](http://drupal.org/node/2008270)
- [x] https://github.com/backdrop/backdrop/pull/400 | [ee9fe14](http://drupalcode.org/project/drupal.git/commit/ee9fe14e8bd0dd955e98e05a77b390f5e11ca39a) | [Issue #641734 by echoz, LewisNyman, davidtrainer, Cottser, falkendk, rteijeiro: Separate generic html elements' style into seven.base.css.](http://drupal.org/node/641734)
- [x] N/A | [99d3490](http://drupalcode.org/project/drupal.git/commit/99d3490f9f4003363b5704d8d2a5456ffbaf835f) | [Issue #2168113 by penyaskito, jessebeach, catch: Add leading underscore and other discouragement to drupal_add_css() and drupal_add_js().](http://drupal.org/node/2168113)
- [x] N/A | [10af33a](http://drupalcode.org/project/drupal.git/commit/10af33ad152464ef995e6b8a2b14b81637d80a5f) | [Issue #2205157 by jibran, rteijeiro | sun: Convert locale.admin.css into a library.](http://drupal.org/node/2205157)
- [x] | [fa84283](http://drupalcode.org/project/drupal.git/commit/fa84283f785fcca25d034fa2472910d2e4ff6ea8) | [Issue #2202999 by thamas: Duplicated lines in style.css of Seven theme.](http://drupal.org/node/2202999)
- [x] https://github.com/backdrop/backdrop/pull/188 | [0cf0a52](http://drupalcode.org/project/drupal.git/commit/0cf0a527741dafa3d74b58f454e321d22ec38cae) | [Issue #1999654 by mondrake: Missing buttons.png referenced in jquery.ui.theme.css.](http://drupal.org/node/1999654)

This list created with the following command:
`git log d1aee00..43de2c72 --reverse --grep='css' --pretty=format:"- [ ] #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"`
