### ISSUE TITLE
Remove the block cache from Backdrop

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#212]
The block cache as it currently stands is not super useful, especially if we move to a panels-based new blocks and layout system.  Caching should be per layout, not global for the whole site. 

Related issues:
- [ ] #xx | [43c8918](http://drupalcode.org/project/drupal.git/commit/43c8918f96612d6ab37e8ca122e0f7c0ac4520a1) | [Issue #1956914 by chaby, pounard: Use a single cache_get_multiple() call per region instead of a cache_get() per block in _block_render_blocks().](http://drupal.org/node/1956914)
- [ ] #xx | [5ae8828](http://drupalcode.org/project/drupal.git/commit/5ae8828fef1b17c5ac412b8a47a7be7cb75d9144) | [Revert "Issue #1956914 by chaby, pounard: Use a single cache_get_multiple() call per region instead of a cache_get() per block in _block_render_blocks()."](http://drupal.org/node/1956914)
- [ ] #xx | [19dc0fc](http://drupalcode.org/project/drupal.git/commit/19dc0fc8cdb97729a14a61e6d83568f05c3802c6) | [Issue #1956914 by pounard, David_Rothstein, chaby: Use a single cache_get_multiple() call per region instead of a cache_get() per block in _block_render_blocks().](http://drupal.org/node/1956914)

**Comment by Dinornis** [comment]
Looking at `/admin/config/development/performance` looks like block cache has been removed already?

**Comment by jenlampton** [comment]
There are still cache settings per block via the block API. I think we removed the checkbox in the UI (since that wouldn't work how people expect anymore) but there are still bits and pieces we should rethink or remove.

**Comment by docwilmot** [comment]
Its just been brought to my attention that block cache constants are still in use in core: https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/group/block_caching/1
There is no code in Layout module for handling block cache. We should figure out what to do with that documentation.
