### ISSUE TITLE
[META] Clean up variables in preprocess layer

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#244]
We spend a lot of time in the preprocess layer preparing variables that are never used, or doing work that could just as easily be done in the templates themselves. For each of the template files listed below we'll need to do the following:
- Remove variables that are not explicitly printed
- Move formatting functions (ex: format_date) into the template files themselves
- Update docblocks in template files to match updated variables

We'll need to go through this process for the following (most-important) templates:
- [ ] #xx | Cleanup variables for page.tpl.php
- [ ] #xx | Cleanup variables for node.tpl.php
- [ ] #xx | Cleanup variables for comment.tpl.php
- [ ] #xx | Cleanup variables for user.tpl.php
- [ ] #xx | Cleanup variables for taxonomy-term.tpl.php
- [ ] #xx | Cleanup variables for block.tpl.php
- [ ] #xx | Review variables for field.tpl.php
