### ISSUE TITLE
Release Backdrop 1.5.3 checklist.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#2470]
Backdrop 1.5.3 Checklist
==================================

## Pre-release tasks

- [x] Merge commits @quicksketch, @serundeputy

## Release tasks

- [x] Tag for release @quicksketch
- [x] ~~Update the front page download link on b.org.~~ moot for this one since we will use `1.6.0`
- [x] Create release notes on GitHub @quicksketch, @jenlampton

## Post-release tasks

- [x] ~~Update the docker image to the latest @serundeputy~~ (moot because of 1.6.0 release)
- [x] ~~Push the bug-fix release to the Pantheon repository~~ (moot because of 1.6.0 release)

**Comment by quicksketch** [comment]
As we're releasing 1.6.0 later today, most items in the normal checklist won't need to be completed. See the 1.6.0 release issue at https://github.com/backdrop/backdrop-issues/issues/2471.

**Comment by serundeputy** [comment]
Looks like we got everything.  Nice job everyone! closing.
