### ISSUE TITLE
Backdrop Release 1.6.0 Checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2471]
Backdrop Release 1.6.0 Checklist
===========================

## Pre-release tasks

- [x] Merge commits @quicksketch, @serundeputy
- [x] Prepare release news post on backdropcms.org. https://github.com/backdrop-ops/backdropcms.org/issues/330

## Release tasks

- [x] Update the tag in bootstrap.inc @quicksketch
- [x] Tag for release @quicksketch
- [x] Revert the tag in bootstrap.inc @quicksketch
- [x] Update the front page download link on b.org.
- [x] Create release notes on GitHub @quicksketch, @jenlampton

## Post-release tasks

- [x] Publish press release on backdropcms.org
- [x] Update the docker image to the latest @serundeputy
- [x] Allow 1 week grace period before pushing to Pantheon.
- [x] Push the minor release to the Pantheon repository

**Comment by quicksketch** [comment]
The last item that we have for changes is https://github.com/backdrop/backdrop-issues/issues/2408 (updating the CSS for messages). Which I'm hoping to get a @jenlampton review on in the next hour or so.

**Comment by jenlampton** [comment]
yes, on it now!

**Comment by quicksketch** [comment]
We're released! Blog post yet to be written though. With the holiday tomorrow, we'll be able to draft that up before the start of the week.

**Comment by quicksketch** [comment]
We've pushed to Pantheon after the release of 1.6.1 at https://github.com/backdrop/backdrop-issues/issues/2533.

**Comment by jenlampton** [comment]
*highfives*
