### ISSUE TITLE
Add normalize.css to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#250]
If we include it as a library, it can replace (much of) system.base.css. Additionally, it will make the seven theme consistent across browsers.  We should add it as a library right away, and then we can switch to using it when we do the admin theme rebrand in https://github.com/backdrop/backdrop-issues/issues/201

Here are the relevant D8 issues:
- [x] | #xx | [3c698fb](http://drupalcode.org/project/drupal.git/commit/3c698fb736cef22c56894d372c972e00b0eddfdc) | [Issue #723392 by ry5n, seutje, Jeff Burnz, JohnAlbin, sun: Tame seven's reset.css.](http://drupal.org/node/723392)
- [x] | #xx | [0311348](http://drupalcode.org/project/drupal.git/commit/0311348b08b14e8addad2f48bde8e1ee0db358e0) | [Issue #1986616 by echoz: Update normalize.css library.](http://drupal.org/node/1986616)
- [x] | #xx | [4b72c96](http://drupalcode.org/project/drupal.git/commit/4b72c96019aad7f96f7d38faf49dcd57cbe3bdb4) | [Issue #1839318 by JohnAlbin, echoz: Added Replace drupal.base.css library with normalize.css for all themes.](http://drupal.org/node/1839318)
- [x] | N/A | [c3b7575](http://drupalcode.org/project/drupal.git/commit/c3b7575ea323daedd7b5e3f5dd38484ab289822a) | [Issue #2100571 by tim.plunkett: Do not add normalize.css to stark.](http://drupal.org/node/2100571)

**Comment by mikemccaffrey** [comment]
We added normalize.css to core? That is great! Good job, guys.
