### ISSUE TITLE
1.6.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2582]
1.6.3 Release
==================================

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create a new bugfix release to follow the current version @quicksketch
- [x] Move all unfinished issues to the next bugfix release @quicksketch
- [x] Draft Release notes @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, push to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @jenlampton
- [x] Update the front page download link on b.org @jenlampton

## Post-release tasks

- [x] Push the bug-fix release to the Pantheon repository @quicksketch
- [x] Tweet that a new release is out @jenlampton
- [x] Update the docker image to the latest @serundeputy 
- [x] Update the Wikipedia articles to at least show the proper version number and date for latest release @klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by serundeputy** [comment]
docker image updated: https://github.com/docker-library/official-images/pull/2777
