### ISSUE TITLE
Drupal 7.28, 7.29, 7.30, 7.31 release crossports

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#262]
Drupal 7.28, 7.29, 7.30, 7.31 release issues need to be ported to Backdrop. Issues included:
- [x] | https://github.com/backdrop/backdrop/pull/342 | [3fbabe4](http://drupalcode.org/project/drupal.git/commit/3fbabe4158dd64da32f456ea80b502c6b3500736) | [Issue #1041486 by cs_shadow, lokapujya, eporama, Pancho: Fix docs for check_markup](http://drupal.org/node/1041486)
- [x] | N/A | [d2481b8](http://drupalcode.org/project/drupal.git/commit/d2481b8ce8b59d6024f1c9deb464d04ca29f54ad) | [Issue #2195357 by Rajendar Reddy, GoddamnNoise, Pol: Fix docs in hook_block_info()](http://drupal.org/node/2195357)
- [x] | https://github.com/backdrop/backdrop/pull/535 | [27304fc](http://drupalcode.org/project/drupal.git/commit/27304fc152198e86100619d367009a64b175f4cb) | [Issue #1885420 by cs_shadow, kim.pepper, xjm: Fix docs for metadata on node access queries](http://drupal.org/node/1885420)
- [x] | N/A | [79d304a](http://drupalcode.org/project/drupal.git/commit/79d304a98297ee8f4b9c6fd149fd1a679281d969) | [Issue #2234611 by visabhishek, cs_shadow, joachim: Fix up docs for drupalCreateRole test method](http://drupal.org/node/2234611)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [0736eee](http://drupalcode.org/project/drupal.git/commit/0736eee12f5d9e2142d9c0d0d0fd95b13abc2ecd) | [Issue #1068840 by sun, TR, Liam Morland, Pancho, Alan D., tim.plunkett, Damien Tournoud, droplet: Country codes missing from includes/iso.inc.](http://drupal.org/node/1068840)
- [x] | https://github.com/backdrop/backdrop/pull/535 | [0a74344](http://drupalcode.org/project/drupal.git/commit/0a743444a023f082a99951efb4e9c080648b2be4) | [Issue #2245057 by cs_shadow, joachim: Fix docs for entity_get_controller](http://drupal.org/node/2245057)
- [x] | N/A | [f4a8b00](http://drupalcode.org/project/drupal.git/commit/f4a8b00f992ca600f2b75ce41b309a582c0d5861) | [Issue #2244087 by cs_shadow, andrei.dincu, joachim: Add explanation comment in NodeCreationTestCase](http://drupal.org/node/2244087)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [1150ea8](http://drupalcode.org/project/drupal.git/commit/1150ea82c078328b42fe8af9e8b95a2ab96ca67c) | [Issue #2169065 by MF82, dcam, nadja.jury, danmuzyka: Fix up some docs in search tests](http://drupal.org/node/2169065)
- [x] | N/A | [c32199c](http://drupalcode.org/project/drupal.git/commit/c32199c82b0262ec2a1879e2f211263c0911a11a) | [Issue #2165143 by MF82, mgifford: Fix tigger misspell in node.test](http://drupal.org/node/2165143)
- [x] | N/A | [478d1a0](http://drupalcode.org/project/drupal.git/commit/478d1a04962de0ae6ef93fc2bde0c751840d36e6) | [Issue #61456 by Albert Volkman, jeffschuler, David_Rothstein, jdefay, edmund.kwok, pillarsdotnet, xjm, alex_b, csevb10, Steve Dondley: Write tests for issues with aggregator titles displaying quotes and other characters with HTML entity equivalents badly.](http://drupal.org/node/61456)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [f91bb95](http://drupalcode.org/project/drupal.git/commit/f91bb951d18a50653cb1937f89b6e7134817c29b) | [Issue #2106129 by brad.bulger, mmilano: Fix PHP notice in drupal_valid_path(): Undefined variable: form_item.](http://drupal.org/node/2106129)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [9fb4d89](http://drupalcode.org/project/drupal.git/commit/9fb4d89ae8f875efd44de30a566baddc3e499b2e) | [Issue #2065917 by SpadXIII, andrewbelcher, kboopathi: SelectQueryExtender::hasAnyTag uses hasAnyTags which doesn't exist.](http://drupal.org/node/2065917)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [b852638](http://drupalcode.org/project/drupal.git/commit/b852638c1b31da62f9ab86918ac0c2a8d06af2f4) | [Issue #2227687 by cs_shadow | Cottser: Slightly ugly error message if a module is incompatible with the version of core and the PHP version.](http://drupal.org/node/2227687)
- [x] | N/A | [ee60a20](http://drupalcode.org/project/drupal.git/commit/ee60a20fc3544497a0f37f9ce3846b2396a84263) | [Issue #2159549 by Dave Reid: File_save() and file_delete() do not clear entity controller cache.](http://drupal.org/node/2159549)
- [x] | N/A | [972e6a9](http://drupalcode.org/project/drupal.git/commit/972e6a9a3d66139cffba44313eac95e717e34843) | [Issue #2130461 by Alan D.: Tracker pager is inconsistent with every other pager in core.](http://drupal.org/node/2130461)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [808a61a](http://drupalcode.org/project/drupal.git/commit/808a61aef282f43f55bf9d8db1de8d947f32e357) | [Issue #1333292 by dcam, mgifford | Everett Zufelt: Screen-reader users receive no info about file upload errors.](http://drupal.org/node/1333292)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [07a910e](http://drupalcode.org/project/drupal.git/commit/07a910ede989af178d98c92aff7080bc027a06ce) | [Issue #2021933 by Crell, David_Rothstein, joachim, lz1irq: Catch exceptions from queue workers.](http://drupal.org/node/2021933)
- [x] | N/A | [dd8e45a](http://drupalcode.org/project/drupal.git/commit/dd8e45aef1e498daad70823a06a73423d0341ad8) | [Issue #1969108 by danblack, cs_shadow | Robert S: INSTALL.mysql.txt does not mention CREATE TEMPORARY TABLES and it should.](http://drupal.org/node/1969108)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [e25cbd6](http://drupalcode.org/project/drupal.git/commit/e25cbd60fcba5a14778af4ffeb6515d5624eb0ac) | [Issue #2182315 by joachim: Simpletest verbose output doesn't show end result of a drupalPostAjaxForm().](http://drupal.org/node/2182315)
- [x] | N/A | [106a1e1](http://drupalcode.org/project/drupal.git/commit/106a1e1adbb4e8ac1329a88208906cdde8076e48) | [Issue #1468686 by ordermind, paranojik, andrewbelcher, xps, Georgique, rlmumford, gapple, dsdeiz, tim.plunkett: File_field_widget_submit(), file.field.inc was using the wrong parent key.](http://drupal.org/node/1468686)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [23d45a3](http://drupalcode.org/project/drupal.git/commit/23d45a332e385165f1f7ba788b2a0d84f79492a2) | [Issue #2161955 by wiifm, mikeytown2, dawehner: Remove get_extension_funcs() call to improve HHVM compatibility .](http://drupal.org/node/2161955)
- [x] | N/A | [00e500b](http://drupalcode.org/project/drupal.git/commit/00e500bbb1b487de635debd5aabd55d5f400b3d8) | [Issue #1790298 by nagba, pwolanin: Unindexed query in aggregator module.](http://drupal.org/node/1790298)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [57bd962](http://drupalcode.org/project/drupal.git/commit/57bd9625f312ad4edea6b9fc45589b5be3a7933b) | [Issue #1191660 by ParisLiakos, Jon_B: Add Tag to Filter Query in admin/content/node.](http://drupal.org/node/1191660)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [20c04c5](http://drupalcode.org/project/drupal.git/commit/20c04c587beb78094cdc1302f9c226af8931747c) | [Issue #1868972 by jweowu, DanChadwick: Db_query_temporary() fails to create a table when the SQL has leading whitespace.](http://drupal.org/node/1868972)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [e928b85](http://drupalcode.org/project/drupal.git/commit/e928b8537bc2987ab4c1a0b5f944eed1957b253c) | [Issue #1300920 by salvis, DamienMcKenna, mkadin, idflood, pjcdawkins, lyricnz, greggles, Niklas Fiekas, gumanist | Dave Reid: The [node:summary] token does not output anything for body fields without a manual summary.](http://drupal.org/node/1300920)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [56670b3](http://drupalcode.org/project/drupal.git/commit/56670b32a07fcf0628271e551bfad54fd94a953f) | [Issue #1200478 by mitron, pounard, David_Rothstein | nicholasThompson: Incorrect setting of the 'class' attribute to a string in the Comment module (could cause fatal errors under rare conditions).](http://drupal.org/node/1200478)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [0c389ed](http://drupalcode.org/project/drupal.git/commit/0c389ed1c55930761dc851dbf3c2fcc9201c85b1) | [Issue #1788060 by BarisW, swentel, dcam | hass: Translatable string <Hidden> cannot imported if translated.](http://drupal.org/node/1788060)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [55b9d54](http://drupalcode.org/project/drupal.git/commit/55b9d543abaec185a0832e73495d27bd05a18021) | [Issue #1525176 by klausi, amateescu, David_Rothstein, dlu, goldenboy, lucascaro, naveko, Georgique, webchick: Using array_diff_assoc() for multilevel arrays in DrupalDefaultEntityController->cacheGet().](http://drupal.org/node/1525176)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [9d55871](http://drupalcode.org/project/drupal.git/commit/9d558710106ff03e1ad4f55e447e24f62333b9f4) | [Issue #1522348 by seanB, jenlampton | Adam S: Notice: getimagesize read error in image_gd_get_info().](http://drupal.org/node/1522348)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [709a0a5](http://drupalcode.org/project/drupal.git/commit/709a0a5a33afb11f192d638d260c71e9069e10d7) | [Issue #2143461 by Sneakyvv: drupal_get_query_array() does not work correctly if a query parameter contains an equals sign.](http://drupal.org/node/2143461)
- [x] | https://github.com/backdrop/backdrop/pull/535 | [5a84df0](http://drupalcode.org/project/drupal.git/commit/5a84df030977e635a2457996d87e8a0c31b821ad) | [Issue #952394 by xjm, webchick, sun, catch | yettyn: "No available releases found" - fetching update information exceeds timeout.](http://drupal.org/node/952394)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [5945c30](http://drupalcode.org/project/drupal.git/commit/5945c30693916783bbfafb5e92d456acddb0893d) | [Issue #2245331 by bendikrb: Use of reserved word in ajax.js breaks IE8.](http://drupal.org/node/2245331)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [4172af5](http://drupalcode.org/project/drupal.git/commit/4172af50d9f090cee9f96ba267f1ba8022228407) | [Issue #2259361 by jweowu, David_Rothstein: Document that db_query_temporary() only works on SELECT queries](http://drupal.org/node/2259361)
- [x] | https://github.com/backdrop/backdrop/pull/342 | [076802c](http://drupalcode.org/project/drupal.git/commit/076802cadd307d6b980676c7a2bb6497d90a9cbf) | [Issue #2048395 by filijonka: Fix up group/topic membership for field hooks](http://drupal.org/node/2048395)
- [x] | https://github.com/backdrop/backdrop/pull/535 | [90de4ec](http://drupalcode.org/project/drupal.git/commit/90de4ecc146a7ed1ae169699b4e845619ffdb36b) | [Issue #1261846 by catch, dawehner, brianV, Berdir, sun, xjm, sandipmkhairnar, marvil07, chrisjlee, Cottser, amitgoyal, Elijah Lynn, er.pushpinderrana: Document 1 MB cache limit in cache functions](http://drupal.org/node/1261846)
- [x] | https://github.com/backdrop/backdrop/pull/535 | [b15cfbb](http://drupalcode.org/project/drupal.git/commit/b15cfbb7f821023174a3a909934bd8497331a6e9) | [Issue #2309549 by Bevan, er.pushpinderrana: Fix incorrect documentation of node-type-specific hooks](http://drupal.org/node/2309549)
- [x] | https://github.com/backdrop/backdrop/pull/535 | [7ca0dfe](http://drupalcode.org/project/drupal.git/commit/7ca0dfe310ed4f7e5cfc86eb554245b0434ed704) | [Issue #2309687 by eriksm: Fix typo in docs for verbose test class method](http://drupal.org/node/2309687)

The command for generating this list was: 
`git log 3fbabe4.. --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"`

where the commit `3fbabe4` is the starting point.
