### ISSUE TITLE
Remove t() from assert statements in tests

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#267]
The following issues are non-release blockers, but would be nice to have.  Pulling them out of the D7 backport issue so we can close that one. Also, novice :)
- [x] #xx | [4095c4e](http://drupalcode.org/project/drupal.git/commit/4095c4e8ff90fa5362a85cf5463866b7f6003a77) | [Issue #1797914 by lazysoundsystem, dcam, izus, Lars Toomre: Remove t() from test assertions in various system tests](http://drupal.org/node/1797914)
- [x] #xx | [f9b9022](http://drupalcode.org/project/drupal.git/commit/f9b90224caa14159b3d71b84fa8674f1f6665fbd) | [Issue #1797252 by dcam,  lazysoundsystem, pwieck, andypost, Lars Toomre, xjm: Remove t() from test assertions in file-related tests](http://drupal.org/node/1797252)
- [x] #xx | [cca1434](http://drupalcode.org/project/drupal.git/commit/cca14341f0afa7d00cccd05a865db46888ac70d4) | [Issue #1797508 by Lars Toomre, dcam, lazysoundsystem: Remove t() from test messages in search module](http://drupal.org/node/1797508)
- [x] #xx | [36fb9a2](http://drupalcode.org/project/drupal.git/commit/36fb9a26d43749085dad66eb8192fd8ed63afa82) | [Issue #1797372 by chrisjlee, lazysoundsystem, dcam, xjm, Lars Toomre: Remove t() from test assertions in path module](http://drupal.org/node/1797372)
- [x] #xx | [ba9798a](http://drupalcode.org/project/drupal.git/commit/ba9798a428145a74c6182294602f009d491d7b60) | [Issue #1797366 by Lars Toomre, lazysoundsystem, dcam: Remove t() from test assertions in translation module](http://drupal.org/node/1797366)
- [x] #xx | [1419cde](http://drupalcode.org/project/drupal.git/commit/1419cdeb3ad550d3ee647ddfc683ecce648ee6ee) | [Issue #1797200 by dcam, K.MacKenzie, Lars Toomre, xjm: Remove t() from test assertions in node.module tests](http://drupal.org/node/1797200)
- [x] #xx | [89f66ab](http://drupalcode.org/project/drupal.git/commit/89f66ab5131d32a5d15099764ab0f79789297db8) | [Issue #1797452 by dcam, izus, xjm, Lars Toomre: Remove t() from test asserts in various system tests](http://drupal.org/node/1797452)
- [x] #xx | [dcd81db](http://drupalcode.org/project/drupal.git/commit/dcd81db201c4e2d9d80f9b338fdad279a38e0968) | [Issue #1797410 by dcam, izus, Lars Toomre: Remove t() from test asserts in misc system tests](http://drupal.org/node/1797410)
- [x] #xx | [25150e7](http://drupalcode.org/project/drupal.git/commit/25150e7b60f6bf6d4d8fb8027e3199172b3f0e60) | [Issue #1797920 by dcam, izus, Lars Toomre: Remove t() from test asserts in misc system tests](http://drupal.org/node/1797920)
- [x] #xx | [8ee9e5a](http://drupalcode.org/project/drupal.git/commit/8ee9e5ab409021fbd250c7a093691c5a10f36ae2) | [Issue #1797926 by dcam, izus, Lars Toomre: Remove t() from test asserts in misc system tests](http://drupal.org/node/1797926)
- [x] #xx | [b61b0d7](http://drupalcode.org/project/drupal.git/commit/b61b0d72791f4e4f78acced2efd04a5dbe0f2723) | [Issue #1797318 by dcam, izus, xjm, Lars Toomre: Remove t() from test asserts in form system tests](http://drupal.org/node/1797318)
