### ISSUE TITLE
Drupal 7.51 commits: crossport or mark as NA.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2774]
- [x] N/A | [8b79f437f5](http://drupalcode.org/project/drupal.git/commit/8b79f437f564af5af02a8b3048fd03c39b7541f8) | [Issue #2766537 by bhavikshah9, mforbes: Missing asterisk in one line of default.settings.php documentation block](http://drupal.org/node/2766537)
- [x] | https://github.com/backdrop/backdrop/pull/1934 | [8e69582fa3](http://drupalcode.org/project/drupal.git/commit/8e69582fa301420d19bd53c90e587a4c6ab5a3b7) | [Issue #2738933 by id.medion, chishah92: Remove unused argument in the function call field_cache_clear()](http://drupal.org/node/2738933)
- [x] | https://github.com/backdrop/backdrop/pull/2002 | [97aa5e1f6b](http://drupalcode.org/project/drupal.git/commit/97aa5e1f6b56d4149cf58f33e7fa16eedcaeea9a) | [Issue #1784548 by btopro, Fabianx, Berdir, rbayliss, xaa: DB Log is missing watchdog table after enabling - Need to catch and ignore exceptions thrown in dblog_watchdog()](http://drupal.org/node/1784548)
- [x] | N/A | [3a34404da4](http://drupalcode.org/project/drupal.git/commit/3a34404da43003217e158fe5aef3d85fa99a1c4f) | [Issue #2764131: Missing modules warning instructions don't make sense for certain situations (such as for old Drupal 6 module entries in the system table)](http://drupal.org/node/2764131)
- [x] | https://github.com/backdrop/backdrop/pull/2002 | [3d5bcd3fbc](http://drupalcode.org/project/drupal.git/commit/3d5bcd3fbcfd891f85260d1db81e880195bf25f9) | [Issue #2051453 by hgoto, joyceg, prabhurajn654, Fabianx: syntax error in update_manager_update_form()](http://drupal.org/node/2051453)
- [x] | https://github.com/backdrop/backdrop/pull/2002 | [14bd92bc6f](http://drupalcode.org/project/drupal.git/commit/14bd92bc6f8fd0fd777e1e33557e886cd18a9054) | [Issue #2468537 by hgoto, cilefen: The update module does not check updates for the admin theme if it is disabled](http://drupal.org/node/2468537)
- [x] | N/A | [29473bdf1e](http://drupalcode.org/project/drupal.git/commit/29473bdf1e3fdfa59d6b72b785765df4b4a5c8d9) | [Issue #2784561 by stefan.r, GoZ, Fabianx: [D7] IpAddressBlockingTest is failing on DrupalCI for PHP 7](http://drupal.org/node/2784561)
- [x] | N/A | [29bc731269](http://drupalcode.org/project/drupal.git/commit/29bc731269e19170c569b1ef39a475d1a8af7541) | [Issue #1880224 by joelpittet, thedavidmeister, rooby, validoll, monta: Notice: Undefined index: value in theme_status_report() (line 2577 of modules/system/system.admin.inc)](http://drupal.org/node/1880224)
- [x] | N/A | [1dea1bf5b7](http://drupalcode.org/project/drupal.git/commit/1dea1bf5b7b0cd3c15144eaa3e6c2836eec486b0) | [Issue #2776439 by aerozeppelin, Novitsh, makbul_khan8: [D7] system_block_ip_action() adding empty IP record in blocked_ips table](http://drupal.org/node/2776439)
- [x] | N/A | [4a4f50448f](http://drupalcode.org/project/drupal.git/commit/4a4f50448f1a7e892a9f6df40c4a1dce0cd1d1a4) | [Issue #2764221 by stefan.r, vensires, Fabianx, fietserwin: utf8mb4IsSupported() shouldn't guess that InnoDB is the default engine](http://drupal.org/node/2764221)
- [x] | https://github.com/backdrop/backdrop/pull/2002 | [bbb3a197d2](http://drupalcode.org/project/drupal.git/commit/bbb3a197d2d98c87373c30a814a32b2b7deda700) | [Issue #2201615 by hgoto: locale_translate_edit_form_submit() should check is_string(), instead of !empty() for string](http://drupal.org/node/2201615)
- [x] | N/A | [865bbe48ea](http://drupalcode.org/project/drupal.git/commit/865bbe48ead6490343b222a0abf5d7a7cf97f7fa) | [Issue #2794155 by kiamlaluno: user_save() documentation has a note for Drupal 8 that is not anymore valid](http://drupal.org/node/2794155)
- [x] | N/A | [0c770aa8b4](http://drupalcode.org/project/drupal.git/commit/0c770aa8b46a64584f46346484df5237ef37c79b) | [Issue #2774725 by sandip27: Wrong hook is invoked (hook_aggregator_process() rather than hook_aggregator_process_info())](http://drupal.org/node/2774725)
- [x] | N/A | [809978d14d](http://drupalcode.org/project/drupal.git/commit/809978d14d3bb7f41b43f7784c062ef4c4dd45e8) | [Issue #2497259 by aerozeppelin, catch, tim.plunkett, alexpott: system_region_list() unnecessarily translates region names](http://drupal.org/node/2497259)
- [x] | https://github.com/backdrop/backdrop/pull/2002 | [df7b3fd272](http://drupalcode.org/project/drupal.git/commit/df7b3fd2727a0e5ea389bdf780958af0e7a04ed5) | [Issue #2672088 by joelpittet, stefan.r, daffie, catch, mikeytown2, Fabianx, dawehner: Add static cache to DatabaseConnection ::escapeDatabase(), ::escapeTable(), ::escapeField() and ::escapeAlias()](http://drupal.org/node/2672088)
- [x] | N/A  | [782dab135b](http://drupalcode.org/project/drupal.git/commit/782dab135b5226735bbf1b99b7cd9f9e0aadd139) | [Issue #1261002 by LewisNyman, Pere Orga, nod_, Trey, quicksketch, jessebeach, mglaman, blueshadow2911, sabsbrain, Fabianx: Draggable tables do not work on touch screen devices](http://drupal.org/node/1261002)
- [x] | https://github.com/backdrop/backdrop/pull/2003 | [27e42bdd67](http://drupalcode.org/project/drupal.git/commit/27e42bdd67125bee3fc9dafa0e9a32bdf786ec01) | [Issue #2459339 by hgoto, dagmar, klausi, kporras07, David_Rothstein, Fabianx: Log messages should be XSS filtered on display](http://drupal.org/node/2459339)
- [x] | N/A | [601cfa56ce](http://drupalcode.org/project/drupal.git/commit/601cfa56ce093e934edf6df9716d515a3c01137c) | [Issue #2720853 by joseph.olstad, donquixote, Fabianx, quicksketch: D7 Improve theme registry build performance by 85%](http://drupal.org/node/2720853)
- [x] | N/A | [d4d7a73eaa](http://drupalcode.org/project/drupal.git/commit/d4d7a73eaac2ea6310b6fe3d751ef7a8fd560416) | [Issue #2009584 by hgoto, jtwalters, rteijeiro, ry5n, emattias, Fabianx: Allow double underscores to pass through drupal_clean_css_identifier as per new CSS standards](http://drupal.org/node/2009584)
- [x] | https://github.com/backdrop/backdrop/pull/2003 | [5a6500dedc](http://drupalcode.org/project/drupal.git/commit/5a6500dedc8c71e6207fbbe6bd9a6262a5d9e8c3) | [Issue #1443342 by joseph.olstad, mikeytown2, LauraRocks, xjm, stefan.r, joelpittet, brianV, effulgentsia, Fabianx, Mac_Weber: Inline file_uri_scheme() in file_stream_wrapper_uri_normalize() and other file.inc functions](http://drupal.org/node/1443342)
- [x] | https://github.com/backdrop/backdrop/pull/2003 | [03b241d5c0](http://drupalcode.org/project/drupal.git/commit/03b241d5c0addc6fe82f90e6fcb0d36d0cc58660) | [Issue #2379947 by ndobromirov, othermachines, hgoto, David_Rothstein: Prevent maximum execution time from being exceeded for large .po files in _locale_import_po()](http://drupal.org/node/2379947)
- [x] | https://github.com/backdrop/backdrop/pull/2003 | [64a69f81f2](http://drupalcode.org/project/drupal.git/commit/64a69f81f2565da57c843d705199e315df50b437) | [Issue #2808789 by hanoii, nod_, heddn, geerlingguy, lokapujya, David_Rothstein, mangy.fox, xurizaemon, timfernihough, jibran, effulgentsia, j0rd, joelpittet, temkin, slashrsm, maxi Todorov, leewillis77, droplet, showrx, orbiteleven, opdavies, rooby, yechuah, shabana.navas, nikunjkotecha, ehj-52n, jhedstrom, sah62, edutrul, rfay, seutje, drupalshrek: Drupal alerts "An AJAX HTTP request terminated abnormally" during normal site operation, confusing site visitors/editors](http://drupal.org/node/2808789)
- [x] | N/A | [00e9ceb158](http://drupalcode.org/project/drupal.git/commit/00e9ceb1585bb55bb1e57d1d9214f52f9caeb69b) | [Issue #2762241 by David_Rothstein, wylbur: Missing default.profile from the file system](http://drupal.org/node/2762241)
- [x] | N/A | [18e46dc4fa](http://drupalcode.org/project/drupal.git/commit/18e46dc4fa0eb263617f36d442c6c6d3ea1c3169) | [Issue #2497259 by David_Rothstein: system_region_list() unnecessarily translates region names](http://drupal.org/node/2497259)

git command:
```
git log 7.50..7.51 --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)" > issues.txt
```
REGEX: Find: `(Issue #)(\w\w+)(.*?)(node\/)` Replace: `$1$2$3$4$2`

**Comment by klonos** [comment]
#2766537 is N/A. We have no `default.settings.php` file and our `settings.php` does not have the line in question.

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/1934 filed for [8e69582fa3](http://drupalcode.org/project/drupal.git/commit/8e69582fa301420d19bd53c90e587a4c6ab5a3b7) | [Issue #2738933 by id.medion, chishah92: Remove unused argument in the function call field_cache_clear()](http://drupal.org/node/2738933)

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2002 needs a little work, comments left on the PR. Test failures are legit on there, probably caused by the issues noted in the comments.

**Comment by quicksketch** [comment]
All ready PRs are merged, only https://github.com/backdrop/backdrop/pull/2002 remains, still needing a few minor updates.

**Comment by jenlampton** [comment]
PRs Fixed, and rebased.

**Comment by quicksketch** [comment]
Oops, except that last PR caused a subsequent test failure. I've opened https://github.com/backdrop/backdrop-issues/issues/2939 to address it.
