### ISSUE TITLE
Drupal 7.52 - Drupal 7.54 commits: crossport or mark as NA.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2775]
- [x] | N/A | [7b9af6b9e9](http://drupalcode.org/project/drupal.git/commit/7b9af6b9e9514c8cccb346315abc40475419aa0d) | [Issue #2825396 by pounard, Pol, Fabianx, David_Rothstein, SebCorbin: Enable modules to define theme engines](http://drupal.org/node/2825396)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [367700622c](http://drupalcode.org/project/drupal.git/commit/367700622c0d220187d7031cb33052201b96f752) | [Issue #1617918 by pfrenssen, stefan.r, Ayesh, Fabianx, rfay, tea.time: $form['#token'] = FALSE in custom form always causes validation error for anonymous users](http://drupal.org/node/1617918)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [7a94baeb94](http://drupalcode.org/project/drupal.git/commit/7a94baeb94781e8aba2ba104394ddab879bc83b7) | [Issue #2821441 by davic, droplet, David_Rothstein, Joe Keene, Fabianx, tory-w: Fixed that newer Chrome versions cannot drag and drop anymore on desktop after 7.51 update when jQuery is updated to 1.7-1.11.0](http://drupal.org/node/2821441)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [dc0064dd91](http://drupalcode.org/project/drupal.git/commit/dc0064dd917f7d38a37531aeaca09a9e75c78482) | [Issue #2715113 by anshuljain2k8, SwapS, dagmar, Fabianx, ndobromirov: Watchdog logging of all searches is performance hit; need ability to turn it off (7.x)](http://drupal.org/node/2715113)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [33013d38e0](http://drupalcode.org/project/drupal.git/commit/33013d38e0bf406f57b588cdbb912e7386c897f8) | [Issue #1569856 by wizonesolutions, faline, IvoryTierra, tstoeckler, sun, cebasqueira: Make CommentHelperCase support $modules like DrupalWebTestCase and make CommentNodeAccessTest use that](http://drupal.org/node/1569856)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [2e1c672337](http://drupalcode.org/project/drupal.git/commit/2e1c672337e7adb25fafe1b84bec6c77b6a52cd1) | [Issue #2237329 by cs_shadow, amgoncalves: comments in OptionsWidgetsTest are in the wrong place](http://drupal.org/node/2237329)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [cfe9983aa7](http://drupalcode.org/project/drupal.git/commit/cfe9983aa79338119998f77b3c7a3c8850cf044e) | [Issue #2821203 by plach: Factor out logic to detect HTTPS requests into an API function](http://drupal.org/node/2821203)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [4004b9f10c](http://drupalcode.org/project/drupal.git/commit/4004b9f10c5e7b8808b8458d57bf0a9f3ef600ec) | [Issue #767404 by das-peter, geru, Ketan Harit, nikhilsukul, Nitesh Sethia: theme_menu_tree() removes helpful data for theming custom menu trees](http://drupal.org/node/767404)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [31864beb3a](http://drupalcode.org/project/drupal.git/commit/31864beb3ab9c3cb9c550ffba9ead3e779ab1398) | [Issue #2042411 by aerozeppelin, generalredneck: Float field type not validating number with decimal point but no decimal numbers](http://drupal.org/node/2042411)
- [x] | https://github.com/backdrop/backdrop/pull/2004 | [82866f9c85](http://drupalcode.org/project/drupal.git/commit/82866f9c85998a3845cee53bfa2958875714cd88) | [Issue #2838650 by er.pushpinderrana: menu_cache_clear description contains duplicate word: cached cached](http://drupal.org/node/2838650)
- [x] | N/A | [223cd3435b](http://drupalcode.org/project/drupal.git/commit/223cd3435b23f6a9702d6eb147f3aac15d770d39) | [Issue #2779379 by sandip27: Minor Coding Standard Issue in color.test file](http://drupal.org/node/2779379)
- [x] | https://github.com/backdrop/backdrop/pull/2005 | [856aa8c85a](http://drupalcode.org/project/drupal.git/commit/856aa8c85a9fd9bcd06ee5261dcad5c7452de846) | [Issue #2724773 by Stevel: Translation tests fail on site with english language prefix (global $language_url is not reset in tests)](http://drupal.org/node/2724773)
- [x] | https://github.com/backdrop/backdrop/pull/2005 | [00b0726076](http://drupalcode.org/project/drupal.git/commit/00b07260760b15d00e4ba6a5df202236fbed04d5) | [Issue #2494221 by david_garcia, dagmar: Slow Log/Watchdog clear when there are lots of data](http://drupal.org/node/2494221)
- [x] | N/A | [8ad071fa68](http://drupalcode.org/project/drupal.git/commit/8ad071fa6884b5c012f2c3b5b4041ef092b7a846) | [Issue #1817748 by markpavlitski, hgoto, wavesailor, Sophie.SK: /admin/config/regional/date-time does not show the correct default format for short and medium format](http://drupal.org/node/1817748)
- [x] | https://github.com/backdrop/backdrop/pull/2005 | [6d92c0c1a7](http://drupalcode.org/project/drupal.git/commit/6d92c0c1a74b6b2d4454559e9f11976342ed4d2c) | [Issue #2637552 by vmachado, Fabianx: Use the drupal_static_fast pattern in drupal_html_id()](http://drupal.org/node/2637552)
- [x] | https://github.com/backdrop/backdrop/pull/1975 | [deb4de9b9c](http://drupalcode.org/project/drupal.git/commit/deb4de9b9c73dccf0221b3980ef6dbfbd4ebf05a) | [Issue #1884830 by pwolanin, dcam: Regression - replace md5 in Filter module calls with sha2 hashes](http://drupal.org/node/1884830)
- [x] | https://github.com/backdrop/backdrop/pull/2005 | [f1a3f532e2](http://drupalcode.org/project/drupal.git/commit/f1a3f532e271058b5ff05bd9f325078a70d78466) | [Issue #1792032 by aerozeppelin, bjorpe, lmeurs, ndobromirov, balsama: File validation error message not removed after subsequent upload of valid file](http://drupal.org/node/1792032)
- [x] | https://github.com/backdrop/backdrop/pull/2005 | [198ba65424](http://drupalcode.org/project/drupal.git/commit/198ba6542446b3d6513f2a7580c1e3b155146dd9) | [Issue #2107287 by BR0kEN: PHP 5.4 calls a new stream_metadata() method on stream wrappers not implemented by Drupal](http://drupal.org/node/2107287)
- [x] | https://github.com/backdrop/backdrop/pull/2005 | [2f3b6e8912](http://drupalcode.org/project/drupal.git/commit/2f3b6e8912866204ccb6eecafec2a280aa25c17d) | [Issue #878284 by jp.stacey: cache_set documentation should make lifetime clearer](http://drupal.org/node/878284)

git command
```
git log 7.51..7.54 --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)" > issues.txt
```

REGEX: Find: `(Issue #)(\w\w+)(.*?)(node\/)` Replace: `$1$2$3$4$2`

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/1975: Issue [#1884830](https://drupal.org/node/1884830) by pwolanin, dcam: Regression - replace md5 in Filter module calls with sha2 hashes

**Comment by quicksketch** [comment]
Thanks @opi! Feel free to combine multiple ports into a single PR (one commit per issue) if that reduces the porting process. If uncertain about one, split it off into it's own PR. I've merged https://github.com/backdrop/backdrop/pull/1975 into 1.x and 1.7.x.

**Comment by jenlampton** [comment]
PRs filed for all commits in this issue. Needs review :)

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2005 into 1.x and 1.8.x. Great job!

The remaining PR at https://github.com/backdrop/backdrop/pull/2004 covers the last of the issues but has some problems noted in a code review: https://github.com/backdrop/backdrop/pull/2004#pullrequestreview-65791985

**Comment by quicksketch** [comment]
Looks like the PR had been updated over a week ago but the tag wasn't updated here. I've re-reviewed it and there is only a few things lingering: https://github.com/backdrop/backdrop/pull/2004#pullrequestreview-88951387

I would be in support of dropping the `Issue #2825396 by pounard, Pol, Fabianx, David_Rothstein, SebCorbin: Enable modules to define theme engines` cross-port. If we're planning on removing theme engines entirely as a concept I don't think we should be expanding it.

**Comment by quicksketch** [comment]
I dropped the theme engine commit (marked N/A above now) and rebased to fix the saving of the new "search_logging" value. If tests are passing I think we're complete here.

**Comment by quicksketch** [comment]
Yay, finally merged https://github.com/backdrop/backdrop/pull/2004 into 1.x and 1.8.x. Another cross-porting issue finally closed. Thanks @opi and @jenlampton for completing these ports.
