### ISSUE TITLE
Drupal 7.55-7.56 commits: crossport or mark as NA.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2776]
- [x] | N/A | [8008df236b](http://drupalcode.org/project/drupal.git/commit/8008df236b80de0f202fd65537efb921fc5d528f) | [Issue #2877243 by David_Rothstein, karoop, joseph.olstad, deminy: DATE_RFC7231 already defined in PHP 7.0.19 and 7.1.5](http://drupal.org/node/2877243)
- [x] | N/A (#2771) | [370fd890d8](http://drupalcode.org/project/drupal.git/commit/370fd890d80232166edf1f286e367f9e771c0bbb) | [Issue #2880700 by David_Rothstein, cilefen, mpdonadio, xjm, Mile23: UserTimeZoneFunctionalTest fails on recent versions of PHP 7 and 7.1](http://drupal.org/node/2880700)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [1531198741](http://drupalcode.org/project/drupal.git/commit/1531198741e170a5aff02c93ea302409b4b2e6e4) | [Issue #2850773 by alexpott: Fix tempnam() usage in PHP 7.1](http://drupal.org/node/2850773)
- [x] | N/A | [f73b791a2f](http://drupalcode.org/project/drupal.git/commit/f73b791a2ff6e45b1da1bba9e4891b93257a76b1) | [Issue #2847325 by sammuell, John Morahan, mfb, sanduhrs, D34dMan, C_Logemann, xumepadismal, serg2, walterebert, David Grudl: Support RFC 5785 on Apache by whitelisting the .well-known directory](http://drupal.org/node/2847325)
- [x] | N/A | [c55fe935e5](http://drupalcode.org/project/drupal.git/commit/c55fe935e5c6dfc629c0a74d07d4c1d880f460eb) | [Issue #2819787 by chiranjeeb2410, shashikant_chauhan, stefan.r, Kartagis, naveenvalecha: The install message referencing insufficient PDO drivers links to the wrong documentation page](http://drupal.org/node/2819787)
- [x] | N/A | [833779ebf5](http://drupalcode.org/project/drupal.git/commit/833779ebf54b5ad16398bdc184ddd3ba79be18e1) | [Issue #1886868 by IRuslan, zvse: Unused $original_destination variable in file_unmanaged_copy()](http://drupal.org/node/1886868)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [950e456481](http://drupalcode.org/project/drupal.git/commit/950e45648154241f503f577bd76ecbbb7a9b8c74) | [Issue #2851665 by tameeshb: In the database schema.inc file, the class DatabaseSchema has no class documentation block](http://drupal.org/node/2851665)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [5abd299fb9](http://drupalcode.org/project/drupal.git/commit/5abd299fb91a91361626f1c1362be03e4c6b2a1b) | [Issue #1854074 by jp.stacey, jhodgdon, kiwimind: Docblock in field.tpl.php needs clarification in its reference to theme_field](http://drupal.org/node/1854074)
- [x] | https://github.com/backdrop/backdrop/pull/1976 | [7edef74f71](http://drupalcode.org/project/drupal.git/commit/7edef74f71b06595de99651c47c97fabd76b2189) | [Issue #2870289 by markcarver: file_ajax_upload() causes malformed Drupal.settings](http://drupal.org/node/2870289)
- [x] | N/A | [c9493f51e6](http://drupalcode.org/project/drupal.git/commit/c9493f51e6a383e6b27c1fcb828b2c52c0e9ab27) | [Issue #2883202 by David_Rothstein: Statistics module subtracts an empty string from an integer, causing PHP 7.1 test failures](http://drupal.org/node/2883202)
- [x] | NA | [cf56426868](http://drupalcode.org/project/drupal.git/commit/cf56426868d9dcf0f104f85879153989443435db) | [Issue #2807393 by armrus, joseph.olstad, pankajchaudhari: Console error on Firefox due to redeclared function argument in Drupal.formatPlural](http://drupal.org/node/2807393)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [ed5ad0faab](http://drupalcode.org/project/drupal.git/commit/ed5ad0faabe389460f425480fe5d595e3f1c8741) | [Issue #2289867 by joseph.olstad, jamesrward, dman, superspring, legolasbo, bceyssens, mdeletter, anrikun, Damien Tournoud: W3C HTML5 Validation error with PHP array-based query-strings built with url() containing [ ] characters](http://drupal.org/node/2289867)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [f5df7abbfa](http://drupalcode.org/project/drupal.git/commit/f5df7abbfaaf15cccd346bcad6b44698b179502c) | [Issue #2182265 by Sweetchuck, joseph.olstad, nod_, andrejsmuzikovs, Gábor Hojtsy, droplet, mr.baileys: Drupal.t() placeholder substitution doesn't always work correctly](http://drupal.org/node/2182265)
- [x] | NA | [de9aa2b7e0](http://drupalcode.org/project/drupal.git/commit/de9aa2b7e0ce6b9ecec16aee6ecb16aa92d7399d) | [Issue #1851530 by JvE, jcovington, tatarbj: Notice: Undefined index: status in _block_rehash()](http://drupal.org/node/1851530)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [0528883b9e](http://drupalcode.org/project/drupal.git/commit/0528883b9e5146cbe57d6d2f5606d7ccb3824014) | [Issue #1823504 by axel.rutz, michalis.kambi, Sylvain Lecoy: Unit tests (descendants of DrupalUnitTestCase) do not work when default site language is not English](http://drupal.org/node/1823504)
- [x] | N/A | [ff27da6b35](http://drupalcode.org/project/drupal.git/commit/ff27da6b35d70cfd601994394fab378ff1df3efb) | [Issue #1599774 by longwave, ben.bunk, Rob C, stefan.r, David_Rothstein, BTMash, kristofferwiklund, marcingy, mpdonadio, DuneBL, serundeputy, Letharion, quicksketch, alexpott, J-Lee, Morbus Iff: Drupal fails to boot with 503 error and .htaccess protections do not work on Apache 2.4 without mod_access_compat](http://drupal.org/node/1599774)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [039472e9dd](http://drupalcode.org/project/drupal.git/commit/039472e9dd657ce8aa2f9e5a3c4ab31e0f378364) | [Issue #1611430 by Berdir, brad.bulger, Stevel, sun, catch: Verbose debug output in unit tests relies on the database](http://drupal.org/node/1611430)
- [x] | N/A | [694c9fe1c9](http://drupalcode.org/project/drupal.git/commit/694c9fe1c9d59f515ca39b4b5d9e6fd5a07cd2f4) | [Issue #348815 by twistor, aerozeppelin, xjm, PROMES, nileema.jadhav, Jill L: Remove category from feed and feed items when category is deleted](http://drupal.org/node/348815)
- [x] | [#2077](https://github.com/backdrop/backdrop/pull/2077) | [ef9608dc1d](http://drupalcode.org/project/drupal.git/commit/ef9608dc1d8b7ef0eaa7b76b07b64a16f73e3bbe) | [Issue #2451449 by drumm: User's contact setting reverts to default when saving](http://drupal.org/node/2451449)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [948066265b](http://drupalcode.org/project/drupal.git/commit/948066265b8751b22e5014120ab74cf2c38eee70) | [Issue #2851725 by Jigar.addweb, tameeshb: Fix typos in various code comments in the includes directory](http://drupal.org/node/2851725)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [8a09ddd4e3](http://drupalcode.org/project/drupal.git/commit/8a09ddd4e39d31ed61a67d9e11ab53f4a0fa5ffd) | [Issue #2042239 by lucaslg, tbradbury, snehi, pkiraly, pjonckiere, oriol_e9g, ivanchaer, jhodgdon, chx, cilefen, David_Rothstein: Fix DeleteQuery::execute() return value documentation and DeleteQuery_sqlite documentation](http://drupal.org/node/2042239)
- [x] | NA | [8238d81c7e](http://drupalcode.org/project/drupal.git/commit/8238d81c7e9f3617463935aa36d5995a22d04730) | [Issue #2853160 by hgoto, smaaz: Variable $name is defined but not used in file_get_content_headers()](http://drupal.org/node/2853160)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [3047f785d5](http://drupalcode.org/project/drupal.git/commit/3047f785d569588cdf88a2efc88efab8cfd898c8) | [Issue #1858486 by idebr, David_Rothstein, trawekp, joseph.olstad, MrHaroldA, jhedstrom: Ajax call breaks Password Reset](http://drupal.org/node/1858486)
- [x] | https://github.com/backdrop/backdrop/pull/2090 | [19b0db81b3](http://drupalcode.org/project/drupal.git/commit/19b0db81b31e7c2f127c79d21e2fe5595946deba) | Drupal 7.56 (SA-CORE-2017-003) by alexpott, catch, cilefen, David_Rothstein, dokumori, greggles, iancawthorne, larowlan, mlhess, pwolanin, quicksketch, smaz, stefan.r, xjm

git command
```
git log 7.54..7.55 --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"
```
REGEX: Find: `(Issue #)(\w\w+)(.*?)(node\/)` Replace: `$1$2$3$4$2`

**Comment by opi** [comment]
[Issue #2807393 by armrus, joseph.olstad, pankajchaudhari: Console error on Firefox due to redeclared function argument in Drupal.formatPlural](http://drupal.org/node/2807393) is already fixed in [our codebase](https://github.com/backdrop/backdrop/blob/1.x/core/misc/backdrop.js#L244)

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/1976 needs review: Issue [2870289](https://drupal.org/node/2870289) by markcarver: file_ajax_upload() causes malformed Drupal.settings

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/1976 is a no-brainer, single-line change. RTBC from me. Thanks @opi 👍

**Comment by jlfranklin** [comment]
Updated issue: Noted #2771 is our fix for d.o issue #2880700.

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2077#issuecomment-359084405 needs some review and discussion about an issue followup (cc @quicksketch maybe)

**Comment by quicksketch** [comment]
Yay, merged https://github.com/backdrop/backdrop/pull/2090 into 1.9.x and 1.x, so Backdrop has full parity with the latest release of Drupal 7 core.
