### ISSUE TITLE
Backdrop 1.7.2 release todo list

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2795]
Steps to create a BUG-FIX release
==================================

## Pre-release tasks

- [x] Merge commits @serundeputy 
- [x] Create a new bugfix release to follow the current version @serundeputy 
- [x] Draft Release notes @serundeputy 
- [x] Move all unfinished issues to the next bugfix release @jenlampton
- [x] Draft [Security Advisory](https://backdropcms.org/security/backdrop-sa-core-2017-009) @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @serundeputy 
- [x] Tag for release, push to GitHub @serundeputy 
- [x] Revert version number back @serundeputy 
- [x] Create release notes on GitHub @serundeputy 
- [x] Update the front page download link on b.org. @jenlampton
- [x] Tweet that a new release is out @jenlampton
- If this is a security release:
  - [x] Publish Security Advisory on b.org @jenlampton
  - [x] Mark the release node on b.org as a security release (tick the checkbox) @jenlampton

## Post-release tasks (asap)

- [x] Update the docker image to the latest @serundeputy
- [x] Push the bug-fix release to the Pantheon repository @serundeputy
- [x] Update the Wikipedia articles to at least show the proper version number and date for latest release @klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by serundeputy** [comment]
Merged `1.7.2` tag into the `backdrop-pantheon` upstream.
- [x] Spun up a new site via `Try Out on Pantheon` button ... all is well
- [ ] Upgraded an existing site ... I was not able to update a `1.5.1` site (merge conflicts)
```
We were not able to perform the merge safely. See the Applying Upstream Updates doc for further debugging tips.
```
@quicksketch any ideas or anybody have say a Pantheon site on `1.7.1` that they can test?

**Comment by serundeputy** [comment]
full error:

```
CONFLICT (rename/rename): Rename "core/themes/basis/css/component/status-messages.css"->"web/core/themes/basis/css/component/status-messages.css" in branch "HEAD" rename "core/themes/basis/css/component/status-messages.css"->"core/modules/system/css/messages.theme.css" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/update/theme/update.theme.inc"->"web/core/modules/update/theme/update.theme.inc" in branch "HEAD" rename "core/modules/update/theme/update.theme.inc"->"core/modules/update/update.theme.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/views/views_handler_filter_file_status.inc"->"web/core/modules/system/views/views_handler_filter_file_status.inc" in branch "HEAD" rename "core/modules/system/views/views_handler_filter_file_status.inc"->"core/modules/file/views/views_handler_filter_file_status.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/views/views_handler_field_file_uri.inc"->"web/core/modules/system/views/views_handler_field_file_uri.inc" in branch "HEAD" rename "core/modules/system/views/views_handler_field_file_uri.inc"->"core/modules/file/views/views_handler_field_file_uri.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/views/views_handler_field_file_status.inc"->"web/core/modules/system/views/views_handler_field_file_status.inc" in branch "HEAD" rename "core/modules/system/views/views_handler_field_file_status.inc"->"core/modules/file/views/views_handler_field_file_status.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/views/views_handler_field_file_filemime.inc"->"web/core/modules/system/views/views_handler_field_file_filemime.inc" in branch "HEAD" rename "core/modules/system/views/views_handler_field_file_filemime.inc"->"core/modules/file/views/views_handler_field_file_filemime.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/views/views_handler_field_file_extension.inc"->"web/core/modules/system/views/views_handler_field_file_extension.inc" in branch "HEAD" rename "core/modules/system/views/views_handler_field_file_extension.inc"->"core/modules/file/views/views_handler_field_file_extension.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/views/views_handler_field_file.inc"->"web/core/modules/system/views/views_handler_field_file.inc" in branch "HEAD" rename "core/modules/system/views/views_handler_field_file.inc"->"core/modules/file/views/views_handler_field_file.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/views/views_handler_argument_file_fid.inc"->"web/core/modules/system/views/views_handler_argument_file_fid.inc" in branch "HEAD" rename "core/modules/system/views/views_handler_argument_file_fid.inc"->"core/modules/file/views/views_handler_argument_file_fid.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/rename): Rename "core/modules/system/file.entity.inc"->"web/core/modules/system/file.entity.inc" in branch "HEAD" rename "core/modules/system/file.entity.inc"->"core/modules/file/file.entity.inc" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/delete): web/core/modules/redirect/js/redirect.admin.js deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/modules/redirect/js/redirect.admin.js left in tree.,CONFLICT (rename/rename): Rename "core/misc/ckeditor/skins/moono/images/spinner.gif"->"web/core/misc/ckeditor/skins/moono/images/spinner.gif" in branch "HEAD" rename "core/misc/ckeditor/skins/moono/images/spinner.gif"->"core/misc/ckeditor/skins/moono-lisa/images/spinner.gif" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/refresh.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/refresh.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/lock.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/lock.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/lock-open.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/lock-open.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/hidpi/refresh.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/hidpi/refresh.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/hidpi/lock.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/hidpi/lock.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/hidpi/lock-open.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/hidpi/lock-open.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/hidpi/close.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/hidpi/close.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/images/close.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/images/close.png left in tree.,CONFLICT (rename/rename): Rename "core/misc/ckeditor/skins/moono/images/arrow.png"->"web/core/misc/ckeditor/skins/moono/images/arrow.png" in branch "HEAD" rename "core/misc/ckeditor/skins/moono/images/arrow.png"->"core/misc/ckeditor/skins/moono-lisa/images/arrow.png" in "d75e164f03048f647426f60b77984e8409329db0",CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/editor_iequirks.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/editor_iequirks.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/editor_ie8.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/editor_ie8.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/editor_ie7.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/editor_ie7.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/editor_ie.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/editor_ie.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/editor_gecko.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/editor_gecko.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/editor.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/editor.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/dialog_iequirks.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/dialog_iequirks.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/dialog_ie8.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/dialog_ie8.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/dialog_ie7.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/dialog_ie7.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/dialog_ie.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/dialog_ie.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/skins/moono/dialog.css deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/skins/moono/dialog.css left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/plugins/icons_hidpi.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/plugins/icons_hidpi.png left in tree.,CONFLICT (rename/delete): web/core/misc/ckeditor/plugins/icons.png deleted in d75e164f03048f647426f60b77984e8409329db0 and renamed in HEAD. Version HEAD of web/core/misc/ckeditor/plugins/icons.png left in tree.
```

**Comment by jenlampton** [comment]
I have a pantheon site I can test. will do that now...

**Comment by jenlampton** [comment]
I've updatet a site from 1.6.3 on pantheon. I checked the "Auto-resolve conflicts" box. Everything merged without a problem. I'll try another site...

**Comment by jenlampton** [comment]
The Second site I updated was 1.7.1. Also no merge conflicts here. I think we're fine. :)

**Comment by serundeputy** [comment]
Thanks @jenlampton !

**Comment by serundeputy** [comment]
Updated Backdrop Docker Image; awaiting PR to be merged:
https://github.com/docker-library/official-images/pull/3354

**Comment by klonos** [comment]
Updated Wikipedia articles. Anything other task pending, or can close?

**Comment by jenlampton** [comment]
Can close :) and ty!
