### ISSUE TITLE
[META] icon cleanup in core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2814]
There are several places in core where we have icons. I would like to see them treated consistently, with a file-naming convention that allows people to understand what they are at first glance. 

We should replace any old icons with new, larger font-awesome equivalent versions as generated by http://fa2png.io. All icons are .pngs at 64px that we can size-down via CSS to look good on retina displays. Additionally, I would like to rename these files to include 1) the font-awesome name, 2) the color 3) the size. Note: These are based on what @wesruv did in [his PR](https://github.com/backdrop/backdrop/pull/1074)

Examples are as follows:

* chevron-right--gray--32.png
* caret-down--gray--32.png
* caret-up--gray--32.png
* check--green--32.png
* plus--blue--32.png

If we can use this issue to agree on a naming convention, we can use each of these sub-issues to do the cleanup:

* [x] https://github.com/backdrop/backdrop-issues/issues/2802 | Seven theme (core/themes/seven)
* [ ] https://github.com/backdrop/backdrop-issues/issues/2816 | Bartik theme (core/themes/bartik)
* [ ] https://github.com/backdrop/backdrop-issues/issues/2815 | Misc (core/misc)
* [ ] https://github.com/backdrop/backdrop-issues/issues/2834 | Installer module

**Comment by opi** [comment]
The `<name>--<color>--<size>.png` pattern is good. It reminds me the [BEM](http://getbem.com/naming/) with 2 modifier level.

**Comment by jenlampton** [comment]
Should we always include color and size, or do you think that if the icons were, say, black and 64px, they could be omitted? (see https://github.com/backdrop/backdrop-issues/issues/2802)

**Comment by jenlampton** [comment]
From chat:

> always, I guess. Makes it easier to process in batch, with some command line stuff for example.
And I don't know what the default is !

**Comment by klonos** [comment]
I think that we should always mention the same things in the filenames for all files, even the "default" ones. Reasons being a) not everyone knows what the "default" is b) the defaults might change from theme to theme and c) consistency.

**Comment by jenlampton** [comment]
Sounds good, I'll make the change.
