### ISSUE TITLE
[META] Clean up description all over the menu block form

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2861]
## Describe your issue or idea

The menu block configuration form has a LOT of words on it. Have this much explanation of what's on the form is off-putting to users, and will cause them not to read it. We should make sure that if we need to add descriptions to our form elements, that the descriptions are adding real value to the user.

* [ ] https://github.com/backdrop/backdrop-issues/issues/2860 Remove or improve description text on Menu Block "Menu style" setting
* [ ]  https://github.com/backdrop/backdrop-issues/issues/2859 Clean up the description test on menu block setting "Starting level"
* [ ]  https://github.com/backdrop/backdrop-issues/issues/2862 Clean up description text on menu block 'Show all menu links' checkbox
