### ISSUE TITLE
[META] Contact module improvements

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#3023]
Gathering issues about the contact module

## To-do (by chronological order of issue raised - not by priority)
- [ ] #1571 | [UX] Have contact.module enabled by default on the standard profile.
- [ ] #1572 | [UX] Have a "Contact" menu item be enabled and added to the primary navigation...
  PR https://github.com/backdrop/backdrop/pull/2145
- [ ] #3222 | Add `Use the site-wide contact form` permission to anonymous by default?
- [ ] #3568 | Contact form message templates edited via the UI
- [ ] #4292 | Add permission for users to be able to administer their own contact form
- [ ] #4721 | Add markup or message field to contact form

## Done
- [x] ~#2872 | [UX] Improve the recipients field in contact category form
  PR https://github.com/backdrop/backdrop/pull/2147~ **Merged in 1.11.0**
- [x] ~#2990 | [UX] Settings form for contact module
  PR https://github.com/backdrop/backdrop/pull/2105~ **Merged in 1.11.0**
- [x] ~#3047 | [UX] Add phone field for Contact forms~
- [x] ~#3052 | [UX] Draggable contact categories
  PR https://github.com/backdrop/backdrop/pull/2146~ **Merged in 1.10.0**
- [x] ~#3053 | [UX] Add a site-wide contact form block
  PR https://github.com/backdrop/backdrop/pull/2294~ **Merged in 1.12.0**
- [x] ~#3190 | [UX] Allow contact form permissions to be set on the contact settings page
  PR https://github.com/backdrop/backdrop/pull/2258~ **Merged in 1.11.0**
- [x] ~#3192 | [UX] Better labels and help text for the Contact module settings form (follow-up to #2990)
  PR https://github.com/backdrop/backdrop/pull/2226~ **Merged in 1.11.0**
- [x] ~#3215 | [UX] Contact form categories: better messages
  PR https://github.com/backdrop/backdrop/pull/2257~ **Merged in 1.11.0**
- [x] ~#3216 | [UX] Contact form categories: recipients should be rendered as a list
  PR https://github.com/backdrop/backdrop/pull/2256~ **Merged in 1.11.0**
- [x] ~#3217 | [UX] Contact form categories: add a 'Cancel' button to the configuration form
  PR https://github.com/backdrop/backdrop/pull/2255~ **Merged in 1.10.0**
- [x] ~#4145 | Contact form categories menu item generates error~

Some old meta and discussions issue about contact module
- [x] #1168 | [META] [UX] Simplify/automate the process of creating a website contact form.
- [x] #569 | Contact module improvements (*talking about enabling menu link like #1572, and a warning about permissions*) 

Other topics to discuss imho are:

* storage of submissions (or should we leave this to the webform module)

**Comment by jenlampton** [comment]
I would *love* to se a contact form block in core!  This is something I see a lot in designs, and I need to use webform to achieve it. Would be great if we could get that in core instead.

**Comment by oadaeh** [comment]
It seems to me that many of the requested improvements would be trivial for a site builder, if the forms were implemented as fieldable entities, like [Entityform](https://www.drupal.org/project/entityform) does.

**Comment by jenlampton** [comment]
I'm concerned about the last two items:

* [UX] Have contact.module enabled by default on the standard profile. #1571
*  Add Use the site-wide contact form permission to anonymous by default?

Primarily because the contact form can be an attack vector. Sometimes it's just spam and not malicious, but it's always an annoyance. I don't think we should do either of these things until we get some better spam protection in core. Something like https://github.com/backdrop/backdrop-issues/issues/1169

**Comment by BWPanda** [comment]
> I'm concerned about the last two items...

I want those two items added/changed in core, I think they're useful. But I agree that we would then need an anti-spam measure added to and enabled in core too.

**Comment by klonos** [comment]
Tagging this issue with the new "needs usage metrics" tag. We should not let the decision of whether this should be on by default on the default profile and the anonymous permission block this issue. We should implement what is safest (off by default), and adapt in the future as we gather more metrics.

**Comment by jlfranklin** [comment]
I agree it should be off by default.  The contact form should be opt-in for the site owner, not opt-out.

**Comment by klonos** [comment]
Precisely! ...if simply enabling the contact module automates things like creating menu links, and enabling "things", or configuring permissions etc., then we're good. Just lower the amount of actions required by the site admin in order to set sensible defaults and to get a simple contact form going.

**Comment by jenlampton** [comment]
removing milestone from the meta, we can add to sub-issues as needed.
