### ISSUE TITLE
1.9.5 release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3055]
## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create a new bugfix release @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton
- [x] Draft Release notes @serundeputy
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)
- If this is a security release:
  - [x] Draft Security Advisory @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub @serundeputy
- [x] Update the front page download link on b.org @jenlampton
- [x] Tweet that a new release is out @jenlampton
- If this is a security release:
  - [x] Publish Security Advisory on b.org @serundeputy
  - [x] Mark the 1.9 release node on b.org as a security release @jenlampton 
  - [x] Mark the 1.8 release node on b.org as a security release @jenlampton 

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @serundeputy 
- [x] Push the bug-fix release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop) @serundeputy 
- [x] Update the docker image @jenlampton 
- [x] Update the Wikipedia articles @klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by jenlampton** [comment]
@serundeputy has the docker image been updated to 1.9.5 (or 1.9.6) or does it still have a huge security hole in it? :)

**Comment by jenlampton** [comment]
@serundeputy also if you can document how to update that image we can find a new maintainer for it so I can stop asking you ;)

**Comment by serundeputy** [comment]
@jenlampton https://github.com/backdrop/backdrop-issues/blob/master/procedures/docs/backdrop-docker-image.md
@klonos it's all yours 🍶 ;

**Comment by jenlampton** [comment]
I'm giving it a try...  I'd like to feel how much work this is to maintain.

**Comment by jenlampton** [comment]
Okay, I've filed [a PR](https://github.com/docker-library/official-images/pull/4371) that updates the latest docker image from 1.9.3 to 1.10.0.  

I'm not sure what happens after the PR is submitted.  Is it supposed to be reviewed by the folks over at @docker? If so, how long does that usually take? 

Is there anything special we need to include in the PR? Do we need a matching issue? 

Also, I've added myself as a maintainer, I'm not sure if that needs to be done in a separate step... If you have any additional info you think might be valuable @serundeputy, let me know!

**Comment by serundeputy** [comment]
> I'm not sure what happens after the PR is submitted. Is it supposed to be reviewed by the folks over at @docker? If so, how long does that usually take?

  * usually takes 2 to 48 hours.

> Is there anything special we need to include in the PR? Do we need a matching issue?

  * nothing special; no issue needed (in fact they don't want one).

> Also, I've added myself as a maintainer, I'm not sure if that needs to be done in a separate step... If you have any additional info you think might be valuable @serundeputy, let me know!

  * @jenlampton maintainer ++;
  * Well done Jen!
