### ISSUE TITLE
[META][UX][A11Y] Make sure Basis and Seven adhere to WCAG 2.0 standards as much as possible.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3118]
I thought of this after #3066...

We should at the very least make sure that elements in the admin theme have enough contrast.

Resources that might help:

https://webaim.org/resources/contrastchecker

https://www.w3.org/WAI/standards-guidelines/wcag

Seven:
- [ ]  https://github.com/backdrop/backdrop-issues/issues/3990
- [x]  https://github.com/backdrop/backdrop-issues/issues/3066

Basis: 
- [ ]  https://github.com/backdrop/backdrop-issues/issues/4922
- [x]  https://github.com/backdrop/backdrop-issues/issues/5043

---
PR by @jenlampton https://github.com/backdrop/backdrop/pull/3711

**Comment by laryn** [comment]
http://a11yrocks.com/colorPalette/ ([via @misshelenasue](https://twitter.com/misshelenasue/status/997191573497679873?s=03))
