### ISSUE TITLE
[UX][META] Promote certain contrib projects in project browser.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3193]
Issue summary todo list:

* [x] use the promoted checkbox on backdropcms.org
* [ ] https://github.com/backdrop-contrib/project/issues/43 support promoted in project module feed
* [ ] https://github.com/backdrop-ops/backdropcms.org/issues/691 Update backdropcms.org to use latest project module changes
* [ ] use this feed value to add a class in core installer module
* [ ] add background colors and/or other decorations to installer list based on class (installer module or seven theme)

This is a follow-up to #1713...

In that issue we have discussed the possibility of adding "experimental" modules in core, same as D8 does for certain modules that are slated for inclusion in core at some later point:

![d8-experimental_modules_in_core](https://cloud.githubusercontent.com/assets/2423362/13727611/04c9a7c6-e94d-11e5-84e2-0d2e7764f759.png)

Although we have rejected that idea (for perfectly valid reasons), this feature serves the following purposes the way I see it:

1. Gives early adopters and testers an easy way to test these modules. The fact that these modules are included with core (though disabled by default) reduces the amount of steps required to enable and start testing them.

2. Makes features that are planned to be included in core more discoverable, so more people will use them early on, thus more feedback, which will ensure better results when the modules are finally merged.

...this has gotten me to think:

1. We are already making it easier for people to test modules, because the Project Browser and the Project Installer we have in core already reduce the steps they need to take. So we do not need to (and do not want to) ship any modules with core in an "experimental" status. (although admittedly one cannot use the Project Browser without internet access).

2. Adding these modules in the module management page does not necessarily expose them in all the right places where it makes more sense, or where people would expect to find them.

So this came to me after going through #3047: Why don't we use the new `info` type message (#3155) to place a message at the top of the Project Browser (and style the entries of these modules in the results to be standing out of the rest):

![promoted_modules](https://user-images.githubusercontent.com/2423362/42464994-1a620f36-83ee-11e8-8bd9-daccf84d7deb.png)

...we could also be promoting these modules independently in various sections of the UI where it makes sense. As a Drupal/Backdrop newcomer who does not know what contributed modules are available out there, it would be helpful to be pointed to the right direction. This following example promotes the Webform module in the core Contact module settings page (`/admin/structure/contact`):

<img width="896" alt="screen shot 2018-07-10 at 5 20 28 am" src="https://user-images.githubusercontent.com/2423362/42471440-076d6f66-8401-11e8-973b-c5cae5f27c50.png">

As a person that tries Backdrop for the first time, one would not be left with a "Seems I can't do this with Backdrop 😞 👎" feeling, but with a "Oh, Backdrop only offers this basic functionality OOTB, but I can do more it using this addon! 💡😄 👍".

**Comment by klonos** [comment]
I just noticed a new "Pinned repositories" feature offered by GitHub:

Perhaps this adds a flag that we can use in the script that parses the contrib projects, and then set a new "Promoted" checkbox accordingly in the project nodes in b.org(??).

@serundeputy ? @quicksketch ?

**Comment by klonos** [comment]
<img width="475" alt="screen shot 2018-10-27 at 11 59 22 am" src="https://user-images.githubusercontent.com/2423362/47597890-dcca9b00-d9df-11e8-845b-e21885177864.png">

**Comment by klonos** [comment]
...also pinned https://github.com/backdrop-contrib/save_draft as per #1383

**Comment by quicksketch** [comment]
Hm, quite interesting. As with other features, this would require integration between core code and the project feed from BackdropCMS.org. I'm not sure we need to re-use the GitHub "promoted" feature. Syncing that information between BackdropCMS.org and GitHub could just be extra work that we don't necessarily need. Re-using the "promoted" flag on the project nodes seems like a good idea though. I thought we had suggested other possible uses of "featured" modules at one point. Is it likely we'll want to have multiple kinds of promotion? e.g. "Candidate modules for core" (Reference) vs. "Popular contrib projects" (Webform)

**Comment by jenlampton** [comment]
> "Popular contrib projects" (Webform)

This is something that doesn't need to be manual flag, we can determine popularity by usage.

**Comment by klonos** [comment]
Hmm, we already have the "Most installed" filter, so people can sort by that if they want to go by usage stats.

The main intention here is to use the promoted projects feature for contrib that are targeted for possible inclusion in Backdrop core. In other words, the equivalent of experimental modules in D8.

What we are trying to do here is to avoid the pitfalls that the experimental modules have introduced in D8:

- risk for people enabling and using an experimental module, but that module does not make it into D8 core after all, so gets removed at a certain point.
- "locking" contrib to evolving at the same pace as core releases.

Because we have Project Browser in Backdrop, we can avoid those issues by recommending contrib modules and encouraging feedback, rather than including them directly in core.

**Comment by klonos** [comment]
...another way to supplement this in the future would be if Project Browser marked as promoted those projects that are not-yet-installed, but listed in the .info files of other currently-installed modules. This could be based in `recommends[] =` entries in .info files of module (see #119).

**Comment by jenlampton** [comment]
There's no PR here yet, and code freeze for 1.13 is in less than a week. We should get crackin' if we want this in the next release.

Do we have a clear statement of the work that needs to be done to make this happen? My guess is that there's no PR because nobody knows what to do :)

**Comment by jenlampton** [comment]
It's release day and there's still no PR. removing milestone, adding candidate tag.

**Comment by klonos** [comment]
Screenshot from the DrupalCon Driesnote, where Dries proposes to add a project browser to Drupal:

...it means that they may actually strat doing something about it, or start listening to those "forgotten users" (who either went away to Wordpress or other solutions, or forked Drupal)

^^ nice ideas of how modules/themes can be "promoted" or "featured".
