### ISSUE TITLE
Checklist for 1.10.2 release

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3287]
Scheduled for September 15, 2018 - 10am PT to 4pm PT.

## Pre-release tasks

- [x] Merge commits @quicksketch / @serundeputy 
- [x] Create a new bugfix release @serundeputy 
- [x] Create the next bugfix milestone @jenlampton
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton
- [x] Draft Release notes @serundeputy 
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @serundeputy 
- [x] Tag for release, and push tag to GitHub @serundeputy 
- [x] Revert version number back @serundeputy 
- [x] Create release notes on GitHub @serundeputy 
  - [x] Double check if any changes were made to files outside the `core` directory

## Post-release tasks

- [ ] Push the bug-fix release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @serundeputy 
- [ ] Push the bug-fix release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop) @serundeputy 
- [ ] Push the bug-fix release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @jenlampton

**Comment by quicksketch** [comment]
Upstreams will go to 1.11.0 instead of 1.10.2, so we're all finished here! Thanks @serundeputy for knocking this one out!
