### ISSUE TITLE
Checklist for 1.11.0 release

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3288]
Scheduled for September 15, 2018 - 10am PT to 4pm PT.

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Move all unfinished issues to the next bugfix release milestone @quicksketch
- [x] Draft Release notes @quicksketch 
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)
- [x] Draft blog post @stpaultim 
- [x] Draft roadmap updates for [backdropcms.org](https://backdropcms.org/roadmap) @stpaultim 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @quicksketch 
  - [x] Double check if any changes were made to files outside the `core` directory
- [x] Update the front page download link on b.org @stpaultim 
- [x] Tweet that a new release is out @jenlampton

## Post-release tasks

- [x] Push the minor release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @serundeputy
- [x] Push the minor release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop) @serundeputy
- [x] Push the minor release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @jenlampton 
- [x] Publish blog post @stpaultim 
- [ ] Send a newsletter via MailChimp @facetinteractive 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton
- [x] Update the roadmap on [backdropcms.org](https://backdropcms.org/roadmap) @stpaultim 
- [x] Update the Wikipedia articles @stpaultim 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

See the Accompanying Bug-Fix Release Checklist
----------------------------------------------
https://github.com/backdrop/backdrop-issues/issues/3287

**Comment by stpaultim** [comment]
Someone please check my work, but I think I got everything assigned to me. 

There is a comment in the source for the Wikipedia page that says to be sure and update the "history" table. But, I'm not seeing any history table. Did I miss anything, or has that been removed?

**Comment by serundeputy** [comment]
Updated Platform.sh to `1.11`.

**Comment by serundeputy** [comment]
Updated Pantheon to `1.10.2`.  Tested dashboard update on test site all is well.

**Comment by klonos** [comment]
@saintlynn I think that there was never a history table. Perhaps the initial wiki page was created from a template that included that(?) ...either that, or I am turning senile 😄. I do plan to add a release history section/table though (once the article is reinstated 😞 ).

**Comment by jenlampton** [comment]
Closing this old issue.
