### ISSUE TITLE
[META] Make Backdrop sites perform better OOTB in Google PageSpeed

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3302]
## Describe your issue or idea

When you run a new Backdrop site through the google PageSpeed Developer tool, it should get a better score without developers needing to "fix" a lot of things.

Here's the tool:
https://developers.google.com/speed/pagespeed/insights/

Here's a list of suggestions google makes to speed up load time:
- [ ]  Remove render-blocking JavaScript
- [ ]  Optimize CSS Delivery
- [ ] Leverage browser caching (see https://github.com/backdrop/backdrop-issues/issues/3937)
- [ ] Enable compression
- [ ] Minify HTML?
- [ ] Minify CSS automatically w aggregation
- [ ] Minify JavaScript automatically w aggregation
- [ ] [Minify key JS files](https://github.com/backdrop/backdrop-issues/issues/4830)
- [ ] Optimize images

Here are some Drupal contrib projects that we may want to consider for Backdrop core:
* [Minify](https://www.drupal.org/project/minify)
* [Advanced Agg](https://www.drupal.org/project/advagg)
* [Image optimize](https://www.drupal.org/project/imageapi_optimize)

**Comment by opi** [comment]
The `Minify` contrib module relies on Google Closure compiler external service ; A standalone minifier could be https://github.com/matthiasmullie/minify

**Comment by jenlampton** [comment]
I think we should minify CSS/JS automatically when it's aggregated. I wonder why this wasn't done when aggregation was added?

**Comment by oadaeh** [comment]
Advanced Agg is a bit of a beast, so I would not recommend including it in core, but instead, seeing what it does & how it does it, and then implementing only the desired functionality is the best way possible for Backdrop.

**Comment by domaingood** [comment]
I wold like you see those are in Backdrop Core from Drupal 8
Internal Dynamic Page Cache
Internal Page Cache
BigPipe
