### ISSUE TITLE
1.11.2 release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3324]
Steps to create a BUG-FIX release
==================================

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create a new bugfix release  (@quicksketch)
- [x] Create the next bugfix milestone  (@jenlampton)
- [x] Move all unfinished issues to the next bugfix release milestone (@jenlampton)
- [x] Draft Release notes (@jenlampton)
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - N/A Include changelog since last version (generated with drush rn)
- [x] Draft Security Advisory (@jenlampton)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub(@quicksketch)
- [x] Update the front page download link on b.org (@stpaultim)
- [x] Tweet that a new release is out(@quicksketch)
- [x] Publish Security Advisory on b.org (@quicksketch)
- [x] Mark the release node on b.org as a security release (@quicksketch)

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) (@quicksketch)
- [ ] Push the bug-fix release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop) (@serundeputy)
- [ ] Push the bug-fix release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) (@jenlampton)
~Update the Wikipedia articles (@stpaultim)~
~https://en.wikipedia.org/wiki/Backdrop_CMS~
~https://en.wikipedia.org/wiki/List_of_content_management_systems~

**Comment by jenlampton** [comment]
# Release notes:

Maintenance and security release for Backdrop CMS.

This release fixes security vulnerabilities. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

[Backdrop core - Multiple vulnerabilities - SA-CORE-2018-006](https://backdropcms.org/security/backdrop-sa-core-2018-006)
No other fixes are included.

No changes have been made to the .htaccess, robots.txt or default settings.php files, or any files outside the /core directory in this release, so upgrading custom versions of those files is not necessary.
