### ISSUE TITLE
[META] Improve internationalization in 1.x

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3369]
There are a number of improvements we can make in 1.x that are backwards compatible (items in bold are prioritised):

- [x] #225 | Make menu items translatable in core
- [x] #704 | [CMI] Add config translation
- [x] #904 | Add Transliteration in core
- [ ] #1638 | Changing the front page for the English language changes the other languages front page too.
- [x] #2637 | Transliteration doesn't respect site default language
- [x] #2934 | Translate taxonomy terms
- [x] #3455 | Identify translatable strings in core static config files
- [x] #3464 | Extend the translation module to include a block that can hold translated content.
- [x] #3498 | [Views][multilingual] Titles of views in blocks cannot be translated
- [ ] #3500 | Front page to be configurable by language
- [ ] #3515 | Assign translatable config for Content types, Fields, Layouts and Image Styles
- [ ] #4322 | Allow default/required settings on multilingual ("Language") fields

Misc:
- [ ] Localization server roadmap: https://github.com/backdrop-ops/localization/issues/5
- [ ] Extract translatable config strings: https://github.com/backdrop-contrib/potx/issues/9
- [ ] #4562 [D8][UX] Rename the "Locale" module to "Interface Translation"

**Comment by herbdool** [comment]
@docwilmot perhaps that could be a meta to this meta. I was thinking first of focusing on core and 1.x but I'm flexible. We also have "projects" in github which are pretty useful for tracking the progress on issues so this could be multiple issues as part of a Internationalization project.

**Comment by olafgrabienski** [comment]
I like to focus on core / 1.x in this issue. Doing so, I expect to also get an image of the (hopefully few) tasks that need to be done in contrib and infrastructure.

Some issues are even connected, take for instance the Backdrop localization server: At the moment, during a Backdrop installation in a language other than English, people get a link to the Drupal localization server. If we want to improve the installation experience, we have to have our own localization server, so it's (also) a core issue.

**Comment by docwilmot** [comment]
@olafgrabienski thats my point. we should ad the server issues to this META, because it is a 'core' issue then.

**Comment by olafgrabienski** [comment]
@herbdool I've added one issue to the description:


- Transliteration doesn't respect site default language https://github.com/backdrop/backdrop-issues/issues/2637

There are two PRs for the issue but it's still unclear what's the best way to proceed. Would be great if you could have a look at it and give some feedback!
