### ISSUE TITLE
1.11.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3427]
Steps to create a BUG-FIX release
==================================

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create a new bugfix release @quicksketch
- [x] Create the next bugfix milestone @jenlampton
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton
- [x] Draft Release notes @jenlampton
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @jenlampton 	
- [x] Update the front page download link on b.org @stpaultim
- [x] Tweet that a new release is out  @stpaultim

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch
- [ ] Push the bug-fix release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop) @serundeputy
- [x] Push the bug-fix release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @jenlampton
- [x] Update the Wikipedia articles @stpaultim
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by stpaultim** [comment]
Our wikipedia page is still broken: https://en.wikipedia.org/wiki/Backdrop_CMS

Were we listed here before? Because we're not on the list now. I can add us to the list, but I'm wondering if we need to wait until we figure out the other problem with our Wikipedia page.
https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by jenlampton** [comment]
Release notes draft: 
```

**Changes since 1.11.2**

* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3315">#3315</a>: [UX] "Add redirect" form has "URL redirects" as page title.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3323">#3323</a>: Typing a "/" in a field label stops the machine name autocomplete.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3296">#3296</a>: [UX] Sort the search CONTENT RANKING settings.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1547">#1547</a>: [UX] Move list of visibility conditions below "+ Add visibility condition".
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2736">#2736</a>: Rename Add text editor (back) to Add text format.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3330">#3330</a>: [UX] Performance: Bandwidth optimization proper warning.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3367">#3367</a>: [UX] Proper page titles for various "Add xyz" pages.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3394">#3394</a>: [UX] Better description for the breadcrumb block.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3365">#3365</a>: Don't replace hyphens with underscores in custom class names.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3412">#3412</a>: [UX] Permissions page: Use darker gray background for module-grouping rows.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3421">#3421</a>: [UX] Fix RTL Autocomplete style.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3392">#3392</a>: Change the description of the Bartik theme.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3305">#3305</a>: info message style affects "Available Updates" page. (<a href="https://github.com/backdrop/backdrop-issues/issues/2315">#2315</a>)
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3247">#3247</a>: [UX] Removing 'main content' block causes some page elements not to display.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2488">#2488</a>: Update Clean URLs messages and links. By @klonos, @hosef and @Graham-72.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2488">#2488</a>: Fixing the path for the clean URL test page.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3368">#3368</a>: [UX] The submit button in the "Add image style" page not styled as primary button.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3325">#3325</a>: Use WATCHDOG_* contants instead of numerical value.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3336">#3336</a>: Node preview: Page not found when machine names have an underscore.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3351">#3351</a>: Remove the word "easily" from code comments.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3351">#3351</a>: Remove unnecessary use of "simply" in comments.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3351">#3351</a>: Remove unnecessary use of "obviously" in docblocks.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3377">#3377</a>: Fix PHP error Undefined index in path path_entity_insert and path_delete_all_by_entity().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3398">#3398</a>: Default the status code to 500 before any other code is run.

```

**Comment by jenlampton** [comment]
Release notes draft: https://github.com/backdrop/backdrop/releases/edit/untagged-7824f634fa690f31ae55

**Comment by stpaultim** [comment]
We were removed from the list of CMSs on Wikipedia, because we don't have a page. See my comment here: https://github.com/backdrop-ops/backdropcms.org/issues/166

I'm afraid that putting us back on the list before our page is approved will have the opposite effect of helping us.

**Comment by jenlampton** [comment]
Understood @stpaultim thanks for looking into it thoroughly!

**Comment by jenlampton** [comment]
PR filed for Docker update: https://github.com/docker-library/official-images/pull/5175

**Comment by jenlampton** [comment]
Closing this issue in favor of https://github.com/backdrop/backdrop-issues/issues/3532
