### ISSUE TITLE
1.12.0 release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3473]
## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create a new bugfix release (@quicksketch) 
- [x] Create the next bugfix milestone (@jenlampton)
- [x] Move all unfinished issues to the next minor release milestone (@jenlampton)
- [x] Draft Release notes (@jenlampton) 
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)
- [x] Draft blog post (@stpaultim)
- [x] Draft roadmap updates for backdropcms.org (@jenlampton)

## Release tasks
 
- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub (@quicksketch)  
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub (@jenlampton)
- [x] Update the front page download link on b.org (@stpaultim)
- [x] Tweet that a new release is out (@stpaultim)

## Post-release tasks

- [ ] Push the minor release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) (assign to @quicksketch)
- [ ] Push the minor release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop) (@serundeputy)
- [ ] Push the minor release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) (@jenlampton)
- [x] Push the minor release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) (@quicksketch)
- [ ] Publish blog post (@stpaultim) 
- [ ] Send a newsletter via MailChimp (@facetinteractive)
- [x] email katie@phpweekly.com for a note in the PHP Weekly Newsletter (@jenlampton)
- [x] Publish roadmap updates for backdropcms.org (@jenlampton)
- [ ] Update the Wikipedia articles (assign @klonos )
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

See the Accompanying Bug-Fix Release Checklist
----------------------------------------------
* https://github.com/backdrop/backdrop-issues/issues/3474

**Comment by stpaultim** [comment]
Have been trying to help out, but pretty busy with other things. Had hoped to get an early start on Blog Post, but it did not happen. Will try to find time ASAP, but dealing with other client stuff now. Will post a note here if I find time to start Blog Post.

**Comment by jenlampton** [comment]
Intro text: 

Backdrop CMS version 1.12 is here! The Backdrop community is proud to release this most recent version, following our 4-month release cycle. This version of Backdrop includes lots of great new features including:

* In-browser Core self-updates. 
* Views grids now use CSS grids.
* Better use of iconography throughout core.
* Translatable taxonomy terms.
* Tags for modules (in addition to packages).
* A simpler way to provide options for selects, radios, and checkboxes.
* Add a block for the site-wide contact form.

Notes for updating: 
* It **will** be necessary to run the update script (located at /update.php) for this release.
* This release does **not** modify files outside the core directory.

**Comment by stpaultim** [comment]
I think it looks good! I don't think I'm going to be able to get to the blog post today. Sorry, I may have time tomorrow if it's not done by then.

**Comment by quicksketch** [comment]
Pushing 1.12.0 out to Pantheon will happen when 1.12.1 is released, or in two weeks, whichever happens first.

**Comment by stpaultim** [comment]
OK, I'm creating a google doc and dumping some screen shots there
https://docs.google.com/document/d/1O0EFTVZfe4JpLfVHfusPSZThK0MkYEmeX58JdHfEQ-c/edit#

**Comment by quicksketch** [comment]
Blog post is up and today we released 1.12.2. I'm closing this so we can also close out the 1.12.0 milestone.
