### ISSUE TITLE
1.11.4 release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3474]
## Pre-release tasks

- [x] Merge commits (@quicksketch) 
- [x] Create a new bugfix release (@quicksketch) 
- [x] Create the next bugfix milestone (@jenlampton)
- [x] Move all unfinished issues to the next bugfix release milestone (@jenlampton)
- [x] Draft Release notes (@jenlampton)
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch) 
- [x] Tag for release, and push tag to GitHub (@quicksketch) 
- [x] Revert version number back (@quicksketch) 
- [x] Create release notes on GitHub (@jenlampton)

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon)  (@quicksketch) 
- [ ] Push the bug-fix release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) (@serundeputy)

**Comment by jenlampton** [comment]
Release notes:

**Changes since 1.11.3**

* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3469">#3469</a>: Add Manage fields and Manage displays drop-buttons for vocabularies.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3468">#3468</a>: User role drop-buttons should read Configure instead of Edit.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3435">#3435</a>: FIX RTL Formatting options in Basis.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3477">#3477</a>: Fix table row hover on sorted columns in Seven.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3434">#3434</a>: Fix RTL Datepicker in Seven.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3405">#3405</a>: [UX] Fix RTL admin_bar style.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3442">#3442</a>: Project Installer: relevancy vs relevance.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3463">#3463</a>: Prevent PHP notice for bundles with no name attribute.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1478">#1478</a>: Allow more time for the "comment-new" flag to be triggered.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3456">#3456</a>: Don't break on whitespace the more/less links.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3338">#3338</a>: [UX] Make the "This is a preview. ..." message a warning and also make it persistent.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3456">#3456</a>: Add arrow indicators to more/less links on modules page.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3430">#3430</a>: Views: add padding to messages within dialogs.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3448">#3448</a>: Clear menu caches when saving URL detection path prefixes.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3404">#3404</a>: CKEditor – Incorrect initial display of the Insert link dialog.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3443">#3443</a>: set storage of the "Image" Library view to module-provided.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3313">#3313</a>: Suppress "Go online" message on maintenance mode settings page when clearing caches.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3403">#3403</a>: Remove usage of each().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1582">#1582</a>: RSS feed icon never printed
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: PHP 7.2 compatibility - make sure some variables are arrays in theme_links().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: When a theme has a managed_file field and a submit callback, call to undefined function error is thrown.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: [PHP 7.2] Avoid count() calls on uncountable variables.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: Hotfix for ImageToolkitGdTestCase failing on newer PHP 7 and 7.1 releases.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: Fix incorrect documentation link at admin/config/media/file-system.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: Fix documentation of taxonomy term title callback code to match nodes and to not imply that it sets the title of the term page.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: PHP7 warning when uploading a user picture.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: backdrop_http_request() should allow caller to set the Host header.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: theme_status_report() doesn't document its parameters (<a href="https://github.com/backdrop/backdrop-issues/issues/2366">#2366</a>)
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: Improve documentation regarding static JS or CSS in .info files.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: Make cache_form expiration configurable, to mitigate runaway cache_form tables.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3375">#3375</a>: file_save_upload() should not alter the file URI string before validation.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3384">#3384</a>: Fix fatal error when adding a link to an image in CKEditor.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3295">#3295</a>: Fixing the color preview on some browsers by waiting for the iframe to be loaded before trying to manipulate it.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3223">#3223</a>: Use a string when rewriting database prefix.

**Comment by quicksketch** [comment]
I pushed the Pantheon upstream to 1.11.4 as well. Here's the merge commit message:

```
    Backdrop 1.11.4. Bugfix release fixing items in the 1.11.x branch. Release notes are at https://github.com/backdrop/backdrop/releases/tag/1.11.4.
    
    The next minor version (1.12.0) was also released today. The Pantheon upstream will be updated in two weeks, or when 1.12.1 comes out, whichever is first.
```

https://github.com/backdrop-ops/backdrop-pantheon/commit/6d2279ca85eea6ad833c885c49110e7bd2be19b0
