### ISSUE TITLE
1.11.6 release checklist

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3548]
## Pre-release tasks

- [x] Merge commits (@quicksketch) 
- [x] Create a new bugfix release (@quicksketch) 
- [x] Create the next bugfix milestone (@jenlampton)
- [x] Move all unfinished issues to the next bugfix release milestone (@jenlampton)
- [x] Draft Release notes (@jenlampton)
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch) 
- [x] Tag for release, and push tag to GitHub (@quicksketch) 
- [x] Revert version number back (@quicksketch) 
- [x] Create release notes on GitHub (@jenlampton)
- [x] Mark release as a security release if that is the case @klonos

**Comment by jenlampton** [comment]
Removing the post-release task to deploy to Pantheon because Pantheon is already on 1.12.

**Comment by quicksketch** [comment]
Tag for https://github.com/backdrop/backdrop/releases/tag/1.11.6 is cut.

**Comment by jenlampton** [comment]
Release notes:
---

This release fixes security vulnerabilities. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

[Backdrop core - Critical - Remote Code Execution - SA-CORE-2019-003](https://backdropcms.org/security/backdrop-sa-core-2019-003)

There are no other Changes since 1.12.2

**Update information**
- The database update script does **not** need to be run.
- No changes have been made to the .htaccess, robots.txt or default settings.php files in this release, so upgrading custom versions of those files is not necessary.
