### ISSUE TITLE
Drupal 7.61-7.64 commits: crossport or mark as NA

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3557]
- [x] N/A| [9f0d39e9ae](https://cgit.drupalcode.org/drupal/commit/?id=9f0d39e9ae79ef419feb90bbf76131a0e645556a) | [Back to dev](http://drupal.org/node/)
- [x] N/A | [56a02cab38](https://cgit.drupalcode.org/drupal/commit/?id=56a02cab38eacee62590941c0227f08d035551fd) | [Issue #2981248 by mfb, LFP6, msti: MySQL 5.7 incompatibility in system upgrade 7061](http://drupal.org/node/2981248)
- [x] https://github.com/backdrop/backdrop/pull/2519 | [9661e7c483](https://cgit.drupalcode.org/drupal/commit/?id=9661e7c4835782f44cdfdb6212a840f9baa5b8fb) | [Issue #3020771 by Ayesh, Pol, sjerdo: [PHP 7.3] strpos explicit string needle warnings](http://drupal.org/node/3020771)
- [x] #1110 | [a0983925ed](https://cgit.drupalcode.org/drupal/commit/?id=a0983925edd79b0749d52659a3d01a20da5c8b38) | [Issue #2482549 by Pol, marcelovani, ndf, drupal@guusvandewal.nl, jenlampton, ufku, kaidjohnson, MiSc, David_Rothstein, RobLoach, SebCorbin, geerlingguy, pablo.guerino, JohnAlbin, joelpittet, afoster: Ignore node_module folder in core to use Drupal with npm/grunt/nodejs](http://drupal.org/node/2482549)
- [x] https://github.com/backdrop/backdrop/pull/2523 | [a5c07d45f9](https://cgit.drupalcode.org/drupal/commit/?id=a5c07d45f96e096a56bb6bcd908510be322843ff) | [Issue #3023066 by Pol, mfb: [PHP 7.3] Fix BootstrapMiscTestCase::testCheckMemoryLimit() notice](http://drupal.org/node/3023066)
- [x] N/A, see #1110 | [a15eff0a8a](https://cgit.drupalcode.org/drupal/commit/?id=a15eff0a8a1c3320fcf14e6fa4b8197aa5f1e1c9) | [Issue #2482549 by Pol, marcelovani, ndf, drupal@guusvandewal.nl, TR, jenlampton, kaidjohnson, ufku, MiSc, David_Rothstein, RobLoach, pablo.guerino, afoster, geerlingguy, SebCorbin, joelpittet, JohnAlbin: Fix up commit - convert short array styles to long.](http://drupal.org/node/2482549)
- [x] #xx | [617d1cefac](https://cgit.drupalcode.org/drupal/commit/?id=617d1cefac0f8ff927a8bef072c280436533dc0a) | [SA-CORE-2019-001 by Ayesh, alexpott, larowlan, xjm, michieltcs, farisv](http://drupal.org/node/)
- [x] #xx | [a4455a1628](https://cgit.drupalcode.org/drupal/commit/?id=a4455a1628111df7127c73e0a202bad7e4a23717) | [SA-CORE-2019-002 by greggles, cashwilliams, EclipseGc, larowlan, samuel.mortenson, alexpott, tedbow, effulgentsia, Fabianx, xjm, mlhess](http://drupal.org/node/)
- [x] N/A | [492fd4da5c](https://cgit.drupalcode.org/drupal/commit/?id=492fd4da5c9e8c0695f779f1967e7f90960d343b) | [Drupal 7.62](http://drupal.org/node/)
- [x] N/A | [2036539df0](https://cgit.drupalcode.org/drupal/commit/?id=2036539df05b27d478fa9eae73d95491b84f9e74) | [Back to dev.](http://drupal.org/node/)
- [x] N/A | [7f1f3b8be0](https://cgit.drupalcode.org/drupal/commit/?id=7f1f3b8be02f6f3af5934687bbb56fcc96574d3a) | [Issue #3026386 by dsnopek, samuel.mortenson, xjm, ydahi, alexpott, Fabianx, kferencz91, littlepixiez, greggles, cilefen: Drush fatal error after upgrading to 8.6.6, 8.5.9, or 7.62: PHP Fatal error:  Uncaught TYPO3PharStreamWrapperException](http://drupal.org/node/3026386)
- [x] N/A | [e1d746d812](https://cgit.drupalcode.org/drupal/commit/?id=e1d746d812b077a5a8fad101904d598bfcf09675) | [Drupal 7.63](http://drupal.org/node/)
- [x] N/A | [3a01537407](https://cgit.drupalcode.org/drupal/commit/?id=3a0153740784595a589ec059408678285eef30c5) | [Back to dev.](http://drupal.org/node/)
- [x] N/A | [80b00d1429](https://cgit.drupalcode.org/drupal/commit/?id=80b00d1429dba9af83db5a553066e1580c1d43d9) | [Issue #3026529 by alexpott: 7.x does not have Phar protection and Phar tests are failing on Drupal 7](http://drupal.org/node/3026529)
- [x] #3488 | [4d0bb65dcd](https://cgit.drupalcode.org/drupal/commit/?id=4d0bb65dcdbf3decadfa1975c74b7c55a5237c14) | [Issue #3018637 by emilymoi, das-peter: [regression] Unset the 'host' header in drupal_http_request() during redirect](http://drupal.org/node/3018637)
- [x] N/A | [ea394f962f](https://cgit.drupalcode.org/drupal/commit/?id=ea394f962f382b8d9c709b22b8587efe12b7138d) | [Issue #1470656 by Damien Tournoud, joseph.olstad, Fabianx, catch: Registry rebuild should not parse the same file twice in the same request](http://drupal.org/node/1470656)
- [x] N/A | [333fd500e0](https://cgit.drupalcode.org/drupal/commit/?id=333fd500e0123da1f0115bbb38c6f9a3d3eec39f) | [Revert "Issue #1470656 by Damien Tournoud, joseph.olstad, Fabianx, catch: Registry rebuild should not parse the same file twice in the same request"](http://drupal.org/node/1470656)
- [x] N/A | [936cc44b52](https://cgit.drupalcode.org/drupal/commit/?id=936cc44b52a6496c90f7d8161724c9d564fe63fe) | [Issue #3028364 by Pol, Fabianx: Update function _registry_update() and move module_implements() and _registry_check_code() calls out of the try/catch](http://drupal.org/node/3028364)
- [x] N/A | [007ee8a5c7](https://cgit.drupalcode.org/drupal/commit/?id=007ee8a5c7e19c4c0798f760d08bf660ba43910b) | [Issue #1470656 by Damien Tournoud, joseph.olstad, Pol, Fabianx, catch: Registry rebuild should not parse the same file twice in the same request](http://drupal.org/node/1470656)
- [x] https://github.com/backdrop/backdrop/pull/2522 | [9b1a957083](https://cgit.drupalcode.org/drupal/commit/?id=9b1a957083480dbb710a39b0f8bfa617059b5c57) | [Issue #1430934 by johnish@gmail.com, DamienMcKenna, Berdir, malcomio, Dane Powell, zerolab, er.pushpinderrana, akosipax, njbarrett, Fabianx, alesr, David_Rothstein, littledynamo, das-peter: Notice: Undefined index: display_field in file_field_widget_value() (line 582 of /module/file/file.field.inc)](http://drupal.org/node/1430934)
- [x] N/A | [cb02ac871c](https://cgit.drupalcode.org/drupal/commit/?id=cb02ac871c4e85b890c3089c052242dd2fd0cd92) | [Update changelog for 7.64 release](http://drupal.org/node/)
- [x] N/A | [868f206924](https://cgit.drupalcode.org/drupal/commit/?id=868f2069242a0983186323c573d498e53dc95af8) | [Release 7.64](http://drupal.org/node/)

git command:

```
git log 7.61..7.64 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"
```

**Comment by klonos** [comment]
CHANGELOG.txt for reference:

```
Drupal 7.64, 2019-02-06
-----------------------
- [regression] Unset the 'host' header in drupal_http_request() during redirect
- Fixed: 7.x does not have Phar protection and Phar tests are failing on Drupal 7
- Fixed: Notice: Undefined index: display_field in file_field_widget_value() (line 582 of /module/file/file.field.inc)
- Performance improvement: Registry rebuild should not parse the same file twice in the same request
- Fixed _registry_update() to clear caches after transaction is committed
```

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2522 need a quick review

**Comment by opi** [comment]
Some Drupal's issues are about the `registry_update` function, which disappear from Backdrop code. I can't find anything related in changes records, so an input from old Backdropers is welcome !

**Comment by herbdool** [comment]
@opi the registry functionality is not needed in Backdrop since classes are defined in an info hook instead of needing to be discovered and cached.

**Comment by opi** [comment]
@herbdool so do you think we could mark all registry related commits as "N/A" ?

**Comment by herbdool** [comment]
@opi I guess yes

**Comment by klonos** [comment]
Searching api.b.or for `registry_update` brings no results: https://api.backdropcms.org/search/node/registry_update

> ..the registry functionality is not needed in Backdrop since classes are defined in an info hook instead of needing to be discovered and cached.

@serundeputy @quicksketch @herbdool shouldn't we at least have a change record for that?

**Comment by quicksketch** [comment]
Merged the existing 3 issues. All other ones seem to be not applicable to Backdrop.

The registry does have a change record at https://api.backdropcms.org/change-records/class-registry-has-been-replaced-static-class-map, though it could be fleshed out further to list these functions that have been removed for better searchability.
