### ISSUE TITLE
[META][UX] Improve book module

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3639]
Various backwards-compatible improvements for the Book module:

- [ ] https://github.com/backdrop/backdrop-issues/issues/1976 Allow display settings for book navigation.
- [ ] https://github.com/backdrop/backdrop-issues/issues/3638 Allow the book outline functionality on non-book-enabled node types to be hidden from users with the "Administer book outlines" permission
- [ ] https://github.com/backdrop/backdrop-issues/issues/3735 Convert /admin/content/book to a View
- [x] https://github.com/backdrop/backdrop-issues/issues/5331 Some UI improvements to Book module
- [ ] Add 'administer own book outlines' permission for ordering books from a book's main page.
- [ ] Keep a book's main page's menu link active while navigating to lower-level book pages.
- [ ] Add an 'Order' tab (node/%/order) to a book's main page.
- [x] https://github.com/backdrop/backdrop-issues/issues/5557
- [ ] https://github.com/backdrop/backdrop-issues/issues/5609

Some improvements from [Book Helper](https://www.drupal.org/project/book_helper) could inspire this list

**Comment by klonos** [comment]
Not sure if these are backwards-compatible, but copy-pasting from the duplicate #3736:

Things that we could do to improve the situation:

`admin/content/book`

<img width="683" alt="Screen Shot 2019-05-01 at 3 23 55 pm" src="https://user-images.githubusercontent.com/2423362/57006576-2f9e3d00-6c25-11e9-97de-f92bfd772f1d.png">

- Change the tab title to "Manage books", to match the other tabs there.
- Move the settings from `/admin/content/book/settings` to `/admin/structure`
- Convert that listing to a view (#3735)

`admin/content/book/%`

<img width="1189" alt="Screen Shot 2019-05-01 at 3 59 22 pm" src="https://user-images.githubusercontent.com/2423362/57007191-2d8aad00-6c2a-11e9-8859-507807be2410.png">

- The "Parent" column does not show parent pages (shown when "show row weights" is clicked). Either fix it, or remove it.
- There should be an easy way to get to the parent book page
- Fix the breadcrumb

`/node/%/outline`

- Remove this entire admin page (we have a "Book outline" vertical tab with the exact same form).

...more?

**Comment by herbdool** [comment]
I've added a couple PRs to child issues https://github.com/backdrop/backdrop-issues/issues/5331 and https://github.com/backdrop/backdrop-issues/issues/1976
