### ISSUE TITLE
[META] Add upgrade paths for modules now integrated into core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3680]
This is a meta issue to track the upgrade path for modules that have been moved into core, or integrated into existing system modules. 

* [ ] https://github.com/backdrop/backdrop-issues/issues/3687 | Admin Menu (moved into core, renamed to Admin Bar module in v1.0)
* [ ] https://github.com/backdrop/backdrop-issues/issues/3682 | Block Class (integrated into System module in v1.0)
* [ ] @todo | Blockify (added page elements as blocks in v1.7)
* [ ] @todo | Btester Custom Block Content* (added hero block in v1.5 and contact block in v1.12)
* [ ] @todo | Caption Filter (integrated into CKEditor module n v1.2)
* [ ] #2569 | Chaos Tools - Views Content Panes (added in v1.7)
* [ ] #3985 | Chaos Tools (integrated into various System modules in v1.0)
* [ ] https://github.com/backdrop/backdrop-issues/issues/3684 | CKEditor (moved into core in v1.2)
* [ ] @todo | CKEditor Link (internal link option added to CKEditor in v1.7)
* [ ] @todo | CKEditor Media Browser* (browser added to CKEditor in 1.11)
* [ ] @todo | CKEditor Upload (image uploads included as of v1.0, file uploads as of v1.10)
* [ ] @todo | Comment Closer (merged into Comment module in v1.10)
* [ ] @todo | Contact Block (contact block added in v1.12)
* [ ] @todo | Context (replaced by Layout "contexts" in v1.0)
* [x] done | Date* (partially moved into core in v1.2 - Date Repeat remains in contrib)
* [ ] @todo | Diff* (diff engine included as part do Configuration Management in v1.0)
* [ ] @todo | Direct Upload (added better image/file upload options in v1.7)
* [ ] @todo | Display Suite (replaced by Layout module in v1.0)
* [x] N/A | Elements (integrated into System module in v1.0)
* [X] done | Email (moved into core in v1.2)
* [ ] @todo | Email Registration (feature included since v1.0)
* [x] N/A | Entity API (merged into System module in v1.0)
* [x] done | Entity View Mode (merged into Field UI module in v1.6)
* [ ] @todo | Field as Block (per-field blocks were added in v1.3)
* [ ] @todo | File Entity* (partially integrated into File module in v1.0 + v1.6)
* [x] N/A | HTML5 Tools (integrated into System modules in v1.0)
* [x] N/A | Image Mobile Camera (support to upload images via mobile cameras was added in v1.4)
* [x] N/A | IMCE WYSIWYG Bridge (replaced by CKEditor and System module in v1.2)
* [x] N/A | Insert (integrated into CKEditor module in v1.2)
* [x] N/A | Instant Filter (integrated into System modules in v1.0)
* [ ] @todo | Libraries API (deprecated, libraries in Backdrop are bundled into modules)
* [x] done | Link (moved into core in v1.2)
* [ ] @todo | Live Preview (better content preview added in v1.11)
* [ ] https://github.com/backdrop/backdrop-issues/issues/3681 | Menu Block (integrated into System & Menu modules v1.5)
* [ ] @todo | Menu Translation (menus became translatable in v1.10)
* [ ] @todo | Node Block (provided by Node module in v1.5)
* [x] done | Options Element (integrated into Field module in v1.12)
* [ ] @todo | Page Preview* (better content preview added in v1.11)
* [ ] @todo | Panels (replaced by Layout module in v1.0)
* [ ] @todo | Panels Everywhere (replaced by Layout module in v1.0)
* [x] done | Pathauto (integrated into Path module in v1.1)
* [x] done | Project Browser (integrated into System module in v1.4)
* [x] done | Redirect (moved into core in v1.4)
* [ ] @todo | Role Assign (integrated into User module in v1.6)
* [ ] @todo | Scheduler (merged into node in v1.10)
* [x] N/A | Smartmenus (replaced by System menus in v1.5 + v1.6) 
* [x] done | Token (integrated into System module in v1.1)
* [ ] @todo | Transliteration (integrated into System module in v1.3)
* [x] N/A | Vertical Tabs Responsive (vertical tabs were made responsive in v1.2)
* [x] done | Views (moved into core in v1.0)
* [x] done | Views Bulk Operations (integrated into System modules in v1.0)
* [ ] @todo | Views Responsive Grid (Views grids use CSS Grid as of v1.12)
* [ ] @todo | WYSIWYG (replaced by CKEditor module in v1.2) -- uninstall / reconfigure

**Comment by klonos** [comment]
Thanks for filing this meta @jenlampton 👍 ...looks like we have some work to do.

Re admin_menu, doesn't it provide (some of) the same options as the core admin_bar module ("sticky at top of pages" etc.)? We should be migrating these settings over ...if not already doing so.

**Comment by docwilmot** [comment]
this is a good issue

**Comment by jenlampton** [comment]
> Re admin_menu, doesn't it provide (some of) the same options as the core admin_bar module ("sticky at top of pages" etc.)? We should be migrating these settings over ...if not already doing so.

I think that's the only setting that's the same between contrib and core, though it wouldn't hurt to check. I'll create an issue for the checking!
