### ISSUE TITLE
[META] Make Backdrop run smoothly on PHP 7.3

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3689]
New versions of MampPro come with php 7.3 by default. If you try to run backdrop on PHP 7.3, it's riddled with errors. Additionally, if you attempt to run the installer, it runs out of memory (probably because of all the errors).

We should address the changes in PHP 7.3 and see if we can't make backdrop run happily on it.

---

Respective meta-issue for D7: https://www.drupal.org/project/drupal/issues/3012308

Child issues of that meta:

- [x] https://www.drupal.org/project/drupal/issues/3023066 | https://git.drupalcode.org/project/drupal/commit/a5c07d4
  Fixed in #3557 | https://github.com/backdrop/backdrop/commit/a15f4059c00219d37717ec785c7707af57cc8aad
- [x] https://www.drupal.org/project/drupal/issues/3020771 | https://git.drupalcode.org/project/drupal/commit/9661e7c
  Fixed in #3557 | https://github.com/backdrop/backdrop/commit/c8629b0872b479f7d573ca8579ec84984a7a4970
- [x] https://www.drupal.org/project/drupal/issues/2902430
  #3699
- [x] ~~https://www.drupal.org/project/drupal/issues/3009351~~
  N/A to Backdrop, since the Statistics module has been removed from core.
- [x] https://www.drupal.org/project/drupal/issues/3025335
  #3700

**Comment by klonos** [comment]
I have added a couple of issues with respective PRs, taken from the D7 meta.
