### ISSUE TITLE
crossport views commits from 7.x-3.9 - 7.x-3.11

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3719]
- [x] https://github.com/backdrop/backdrop/pull/2628 | [dbc703c7](http://drupalcode.org/project/views/commit/dbc703c73f486875874947d5a047f68e45f4c7ff) | [Issue #2308885 by pfrenssen: Wrong example in documentation for hook_views_pre_view()](http://drupal.org/node/2308885)
- [x] https://github.com/backdrop/backdrop/pull/2627 | [614e2cde](http://drupalcode.org/project/views/commit/614e2cde4d56390755964a6b942018fed8d82b99) | [Issue #2007474 by dawehner: Add documentation for refreshing of a view](http://drupal.org/node/2007474)
- [x] N/A ([see comment](https://github.com/backdrop/backdrop-issues/issues/3719#issuecomment-493149067)) | [0aea01a6](http://drupalcode.org/project/views/commit/0aea01a6a764236acfe87839f54958506b7dfe25) | Strengthen the default configuration
- [x] N/A | [f4e8b47f](http://drupalcode.org/project/views/commit/f4e8b47ff8adecbb00eb921a978dfe0b6a278539) | Strengthen the redirect of views locking
- [x] ~https://github.com/backdrop/backdrop/pull/2626~ https://github.com/backdrop/backdrop/pull/2800 | [580ff35b](http://drupalcode.org/project/views/commit/580ff35b315b8cf0eed6e33ab97e985634f829b1) | [Issue #1376400 by fietserwin: Cache views plugin data](http://drupal.org/node/1376400)
- [x] https://github.com/backdrop/backdrop/pull/2850 | [3c56af8a](http://drupalcode.org/project/views/commit/3c56af8a08c6b411435607cf57b3028e1da88d05) | [Issue #1182256 by stella, artis, das-peter: Date filter does not work with dynamic dates](http://drupal.org/node/1182256)
- [x] https://github.com/backdrop/backdrop/pull/2624 | [ab35ae9c](http://drupalcode.org/project/views/commit/ab35ae9c380807772e7695a917f8dfa566ab90dd) | [Issue #2159347 by claudiu.cristea, david_garcia, mallezie: Aggregation not working simple test case](http://drupal.org/node/2159347)
- [x] N/A (#3729) | [c615dadb](http://drupalcode.org/project/views/commit/c615dadb7eae26e207540344171dbc6a9a2693ce) | [Issue #1389720 by igor.ro, colan: Added support for "drush views-revert --all".](http://drupal.org/node/1389720)
- [x] https://github.com/backdrop/backdrop/pull/2623 | [3e64a92f](http://drupalcode.org/project/views/commit/3e64a92faf31255f90ab3baff884d007bea0dff9) | [Issue #2018737 by oriol_e9g, johnv, david_garcia, klausi, forgenator: Notice: Undefined index: data in views_plugin_cache->restore_headers()](http://drupal.org/node/2018737)
- [x] https://github.com/backdrop/backdrop/pull/2622 | [aba8e024](http://drupalcode.org/project/views/commit/aba8e024bc4a7bbd9ee56ca4a4b4d6ae275e2cd0) | [Issue #1982806 by dhaval_panara: Typo "chang" instead of "change"](http://drupal.org/node/1982806)
- [x] https://github.com/backdrop/backdrop/pull/2621 | [0352f384](http://drupalcode.org/project/views/commit/0352f384439734bc1e6f173d65c5461e969a7398) | [Issue #2171389 by stella: Attachments on Views Content Panes don't always inherit exposed filters](http://drupal.org/node/2171389)
- [x] https://github.com/backdrop/backdrop/pull/2620 | [10e71bd4](http://drupalcode.org/project/views/commit/10e71bd493b8b36adc90ae139ec95a40d9bb8e0b) | [Issue #1460506 by ellen.davis, dawehner: use format_username for RSS feed creator](http://drupal.org/node/1460506)
- [x] https://github.com/backdrop/backdrop/pull/2618 | [cef693bc](http://drupalcode.org/project/views/commit/cef693bc5874d75659bbcb03f77fc7ecf106be97) | [Issue by das-peter: Ensure that we do not end up with broken views data cache entries.](http://drupal.org/node/)

**Comment by herbdool** [comment]
RTBC on https://github.com/backdrop/backdrop/pull/2618#issuecomment-491508753

**Comment by jenlampton** [comment]
This issue has a PR, so removing the `milestone candidate - bug` label.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2618#issuecomment-491508753 has been merged but all the other ones still need review.

**Comment by klonos** [comment]
...would be great to have a record of why the two commits in the list in the issue summary have been deemed N/A.

**Comment by jenlampton** [comment]
I marked `Strengthen the default configuration` as NA by checking all the default views that were modified in that patch, and confirming that we already had those changes to the default views in our config files. I don't know about the other issue, I didn't check that one.

**Comment by quicksketch** [comment]
All issues have been merged except https://github.com/backdrop/backdrop/pull/2625, which has test failures. At this point I'm unclear if it's a problem with the test or the code. The cross-port itself seems fine though.

**Comment by jenlampton** [comment]
I fixed the last failing test, and filed a new PR: https://github.com/backdrop/backdrop/pull/2850

Some of the views patch hadn't applied, I deleted the lines manually and voila!

**Comment by klonos** [comment]
Doh! 😅 ...thanks @jenlampton. RTBC 👍

**Comment by quicksketch** [comment]
Thanks finally merged https://github.com/backdrop/backdrop/pull/2850 and now we're all set with this set of cross-ports. :rocket:
