### ISSUE TITLE
crossport views commits from 7.x-3.12

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3720]
- [x] https://github.com/backdrop/backdrop/pull/2674 | [d55db813](http://drupalcode.org/project/views/commit/d55db813e033ea421ac41cbdf7cb76aff3915dde) | [Issue #2480753 by dawehner, jibran, das-peter: Make it easier to subclass views_handler_area_view](http://drupal.org/node/2480753)
- [x] https://github.com/backdrop/backdrop/pull/2673 | [4317c5eb](http://drupalcode.org/project/views/commit/4317c5eb4ec719c05da4185307c8ec271304508f) | [Issue #1831162 by dcmouyard, Valentine94: Tables generated by Views need better semantics](http://drupal.org/node/1831162)
- [x] https://github.com/backdrop/backdrop/pull/2672 | [d08465de](http://drupalcode.org/project/views/commit/d08465de955b88e5f262c06d99b79ceb167dca88) | [Issue #1976836 by Dean Reilly: Views locale edit link field uses the old D6 path](http://drupal.org/node/1976836)
- [x] https://github.com/backdrop/backdrop/pull/2671 | [4218722c](http://drupalcode.org/project/views/commit/4218722c7b0b61256489dd80a0c7ba1d571696b1) | [Issue #1959594 by chrisjlee: typo 'lenght' in view_trim_views()](http://drupal.org/node/1959594)
- [x] https://github.com/backdrop/backdrop/pull/2670 | [39abeb04](http://drupalcode.org/project/views/commit/39abeb04ed654553b157115f4e3176ce24ec34b6) | [Issue #2473959 by fizk: Typo](http://drupal.org/node/2473959)
- [x] https://github.com/backdrop/backdrop/pull/2669 | [2a5df673](http://drupalcode.org/project/views/commit/2a5df67307cd603fc0f98422f0454f0776468ea8) | [Issue #1819538 by azinck: More link disappears when time-based views cache is enabled](http://drupal.org/node/1819538)
- [x] N/A | [c3536f4d](http://drupalcode.org/project/views/commit/c3536f4db9762dfa84a03aa558e0027acd6620d4) | [Issue #1036962 by acbramley, dsnopek, grahamC, mr.york, das-peter, wiifm: Edit link destination incorrect when using AJAX-enabled views](http://drupal.org/node/1036962) - Fixed in Backdrop in eff5173481b797f30c2a0a2ee01d1a46dafabb10
- [x] https://github.com/backdrop/backdrop/pull/2668 | [c125e4fc](http://drupalcode.org/project/views/commit/c125e4fc95e7399b130eab54eb12eaac3172b836) | [Issue #2408939 by shashikant_chauhan: Views Plugins documentation topic lists incorrect number of plugin types](http://drupal.org/node/2408939)
- [x] https://github.com/backdrop/backdrop/pull/2667 | [d7837bc1](http://drupalcode.org/project/views/commit/d7837bc1adcef409523b7944a81b784ebefb6fa1) | [Issue #2284593 by jhedstrom, Lendude:  Fatal error: Call to a member function ensure_my_table() on a non-object](http://drupal.org/node/2284593)
- [x] N/A | [96a54e04](http://drupalcode.org/project/views/commit/96a54e041b171eb47c6a00805b9c4731c81d9283) | [Issue #1809958 by joelpittet, steve.stotter, alesr, klaasvw: Views with exposed filter (ajax enabled) inside modal window (ctools)](http://drupal.org/node/1809958)
- [x] https://github.com/backdrop/backdrop/pull/2666 | [ae60042d](http://drupalcode.org/project/views/commit/ae60042d359c1bd40cb25bd16b6dc26dbb8ae960) | [Issue #2188165 by dww, jesss, tim.plunkett: Issue tag 'is/not empty' and 'not one of' operators do not work](http://drupal.org/node/2188165)
- [x] https://github.com/backdrop/backdrop/pull/2665 | [ea75e556](http://drupalcode.org/project/views/commit/ea75e556c2c06952c90c2c03c16c5a4570c76e33) | [Issue #1484208 by tedfordgif: Undefined index options_form()](http://drupal.org/node/1484208)
- [x] https://github.com/backdrop/backdrop/pull/2664 | [28d92baa](http://drupalcode.org/project/views/commit/28d92baa758adce7329cdbd5a5b178c1d17aac22) | [Issue #2211253 by sandipmkhairnar: Incorrect array index given in example for hook_views_ajax_data_alter()](http://drupal.org/node/2211253)
- [ ] https://github.com/backdrop/backdrop/pull/2661 | [05fcf52d](http://drupalcode.org/project/views/commit/05fcf52dd3b374513320a3e6b7c67757baf6495d) | [Issue #1802438 by andrewbelcher, vasike: get_result_entities() Doesn't support revisions](http://drupal.org/node/1802438)
- [x] https://github.com/backdrop/backdrop/pull/2660 | [21fd8f9f](http://drupalcode.org/project/views/commit/21fd8f9f89deaf875e768b6fb97717297f0f6967) | [Issue #2115269 by lalweil, anrikun: Check for entity in views_handler_field_field->get_value() before accessing it.](http://drupal.org/node/2115269)
- [x] https://github.com/backdrop/backdrop/pull/2659 | [24188c4f](http://drupalcode.org/project/views/commit/24188c4f20181a113f3b86219971f70169c94c94) | [Issue #339384 by colan: Added help text to keep the exposed filter terms list unset to keep unfiltered "Any" option default.](http://drupal.org/node/339384)
- [x] https://github.com/backdrop/backdrop/pull/2658 | [6d8b0cb5](http://drupalcode.org/project/views/commit/6d8b0cb57927569c709b77fd2ff1df0c809f2327) | [Issue #2376607 by rrfegade, dakku: Fix some typos in comments.](http://drupal.org/node/2376607)
- [x] https://github.com/backdrop/backdrop/pull/2657 | [0f54f7fd](http://drupalcode.org/project/views/commit/0f54f7fd228881357e24927fa30d46cd8e96fd94) | [Issue #1491082 by drzraf, dawehner, colan: Set a default template if there is no theme definition.](http://drupal.org/node/1491082)
- [x] https://github.com/backdrop/backdrop/pull/2656 | [4ae33535](http://drupalcode.org/project/views/commit/4ae3353503cea91b9e4e7106a7c9eca63bc4064a) | [Issue #1771140 by imclean, das-peter, GuGuss: view_menu_alter() adding to existing "access arguments" causes user_access() error](http://drupal.org/node/1771140)
- [x] https://github.com/backdrop/backdrop/pull/2655 | [d66cd3e6](http://drupalcode.org/project/views/commit/d66cd3e6a75fbab75548106ea666ddd7b6293468) | [Issue #1547924 by rbp: Document field_math feature previous value](http://drupal.org/node/1547924)
- [x] N/A See https://github.com/backdrop/backdrop-issues/issues/4137 | [fba32b8e](http://drupalcode.org/project/views/commit/fba32b8efcff01e5fd03a0905aa1647d6dfea52b) | [Issue #1248716 by milesw, ndf, stefan.r: Views strings not translatable when loaded from a feature](http://drupal.org/node/1248716)
- [x] https://github.com/backdrop/backdrop/pull/2653 | [5a0309a2](http://drupalcode.org/project/views/commit/5a0309a25040dba327613ed64b58570bb1f25f7c) | [Issue #2559839 by hexabinaer: [Backport] Expand display "Comment" trim from 10 to 80 characters](http://drupal.org/node/2559839)
- [x] https://github.com/backdrop/backdrop/pull/2652 | [f510a924](http://drupalcode.org/project/views/commit/f510a924eb8c7da4c105dee2ad381a58d86ed9b6) | [Issue #1940212 by jweowu: "Content translation: Translations" relationship incorrectly specifying translation source](http://drupal.org/node/1940212)
- [x] N/A | [8e0dab36](http://drupalcode.org/project/views/commit/8e0dab36d94a287e7fa79b61568d7d495adb10b5) | [Issue #2579819 by skyredwang: Deprecating PHP4 style constructors](http://drupal.org/node/2579819)
- [x] N/A | [dd39988f](http://drupalcode.org/project/views/commit/dd39988f1dfd4876b5a30d1e6c5f5b2e373f04dc) | [Issue #2450447: Drupal QA is broken for Views 7.x-3.x](http://drupal.org/node/2450447) - Already fixed in Backdrop per eff5173481b797f30c2a0a2ee01d1a46dafabb10.
- [x] N/A (see #3775) | [d649d329](http://drupalcode.org/project/views/commit/d649d329eb2fc56d9feb1320c173fd69f3c9a986) | [Issue #2204257 by ezra-g, andyg5000: Update Views Content access filter per core performance improvements](http://drupal.org/node/2204257)  https://github.com/backdrop/backdrop/pull/2651
- [x] https://github.com/backdrop/backdrop/pull/2679 [see comment/question](https://github.com/backdrop/backdrop-issues/issues/3720#issuecomment-491753374) | [4edefe17](http://drupalcode.org/project/views/commit/4edefe170aec2df46a59a3b5a17e67429f9108fb) | [Issue #1154830 by heddn, hass, dunix: Schema mismatch after upgrade D6 to D7](http://drupal.org/node/1154830)
- [x] https://github.com/backdrop/backdrop/pull/2650 | [9aaf9692](http://drupalcode.org/project/views/commit/9aaf9692081ba5ca3a79137069a0d508f78a9cb4) | [Issue #1337894 by fengtan: Views RSS feeds have validation issues](http://drupal.org/node/1337894)
- [x] https://github.com/backdrop/backdrop/pull/2649 | [0ae5fd66](http://drupalcode.org/project/views/commit/0ae5fd6650e52fa1f32d385ab8adfaa15abb6966) | [Issue #1751424 by Ken Ficara, jwilson3: Undefined index: current_user](http://drupal.org/node/1751424)

**Comment by klonos** [comment]
Re https://www.drupal.org/node/1154830 and [the respective 7.x commit](https://git.drupalcode.org/project/views/commit/4edefe170aec2df46a59a3b5a17e67429f9108fb), do we support D6 to Backdrop, and in general, do we advise people to first upgrade to the latest version of the respective 7.x module before doing D7 to Backdrop upgrades?

I'm asking because the commit adds a 
`views_update_7302()`, which would have already run if the module on a D6/D7 site was using the latest version of Views 7.x. Other wise, do we need to add a new 100x update hook on our end?

**Comment by klonos** [comment]
We seem to already have implemented the same fix as https://git.drupalcode.org/project/views/commit/96a54e041b171eb47c6a00805b9c4731c81d9283, but we are using `form#views-exposed-form-` instead of `#views-exposed-form-`. I called it a N/A, but feel free to change that if you thing that we should change things accordingly.

**Comment by jenlampton** [comment]
> Re drupal.org/node/1154830 and the respective 7.x commit, do we support D6 straight to Backdrop, 

No. Not officially, but I think there is an issue somewhere to add this. Though, the longer it takes to address that, the harder it will get.

> and in general, do we advise people to first upgrade to the latest version of the respective 7.x module before doing D7 to Backdrop upgrades?

Yes.

> I'm asking because the commit adds a
views_update_7302(), which would have already run if the module on a D6/D7 site was using the latest version of Views 7.x. Other wise, do we need to add a new 100x update hook on our end?

@klonos that update would only have already been run if someone had added the views module  to their D7 site after the update was added, but before before moving to Backdrop. What if they had already upgraded from D7 to Backdrop before that update was added to D7 views. Is there anything in there that their Backdrop site won't have? 

For other updates like this, we add the update to Backdrop, but in the update we test if the change has been made already. If so, we do nothing. If not, we do the update. That we we account for all use-cases.

**Comment by klonos** [comment]
> ...What if they had already upgraded from D7 to Backdrop before that update was added to D7 views. Is there anything in there that their Backdrop site won't have?... That way we account for all use-cases.

Makes sense @jenlampton 👍 ...will add a PR for that change as well then.

**Comment by klonos** [comment]
...done 🙂

**Comment by jenlampton** [comment]
Since most of these PRs are RTBC, I've changed the tags to get committer eyes on this. @klonos there are 2 of these PRs that still need work:
* https://github.com/backdrop/backdrop/pull/2661
* https://github.com/backdrop/backdrop/pull/2659

**Comment by quicksketch** [comment]
> Re https://www.drupal.org/node/1154830 and the respective 7.x commit, do we support D6 straight to Backdrop, and in general, do we advise people to first upgrade to the latest version of the respective 7.x module before doing D7 to Backdrop upgrades?

Yes, we do encourage that. Though it seems as though this particular issue could slip through to some (few) Backdrop sites. Since Backdrop existed for ~3 years by the time that issue was committed, it's possible that some Backdrop sites were upgraded from D7 with that problem before it was fixed in Views. It's low impact overall, so I think merging the fix suggested in https://github.com/backdrop/backdrop/pull/2679 is a good idea.

**Comment by quicksketch** [comment]
I merged in all the ready items here for 1.14.1. There are now only 3 remaining items. https://github.com/backdrop/backdrop/pull/2654 should be separated out into a dedicated issue, as I don't think we'll need/want a direct port of that code from Drupal 7.

**Comment by domaingood** [comment]
Im getting same problem
Access denied
You are here
Home
You are not authorized to access this page.

Php 7.2 
MariaDB 104

**Comment by jenlampton** [comment]
I've created a follow-up issue at https://github.com/backdrop/backdrop-issues/issues/4137 and marked the item as NA in this list.

**Comment by herbdool** [comment]
Pushed a fix to this PR https://github.com/backdrop/backdrop/pull/2659

**Comment by herbdool** [comment]
Pushed a fix to this PR too https://github.com/backdrop/backdrop/pull/2661.

As far as I can see there are only two PRs left on this list. Fingers crossed they get merged and this whole issue can be closed.

**Comment by jenlampton** [comment]
Just adding a note here that there's only one more PR to close this issue, but it needs steps to reproduce the bug, so that we can confirm that the bug is fixed in Backdrop. 

Here's a usecase that came up in Drupal:

> Because for a project we would like to integrate Megarows with workbench. A few of the views Workbench supplies are based on revisions.

It might be worthwhile looking at the revision views in workbench, and trying to recreate them in Backdrop.

**Comment by quicksketch** [comment]
I tried to see if I could discover any new functionality in Views after the final patch in https://github.com/backdrop/backdrop/pull/2661, and I was not successful. The code seems to make sense but I can't tell where it would have any effect. I tried assembling a view starting from a "Content Revisions" table and a view from the "Content" table and joining over to revisions, but in both cases I can't find anything that I couldn't do before.

**Comment by olafgrabienski** [comment]
Looking for an older views crossport, I stumbled about this list where 28 of 29 tasks are checked, which is great! There is only one unclear issue - see https://github.com/backdrop/backdrop-issues/issues/3720#issuecomment-1017945548. Can we set the unclear issue to `N/A` and proceed?

**Comment by quicksketch** [comment]
I couldn't bear to bump this issue yet again. With only https://github.com/backdrop/backdrop/pull/2661 remaining and no complaints against the code implementation, I went ahead and merged that last PR so we can close this issue.
