### ISSUE TITLE
crossport views commits from 7.x-3.13 - 7.x-3.14 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3721]
- [x] | N/A | [5c2bfc96](http://drupalcode.org/project/drupal.git/commit/5c2bfc9638e3e78023d1efb754b79d4ac994d0c6) | [Revert "Issue #2204257 by ezra-g, andyg5000: Update Views Content access filter per core performance improvements"](http://drupal.org/node/2204257)
- [ ] | #xx | [db39913b](http://drupalcode.org/project/drupal.git/commit/db39913b82043b141747150e0868f3d0339784bb) | [Issue #2610292 by dawehner: Fix 7.x-3.x-dev test failures.](http://drupal.org/node/2610292)
- [ ] | #xx | [e5c8b656](http://drupalcode.org/project/drupal.git/commit/e5c8b65610fbfb93215466c2f234ec7aa825a1ba) | [Issue #339384 by lotyrin, neuquen, marcingy, colan: Default option <Any> not set in exposed filters when terms are selected](http://drupal.org/node/339384)
- [ ] | #xx | [6e352ed8](http://drupalcode.org/project/drupal.git/commit/6e352ed834e0cc23a1202443f3a653ac65b6d14b) | [Issue #551808 by dawehner, axel.rutz: Provide hook_views_save, hook_view_delete](http://drupal.org/node/551808)
- [x] | N/A (reverted later) | [88b7108b](http://drupalcode.org/project/drupal.git/commit/88b7108b2af12cc29577fbad202ea344251cc219) | [Issue #2290127 by DanChadwick: pre_render not consistently passed result by reference](http://drupal.org/node/2290127)
- [ ] | #xx | [c9598c27](http://drupalcode.org/project/drupal.git/commit/c9598c27028502483dab3bfce9ff25d07c05855f) | [Issue #1262630 by Jelle_S, dgtlmoon: Raw value tokens not replaced if used in css class](http://drupal.org/node/1262630)
- [ ] | #xx | [581e27d8](http://drupalcode.org/project/drupal.git/commit/581e27d8f18f0933fec2397fed736077f9f1a1be) | [Issue #1262630 by damiankloip: Raw value tokens not replaced if used in css class](http://drupal.org/node/1262630)
- [ ] | #xx | [feaeb7c4](http://drupalcode.org/project/drupal.git/commit/feaeb7c4bc032d04bdca55a40a0c84a822f5165b) | [Issue #1685144 by marcelovani, dawehner, q0rban: Refactor init_localization() to init and return the translate property for all plugins.](http://drupal.org/node/1685144)
- [x] | N/A | [e095983b](http://drupalcode.org/project/drupal.git/commit/e095983b4eadf447a1323f13cd9e4f09f022ec20) | [Revert "Issue #2290127 by DanChadwick: pre_render not consistently passed result by reference"](http://drupal.org/node/2290127)
- [ ] | #xx | [bdf5b7f6](http://drupalcode.org/project/drupal.git/commit/bdf5b7f61b9d9472b3d8ea78a19de171794d83cb) | [Issue #1948578 by jweowu: Duplicate code. Issue #1515156 patch applied twice](http://drupal.org/node/1948578)
- [x] | N/A (reverted later) | [f3c64f9d](http://drupalcode.org/project/drupal.git/commit/f3c64f9d41a48eb0862abc1e208a90ac54a3048f) | [Issue #564106 by dawehner et al.: More link to point to custom URL](http://drupal.org/node/564106)
- [ ] | #xx | [0c9fa055](http://drupalcode.org/project/drupal.git/commit/0c9fa05599c41bccdf4cd630ccf01643b487f015) | [Issue #652610 by johnv, dawehner, colan, Les Lim: Stop caching when not set.](http://drupal.org/node/652610)
- [ ] | #xx | [09adda61](http://drupalcode.org/project/drupal.git/commit/09adda610e96b38b411b3f1953cf27bebca85da1) | [Issue #1090432 by fubhy, derhasi, rudiedirkx, IT-Cru: Allow additional field-to-field conditions with the default views_join handler](http://drupal.org/node/1090432)
- [ ] | #xx | [f9d7151d](http://drupalcode.org/project/drupal.git/commit/f9d7151de333ac4c927df80cf70ed99f61645355) | [Issue #1190900 by ls, philipz, Neograph734, Oniryck: Random sort from multiple value field in views](http://drupal.org/node/1190900)
- [ ] | #xx | [94efb780](http://drupalcode.org/project/drupal.git/commit/94efb78083b1effc555b6dce058718d11e50a1c8) | [Issue #1232920 by dawehner, Anybody, chiddicks: Hide earlier in the process.](http://drupal.org/node/1232920)
- [ ] | #xx | [4264f5ff](http://drupalcode.org/project/drupal.git/commit/4264f5ffe5582eb4eee70379978a580d28c08561) | [Issue #1482824 by DeFr, Alan Evans, robertom: Block display view ajax pager does not advance with multiple pagers on a page when the first pager > 0](http://drupal.org/node/1482824)
- [ ] | #xx | [aa989c4d](http://drupalcode.org/project/drupal.git/commit/aa989c4de4805780a9acd9f7abe09942ef4db34f) | [Issue #1608920 by dawehner, rudiedirkx, axel.rutz, solotandem, Anybody, JvE, helior: Add drop-button field display](http://drupal.org/node/1608920)
- [x] | N/A | [c734b45e](http://drupalcode.org/project/drupal.git/commit/c734b45ec347dc51ac1587e2d11d484578373d28) | [Revert "Issue #564106 by dawehner et al.: More link to point to custom URL"](http://drupal.org/node/564106)
- [ ] | #xx | [49aa55b1](http://drupalcode.org/project/drupal.git/commit/49aa55b1de0a4118da2681d6d48e17967bff10bb) | [Issue #564106 by rv0 et al.: More link to point to custom URL](http://drupal.org/node/564106)
- [ ] | #xx | [2ff67291](http://drupalcode.org/project/drupal.git/commit/2ff672918cb57cfaff192d491aedf89cdb1c15be) | [Issue #2563431 by joelpittet, lauriii: ajax_render should not be used; ajax_deliver should be used instead](http://drupal.org/node/2563431)
- [ ] | #xx | [22d2ebc0](http://drupalcode.org/project/drupal.git/commit/22d2ebc06e308f29102109ae10c21dc6c62d1f02) | [Issue #959048 by rooby, dawehner, joelpittet, pyry_p: Added a revision count.](http://drupal.org/node/959048)
- [ ] | #xx | [7bd62d1a](http://drupalcode.org/project/drupal.git/commit/7bd62d1a81dd0c4fba0bc46e80101acbc105501a) | [Issue #981870 by infojunkie, joelpittet, andypost: views::get_url() to skip default arguments](http://drupal.org/node/981870)
- [ ] | #xx | [e6e754b9](http://drupalcode.org/project/drupal.git/commit/e6e754b9b337d6fba2991fc24db556122d551bfa) | [Issue #1535912 by dawehner, joelpittet: Remove no-longer-necessary $condition variable.](http://drupal.org/node/1535912)
- [ ] | #xx | [7ca81248](http://drupalcode.org/project/drupal.git/commit/7ca812484871f14a0549adbe59ff9b2711a6c957) | [Issue #1567354 by joelpittet, robcolburn: Stop lowercasing undefined values.](http://drupal.org/node/1567354)
- [ ] | #xx | [41fbac72](http://drupalcode.org/project/drupal.git/commit/41fbac72e048085b3273f692586eff1561add8c6) | [Issue #1615438 by rsmylski, MediaFormat, awolfey, ParisLiakos: Search terms: nodes dont appear when using multiple arguments](http://drupal.org/node/1615438)
- [ ] | #xx | [4c4cedfc](http://drupalcode.org/project/drupal.git/commit/4c4cedfc0e9177cb7d8820e6a8c37729e5bd7222) | [Issue #1358412 by davidgrayston, marcelovani, jamiecuthill, mikeytown2, ParisLiakos, Josh Waihi: Content: Has taxonomy term ID (with depth) query performance](http://drupal.org/node/1358412)
- [ ] | #xx | [bf1e53a5](http://drupalcode.org/project/drupal.git/commit/bf1e53a5121f906a96778ed6158a3a7d87cf2fb9) | [Issue #1359298 by robertwb: Support Plugins for Views Aggregate in D7 (D8 Backport)](http://drupal.org/node/1359298)
- [ ] | #xx | [7a4e5ab1](http://drupalcode.org/project/drupal.git/commit/7a4e5ab1cf6f73211714c7210f15c2df3495af7b) | [Issue #2708535 by stefan.r: Allow users to sort on a specific language, showing it before any others](http://drupal.org/node/2708535)
- [ ] | #xx | [bebb2ffc](http://drupalcode.org/project/drupal.git/commit/bebb2ffcc66a7bbede9d4c53d0417cd806e9c53f) | [Issue #2200309 by helmo: Changed invalid placeholder from "handler" to "extender".](http://drupal.org/node/2200309)
- [x] | N/A | [485b6970](http://drupalcode.org/project/drupal.git/commit/485b697082cf2ec42cc596eed952daa6f61e8012) | [Adding field handlers for statistics fields](http://drupal.org/node/)
