### ISSUE TITLE
crossport views commits from 7.x-3.15

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3722]
- [ ] | #xx | [2f39f5ce](http://drupalcode.org/project/drupal.git/commit/2f39f5ceebb6871911b0a486f90ab40d63148da8) | [Issue #2761829 by DamienMcKenna, jeroen.b: Getting drupal_trigger_error_with_delayed_logging errors on Drupal 7.x dev (7.50)](http://drupal.org/node/2761829)
- [ ] | #xx | [4301e37a](http://drupalcode.org/project/drupal.git/commit/4301e37af0cfd99267e5c060c53e2b796fdc251d) | [Issue #2037749 by JvE: Removed form_process_select from the process array.](http://drupal.org/node/2037749)
- [ ] | #xx | [33c86b54](http://drupalcode.org/project/drupal.git/commit/33c86b54e238b1ffc8b82a5e98b70721867c9903) | [Issue #2272387 by tedfordgif, heylookalive, tanc, weseze: Prevent jump menu warning message by checking for an empty value.](http://drupal.org/node/2272387)
- [ ] | #xx | [2d365485](http://drupalcode.org/project/drupal.git/commit/2d365485995c3cac3c56137253cfda68ac7c9478) | [Issue #1803758 by Scott Robertson, bsuttis: AJAXified glossary view arguments fail when Language URL detection enabled](http://drupal.org/node/1803758)
- [ ] | #xx | [c1d60422](http://drupalcode.org/project/drupal.git/commit/c1d60422a013145cf00d315366f9b2c99b253b57) | [Issue #2628960 by Fabianx: Time-based output cache key no longer changes when database results change, results cache no longer depends on _GET parametrs](http://drupal.org/node/2628960)
- [ ] | #xx | [63e1d67c](http://drupalcode.org/project/drupal.git/commit/63e1d67c7125cdcf7e5aeaeefe375f8c49ce92d8) | [Issue #2754667 by temkin: "In none of" (= Off/0) filter operator stopped working after Views update to 7.x-3.14](http://drupal.org/node/2754667)
- [ ] | #xx | [9227dc99](http://drupalcode.org/project/drupal.git/commit/9227dc992c2b201318387f50b6c6b36e1da4ad2b) | [Issue #1806266 by derhasi, axel.rutz: Complete entity_uri support for taxonomy_term](http://drupal.org/node/1806266)
- [ ] | #xx | [308fe88a](http://drupalcode.org/project/drupal.git/commit/308fe88aedadcbb3c37b3f25cdebef4ae92c46b1) | [Add additional query tags](http://drupal.org/node/)
