### ISSUE TITLE
crossport views commits from 7.x-3.16

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3723]
- [ ] | #xx | [b5a14eab](http://drupalcode.org/project/drupal.git/commit/b5a14eabe3944ef36074166de7bb4c138a2459f8) | [Issue #1090432 by fubhy, Sam152, derhasi, rudiedirkx, othermachines, IT-Cru: Allow additional field-to-field conditions with the default views_join handler](http://drupal.org/node/1090432)
- [ ] | #xx | [7c42020b](http://drupalcode.org/project/drupal.git/commit/7c42020baffba67b5bc354c231f78972ca6c8e41) | [Issue #2768893 by joelpittet: Remove version compare for < PHP 5 because 5.2 is required by Drupal 7.](http://drupal.org/node/2768893)
- [ ] | #xx | [8d944c63](http://drupalcode.org/project/drupal.git/commit/8d944c6382cc6f198706dbef6881768e07a219ef) | [Issue #2750021 by bsains: View Styles Plugin - row CSS class name was forced to lowercase.](http://drupal.org/node/2750021)
- [ ] | #xx | [6451346d](http://drupalcode.org/project/drupal.git/commit/6451346da4daed39d4a2b6e974746e984a461b33) | [Issue #2422175 by IshaDakota, Canutza: Typo in help text for "Remove Search Score" setting in search term filter.](http://drupal.org/node/2422175)
- [ ] | #xx | [4260e0a7](http://drupalcode.org/project/drupal.git/commit/4260e0a7f6974f7b350f54e52cf099d00cc56037) | [Issue #2704557 by Rob C: Missing variable declaration in base.js.](http://drupal.org/node/2704557)
- [ ] | #xx | [74931fc6](http://drupalcode.org/project/drupal.git/commit/74931fc6c3a6f3e12ae402430b640edb0145cc57) | [Issue #894560 by Alan D., mstrelan: Fixed additional warnings from invalid values being passed to format_date().](http://drupal.org/node/894560)
- [ ] | #xx | [d144ae76](http://drupalcode.org/project/drupal.git/commit/d144ae762c812147f136d902522cdbd5743df22d) | [Issue #2292721 by mpdonadio: Do not cause WSOD errors if comment.module is disabled.](http://drupal.org/node/2292721)
- [ ] | #xx | [6643464a](http://drupalcode.org/project/drupal.git/commit/6643464a827f995a1bcbecabf820842cba901ba1) | [Issue #2446697 by tom.gillett: hook_views_post_render() did not work correctly if the current theme had a base theme.](http://drupal.org/node/2446697)
- [ ] | #xx | [2f51e614](http://drupalcode.org/project/drupal.git/commit/2f51e61416d2f45f01cb7708cd7e5a127b90f579) | [Issue #2553207 by Pravin Ajaaz: Invalid HTML entity in code example in views.api.php.](http://drupal.org/node/2553207)
- [ ] | #xx | [f969f3f9](http://drupalcode.org/project/drupal.git/commit/f969f3f976116c2050bc3c1a5c0762d634f8f0e7) | [Issue #2704459 by hiramanpatil: Views display "path" setting title should show the full path rather than the truncated version.](http://drupal.org/node/2704459)
- [ ] | #xx | [9649e5d5](http://drupalcode.org/project/drupal.git/commit/9649e5d54d6a2011d4f35c005ce4bb6534d46396) | [Issue #2572117 by Steven Jones, liezie_D: Support for the AJAX path validation added to core 7.39.](http://drupal.org/node/2572117)
- [ ] | #xx | [44e23d61](http://drupalcode.org/project/drupal.git/commit/44e23d612507d138dba18e47a2df060d06f97763) | [Issue #1822368 by mojzis: Missing return in area plugin example.](http://drupal.org/node/1822368)
- [ ] | #xx | [f353a77e](http://drupalcode.org/project/drupal.git/commit/f353a77e327b63f0de7beeb6336faef178a8951e) | [Issue #2069677 by nbourdial, DamienMcKenna, rossb89, harivenuv: Initialize the query if needed when initializing a pager.](http://drupal.org/node/2069677)
- [ ] | #6843  | [2f23c3e0](http://drupalcode.org/project/drupal.git/commit/2f23c3e081eb1f2049211be2e836b1d085638251) | [Issue #2315365 by alexdmccabe: Pager should be built with view::get_exposed_input(), not $view->exposed_raw_input.](http://drupal.org/node/2315365)
- [ ] | #xx | [8514d635](http://drupalcode.org/project/drupal.git/commit/8514d63510c6a2d82384db4bc80e9fdd89604ca7) | [Issue #2514694 by MustangGB: uid=NULL displays username as "Anonymous" rather than leave an empty response.](http://drupal.org/node/2514694)
- [x] #1578 | [78ecd55e](http://drupalcode.org/project/drupal.git/commit/78ecd55e5df5b45d4e04506e56e4aa4c060a6d8c) | [Issue #1456836 by gifad: Verify the "identifier" variable exists in is_identifier_unique() before using it.](http://drupal.org/node/1456836)
- [ ] | #xx | [eacc8d0f](http://drupalcode.org/project/drupal.git/commit/eacc8d0f3d2be5090e82f4ebc4adced9c97fdb40) | [Issue #1962712 by Cottser: Description for "Global: Combine" fields filter is inaccurate.](http://drupal.org/node/1962712)
- [ ] | #xx | [36eef6ea](http://drupalcode.org/project/drupal.git/commit/36eef6ea09967bdf63dc3bfa3ba2ee3c2ffcf59e) | [Issue #1930288 by kristiaanvandeneynde, MustangGB, DamienMcKenna: views_join: incorrect handling of $extra parameter.](http://drupal.org/node/1930288)
- [ ] | #xx | [8d349f48](http://drupalcode.org/project/drupal.git/commit/8d349f485677861fd59d245a58e3c8a835bfccb6) | [Issue #1881910 by Berdir, johnv, miro_dietiker: Multiple exposed filters conflict, ignores "remember" option.](http://drupal.org/node/1881910)
- [ ] | #xx | [f80763cf](http://drupalcode.org/project/drupal.git/commit/f80763cfe54962ecedcba75dddeecf6daa01d60e) | [Issue #2051869 by rudiedirkx: this.pagerAjax in attachPagerLinkAjax() is overwritten by every next link.](http://drupal.org/node/2051869)
- [ ] | #xx | [d65aa619](http://drupalcode.org/project/drupal.git/commit/d65aa61901b262ae6b4ef81ba0f96ff45d7675c0) | [Issue #1785224 by mstef: Search term bug when less than 4 characters.](http://drupal.org/node/1785224)
- [ ] | #xx | [31ec6004](http://drupalcode.org/project/drupal.git/commit/31ec600416745cb79583339bce55923df7b587cd) | [Issue #2328791 by chrisolof: entity_uri() options not retained when rendering links for taxonomy terms.](http://drupal.org/node/2328791)
- [ ] | #xx | [0c8e3753](http://drupalcode.org/project/drupal.git/commit/0c8e375342af111ec5e6250d9866bbe7570e38ad) | [Issue #2040281 by grasmash, znerol: Views PHP Fatal error: view::destroy() on cache clear when autoload enabled.](http://drupal.org/node/2040281)
- [ ] | #xx | [fb9b83ed](http://drupalcode.org/project/drupal.git/commit/fb9b83ed600884bad22e4944811885d61742d591) | [Issue #2324931 by alex_drupal_dev, Owen Barton, harsha012, dhaval_panara, fegade_ravindra, paresha.uchdadiya: Comment missing period (coding standards).](http://drupal.org/node/2324931)
- [ ] | #xx | [1296e973](http://drupalcode.org/project/drupal.git/commit/1296e973598a73c36b42dbca76d93b7c51dab21b) | [Issue #2828378 by dscl, jansete, klausi: Inconsistent name for term access query - SA-CORE-2016-005.](http://drupal.org/node/2828378)
- [ ] | #xx | [c63d584c](http://drupalcode.org/project/drupal.git/commit/c63d584c0efe94fa89dd45b61f72844226c4d7fb) | [Issue #1843776 by Cottser, joelpittet, sdstyles, steveoliver, Pete B: Remove unused template views-ui-edit-item.tpl.php.](http://drupal.org/node/1843776)
- [ ] | #xx | [2a98bc54](http://drupalcode.org/project/drupal.git/commit/2a98bc54d63cc20bfca7182cc23e7a8471d48e13) | [Issue #2609312 by mjpa: Wrong invocation of hook_views_query_substitutions.](http://drupal.org/node/2609312)
- [ ] | #xx | [641848a8](http://drupalcode.org/project/drupal.git/commit/641848a84faae9d964b38cd748398758d0564016) | [Issue #2689657 by cafuego: Comment date fields uses incorrect database column, added new fields for the actual "created" columns.](http://drupal.org/node/2689657)
- [ ] | #xx | [5bca3711](http://drupalcode.org/project/drupal.git/commit/5bca37119e68756932e81febbf1569c6c9bd910c) | [Issue #1567784 by Cottser, krina.addweb: Typo fix and grammar tweak for User - "Row style options" help text.](http://drupal.org/node/1567784)
- [ ] | #xx | [3c55ad84](http://drupalcode.org/project/drupal.git/commit/3c55ad84c51850735c24807c3c31e4ec4e1338b0) | [Issue #1715350 by aspilicious, dawehner, larowlan, jibran: Improved views_schema() to reduce out-of-memory errors.](http://drupal.org/node/1715350)
- [ ] | #xx | [5937d319](http://drupalcode.org/project/drupal.git/commit/5937d31953ed6c139fa2c080d5bb32291295ccf5) | [Issue #1684990 by scor, Bensbury: Added a description explaining why the "Remove tags from rendered output" is useful.](http://drupal.org/node/1684990)
- [ ] | #xx | [33060f5b](http://drupalcode.org/project/drupal.git/commit/33060f5b5bc4d3b2114c91a8d382eed5fb11578d) | [Issue #2850719 by greggadsdon: PHP 7 incompatibility in views_plugin_style_mapping.](http://drupal.org/node/2850719)
- [ ] | #xx | [478357d7](http://drupalcode.org/project/drupal.git/commit/478357d785163bca6a5a3fb08555c7ac6532a904) | [Issue #2564595 by badjava: "clone" is a reserved keyword introduced in PHP 5 and cannot be invoked as a function.](http://drupal.org/node/2564595)
- [ ] | #xx | [dcb46159](http://drupalcode.org/project/drupal.git/commit/dcb461594ca8a96b1461575c416634afeb7a87b1) | [Issue #2329923 by deviantintegral: Missing @return docs in query().](http://drupal.org/node/2329923)
- [ ] | #xx | [e33f07ec](http://drupalcode.org/project/drupal.git/commit/e33f07ec49d4565cf44117d0d5e2153392f36936) | [Issue #2003014 by InternetDevels: Unused variable $count in views_handler_area_result.](http://drupal.org/node/2003014)
- [ ] | #xx | [82a4cf12](http://drupalcode.org/project/drupal.git/commit/82a4cf12b38e0659339a96a651294d461315179c) | [Issue #2532932 by snehi, er.pushpinderrana: Typo in views.inc](http://drupal.org/node/2532932)
- [ ] | #xx | [b6988b02](http://drupalcode.org/project/drupal.git/commit/b6988b02b09d477e3e43cdde86b6c4666037e2e6) | [Issue #2758517 by ggrzywna: RTL support: buttons floated to the wrong side.](http://drupal.org/node/2758517)
- [ ] | #xx | [9042d0cc](http://drupalcode.org/project/drupal.git/commit/9042d0cc72571e6586c3ad0d3322620b556cde49) | [Issue #2864117 by hass: Simplify verbiage around adding CSS classes, plus a typo.](http://drupal.org/node/2864117)
- [ ] | #xx | [6118e4be](http://drupalcode.org/project/drupal.git/commit/6118e4be78f7474368e27cefc7468db444c49b54) | [Revert "Issue #2864117 by hass: Simplify verbiage around adding CSS classes, plus a typo."](http://drupal.org/node/2864117)
- [ ] | #xx | [74c50de5](http://drupalcode.org/project/drupal.git/commit/74c50de5bc832984eab1dc255aeee2905a5a2a9d) | [Issue #2138093 by DamienMcKenna, zhuber: Disallow "q" as custom filter identifier.](http://drupal.org/node/2138093)
- [ ] | #xx | [b31303e3](http://drupalcode.org/project/drupal.git/commit/b31303e3d1c0003bfeb6e662b618802260e03e4c) | [Issue #1760494 by DamienMcKenna: Allow the page title to be not assigned if it has the value "<none>", matching standard block title handling.](http://drupal.org/node/1760494)
- [ ] | #xx | [5df2dc4f](http://drupalcode.org/project/drupal.git/commit/5df2dc4fdb020c571f955e930490dae210d1bede) | [Issue #2752617 by Mirakolous, knalstaaf, jeni_dc, hein.corbet: Update to 7.x-3.14 breaks displays using CCS classes with spaces](http://drupal.org/node/2752617)
- [ ] | #xx | [026828e1](http://drupalcode.org/project/drupal.git/commit/026828e172287b69db613f0dfa5f4325a3ee8570) | [Issue #2754601 by joseph.olstad, Sergio.Tashdjian, sergiuteaca, malcolm_p: Pager stopped worked with all types of AJAX requests.](http://drupal.org/node/2754601)
