### ISSUE TITLE
crossport views commits from 7.x-3.17 - 7.x-3.18

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3724]
- [ ] | #xx | [28cae1ac](http://drupalcode.org/project/drupal.git/commit/28cae1ac11042af7502b12841d107b8745a326a5) | [Issue #2384395 by jonathan_hunt, krina.addweb, RenatoG: Typo in views pager full validation error message](http://drupal.org/node/2384395)
- [ ] | #xx | [5743ed95](http://drupalcode.org/project/drupal.git/commit/5743ed951dfce9733a1c3248b923a5fd6dadf8c3) | [Issue #2890079 by RenatoG: Fixed unused variables](http://drupal.org/node/2890079)
- [ ] | #xx | [5b32c044](http://drupalcode.org/project/drupal.git/commit/5b32c04469c3b934ae8e82d1c15c9ead9c71b61a) | [Issue #2890367 by RenatoG: Update README file for new template of Drupal.org](http://drupal.org/node/2890367)
- [ ] | #xx | [940206e0](http://drupalcode.org/project/drupal.git/commit/940206e0299670d53758db111375d06822c58bbc) | [Issue #2595333 by dbt102, cherebedov.s, dhruveshdtripathi, RenatoG: Add hook_help() implementation](http://drupal.org/node/2595333)
- [ ] | #xx | [b285f274](http://drupalcode.org/project/drupal.git/commit/b285f274b78f0d019fc8195903d7b4234a7f6b33) | [Issue #2890490 by RenatoG: Configure Link for Views UI refer to Settings instead of list](http://drupal.org/node/2890490)
- [ ] | #xx | [b1051039](http://drupalcode.org/project/drupal.git/commit/b10510397ce21ce2ab7f985c71d8eba4f5fdf99e) | [Issue #2887227 by sumanthkumarc, Algarte, RenatoG: Display comments option not shown in row style options for node view](http://drupal.org/node/2887227)
- [ ] | #xx | [812a57e1](http://drupalcode.org/project/drupal.git/commit/812a57e1e3872229a648f05177c449f71c848bdb) | [Issue #2890785 by RenatoG: Fixed pareview recomendations for Views UI](http://drupal.org/node/2890785)
- [ ] | #xx | [b5fbdeff](http://drupalcode.org/project/drupal.git/commit/b5fbdeff4060c52daea41d7b934aba59f9660f2f) | [Issue #2838338 by RenatoG, RAWDESK, nico.knaepen: Pager more link opens in new window (target _blank)](http://drupal.org/node/2838338)
- [ ] | #xx | [42ae0cfd](http://drupalcode.org/project/drupal.git/commit/42ae0cfd8b6d6ed51f2bb2dc655f7ddd2b2f0f28) | [Issue #2890863 by RenatoG: Create shortcut for clear view's cache](http://drupal.org/node/2890863)
- [ ] | #xx | [a0fa5a8e](http://drupalcode.org/project/drupal.git/commit/a0fa5a8ef1bb84211ee077f825ce718f0329979d) | [Revert "Issue #2890863 by RenatoG: Create shortcut for clear view's cache"](http://drupal.org/node/2890863)
- [ ] | #xx | [59c2d413](http://drupalcode.org/project/drupal.git/commit/59c2d4137df1bb497ab3b20645706f643e9cd044) | [Issue by maximpodorov, klausi, dawehner, drumm, mlhess, xjm, Wim Leers, lendude, pwolanin, dsnopek: Ensure we check for ajax to be configured](http://drupal.org/node/)
- [ ] | #xx | [3439ab35](http://drupalcode.org/project/drupal.git/commit/3439ab35c0d5b4aae1170866be90e2d45d63bd0b) | [Issue by maximpodorov, klausi, dawehner, drumm, mlhess, xjm, Wim Leers, lendude, pwolanin, dsnopek: Ensure we check for ajax to be configured](http://drupal.org/node/)
- [ ] | #xx | [04e87cc0](http://drupalcode.org/project/drupal.git/commit/04e87cc0fb6bcbd39e6d49e549209426259e51ba) | [Issue #2903006 by Stevel, DamienMcKenna: Fix tests for 7.x-3.x.](http://drupal.org/node/2903006)
- [ ] | #xx | [7e3a463c](http://drupalcode.org/project/drupal.git/commit/7e3a463caeef689e5d383d8e2befdfe7658a4271) | [Issue #2852791 by akshay4627: Fixed: Undefined index: field_FIELDNAME in views_handler_filter_term_node_tid->exposed_validate().](http://drupal.org/node/2852791)
- [ ] | #xx | [028bae8b](http://drupalcode.org/project/drupal.git/commit/028bae8bc935f45007c5dd2680b11de45516b7d7) | [Issue #2879960 by Jill L: The "extra" parameter in search_dataset must be an array like all other definitions.](http://drupal.org/node/2879960)
- [ ] | #xx | [5e00d963](http://drupalcode.org/project/drupal.git/commit/5e00d963bfb732bd0e3cac9f33c46dcc4b171172) | [Issue #2866370 by hargobind, Rudi Teschner, DamienMcKenna, schwarli4783, Dmitry Pogodaev, dotline, alzz, bohz, hartsak, loze, perarg, steveganz, sergei_brill, knalstaaf, berenddeboer, attisan, AlfTheCat, nironan, RoSk0, J-Lee, artis, drupalfan2, marco-s, hossein425: Join 'extras' should be an array.](http://drupal.org/node/2866370)
- [ ] | #xx | [4cfe62cb](http://drupalcode.org/project/drupal.git/commit/4cfe62cb259287cee0e5ddeb8f3cdf26bb61499b) | [Issue #2890490 by DamienMcKenna: Reverted the config path change.](http://drupal.org/node/2890490)
