### ISSUE TITLE
crossport views commits from 7.x-3.19

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3725]
- [ ] | #xx | [505c936e](http://drupalcode.org/project/drupal.git/commit/505c936ec05c4674ce3c84f3bd7dc596125a794e) | [Issue #2913993 by DamienMcKenna: Document how to run all of the tests in one go.](http://drupal.org/node/2913993)
- [ ] | #xx | [84facc81](http://drupalcode.org/project/drupal.git/commit/84facc81fc2ff1e02be952758c07bb2736a0b987) | [Issue #2920737 by DamienMcKenna, MustangGB: Major code cleanup; resolved most of the coding standards violations, excluding class, method and property names.](http://drupal.org/node/2920737)
- [ ] | #xx | [ee57c167](http://drupalcode.org/project/drupal.git/commit/ee57c167740eacc2c39c4f3bbe8682e162a517e7) | [Issue #2908538 by weri: Extras "OR" conditions not enclosed correctly.](http://drupal.org/node/2908538)
- [ ] | #xx | [458d2a82](http://drupalcode.org/project/drupal.git/commit/458d2a82735eaedca7a872246a148f7b193b42b8) | [Issue #2760419 by joelpittet, joseph.olstad, DamienMcKenna, willzyx, dsutter: get_option() micro optimization by using isset() before array_key_exists().](http://drupal.org/node/2760419)
- [ ] | #xx | [00964310](http://drupalcode.org/project/drupal.git/commit/00964310f8b05756c439c7c177cc703ada4432e2) | [Issue #2904559 by volkswagenchick, prafull.addweb, RenatoG, loopduplicate: Typo in views_plugin_pager_full::exposed_form_validate() error message.](http://drupal.org/node/2904559)
- [ ] | #xx | [f6e8072a](http://drupalcode.org/project/drupal.git/commit/f6e8072a8519442097f5e62fd26b05be86d051ce) | [Issue #2862348 by DamienMcKenna, rsvelko, alan.cole: ajax_view.js is not compatible with jQuery 3+, use .length instead of .size().](http://drupal.org/node/2862348)
- [ ] | #xx | [ecfdf7d9](http://drupalcode.org/project/drupal.git/commit/ecfdf7d954c2ddb5de805e85664c26d1eb962074) | [Issue #2760405 by joelpittet, joseph.olstad, dsutter, gdaw: Reduce the calls to the same t() in views_fetch_fields().](http://drupal.org/node/2760405)
- [ ] | #xx | [bb1d8129](http://drupalcode.org/project/drupal.git/commit/bb1d8129896b9bc8af7c5c4c210467d437645770) | [Issue #2653266 by joelpittet, joseph.olstad, dsutter, gdaw: Avoid excess t() calls in field_views_field_default_views_data().](http://drupal.org/node/2653266)
- [ ] | #xx | [fd3d3f8b](http://drupalcode.org/project/drupal.git/commit/fd3d3f8b1c29203d5580e22351939dd53ce44bd1) | [Issue #2653214 by joelpittet, joseph.olstad, dsutter, gdaw: Replace views_include() with include_once.](http://drupal.org/node/2653214)
- [ ] | #xx | [b16774fe](http://drupalcode.org/project/drupal.git/commit/b16774fe58a6b5b26b4618e9fbc9367a1f6d9075) | [Issue #2834290 by larsmw, RenatoG: Unnecessary array copy in views_handler_field_field->set_items.](http://drupal.org/node/2834290)
- [ ] | #xx | [47db4ff0](http://drupalcode.org/project/drupal.git/commit/47db4ff0bbb2eadcd6bbd67340852e942f554285) | [Issue #2904610 by larsmw, DamienMcKenna, Dinesh18, MustangGB, RenatoG: Unnecessarily microtime() call in views_block_view().](http://drupal.org/node/2904610)
- [ ] | #xx | [a4cf6d70](http://drupalcode.org/project/drupal.git/commit/a4cf6d70e6f79ed65219f300bcb527d6cd1e6ded) | [Issue #2921934 by DamienMcKenna: aggregator_views_data() contains two definitions for $data['aggregator_item']['iid'].](http://drupal.org/node/2921934)
- [ ] | #xx | [a5caa46e](http://drupalcode.org/project/drupal.git/commit/a5caa46efd91264250d9abeb09a46559d8d17545) | [Issue #2492687 by dikini: An infinite loop in include/handlers.inc can cause denial of service.](http://drupal.org/node/2492687)
- [ ] | #xx | [f3985652](http://drupalcode.org/project/drupal.git/commit/f3985652fc70314fea2bdfe6ada6e3b7cbc4c763) | [Issue #2946216 by DamienMcKenna: Remove usage of deprecrated each() function for PHP 7.2+ future proofing](http://drupal.org/node/2946216)
- [ ] | #xx | [3cc63885](http://drupalcode.org/project/drupal.git/commit/3cc63885918474b7a7cdb9095fecd89785e3b8f3) | [Issue #2946216 by DamienMcKenna: Follow up to improve logic in views_ui_ajax_form().](http://drupal.org/node/2946216)
- [ ] | #xx | [b30711c2](http://drupalcode.org/project/drupal.git/commit/b30711c2dd45479c3a848eac39954f53ce430e28) | [Issue #1995056 by bpleduc, marvin_B8: Exposed grouped filter gives WSOD+error "Cannot create references to/from string offsets nor overloaded objects".](http://drupal.org/node/1995056)
- [ ] | #xx | [de8e5255](http://drupalcode.org/project/drupal.git/commit/de8e5255713700ee0e5f04789083b76ae36a5a82) | [Issue #2684749 by vistree, Neo13, wfragakis, introfini: Error in views_handler_field_user_picture.inc if user picture fid exists but file cannot be loaded.](http://drupal.org/node/2684749)
- [ ] | #xx | [22622c95](http://drupalcode.org/project/drupal.git/commit/22622c95760dffdcda8d3b64b032298184eaa66c) | [Issue #2610418 by MustangGB, DamienMcKenna, rudiedirkx, flaviovs: Add option_definition alter to make all handlers & plugins more extensible.](http://drupal.org/node/2610418)
- [ ] | #xx | [807bd102](http://drupalcode.org/project/drupal.git/commit/807bd1028fa86fb778d503c76357d73dc486a4e4) | [Issue #2295379 by DamienMcKenna, nvahalik, fonant, bmango, bardenjed, joegl: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.uid1' in 'where clause'.](http://drupal.org/node/2295379)
- [ ] | #xx | [325f6be2](http://drupalcode.org/project/drupal.git/commit/325f6be2ba3ec27d0bc398dad83aeba4b1429b4d) | [Issue #1264794 by dsnopek: Views exposed autocomplete + ajax view = form submit happens too early.](http://drupal.org/node/1264794)
- [ ] | #xx | [0571e092](http://drupalcode.org/project/drupal.git/commit/0571e09200d09b056f34f9389ae34dbc6c77cd07) | [Issue #2638220 by phergo, jojonaloha, jantoine, Mav-im, jweowu, joanpebupe, shagren, fabio84: "Content translation: Translations" relationship broken.](http://drupal.org/node/2638220)
- [ ] | #xx | [e3e8e315](http://drupalcode.org/project/drupal.git/commit/e3e8e31554c94fe69196f31f81ec991aef52570c) | [Issue #2452655 by MrHaroldA, AdamPS, fonant, zmove: Defaults not working for grouped filter with multiple selections](http://drupal.org/node/2452655)
- [ ] | #xx | [ec54a7d6](http://drupalcode.org/project/drupal.git/commit/ec54a7d6db458ac29eb3ad99e2d1b13de1684670) | [Issue #1984694 by hkirsman, drumm: Increase weight #delta along with the number of grouped filters](http://drupal.org/node/1984694)
- [ ] | #xx | [aff92c08](http://drupalcode.org/project/drupal.git/commit/aff92c08791e5bb01271e5e661375d04f46fcd8a) | [Issue #2476297 by nicrodgers, David_Rothstein: Views cache should be segmented based on content language, not just interface language.](http://drupal.org/node/2476297)
- [ ] | #xx | [3fc24593](http://drupalcode.org/project/drupal.git/commit/3fc245930f035a14f6f5bae589f29dbad76bcfcd) | [Issue #1875878 by DamienMcKenna, joseph.olstad, ultimateboy, phiscock, JayDarnell: User picture field doesn't have alt attribute when using non-default image style.](http://drupal.org/node/1875878)
- [ ] | #xx | [df56e74b](http://drupalcode.org/project/drupal.git/commit/df56e74b663854fecd02333874fe3b6fd01d87c0) | [Issue #1417090 by eosrei, prinds, jamix, rbp, fadi.assaad, drupov, bmango, Countzero, dawehner, darrenmothersele: Taxonomy term "Representative node" views with filters and sorts don't work.](http://drupal.org/node/1417090)
- [ ] | #xx | [4c60cf4a](http://drupalcode.org/project/drupal.git/commit/4c60cf4a26203c7ffb9b21441291d1039bb6ce09) | [Issue #2725131 by DamienMcKenna, boombatower, dasha_v: Rename hook_views_pre_view() because it doesn't work as described](http://drupal.org/node/2725131)
- [ ] | #xx | [82987986](http://drupalcode.org/project/drupal.git/commit/82987986d4ca7b4efc91ecfcbedede60b4256d9f) | [Issue #1331056 by thekevinday, robertwb, steinmb, DamienMcKenna, joseph.olstad, chamilsanjeewa, Proteo, dawehner, steverweber, hubScrappy, tim.plunkett, colan, acbramley, stevector, merlinofchaos, sylus, seanB, scott.whittaker, matheushamonangan, drmabuse_, bellerophons_pegasus: Regression: Improper use of GROUP BY statement produces ambiguous column error.](http://drupal.org/node/1331056)
