### ISSUE TITLE
[META] Date handling improvements

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3747]
Related issues:

- [ ] [UX] Date formats - prevent month vs day confusion - https://github.com/backdrop/backdrop-issues/issues/989
- [ ] Set date formats by country - https://github.com/backdrop/backdrop-issues/issues/1521
- [ ] [DX] Make date formats individually exportable - https://github.com/backdrop/backdrop-issues/issues/3467
- [ ] Make date field display the same date in examples - https://github.com/backdrop/backdrop-issues/issues/4510
- [ ] Do not capitalize the word "Date" in the OOTB date formats - https://github.com/backdrop/backdrop-issues/issues/4522
- [ ] Allow selecting an existing date format for log messages - https://github.com/backdrop/backdrop-issues/issues/4621
- [ ] Add a Day/Month/YYYY date format to to core - https://github.com/backdrop/backdrop-issues/issues/4645
- [ ] Use the default date entry format for the default date display format - https://github.com/backdrop/backdrop-issues/issues/4646

- - - - - -

This is the result of a quick research after looking into #3744. Similarly to the ongoing #3685, we need to keep the core Date module in par with the respective 7.x contrib module + keep an eye on date-related changes/improvements happening in D8 core (which also makes this issue part of #378).

Here's a list of issues I have found in d.org that we should consider:

- [Let TimestampItem (de)normalize to/from RFC3339 timestamps, not UNIX timestamps, for better DX](https://www.drupal.org/project/drupal/issues/2768651) ([change record](https://www.drupal.org/node/2859657)) (seems "bold"; has a backwards-compatible switch to retain "old" functionality, but will be deprecated in D9)

- [Date filter for UNIX Timestamp show wrong results because bad timezone handling](https://www.drupal.org/project/date/issues/2311501) (against Date 7.x; seems similar/related to previous D8 core issue/change, but could be wrong)

- [Allow the ChangedItem to skip updating](https://www.drupal.org/project/drupal/issues/2329253) and resulting contrib module: https://www.drupal.org/project/preserve_changed (8.x only)

- [Add 'published' timestamp to nodes](https://www.drupal.org/project/drupal/issues/1838918) and resulting contrib module: https://www.drupal.org/project/publication_date (both 8.x and 7.x)

    [comment](https://www.drupal.org/project/drupal/issues/1838918#comment-13035829) by @jstoller:
    > I think it's ridiculous this feature hasn't been implemented in core yet, but I don't have the bandwidth to fight for it now.

...this is by far an incomplete list; just thought I'd document it here as a future task. Lets add related issues as we come across them.
