### ISSUE TITLE
[META][D8][UX] Convert all confirmation pages to confirmation dialogs instead.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3769]
I had filed a couple of separate issues for this back in 2015, about specific pages. Let's make this issue here a meta to list all such issues.

First step would be:

- [ ] #3771 | [UX] Introduce a `confirm_dialog()` function (and use that one instead of `confirm_form()`)

Specific confirmation pages to be converted to dialogs:

- [ ] #769 | [UX] Move the confirmation dialog for deletion of nodes to a modal.
- [ ] #770 | [UX] Move the confirmation dialog for deletion of menu links to a modal.
- [ ] #3770 | [UX] Move the confirmation dialog for enabling/uninstalling modules to a modal.

Related D8 issues:

- [Add abstracted dialog to core (resolves accessibility bug)](https://www.drupal.org/project/drupal/issues/1667742)
- [[META] Convert all confirm forms already converted to new routing system to use modal dialog](https://www.drupal.org/project/drupal/issues/1842036)

Related D7 issues:
- [Ajax Popups in Drupal 7: Adding Modal Dialogs to Help, Confirmations and Filter tips (Unified)](https://www.drupal.org/project/drupal/issues/193311)
- [Popbox (Popups Lite): Adding Modal Dialogs to Confirmations](https://www.drupal.org/project/drupal/issues/374646)

(Triaged as possible accessibility issue on 08/17/2921. This one may or many not qualify, please add the [A11Y] tag if you think it qualifies.)

**Comment by klonos** [comment]
@BWPanda in https://github.com/backdrop/backdrop-issues/issues/1032#issuecomment-593799155 mentioned https://mdbootstrap.com/docs/jquery/modals/forms ...seems neat.

**Comment by klonos** [comment]
I've found a couple of old requests for this in D7 here:
- https://www.drupal.org/project/drupal/issues/193311
- https://www.drupal.org/project/drupal/issues/374646

**Comment by docwilmot** [comment]
Just a note that a `confirm_dialog` function wouldn't help. The `confirm_form()` function actually renders the confirm form itself so if youre using that function, youre already on the confirm form page, too late for a modal.

We'd need to go through all the links and buttons which _lead_ to a confirm form page, and add the `data-dialog` / `use-ajax` attributes to them. 

This would be a manual one by one thing for the 47 calls in core though.

**Comment by robertgarrigos** [comment]
It will not be a need, though. confirm_form will still work as usual.

**Comment by robertgarrigos** [comment]
> This would be a manual one by one thing for the 47 calls in core though.

@docwilmot, what search do you do to find those 47 calls? Looking for `$links['delete']`gives me 22 results. Searching for `return confirm_form`gives me 41 results. How did you get with those 47 calls?

**Comment by robertgarrigos** [comment]
I would like to give this other approach a try. Should I open a new issue for it?

**Comment by DevinCarlson** [comment]
The linked PR converts all of the form action buttons that currently utilize a confirm form including blocks, fields, file types, menus, node types, paths, redirects and taxonomy terms.

Not covered is anything that uses a drop button (like deleting files, nodes, etc from the their listing pages) or more advanced operations that only sometimes utilize a confirm form, like installing a module with/without dependencies.

Confirm forms now only display a cancel link when they are rendered outside of a dialog, as the dialogs can already be 'cancelled' by simply closing them.

This also fixes #7063, as it adds the danger styling to 'delete' action buttons.

**Comment by izmeez** [comment]
@DevinCarlson The PR applies as a patch without difficulty and works for me. Thanks.

**Comment by olafgrabienski** [comment]
@DevinCarlson - Thanks for the PR! I've had a look at the field delete dialog, and it works for me.

> Confirm forms now only display a cancel link when they are rendered outside of a dialog, as the dialogs can already be 'cancelled' by simply closing them.

I'm not sure if I agree with not offering a cancel link in modal dialogs. For me, a _Cancel_ link is more clear than a _Close_ button. Furthermore, Backdrop already offers _Cancel_ links in modal dialogs, at least sometimes (see screenshot below). I'd suggest to keep the _Cancel_ links for the time being and to discuss the topic in a separate issue.

**Screenshot: Cancel button in dialog example**
<img width="400" alt="Screenshot" src="https://github.com/user-attachments/assets/14a8b5f3-f2e5-4a73-9ef8-16fef394ce75" />

**Comment by izmeez** [comment]
I agree with @olafgrabienski having a `Cancel` in the example is helpful for people to see.
