### ISSUE TITLE
[D8][META] Consider adding modules/features to core for parity with Drupal 8/9/10

### ISSUE THREAD

**Issue by dgoutam** [backdrop/backdrop-issues#378]
Based on the [presentation by Dave Reid at Drupalcon Amsterdam 2014](http://youtu.be/WEQAAJX9dA0), the ["Core modules" list in d.org](https://www.drupal.org/docs/8/core/modules/) and other sources (like the [d.org issue queue](https://www.drupal.org/project/issues/drupal) and the [D8 change records](https://www.drupal.org/list-changes/published?version=8.x)).

**Modules to be added**:
- [ ] #282 | [admin_language](https://www.drupal.org/project/admin_language)
- [ ] #475 | [simplified_menu_admin](https://www.drupal.org/project/simplified_menu_admin)
- [ ] #1009 | [modernizr](https://www.drupal.org/project/modernizr)
- [ ] #1040 | [Inline Form Errors](https://www.drupal.org/project/ife) & [Inline Messages](https://www.drupal.org/project/inline_messages)
- [ ] #1374 | [i18n](https://www.drupal.org/project/i18n)
- [ ] #1375 | [i18nviews](https://www.drupal.org/project/i18nviews)
- [ ] #1377 | [l10n_update](https://www.drupal.org/project/l10n_update)(https://www.drupal.org/project/field_formatter_settings)
- [ ] #1384 | [filter_html_image_secure](https://www.drupal.org/project/filter_html_image_secure)
- [ ] #1403 | [Form Element Layout](https://www.drupal.org/project/fel) / https://www.drupal.org/project/drupal/issues/314385 / https://www.drupal.org/node/2324025
- [ ] #1840 Merge Special Menu Items module functionality in core | https://www.drupal.org/node/2698057
- [ ] #1878 Bring back the "ban IP" feature | https://www.drupal.org/docs/8/core/modules/ban/overview
- [ ] #2101 | [Add hidden and read-only field widgets](https://www.drupal.org/node/1465774)
- [ ] #2498 | [Trash](https://www.drupal.org/project/trash) / https://www.drupal.org/node/2797395 / https://www.drupal.org/project/drupal/issues/2797247 / https://www.drupal.org/project/ideas/issues/2786135 / https://www.drupal.org/project/drupal/issues/2725449
- [ ] #2658 | CKEditor: Allow Image Styles to be used with inline images
- [ ] #314 | [multiple_fields_remove_button](https://www.drupal.org/project/multiple_fields_remove_button) or [field_remove_item](https://www.drupal.org/project/field_remove_item): https://www.drupal.org/project/drupal/issues/1038316
- [ ] #3157 | [save_draft](https://www.drupal.org/project/save_draft)
- [ ] #3656 | Views: Expose responsive classes in the UI via table settings

**Other misc changes we might also want to consider**:
- [ ] #243 | Convert user pictures to an actual Image Field (2.x)| https://www.drupal.org/node/1292470 (change record: https://www.drupal.org/node/1851200)
- [ ] #422 | Allow menu items to be created even if no page exists at that path | https://www.drupal.org/node/2693725
- [ ] #475 | Clean up & simplify the menu administration | https://www.drupal.org/node/663946
- [ ] #1145 | Entity bundles should declare both a singular and a plural form of their label | https://www.drupal.org/node/23298 / https://www.drupal.org/node/1850080 (change record: https://www.drupal.org/node/2689949)
- [ ] #2921 | Add new formatter - "URL to Image" to image field in Views
- [ ] #4127 | [PS][D8] Advanced Drupal Caching (a.k.a. [cache tags](https://www.drupal.org/project/cachetags) and cache max-age)
- [ ] #6100

**Feature parity with the Layout Builder module in modern drupal:
- [ ] #1131 | [UX] Create/select layout for a specific page from the content add/edit form.
- [ ] #2894 | [UX] Create/select layout for specific content type from the content type add/edit form.

**Modules/features already added**:
- [x] #1301 | [entityreference](http://www.drupal.org/project/entityreference)
- [x] #1380 | [multiupload_filefield_widget](https://www.drupal.org/project/multiupload_filefield_widget)
- [x] #1380 | [multiupload_imagefield_widget](https://www.drupal.org/project/multiupload_imagefield_widget)
- [x] #1382 | [secure_permissions](https://www.drupal.org/project/secure_permissions)
- [x] #1475 | Better workflow states and content save options | https://www.drupal.org/node/282122 / https://www.drupal.org/node/218755 / https://www.drupal.org/node/1777388
- [x] #40 | [rss_permissions](https://www.drupal.org/project/rss_permissions)
- [x] #40 | [views](https://www.drupal.org/project/views)
- [x] #74 | [entity_cache](https://www.drupal.org/project/entity_cache)
- [x] #86 | [multiblock](https://www.drupal.org/project/multiblock)
- [x] #86 | [responsive_bartik](https://www.drupal.org/project/responsive_bartik)
- [x] #100 | [bean](https://www.drupal.org/project/bean)
- [x] #101 | [caption_filter](https://www.drupal.org/project/caption_filter)
- [x] #101 | [ckeditor](https://www.drupal.org/project/ckeditor)
- [x] #104 | [dialog](https://www.drupal.org/project/dialog)
- [x] #142 | [views_bulk_operations](https://www.drupal.org/project/views_bulk_operations)
- [x] #151 | [admin_views](https://www.drupal.org/project/admin_views)
- [x] #169 | [configuration](https://www.drupal.org/project/configuration)
- [x] #169 | [defaultconfig](https://www.drupal.org/project/defaultconfig)
- [x] #189 | [navbar](https://www.drupal.org/project/navbar)
- [x] #200 | [elements](https://www.drupal.org/project/elements)
- [x] #200 | [html5_tools](https://www.drupal.org/project/html5_tools)
- [x] #240 | [link](https://www.drupal.org/project/link)
- [x] #300 | [instantfilter](https://www.drupal.org/project/instantfilter)
- [x] #313 | [RoleAssign](https://www.drupal.org/project/roleassign) | https://www.drupal.org/project/drupal/issues/267342
- [x] #315 | [entity_view_mode](https://www.drupal.org/project/entity_view_mode)
- [x] #382 | [taxonomy_access_fix](https://www.drupal.org/project/taxonomy_access_fix)
- [x] #476 | [email](https://www.drupal.org/project/email)
- [x] #478 | [date](https://www.drupal.org/project/date)
- [x] #479 | [views_responsive_grid](https://www.drupal.org/project/views_responsive_grid)
- [x] #845 | [menu_block](https://www.drupal.org/project/menu_block)
- [x] #904 | [transliteration](https://www.drupal.org/project/transliteration)
- [x] #1371 | [entity](https://www.drupal.org/project/entity)
- [x] #1376 | [field_formatter_settings](https://www.drupal.org/project/field_formatter_settings) / [hook_field_formatter_settings_summary_alter()](http://api.drupal.org/api/drupal/core!modules!field_ui!field_ui.api.php/function/hook_field_formatter_settings_summary_alter/8) / [hook_field_formatter_settings_form_alter()](http://api.drupal.org/api/drupal/core!modules!field_ui!field_ui.api.php/function/hook_field_formatter_settings_form_alter/8)
Change record: [Introduced hooks to extend field formatters and widgets with third-party settings](https://www.drupal.org/node/2130757)
- [x] #1379 | [date_popup_authored](https://www.drupal.org/project/date_popup_authored)
- [x] #2568 | Add support for "trusted_host_patterns" | https://www.drupal.org/node/1992030 / https://www.drupal.org/node/2410395
- [x] #2922 | [DX] Views: Add a "[hidden]" label to fields when excluded from display
- [x] #3594 | Expand image tokens to allow image styles (imagecache_token functionality)
- [x] #3755 | [D8] Add ability to create configurable layout templates
- [x] #3764 | [UX] Enable autocomplete on all link/path fields | https://www.drupal.org/node/2418017 / https://www.drupal.org/node/2407913 / Change record: [Menu link UI now an autocomplete, with optional manual path entry](https://www.drupal.org/node/2424003)
- [x] #4372 | [adminrole](https://www.drupal.org/project/adminrole) (??) / https://www.drupal.org/node/1153072 / https://www.drupal.org/node/787152 / https://www.drupal.org/node/2435075
Change record: [Admin roles are stored on the roles itself](https://www.drupal.org/node/2444095)
- [x] [responsive_table](https://www.drupal.org/project/responsive_table)
- [x] [uuid](https://www.drupal.org/project/uuid)
- [x] #3627 | `theme_table()` should take an optional footer variable and produce `<tfoot>`: https://www.drupal.org/project/drupal/issues/806982
- [x] #1383

**Not planned/needed in Backdrop**:
- ~~#1716 / #1413 | https://www.drupal.org/project/big_pipe~~
- ~~https://www.drupal.org/project/breakpoints~~
- ~~https://www.drupal.org/project/composer_manager~~
- ~~https://www.drupal.org/project/composer_vendor~~
- ~~https://www.drupal.org/project/entity_translation~~
- ~~https://www.drupal.org/project/escape_admin~~
- ~~https://www.drupal.org/project/imagecache~~ (already in D7 core)
- ~~https://www.drupal.org/project/joyride~~
- ~~https://www.drupal.org/project/migrate~~
- ~~https://www.drupal.org/project/migrate_d2d~~
- ~~https://www.drupal.org/project/phone~~
- ~~https://www.drupal.org/project/picture~~
- ~~https://www.drupal.org/project/pred8~~
- ~~https://www.drupal.org/project/quickedit~~
- ~~https://www.drupal.org/project/restws~~
- ~~http://github.com/Gizra/restful~~
- ~~https://www.drupal.org/project/title~~
- ~~https://www.drupal.org/project/entity_modified~~
- ~~https://www.drupal.org/project/render_cache~~

**Removed from d8 core**:
- ~~https://www.drupal.org/node/2116417~~ refer to https://backdropcms.org/node/28

**Comment by klonos** [comment]
...ticked another module off the list (date) :wink:

**Comment by klonos** [comment]
Updated the issue summary:

- some minor typos ("Layotus" instead of "Layouts")
- list projects alphabetically
- added http://www.drupal.org/project/entityreference / #1301

Th "Removed from D8 core" section points to refer to https://backdropcms.org/node/28 but that page does not exist. Does anybody know where it's gone or what we intended to point to?

**Comment by klonos** [comment]
...adding https://www.drupal.org/project/phone as well.

**Comment by klonos** [comment]
...added https://www.drupal.org/project/entity

**Comment by mikemccaffrey** [comment]
@klonos Shouldn't we not need the entity project, since @quicksketch integrated the Entity API functionality into core in #49?

**Comment by klonos** [comment]
I couldn't possibly answer that question. It's my understanding that with #49 only a subset of the module was merged into core. I don't know what was left out or why or whether there's more to be done in order to be in par with D8. I believe that @quicksketch is the right person to answer that.

I simply added the module to the list is because I saw the "This module has been included with Drupal 8 core." section on the project page in d.org. I then checked our list here and saw no mention of it. So I added it. If it is deemed that we need not do anything else, then I'll just close #1371 as a duplicate of #49 and I'll update the list in the issue summary accordingly.

**Comment by klonos** [comment]
Updated the list from the [Drupal Contrib Tracker](https://www.drupal.org/project/contrib_tracker) and filed respective issues (or linked to already existing ones).

**Comment by mikemccaffrey** [comment]
Hey @klonos, thanks for creating all of those tickets for modules that have been moved into Drupal 8 core! We definitely should go through them and see what we can move into backdrop core.

However, the whole concept of Drupal 8 parity is perhaps something that we should not be heavily pursuing, since we are actually trying to differentiate ourselves from the drupal community, and one of our core tenets is that we are trying to keep things simple by only including features in core that will be used by a majority of sites.

Having looked at all of these modules, do you have recommendations about which are the most important to move into core, and which modules we might want to mark off as being kept in contrib?

**Comment by docwilmot** [comment]
> the whole concept of Drupal 8 parity is perhaps something that we should not be heavily pursuing

:+1: 

I maintain the aim should be "user experience parity" with Wordpress. :smile:

**Comment by docwilmot** [comment]
P.s. I like "Save Draft", and "Menu Block". All the rest, not so much for core.

**Comment by klonos** [comment]
Yeah, I hear you both. I believe that this issue here was never meant as a todo list rather than a list of things to consider. The parity thing is in order for D7 undecided people to not have many excuses to not move to backdrop. We should aim to be a Drupal 8 alternative - not a copy with different code base. Perhaps the title change communicates the intention a bit better.

Talking about Wordpress...

**Comment by klonos** [comment]
I haven't been visiting d.org for a while and they seem to have launched their new site design (based on D8 I guess). Has anyone noticed that they use Backdrop for their "Who Uses Drupal?" site showcase? Amazing!

**Comment by klonos** [comment]
There's a list of modules that are planed for inclusion in D8.1 and are currently in *experimental* status but shipped with core nevertheless. I made a separate list in the issue summary and I'll file separate issues for each one shortly.

**Comment by klonos** [comment]
...not sure about the whole family of migrate* modules. We have https://www.drupal.org/project/migrate
and https://www.drupal.org/project/migrate_d2d listed in the "not planned/needed" section, but I don't recall any issue or discussion about this.

**Comment by jenlampton** [comment]
> ...not sure about the whole family of migrate* modules. We have [some] listed in the "not planned/needed" section, but I don't recall any issue or discussion about this.

We don't need migrate in core because we already have a supported upgrade path in core via update.php. Our target audience are sites that are less likely to use migrate and more likely to use update.php. Whereas the enterprise are more likely to throw out an existing site and start over, migrating in their previous content.  Migrate should exist for Backdrop but in contrib.

**Comment by olafgrabienski** [comment]
Added two Views related features: #2921 and #2922.

**Comment by klonos** [comment]
I have updated the issue summary, and have added #2498

**Comment by klonos** [comment]
I believe that given that we have the [Feature parity with Drupal](https://github.com/backdrop/backdrop-issues/projects/8) GitHub project to help us track issues + also the various `[Dx]` keywords that we are using in the titles of the issues, perhaps we should close this issue here.

I'll leave it open for a while longer, but will close it next time I am brought here unless there are objections to that.
