### ISSUE TITLE
Backdrop 1.13.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3785]
Scheduled for May 15, 3:30pm - 5:30pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Move all unfinished issues to the next minor release milestone @jenlampton 
- [x] Create a new minor release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)
- [x] Draft roadmap updates for backdropcms.org @klonos 
- [x] Draft blog post @jenlampton 
- [x] Draft tweet announcing the release of 1.13.0

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch
- [x] Revert version number back on 1.x branch with minor number increased @quicksketch
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch
- [x] Create release notes on GitHub @jenlampton 
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @klonos
- [x] Tweet that a new release is out @jenlampton 

## Post-release tasks

- [x] Push the minor release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch
- [x] Push the minor release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch 
- [x] Push the minor release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) @jenlampton 
- [x] Push the minor release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @drupol 
- [x] Publish blog post @jenlampton 
- [x] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [x] Publish roadmap updates for backdropcms.org @klonos
- [ ] Send a newsletter via MailChimp @facetinteractive 
- [x] Update the Wikipedia articles @klonos @stpaultim @docwilmot @herbdool 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

~~See the Accompanying Bug-Fix Release Checklist: https://github.com/backdrop/backdrop-issues/issues/3786~~

See a recent Bug-Fix Release Checklist: https://github.com/backdrop/backdrop-issues/issues/3838

**Comment by jenlampton** [comment]
Does this look right for the changelog?

**Changes since 1.12.7**

* Backdrop 1.13.0 preview.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3742">#3742</a>: Add field_formatter_settings to backdrop_merged_modules().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/495">#495</a>: Add a useful dashboard to Backdrop core.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1777">#1777</a>: Add more link attributes in the Rich-Text editor.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1376">#1376</a>: Merge field formatter settings into core.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3011">#3011</a>: Added entity_access and Entity::createAccess() and Entity::access() for all Entities.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3455">#3455</a>: Translated config for site_name, site_slogan, maintenance message, user mail messages.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3657">#3657</a>: Add vertical tabs to the taxonomy term edit form.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3655">#3655</a>: Add the number of terms to the vocabulary overview form.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3453">#3453</a>: Enable manual core updates by default on all new sites.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/574">#574</a>: Change default setting for who can register accounts to Admin-only.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2595">#2595</a>: JavaScript double-click protection on form submit buttons.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3690">#3690</a>: [DX] Add ->fieldGetValue() method to match field_get_value().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/461">#461</a>: Add field_get_value() and matching method.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3673">#3673</a>: Improve documentation of settings.local.php in settings.php.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3581">#3581</a>: Adds a reset button to admin/modules filter.
* SA-CORE-2019-008: jQuery extend backport.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3628">#3628</a>: Warning: uasort() expects parameter 1 to be array, null given in node_view_multiple().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2690">#2690</a>: Fix views contextual links on page displays by treating the same as block displays.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2673">#2673</a>: Menu settings of custom layouts not cloned properly.
* Issue 2497: Make comment, path, redirect operations drop-downs consistent.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3075">#3075</a>: [UX] Provide a hint that classes can be added to the inner wrapper of a region.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3249">#3249</a>: Help Views Wizard connect to vocabulary correctly.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3316">#3316</a>: [UX] Add human name to fields list at admin/reports/fields.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3345">#3345</a>: [UX] Layouts: render the "Configure" link only if the block is not broken.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3378">#3378</a>: [UX] Default text formats are not saved properly without accompanying values.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3485">#3485</a>: Add options_element in backdrop_merged_modules().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3502">#3502</a>: [UX] Add hover color to error rows.
* Issue 3533: Add confirmation form for disabling themes.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3613">#3613</a>: Add 'type = profile' in .info files.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3573">#3573</a>: Fix draggable nested items in RTL being dragged in the opposite direction.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3592">#3592</a>: Change the weight field in the taxonomy term form to a number field.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3593">#3593</a>: [UX] Views: Change the "Weight" field to for the page menu/tab to a number field.
* Issue 3622: Fix non-numeric warning in Options Element.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3623">#3623</a>: [DX] Remove the hard-coded parentheses from fieldset summaries.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3649">#3649</a>: Color module: Call to undefined function admin_bar_suppress().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3505">#3505</a>: [UX] Move the translation settings for content types to its own tab.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3519">#3519</a>: Fix image link class being removed when using image caption.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3542">#3542</a>: [UX] Views: use "configuration changes" instead of "automatic updates" in messages.
* Revert unnecessary error suppression from SA-CORE-2019-008.
* SA-CORE-2019-007: Disallow invalid file names.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3543">#3543</a>: [UX] Fix RTL password field style.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3554">#3554</a>: [UX] Basis: Fix RTL breadcrumb style.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3558">#3558</a>: [DX] Consolidate theme_debug warning.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3575">#3575</a>: Fix docblock in page.tpl.php
* Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/2532">#2532</a> from quicksketch/sa-core-2019-004
* By B-Prod, dawehner, DamienMcKenna, Lendude: Improved argument validation.
* By heddn, klausi, greggles, azinck, dawehner, DamienMcKenna, vijaycs85: Improved handling of exposed field filters.
* By rstamm, damiankloip, dawehner, dsnopek, quicksketch: Improved output of serialized fields.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3557">#3557</a>: [PHP 7.3] strpos explicit string needle warnings.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3557">#3557</a>: Crossport Drupal issue <a href="https://github.com/backdrop/backdrop-issues/issues/3023066">#3023066</a>: [PHP 7.3] Fix BootstrapMiscTestCase::testCheckMemoryLimit() notice.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3557">#3557</a>: Crossport Drupal issue <a href="https://github.com/backdrop/backdrop-issues/issues/1430934">#1430934</a>: Notice: Undefined index: display_field in file_field_widget_value().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3464">#3464</a>: Allow existing content block to use translations.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3470">#3470</a>: Fix PHP Deprecated Warning with Link module.
* SA-CORE-2019-003: Ensure link values are as expected when validating.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3512">#3512</a>: Test that array index '#type' is set in form_process_actions().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2999">#2999</a>: Date format links should read Configure.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3516">#3516</a>: Make the 'Formatting options' link less distracting.
* Issue 1294: Exclude .tests.info when using updater.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3424">#3424</a>: [UX] Fix RTL vertical tabs style.
* Revert "Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3364">#3364</a>: Backdrop Install.php shows "Backdrop already installed" when database credentials are incorrect."
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3371">#3371</a>: Show "You do not have any admin items" message in '/admin/config'.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1909">#1909</a>: Remove exposed sort and summary options for Random sort order in Views.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3423">#3423</a>: [UX] Fix RTL width of the add content page.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3431">#3431</a>: Fix RTL formatting options in Seven.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3523">#3523</a>: [UX] Fix RTL table headers.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3525">#3525</a>: [UX] Fix RTL options element.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3478">#3478</a>: Improve theme config handling.
* Issue 3494: Set the deprecrated table option for all Views with grids.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3257">#3257</a>: Adding since docblock for color_get_color_element().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3257">#3257</a>: Allowing color elements to be put in multiple fieldsets.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1579">#1579</a>: Use saveXML() instead of saveHTML() when saving image captions.
*  Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3364">#3364</a>: Backdrop Install.php shows "Backdrop already installed" when database credentials are incorrect.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3466">#3466</a>: ETags should be quoted.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3481">#3481</a>: CKEditor: Select image library is disabled.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3493">#3493</a>: Prevent PHP warnings when classes are givein for views list, and views list wrapper.
* Issue 3487: Fix taxonomy update hook message.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3488">#3488</a>: backdrop_http_request() should remove host during redirects. Fixes update and install of projects.
* Cross-ports from Drupal 7.62
* Merge branch 'security-54-002' into security-54
* SA-CORE-2019-002: Disable web-based phar stream wrapper.
* SA-CORE-2019-001: Update Archive_Tar library.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3425">#3425</a>: Seven: fix disabled buttons style.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3386">#3386</a> : Thumbnails not showing in the library view when using a custom files directory.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2960">#2960</a>: Add drop-buttons for exports everywhere. Config must check query string for group and name.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3461">#3461</a>: Suppress OPcache PHP warnings for PHP 7.2+.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3459">#3459</a>: file_unmanaged_move() should issue rename() where possible instead of copy() & unlink().

**Comment by jenlampton** [comment]
Tweet announcement will read:

`Hello there version 1.13 of #BackdropCMS, my what a nice #dashboard you have.`

**Comment by klonos** [comment]
Roadmap page and home page download links updated 👍

**Comment by jenlampton** [comment]
Blog post is up: https://backdropcms.org/news/backdrop-113-released (finally)

**Comment by klonos** [comment]
Docker image PR has also been merged :wink:: https://github.com/docker-library/official-images/pull/6006

**Comment by jenlampton** [comment]
Newsletter draft is getting reviewed: https://docs.google.com/document/d/1ql-bn5YM4Cjwj4Ql9EkEAgyGoqBFWJcUwCM_l0ruRi0/edit?ts=5cf6e68f#

**Comment by klonos** [comment]
Let's close this one :)
