### ISSUE TITLE
Backdrop 1.12.7 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3786]
Scheduled for May 15, 2:30pm - 4:30pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create a new bugfix release @herbdool
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @herbdool 
- [x] Tag for release, and push tag to GitHub @herbdool 
- [x] Revert version number back @herbdool 
- [x] Create release notes on GitHub @jenlampton 

See the Accompanying Minor Release Checklist https://github.com/backdrop/backdrop-issues/issues/3785

**Comment by jenlampton** [comment]
Release notes:



**Changes since 1.12.6**

* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3628">#3628</a>: Fixed: Warning: uasort() expects parameter 1 to be array, null given in node_view_multiple().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2690">#2690</a>: Fixed: Views contextual links on page displays by treating the same as block displays.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2673">#2673</a>: Fixed: Menu settings of custom layouts not cloned properly.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2497">#2497</a>: Make comment, path, redirect operations drop-downs consistent.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3075">#3075</a>: Provide a hint that classes can be added to the inner wrapper of a region.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3249">#3249</a>: Help Views Wizard connect to vocabulary correctly.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3316">#3316</a>: Add human name to fields list at admin/reports/fields.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3345">#3345</a>: Layouts: render the "Configure" link only if the block is not broken.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3378">#3378</a>: Fixed: Default text formats are not saved properly without accompanying values.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3485">#3485</a>: Add options_element in backdrop_merged_modules().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3533">#3533</a>: Add confirmation form for disabling themes.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3613">#3613</a>: Add 'type = profile' in .info files.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3573">#3573</a>: Fixed: draggable nested items in RTL being dragged in the opposite direction.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3592">#3592</a>: Change the weight field in the taxonomy term form to a number field.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3593">#3593</a>: Views: Change the "Weight" field to for the page menu/tab to a number field.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3622">#3622</a>: Fixed: non-numeric warning in Options Element.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3623">#3623</a>: Remove the hard-coded parentheses from fieldset summaries.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3649">#3649</a>: Fixed: Call to undefined function admin_bar_suppress() in color module.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3519">#3519</a>: Fixed: image link class removed when using image caption.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3542">#3542</a>: Change the text "automatic updates" to "configuration changes" in views messages.
