### ISSUE TITLE
[META] VBO: Feature parity with 7.x

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3797]
Here's the options we provide when configuring VBO (same as D8 core Views, so, we have feature parity):

![Screen Shot 2019-05-20 at 8 35 47 am](https://user-images.githubusercontent.com/2423362/57989167-4cb68500-7ada-11e9-9dfb-361742df7ef9.png)

Here's what VBO 7.x provides:

![Screen Shot 2019-05-20 at 8 28 08 am](https://user-images.githubusercontent.com/2423362/57989237-26451980-7adb-11e9-925f-1bf8a9be8298.png)

Features/options missing:

- [ ] #802 | Option to have either a) a dropdown menu + a submit button b) separate buttons of each operation
- [ ] #3798 | Select all items on all pages
- [ ] Make the whole row clickable
- [ ] Force selecting a single item from the list
- [ ] Number of entities to load at once
- [ ] Skip batching

![Screen Shot 2019-05-20 at 8 47 31 am](https://user-images.githubusercontent.com/2423362/57989294-006c4480-7adc-11e9-8502-4909d1c0d969.png)

- [ ] #802 | Option to override operation labels
- [ ] Options for each operation to skip confirmation/permission
- [ ] Option to enqueue operations
- [ ] #2297 | Allow bulk enabling/disabling comments on existing content.
- [ ] #4401 | Allow bulk operations for updating entity values (including taxonomy terms - [see comment](https://github.com/backdrop/backdrop-issues/issues/3797#issuecomment-493886717))
- [ ] Action to change content author

**Comment by olafgrabienski** [comment]
In comparison to VBO 7.x, there's also one bulk operation missing in D8 and Backdrop: "Modify entity values". As a site builder without coding skills, I find it *very* useful.

For D8 there are contrib modules like [Bulk update fields](https://www.drupal.org/project/bulk_update_fields) and [Views Bulk Edit](https://www.drupal.org/project/views_bulk_edit) to help out. I suggest to include the missing "Modify entity values" operation to Backdrop core.

**Comment by olafgrabienski** [comment]
Below a screenshot to show the "Modify entity values" setting from VBO 7.x:

![screen-d7-vbo-modify-entity-values](https://user-images.githubusercontent.com/14188307/58009354-8b563a80-7aee-11e9-95d3-fac02a0eb58e.png)

**Comment by klonos** [comment]
Thanks @olafgrabienski 👍 ...I've added that to the task list in the issue summary.

**Comment by jenlampton** [comment]
I've started work on a contrib `modify_field_values` module to add this one operation for a client site. (Let me know if you think I should call this `views_bulk_operations` instead, and extend it for all the missing operations.)

The action API in Backdrop core is not the same as it was in VBO, so it won't be simple to add most these more complex actions. 

VBO extended the API to allow for a form as the secondary step of the action, submit handlers, access callbacks, etc. Instead, Backdrop core leverages an existing page callback that already has the form (for things like node delete and user delete) and shoves necessary information for that form into the `$_SESSION`.

Additionally, VBO leveraged the trigger system to execute the action. Backdrop core has no trigger system (that was removed from core) and instead executes the action on demand.

Blarg, fingers crossed this works!

**Comment by olafgrabienski** [comment]
> I've started work on a contrib `modify_field_values` module to add this one operation for a client site. 

That's great, I'm looking forward to test it!

> (Let me know if you think I should call this views_bulk_operations instead, and extend it for all the missing operations.)

Not sure, I'll leave the answer to @klonos or others!

**Comment by klonos** [comment]
>(Let me know if you think I should call this views_bulk_operations instead, and extend it for all the missing operations.)

Sounds like a great idea to me @jenlampton 👍 ...that way, people installing that contrib would get the functionality we left out when we implemented VBO "light" in core.

...we are pretty much doing the same with other contrib, such as Save Draft. Once some of their features are added to core, they are removed from the contrib module, then a new release of that module is created by the maintainer, and this new release also includes a `dependencies[] = system (>=1.x.0)` line in its .info file (where `x` is the minor version of core that includes the feature(s) previously included in the contrib module). This prevents installing the new version of the module on an older version of core (that does not include the features).

...I would personally make a release with `dependencies[] = system (<1.[new-core-minor].0)` first, then remove the added-to-core features, then create another release with `dependencies[] = system (>=1.[new-core-minor].0)` 😉

**Comment by jenlampton** [comment]
A quick update here: my one-hour task turned into a five-hour task yesterday, so I ended up just hard-coding the entity type (node) and field (taxonomy_term_1) that my client needed to be able to change. 

The good news is that that's working, so if anyone else needs to do the same in a pickle, they can: https://github.com/jenlampton/modify_feild_values/tree/master

The bad news is that this isn't yet a comparable alternative to VBO for Drupal 7.

**Comment by klonos** [comment]
Thanks @jenlampton 👍 multiple typos in the README indicate that you must be tired after this task 🙂 ...if you moved it to contrib, I'd help with that.

**Comment by jenlampton** [comment]
It's not suitable for contrib since it only works for one field, and that's
hard-coded.

**Comment by freeform-sg** [comment]
@jenlampton thank you so much for this! Came in very useful :)

**Comment by Wylbur** [comment]
Another item that should be added to the list - "Change author of content" or "Change Owner".

This is a great admin action!

**Comment by klonos** [comment]
I've added that to the list in the issue summary @Wylbur

**Comment by olafgrabienski** [comment]
@klonos and others interested - In the meantime @argiepiano has ported Views Bulk Operations contrib module to Backdrop, see [this comment in github.com/backdrop/backdrop-issues/issues/3646](https://github.com/backdrop/backdrop-issues/issues/3646#issuecomment-1120498234) for details. I'm tending to close this issue and mark it as `contrib candidate`. What do you think about it?
