### ISSUE TITLE
Backdrop 1.13.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3812]
## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create a new bugfix release @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub @jenlampton 
- [x] Update the front page download link on b.org @klonos 
- [x] Tweet that a new release is out @jenlampton 

## Post-release tasks

- [ ] Push the bug-fix release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) @jenlampton 
- [ ] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch 
- [x] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch 
- [ ] Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @drupol
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by jenlampton** [comment]
Release notes draft:

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

Update information:

* **The database update script does need to be run.**
* No changes have been made to the `.htaccess`, robots.txt or default settings.php files in this release, so upgrading custom versions of those files is not necessary.

**Changes since 1.13.0**

* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3728">#3728</a>: Replace deprecated format_username() in comment.test with user_format_name().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3658">#3658</a>: Replace all instances of 'theming' with a more specific and accurate word.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2536">#2536</a>: Fix display of submitted info for node in block.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3716">#3716</a>: Add views_clean_css_identifier() as a Backwards-Compatible wrapper function.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3809">#3809</a>: Revert the static definition added to entityType().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3753">#3753</a>: Provide a dedicated date format for logging.

**Comment by laryn** [comment]
NOTE: the database update script does need to be run due to https://github.com/backdrop/backdrop/commit/59d2d169b258bd4a914f0821eca18aa2e73642c0

**Comment by jenlampton** [comment]
> Update: I read that wrong.

I was thinking I would bold it when it DOES need to be run, and not bold it when it doesn't. I agree the difference is hard to determine :)

**Comment by jenlampton** [comment]
closing in favor of https://github.com/backdrop/backdrop-issues/issues/3838
