### ISSUE TITLE
crossport Views commits from 7.x-3.22 - 7.x-3.23

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3853]
Has separate issues/PRs:
- [x] #4075 | [e19e3546](http://git.drupalcode.org/project/views/commit/e19e354618badf48640dfd46db696e21eb7c26f1) | [Issue #2900405 by collinhaines, jenlampton, sano, paulbeaney, jyraya: Undefined index in views_handler_filter->store_exposed_input().](http://drupal.org/node/2900405)
- [x] #4075 | [ddaeddc3](http://git.drupalcode.org/project/views/commit/ddaeddc3b3243e9672bf3331a4e6f7d7d5f33f21) | [Issue #2481401 by daemonchrist, MXT, sirnjeet, blasthaus, retiredpro, Kingdutch, flocondetoile, emmonsaz, sch2, chegor, m4olivei, bdupls, Berliner-dupe, broeker, jamesrward, cwells, pmoz, ckoharj, pedronau: Undefined property: view::$exposed_input in views_plugin_display_attachment](http://drupal.org/node/2481401)
- [x] #4323 | [8b6ccb08](http://git.drupalcode.org/project/views/commit/8b6ccb08b1fdddca26c2ac6d3b0c6c3929ca41ae) | [Issue #2810431 by MustangGB, Anybody, brad.bulger, NWOM: Parameter 3 to views_ui_build_form_state() expected to be a reference, value given in views_ui_ajax_form().](http://drupal.org/node/2810431)
- [x] N/A - handled in #3614 | [9aaf2f8d](http://git.drupalcode.org/project/views/commit/9aaf2f8d1557438023ecdadad0f9f41d43d6f641) | [Issue #3040391 by FeyP, Joseph Zhao, jefftrnr, joelpittet, jzasnake, ChaseOnTheWeb, DamienMcKenna, kristofferwiklund, pvdpdrop, skylord: 3.21 Regression, malformed SQL: 'Is none of' within grouped exposed filter.](http://drupal.org/node/3040391) 
- [ ] https://github.com/backdrop/backdrop/pull/5085 | [88cbaab7](http://git.drupalcode.org/project/views/commit/88cbaab793f0ca397b418f15fcb870cbd805065c) | [Issue #2885660 by StefanPr, Plazik, steinmb, joelpittet, Manuel Garcia, natanmoraes, thebigmacmurray, nikolabintev, dsnopek: Warning: A non-numeric value encountered in views_plugin_pager_full->query().](http://drupal.org/node/2885660)

No issues/PRs yet:
- [ ] #xx | [0a269672](http://git.drupalcode.org/project/views/commit/0a2696728b23217bc19287e82b291c34266d4ba2) | [Issue #1609088 by JvE, johnv, rpayanm, matthias_mo, klausi, jasom, hillmore, boabjohn: Undefined index: uid in views_handler_field->get_value() (line 375 of views_handler_field.inc)](http://drupal.org/node/1609088)
- [ ] #xx | [985412f2](http://git.drupalcode.org/project/views/commit/985412f2720b963a05d0dd94a1ee2aa154b1b933) | [Issue #2939559 by loopduplicate, volkswagenchick: Add hook_admin_menu_cache_info() implementation.](http://drupal.org/node/2939559)
- [ ] #xx | [6ac35382](http://git.drupalcode.org/project/views/commit/6ac3538254bdcd88be6f794e707464857d9f826e) | [Issue #2916772 by rpayanm, MustangGB: Admin modal is not compatible with jQuery3.](http://drupal.org/node/2916772)
- [ ] #xx | [bed9de56](http://git.drupalcode.org/project/views/commit/bed9de5663e1e5efb1909b07b9799851cdc58d80) | [Issue #2823977 by RoSk0, ridoo, joelpittet, robertwb, poorva, iryston, TwoD, Kris77, onehandsomedog, joe_carvajal: Ajax http 500 error using taxonomy to filter view.](http://drupal.org/node/2823977)
- [ ] #xx | [af9e128d](http://git.drupalcode.org/project/views/commit/af9e128d848d87b967b39b70cc57abe1e8dafe79) | [Issue #2977851 by Jorrit, dsnopek: PHP 7.2: count() on non-Countable in views_many_to_one_helper.](http://drupal.org/node/2977851)
- [ ] #xx | [3f1efccd](http://git.drupalcode.org/project/views/commit/3f1efccdeed64ad339ea7e2e34968fa7ada5da7b) | [Issue #1886554 by Fabianx, johnv, dawehner, Arnaud Meunier: :db_condition_placeholder leads to cache misses and superfluous cache_set.](http://drupal.org/node/1886554)
- [ ] #xx | [5c262a65](http://git.drupalcode.org/project/views/commit/5c262a659a38a37b9df7357bcef9e0f0bf79f1b2) | [Issue #1744478 by schiavone, skwashd: Grid format disregards "number of columns" option for a single line of results.](http://drupal.org/node/1744478)
- [ ] #xx | [04f4fce7](http://git.drupalcode.org/project/views/commit/04f4fce709c9a774c9bef589a45e2d662e1820ee) | [Issue #2483055 by ron_s, joelpittet: Empty "contains" operator causes Views to return limited results when added on Entityforms.](http://drupal.org/node/2483055)
- [ ] #xx | [bdb04c76](http://git.drupalcode.org/project/views/commit/bdb04c76c1696ae825a8d5dbbf57f28b69994af7) | [Issue #2226015 by jweowu, yang_yi_cn, RoSk0: UI text for disable_sql_rewrite option is misleading.](http://drupal.org/node/2226015)
- [ ] #xx | [36ce831a](http://git.drupalcode.org/project/views/commit/36ce831aed12274b9d36d254d9d1f52d237e8a81) | [Issue #2331209 by nico.knaepen, alberto56, DigitalFrontiersMedia, deepakrmklm, alancooney, webservant316, operawong: Notice: Undefined index: flagging in views_handler_field_field->access() (line 127 of modules/field/views_handler_field_field.inc)](http://drupal.org/node/2331209)
- [ ] #xx | [baa13a5a](http://git.drupalcode.org/project/views/commit/baa13a5a42f2917097ece7f3b53313e748c2e7a9) | [Issue #2793085 by longwave, Rob230, joelpittet: 'remember_roles' option stores unnecessary data.](http://drupal.org/node/2793085)
- [ ] #xx | [d0e5ea78](http://git.drupalcode.org/project/views/commit/d0e5ea784bfc2ea0b8e126f3f1b2db9cc430fd5e) | [Issue #2115213 by fgm, merlinofchaos: Incorrect $view parameter passed to hook_views_handler_options_alter().](http://drupal.org/node/2115213)
- [ ] #xx | [5ed41782](http://git.drupalcode.org/project/views/commit/5ed41782216a9008959695584e34b5e3368bd18a) | [Issue #1818176 by deetergp, xlin, OnkelTem, ikeigenwijs, mikeker, othermachines, gcb, Chris Charlton, fehin, gthing: Error when configuring exposed group filter: "The value is required if title for this item is defined."](http://drupal.org/node/1818176)
- [ ] #xx | [fb1c470c](http://git.drupalcode.org/project/views/commit/fb1c470cf4a3fb825826b96209e05b15b659a9ea) | [Issue #2869022 by Jorrit, Chris2: Disable query rewriting notice not displayed correctly.](http://drupal.org/node/2869022)
- [ ] #xx | [776e8ccc](http://git.drupalcode.org/project/views/commit/776e8ccc90c56b866e17d5d39a250a1bbde94328) | [Issue #3003008 by Ishani.addweb, Aanal.addweb, RenatoG: Typo in the documentation.](http://drupal.org/node/3003008)
- [ ] #xx | [5c44b7f1](http://git.drupalcode.org/project/views/commit/5c44b7f100dd2fd4a6bce3d86a55980a20e0db98) | [Issue #3016530 by jweowu, MustangGB: Relocate calls to func_get_args() to beginnings of functions.](http://drupal.org/node/3016530)
- [ ] #xx | [a19d7d80](http://git.drupalcode.org/project/views/commit/a19d7d8027209229cae9cd2b7a28911c629b9ecc) | [Issue #1695658 by Chi, aloyr, Simon Georges, jzavrl, DamienMcKenna, Ante890, semiaddict, jespermb, millerrs, glynster, philipz, dawehner, -Mania-, rositis@gmail.com, Lang Wu Jane, nimek, travisc, dmitryl, coconnor: Support optgroups for taxonomy selection list.](http://drupal.org/node/1695658)
- [ ] #xx | [2ae973e9](http://git.drupalcode.org/project/views/commit/2ae973e9220cd82473684c18a2968c76adca0862) | [Issue #3016530 by jweowu: Follow-up to restore views_ui too.](http://drupal.org/node/3016530)
- [ ] #xx | [1d871c1e](http://git.drupalcode.org/project/views/commit/1d871c1e855763dbd683c5ceaf603bb1ee505ec2) | [Issue #1843778 by joelpittet, mgifford, cs_shadow, steveoliver, dawehner, Chris2, colan, jpamental, mbrett5062, catch, DamienMcKenna: Remove views/views_ui/theme/views-ui-edit-view.tpl.php.](http://drupal.org/node/1843778)
- [ ] #xx | [990dc3fd](http://git.drupalcode.org/project/views/commit/990dc3fdbde727a9d4ca2819cf157181e19e2e55) | [Issue #2832381 by vagelis-prokopiou, Chris2, darrenwh: "Javascript" should be "JavaScript".](http://drupal.org/node/2832381)
- [ ] #xx | [eb137d73](http://git.drupalcode.org/project/views/commit/eb137d7374d3e862763dcfb834a4855012a13a63) | [Issue #2530302 by jproctor, snehal.addweb, Chris2: Spurious apostrophes in code comments.](http://drupal.org/node/2530302)
- [ ] #xx | [a8a41a26](http://git.drupalcode.org/project/views/commit/a8a41a26775fbd2ff07be81896f702d3f9b65b86) | [Issue #1602658 by Reg, hargobind, andrefy, raincloud, damiankloip, xurizaemon, fiftyz, Chris2, attheshow, yang_yi_cn, FerCamp, annya, dolu, heddn, eileenmcnaughton: Add negative regular expression filter.](http://drupal.org/node/1602658)
- [ ] #xx | [66d1c17e](http://git.drupalcode.org/project/views/commit/66d1c17e06d52edb292bd6340eb8a003db6b6ec4) | [Issue #1944150 by esmerel, joelpittet, Chris2, dawehner, BrockBoland: Combine fields filter includes a duplicate condition in if() statement.](http://drupal.org/node/1944150)
- [ ] #xx | [6713f914](http://git.drupalcode.org/project/views/commit/6713f914ebd0ace9186e311e029306f6229a2fd7) | [Issue #1777580 by StoraH, Valentine94, dawehner, aspilicious, Chris2: Clearer theme suggestion lists.](http://drupal.org/node/1777580)
- [ ] #xx | [7d8bb19e](http://git.drupalcode.org/project/views/commit/7d8bb19e7a81b46f88cb0835ab921a93e8029dc8) | [Issue #2219937 by jenlampton, Chris2: Add comment ID as argument / filter / field.](http://drupal.org/node/2219937)
- [ ] #xx | [4d20269f](http://git.drupalcode.org/project/views/commit/4d20269fa356946bb366ae9599e7451de8ecd162) | [Issue #1773966 by Scott Robertson, WorldFallz, parisek, joshmiller, nicoz, mstrelan, Jason Dean, albie001, Alan D., JurriaanRoelofs, Kimberley_p, sergeypavlenko: User: Comments authored relationship.](http://drupal.org/node/1773966)
- [ ] #xx | [25e311f6](http://git.drupalcode.org/project/views/commit/25e311f6f4570705f3442a425264005d37662076) | [Issue #3032213 by joelpittet, crutch, rclemings: When admin theme is not a modal window, .ctools-twisty .ctools-text arrow stretched for view, clone, delete, disable button.](http://drupal.org/node/3032213)
- [ ] #xx | [ad3cb726](http://git.drupalcode.org/project/views/commit/ad3cb72610533af86385f7b299bc94508a1f2ff7) | [Issue #1635912 by wolffereast, tatyana, neRok, silinor, cesarmiquel, jordiserra, Chris Matthews: A view with ajax pager does not load the first page results when you are visiting a subsequent page directly.](http://drupal.org/node/1635912)
- [ ] #xx | [5eaddbf5](http://git.drupalcode.org/project/views/commit/5eaddbf5287f6eb23de5a85a181c2f16726956c8) | [Issue #3033015 by geoffray, Neslee Canil Pinto: Minor typo in table settings.](http://drupal.org/node/3033015)
- [ ] #xx | [6a547c32](http://git.drupalcode.org/project/views/commit/6a547c32d9852129dbf3f4e097f709737cca44eb) | [Issue #3039953 by joelpittet, dromansab, awasson, joseph.olstad, darkodev, TheWrench: PHP 5.3.x fix for syntax changes Views 3.21.](http://drupal.org/node/3039953)
- [ ] #xx | [58bb2688](http://git.drupalcode.org/project/views/commit/58bb2688211421088a2d85f0fb5df06878d30833) | [Issue #2985178 by nagy.balint, Siavash, maticb, chrisgross, jonnyeom: Views 3.18 > 3.20 update problem with duplicate/group_by.](http://drupal.org/node/2985178)
- [ ] #xx | [62607944](http://git.drupalcode.org/project/views/commit/626079447d396de00b0be54c313c0b4d380fe534) | [Issue #2564205 by berdyshev, maximpodorov, temkin: Decode html entities for views_ajax calls](http://drupal.org/node/2564205)
- [ ] #xx | [35bf47c9](http://git.drupalcode.org/project/views/commit/35bf47c9607cd871243a22339a311b1a47ff9ae1) | [Issue #3040497 by FeyP: [Regression] Missing JOIN in attached display with taxonomy filter and inherited exposed filter](http://drupal.org/node/3040497)
- [ ] #xx | [304108e6](http://git.drupalcode.org/project/views/commit/304108e690112d91a92d4ee6d3b0610c925c8fc0) | [Issue #1877238 by MustangGB, willzyx, seanmrafferty, firewaller, geoffreyr, cilefen, joelpittet, mstef, robertom, narkoff, kmoll, glass.dimly: Views caching cannot be combined with Ajax on cached pages.](http://drupal.org/node/1877238)
- [ ] #xx | [4a603f44](http://git.drupalcode.org/project/views/commit/4a603f447037d88dee6b89d1784f23e32e36ad42) | [Issue #1488744 by goldenboy, jibran, a.milkovsky, aquasplash, Tessa Bakker, rongok, lunk rat, scotself, wooody, BrightBold, alex.designworks, MustangGB, kanani, discipolo, Cracu, koechsle, André Ferreira, dawehner, pmcdougl: Grouping level is always zero in views_plugin_style::render_grouping_sets().](http://drupal.org/node/1488744)
- [ ] #xx | [a8f8d295](http://git.drupalcode.org/project/views/commit/a8f8d295df2db4a72c7e758e317de33dec6329b7) | [Issue #2557603 by Krilo_89, DamienMcKenna, charlie_eval, ccjjmartin: PHP Fatal error:  Call to a member function get_option() Line 1327.](http://drupal.org/node/2557603)
- [ ] #xx | [e323fad3](http://git.drupalcode.org/project/views/commit/e323fad342d0276b200e7dba66111448481c120b) | [Issue #2778747 by happysnowmantech, jacob.embree, alan-ps, krina.addweb, NWOM, kingandy, GuyPaddock, hargobind, ultrabob: "Global: Contextual Links" field - "Create a label" option is not saved.](http://drupal.org/node/2778747)
- [ ] #xx | [24a3cab1](http://git.drupalcode.org/project/views/commit/24a3cab16e9c80fd0aaed1d8f0e8c0f4c2a3c8e1) | [Issue #2908350 by DamienMcKenna, donquixote: Link to views_ui from block settings page.](http://drupal.org/node/2908350)
- [ ] #xx | [d2e58612](http://git.drupalcode.org/project/views/commit/d2e586128b51b6955bf5f9af0a7db3288636dca0) | [Issue #873872 by dagmar, damiankloip, dawehner, RickJ, DamienMcKenna, tim.plunkett, catch: Allow to limit which exposed operators apply.](http://drupal.org/node/873872)
- [ ] #xx | [f3ce4242](http://git.drupalcode.org/project/views/commit/f3ce4242c2697bf17b1d8213a93c555e37c5921a) | [Issue #1689472 by minorOffense, DamienMcKenna, Anybody, nmillin, Sneakyvv, darrenwh, adammalone, cybercampbell, RunOfTheMill, dreftymac: Add class to table in table format.](http://drupal.org/node/1689472)
- [ ] #xx | [0561a93a](http://git.drupalcode.org/project/views/commit/0561a93a67e14cbf0ac658e14e36ebd67ff014e3) | [Issue #1776332 by andrewbelcher, Aurangzeb_Alamgir, roderik, Chris Matthews, vitalie, deetergp, zolt_toth, mitsuroseba, presleyd, ikeigenwijs: views_handler_filter_date cannot filter for NULL](http://drupal.org/node/1776332)
- [ ] #xx | [c78d0d22](http://git.drupalcode.org/project/views/commit/c78d0d22c947b73eabfbbf822ef21f5bc607aa4a) | [Issue #2178287 by joachim, natanmoraes, pythagory, lucyp, caminadaf: allow views_handler_field_date to work with SQL datetime format](http://drupal.org/node/2178287)
- [ ] #xx | [408574d8](http://git.drupalcode.org/project/views/commit/408574d890d41a17edddbd7a6dca5240267d7530) | [Issue #2756649 by pbirk, villav74, attheshow, petednz: Numeric Field Handler Converts NULL to Zero](http://drupal.org/node/2756649)
- [ ] #xx | [e6e14574](http://git.drupalcode.org/project/views/commit/e6e14574eb8a29517cd3c0d8a8829a18c54382ab) | [Issue #2871727 by chellman, jozzy_a, DamienMcKenna, mstrelan, BTMash: views_plugin_argument_validate_taxonomy_term has ambiguous column tid](http://drupal.org/node/2871727)
- [ ] #xx | [e10d893f](http://git.drupalcode.org/project/views/commit/e10d893fd7a98547699caebaab0d7c3f80bfb28f) | [Issue #1779658 by hass, mitron, esoteric1, YesCT, disasm, Andrew Answer, irunflower, xjm, dawehner, webchick, catch, Chris Matthews, David_Rothstein: Translatable strings not self-explanatory / not context-independent.](http://drupal.org/node/1779658)
- [ ] #xx | [3b624d18](http://git.drupalcode.org/project/views/commit/3b624d180ef4bb92d7a6a7af540e9f07d44c267e) | [Issue #2200899 by rsmylski, tatarbj, Spleshka, ali_b, System Lord, vinmassaro, gerson.analista: Result summary does not display for empty view when "Display even if view has no result" is checked.](http://drupal.org/node/2200899)
- [ ] #xx | [22abb7a1](http://git.drupalcode.org/project/views/commit/22abb7a1f0ad6648ebbd4042c8d51e374127ca09) | [Issue #1364064 by INAScon, thekevinday, g33kg1rl, dat deaf drupaler: Undefined index: entity type in views_handler_field_entity->init().](http://drupal.org/node/1364064)
- [ ] #xx | [eb5f5439](http://git.drupalcode.org/project/views/commit/eb5f54393d116e48d5ff5e9cadf9179eb5cc69ce) | [Issue #2159967 by mr.york, Nitesh Sethia, nickBumgarner, DamienMcKenna, Chris Matthews: The active URL doesn't always receive the active class.](http://drupal.org/node/2159967)
- [ ] #xx | [4686f239](http://git.drupalcode.org/project/views/commit/4686f23964c3ee4443face759cf63c3f0ab5ebc4) | [Issue #2962142 by smustgrave, LeDucDuBleuet: View for Taxonomy Vocabulary does not have an entity type set.](http://drupal.org/node/2962142)
- [ ] #xx | [e7bd9429](http://git.drupalcode.org/project/views/commit/e7bd942952002cb2706c1de20dcc4aadeb64d2d4) | [Issue #2544642 by plach, marco: Translate link leads to an "acccess denied" page when node is language neutral.](http://drupal.org/node/2544642)
- [ ] #xx | [9b453d68](http://git.drupalcode.org/project/views/commit/9b453d68e4df66ba621e574194628dbc8bd9df88) | [Issue #2742805 by bohart, abramm: Taxonomy Term Edit Link field handler ignoring settings from `Output this field as a link`.](http://drupal.org/node/2742805)
- [ ] #xx | [0f6e47b1](http://git.drupalcode.org/project/views/commit/0f6e47b1611d82ae329a186786540ffd509e2d12) | [Issue #1103234 by dawehner, David_Rothstein, AexChecker, helmo, bojanz, mmilutinovic1313: Notice: Undefined index: group in views_handler->ui_name() (line 277 of includes/handlers.inc).](http://drupal.org/node/1103234)
- [ ] #xx | [50fe583e](http://git.drupalcode.org/project/views/commit/50fe583e15ae22d23565d8bb470345e85b77efb3) | [Issue #477984 by DamienMcKenna, fatstar415, Deciphered, Shevchuk, demeritcowboy, dzy, dagmar, jfrederick, aBrookland, Mike Dodd: CCK field is empty/not empty filter doesn't work when exposed.](http://drupal.org/node/477984)
- [ ] #xx | [05a734ee](http://git.drupalcode.org/project/views/commit/05a734ee90fdba0e213b5569d419038e255f3840) | [Issue #2813033 by kristiaanvandeneynde, johnennew: views_handler_field_user_name does not handle NULL columns.](http://drupal.org/node/2813033)
- [ ] #xx | [8d86ce27](http://git.drupalcode.org/project/views/commit/8d86ce27692cfad197e2b20c8b630bbe45b0095d) | [Issue #662692 by joachim, hanoii, ShaneOnABike, lunazoid, 5t4rdu5t: strange decimal precision error on floating numeric fields.](http://drupal.org/node/662692)
- [ ] #xx | [b394d13f](http://git.drupalcode.org/project/views/commit/b394d13f68fdde21eb61fef19fcafb74cad59a44) | [Issue #1877446 by James Andres, caiosba, Darren Oh, Jelle_S, dawehner, code-brighton, bpadaria, Pranjal.addweb, SunnyGambino, sergiuteaca, sadashiv, dmsmidt: Fix Ajax pager in nested views.](http://drupal.org/node/1877446)
- [ ] #xx | [670a5a90](http://git.drupalcode.org/project/views/commit/670a5a90f88351712788811ea9f9b814479a1459) | [Issue #2036473 by FeyP, DamienMcKenna, braindrift, grasmash, AaronBauman, RedEight, moonray, fietserwin, donquixote, badrange: Grouped exposed filters produces wrong where clause](http://drupal.org/node/2036473)
- [ ] #xx | [79ec694d](http://git.drupalcode.org/project/views/commit/79ec694deade1c991d1946eda98b35a5902e6bf4) | [Issue #3040090 by FeyP, Hidehisa, sarguna raj M, Joseph Zhao, BrankoC, Emil Cataranciuc: "SQLSTATE[HY000]: General error: 1116 Too many tables" with filter for field of relation.](http://drupal.org/node/3040090)
- [ ] #xx | [1f22336b](http://git.drupalcode.org/project/views/commit/1f22336b5ebc27c225986949e4ba717919c47311) | [Issue #3052850 by Spokje: PHP < 5.4 : Short Array notation error in views/handlers/views_handler_filter.inc.](http://drupal.org/node/3052850)
- [ ] #xx | [0d270fa4](http://git.drupalcode.org/project/views/commit/0d270fa45dbdedd19d9c5ca6488ed39a7b8a4886) | [Issue #3052872 by DamienMcKenna: Views-D7 code cleanups.](http://drupal.org/node/3052872)
- [ ] #xx | [b6414cb9](http://git.drupalcode.org/project/views/commit/b6414cb971b49927d0e6d18e6108204f70a2779d) | [Issue #3052872 by DamienMcKenna: Views-D7 code cleanups.](http://drupal.org/node/3052872)
- [ ] #xx | [535ff980](http://git.drupalcode.org/project/views/commit/535ff980ae3c0063b7314efc3ca21024699fa361) | [Issue #2529948 by klausi, danieldd: Remove filter_xss_admin() from result rewriting because views editors are already trusted admins.](http://drupal.org/node/2529948)
- [ ] #xx | [69c99e6d](http://git.drupalcode.org/project/views/commit/69c99e6d98aee31dbd34f840a631fd50aefa5e19) | [Issue #1930472 by Owen Barton, Dean Reilly: Add exclude support to string contextual filter handler.](http://drupal.org/node/1930472)
- [ ] #xx | [ac0e37e5](http://git.drupalcode.org/project/views/commit/ac0e37e555037f2272f503bbb66c081e69b5e754) | [Issue #2092929 by maijs, rafenden, Chris Matthews: Parent menu item weight can not be set via Views UI.](http://drupal.org/node/2092929)
- [ ] #xx | [04cdaf4d](http://git.drupalcode.org/project/views/commit/04cdaf4df95ef688d04338cbca763c0daf0388af) | [Issue #1644686 by mariacha1, marcusx, nicholas.alipaz, tim.plunkett, cgmonroe, firewaller: Add "local action" as a page display menu type.](http://drupal.org/node/1644686)
- [ ] #xx | [ce2f6611](http://git.drupalcode.org/project/views/commit/ce2f6611cafcbe15c758c0044a0e759d90156e64) | [Issue #2016127 by mmikitka, Chris Matthews: Provide ability to remove a user-specified list of unwanted characters from a URL path.](http://drupal.org/node/2016127)
- [ ] #xx | [544b5be5](http://git.drupalcode.org/project/views/commit/544b5be5f07af5e1d29e748b74715d598ec15a46) | [Issue #2285729 by emattias, DamienMcKenna, zterry95, Chris Matthews: Count multi field (without enabling aggregation).](http://drupal.org/node/2285729)
- [ ] #xx | [a394f9ad](http://git.drupalcode.org/project/views/commit/a394f9ad2e10b383942b4b67439f62a3d166468a) | [Issue #1269592 by monish_deb, rooby, DamienMcKenna, dioni, rdrh555, joelpittet, transformative, Darvanen, Tim Prys, Aporie: Attachment display title not showing.](http://drupal.org/node/1269592)
- [ ] #xx | [c2b1c575](http://git.drupalcode.org/project/views/commit/c2b1c575daf1e2181fef8e45799425b19c157fe0) | [Issue #2025443 by kvanderw, Andrew Answer, Chris Matthews, DamienMcKenna: Page display path maxlength should mirror core's 255 support.](http://drupal.org/node/2025443)
- [ ] #xx | [610f570e](http://git.drupalcode.org/project/views/commit/610f570e455fcbd9b21e91cfbbe7d4a020835186) | [Issue #2815863 by MustangGB, DamienMcKenna, stupiddingo, Pancho: Contextual filter values of "" don't trigger "When the filter value is NOT available".](http://drupal.org/node/2815863)
- [ ] #xx | [2c4f62ad](http://git.drupalcode.org/project/views/commit/2c4f62ade0af1a2541b1bd1a927de92ac31316ea) | [Issue #1773798 by DamienMcKenna, MustangGB, danwonac, imclean, kari.nies, NaX, clfer, DaPooch, Chris Matthews, gianfrasoft: For the grid format "Fill up single line" does not work when using vertical alignment for a single row.](http://drupal.org/node/1773798)

---
`git log 7.x-3.22..7.x-3.23 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](http://git.drupalcode.org/project/views/commit/%H) | [%s](http://drupal.org/node/" | sed -E "s/^(.*#)([[:digit:]]*)(.*)$/\1\2\3\\2)/g"`

**Comment by laryn** [comment]
I'm seeing this warning on a site when using Views, just noting here in case anyone is searching for the error later:

> Warning: Parameter 3 to views_ui_build_form_state() expected to be a reference, value given in views_ui_ajax_form() (line 2882 of /path/core/modules/views_ui/views_ui.admin.inc). 

It looks like it's covered by [a Drupal issue](https://www.drupal.org/project/views/issues/2810431) that is already linked above.

**Comment by jenlampton** [comment]
I also just created [an issue](https://github.com/backdrop/backdrop-issues/issues/4075) for an issue listed above. Will mark that one as duplicate of this.
