### ISSUE TITLE
Backdrop 1.13.3 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3969]
Scheduled for August 7th, 2019 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [x] Draft Release notes (@jenlampton)
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)
- [x] Draft Security Advisories (???)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub (@jenlampton)
- [x] Update the front page download link on b.org (@jenlampton)
- [x] Tweet that a new release is out (assign to stpaultim / jimbirch / jenlampton / quicksketch)

If this is a security release:
- [x] Publish Security Advisories on b.org (@klonos)
- [x] Mark the release node on b.org as a security release (@klonos)
- [x] [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) (@jenlampton) 
- [ ] Email the people who reported these issues (@jenlampton) 

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) (@quicksketch)
- [ ] Push the bug-fix release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) (@jenlampton)
- [ ] Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) (@drupol)
- [x] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) (@quicksketch)
- [x] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) (@serundeputy)
- [x] Update the Wikipedia articles (@klonos)
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

If this is a security release:
- [x] Update the Security Advisory with CVE (@jenlampton)

**Comment by jenlampton** [comment]
CVE ID Request #737503

**Comment by jenlampton** [comment]
CVEs added:
https://backdropcms.org/security/backdrop-sa-core-2019-011
https://backdropcms.org/security/backdrop-sa-core-2019-010
https://backdropcms.org/security/backdrop-sa-core-2019-012

**Comment by quicksketch** [comment]
Awesome! Wow that's a lot faster acquiring CVEs than it used to be. Thanks @jenlampton!

**Comment by findlabnet** [comment]
Incorrect info:
>>Update information:
>>    The database update script does not need to be run.

Actually, is need to be run - caused **system** module

    1069 - Removes an unused state value.

**Comment by klonos** [comment]
@olafgrabienski pointed that we missed #3643 from the list in the release notes for 1.13.3. Unfortunately, I don't have permissions to edit release descriptions, so can you please take care of that @jenlampton ?

**Comment by jenlampton** [comment]
I updated the database update script line for 1.13.3

**Comment by stpaultim** [comment]
Do we need to add Tugboat to the list of things to update after a release (especially a security release)?

I just logged in to a demo site and ran cron (as per @klonos 's suggestion) and got this:

![Status_report___Test](https://user-images.githubusercontent.com/3144571/62816110-1c362400-bae8-11e9-8f25-ef080c0bcac7.png)

**Comment by jenlampton** [comment]
@stpaultim 
it's there, and it's been done. See "Push the bug-fix release to the TugBoat Backdrop repository (@quicksketch)" with the check-mark to the left.

**Comment by stpaultim** [comment]
I must have been focused on the items that were not checked, because I did not see it there. Either that, or I'm going blind. Because I did check the list. 

:-)

**Comment by klonos** [comment]
Keeping browser tabs open and forgetting to refresh gets me all the time, so it could have been that @stpaultim 🤷‍♂ 

...I have also tested spinning a demo sandbox, and can confirm that it still runs 1.13.2.

**Comment by klonos** [comment]
@olafgrabienski mentioned that we also missed #3934 from the changelog.

@jenlampton ^^

**Comment by jenlampton** [comment]
I added the two missing issues to https://github.com/backdrop/backdrop/releases/tag/1.13.3
