### ISSUE TITLE
Backdrop 1.14.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4005]
Scheduled for September 15, 2019 TBD PT

## Pre-release tasks
 
- [x] Merge commits (assign to @quicksketch)
- [x] Create a new minor release milestone (@jenlampton)
- [x] Move all unfinished issues to the next minor release milestone (@klonos)
- [x] Draft Release notes (@stpaultim) 
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at `/update.php`) for this release."
  - [x] Include changelog since last version (generated with drush rn and then fixed)
- [x] Draft blog post (@stpaultim)
- [x] Draft roadmap updates for backdropcms.org (@klonos)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub (@quicksketch)
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub (@jenlampton)
- [x] Unpublish preview release on backdropcms.org (@klonos)
- [x] Update the front page download link on b.org (@stpaultim)
- [x] Tweet that a new release is out (@stpaultim)
- [x] Update https://api.backdropcms.org/documentation/trusted-host-settings (remove the warning at the top) and publish it.

## Post-release tasks

- [ ] Push the minor release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) (@quicksketch) 
- [ ] Push the minor release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) (@serundeputy)
- [ ] Push the minor release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) (@drupol)
- [x] Push the minor release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) (@quicksketch) 
- [x] Update b.org to use the new tugboat version (@quicksketch) 
- [ ] Push the minor release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) (@serundeputy)
- [x] Publish blog post (@stpaultim)
- [x] Publish forum post (@stpaultim)
- [ ] Send a newsletter via MailChimp (@facetinteractive)
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter (@jenlampton)
- [x] Publish roadmap updates for backdropcms.org (@klonos) 
- [x] Update the Wikipedia articles (@klonos)
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

See the Accompanying Bug-Fix Release Checklist
----------------------------------------------
https://github.com/backdrop/backdrop-issues/issues/4006

**Comment by jenlampton** [comment]
Release notes for the preview:
<p>Changes since 1.13.3:</p>
<ul>
  <li>Backdrop 1.14.0 Preview.</li>
  <li><a href="/node/2632">#2632</a>: Core fieldable file entity bundles.</li>
  <li><a href="/node/3755">#3755</a>: Fixing delete row token checking.</li>
  <li><a href="/node/3755">#3755</a>: Adding flexible templates to Layouts.</li>
  <li><a href="/node/2568">#2568</a>: Add support for "trusted_host_patterns".</li>
  <li><a href="/node/3862">#3862</a>: Exclude hidden paths from search for users without permission to view directly.</li>
  <li><a href="/node/1285">#1285</a>: Include an editor role in the standard profile.</li>
  <li><a href="/node/3994">#3994</a>: Add welcome dashboard block.</li>
</ul>

**Comment by klonos** [comment]
...as @olafgrabienski pointed out over Gitter, we should point out that people will need to update their `settings.php` files (because of #2568).

**Comment by stpaultim** [comment]
Draft blog post = https://backdropcms.org/news/backdrop-cms-114-released

Need to update link to release notes before publishing!

**Comment by stpaultim** [comment]
Don't know if this is helpful. But, I'll start a draft of some possible text for the actual [release notes](https://github.com/backdrop/backdrop/releases) here (to cut and paste).

Backdrop CMS version 1.14 is here!

The Backdrop community is proud to release this most recent version following our 4-month release cycle. This version of Backdrop includes great new features including:

* Core fieldable file entity bundles.
* Adding flexible templates to Layouts.
* Add support for `trusted_host_patterns`.
* Exclude hidden paths from search for users without permission to view directly.
* Include an editor role in the standard profile.
* Add welcome dashboard block.
* All the changes included in 1.13.3.
* More!

**Notes for updating:**

* It will be necessary to run the update script (located at /update.php) for this release.
* This release does not modify files outside the core directory. Updating customized copies of those files is not necessary.
* [Do we need any instructions for field files?]

**Changes since 1.13.3**

**Comment by klonos** [comment]
> This release does not modify files outside the core directory. Updating customized copies of those files is not necessary.

This is wrong. We have modified settings.php for #2568 ...people are advised to copy that section over to their existing settings.php file, and configure their trusted patterns.

**Comment by jenlampton** [comment]
I updated the section of @stpaultim's notes to include the change to settings.php. I don't think we need to add anything about fieldable files.

**Comment by stpaultim** [comment]
No, we don't need to say anything about fieldable files now that we've fixed the issue I complained about.

**Comment by stpaultim** [comment]
Just posted in Gitter. We never included any note in the release notes for 1.13 suggesting that users turn on the dashboard module. If they haven't enabled the dashboard module, they will never see the new welcome block. Maybe that's ok, because they are experienced users and might not need it.

But, I would like to see a line in the release notes that says something to the effect of: "You may need to enable the dashboard module to access the new welcome block."

**Comment by jenlampton** [comment]
Oh, I was thinking we should add that to the 1.3 release notes.

**Comment by stpaultim** [comment]
OK, it was good to add that to the 1.3 release notes. For some reason I had it in my mind that they were frozen. 

We could still put a note in the release notes that the Welcome Block is dependent upon the Dashboard module being enabled. I suggest this, since we are advertising this new feature, because it's so cool, and because I am guessing that most sites that were built with 1.12 or before probably have not turned on the dashboard module yet.

Also, we might want to emphasis that the new editor role will only appear on NEW sites. This might not be clear to all users and could be confusing to anyone expecting to find it.

**Comment by jenlampton** [comment]
@stpaultim I think those things would be better in the blog post than in the release notes. Not many people read the release notes on GitHub, and I'd bet most are developers.

**Comment by klonos** [comment]
...I will go ahead and close this one, since 1.14.2 was released today.
