### ISSUE TITLE
Backdrop 1.13.4 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4006]
Scheduled for Sept 15th, 2019 @TBD PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@klonos)
- [x] Move all unfinished issues to the next bugfix release milestone (@klonos)
- [x] Draft Release notes (@jenlampton)
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub (@jenlampton)

## Post-release tasks

All are handled in https://github.com/backdrop/backdrop-issues/issues/4005

**Comment by jenlampton** [comment]
Release notes Draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Update information:**

* The database update script does not need to be run.
* No changes have been made to the .htaccess, robots.txt or default settings.php files in this release, so upgrading custom versions of those files is not necessary.

**Changes since 1.13.3**

TBD

**Comment by jenlampton** [comment]
woot!

**Comment by klonos** [comment]
@jenlampton the issue links in https://github.com/backdrop/backdrop/releases/tag/1.13.4 are borked. I'd have fixed them myself, but no permission to edit releases 🤷‍♂

**Comment by klonos** [comment]
...also perhaps mention that with the last commit in #3719, we now have parity with Views 7.x-3.11?

**Comment by jenlampton** [comment]
Fixed: https://github.com/backdrop/backdrop/releases/tag/1.13.4
