### ISSUE TITLE
[META] Stay on top of date module updates

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4027]
Updates the Drupal 7 date module since we merged date into core:

- [ ] #4056 | Merge commits from Date 7.x-2.10-beta1 
- [ ] #4057 | Merge commits from Date 7.x-2.10-rc1 
- [ ] #4058 | Merge commits from Date 7.x-2.10-rc2 & 7.x-2.10
- [ ] #4059 | Merge commits from Date 7.x-2.11-beta1
- [ ] #4060 | Merge commits from Date 7.x-2.11-beta2  
- [ ] #5009 | Merge commits from Date 7.x-2.11-beta3 
- [ ] #5010 | Merge commits from Date 7.x-2.11-rc1
- [ ] #xx | Merge commits from Date 7.x-2.11
- [ ] #xx | Merge commits from Date  [7.x-2.12](https://www.drupal.org/project/date/releases/7.x-2.12)
- [ ] #xx | Merge commits from Date  [7.x-2.13](https://www.drupal.org/project/date/releases/7.x-2.13)
- [ ] #xx | Merge commits from Date  [7.x-2.14](https://www.drupal.org/project/date/releases/7.x-2.14)

This is the commit when date module went into core:
```
commit c1cdef69d5192525b9ec38bbab9dddc1a7adcb87
Merge: 6d119d137 da5728a55
Author: Nate Haug <nate@quicksketch.org>
Date:   Sun Sep 13 15:15:07 2015 -0600

    Merge pull request #1032 from quicksketch/478/date
    Issue #478: Add Date (field) module to core.

```

To find the date date module went into core, check [the roadmap]() for which release it was, then do a git log for all the commits for that release. You can either do this by release number, or by date:
`git log --since "May 15 2015" --until "sept 15 2015"`

Checking this list of commits for the one for Date module is easier than checking the whole history, but you can also do a commit search, with:
`git log --all --grep='searchstring'`

Now, let's find the previous stable release of date module. It looks like it was [7.x-2.9](https://www.drupal.org/project/date/releases/7.x-2.9) which came out on 8 September 2015.

These are all the previous releases of Date module including 7.x-2.9. (this list was generated from the "Other releases" sidebar on a [release detail page](https://www.drupal.org/project/date/releases/7.x-2.9).)

* [date 7.x-2.11-beta2]() 22 January 2019
* [date 7.x-2.11-beta1](https://www.drupal.org/project/date/releases/7.x-2.11-beta1) 26 October 2018
* [date 7.x-2.10](https://www.drupal.org/project/date/releases/7.x-2.10) 7 April 2017
* [date 7.x-2.10-rc2](https://www.drupal.org/project/date/releases/7.x-2.10-rc2) 29 March 2017
* [date 7.x-2.10-rc1](https://www.drupal.org/project/date/releases/7.x-2.10-rc1) 27 April 2016
* [date 7.x-2.10-beta1](https://www.drupal.org/project/date/releases/7.x-2.10-beta1) 8 January 2016
* [date 7.x-2.9](https://www.drupal.org/project/date/releases/7.x-2.9) 8 September 2015 

For the date module, let's find all the commits between that release and the current stable release, and format that to be all pretty for this issue, with:
`git log 7.x-2.9..7.x-2.11-beta2 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

Or if you want the commits by release number:

`git log 7.x-2.9..7.x-2.10-beta1 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

`git log 7.x-2.10-beta1..7.x-2.10-rc1 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

`git log 7.x-2.10-rc1..7.x-2.10-rc2 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

`git log 7.x-2.10-rc2..7.x-2.10 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

`git log 7.x-2.10..7.x-2.11-beta1 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

`git log 7.x-2.11-beta1..7.x-2.11-beta2 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

Part of https://github.com/backdrop/backdrop-issues/issues/2789

**Comment by jenlampton** [comment]
Today I ran into [this issue]() that has been resolved in the Drupal date module, so I decided to create this meta to get caught up with Date module for Backdrop. I've also filed [a PR for only that issue](https://github.com/backdrop/backdrop/pull/2868) so that I could get my site working again. I hope to have time to address some of these other changes soon too!
