### ISSUE TITLE
Merge commits from Link 7.x-1.3

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4054]
- [ ] #xx | [351670d](https://cgit.drupalcode.org/drupal/commit/?id=351670d04252c987abfb6c0a9a1d547a469c6c6d) | [Issue #2843813 by idebr, klausi, michael_wojcik, clemens.tolboom: Fix failing tests due to missing 'administer fields' permission](http://drupal.org/node/2843813)
- [ ] #xx | [5121965](https://cgit.drupalcode.org/drupal/commit/?id=51219658b6cabef08e35d43d58adafcac796dcd5) | [Issue #2888461 by RenatoG: Clear variable "link_extra_domains" on uninstall](http://drupal.org/node/2888461)
- [ ] #xx | [66918c5](https://cgit.drupalcode.org/drupal/commit/?id=66918c560c4dc766d4cdff117c8f10e9b6f13e8c) | [Issue #2888480 by RenatoG: Fixed documentation links in new window target "blank"](http://drupal.org/node/2888480)
- [ ] #xx | [b8d9338](https://cgit.drupalcode.org/drupal/commit/?id=b8d9338ea0fce6e2f21a0223357a8e041f598c0d) | [Issue #2888510 by RenatoG: Create tip for token on install](http://drupal.org/node/2888510)
- [ ] #xx | [3a22e7f](https://cgit.drupalcode.org/drupal/commit/?id=3a22e7f0c490ead39e26a9b6c57b517cc492eb52) | [Issue #2578521 by kala4ek, arialvix, soapboxcicero, ervit, RenatoG: Validation error](http://drupal.org/node/2578521)
- [ ] #xx | [838d0bb](https://cgit.drupalcode.org/drupal/commit/?id=838d0bbc5f3fb5f4adce6c3a919ecd8922b10119) | [Issue #2723993 by dhruveshdtripathi, rahul.shinde, jeevanbhushetty, RenatoG: help hook is not there](http://drupal.org/node/2723993)
- [ ] #xx | [01c1ed3](https://cgit.drupalcode.org/drupal/commit/?id=01c1ed35a97e906da371c44469ba9d0a5536b151) | [Issue #2888582 by RenatoG: Resolved unused variables in install file](http://drupal.org/node/2888582)
- [ ] #xx | [69a4b1c](https://cgit.drupalcode.org/drupal/commit/?id=69a4b1c69e271bfeafc9c15d6597de4b21c7a0e5) | [Issue #2566443 by ohthehugemanatee, RenatoG: Broken description text when used through Form API](http://drupal.org/node/2566443)
- [ ] #xx | [76825fd](https://cgit.drupalcode.org/drupal/commit/?id=76825fd15eb1700d47290a50b5e5daf0e7555d52) | [Issue #2889755 by RenatoG: Fixed Best practice in Drupal](http://drupal.org/node/2889755)
- [ ] #xx | [ee6ab07](https://cgit.drupalcode.org/drupal/commit/?id=ee6ab071b6556ff64ee2517628851c353c1ca2e7) | [Issue #2890013 by RenatoG: Fix codings standards for Link](http://drupal.org/node/2890013)
- [ ] #xx | [1568f74](https://cgit.drupalcode.org/drupal/commit/?id=1568f74c5748df1a406563d07716a816222a39cf) | [Issue #2299657 by egfrith, ChuChuNaKu, RenatoG, idebr, jtsnow, Leeteq, GoddamnNoise, tobiberlin, kristiaanvandeneynde, Remon, jcfiala, rootwork, drumm, klonos, brice_gato, quicksketch, brantwynn, mikeytown2, Vacilando, reptilex, samuel.mortenson, DamienMcKenna, ultimike, Graber, rv0, doraf, jp.stacey, kenorb, jmart, JonMcL, katjam: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [ ] #xx | [4b34720](https://cgit.drupalcode.org/drupal/commit/?id=4b34720b4fb670b329ac880485dbe84b72f0888d) | [Issue #2890057 by RenatoG: All content of file commented "link.views.inc" should be use @codingStandardsIgnoreFile tag](http://drupal.org/node/2890057)
- [ ] #xx | [f2ddf29](https://cgit.drupalcode.org/drupal/commit/?id=f2ddf29146047f54940aa4fd926295ef465aa9de) | [Issue #2299657 by egfrith, ChuChuNaKu, RenatoG, idebr, jtsnow, rootwork, Leeteq, kristiaanvandeneynde, GoddamnNoise, tobiberlin, Remon, drumm, jcfiala, klonos, brantwynn, quicksketch, mikeytown2, samuel.mortenson, brice_gato, Vacilando, katjam, kenorb, ultimike, Graber, rv0, DamienMcKenna, doraf, jmart, reptilex, jp.stacey, JonMcL: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [ ] #xx | [01bf538](https://cgit.drupalcode.org/drupal/commit/?id=01bf5385a653ac5221fd865f84e3aa1a5904ae7c) | [Issue #2299657 by egfrith, RenatoG, ChuChuNaKu, idebr, jtsnow, rootwork, kristiaanvandeneynde, GoddamnNoise, Leeteq, jcfiala, Remon, drumm, tobiberlin, brantwynn, klonos, Vacilando, quicksketch, mikeytown2, samuel.mortenson, brice_gato, katjam, kenorb, ultimike, Graber, rv0, othermachines, r0nn1ef, DamienMcKenna, doraf, jmart, reptilex, Berliner-dupe, jp.stacey, JonMcL, peter-majmesku: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [ ] #xx | [f51b531](https://cgit.drupalcode.org/drupal/commit/?id=f51b531aed9e3c63d8e64341438892895b2a13b6) | [Issue #2650956 by loopduplicate, amitmaity, karsumit94, RenatoG: Code standards are not followed for array modified in 2367069](http://drupal.org/node/2650956)
- [ ] #xx | [c6bbf42](https://cgit.drupalcode.org/drupal/commit/?id=c6bbf420e763b6cd25402eef6712950020e6e931) | [Issue #1909788 by mthomas, jesss, csc4, Kpolymorphic, RenatoG: Add an entity token for the display_url](http://drupal.org/node/1909788)
- [ ] #xx | [7f95f63](https://cgit.drupalcode.org/drupal/commit/?id=7f95f631f7066ed969ed001bbcc6aa7fb406a874) | [Issue #2299657 by egfrith, RenatoG, ChuChuNaKu, idebr, jtsnow, rootwork, kristiaanvandeneynde, GoddamnNoise, Leeteq, jcfiala, Remon, drumm, tobiberlin, brantwynn, klonos, Vacilando, quicksketch, mikeytown2, samuel.mortenson, brice_gato, katjam, kenorb, ultimike, Graber, rv0, othermachines, r0nn1ef, DamienMcKenna, doraf, jmart, reptilex, jp.stacey, JonMcL: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [ ] #xx | [d724ef6](https://cgit.drupalcode.org/drupal/commit/?id=d724ef626e9d2e156943bfdeccd55981df6a4352) | [Issue #2323441 by paolomainardi, sumitmadan, SylvainM, brockfanning, rob_johnston, RenatoG, mikeryan: [Patch] Migrate language argument array handling](http://drupal.org/node/2323441)
- [ ] #xx | [cb96589](https://cgit.drupalcode.org/drupal/commit/?id=cb96589532d581cce6852eb06a37121f09e2dec8) | [Issue #2553705 by Trav84, aguilarm, michaelfavia, reshma.i, RenatoG, roopeshnaik: Static Title does not show up when using 'Optional URL' + 'Static Title' with an empty URL](http://drupal.org/node/2553705)
- [ ] #xx | [1830a00](https://cgit.drupalcode.org/drupal/commit/?id=1830a003ff7e4c31c61322c6f4cfb45d996464c6) | [Issue #1418762 by num37, RenatoG, rvilar, jcfiala, randyhook: Provide default title when title is optional](http://drupal.org/node/1418762)
- [ ] #xx | [0771f0e](https://cgit.drupalcode.org/drupal/commit/?id=0771f0ed3d34ba1bc413b988dd3abcac12c4cd15) | [Issue #2140087 by olofjohansson, maximpodorov, mistermoper, RenatoG: Allow '0' as the link title](http://drupal.org/node/2140087)
- [ ] #xx | [f32d59b](https://cgit.drupalcode.org/drupal/commit/?id=f32d59b2030fbcc3aa2f5757036a0eeb8cf3df94) | [Issue #2693731 by Antonnavi, RenatoG: Tokens replaced on "Static title" when "Allow user-entered tokens" not enabled](http://drupal.org/node/2693731)
- [ ] #xx | [cc065f6](https://cgit.drupalcode.org/drupal/commit/?id=cc065f6f68b4a09056fcec063c2216185c062876) | [Issue #2612176 by FluxSauce, pcambra, RenatoG: PHP Fatal error: Class 'MigrateFieldHandler' not found](http://drupal.org/node/2612176)
- [ ] #xx | [0235032](https://cgit.drupalcode.org/drupal/commit/?id=0235032742ce4c70b34e537c799becf27ee0a89d) | [Issue #1335424 by claudiu.cristea, RenatoG: Title as a select](http://drupal.org/node/1335424)
- [ ] #xx | [eb42744](https://cgit.drupalcode.org/drupal/commit/?id=eb427442095c39a3e488cf550bbbb3c34a4098cd) | [Issue #1295132 by Scyther, RenatoG: Unnecessary variables in link.install](http://drupal.org/node/1295132)
- [ ] #xx | [a30f0b1](https://cgit.drupalcode.org/drupal/commit/?id=a30f0b16bcfb37f86daa31a6a350c7578b6e4d9c) | [Issue #2499165 by jcnventura, RenatoG: Validate all latin accented chars](http://drupal.org/node/2499165)
- [ ] #xx | [232dc95](https://cgit.drupalcode.org/drupal/commit/?id=232dc95e789f0dcd7473d18b40d6f71c4cecad08) | [Issue #2299657 by RenatoG, egfrith, ChuChuNaKu, idebr, jtsnow, rootwork, kristiaanvandeneynde, GoddamnNoise, Leeteq, jcfiala, Remon, drumm, tobiberlin, brantwynn, klonos, Vacilando, quicksketch, mikeytown2, samuel.mortenson, brice_gato, katjam, kenorb, ultimike, Graber, rv0, othermachines, r0nn1ef, DamienMcKenna, doraf, jmart, reptilex, Berliner-dupe, jp.stacey, JonMcL: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [ ] #xx | [4f099b5](https://cgit.drupalcode.org/drupal/commit/?id=4f099b52557bab0093c37fb93d996d4a4498304d) | [Issue #2558497 by joachim, RenatoG: property type for 'url' entity metadata property should not be 'url'](http://drupal.org/node/2558497)
- [ ] #xx | [a7d2015](https://cgit.drupalcode.org/drupal/commit/?id=a7d2015d2208b8717acc1c6de2b884da5525f0f3) | [Issue #2889683 by Yago Elias, RenatoG: Protocol-less URLs should be cleaned for use](http://drupal.org/node/2889683)
- [ ] #xx | [f52d232](https://cgit.drupalcode.org/drupal/commit/?id=f52d232bcede9bd0fa45d6dc86b9d6a403c2d740) | [Issue #2166459 by j0rd, mstef: Notice: Undefined index: error_element in link_field_widget_error() (line 328 of link.module)](http://drupal.org/node/2166459)
- [ ] #xx | [dae1c4f](https://cgit.drupalcode.org/drupal/commit/?id=dae1c4f1b6e609d8892e4f541972da3885a07b76) | [Issue #2897332 by RenatoG: Fix all items of Code Review for Link](http://drupal.org/node/2897332)
- [ ] #xx | [60c08b4](https://cgit.drupalcode.org/drupal/commit/?id=60c08b4e03518e489b3f2583971f8a8c90c67821) | [Issue #2897348 by RenatoG: Update documentation in README file for nre template of Drupal.org](http://drupal.org/node/2897348)
- [ ] #xx | [224e1c2](https://cgit.drupalcode.org/drupal/commit/?id=224e1c2ae14e736c14390b8983b5abe87ad745ba) | [Issue #2897563 by RenatoG: Fix Coding Standards, Best Practices and Insert Documentation in Comments for Tests](http://drupal.org/node/2897563)
- [ ] #xx | [315f554](https://cgit.drupalcode.org/drupal/commit/?id=315f5549fcd0a04fcd16b99f869f77a8c616a911) | [Issue #2743401 by RenatoG, MHuebner: Use parent directory in internal url](http://drupal.org/node/2743401)
- [ ] #xx | [11d7a81](https://cgit.drupalcode.org/drupal/commit/?id=11d7a81d305e8aa2de54dee8edaa6cf9b8afc08f) | [Issue #2244041 by alberto56, RenatoG: Undefined index: widget in link.module on line 1341](http://drupal.org/node/2244041)
- [ ] #xx | [c722643](https://cgit.drupalcode.org/drupal/commit/?id=c722643295e82b8e67c9d2c889d17bebae7400eb) | Fix tests
- [ ] #xx | [1947a81](https://cgit.drupalcode.org/drupal/commit/?id=1947a815e6990ce027c178fc28420b2c9d3fa0f2) | Fix tests
- [ ] #xx | [f8fb946](https://cgit.drupalcode.org/drupal/commit/?id=f8fb946400a78b59c2f629052f6e43750f45a026) | [Issue #2911860 by RenatoG: Fix tests items results](http://drupal.org/node/2911860)
- [ ] #xx | [ffa33c0](https://cgit.drupalcode.org/drupal/commit/?id=ffa33c0878c2c6f43d680699b5fcda21241ef810) | Fix tests
- [ ] #xx | [7381efc](https://cgit.drupalcode.org/drupal/commit/?id=7381efc5f2aa7d2ae5f794cc0913e7286a354f46) | [Issue #2911860 by RenatoG: Fix tests items results](http://drupal.org/node/2911860)
- [ ] #xx | [19d07bc](https://cgit.drupalcode.org/drupal/commit/?id=19d07bcc7d8bf5d04f80fa42a42fee4956bf4566) | Fix tests
- [ ] #xx | [c6bb41b](https://cgit.drupalcode.org/drupal/commit/?id=c6bb41bd5f1b4f0d59fe2255a69554a928e55448) | [Issue #2911860 by RenatoG: Fix tests items results](http://drupal.org/node/2911860)
- [ ] #xx | [af6d13a](https://cgit.drupalcode.org/drupal/commit/?id=af6d13a27a3d8a94ab6d88551f8b9ab600b8bdee) | [Issue #2480723 by krystalcode, naidim, rrrob, sumitmadan, Argus, diqidoq, RenatoG, jbitdrop: Avoid warning in diff integration for links without title](http://drupal.org/node/2480723)
- [ ] #xx | [c0d2425](https://cgit.drupalcode.org/drupal/commit/?id=c0d242585e6c70913436522fcfd361d7a4eff5aa) | Modification for bug fixes related to HTML entities in title and no protocol for url display format
- [ ] #xx | [7c501ee](https://cgit.drupalcode.org/drupal/commit/?id=7c501ee9b4fbd269d2aa59be0d710fa1ec446fcb) | [Issue #2216399 by jemond: Provide Formatter to remove http:// or https:// from URL Issue #1836632 by jmart: Double HTML escaping when using plain_title formatter](http://drupal.org/node/2216399)
- [ ] #xx | [c13b372](https://cgit.drupalcode.org/drupal/commit/?id=c13b37261e5c41d85f8a1fec9f368e84b8e0c86d) | [Issue #2901656 and #2210297 by nightwalkr, mfernea: validates that the input on the URL field actually exists as a path alias. Theme_link_formatter_link_default() doesn't work with classes defined in a preprocess function.](http://drupal.org/node/2901656)
- [ ] #xx | [eed0cf1](https://cgit.drupalcode.org/drupal/commit/?id=eed0cf14fcf81b5d3c24b3217d7d358b90068490) | [Issue #2945128: Fix coding standard test parts](http://drupal.org/node/2945128)
- [ ] #xx | [de09697](https://cgit.drupalcode.org/drupal/commit/?id=de096973f4ceead6c540715ef0607887d1fe3d63) | [Issue #2945131: Fix coding standards module.](http://drupal.org/node/2945131)
- [ ] #xx | [06b1040](https://cgit.drupalcode.org/drupal/commit/?id=06b10406584841d781a1158657f7a19df81af31b) | [Issue #2945133: Warning: Method call uses 2 parameters, but method signature uses 1 parameters](http://drupal.org/node/2945133)
- [ ] #xx | [2a475d4](https://cgit.drupalcode.org/drupal/commit/?id=2a475d494f8e4f1e5a03cf43e4a251680fc9f055) | [Issue #2945137: Unused variables](http://drupal.org/node/2945137)
- [ ] #xx | [1d59d6c](https://cgit.drupalcode.org/drupal/commit/?id=1d59d6cbede799d9199659d8c53256a2446eb306) | [Issue #2945139: options(&$options) deprecated since views2.](http://drupal.org/node/2945139)
- [ ] #xx | [6f1bf54](https://cgit.drupalcode.org/drupal/commit/?id=6f1bf54adcbb40cb37b1f545d3bff0e7d8265e50) | Fixed test
- [ ] #xx | [77147ee](https://cgit.drupalcode.org/drupal/commit/?id=77147ee19fcf0efd7dffcc3bc3deb3f3ec5e3e21) | Fixed test
- [ ] #xx | [90a59d3](https://cgit.drupalcode.org/drupal/commit/?id=90a59d3994b4510acbdd598d782469495b401358) | [Issue #2553705 and #2961210 by billywardrop, pifagor, vinmassaro, alex_optim, alex.mazaltov: Preparation of module version 1.5.](http://drupal.org/node/2553705)

This list generated with:
`git log 7.x-1.3..7.x-1.4 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`

**Comment by herbdool** [comment]
I've created an issue https://github.com/backdrop/backdrop-issues/issues/5000 and linked it above: URLs are not validated.
