### ISSUE TITLE
Merge commits from Link 7.x-1.5 (and 7.x-1.6)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4055]
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786944436) | [351670d](https://git.drupalcode.org/project/link/commit/351670d) | [Issue #2843813: Fix failing tests due to missing 'administer fields' permission](http://drupal.org/node/2843813)
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786946686) | [5121965](https://git.drupalcode.org/project/link/commit/5121965) | [Issue #2888461: Clear variable "link_extra_domains" on uninstall](http://drupal.org/node/2888461)
- [ ] https://github.com/backdrop/backdrop/pull/3540 | [66918c5](https://git.drupalcode.org/project/link/commit/66918c5) | [Issue #2888480: Fixed documentation links in new window target "blank"](http://drupal.org/node/2888480)
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786950152) | [b8d9338](https://git.drupalcode.org/project/link/commit/b8d9338) | [Issue #2888510: Create tip for token on install](http://drupal.org/node/2888510)
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786952558) | [3a22e7f](https://git.drupalcode.org/project/link/commit/3a22e7f) | [Issue #2578521: Validation error](http://drupal.org/node/2578521)
- [x] N/A, since the Help module and `hook_help()` have removed from Backdrop core | [838d0bb](https://git.drupalcode.org/project/link/commit/838d0bb) | [Issue #2723993: help hook is not there](http://drupal.org/node/2723993)
- [x] N/A (that commit only updates 7xxx update hooks in `link.install`) | [01c1ed3](https://git.drupalcode.org/project/link/commit/01c1ed3) | [Issue #2888582: Resolved unused variables in install file](http://drupal.org/node/2888582)
- [ ] https://github.com/backdrop/backdrop/pull/3541 | [69a4b1c](https://git.drupalcode.org/project/link/commit/69a4b1c) | [Issue #2566443: Broken description text when used through Form API](http://drupal.org/node/2566443)
- [ ] https://github.com/backdrop/backdrop/pull/3542 | [76825fd](https://git.drupalcode.org/project/link/commit/76825fd) | [Issue #2889755: Fixed Best practice in Drupal](http://drupal.org/node/2889755)
- [x] N/A | [ee6ab07](https://git.drupalcode.org/project/link/commit/ee6ab07) | [Issue #2890013: Fix codings standards for Link](http://drupal.org/node/2890013)
- [x] N/A see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786952558 | [1568f74](https://git.drupalcode.org/project/link/commit/1568f74) | [Issue #2299657: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [x] N/A | [4b34720](https://git.drupalcode.org/project/link/commit/4b34720) | [Issue #2890057: All content of file commented "link.views.inc" should be use @codingStandardsIgnoreFile tag](http://drupal.org/node/2890057)
- [x] N/A see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786952558 | [f2ddf29](https://git.drupalcode.org/project/link/commit/f2ddf29) | [Issue #2299657: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [x] N/A see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786952558 | [01bf538](https://git.drupalcode.org/project/link/commit/01bf538) | [Issue #2299657: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [x] N/A | [f51b531](https://git.drupalcode.org/project/link/commit/f51b531) | [Issue #2650956: Code standards are not followed for array modified in 2367069](http://drupal.org/node/2650956)
- [ ] N/A ??? see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786975503 | [c6bbf42](https://git.drupalcode.org/project/link/commit/c6bbf42) | [Issue #1909788: Add an entity token for the display_url](http://drupal.org/node/1909788)
- [x] N/A see https://github.com/backdrop/backdrop-issues/issues/4055#issuecomment-786952558 | [7f95f63](https://git.drupalcode.org/project/link/commit/7f95f63) | [Issue #2299657: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [x] N/A | [d724ef6](https://git.drupalcode.org/project/link/commit/d724ef6) | [Issue #2323441: [Patch] Migrate language argument array handling](http://drupal.org/node/2323441)
- [ ] https://github.com/backdrop/backdrop/pull/3544 | [cb96589](https://git.drupalcode.org/project/link/commit/cb96589) | [Issue #2553705: Static Title does not show up when using 'Optional URL' + 'Static Title' with an empty URL](http://drupal.org/node/2553705)
- [ ] https://github.com/backdrop/backdrop/pull/3545 | [1830a00](https://git.drupalcode.org/project/link/commit/1830a00) | [Issue #1418762: Provide default title when title is optional](http://drupal.org/node/1418762)
- [ ] https://github.com/backdrop/backdrop/pull/3546 | [0771f0e](https://git.drupalcode.org/project/link/commit/0771f0e) | [Issue #2140087: Allow '0' as the link title](http://drupal.org/node/2140087)
- [ ] https://github.com/backdrop/backdrop/pull/3547 | [f32d59b](https://git.drupalcode.org/project/link/commit/f32d59b) | [Issue #2693731: Tokens replaced on "Static title" when "Allow user-entered tokens" not enabled](http://drupal.org/node/2693731)
- [x] N/A | [cc065f6](https://git.drupalcode.org/project/link/commit/cc065f6) | [Issue #2612176: PHP Fatal error: Class 'MigrateFieldHandler' not found](http://drupal.org/node/2612176)
- [x] #4970 | [0235032](https://git.drupalcode.org/project/link/commit/0235032) | [Issue #1335424: Title as a select](http://drupal.org/node/1335424)
- [ ] #xx | [eb42744](https://git.drupalcode.org/project/link/commit/eb42744) | [Issue #1295132: Unnecessary variables in link.install](http://drupal.org/node/1295132)
- [ ] #xx | [a30f0b1](https://git.drupalcode.org/project/link/commit/a30f0b1) | [Issue #2499165: Validate all latin accented chars](http://drupal.org/node/2499165)
- [x] https://github.com/backdrop/backdrop/pull/3543 | [232dc95](https://git.drupalcode.org/project/link/commit/232dc95) | [Issue #2299657: Allow any TLD because site admins can never keep up with ICANN](http://drupal.org/node/2299657)
- [ ] #xx | [4f099b5](https://git.drupalcode.org/project/link/commit/4f099b5) | [Issue #2558497: property type for 'url' entity metadata property should not be 'url'](http://drupal.org/node/2558497)
- [ ] https://github.com/backdrop/backdrop-issues/issues/5000 | [a7d2015](https://git.drupalcode.org/project/link/commit/a7d2015) | [Issue #2889683: Protocol-less URLs should be cleaned for use](http://drupal.org/node/2889683)
- [ ] #xx | [f52d232](https://git.drupalcode.org/project/link/commit/f52d232) | [Issue #2166459: Notice: Undefined index: error_element in link_field_widget_error() (line 328 of link.module)](http://drupal.org/node/2166459)
- [ ] #xx | [dae1c4f](https://git.drupalcode.org/project/link/commit/dae1c4f) | [Issue #2897332: Fix all items of Code Review for Link](http://drupal.org/node/2897332)
- [ ] #xx | [60c08b4](https://git.drupalcode.org/project/link/commit/60c08b4) | [Issue #2897348: Update documentation in README file for nre template of Drupal.org](http://drupal.org/node/2897348)
- [ ] #xx | [224e1c2](https://git.drupalcode.org/project/link/commit/224e1c2) | [Issue #2897563: Fix Coding Standards, Best Practices and Insert Documentation in Comments for Tests](http://drupal.org/node/2897563)
- [ ] #xx | [315f554](https://git.drupalcode.org/project/link/commit/315f554) | [Issue #2743401: Use parent directory in internal url](http://drupal.org/node/2743401)
- [ ] #xx | [11d7a81](https://git.drupalcode.org/project/link/commit/11d7a81) | [Issue #2244041: Undefined index: widget in link.module on line 1341](http://drupal.org/node/2244041)
- [ ] #xx | [c722643](https://git.drupalcode.org/project/link/commit/c722643) | Fix tests
- [ ] #xx | [1947a81](https://git.drupalcode.org/project/link/commit/1947a81) | Fix tests
- [ ] #xx | [f8fb946](https://git.drupalcode.org/project/link/commit/f8fb946) | [Issue #2911860: Fix tests items results](http://drupal.org/node/2911860)
- [ ] #xx | [ffa33c0](https://git.drupalcode.org/project/link/commit/ffa33c0) | Fix tests
- [ ] #xx | [7381efc](https://git.drupalcode.org/project/link/commit/7381efc) | [Issue #2911860: Fix tests items results](http://drupal.org/node/2911860)
- [ ] #xx | [19d07bc](https://git.drupalcode.org/project/link/commit/19d07bc) | Fix tests
- [ ] #xx | [c6bb41b](https://git.drupalcode.org/project/link/commit/c6bb41b) | [Issue #2911860: Fix tests items results](http://drupal.org/node/2911860)
- [ ] #xx | [af6d13a](https://git.drupalcode.org/project/link/commit/af6d13a) | [Issue #2480723: Avoid warning in diff integration for links without title](http://drupal.org/node/2480723)
- [ ] #xx | [c0d2425](https://git.drupalcode.org/project/link/commit/c0d2425) | [Modification for bug fixes related to HTML entities in title and no protocol for url display format](http://drupal.org/node/)
- [ ] #xx | [7c501ee](https://git.drupalcode.org/project/link/commit/7c501ee) | [Issue #2216399: Provide Formatter to remove http:// or https:// from URL Issue #1836632 by jmart: Double HTML escaping when using plain_title formatter](http://drupal.org/node/2216399)
- [ ] #xx | [c13b372](https://git.drupalcode.org/project/link/commit/c13b372) | Issue [#2901656](http://drupal.org/node/2901656) and [#2210297](http://drupal.org/node/2210297) : validates that the input on the URL field actually exists as a path alias. Theme_link_formatter_link_default() doesn't work with classes defined in a preprocess function.
- [ ] #xx | [eed0cf1](https://git.drupalcode.org/project/link/commit/eed0cf1) | [Issue #2945128: Fix coding standard test parts](http://drupal.org/node/2945128)
- [ ] #xx | [de09697](https://git.drupalcode.org/project/link/commit/de09697) | [Issue #2945131: Fix coding standards module.](http://drupal.org/node/2945131)
- [ ] #xx | [06b1040](https://git.drupalcode.org/project/link/commit/06b1040) | [Issue #2945133: Warning: Method call uses 2 parameters, but method signature uses 1 parameters](http://drupal.org/node/2945133)
- [ ] #xx | [2a475d4](https://git.drupalcode.org/project/link/commit/2a475d4) | [Issue #2945137: Unused variables](http://drupal.org/node/2945137)
- [ ] #xx | [1d59d6c](https://git.drupalcode.org/project/link/commit/1d59d6c) | [Issue #2945139: options(&$options) deprecated since views2.](http://drupal.org/node/2945139)
- [ ] #xx | [6f1bf54](https://git.drupalcode.org/project/link/commit/6f1bf54) | Fixed test.
- [ ] #xx | [77147ee](https://git.drupalcode.org/project/link/commit/77147ee) | Fixed test.
- [ ] #xx | [90a59d3](https://git.drupalcode.org/project/link/commit/90a59d3) | Issues [#2553705](http://drupal.org/node/2553705) and [#2961210](http://drupal.org/node/2961210) : Preparation of module version 1.5.

This list generated with:
`git log 7.x-1.4..7.x-1.5 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://git.drupalcode.org/project/link/commit/%h) | [%s](http://drupal.org/node/)"`

**Comment by klonos** [comment]
[351670d](https://git.drupalcode.org/project/link/commit/351670d) | [Issue #2843813: Fix failing tests due to missing 'administer fields' permission](http://drupal.org/node/2843813)

This is not applicable to us; the `protected $permissions` array in `class LinkBaseTestClass` within our `link.test` file already includes the `'administer content types'` permission, and that is what's being used in the rest of the `link.*` tests.

**Comment by klonos** [comment]
[5121965](https://git.drupalcode.org/project/link/commit/5121965) | [Issue #2888461: Clear variable "link_extra_domains" on uninstall](http://drupal.org/node/2888461)

This is also not applicable to us. See `link_update_1000()` and `link_update_1001()` and the comments re `Link no longer has any config in Backdrop.`

`update_variable_del('link_extra_domains');` was specifically removed from `link_update_1000()` with https://github.com/backdrop/backdrop/commit/5f10c4cd7b5ea11ebd5b88fa2c62d460e0c0ddad#diff-d29e5fcceede04c547aa6b97a8ea269db0c950f75a82c0d9cf6a5af33aa36c0cL61

**Comment by klonos** [comment]
[b8d9338](https://git.drupalcode.org/project/link/commit/b8d9338) | [Issue #2888510: Create tip for token on install](http://drupal.org/node/2888510)

This commit in Link 7.x was simply adding this:

```php
function link_install() {
  // Notify the user they may want to install token.
  if (!module_exists('token')) {
    drupal_set_message(t('If you install the <a href="!url" target="blank">Token</a>, static title can use any other entity field as its value.', array(
      '!url' => 'http://drupal.org/project/token',
    )));
  }
}
```

...but with token being baked into Backdrop core, and not a separate module, this does not apply to us.

**Comment by klonos** [comment]
[3a22e7f](https://git.drupalcode.org/project/link/commit/3a22e7f) | [Issue #2578521: Validation error](http://drupal.org/node/2578521)

Does not apply to us, since domain validation was removed from the Link module in Backdrop core, with https://github.com/backdrop/backdrop/commit/5f10c4cd7b5ea11ebd5b88fa2c62d460e0c0ddad#diff-fb3b913f72a04dbe75122117c4c9c8264199da44f2f8b6b1ffbb9ba54a8f5847L13

The bug report in https://www.drupal.org/node/2578521 said:

> http://www.eitb.eus/es/ considered not valid URL on field validation.

Which I just tested and confirmed that no validation errors are thrown in Backdrop 👍

**Comment by jenlampton** [comment]
Thanks @klonos! For any commit that is N/A for us can you please tick the item off the list?

**Comment by klonos** [comment]
I need help with [c6bbf42](https://git.drupalcode.org/project/link/commit/c6bbf42) | [Issue #1909788: Add an entity token for the display_url](http://drupal.org/node/1909788)

This seems like a new feature(?). From the issue description in d.org:

> It would be incredibly useful to have an entity token available for the display_url. `[node:field-link:url]` strips the query string from the URL, which makes it difficult to use it as a replacement in Linked Field, Views and elsewhere.

When adding a link field to a content type though, the only token I see available in Backdrop is `[node:field_link]`:

![image](https://user-images.githubusercontent.com/2423362/109370431-eb276b00-78a8-11eb-843c-25b77dc9ad95.png)

...and it's the same in D7, with the respective 7.x versions of token/link/pathauto:

![image](https://user-images.githubusercontent.com/2423362/109370755-5c1b5280-78aa-11eb-8865-d23e5a15d601.png)

What am I missing here? How do we get these `:url` tokens?

**Comment by jenlampton** [comment]
The commit shows one file changed -- and not relating to tokens:

https://git.drupalcode.org/project/link/commit/c6bbf42

**Comment by klonos** [comment]
I've split #4970 into its own issue, since it's a new feature, and I've ticked it off the list here. If there are commits between 7.x-1.4 and 7.x-1.7 of the Link module that touch that featire, then lets include them in the PR for that issue.

**Comment by herbdool** [comment]
@klonos RTBC on https://github.com/backdrop/backdrop/pull/3543

**Comment by herbdool** [comment]
I've created https://github.com/backdrop/backdrop-issues/issues/5000 and linked it above to "protocol-less...".

**Comment by jenlampton** [comment]
Issue 5000! :)
