### ISSUE TITLE
Merge commits from Date 2.10-beta1

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4056]
- [ ] #xx | [b7fa095d](https://cgit.drupalcode.org/drupal/commit/?id=b7fa095d162dcb79e8d43e9398a55c8b65d21c8e) | [Issue #2325207 by jojonaloha, v1nk, podarok: DateTimeZone could not be converted to string](http://drupal.org/node/2325207)
- [ ] #xx | [caef1bc0](https://cgit.drupalcode.org/drupal/commit/?id=caef1bc02567c2a68c981c8ce080e68d9291b515) | [Issue #2469189 by TommyK: Notice: Undefined index: show_remaining_days in date_field_formatter_view() (line 210 of …/date/date.field.inc)](http://drupal.org/node/2469189)
- [ ] #xx | [ed287f8c](https://cgit.drupalcode.org/drupal/commit/?id=ed287f8c36a00c83965bbe0cbde4df3ba4ba73b2) | [Issue #1854220 by ryanissamson, paravibe: Add module_exists so that error isn't thrown when disabling date_repeat_field module](http://drupal.org/node/1854220)
- [ ] #xx | [c388ec75](https://cgit.drupalcode.org/drupal/commit/?id=c388ec75c9cd6eba68fb798f0d4e9b63c461a0c1) | [Issue #2375235 by Lostboy22, steinmb, rsmylski, Jelle_S: Calendar block Next/Prev navigation broken](http://drupal.org/node/2375235)
- [ ] #xx | [c8771964](https://cgit.drupalcode.org/drupal/commit/?id=c8771964ab47385490996ed4a86ae6adc2979ef6) | [Issue #1889744 by tatyana, mstrelan, mariagwyn:  PDOException when saving date as unix timestamp](http://drupal.org/node/1889744)
- [ ] #xx | [2a62136e](https://cgit.drupalcode.org/drupal/commit/?id=2a62136e6a4dfee6d1dc8fa0c32c6e422262f4d6) | [Issue #1797630 by damiankloip, webby7097, Fabianx: 'Is empty(null)' views filter is not working with exposed operators enabled when actual date values are left empty](http://drupal.org/node/1797630)

This list generated by:
`git log 7.x-2.9..7.x-2.10-beta1 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`
