### ISSUE TITLE
Merge commits from Date 10-rc1

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4057]
- [ ] #xx | [3f2c698f](https://cgit.drupalcode.org/drupal/commit/?id=3f2c698f41c39832f49db84d70a4bc0b958b4194) | [Issue #1355256 by develCuy, barraponto, KarenS, jgullstr, Romash: date field minutes and seconds rounding after update/save](http://drupal.org/node/1355256)
- [ ] #xx | [18fc1a72](https://cgit.drupalcode.org/drupal/commit/?id=18fc1a72a2d76dff885d349ace62cdca53edc9cf) | [Issue #1889744 by tatyana, mstrelan, mariagwyn:  PDOException when saving date as unix timestamp](http://drupal.org/node/1889744)
- [ ] #xx | [2b790116](https://cgit.drupalcode.org/drupal/commit/?id=2b7901162bd6880e5b561b3fe5107d339ce1082f) | [Issue #1504202 by seanB, steinmb: Allow entering of custom date format in Views field handlers](http://drupal.org/node/1504202)
- [ ] #xx | [d6e1d4e0](https://cgit.drupalcode.org/drupal/commit/?id=d6e1d4e03c33b68248574c573f5f204614102c58) | [Issue #2532636 by jstoller: Undefined index: #default_value in date_popup_process_time_part()](http://drupal.org/node/2532636)
- [ ] #xx | [4a2dc354](https://cgit.drupalcode.org/drupal/commit/?id=4a2dc354448b293b0e2bb56827cacf24ab2f110d) | [Issue #1699312 by gmclelland, pounard, Niklas Fiekas, azinck, netlooker: Fatal error: Call to undefined function date_field_widget_settings_form_validate() in form.inc](http://drupal.org/node/1699312)
- [ ] #xx | [e29ef157](https://cgit.drupalcode.org/drupal/commit/?id=e29ef1572b5750d2ec6e3f1a618f5412d561e838) | [Issue #1874422 by danwonac, bluetegu, SeanA, rv0, brockfanning: Pager may cause incorrect "prev" or "next" link](http://drupal.org/node/1874422)
- [ ] #xx | [e0c88c04](https://cgit.drupalcode.org/drupal/commit/?id=e0c88c0439918165e7549db0e101528b31203c54) | [Issue #2038057 by vijaycs85, djdevin, pivanov: date_select element's default value as an array raises a warning](http://drupal.org/node/2038057)
- [ ] #xx | [1087cb59](https://cgit.drupalcode.org/drupal/commit/?id=1087cb592761d351743115129e5ae28ff39062ae) | [Issue #2026545 by mistermoper, Jon Nunan: Date field's interval formatter always uses start date](http://drupal.org/node/2026545)
- [ ] #xx | [02eeea30](https://cgit.drupalcode.org/drupal/commit/?id=02eeea3008d71487a097cd08c4712432f2856a76) | [Issue #2331975 by BarisW, StryKaizer: Sync end date for the date popup functionality](http://drupal.org/node/2331975)
- [ ] #xx | [3072a85b](https://cgit.drupalcode.org/drupal/commit/?id=3072a85b981963eaa2da51576fc5411d6e130cb3) | [Issue #2339119 by maximpodorov, darkdim: Notice: Undefined index: date in date_text_element_process()](http://drupal.org/node/2339119)
- [ ] #xx | [06f75d14](https://cgit.drupalcode.org/drupal/commit/?id=06f75d14662665f500c69af91144a4881a482c6d) | [Issue #2570239 by PascalAnimateur: Display date range as span instead of div](http://drupal.org/node/2570239)
- [ ] #xx | [df4de443](https://cgit.drupalcode.org/drupal/commit/?id=df4de4431ea4f937bb071b4fb5c3c48441c6b31f) | [Issue #2611968 by FluxSauce: PHP Fatal error: Class 'MigrateFieldHandler' not found](http://drupal.org/node/2611968)
- [ ] #xx | [15fbe471](https://cgit.drupalcode.org/drupal/commit/?id=15fbe471c7cc769df4ef65a91f84365235018c11) | [Issue #2160843 by nupur.lohokare: Grammar issue: "Date objects can be created and cached as date fields are loaded rather than when they are displayed to improve performance"](http://drupal.org/node/2160843)

This list generated by
`git log 7.x-2.10-beta1..7.x-2.10-rc1 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"
