### ISSUE TITLE
Merge commits from Date 2.10-rc2 & 2.10

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4058]
- [ ] #xx | [c9f9c1ea](https://cgit.drupalcode.org/drupal/commit/?id=c9f9c1ea938fa5e6342a4976b9d90cfb7727bb95) | [Issue #1037150 by raggax2, vishy_singhal, antroxim, Risse: date_popup element with just time doesn't work](http://drupal.org/node/1037150)
- [ ] #xx | [4e2ed49d](https://cgit.drupalcode.org/drupal/commit/?id=4e2ed49d0faca67ac3f8ef1f64d6e37814aa4fcc) | [Issue #2648114 by tsapenkoum: DateTime::format(): The DateTime object has not been correctly initialized by its constructor in DateObject->format()](http://drupal.org/node/2648114)
- [ ] #xx | [ea2ea311](https://cgit.drupalcode.org/drupal/commit/?id=ea2ea311f0b6762f842683a3871b24d803e16ce2) | [Issue #2780415 by prince_zyxware, DamienMcKenna: As per Drupal coding standards, use uppercase for PHP constants](http://drupal.org/node/2780415)
- [ ] #xx | [fdb7029f](https://cgit.drupalcode.org/drupal/commit/?id=fdb7029f6690e35fa2480deb7e3561bf4366964e) | [Issue #2646646 by anpolimus, Stevel, DamienMcKenna: Tests are broken on current 7.x-2.x branch](http://drupal.org/node/2646646)
- [ ] #xx | [a769db79](https://cgit.drupalcode.org/drupal/commit/?id=a769db79b9dbfe2dc4e1bb5d04b1d2326e617031) | [Issue #2412049 by Stevel: DateMigrateExampleUnitTest fails if migrate is missing](http://drupal.org/node/2412049)
- [ ] #xx | [5697af7b](https://cgit.drupalcode.org/drupal/commit/?id=5697af7b0d1c44ba8e104c2cc3a97030813d745c) | [Issue #2186191 by kaare, jiv_e, DamienMcKenna, welly, PascalAnimateur, lussoluca, mErilainen, vijaycs85, paulwdru, zerolab, joep.hendrix, marc.groth, podarok, pmackay, idebr, jastraat, WorldFallz, autopoietic, streever: missing help text](http://drupal.org/node/2186191)
- [ ] #xx | [758d2b42](https://cgit.drupalcode.org/drupal/commit/?id=758d2b42ffa701a7fb03c616d3ea0c4083f19da1) | [Issue #2377623 by Gergely Lekli, qzmenko: Remove unnecessary space in data_combo title](http://drupal.org/node/2377623)

This list generated by 
`git log 7.x-2.10-rc1..7.x-2.10 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`
