### ISSUE TITLE
Merge commits from Date 7.x-2.11-beta1

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4059]
- [ ] #xx | [f3ceae1f](https://cgit.drupalcode.org/drupal/commit/?id=f3ceae1f611d559fd9b9a33e3c66db34893f7c5b) | [Issue #2937071 by DamienMcKenna: Tidy up the CHANGELOG.txt file.](http://drupal.org/node/2937071)
- [ ] #xx | [f55763fc](https://cgit.drupalcode.org/drupal/commit/?id=f55763fc6d6549dc6fd0aa40a1ed79ecffeba714) | [Issue #2514146 by ram4nd: Remove the .gitignore file.](http://drupal.org/node/2514146)
- [ ] #xx | [0c6157fd](https://cgit.drupalcode.org/drupal/commit/?id=0c6157fdfdabb39336c2d028a3987cf27ed13ee5) | [Issue #2533080 by jribeiro, DamienMcKenna, rajeev_drupal, badjava: 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function.](http://drupal.org/node/2533080)
- [ ] #xx | [a2ef9525](https://cgit.drupalcode.org/drupal/commit/?id=a2ef952517f789bfd85659f96a0321a66936661a) | [Issue #2843367 by RemyAroundTown, alesr, joelpittet, DamienMcKenna, oadaeh, ikeigenwijs, johnzzon, Novitsh, matthiasm11, glynster, robertgarrigos, dchatry, szeidler, Majdi, Plazik, NancyDru, nanobyt3: String Offset errors on edit page using PHP 7.1.0.](http://drupal.org/node/2843367)
- [ ] #xx | [b6574516](https://cgit.drupalcode.org/drupal/commit/?id=b6574516aea314840715312414b425efc4863cb2) | [Issue #2889636 by MustangGB, ikeigenwijs, Stevel: Fix PHP 7 tests.](http://drupal.org/node/2889636)
- [ ] #xx | [061d4b3b](https://cgit.drupalcode.org/drupal/commit/?id=061d4b3b0264d67b1ba376939a9e2c7722eb4070) | [Issue #2227903 by DuaelFr, l0ke, leramulina: Problem with filtering dates with "all day" duration](http://drupal.org/node/2227903)
- [ ] #xx | [8f240e7b](https://cgit.drupalcode.org/drupal/commit/?id=8f240e7bbb365376c2dd46390080d54f692e4c16) | [Issue #2503807 by DamienMcKenna: Date Pager position has no effect after updating to Views 3.11](http://drupal.org/node/2503807)
- [ ] #xx | [7003dd0c](https://cgit.drupalcode.org/drupal/commit/?id=7003dd0c86add32d57af89aaf54fcacf656117c6) | [Issue #2995679 by Liam Morland, joseph.olstad: PHP 7.1 no longer converts string to arrays the first time a value is assigned with square bracket notation.](http://drupal.org/node/2995679)
- [ ] #xx | [04c16a3a](https://cgit.drupalcode.org/drupal/commit/?id=04c16a3a54d17b3d2e3419a736ff53ee1965b02d) | [Issue #2889759 by ladybug_3777: Exposed Date Filter - PHP 7 Error](http://drupal.org/node/2889759)
- [ ] #xx | [c805244f](https://cgit.drupalcode.org/drupal/commit/?id=c805244fda1f575d274827be7f03a44f74d30af2) | [Issue #2449261 by daniel_j, pcho, joseph.olstad, David Hernández, collinhaines, vinmassaro, SkyNet Costa Rica: expects an array, not a scalar - Fatal error:  Cannot create references to/from string offsets.](http://drupal.org/node/2449261)
- [ ] #xx | [be333646](https://cgit.drupalcode.org/drupal/commit/?id=be3336462fa02835abd7ccb98bf30d9d083f5d70) | [Issue #1741062 by kim.pepper: The merge method of DateObject class has a wrong parameter type.](http://drupal.org/node/1741062)
- [ ] #xx | [33cf625d](https://cgit.drupalcode.org/drupal/commit/?id=33cf625d8d412b48d79f9c7bcb94580686ab0ac4) | [Issue #2873415 by Squee3P0, jcisio, rujinxero, digitaltodd, fdverwoerd, Stray14: PHP 5.3 - Date field being flagged as Invalid date not actually invalid.](http://drupal.org/node/2873415)
- [ ] #xx | [6ab25f7a](https://cgit.drupalcode.org/drupal/commit/?id=6ab25f7a24564cf83c0edc0438afb66619b9e0b9) | [Issue #2902829 by JayKandari, tucho, nileshlohar, matthiasm11, mr.york, kmonty: Formatter settings for Custom date type is not getting saved.](http://drupal.org/node/2902829)
- [ ] #xx | [4b86a4ed](https://cgit.drupalcode.org/drupal/commit/?id=4b86a4eda0e93ef098c33ad81136b27d944abbda) | [Issue #2208769 by Cracu, bunthorne, jeni_dc, Proteo, Reis Quarteu, echoz: Theme hook not found while managing date field.](http://drupal.org/node/2208769)
- [ ] #xx | [4d439541](https://cgit.drupalcode.org/drupal/commit/?id=4d439541a98763fba543e4c9aa51d16dd26d403c) | [Issue #3002449 by plach: Timezone rendered when theming date formats without time](http://drupal.org/node/3002449)
- [ ] #xx | [b7f4f0fd](https://cgit.drupalcode.org/drupal/commit/?id=b7f4f0fdd50e541de4a1e693010b0289ebb6ea8c) | [Issue #2123039 by Gold, hgoto, DamienMcKenna: Add Entity API as a new test dependency.](http://drupal.org/node/2123039)
- [ ] #xx | [43d22cb4](https://cgit.drupalcode.org/drupal/commit/?id=43d22cb47b9a532c0515d3e0d6bf4b8fd99ab6fc) | [Issue #2123039 by Gold, hgoto, DamienMcKenna, RoSk0, Juterpillar, joachim: Default timezone setting mismatch in metadata wrapper integration.](http://drupal.org/node/2123039)
- [ ] #xx | [df271fbe](https://cgit.drupalcode.org/drupal/commit/?id=df271fbe1e13c689130b6dfb1f02decdd6b08b77) | [Issue #2323857 by anpolimus, DamienMcKenna, claudiu.cristea, catch, joelpittet: date_field_schema() has no index on date.](http://drupal.org/node/2323857)
- [ ] #xx | [355551a7](https://cgit.drupalcode.org/drupal/commit/?id=355551a721b9782e5bcb00d495e79ba7f39c9e42) | [Issue #2016787 by r-mo, DamienMcKenna, joep.hendrix, heddn, julien_g: Change date fields to "big" int values to avoid "PDOException 22003" errors.](http://drupal.org/node/2016787)
- [ ] #xx | [9aec9ede](https://cgit.drupalcode.org/drupal/commit/?id=9aec9ede8571e54b8075c39539c8549774b6aeb4) | [Issue #1137062 by El Alemaño, Nelson Lago, bjcooper, ron_s, ronnienorwood, lunazoid, Michael_Lessard_micles.biz, DamienMcKenna, vinmassaro: Follow-up to fix regression on week calculations.](http://drupal.org/node/1137062)
- [ ] #xx | [5fd1f348](https://cgit.drupalcode.org/drupal/commit/?id=5fd1f3483ccebe6c757a3a99864d19ddc81364e5) | [Issue #1177198 by tim.plunkett, DamienMcKenna, MustangGB, arlinsandbulte, KarenS: Allow CTools to process #dependency for date elements.](http://drupal.org/node/1177198)
- [ ] #xx | [0c839ff8](https://cgit.drupalcode.org/drupal/commit/?id=0c839ff80810d0f25de825e3319565a5568d6988) | [Issue #1778220 by hswong3i, kpyan8s, jacob.embree: Remove version from date_migrate_example.info for better git_deploy integration](http://drupal.org/node/1778220)
- [ ] #xx | [f5d11409](https://cgit.drupalcode.org/drupal/commit/?id=f5d11409fff7ccb86184ba63c5e42f241aa06400) | [Issue #2880395 by DamienMcKenna, jojonaloha, GoZ: Fatal error: DateTimeZone could not be converted to string](http://drupal.org/node/2880395)
- [ ] #xx | [2fba352b](https://cgit.drupalcode.org/drupal/commit/?id=2fba352b526e0e937e6ab0b4e4b10321c2eaa6e0) | [Issue #2100851 by Juterpillar, Drupa1ish, RoSk0, pingwin4eg, acbramley: Date views exposed filter causes SQL error on PostgreSQL.](http://drupal.org/node/2100851)
- [ ] #xx | [7a42ab81](https://cgit.drupalcode.org/drupal/commit/?id=7a42ab81b339c8607fe672aa9f0ac8160e35f12b) | [Issue #2453445 by DamienMcKenna, dan3h, rahul.nahar001: PDOException not handled when using PostgreSQL without timezone support.](http://drupal.org/node/2453445)
- [ ] #xx | [5241ebee](https://cgit.drupalcode.org/drupal/commit/?id=5241ebee769faaa9d7da2b628bbccc3d194aed5b) | [Issue #2204713 by BR0kEN, jstoller, ebeyrent, gaurav.goyal: Undefined index #default_value in date_select_element_process.](http://drupal.org/node/2204713)
- [ ] #xx | [d113587b](https://cgit.drupalcode.org/drupal/commit/?id=d113587b32b00bc769952ad2bff3434debb214b3) | [Issue #2291271 by emek, LoonyLuna, periksson: Datepicker needs dynamic width.](http://drupal.org/node/2291271)
- [ ] #xx | [24338bfc](https://cgit.drupalcode.org/drupal/commit/?id=24338bfcfd710b4362c79ad5e076d4b3e652df1e) | [Issue #2851020 by jacob.embree, nileshlohar, AshwiniPatil, rahul.nahar001, Pranjal.addweb, DamienMcKenna, darshanchoudhary: Use of uppercase for PHP constants.](http://drupal.org/node/2851020)
- [ ] #xx | [e25bbd6c](https://cgit.drupalcode.org/drupal/commit/?id=e25bbd6c254b73fe21a7722cf2d3046f3163a94c) | [Issue #2832257 by danuddara, alexbarrett: Typo error - "The upcoming date less then 1 day" - date.theme.](http://drupal.org/node/2832257)
- [ ] #xx | [82a3d153](https://cgit.drupalcode.org/drupal/commit/?id=82a3d15332dc4f1f2a208c001f06386575388402) | [Issue #2844948 by jiv_e: Notice: Undefined index: tz in date_ical_date().](http://drupal.org/node/2844948)
- [ ] #xx | [a089c8d2](https://cgit.drupalcode.org/drupal/commit/?id=a089c8d2f88fe4c6040028687b02a540f9e952c1) | [Issue #1882432 by DamienMcKenna, lolandese: Improve the module's README.txt files.](http://drupal.org/node/1882432)
- [ ] #xx | [3d8b3dbe](https://cgit.drupalcode.org/drupal/commit/?id=3d8b3dbea02d5d61e75ae4435413d7ad789c2d80) | [Issue #346752 by rreiss, DamienMcKenna: RTL support.](http://drupal.org/node/346752)

this list generated with:
`git log 7.x-2.10..7.x-2.11-beta1 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`
