### ISSUE TITLE
Merge commits from Date 7.x-2.11-beta2

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4060]
- [ ] #xx | [d7823e2e](https://cgit.drupalcode.org/drupal/commit/?id=d7823e2ea1dbb997126c1e3d1ab218be979047aa) | [Issue #3009740 by evgeny.chernyavskiy, DamienMcKenna, steinmb: PHP 7.3 compatibility, swtich-continue.](http://drupal.org/node/3009740)
- [ ] #xx | [5abaa01e](https://cgit.drupalcode.org/drupal/commit/?id=5abaa01e11c3faf18ed7948935dbed0621ccf54d) | [Issue #1267434 by Ronino, DamienMcKenna: Default value for #date_items should be an array in date_field_widget_form().](http://drupal.org/node/1267434)
- [ ] #xx | [9bb27fda](https://cgit.drupalcode.org/drupal/commit/?id=9bb27fdaa69e19e721a7842a46c649503119e9a8) | [Issue #1267434 by Ronino, DamienMcKenna, kingandy: Default value for #date_items should be an array in date_field_widget_form().](http://drupal.org/node/1267434)
- [ ] #xx | [58d7d246](https://cgit.drupalcode.org/drupal/commit/?id=58d7d246e4d2c669d46e9ccce0c9b5289f5542ae) | [Issue #2706965 by DamienMcKenna, arulraj, joelstein: Getting browser autocomplete for date pop fields.](http://drupal.org/node/2706965)
- [x] N/A | [89ba60b6](https://cgit.drupalcode.org/drupal/commit/?id=89ba60b6f4cc00a1090312a707f861ad3eaf030c) | [Revert "Issue #2123039 by Gold, hgoto, DamienMcKenna, RoSk0, Juterpillar, joachim: Default timezone setting mismatch in metadata wrapper integration."](http://drupal.org/node/2123039)
- [ ] #xx | [3839dd90](https://cgit.drupalcode.org/drupal/commit/?id=3839dd904ef940a7ee11b06058e3e25bc4dfd4ea) | [Issue #3010076 by DamienMcKenna, steinmb: Improve coding standards in Date module.](http://drupal.org/node/3010076)
- [ ] #xx | [91707ce1](https://cgit.drupalcode.org/drupal/commit/?id=91707ce163ef2d69e88fa1684904100b6d0019e2) | [Issue #3012729 by joseph.olstad, lazzyvn: Bad variable $elent.](http://drupal.org/node/3012729)
- [ ] #xx | [23e5e1af](https://cgit.drupalcode.org/drupal/commit/?id=23e5e1afa2e1b998c7bd1539a22535303d26889e) | [Issue #2843367 by artem0793, Liam Morland, azovsky: String Offset errors on edit page using PHP 7.1.0.](http://drupal.org/node/2843367)
- [x] N/A | [9d0c38e5](https://cgit.drupalcode.org/drupal/commit/?id=9d0c38e5dc694c7cc60875210a8e8c4f53d44732) | [Issue #1138210 by djdevin, kyoder, coltrane, cafuego, JvE: date_sql_handler STR_TO_DATE math incorrect.](http://drupal.org/node/1138210)
- [x] N/A | [d3034a9f](https://cgit.drupalcode.org/drupal/commit/?id=d3034a9fd9e550572b19a521b387d4fe6163f7dc) | [Revert "Issue #1138210 by djdevin, kyoder, coltrane, cafuego, JvE: date_sql_handler STR_TO_DATE math incorrect."](http://drupal.org/node/1138210)
- [ ] #xx | [65114139](https://cgit.drupalcode.org/drupal/commit/?id=65114139ad5b1a35e545c580410b1f7b83439596) | [Issue #2447277 by SebCorbin, steinmb: Performance: replace sylesheets[all][] with attached](http://drupal.org/node/2447277)
- [ ] #xx | [af189569](https://cgit.drupalcode.org/drupal/commit/?id=af1895698258a3fb9130c259b31992db046cf3ac) | [Issue #2990189 by solotandem, jacob.embree, theaxe, sonnykt: Illegal string offset 'value' in date_combo_element_process.](http://drupal.org/node/2990189)
- [ ] #xx | [77dd88ea](https://cgit.drupalcode.org/drupal/commit/?id=77dd88eac34f2899431526cb3db545de5e468490) | [Issue #2792385 by binoli.addweb, brunodbo, pingwin4eg, joelpittet, DamienMcKenna: Include project namespace in dependency declaration.](http://drupal.org/node/2792385)
- [ ] #xx | [7d4c0b40](https://cgit.drupalcode.org/drupal/commit/?id=7d4c0b40cd98ed8ed479f9e9a63aa18c32afbf88) | [Issue #1138210 by djdevin, kyoder, coltrane, cafuego, JvE: date_sql_handler STR_TO_DATE math incorrect.](http://drupal.org/node/1138210)
- [ ] #xx | [17b88fde](https://cgit.drupalcode.org/drupal/commit/?id=17b88fde2f053910b18626edc1b922594dcf4855) | [Issue #1415210 by jgullstr, nmudgal, ohthehugemanatee, djdevin, asirjacques, christine1126, steinmb, cydharttha, Jelle_S: Date popup calender doesn't popup when reach to text-field via tab.](http://drupal.org/node/1415210)
- [ ] #xx | [59ad05a6](https://cgit.drupalcode.org/drupal/commit/?id=59ad05a69e5e6e26e25d673ca413fff73c4b8829) | [Issue #2894759 by DamienMcKenna, Mansi.AddWeb, hiramanpatil, Michael_Lessard_micles.biz, steinmb: (All Day) : the parantheses are hardcoded.](http://drupal.org/node/2894759)
- [ ] #xx | [b0a9fd17](https://cgit.drupalcode.org/drupal/commit/?id=b0a9fd17a05e125c3c8861eac5ba847b5ee76406) | [Issue #2703401 by jacob.embree, le72, Chris2: Bad assumption about year range format in date_devel_generate().](http://drupal.org/node/2703401)

This list generated with:
`git log 7.x-2.11-beta1..7.x-2.11-beta2 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`
