### ISSUE TITLE
[META] Issues with Basis

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4094]
I have been doing some experiments to determine what a site builder can do with Basis out of the box to style and format their site, without any sub-theme changes and discovering quirks with the Basis theme that frustrate me. Please, add your own here. 

The goal is to improve the out of the box usability of the Basis theme. NOTE: I'm trying to experiment with and fix many of these issues in the [Tatsu contrib](https://backdropcms.org/project/tatsu) theme, which is a sub-theme of Basis.

- [ ] #1844 | In add comment form `comment_body` missing `form-item` class
- [x] #2259 | Basis: issues when used as the admin theme.
- [ ] #2420 | Using Basis as a sub-theme breaks dropdown menu
- [ ] #2653 | Make sure Basis looks and works decently when used as an admin theme.
- [ ] #2689 | Tabledrag hierarchy is broken in Basis
- [ ] #2797 | Basis: Needs styling on Node links like "Read more" and "Comments"
- [ ] #3108 | [UX] Basis: login page tabs wrapping outside their container on mobile portrait mode.
- [ ] #3400 | Basis: Style dropdown menu for sidebar
- [x] #3458 | [UX][DX] Improve the message about theme color.module support.
- [x] #3748 | Remove the hover color from header account links in Basis
- [ ] #3914 | Add a sub-theme starter kit to Basis
- [x] #3982 | Missing width/height in Basis when choosing Use the logo supplied by the active theme
- [ ] #4070 | [UX] Basis: Fix styling of responsive dropdown on smaller screens on RTL
- [x] #4093 | **(RTBC)** Remove the default color change behind the site name 
- [ ] #4095 | Remove white space between two hero blocks placed next to each other
- [ ] #4163 | [META] Basis: ensure HTML5 and CSS3 are valid
- [ ] #4165 | Missing properties from system.theme.css in Basis
- [ ] #4166 | **(Has PR)** Should we set default margins on 'p' tag in Basis?
- [ ] #4201 | CKEditor uses Arial instead of Open Sans in Basis
- [x] #4203 | Add hover-over and focus indication to the delete/edit/reply links for comments
- [x] #4206 | Remove underline from Delete button
- [ ] #4208 | Basis: Update box-sizing method
- [ ] #4384 | Taxonomy terms do not display properly in theme Basis
- [ ] #4415 | Save button is invisible with Goldfish colorset chosen

Major issues:
- [x] #4167 | Decide on best way to make improvements to the CSS for Basis without breaking existing sites
- [x] #4512 | Create interface to add a supplemental stylesheet to Basis - to safely make css updates
