### ISSUE TITLE
Backdrop 1.14.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4133]
Release scheduled for October 13th, 2019 5pm - 7pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@jenlampton)
- [x] Move all unfinished issues to the next bugfix release milestone (@jenlampton)
- [x] Draft Release notes (@jenlampton)
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at `/update.php`) for this release."
  - [x] Include change log since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub (@jenlampton)
- [x] Update the front page download link on b.org (@klonos)
- [x] Tweet that a new release is out (@jenlampton)	

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) (@quicksketch)
- [x] Push the bug-fix release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) (@jenlampton)
- [ ] Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) (@drupol)
- [x] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) (@serundeputy)
- [ ] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) (@quicksketch)
- [x] Update backdropcms.org to use the latest TugBoat (@quicksketch)
- [x] Update the Wikipedia articles (@klonos)
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by jenlampton** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

Update information:

* The database update script does not need to be run.
* No changes have been made to the .htaccess, robots.txt or default settings.php files in this release, so upgrading custom versions of those files is not necessary.

<p>Changes since 1.14.0:</p>
<ul>
  <li>Backdrop 1.14.1</li>
  <li><a href="/node/1828">#1828</a>: [UX] Seven: Fix font-weight for labels inside fieldsets.</li>
  <li><a href="/node/4021">#4021</a>: PHP notice: Trying to get property 'langcode' of non-object in locale_language_url_rewrite_url().</li>
  <li><a href="/node/4048">#4048</a>: Rename Layout Settings page to Layout Templates.</li>
  <li><a href="/node/3720">#3720</a>: Views: Undefined index: current_user.</li>
  <li><a href="/node/3720">#3720</a>: Views RSS feeds have validation issues.</li>
  <li><a href="/node/3720">#3720</a>: Views: Schema mismatch after upgrade D6 to D7/Backdrop.</li>
  <li><a href="/node/3720">#3720</a>: Views: "Content translation: Translations" relationship incorrectly specifying translation source.</li>
  <li>Views: Expand display "Comment" trim from 10 to 80 characters (<a href="/node/2653">#2653</a>)</li>
  <li><a href="/node/3720">#3720</a>: Views: Document field_math feature previous value.</li>
  <li><a href="/node/3720">#3720</a>: view_menu_alter() adding to existing "access arguments" causes user_access() error.</li>
  <li><a href="/node/3720">#3720</a>: Views: Set a default template if there is no theme definition.</li>
  <li><a href="/node/3720">#3720</a>: Views: Fix some typos in comments.</li>
  <li><a href="/node/3720">#3720</a>: Check for entity in views_handler_field_field->get_value() before accessing it.</li>
  <li><a href="/node/3720">#3720</a>: Incorrect array index given in example for hook_views_ajax_data_alter().</li>
  <li><a href="/node/3720">#3720</a>: Views: Undefined index: help topic in views_plugin_display->options_form().</li>
  <li><a href="/node/3720">#3720</a>: Views: Issue tag 'is/not empty' and 'not one of' operators do not work. (<a href="/node/2666">#2666</a>)</li>
  <li>Views: Fatal error: Call to a member function ensure_my_table() on a non-object (<a href="/node/2667">#2667</a>)</li>
  <li><a href="/node/4066">#4066</a> - Adding l-header and l-footer classes to flexible layout templates.</li>
  <li><a href="/node/3614">#3614</a>: Fix broken is-one-of views filter.</li>
  <li><a href="/node/4071">#4071</a>: Fix broken block descriptions too strictly escaped after SA-CORE-2019-011-013.</li>
  <li><a href="/node/4085">#4085</a>: Increase maxlength of Allowed File Extensions field.</li>
  <li><a href="/node/4103">#4103</a>: Check before and after file_delete() to show metadata is really deleted.</li>
  <li>Reverting version string.</li>
</ul>
