### ISSUE TITLE
[META][UX] Content translation improvements 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4198]
> I'd love to hear more use-cases where people feel they are hitting the limits of what content translation supports. I've pulled a few things out of the above comment thread and added them to this new issue for 1.x. But let's keep adding things.

Considerations for improvements in 1.x:

- [ ] #?? | Don't separate comment threads between languages, but allow comments to be filtered by language
- [ ] #?? | Provide a UI for each node type to define fields that shouldn't be translated
- [ ] #?? | A view with a (translated) tid or nid as a contextual filter - want just one view for all languages (proposed solution: global context that will "translate" the filter value before passing to views or layouts)
- [ ] #?? | Term (and other) references will need to maintain their mappings from translated node to translated term. (proposed solution: global context?)
- [ ] #?? | Add better translation support to core entity API. maybe a `->getTranslated()` or similar methods for developers. Look to Entity API in D7 contrib for examples. 

This issue is a spin-off from https://github.com/backdrop/backdrop-issues/issues/52

**Comment by mazzech** [comment]
`Provide a UI for each node type to define fields that shouldn't be translated`
++
