### ISSUE TITLE
Drupal 7.33 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#420]
- [x] | https://github.com/backdrop/backdrop/pull/565 | [b558549](http://drupalcode.org/project/drupal.git/commit/b5585495b9ae8768d3cbb91afd76afebeb31050d) | [Issue #2318981 by grisendo: Make hook_node_grants and hook_node_access_records sample function bodies consistent](http://drupal.org/node/2318981)
- [x] | https://github.com/backdrop/backdrop/pull/558 | [8af676d](http://drupalcode.org/project/drupal.git/commit/8af676d68440e4909eb9f42a4a0189a266f2191a) | [Issue #2324083 by er.pushpinderrana, martin_q: Fix up description of return value from drupal_array_get_nested_value()](http://drupal.org/node/2324083)
- [x] | https://github.com/backdrop/backdrop/pull/558 | [29a0dc3](http://drupalcode.org/project/drupal.git/commit/29a0dc349bf1ec8251cccc4e561eabcaccde038b) | [Issue #993186 by joshi.rohit100, moshe weitzman | webchick: Node access rebuilds should go newest to oldest (fix for direct node access rebuilds only, not rebuilds done via a batch).](http://drupal.org/node/993186)
- [x] | https://github.com/backdrop/backdrop/pull/557 | [99c124d](http://drupalcode.org/project/drupal.git/commit/99c124d4d4c86d2cd2a9dc65d71632bc0dd98c1a) | [Issue #1468210 by marthinal, quicksketch, tstoeckler, Devin Carlson, David_Rothstein, Eric_A: Fixed Remove special $user->uid == 1 check in file_validate_size().](http://drupal.org/node/1468210)
- [x] | N/A | [0867207](http://drupalcode.org/project/drupal.git/commit/0867207af614d7f416dc81548a832f68fc533b7b) | [Issue #1890980 by amitgoyal, robinvdvleuten: Fixed Unnecessary extra output variable in theme_links.](http://drupal.org/node/1890980)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [be54be0](http://drupalcode.org/project/drupal.git/commit/be54be0d14db49f655f610bda8d365c7e1c88fc0) | [Issue #1859084 by Jorrit, David_Rothstein, attiks: Improved database queries generated by EntityFieldQuery in the case where delta or language condition groups are used, to reduce the number of INNER JOINs.](http://drupal.org/node/1859084)
- [x] | https://github.com/backdrop/backdrop/pull/565 | [2200030](http://drupalcode.org/project/drupal.git/commit/22000303106e6428df331bc98da773d49fa6cec7) | [Issue #2277281 by dobe, amitgoyal, michaelfavia, er.pushpinderrana, dcam | drumm: Increase the maximum number of characters on the file field allowed extensions setting from 128 to 256.](http://drupal.org/node/2277281)
- [x] | https://github.com/backdrop/backdrop/pull/565 | [8a6142a](http://drupalcode.org/project/drupal.git/commit/8a6142a83dc826972a2319825545da814f484e04) | [Issue #1166114 by jhodgdon, tomogden, Rajendar Reddy, larowlan, swentel, splatio, erics14, MF82 | RobLoach: Renamed the "Search result" view mode to "Search result highlighting input" to better reflect how it is used.](http://drupal.org/node/1166114)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [3bd008b](http://drupalcode.org/project/drupal.git/commit/3bd008b0319c98fad591ab5d175889df8033a519) | [Issue #2334689 by er.pushpinderrana, joachim: Document character limit on lock_aquire() for lock name](http://drupal.org/node/2334689)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [5b99e31](http://drupalcode.org/project/drupal.git/commit/5b99e319cd7614512de69b32974cc96b6f7e98ee) | [Issue #2314181 by roderik, er.pushpinderrana, hefox: Fix docs for drupal_static](http://drupal.org/node/2314181)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [8d1e516](http://drupalcode.org/project/drupal.git/commit/8d1e5167f6b40177732f37ce693a189ab6f49021) | [Issue #2340675 by er.pushpinderrana, David Hernández: Clarify first, unused argument docs in update_calculate_project_update_status()](http://drupal.org/node/2340675)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [f2c8d95](http://drupalcode.org/project/drupal.git/commit/f2c8d9550ec95b207dde99f45050b81337ae0065) | [Issue #2283675 by er.pushpinderrana, amitgoyal, mparker17, joachim, mmarquez: Document how optgroups are generated in form_select_options()](http://drupal.org/node/2283675)
- [x] | N/A | [131a6f5](http://drupalcode.org/project/drupal.git/commit/131a6f5129b18f3913ba5882111797f8588c5aaf) | Drupal 7.32 Tag
- [x] | https://github.com/backdrop/backdrop/pull/621 | [57236b0](http://drupalcode.org/project/drupal.git/commit/57236b056f8785137d27f6f5ba99a40127dc1c51) | [Issue #2329189 by nlisgo, joachim, Mirroar, opdavies: Fix up docs and example code for hook_field_attach_validate()](http://drupal.org/node/2329189)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [4a93ebd](http://drupalcode.org/project/drupal.git/commit/4a93ebd89d77e3bc850059cdc1923c364042331f) | [Issue #667098 by catch, chx, plach, Fabianx: Fixed a bug which caused drupal_get_bootstrap_phase() to abort the bootstrap when called early in the page request.](http://drupal.org/node/667098)
- [x] | https://github.com/backdrop/backdrop/pull/608 | [5f380f9](http://drupalcode.org/project/drupal.git/commit/5f380f922531255efe95ee443606379dcac2fc9e) | [Issue #2332295 by sanduhrs, klausi, er.pushpinderrana, Berdir | jfha73: Fixed Unicode requirements check not working with PHP 5.6.](http://drupal.org/node/2332295)
- [x] | N/A | [fa2e36b](http://drupalcode.org/project/drupal.git/commit/fa2e36b863eecea32852d3a7f374680736c87732) | [Issue #2301955 by er.pushpinderrana, lokapujya | scor: Ensure RDFa metadata tags are hidden.](http://drupal.org/node/2301955)
- [x] | N/A | [4d5a0ad](http://drupalcode.org/project/drupal.git/commit/4d5a0ad301544ad3ba4dcc6d7f29c513e29d884e) | [Issue #1323830 by cwells, scor, mgifford, er.pushpinderrana, kay_v: Place title RDFa metadata inside entity HTML element.](http://drupal.org/node/1323830)
- [x] | N/A | [3a4f085](http://drupalcode.org/project/drupal.git/commit/3a4f085dfbf48a12d364b3aa80d0ecd336eb23e9) | [Issue #2130673 by lokapujya, cwells | scor: Place number of comments metadata inside node template.](http://drupal.org/node/2130673)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [6b7514a](http://drupalcode.org/project/drupal.git/commit/6b7514afd2f03f3543d7c84e77cc97fa1d84dbb4) | [Issue #829464 by Berdir, klausi, sepgil | Heine: Fixed orderby() should verify that the sort direction is always ASC or DESC.](http://drupal.org/node/829464)
- [x] | N/A | [ac66040](http://drupalcode.org/project/drupal.git/commit/ac660408ac20201a871e9b816d19e75385980936) | [Issue #2291081 by pounard: forum_node_view attempt an unnecessary vocabulary_load() under certain circumstances.](http://drupal.org/node/2291081)
- [x] | N/A | [e9bca3a](http://drupalcode.org/project/drupal.git/commit/e9bca3a0c23b5230fb3c73280f413bb5169eb4a3) | [Issue #1182374 by lyricnz, xendil, sivaji, brianV: Code style fixes for includes/filetransfer.](http://drupal.org/node/1182374)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [62c952c](http://drupalcode.org/project/drupal.git/commit/62c952c6e4cad7ac18ee8aea6791f4f0d1117231) | [Issue #1183708 by Liam Morland | onair1: Fixed Notice: Undefined index: favicon_path in system_theme_settings_validate().](http://drupal.org/node/1183708)
- [x] | https://github.com/backdrop/backdrop/pull/621 | [d5945c1](http://drupalcode.org/project/drupal.git/commit/d5945c1c062bf8ef67c03cfb8681b312c59312e3) | [Issue #208611 by p.brouwers, mgifford, tstoeckler, DougKress, Jody Lynn, ksenzee | walkah: Made the Ajax system use drupal_array_merge_deep_array() to stop JavaScript settings from being added twice.](http://drupal.org/node/208611)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [5aede0d](http://drupalcode.org/project/drupal.git/commit/5aede0dadeb785ca30f5e16c6d67281286a047ee) | [Issue #1936942 by jweowu: Fixed translation_node_insert() updates the node table directly without also flushing the entity load cache.](http://drupal.org/node/1936942)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [c312e5e](http://drupalcode.org/project/drupal.git/commit/c312e5ee5589d060601f633deba3be26df494815) | [Issue #1968348 by znerol, David_Rothstein, peximo, DuaelFr: Fixed hook_field_formatter_prepare_view does not make use of hook_entity_view_mode_alter causing major errors.](http://drupal.org/node/1968348)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [4443a30](http://drupalcode.org/project/drupal.git/commit/4443a3070b80971e636c7ef5ba0fbb5ebfc8d024) | [Issue #2307505 by Cottser, Fabianx: Port twig_debug output to Drupal 7.](http://drupal.org/node/2307505)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [d1a4193](http://drupalcode.org/project/drupal.git/commit/d1a41934107ebcffe11ccff6d423b3390364ba0b) | [Issue #1988456 by gaurav.goyal, eltermann, pvmchau: Non-standard indentation on user_register_form().](http://drupal.org/node/1988456)
- [x] | N/A | [71651db](http://drupalcode.org/project/drupal.git/commit/71651dbf4f0f9f0e3169e3beb9b89f9037f5c13e) | [Issue #28175 by dcam, bleen18 | bertboerland: Fixed Ordering by 'Visitor' in access log pages does not sort IP addresses.](http://drupal.org/node/28175)
- [x] | N/A | [e052539](http://drupalcode.org/project/drupal.git/commit/e052539654ea7f475c9359ebaf9b0be066522d18) | [Issue #2224917 by m1r1k, Steven Jones, drumm: Fixed Tracker page doesn't order results properly.](http://drupal.org/node/2224917)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [0e3d0be](http://drupalcode.org/project/drupal.git/commit/0e3d0beddbdd170165666af4451c088a0eb330d2) | [Issue #1790612 by carwin, Eric_A, mgifford: Fixed Sanitize the trim_length variable before printing it.](http://drupal.org/node/1790612)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [6b47cbf](http://drupalcode.org/project/drupal.git/commit/6b47cbf7d0aa4b0ad3b249a3e16d023fac0b140a) | [Issue #205969 by Mile23, oadaeh, twistor, ssm2017 Binder, barraponto, superspring: Fixed backdrop_http_request() assumes presence of Reason-Phrase in response Status-Line.](http://drupal.org/node/205969)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [49a51c7](http://drupalcode.org/project/drupal.git/commit/49a51c70b8dc6417999ed1b99bcae3bcb58a6449) | [Issue #1452896 by Mile23, marthinal, Freso, kid_icarus, joshi.rohit100, alexpott, tim.plunkett, jhodgdon: Fixed PHP notice in clickLink if link does not exist.](http://drupal.org/node/1452896)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [a0561f8](http://drupalcode.org/project/drupal.git/commit/a0561f83ea19176258c654a77e132740a01bf08b) | [Issue #2231693 by helmo, amitgoyal, joshi.rohit100, LinL, iS: Update Powered by Drupal link.](http://drupal.org/node/2231693)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [ea1c7a9](http://drupalcode.org/project/drupal.git/commit/ea1c7a94418526cf2298dcd6011a5995e626f3d5) | [Issue #1120440 by er.pushpinderrana | skwashd: Fixed user.api.php hook summary lines should be more consistent with other entity hooks.](http://drupal.org/node/1120440)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [90687ab](http://drupalcode.org/project/drupal.git/commit/90687ab52679427a3889d45c747fb401bc419294) | [Issue #780304 by dcam, naxoc, Crell | zyxware: Fixed HTML encoding of em wrappers for database table names while showing schema errors.](http://drupal.org/node/780304)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [a28e032](http://drupalcode.org/project/drupal.git/commit/a28e032e503943230ef99822fe63af0a8e99af5f) | [Issue #1891728 by gielfeldt: Fixed Database schema methods like getComment() and findTables() always query the "default" target on MySQL.](http://drupal.org/node/1891728)
- [x] | N/A | [c95d725](http://drupalcode.org/project/drupal.git/commit/c95d72521d31ff2ae4f843979f4ab5a39e633300) | [Issue #2228825 by donquixote | pingwin4eg: Fixed drupal_get_filename() does not search the filesystem when the file isn't yet listed in the {system} table in the database.](http://drupal.org/node/2228825)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [c684532](http://drupalcode.org/project/drupal.git/commit/c684532504121f6342ed4ae97951dc7034dfb82b) | [Issue #1099732 by joshi.rohit100, droplet | Chi: Fixed Incorrect encoding for error pages in image_style_deliver().](http://drupal.org/node/1099732)
- [x] | https://github.com/backdrop/backdrop/pull/622 | [90d6f05](http://drupalcode.org/project/drupal.git/commit/90d6f05facedd14e6abf39b86bddff5ae1320eed) | [Issue #1679570 by mgifford, lucascaro, sun: Fixed TestBase does not always use the correct database connection for handling assertions.](http://drupal.org/node/1679570)
- [x] | N/A | [417fae5](http://drupalcode.org/project/drupal.git/commit/417fae5b2547d3b27071eab5cd0f23356956b176) | [Issue #1775488 by mgifford, vijaycs85, amateescu | chx: Fixed drupal_cron_cleanup is not converted to lock.](http://drupal.org/node/1775488)
- [x] | N/A | [8d5c1bf](http://drupalcode.org/project/drupal.git/commit/8d5c1bf0220a687c36467c0c311abc341589c517) | [Issue #366152 by Mile23, bjaspan: Removed the Field module's field_modules_uninstalled() function, since it did not do anything when it was invoked.](http://drupal.org/node/366152)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [f68c6ce](http://drupalcode.org/project/drupal.git/commit/f68c6ce8495dbdf396676da1e323339b725b0d13) | [Issue #466576 by gagarine, jackbravo, tim.plunkett, sheise, Rob C, jamesm6162 | daemon: Increased the maximum allowed length of block titles to 255 characters.](http://drupal.org/node/466576)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [bc7940a](http://drupalcode.org/project/drupal.git/commit/bc7940aa6a876eeaaa301f54747091166f995b09) | [Issue #2058761 by kirby14, thedavidmeister: PHP notice when #attributes is not set with #theme_wrappers 'container'.](http://drupal.org/node/2058761)
- [x] | N/A | [a6d70dd](http://drupalcode.org/project/drupal.git/commit/a6d70ddfbbe4c9713d67a93cf5b0548e42ce6b7c) | [Issue #908822 by jmking, asimmonds | salvis: Fixed Dashboard discards <em class="placeholder"> elements.](http://drupal.org/node/908822)
- [x] | N/A | [433fe74](http://drupalcode.org/project/drupal.git/commit/433fe74a8181189fc825d5d4ae43216c6eed71f2) | [Issue #1221772 by pounard, colan, jcisio | sivaji: Fixed Transaction database settings is misleading in settings.php.](http://drupal.org/node/1221772)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [56e257d](http://drupalcode.org/project/drupal.git/commit/56e257d57db9de0a1d874e3fd3c1a259d824968f) | [Issue #1854134 by EtienneRd, jeffam | dolu: Added a query tag to the query in menu_link_get_preferred() to allow modules to alter the query.](http://drupal.org/node/1854134)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [2a4f67c](http://drupalcode.org/project/drupal.git/commit/2a4f67cdc54a35c17b7d75e16858f236986cd8b4) | [Issue #1824820 by crevillo, muriqui, a.milkovsky, Phizes: Fixed String offset cast notice in field_invoke_method_multiple().](http://drupal.org/node/1824820)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [355446d](http://drupalcode.org/project/drupal.git/commit/355446db94f4ad4e0a75f22e00d12f524a2807d4) | [Issue #1195358 by Liam Morland, droplet: Fixed Multiple "Edit/Hide summary" links appear.](http://drupal.org/node/1195358)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [2e235b5](http://drupalcode.org/project/drupal.git/commit/2e235b51529b76c93930d1d2c84170d7d3064ba6) | [Issue #849624 by brad.bulger, dcam, Alan Evans, oriol_e9g, Stevel | tsvenson: Fixed wrong permission for admin/structure/menu/parents.](http://drupal.org/node/849624)
- [x] | https://github.com/backdrop/backdrop/pull/625 | [766312e](http://drupalcode.org/project/drupal.git/commit/766312e23cfe2f7e4fc12ef9c4d332757f3b9a5f) | [Issue #1640404 by er.pushpinderrana, dcam, amit.drupal, hass | versvs: Fixed Use format_username() in node_feed().](http://drupal.org/node/1640404)
- [x] | N/A | [010a9a5](http://drupalcode.org/project/drupal.git/commit/010a9a54e74f7762e17591cb16881ae16637ef7d) | [Issue #2324821 by rpayanm, er.pushpinderrana | Elijah Lynn: Remove reference to nonexistent theme_poll_bar() function in template_preprocess_poll_bar() documentation.](http://drupal.org/node/2324821)
- [x] | N/A | [0c8dc6e](http://drupalcode.org/project/drupal.git/commit/0c8dc6ea062cd7595a7b6fbd02fb0f0294ccecef) | [Issue #1823906 by joshi.rohit100, amitgoyal, rahulbile | gargsuchi: Fixed Incorrect error message when poll is submitted with no option selected.](http://drupal.org/node/1823906)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [62e874b](http://drupalcode.org/project/drupal.git/commit/62e874b348fe64490952a12f419164e26ea98d21) | [Issue #1071818 by JeremyFrench, nod_, Cottser, gielfeldt, xjm, anthbel, reglogge, NROTC_Webmaster, kristofferwiklund, lliss, sun | sepgil: Fixed Lazy-loading CSS fails in IE.](http://drupal.org/node/1071818)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [9ebc7af](http://drupalcode.org/project/drupal.git/commit/9ebc7af3c50368e899f028320ea752a0885642d5) | [Issue #1913958 by hass, YesCT: Fixed Bartik theme shouldn't change capitalization of translatable strings with CSS.](http://drupal.org/node/1913958)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [f7cf579](http://drupalcode.org/project/drupal.git/commit/f7cf579dfb85ffb21f7870ef1c73aec4147127f9) | [Issue #1069152 by droplet, alexandrezia, Mixologic, jhedstrom | ogi: Fixed Throbber in textfield is often misaligned.](http://drupal.org/node/1069152)
- [x] | N/A | [0b4c3b1](http://drupalcode.org/project/drupal.git/commit/0b4c3b17e2209b1804a7b6b5974e5217c3e2a87e) | [Issue #2357311 by penyaskito: Fixed Follow-up to SA-CORE-2014-005 (tests don't work correctly on non-MySQL databases).](http://drupal.org/node/2357311)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [c401ec3](http://drupalcode.org/project/drupal.git/commit/c401ec33e847ec2710ef6914625ca63a3e5663b4) | [Issue #2112247 by sihv, mitsuroseba, dgroene, aalamaki, Dennis Walgaard, mErilainen: Fixed Valid file extensions in file names are not properly enforced when uploading files with non-lowercase names.](http://drupal.org/node/2112247)
- [x] | N/A | [af4cde1](http://drupalcode.org/project/drupal.git/commit/af4cde1b8fc393c16051ffc275acf94371c68236) | [Issue #2193149 by mikeytown2: Fixed Deadlocks occur in cache_field table.](http://drupal.org/node/2193149)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [c2b05dd](http://drupalcode.org/project/drupal.git/commit/c2b05dd9c0109b8d417c8140883e1808400f0503) | [Issue #2142441 by Garrett Albright: Fixed CSS aggregator prepends data: URLs with paths.](http://drupal.org/node/2142441)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [f609f39](http://drupalcode.org/project/drupal.git/commit/f609f390af91ccbad813134d0eb0b054e85dc1c5) | [Issue #1231710 by cs_shadow, Hydra, dcam, kathyh, klausi, mlncn: Fixed Field exceptions should return the name of the field that has exceptions.](http://drupal.org/node/1231710)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [8cf521c](http://drupalcode.org/project/drupal.git/commit/8cf521c61c62a30d3d2636502f70e6ea26d3200a) | [Issue #1443070 by CrashTest_, bluegriff | Dave Reid: Added support for popular e-book formats, Google web formats, mkv and mka in file_default_mimetype_mapping().](http://drupal.org/node/1443070)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [e7b2772](http://drupalcode.org/project/drupal.git/commit/e7b2772c2583c36b506627bf86aaf3a51b34f9a0) | [Issue #2278583 by nlisgo, Berdir, joshi.rohit100 | Fabianx: Fixed field_has_data looks at current data instead of revisioning data: this can lead to data loss.](http://drupal.org/node/2278583)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [d7ea3ba](http://drupalcode.org/project/drupal.git/commit/d7ea3ba5994c5a4d69bd5661972637d094536b99) | [Issue #2356055 by bdlangton: Fixed Notice in includes/mail.inc define.](http://drupal.org/node/2356055)
- [x] | https://github.com/backdrop/backdrop/pull/631 | [037848a](http://drupalcode.org/project/drupal.git/commit/037848ad555fd5fe7fad45df5e720f03eaf8df04) | [Issue #935592 by pillarsdotnet, lokapujya, David_Rothstein, John Franklin, amitgoyal, joshi.rohit100, sivaji, mgifford, peximo, wodenx, Romlam, Owen Barton, alpritt, beejeebus | macgirvin: Fixed User picture is deleted after calls to user_save().](http://drupal.org/node/935592)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [1b82c57](http://drupalcode.org/project/drupal.git/commit/1b82c570504697f024cabba52fd34040d93ff19d) | [Issue #1433288 by haggins, fago, David_Rothstein, marcin.wosinek: Fixed Integrity constraint violation when saving a user account after creation.](http://drupal.org/node/1433288)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [c8a26f2](http://drupalcode.org/project/drupal.git/commit/c8a26f2d06a54b80a491d658c437846251d0d5e6) | [Issue #927138 by manarth, handrus, rasmusluckow, douggreen, .John, Taz, David_Rothstein, droplet, webchick, marcingy: Fail image generation with 404 instead of 500 when source file is missing.](http://drupal.org/node/927138)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [d6c5029](http://drupalcode.org/project/drupal.git/commit/d6c502926e1286e22771c58e01db386ba80d6480) | [Issue #779374 by helmo, joshi.rohit100, meba, sun | coltrane: Fixed XSS via text format names.](http://drupal.org/node/779374)
- [x] | N/A | [9559160](http://drupalcode.org/project/drupal.git/commit/9559160204f1c4e72e145cf95d61bf61e4bd1fcf) | [Issue #1930960 by pounard, iamEAP, pjcdawkins, msonnabaum, David_Rothstein: Fixed Block caching disable hardcoded on sites with hook_node_grant() causes serious performance troubles when not necessary.](http://drupal.org/node/1930960)
- [x] | N/A | [b09c678](http://drupalcode.org/project/drupal.git/commit/b09c6788a60b200234efec2ce6310a1583fa4cb3) | [Issue #863594 by David_Rothstein, smussbach, mbrett5062: Fixed Strange first paragraph in the installer database error message.](http://drupal.org/node/863594)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [af79dc0](http://drupalcode.org/project/drupal.git/commit/af79dc0b60cd8e1af7f6515fc23a52d0d29924b3) | [Issue #1069152 by droplet, alexandrezia, Mixologic, jhedstrom, David_Rothstein | ogi: Fixed Throbber in textfield is misaligned when browser hardware acceleration enabled (followup for Bartik RTL styling).](http://drupal.org/node/1069152)
- [x] | N/A | [ebf478b](http://drupalcode.org/project/drupal.git/commit/ebf478b5af00163c15e92ffca779b26479785a84) | [Issue #1338966 by geerlingguy, loganfsmyth, lokapujya: Fixed Introduce _rdf_mapping_load_multiple to reduce queries.](http://drupal.org/node/1338966)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [b73583f](http://drupalcode.org/project/drupal.git/commit/b73583ffb3274f7f7561cae5bc45db2890a3cc25) | [Issue #393538 by Liam Morland, valthebald, dmitrig01, David_Rothstein: Document that check_plain() can issue PHP messages on invalid UTF-8 input.](http://drupal.org/node/393538)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [cd38268](http://drupalcode.org/project/drupal.git/commit/cd3826875558cf9cf6faf0a797f9a468e43b44d8) | [Issue #2310415 by cilefen, ednawig, TravisCarden: Fixed run-tests.sh does not handle the error when invalid test groups/classes are specified.](http://drupal.org/node/2310415)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [6cf3889](http://drupalcode.org/project/drupal.git/commit/6cf3889e1dc5aa69ee00bea969725d164c4b2b26) | [Issue #2147321 by manfer: Fixed Unnecessary space in session-active class.](http://drupal.org/node/2147321)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [2e906b8](http://drupalcode.org/project/drupal.git/commit/2e906b8d706461f2a65b05fbe8505ccdff562c13) | [Issue #2282541 by Mark Carver | gge: Fixed Hide summary in text.js not working in jQuery 1.9+.](http://drupal.org/node/2282541)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [35e7cb1](http://drupalcode.org/project/drupal.git/commit/35e7cb17865a0d524b500c9318197bcf89f2ae60) | [Issue #892344 by amitgoyal, tstoeckler, hussainweb, pcambra, LaurentAjdnik: Fixed Wrong schema description for {cache_field}.](http://drupal.org/node/892344)
- [x] | https://github.com/backdrop/backdrop/pull/673 | [c990cd6](http://drupalcode.org/project/drupal.git/commit/c990cd6bf3e409fa65bbe885dbafd7afa5144848) | [Issue #1355526 by cafuego, jenlampton: Added a way to determine the date a module was added so the modules page can use it for sort.](http://drupal.org/node/1355526)
- [x] | N/A | [0091b69](http://drupalcode.org/project/drupal.git/commit/0091b69893afe3e3c9bb0652db19b41f5f796354) | [Issue #2305291 by scor: Fixed Poll title should have same length as regular content type (255).](http://drupal.org/node/2305291)
- [x] | N/A | [abb166c](http://drupalcode.org/project/drupal.git/commit/abb166c0b246450989c375978502f1827331421a) | Various updates to CHANGELOG.txt in preparation for the 7.33 release.
- [x] | https://github.com/backdrop/backdrop/pull/673  | [86a1ebe](http://drupalcode.org/project/drupal.git/commit/86a1ebefd3073713e795035c5bc0b0d1024a2189) | [Issue #2307505 by Cottser, David_Rothstein, Fabianx: Followup to ensure all theme debug output is properly sanitized.](http://drupal.org/node/2307505)
- [x] | N/A | [caff8dd](http://drupalcode.org/project/drupal.git/commit/caff8dd434b15cc1e1d739dfd35dff52238d17ff) | Added issue #2310415 to CHANGELOG.txt.

Follow-up issues
- https://github.com/backdrop/backdrop-issues/issues/583 | [df8de73](http://drupalcode.org/project/drupal.git/commit/df8de735c3b998af03fc34c493661e2f7c4019b0) | [Issue #1918820 by neclimdul, typhonius, girishmuraly, pwolanin | 0x534B41: Fixed HTTP header date formats to follow RFC 7231 rather than RFC 1123.](http://drupal.org/node/1918820)

The command for generating this list was: 
``git log b558549.. --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"``

where the commit ``b558549`` is the starting point.

**Comment by quicksketch** [comment]
Merged the first set from https://github.com/backdrop/backdrop/issues/621. Thanks @jenlampton!

**Comment by quicksketch** [comment]
Another couple PRs merged from https://github.com/backdrop/backdrop/issues/625 and https://github.com/backdrop/backdrop/issues/661. 16 left to go, though I'm not sure many of them actually apply to Backdrop.

**Comment by jenlampton** [comment]
12 apply. Final PR filed.

**Comment by quicksketch** [comment]
Filed a new replacement PR at https://github.com/backdrop/backdrop/pull/673, this should get the rest of them now.

**Comment by quicksketch** [comment]
Yay, tests passed and we're merged with the last set. Thanks!
