### ISSUE TITLE
Backdrop 1.14.2 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#4243]
Release scheduled for December 18, 2019 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create the next bugfix milestone @klonos
- [x] Move all unfinished issues to the next bugfix release milestone @klonos
- [x] Draft Release notes @jenlampton
  - [x] Short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Note if any changes were made to files outside the `core` directory, for example:
    - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.
  - [x] Note if updates (update.php) needs to be run, for example:
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)

If this is a security release:
- [x] Draft Security Advisories @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @jenlampton
- [x] Update the front page download link on b.org @klonos
- [x] Tweet that a new release is out @jenlampton

If this is a security release:
- [x] Publish Security Advisories on b.org @klonos
- [x] Mark the release node on b.org as a security release @klonos
- [x] We should [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) @jenlampton

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch
- [x] Push the bug-fix release to the [Platform.sh Backdrop repository](https://github.com/platformsh/platformsh-example-backdrop) @jenlampton
- [x] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch
- [ ] Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @drupol
- [ ] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) @serundeputy
- [x] Update the Wikipedia articles @klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

If this is a security release:
- [x] Update the Security Advisory with CVE @jenlampton

## Backdrop Website updates

- [x] backdropcms.org @jenlampton
- [x] api.backdropcms.org @jenlampton
- [x] forum.backdropcms.org @jenlampton

**Comment by quicksketch** [comment]
And https://github.com/backdrop/backdrop/releases/tag/1.14.2 is ready to go.

**Comment by jenlampton** [comment]
Release notes draft

---

Maintenance release for Backdrop CMS. This update contains only security updates.

<p><strong>Update information:</strong></p>
<ul>
<li>The database update script does not need to be run.</li>
<li>No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.</li>
</ul>

<p>Changes since 1.14.1:</p>
<ul>
  <li>Fix symlink and path traversal issues in ArchiveTar.</li>
  <li>Escape descriptions for file types.</li>
  <li>Check config archives contain allowable files before import.</li>
  <li>Escape HTML in node type names.</li>
  <li>Filter admin block titles and descriptions.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4214">#4214</a>: Capitalize "Reply-To" header.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4221">#4221</a>: Hide help text for min resolution if there is no limit set.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4231">#4231</a>: Prevent all tabelselect tables on a page from responding to any "Select all" checkbox.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4202">#4202</a>: Fix documented path to maintenance mode page.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4216">#4216</a>: Allow empty max value for number fields.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4193">#4193</a>: Set `file_temporary_path` in initial `system.core.json` file.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4093">#4093</a>: Remove the default color change behind the site name in Basis.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4180">#4180</a>: Fix broken test at midnight in testing timezone.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4135">#4135</a>: Remove the hash at the beginning of lines in favor of our inline PHP comment indicator.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4136">#4136</a>: Delete backup file for `flexible_template.png`.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4178">#4178</a>: Standardize on label for file description text.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2052">#2052</a>: Let File delete files whether they exist or not.</li>
</ul>

**Comment by jenlampton** [comment]
Requested 4 CVEs.

**Comment by jenlampton** [comment]
PR filed for platform.sh: https://github.com/platformsh/template-builder/issues/182

**Comment by jenlampton** [comment]
@Druopl and @serundeputy the last to items here are on your lists.

**Comment by jenlampton** [comment]
Closing this issue in favor of https://github.com/backdrop/backdrop-issues/issues/4274
