### ISSUE TITLE
Backdrop 1.13.5 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#4244]
Release scheduled for December 18, 2019 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits 
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Note if any changes were made to files outside the `core` directory, for example:
    - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.
  - [x] Note if updates (update.php) needs to be run, for example:
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)

If this is a security release:
- [x] Draft Security Advisories @jenlampton / @klonos 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @jenlampton 

If this is a security release:
- [x] Mark the release node on b.org as a security release @klonos 

See also: https://github.com/backdrop/backdrop-issues/issues/4243

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.13.5 is cut and ready to go.

**Comment by jenlampton** [comment]
Release notes:

Maintenance release for Backdrop CMS. This update contains security updates, bug fixes, and usability improvements only.

<p><strong>Update information:</strong></p>
<ul>
<li>The database update script does not need to be run.</li>
<li>No changes have been made to the .htaccess, robots.txt or default settings.php files in this release, so upgrading custom versions of those files is not necessary.</li>
</ul>

<p><strong>Changes since 1.13.4:</strong></p>
<ul>
  <li>Fix symlink and path traversal issues in ArchiveTar.</li>
  <li>Check config archives contain allowable files before import.</li>
  <li>Escape HTML in node type names.</li>
  <li>Filter admin block titles and descriptions.</li>
</ul>

**Comment by klonos** [comment]
All done here. Closing...
