### ISSUE TITLE
Backdrop 1.15.0 Preview Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4250]
Scheduled for January 1st, 2020 10pm - 11:59pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create a new minor release milestone @jenlampton 
- [x] Move all unfinished issues to the next minor release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release
  - [x] Include list of major new features

## Pre-release Publicity + documentation tasks

- [ ] Draft blog post for 1/15 release @stpaultim
- [ ] Draft roadmap updates for backdropcms.org @klonos 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub @jenlampton 

## Post-release Publicity + documentation tasks

- [ ] Tweet that a new preview release is out @jenlampton 
- [ ] Publish roadmap updates for backdropcms.org @klonos

**Comment by jenlampton** [comment]
Draft release notes:
---

This is the preview release of Backdrop 1.15.0. Please use this version if you would like to test the features of the new version of Backdrop prior to the official release on January 15, 2020.

Major new features in Backdrop 1.14.0 preview include:

* #3297 Add Image Library modal to Image fields
* #3566 Add a recent news block to the dashboard
* #1610 Allow content to be placed into the menu by default
* #4200 Allow menus to be always click/touch activated rather than hover
* #3972 Add new translatable HTML5 date form elements: html_datetime, html_date, html_time
* #4235 Add more display options for boolean fields

**Comment by klonos** [comment]
@jenlampton I think that #4181 should be mentioned (not as new feature - but major change), along with a [link to its change record](https://api.backdropcms.org/change-records/entity_create_stub_entity-removed-from-core).

**Comment by jenlampton** [comment]
Did I leave it out of the release notes?

**Comment by klonos** [comment]
Yup, also, all but one ticket numbers in the release notes aren't linkified: https://github.com/backdrop/backdrop/releases/tag/1.15.0-preview

**Comment by jenlampton** [comment]
Linked: https://github.com/backdrop/backdrop/releases/tag/1.15.0-preview

I didn't include the function removal because it's not a 'Major new feature' but it will be in the release notes for 1.15.

**Comment by quicksketch** [comment]
With 1.15.0 coming out today we can close this one.
