### ISSUE TITLE
Backdrop 1.14.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4274]
Release scheduled for Jan 15th, 2020 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Note if any changes were made to files outside the `core` directory, for example:
    - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.
  - [x] Note if updates (update.php) needs to be run, for example:
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub @jenlampton 

## Post-release tasks

* See the post-release tasks on the matching Minor release issue

**Comment by jenlampton** [comment]
New bug-fix milestone for 1.15.1 created: https://github.com/backdrop/backdrop-issues/milestones?with_issues=no

**Comment by jenlampton** [comment]
Release notes draft:
---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Update information:**

* The database update script does not need to be run
* No changes have been made to the .htaccess, robots.txt or default settings.php files in this release, so upgrading custom versions of those files is not necessary.

**Changes since 1.14.2:**

<ul>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2843">#2843</a>: Allow longer URLs in rich text editor.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/1578">#1578</a>: Undefined index: identifier in views_plugin_display->is_identifier_unique().</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3550">#3550</a>: Set maintenance mode value correctly when using Installer module.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4151">#4151</a>: Support multisites in install.sh.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4145">#4145</a>: Fixing admin/structure/contact/list menu link.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4158">#4158</a>: Title and alt attributes may be stripped if they contain a colon.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4081">#4081</a>: Better descriptions for row widths on flexible layouts.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4187">#4187</a>: EntityDatabaseStorageController::create() should require entity class.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2623">#2623</a>: Remove reference to non-existent add.png file.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2655">#2655</a>: Fixed inconsistent sorting issues with backdrop_sort().</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4263">#4263</a>: Convert {} to [] for PHP 7.4.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3556">#3556</a>: Link documentaion on backing up database to new backdropcms.org page.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3873">#3873</a>: Better empty field value handling, fixes fatal on saving empty number fields.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4180">#4180</a>: DateThemeTestCase fails at certain times of day.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4191">#4191</a>: Added the missing @see lines to config_* function doc blocks.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4215">#4215</a>: Hero block needs file_usage_delete() when files change.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4236">#4236</a>: Dashboard: Fix undefined index notice in theme color/settings link.</li>
</ul>



<p>Changes since 1.14.2:</p>
<ul>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2843">#2843</a>: Allow longer URLs in rich text editor.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/1578">#1578</a> Undefined index: identifier in views_plugin_display->is_identifier_unique().</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3550">#3550</a>: Set maintenance mode value correctly when using Installer module.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4151">#4151</a>: Support multisites in install.sh.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4145">#4145</a>: Fixing admin/structure/contact/list menu link.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4158">#4158</a>: Title and alt attributes may be stripped if they contain a colon.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4081">#4081</a> - Better descriptions for row widths on flexible layouts.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4187">#4187</a>: EntityDatabaseStorageController::create() should require entity class.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2623">#2623</a>: Remove reference to non-existent add.png file.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2655">#2655</a>: Fixed inconsistent sorting issues with backdrop_sort().</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4263">#4263</a>: Convert {} to [] for PHP 7.4.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3556">#3556</a>: Link documentaion on backing up database to new backdropcms.org page.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3873">#3873</a>: Better empty field value handling, fixes fatal on saving empty number fields.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4180">#4180</a>: DateThemeTestCase fails at certain times of day.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4191">#4191</a>: Added the missing @see lines to config_* function doc blocks.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4215">#4215</a>: Hero block needs file_usage_delete() when files change.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4236">#4236</a>: Dashboard: Fix undefined index notice in theme color/settings link.</li>
</ul>
