### ISSUE TITLE
Backdrop 1.15.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4275]
Scheduled for January 15, 2020 4:30pm PT

## Pre-release tasks

- [x] Merge bug-fix commits @quicksketch 
- [x] Move all unfinished issues to the next bug-fix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows (in BOLD)
    - [x] NEW Short, descriptive summary of the release
    - [x] Note if any changes were made to files outside the `core` directory
    - [x] Note if updates (update.php) needs to be run
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include UPDATED changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Unpublish preview release on backdropcms.org @jenlampton
- [x] Create release notes on GitHub @jenlampton 

## Post-release tasks

- [ ] Push the minor release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch 
- [ ] Push the minor release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch 
- [ ] Update backdropcms.org to use the latest TugBoat @quicksketch 
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @jenlampton  
- [ ] Push the minor release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) @serundeputy 
- [ ] Push the minor release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) ???

## Post-release Publicity + documentation tasks

- [x] Update the front page download link on b.org @klonos  
- [x] Tweet that a new release is out @stpaultim 
- [x] Publish blog post @stpaultim 
- [ ] Send a newsletter @jenlampton 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates

- [ ] backdropcms.org
- [ ] api.backdropcms.org
- [ ] forum.backdropcms.org

See the Accompanying Bug-Fix Release Checklist
----------------------------------------------

* https://github.com/backdrop/backdrop-issues/issues/4274

**Comment by drupol** [comment]
Hi there,
Sorry but I don't have much time for Backdrop anymore :(
I'll hope to be back as soon as I can!

**Comment by jenlampton** [comment]
Thanks for letting us know @drupol, we'll try to find a new co-maintainer for the Backdrop Docker project.

**Comment by jenlampton** [comment]
Release notes draft: 
---

The Backdrop community is proud to release version 1.15 of Backdrop CMS, following our 4-month release cycle.

**Notes for updating:**

* It **will** be necessary to run the update script `(located at `/update.php`) for this release.
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating custom versions of those files is not necessary.

**Major new features in Backdrop 1.15.0 preview include:**

* [#3297](http://github.com/backdrop/backdrop-issues/issues/3297) Add Image Library modal to Image fields
* [#3297](http://github.com/backdrop/backdrop-issues/issues/3297) Add a recent news block to the dashboard
* [#1610](http://github.com/backdrop/backdrop-issues/issues/1610) Allow content to be placed into the menu by default
* [#4200](http://github.com/backdrop/backdrop-issues/issues/4200) Allow menus to be always click/touch activated (rather than hover activated)
* [#3972](http://github.com/backdrop/backdrop-issues/issues/3972) Add new translatable HTML5 date form elements: html_datetime, html_date, html_time
* [#4235](http://github.com/backdrop/backdrop-issues/issues/4235) Add more display options for boolean fields

**Also changed since version 1.14.2:**

* 
* [All changes in version 1.14.3](https://github.com/backdrop/backdrop/releases/tag/1.14.3)

**Comment by klonos** [comment]
PR to update the tugboat repo to 1.15.0: https://github.com/backdrop-ops/backdrop-tugboat/pull/5

PR to update the procedures document: https://github.com/backdrop/backdrop-issues/pull/4294
