### ISSUE TITLE
Backdrop 1.14.4 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4346]
Release scheduled for **March 25th**, 2020 3pm - 6pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Draft Release notes  @jenlampton
  - [x] Short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update con tains bug fixes and usability improvements only.
  - [x] Note if any changes were made to files outside the `core` directory, for example:
    - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.
  - [x] Note if updates (update.php) needs to be run, for example:
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)

If this is a security release:
- [x] Draft Security Advisories  @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub  @jenlampton

If this is a security release:
- [x] Mark the release node on b.org as a security release  @jenlampton

See also: [the 1.15.1 issue](https://github.com/backdrop/backdrop-issues/issues/4347)

**Comment by jenlampton** [comment]
Maintenance release for Backdrop CMS. This update contains only security updates.

<p><strong>Update information:</strong></p>
<ul>
<li>The database update script does not need to be run.</li>
<li>No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.</li>
</ul>

<p><strong>Changes since 1.13.4:</strong></p>
<ul>
  <li>Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3355">#3355</a>: Update CKEditor to version 4.14.0.</li>
  <li>Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4330">#4330</a>: Check config archives contain allowable files before import.</li>
</ul>

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.14.4 is out
