### ISSUE TITLE
Backdrop  1.15.1  Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4347]
Release scheduled for **March 25th**, 2019 8pm - 9pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create the next bugfix milestone @jenlampton
- [x] Move all unfinished issues to the next bugfix release milestone  @jenlampton
- [x] Draft Release notes  @jenlampton
  - [x] Short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update con tains bug fixes and usability improvements only.
  - [x] Note if any changes were made to files outside the `core` directory, for example:
    - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.
  - [x] Note if updates (update.php) needs to be run, for example:
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)

If this is a security release:
- [x] Draft Security Advisories  @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub  @jenlampton
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton

If this is a security release:
- [x] Publish Security Advisories on b.org  @jenlampton
- [x] Mark the release node on b.org as a security release  @jenlampton

## Post-release tasks

- [ ] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch
- [ ] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @jenlampton
- [ ] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) @serundeputy  
- [ ] Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @drupol 
- [ ] Update the Wikipedia articles @stpaultim
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates

- [ ] backdropcms.org - @jenlampton 
- [ ] api.backdropcms.org - @jenlampton 
- [ ] forum.backdropcms.org - @jenlampton

**Comment by jenlampton** [comment]
Draft release notes:
---

Maintenance release for Backdrop CMS. This update contains only security updates.

<p><strong>Update information:</strong></p>
<ul>
<li>The database update script does not need to be run.</li>
<li>No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.</li>
</ul>

<p><strong>Changes since 1.15.0:</strong></p>
<ul>
  <li>Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3355">#3355</a>: Update CKEditor to version 4.14.0.</li>
  <li>Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3853">#3853</a>: Fixed Parameter 3 expected to be a reference, value given.</li>
  <li>Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4328">#4328</a>: Fixed viewsSearchQuery class missing from autoloader.</li>
  <li>Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4330">#4330</a>: Fixed the permission check in the color module for previews.</li>
  Issue #4321: Fix language pseudo field's weight to allow re-ordering.
  Issue #4326: Fix small typo in Basis theme's README.md.
  Issue #4299: Fix taxonomy_get_term_by_name() docblock.
  Issue #4034: Remove redundant 'contentinfo' aria role from 'footer'


</ul>

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.15.1 is out
