### ISSUE TITLE
[META] CMI in Backdrop 2.x

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#435]
In Backdrop 1.x, we made some compromises in the configuration management system to decrease the complexity and meet our timeline. This issue summarizes major config management undertakings that will likely require API changes and thus be a target for Backdrop 2.x:
- [ ] #704 | Provide central system for translating config.
- [ ] Automatically enable/install and disable/uninstall modules through config.
- [ ] Allow deletion of fields through config.
- [ ] Manage menu links through config.

**Comment by mikemccaffrey** [comment]
Do all of these items need to wait for Backdrop 2? As long as we provide an upgrade path, it seems like we should be fine with making all of these changes to the existing 1.x version.
