### ISSUE TITLE
Backdrop 1.16.0-preview Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4393]
Scheduled for May 1st, 2020 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create a new minor release milestone  @quicksketch
- [x] Move all unfinished issues to the next minor release milestone  @quicksketch
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release
  - [x] Include list of major new features

## Pre-release Publicity + documentation tasks

- [ ] Draft blog post for release on the 15th @klonos 
- [x] Draft roadmap updates for backdropcms.org @klonos 

## Release tasks

- [x] Update bootstrap.inc with version number  @quicksketch
- [x] Tag for release, and push tag to GitHub  @quicksketch
- [x] Branch for new minor number (e.g. `1.10.x-preview`) and push to GitHub  @quicksketch
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`)  @quicksketch
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`)  @quicksketch
- [x] Create release notes on GitHub, and publish the release  @jenlampton 

## Post-release Publicity + documentation tasks

- ~Tweet that a new release is out~ a bit late for this one
- [x] Publish roadmap updates for backdropcms.org @klonos

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4394)
* [Minor Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4395)

**Comment by jenlampton** [comment]
@quicksketch  I'm assigning the release notes task to myself and will update the preview release when I write them for the minor release.

**Comment by klonos** [comment]
Closing this in favor of #4395 for the actual 1.16.0 release.

**Comment by jenlampton** [comment]
@klonos  this is a different issue, its for this item: https://github.com/backdrop/backdrop/releases/tag/1.16.0-preview

**Comment by jenlampton** [comment]
Okay, added release notes to https://github.com/backdrop/backdrop/releases/tag/1.16.0-preview and published it! 

That's my last check in this checklist. Since the only thing left now is the blog post and @klonos is working on that in the other issue, closing this one now :)
