### ISSUE TITLE
Backdrop 1.15.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4394]
May 15th, 2020 approx 2pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Note if any changes were made to files outside the `core` directory, for example:
    - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release, so upgrading custom versions of those files is not necessary.
  - [x] Note if updates (update.php) needs to be run, for example:
    - Use the text "The database update script does **not** need to be run."
    - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub @jenlampton 
- [x] ~~Update the front page download link on b.org @klonos~~ Not required; we're releasing 1.16.0 as well.

See Also
---------
* (Minor Release Checklist)[https://github.com/backdrop/backdrop-issues/issues/4393]

**Comment by jenlampton** [comment]
Draft Release Notes
--------------------

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

* No changes have been made to the `.htaccess`, `robots.txt`, or default `settings.php` files in this release, so updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.


<p>Changes since 1.15.1:</p>
<ul>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4389">#4389</a>: PHP notice on List layouts page when permission is missing.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4308">#4308</a>: Convert deprecated code for PHP 7.4 compatibility.</li>
  <li>Revert "Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1140">#1140</a>: Fix fields with inline labels next to floated elements."</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4017">#4017</a>: Fix "file may not be referenced" in image dialog for manually uploaded files.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4227">#4227</a>: Do not allow image field min dimensions to be larger than max dimensions.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4295">#4295</a>: Rebuild Color module CSS on cache flush.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4357">#4357</a>: Prevent "theme hook not found" on date field creation.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4371">#4371</a>: Fix file path placeholder for Layouts.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3869">#3869</a>: Fix Taxonomy term list table headers when Language module is enabled.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4319">#4319</a>: Fix Empty fields are rendering markup.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4373">#4373</a>: Fix incorrect cache bin.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4360">#4360</a>: Caching install profiles setting was not being saved.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3348">#3348</a>: Fixed Color module support for sub themes and Basis sub-theme color support.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4261">#4261</a>: Remove extraneous characters in SelectQuery::addField()'s docblock.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/1394">#1394</a>: Remove the unused Block IP addresses permission.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4306">#4306</a>: Adding code to time the test runs and display them in the summary.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3355">#3355</a>: Update CKEditor to version 4.14.0.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3853">#3853</a>: Parameter 3 to views_ui_build_form_state() expected to be a reference, value given in views_ui_ajax_form().</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4328">#4328</a>: viewsSearchQuery class missing from autoloader.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4330">#4330</a>: Fixed the permission check in the color module so that users other than UID 1 can see the color preview.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4321">#4321</a>: Fix language pseudo field's weight to allow re-ordering.</li>
  <li>Change 'Bartik' to 'Basis' in minimal.install comment.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4209">#4209</a>: Add comments to explain block removal code.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4326">#4326</a>: Fix small typo in Basis theme's README.md.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4299">#4299</a>: Fix taxonomy_get_term_by_name() docblock.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4034">#4034</a>: Remove redundant 'contentinfo' aria role from 'footer'.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4225">#4225</a>: Fix permission checking for individual vocabularies.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4297">#4297</a>: Content display modes: Remove angle brackets from the label options.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4280">#4280</a>: Fix "chronological" spelling.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4288">#4288</a>: Fix typo in taxonomy_vocabulary_load_multiple() docblock.</li>
</ul>

**Comment by jenlampton** [comment]
Release is out! 
https://github.com/backdrop/backdrop/releases/tag/1.15.2
