### ISSUE TITLE
Backdrop 1.16.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4395]
Scheduled for May 15, 2020 2pm PT

## Pre-release tasks

- [x] Merge minor release commits @quicksketch 
- [x] Move all unfinished issues to the next bug-fix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows (in BOLD)
    - [x] NEW Short, descriptive summary of the release
      - The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Note if any changes were made to files outside the `core` directory
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating custom versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include UPDATED changelog since last version 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @klonos 
- [x] Update the roadmap page on b.org @klonos 

## Post-release tasks

- [ ] Push the minor release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @jenlampton
- [x] Push the minor release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) @serundeputy
- [x] Push the minor release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch
  - [x] Update backdropcms.org to use the latest TugBoat @quicksketch
- [ ] Update the [Backdrop Docker repository](https://github.com/backdrop-ops/backdrop-docker) ???
    - [ ] Create a PR to update the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) ???

## Post-release Publicity + documentation tasks

- [ ] Tweet that a new release is out @stpaultim 
- [ ] Publish draft blog post @klonos 
- [ ] Send a newsletter via MailChimp @jelampton 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates

- [ ] backdropcms.org
- [ ] api.backdropcms.org
- [ ] forum.backdropcms.org

See Also
---------
- [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4394)

**Comment by jenlampton** [comment]
Draft release notes:
---

The Backdrop community is proud to release version 1.16 of Backdrop CMS, following our 4-month release cycle. This version contains a handful of new features, as well as the usual cleanup tasks, and usability improvements.

## Notes for updating:
* It will be necessary to run the update script (located at /update.php) for this release.
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating custom versions of those files is not necessary.

## Major new features in Backdrop 1.15.0 preview include:

* Any configuration value can be overridden in settings.php https://github.com/backdrop/backdrop-issues/issues/2805
* Autocomplete is now available on all link/path fields  https://github.com/backdrop/backdrop-issues/issues/3764
* Disabled text formats can now be re-enabled https://github.com/backdrop/backdrop-issues/issues/1575
* Author and Date display can now be customized for each content type https://github.com/backdrop/backdrop-issues/issues/2379
* Specific content types can now be excluded from the search index
https://github.com/backdrop/backdrop-issues/issues/4197

### Usability improvements
* Double dashes in the menu parent select list have been replaced with a Middot https://github.com/backdrop/backdrop-issues/issues/4218
* Text filter configuration has been moved into modals https://github.com/backdrop/backdrop-issues/issues/1032
* Hide the password field when the Notification checkbox is checked on the user account creation form https://github.com/backdrop/backdrop-issues/issues/4266

### API additions
* A `removed_blocks` property has been added to the `Layout` class https://github.com/backdrop/backdrop-issues/issues/4209
* A new `theme_has_color()` function https://github.com/backdrop/backdrop-issues/issues/4044
* Content can now have an active revision that is not the most recent revision (no UI included) https://github.com/backdrop/backdrop-issues/issues/4354
* Integrate Entity Cacheing https://github.com/backdrop/backdrop-issues/issues/74

### Cleanup tasks
* Node actions code moved into a separate `node.actions.inc` file. https://github.com/backdrop/backdrop-issues/issues/3807

**Comment by serundeputy** [comment]
> Push the minor release to the Backdrop Composer repository @serundeputy

Looks like I don't have push access to the `backdrop-ops/backdrop-composer` repository any longer.

```bash
gff ~/code/backdrop-ops/backdrop-composer 
(1.x) └─ ∴ git push origin 1.x 
ERROR: Permission to backdrop-ops/backdrop-composer.git denied to serundeputy.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

@jenlampton or @quicksketch is that something you can fix for me?

**Comment by jenlampton** [comment]
@serundeputy weird, there were NO people with access!  I've added you.

**Comment by klonos** [comment]
Lets close this one in favor of the checklist for 1.16.1: #4405
