### ISSUE TITLE
Backdrop 1.16.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4405]
Release scheduled for May 20, 2020 12noon PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelong can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.1

If this is a security release:
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back@quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
- [x] Publish Security Advisories on b.org @jenlamptpn 
- [x] Mark the release node on b.org as a security release @quicksketch 
- [X] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) 

## Post-release tasks

- [ ] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch 
- [ ] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch 
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @serundeputy
- [x] N/A Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) 
- [x] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) @serundeputy 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] N/A Update the Security Advisory with CVE 

## Backdrop Website updates
- [ ] backdropcms.org
- [x] api.backdropcms.org
- [ ] forum.backdropcms.org

**Comment by jenlampton** [comment]
Draft release notes:

---

Maintenance release for Backdrop CMS. This update contains security updates and bug fixes only.

* No changes have been made to the `.htaccess`, `robots.txt`, or default `settings.php` files in this release, so updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.


<p>Changes since 1.16.0:</p>

* Security Fix, see [SA](https://backdropcms.org/security/backdrop-sa-core-2020-002)
* Security fix, see [SA](https://backdropcms.org/security/backdrop-sa-core-2020-003)
* Issue [#4318](https://github.com/backdrop/backdrop-issues/issues/4318): Align color inputs with labels in theme settings.

**Comment by quicksketch** [comment]
The database update script _does_ need to be run after this update, even though it only clears the caches.

**Comment by klonos** [comment]
#4318 is listed twice (first and last bullet point) ...I have no permission to edit release notes @jenlampton

**Comment by jenlampton** [comment]
Looks like that was fixed on https://github.com/backdrop/backdrop/releases/tag/1.16.1.
