### ISSUE TITLE
Backdrop 1.15.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4406]
Release scheduled for May 20, 2020 12noon PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @quicksketch 
- [x] Move all unfinished issues to the next bugfix release milestone @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelong can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.1

If this is a security release:
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back@quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton

**Comment by jenlampton** [comment]
Draft release notes:

---

Maintenance release for Backdrop CMS. This update contains security updates and bug fixes only.

* No changes have been made to the `.htaccess`, `robots.txt`, or default `settings.php` files in this release, so updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.


<p>Changes since 1.15.2:</p>

**Comment by quicksketch** [comment]
@jenlampton 1.15.3 only includes the security fixes. All 3 of those other issues are 1.16.1 only fixes.

**Comment by jenlampton** [comment]
1.13.3 is out https://github.com/backdrop/backdrop/releases/tag/1.15.3
