### ISSUE TITLE
Backdrop 1.16.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4442]
Release scheduled for June 17th, 10am PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @klonos 
- [x] Tweet that a new release is out @jenlampton 
- [x] Publish Security Advisories on b.org @quicksketch 
- [x] Mark the release node on b.org as a security release @klonos 

## Post-release tasks

If this release does NOT accompany a minor release:
- [x] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch 
- [x] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch 
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @quicksketch 
- [ ] Push the bug-fix release to the [Docker Backdrop repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) @serundeputy 
- [ ] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) @serundeputy 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] Update the Security Advisory with CVE @jenlampton 

## Backdrop Website updates
- [x] backdropcms.org - @jenlampton 
- [x] api.backdropcms.org - @jenlampton 
- [x] forum.backdropcms.org - @jenlampton 

## See Also
- [1.15.4 Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4443)

**Comment by jenlampton** [comment]
Draft SA: https://backdropcms.org/security/backdrop-sa-core-2020-004

**Comment by jenlampton** [comment]
Release notes draft:
---

Maintenance release for Backdrop CMS. This update contains security updates and bug fixes only.

Previously, if a form submission failed Drupal's cross-site request forgery protection, the submitted form values would be re-displayed to the user along with a message advising them to copy their previously submitted values and reload the page. Beginning with this release, the form is shown without any values for security reasons, and the user is prompted to press the back button to return to their previously entered values.

The user-facing translatable string that appears when a form is outdated has also been changed, and translations of it will need to be updated.

## Notes for updating:

* No changes have been made to the `.htaccess`, `robots.txt`, or default `settings.php` files in this release, so updating customized versions of those files is **not** necessary.
* The database update script does **not** need to be run

**Changes since 1.16.1**

* Security Fix, see [BACKDROP-SA-CORE-2020-004](https://backdropcms.org/security/backdrop-sa-core-2020-004)
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4423">#4423</a>: Fix incorrect t() parameter usage in update_mail().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4419">#4419</a>: prevent new empty formats if disabled ones exist
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4431">#4431</a>: Use b.org link for backups help.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3044">#3044</a>: Update cron links to use backdropcms.org documentation.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3734">#3734</a>: Fix broken template rescan in views.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4223">#4223</a>: Correct API groups for Field UI documentation.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4146">#4146</a>: Minor change to text in contact module.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4281">#4281</a>: Enforce password value requirement on reset form.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4434">#4434</a>: Optimize color_css_alter() to reduce number of file system checks.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/4424">#4424</a>: Remove unnecessary string concatenations.

**Comment by jenlampton** [comment]
Closing, since 1.16.3 is out now.
