### ISSUE TITLE
Backdrop 1.15.4 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4443]
Release scheduled for June 17th, 10am PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @quicksketch 
- [x] Mark the release node on b.org as a security release @quicksketch 

## See Also
- [1.16.2 Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4442)

**Comment by jenlampton** [comment]
Release notes draft:
---

Maintenance release for Backdrop CMS. This update contains security updates and bug fixes only.

Previously, if a form submission failed Drupal's cross-site request forgery protection, the submitted form values would be re-displayed to the user along with a message advising them to copy their previously submitted values and reload the page. Beginning with this release, the form is shown without any values for security reasons, and the user is prompted to press the back button to return to their previously entered values.

The user-facing translatable string that appears when a form is outdated has also been changed, and translations of it will need to be updated.

## Notes for updating:

* No changes have been made to the `.htaccess`, `robots.txt`, or default `settings.php` files in this release, so updating customized versions of those files is **not** necessary.
* The database update script does **not** need to be run

**Changes since 1.15.3**

* Security Fix, see [BACKDROP-SA-CORE-2020-003](https://backdropcms.org/security/backdrop-sa-core-2020-003)

**Comment by jenlampton** [comment]
Draft SA: https://backdropcms.org/security/backdrop-sa-core-2020-004

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.15.4 is out and SA is published, thanks @jenlampton!
