### ISSUE TITLE
[META][UX] Better "Recent content" block

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4576]
I started tweaking #4020 and quickly got into multiple interesting rabbit holes 😅 ...in the end I got a very nice result, but there were multiple changes in all sorts of places, and I'm afraid that a single PR would make this unreviewable. So I'm filing this as a meta issue, to get all the bits implemented incrementally.

Here's what I have so far (admin user - CSS still needs some work):

![image](https://user-images.githubusercontent.com/2423362/91332208-82b1e100-e7d4-11ea-9354-d2891da76f2c.png)

Changes:

- [ ] Zebra stripping the rows in the block
- [ ] Tweaked `theme_more_link()` to allow custom "more" link text/properties, and made that "All recent content" for this block.
- [ ] Made the "Number of recent content items to display" field in the block settings a number field instead of a select with limited options.
- [ ] Make the edit/delete links dropbuttons instead.
- [ ] Adjust the colspan of the content/author column cells, depending on whether the operations buttons are shown or not for each row (based on permissions the current user has).
- [ ] Add checkbox in the block settings, to show the operations dropbuttons column or not.
- [ ] Proper "submitted by" info, pulled from the content type settings, instead of just the author username
- [ ] Add checkbox in the block settings, to show the "submitted by" info or not.
- [ ] Render the username link via a new [node:author:link] token (see https://www.drupal.org/project/token/issues/1176592 and https://www.drupal.org/project/token/issues/698242)
- [ ] Moved `sevenDropButtonWidths()` that helps calculate dropbutton widths from `core/themes/seven/js/script.js` to `core/misc/dropbutton.js` (and renamed it to `dropButtonWidths()`), so it can be used in Basis and other themes.

Happy to discuss each of these changes and either do or not.

Here's a few more screenshots...

- anonymous user viewing the page ("submitted by" info hidden):

  ![image](https://user-images.githubusercontent.com/2423362/91334526-ca863780-e7d7-11ea-82ac-6b3c7ac1dc3b.png)

- `another_user` logged in ("Editor" role, author of the second piece of content in the table - has no permission to delete own content):

  ![image](https://user-images.githubusercontent.com/2423362/91333713-9b22fb00-e7d6-11ea-8b40-6a8c564f5ddb.png)

- block settings dialog:

  ![Screen Shot 2020-08-26 at 8 05 50 pm](https://user-images.githubusercontent.com/2423362/91334725-0a4d1f00-e7d8-11ea-9fe7-87aee6fac528.png)

**Comment by klonos** [comment]
PoC PR with all the bells and whistles included: https://github.com/backdrop/backdrop/pull/3269

Please test and let me know which of the changes may be a good fit for inclusion in #4020.

**Comment by klonos** [comment]
BTW, the recent content block as it currently is does not fit very well in narrow regions. Here's what it looks like in the sidebar region of the Moscone Flipped layout template:

![screencapture-1-16-2-2ab4fpur6ydtqqgps5lkodsq7wkgsq5j-tugboat-qa-home-2020-08-26-23_18_26](https://user-images.githubusercontent.com/2423362/91352465-9409e600-e7f2-11ea-9ea4-787b12b3caee.png)

...that's why I thought it'd be better if the edit/delete links were combined into a dropbutton. That way there's some more horizontal space left for the content title/author column.

**Comment by stpaultim** [comment]
Taking a look at this issue and testing the Pull Request and have the following questions.

1) Is this really backward compatible. It seems like it is likely that this block is being used on production sites. The changes here modify how it functions and it's appearance. Won't this changes some users sites or are the changes all "options"? I don't think so. 

2) Do we really want to improve the current block or replace it with a view? See: https://github.com/backdrop/backdrop-issues/issues/146

I generally like what is being done here. But, it doesn't make sense to invest much more time reviewing this unless it is something that we are likely to use.

**Comment by herbdool** [comment]
Converting it to a view would solve a bunch of these, including leaving the old block around.

**Comment by klonos** [comment]
The PR for this is now outdated. I will re-work on it and change the status of this issue when ready for testing/review/feedback.
