### ISSUE TITLE
Backdrop 1.17.0-preview Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4593]
Scheduled for September 2nd, 2020 

## Pre-release tasks

- [x] Merge commits 
- [x] Create a new minor release milestone 
- [x] Move all unfinished issues to the next minor release milestone 
- [x] Draft Release notes @stpaultim
  - [x] Include a short, descriptive summary of the release, for example:
    - This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include list of major new features
    - This list can be generated from closed issues in the milestone

## Pre-release Publicity + documentation tasks

- [x] Draft blog post for release on the 15th @jenlampton 
- [x] Draft roadmap updates for backdropcms.org @klonos

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x-preview`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub w/ release notes above @jenlampton 

## Post-preview-release Publicity + documentation tasks

- [ ] Tweet that a new release is out @stpaultim
- [x] Publish roadmap updates for backdropcms.org @klonos 

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4595)
* [Minor Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4596)

**Comment by quicksketch** [comment]
Tag is cut for 1.17.0-preview: https://github.com/backdrop/backdrop/releases/tag/1.17.0-preview

**Comment by klonos** [comment]
I've updated the "Features planned for version 1.17" section in https://backdropcms.org/roadmap 👍 ...so far the only feature slated for 1.18 is the admin theme #4410 ...I'll be updating the list as we are adding milestones.

**Comment by quicksketch** [comment]
Release notes are published, thanks so much @stpaultim for writing them up!

https://github.com/backdrop/backdrop/releases/tag/1.17.0-preview

**Comment by jenlampton** [comment]
Draft blog post at backdropcms.org/node/3035
