### ISSUE TITLE
Backdrop 1.16.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4595]
Release scheduled for September 15th, 2020 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch @serundeputy @herbdool @bwpanda 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub, and publish release @jenlampton

## See Also

If this release DOES accompany a minor release:
- [Minor Release Checklist]()

**Comment by quicksketch** [comment]
Release tag is now cut: https://github.com/backdrop/backdrop/releases/tag/1.16.3

**Comment by jenlampton** [comment]
Draft release notes:
---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

# Notes for updating:

* It will be necessary to run the update script (located at `/update.php`) for this release.
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating custom versions of those files is not necessary.

# Changes since 1.16.2:

<ul>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/2200">#2200</a>: Allow sub-modules to be enabled during Install module process.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3846">#3846</a>: Prevent PHP fatal on update when staging directory is missing. Throw warning instead.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4351">#4351</a>: Add Tugboat code in preparation for new PR sandboxes.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4591">#4591</a>: Update system.core config name.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4592">#4592</a>: Use Filter library to fix file loading order.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4413">#4413</a>: Fixing problem with label for comment title field.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3739">#3739</a>: [DX] Watchdog deprecated messages for `element_validate_integer()`, `element_validate_integer()` and `element_validate_number()`.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/1259">#1259</a>: CKEditor in source mode does not save when in dialogs.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4527">#4527</a>: Image browser is missing CSS when no text editor is present first.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4481">#4481</a>: Improve readability of suggestions in link autocomplete dropdown.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4090">#4090</a>: Add tugboat.qa to the list of companies we thank in the README.md</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4536">#4536</a>: Update PHP date format link.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3615">#3615</a>: Prevent contextual links overlapping each other.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4537">#4537</a>: Update documentation for path_save_automatic_entity_alias().</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4573">#4573</a>: Make URL alias field on entities match the site-wide form.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4532">#4532</a>: Fix undefined variable in ConfigFileStorage::initializeStorage().</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4542">#4542</a>: Display the 'Manage content' link in the dashboard to anyone with the 'access content overview' permission.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4517">#4517</a>: Wrong langcode data shown if the default language is not English.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3665">#3665</a>: Clear theme cache for manually added new layout templates.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4468">#4468</a>: Fix HTML markup in color.theme.inc related to the color settings preview.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4524">#4524</a>: Tab index: Password toggle should come after password field.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/1047">#1047</a>: Fix the styling/wrapping of disabled themes.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4538">#4538</a>: Update documentation in user.actions.inc.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/1500">#1500</a>: Prevent current and user 1 accounts from being blocked.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4407">#4407</a>: Text format order not respected in admin UI.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3746">#3746</a>: Change 'language' to 'langcode' in Views field handler.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4528">#4528</a>: Fix duplicated fields on comment reply page.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3799">#3799</a>: Changed references of 'post' to 'content'.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4530">#4530</a>: Update reference to deprecated htaccess function.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4101">#4101</a>: Fix typo in the `default_allowed_extensions` form element.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4183">#4183</a>: Autofocus the username field on user forms.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3048">#3048</a>: Enable password toggles on all core password fields.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3936">#3936</a>: Fix Views filter group operators in rearrange filter criteria dialog.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4462">#4462</a>: Legacy layout does not have value for template.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4503">#4503</a>: Sort by package, then module name.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4485">#4485</a>: Move LICENSE.txt in the project root.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4478">#4478</a>: Allow partial matching in path autocomplete text fields.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4493">#4493</a>: Page title of /user/register not translated.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4492">#4492</a>: CKEditor settings not respecting current site language.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/3841">#3841</a>: Improve table borders display in Seven theme using box-shadow borders.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4474">#4474</a>: PHP 7.4 Invalid characters in Color module base conversion functions.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/1505">#1505</a>: Lowercase uploaded file names by default.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4194">#4194</a>: Open the rewrite fieldset in Views UI if any rewriting is configured.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4117">#4117</a>: Fix update.php link in status report for sites in sub-directories.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4433">#4433</a>: Comments per page setting as number form item.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4418">#4418</a>: Avoid race-condition in page header test. Fixing regression from <a href="https://github.com/backdrop/backdrop-issues/issues/4306">#4306</a>.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4248">#4248</a>: Hide remaining days if time has elapsed.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4283">#4283</a>: Remove broken JavaScript disabled setting from Views.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4370">#4370</a>: Add a link to the layout path from the Layout configure page.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4382">#4382</a>: Bring back Views localization.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4420">#4420</a>: Allow blocks to be removed when changing layout templates.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4403">#4403</a>: Empty admin email subject and body when accounts require admin approval.</li>
  <li><a href="https://github.com/backdrop/backdrop-issues/issues/4426">#4426</a>: EntityMalformedException when comment author has been deleted.</li>
</ul>

**Comment by jenlampton** [comment]
Release notes published :)
