### ISSUE TITLE
Backdrop 1.17.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4596]
Scheduled for January/September/May 15, 20xx 10am - 4pm PT

## Pre-release tasks

- [x] Merge minor release commits @quicksketch
- [x] Move all unfinished bug-fix issues to the next bug-fix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      - The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section containing **Notes for updating**
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      - [x] Note if updates (update.php) needs to be run, for example:
        - Use the text "The database update script does **not** need to be run."
        - or "It will be necessary to run the update script (located at /update.php) for this release."
    - [x] Include list of major new features
      - This list can be generated from the list on the preview release, but review closed issuses in the milestone
      - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub, and publish release @quicksketch 
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 

## Post-release tasks

- [x] Push the minor release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch
  - [x] Update backdropcms.org to use the latest TugBoat @quicksketch
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @jenlampton
- [ ] Push the minor release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) @serundeputy
- [ ] Update the [Backdrop Docker repository](https://github.com/backdrop-ops/backdrop-docker) ???
    - [ ] Create a PR to update the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) ???

## Post-release Publicity tasks

- [x] Tweet that a new release is out @jenlampton 
- [x] Publish blog post @jenlampton 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] Update api.backdropcms.org @jenlampton 

## 2 weeks Post-release Publicity tasks
- [ ] Push the minor release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch
- [ ] Send a newsletter to subscribers @stpaultim
- [ ] Update backdropcms.org @jenlampton 
- [ ] Update forum.backdropcms.org @jenlampton 

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4595)
* [Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4593)

**Comment by jenlampton** [comment]
Draft release notes (thank you @stpaultim) 
---

The Backdrop community is proud to release version 1.17.0 of Backdrop CMS, following our 4-month release cycle.

# Notes for updating:

* It will be necessary to run the update script (located at `/update.php`) for this release.
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating custom versions of those files is not necessary.

# Major new features in Backdrop 1.17.0 include:

* Add a lazy-loading option for image fields backdrop/backdrop-issues#3659
* Provide image style tokens (imagecache_token module added to core) backdrop/backdrop-issues#3594
* Layouts: Provide an admin label and description for all blocks backdrop/backdrop-issues#4558
* Layouts: Allow support for custom contexts backdrop/backdrop-issues#3750
* Security enhancement: Enforce basic password constraints (no username or email as password) backdrop/backdrop-issues#4265
* Security enhancement:  Use `.htaccess` files to secure configuration directories backdrop/backdrop-issues#706

## Usability improvements

* Sort the "Available Updates" page by priority backdrop/backdrop-issues#3132
* Add the 'Administer content' permission to the editor role backdrop/backdrop-issues#4541
* Add the "new" marker to the content overview listing. backdrop/backdrop-issues#2350
* Enable the password toggle on all password fields backdrop/backdrop-issues#3048
* Make autocomplete suggestions easier to read backdrop/backdrop-issues#4481

## Cleanup tasks

* Restore missing "Page by date" Views pager plugin backdrop/backdrop-issues#2766
* Seven theme: Do not capitalize the labels of fieldsets backdrop/backdrop-issues#4125
* Fix formatting issues in core text files backdrop/backdrop-issues#4417
* Add a CSS class containing node ID to "existing content" blocks backdrop/backdrop-issues#3730

**Comment by quicksketch** [comment]
Tag for 1.17.0 is cut: https://github.com/backdrop/backdrop/releases/tag/1.17.0

New branch for 1.17.x created. And now the main 1.x branch is for 1.18.x.

**Comment by jenlampton** [comment]
release pubished: https://github.com/backdrop/backdrop/releases/tag/1.17.0

**Comment by quicksketch** [comment]
Tugboat demos are updated and working from backdropcms.org homepage.

**Comment by jenlampton** [comment]
I'm also working on a blog post at https://backdropcms.org/node/3035

**Comment by stpaultim** [comment]
I saw that. I keep thinking I will get to it, but Backdrop LIVE is taking all my time. Thanks. I have a little time now, if you need help.

**Comment by quicksketch** [comment]
Items like the push to Pantheon will be in the 1.17.1 release, which will be today: https://github.com/backdrop/backdrop-issues/issues/4661
