### ISSUE TITLE
Backdrop 1.17.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4661]
Release scheduled for Sept 30th, 2020 12pm - 2pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

If this is a security release:
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text "A security release for #BackdropCMS is out today, please update to version 1.17.1 as soon as possible: https://backdropcms.org"
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 

## Post-release tasks

If this release does NOT accompany a minor release:
- [ ] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch 
- [x] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @quicksketch
  - [x] Update backdropcms.org to use the latest TugBoat @quicksketch
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @jenlampton 
- [ ] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) ???
- [ ] Update the [Backdrop Docker repository](https://github.com/backdrop-ops/backdrop-docker) ???
    - [ ] Create a PR to update the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) ???
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates
- [x] backdropcms.org
- [x] api.backdropcms.org
- [x] forum.backdropcms.org

## See Also

If this is a security release:
- [Checklist for 1.16.4 release](https://github.com/backdrop/backdrop-issues/issues/4662)

**Comment by jenlampton** [comment]
Security Advisories drafted:
* https://backdropcms.org/security/backdrop-sa-core-2020-005
* https://backdropcms.org/security/backdrop-sa-core-2020-006

**Comment by jenlampton** [comment]
Draft release notes:
---

Security release for Backdrop CMS. This release fixes 2 security vulnerabilities:

* [Backdrop core - Moderately critical - Cross-site scripting - BACKDROP-SA-CORE-2020-005](https://backdropcms.org/security/backdrop-sa-core-2020-005)
* [Backdrop core - Moderately critical - Cross-site scripting - BACKDROP-SA-CORE-2020-006](https://backdropcms.org/security/backdrop-sa-core-2020-006)

**Notes for updating**

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

**Changes since 1.17.0**

* TBD
* TBD

**Comment by quicksketch** [comment]
Tag has been created at https://github.com/backdrop/backdrop/releases/tag/1.17.1

**Comment by jenlampton** [comment]
1.17.1 release is out https://github.com/backdrop/backdrop/releases/tag/1.17.1

**Comment by jenlampton** [comment]
I think @quicksketch did the tugboat things.

**Comment by quicksketch** [comment]
Yes Tugboat demos are updated and 1.17.1 is used on all new demos.

**Comment by jenlampton** [comment]
@quicksketch people on Pantheon are getting security notices telling them to update, can we get that upstream updated asap?

**Comment by quicksketch** [comment]
1.17.2 is now out, we should close this issue. Pantheon upstream was updated and now it's on the latest 1.17.2.
