### ISSUE TITLE
Backdrop 1.16.4 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4662]
Release scheduled for Sept 30th, 2020 12pm - 2pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 

## See Also

If this is a security release:
- [Checklist for 1.17.1 release](https://github.com/backdrop/backdrop-issues/issues/4661)

**Comment by jenlampton** [comment]
Draft release notes:
---

Maintenance and security release for Backdrop CMS.

This release fixes **two security vulnerabilities**:

* [Backdrop core - Moderately critical - Cross-site scripting - BACKDROP-SA-CORE-2020-005](https://backdropcms.org/security/backdrop-sa-core-2020-005)
* [Backdrop core - Moderately critical - Cross-site scripting - BACKDROP-SA-CORE-2020-006](https://backdropcms.org/security/backdrop-sa-core-2020-006)

**Notes for updating**

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

**Changes since 1.16.3**

* TBD
* TBD

**Comment by indigoxela** [comment]
Ehmmm... we already have a [1.16.3 release](https://github.com/backdrop/backdrop/releases/tag/1.16.3). Is this a typo?

**Comment by jenlampton** [comment]
Yes, 1.16.4 :)

**Comment by quicksketch** [comment]
Tag for 1.16.4: https://github.com/backdrop/backdrop/releases/tag/1.16.4

**Comment by jenlampton** [comment]
Release is out: https://github.com/backdrop/backdrop/releases/tag/1.16.4
