### ISSUE TITLE
[META][UX] Copy more permissions from Permissions page to specific settings areas

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4708]
We moved the permissions for node types to the node type configuration page, and people love that. But we haven't copied all the permissions from the permissions page into other places people are likely to be configuring core features. 

This issue is to track all the related issues for duplicating permissions:
* [ ] Administration Bar permissions - copy to `admin/config/administration/admin-bar`
* [ ] Configuration Manager - 

Ideas that need further discussion:
* [ ] Block - copy to bottom of `admin/structure/block/list` ?
* [ ] Comment - copy to new page at `admin/content/comment/settings`? (see related issue to create this page)
* [ ]

**Comment by klonos** [comment]
Assigning myself in order to see if we already have child-issues for these tasks.

I'd like to point out that perhaps we should work on issues like #3332 and #5031 first. These should make things easier for the tasks here.
