### ISSUE TITLE
Backdrop 1.17.2 Release checklist

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4742]
Release scheduled for Nov 8th, 2020 3pm - 6pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @quicksketch 
- [x] Move all unfinished issues to the next bugfix release milestone @quicksketch 
- [x] Draft Release notes @stpaultim (??) 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

If this is a security release:
- ~[ ] Draft Security Advisories~

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @quicksketch 
- [x] Update the front page download link on b.org @quicksketch 
- [x] Tweet that a new release is out @stpaultim  
- ~[ ] Publish Security Advisories on b.org~
- ~[ ] Mark the release node on b.org as a security release~ 

## Post-release tasks

If this release does NOT accompany a minor release:
- [x] Push the bug-fix release to the [Pantheon Backdrop repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch 
- [x] Push the bug-fix release to the [TugBoat Backdrop repository](https://github.com/backdrop-ops/backdrop-tugboat) @BWPanda 
  - [x] Update backdropcms.org to use the latest TugBoat @BWPanda
- [ ] Create a PR to update the [Platform.sh Backdrop repository](https://github.com/platformsh/template-builder/blob/master/project/backdrop.py) @jenlampton 
- [ ] Push the bug-fix release to the [Backdrop Composer repository](https://github.com/backdrop-ops/backdrop-composer) ???
- [ ] Update the [Backdrop Docker repository](https://github.com/backdrop-ops/backdrop-docker) ???
    - [ ] Create a PR to update the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) ???
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates
- [ ] backdropcms.org
- [ ] api.backdropcms.org
- [ ] forum.backdropcms.org

**Comment by stpaultim** [comment]
Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

## Notes for updating:
It will be necessary to run the update script (located at /update.php) for this release.
No changes have been made to the .htaccess, robots.txt or default settings.php files in this release. Updating custom versions of those files is not necessary.
## Changes since 1.16.2:
* [#4732](/backdrop/backdrop-issues/issues/4732): Errors when adding a Number (integer) field to a Layout
* [#4727](/backdrop/backdrop-issues/issues/4727): Problems with hidden_path views support (views_handler_filter_node_hidden_path)
* [#4719](/backdrop/backdrop-issues/issues/4719): Trying to sort the content overview via table header ticks (and filters by) new/updated content

* [#4698](/backdrop/backdrop-issues/issues/4698): Fix references to node language fields in Views when updating from Drupal 7
* [#4695](/backdrop/backdrop-issues/issues/4695): Basis pager ellipsis colour
* [#4694](/backdrop/backdrop-issues/issues/4694): Views UI: "Save & exit" button accidentally made primary instead of the "Continue & configure" button
* [#4686](/backdrop/backdrop-issues/issues/4686): Dashboard test looks for hardcoded relative paths so fails in subdirectories
* [#4685](/backdrop/backdrop-issues/issues/4685): Simpletest: Exceptions with htaccess files when tests run with profile caching
* [#4678](/backdrop/backdrop-issues/issues/4678): Layouts: the 'View page' link on the Manage Blocks page should just be the path from the layout
* [#4632](/backdrop/backdrop-issues/issues/4632): Date fields never show in localized display formats, always in default formats
* [#4626](/backdrop/backdrop-issues/issues/4626): Error: Call to a member function init() on null in view->init_localization() on updating core (latest release)
* [#4613](/backdrop/backdrop-issues/issues/4613): Clean up layout.context.admin
* [#4559](/backdrop/backdrop-issues/issues/4559): SQL error when uninstalling Locale module, if a language other than English has been set as the default
* [#4548](/backdrop/backdrop-issues/issues/4548): Remove check for 'php_code' filter
* [#4547](/backdrop/backdrop-issues/issues/4547): Better alignment of 'Add new field' row on 'Manage fields' page
* [#4513](/backdrop/backdrop-issues/issues/4513): Broken views_handler_relationship_translation.inc because of table column name
* [#4383](/backdrop/backdrop-issues/issues/4383): Why do the Default and Admin Default layouts have different paths?
* [#4351](/backdrop/backdrop-issues/issues/4351): Use Tugboat.qa for PR sandboxes
* [#4286](/backdrop/backdrop-issues/issues/4286): Remove 'Spock' from Backdrop.
* [#4238](/backdrop/backdrop-issues/issues/4238): MySQL 8 support
* [#4149](/backdrop/backdrop-issues/issues/4149): Remove duplication in `install.sh
* [#4111](/backdrop/backdrop-issues/issues/4111): PHP warning: Headers already sent on PHP 7.2.+
* [#3930](/backdrop/backdrop-issues/issues/3930): Seven: Fieldset labels overflow container when collapsed
* [#3806](/backdrop/backdrop-issues/issues/3806): Fix inline docs in `user_cancel_user_action()
* [#3484](/backdrop/backdrop-issues/issues/3484): Recoverable fatal error: Argument 1 passed to file_usage_add() must be an instance of File, boolean given
* [#3314](/backdrop/backdrop-issues/issues/3314): [SEO] Bulgarian Transliteration Improvement - bg.php
* [#2637](/backdrop/backdrop-issues/issues/2637): Transliteration doesn't respect site default language
* [#1849](/backdrop/backdrop-issues/issues/1849): [UX] Admin bar: empty `class=""` attribute left behind when the `active-search-item` class is removed.
* [#1695](/backdrop/backdrop-issues/issues/1695): [UX] Reorder the filter widgets of the manage content view to be consistent with the columns.
* [#1604](/backdrop/backdrop-issues/issues/1604): Update core/includes/transliteration/bg.php to follow the up-to-date transliteration standards for Bulgarian

**Comment by quicksketch** [comment]
Thanks so much @stpaultim!

Release is cut and now available: https://github.com/backdrop/backdrop/releases/tag/1.17.2

I updated the backdropcms.org homepage and Pantheon upstream. I usually handle updating the Tugboat demos, but @BWPanda has graciously volunteered to manage that for this release.

**Comment by BWPanda** [comment]
Tugboat updated.

**Comment by findlabnet** [comment]
Update script run **is required** for translation_update_1001

**Comment by indigoxela** [comment]
@findlabnet yep, this has already been corrected in the [release comment](https://github.com/backdrop/backdrop/releases), although it only affects installs with the translation module turned on. :wink:

**Comment by stpaultim** [comment]
Someone seems to have updated Wikipedia already. I don't recognize the user name.

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop/backdrop-issues/issues/4765
