### ISSUE TITLE
Backdrop 1.17.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4765]
Release scheduled for Nov 18th, 2020 11am - 1pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone -- ??
- [x] Move all unfinished issues to the next bugfix release milestone -- ??
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton
- [x] Tweet that a new release is out @jenlampton
- [x] Publish Security Advisories on b.org @jenlampton
- [x] Mark the release node on b.org as a security release @jenlampton
- [x] N/A We should [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)

## Post-release tasks

- [x] Update the Security Advisory with CVE @jenlampton
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--pantheon-upstream.md) @herbdool
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--platformsh-template.md) @herbdool
- [x] Update Composer @herbdool
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [ ] Update the Wikipedia articles (assign to @klonos)
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates
- [ ] backdropcms.org @jenlampton 
- [ ] api.backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton 

## See Also
- [Checklist for 1.16.5](https://github.com/backdrop/backdrop-issues/issues/4764)

**Comment by findlabnet** [comment]
1.17.3 - right?

**Comment by jenlampton** [comment]
yes, thank you :)

**Comment by jenlampton** [comment]
Draft SA: https://backdropcms.org/security/backdrop-sa-core-2020-007

**Comment by jenlampton** [comment]
## Release notes draft:

Security release for Backdrop CMS. This release fixes 1 security vulnerabilities:

* [Backdrop core - Critical - Remote code execution - SA-CORE-2020-007](https://backdropcms.org/security/backdrop-sa-core-2020-007)

**Notes for updating**

* No changes have been made to the .htaccess, robots.txt or default settings.php files in this release. Updating customized versions of those files is not necessary.
* The database update script does *not* need to be run.

**Changes since 1.17.5**

* @todo

**Comment by findlabnet** [comment]
Same typo (1.17.5) exists on https://backdropcms.org/security/backdrop-sa-core-2020-007

**Comment by jenlampton** [comment]
Thank you again :) fixed:
https://backdropcms.org/security/backdrop-sa-core-2020-007

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.17.3 is ready to go.

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.17.3 is out

**Comment by herbdool** [comment]
@jenlampton do we need to update the translation website too even though it's on D7?

**Comment by herbdool** [comment]
I updated Docker - it was really out of date. And added the steps to do that next time: https://github.com/backdrop-ops/backdrop-docker/issues/49

**Comment by jenlampton** [comment]
thank you! :)

**Comment by herbdool** [comment]
Oops, just noticed that there already are some instructions for the Docker @jenlampton. I think I was getting mixed up with the Composer one.

There's a couple more things to do with Docker which I'll do as well.

**Comment by herbdool** [comment]
@jenlampton once I've got permissions to https://github.com/backdrop-ops/backdrop-composer I'll update it too.

For Docker I'm waiting for the Travis-CI build to pass - seems to be taking some time. Not sure if it requires someone to do something or what...

**Comment by olafgrabienski** [comment]
> do we need to update the translation website too even though it's on D7?

@herbdool @jenlampton Yes.

**Comment by BWPanda** [comment]
Tugboat done.

**Comment by klonos** [comment]
@jenlampton there's a "stray" mention to 1.17.5 in the release notes:

![image](https://user-images.githubusercontent.com/2423362/99621871-9a92ad00-2a31-11eb-9bfd-d242ebf6d021.png)

...I don't have access to edit release notes 😓

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop/backdrop-issues/issues/4776
