### ISSUE TITLE
Backdrop 1.16.6 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4775]
Release scheduled for Nov 25th, 2020 5pm - 7pm PT

## Pre-release tasks

- [x] Merge commits @bwpanda
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

- [x] Draft Security Advisories @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @bwpanda 
- [x] Tag for release, and push tag to GitHub @bwpanda 
- [x] Revert version number back @bwpanda 
- [x] Create release notes on GitHub, and publish release @jenlampton

- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)

## See Also

- [Checklist for 1.17.4 release](https://github.com/backdrop/backdrop-issues/issues/4776)

**Comment by jenlampton** [comment]
Release notes draft: 
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

* Backdrop core - Critical - Remote code execution - BACKDROP-SA-CORE-2020-008

**Notes for updating**

No changes have been made to the .htaccess, robots.txt or default settings.php files in this release. Updating customized versions of those files is not necessary.
The database update script does not need to be run.

**Changes since 1.16.4**

* BACKDROP-SA-CORE-2020-08 Archive Tar filename manipulation fix.

**Comment by jenlampton** [comment]
SA draft: https://backdropcms.org/security/backdrop-sa-core-2020-008

**Comment by jenlampton** [comment]
Released: https://github.com/backdrop/backdrop/releases/tag/1.16.6
