### ISSUE TITLE
[Meta] Issues related to Home Page

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4847]
There has been quite a bit of talk about a variety of issues related to the home (formerly "front") page. I'm creating this META to help me (and anyone else interested) get a handle of everything that is going on.

- [x] #144 | Replace /node (frontpage) with a View
- [x] #1042 | Add a default Home Page layout
- [x] #1628 | Better front page selection UI
- [ ] #1638 | Multi language site: Changing the front page for the English language changes the other languages front page too.
- [x] #2162 | Change `Front page` to `Home page` in core
- [x] #2165 | Change big 'ol "Welcome to Backdrop CMS" to "Welcome to [sitename]"
- [ ] #2636 | Main page content block not available for the Home page layout.
- [x] #2709 | Admin bar: Consider replacing the home button with a "Back to site" button.
- [ ] #2946 | Out of the Box experience initiative
- [x] #3343 | System -> Site Information: Sort out issues with setting the default home page
- [ ] #3500 | Front page to be configurable by language
- [ ] #4785 | Translated Nodes do not switch languages properly when set as the home page.
- [ ] #4839 | Better help/guidance for users regarding Default Home Page path setting
- [x] #4849 | Replace the current default "Promoted Content" block with a page on Home page
- [ ] #4921 | Disable the Home page layout when front-page is not set to `home`

**Comment by klonos** [comment]
Thanks for taking the time to create this meta @stpaultim 👍 ...I had forgotten all about #1628
