### ISSUE TITLE
Backdrop 1.18.0-preview Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4875]
Scheduled for January 3rd, 20xx 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create a new minor release milestone @quicksketch 
- [x] Move all unfinished issues to the next minor release milestone @quicksketch 
- [x] Draft Release notes @bwpanda 
  - [x] Include a short, descriptive summary of the release, for example:
    - This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include list of major new features
    - This list can be generated from close issuses in the milestone

## Pre-release Publicity + documentation tasks

- [x] Create new forum topic for feedback on the release @stpaultim
- [x] Draft blog post for release on the 15th @cellear 
- [x] Draft roadmap updates for backdropcms.org @klonos 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x-preview`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub @bwpanda 
- [x] update api.backdropcms.org @jenlampton

## Post-release Publicity + documentation tasks

- [x] Tweet that a new release is out @stpaultim 

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4877)
* [Minor Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4876)

**Comment by jenlampton** [comment]
API site has been updated to 1.18.0

**Comment by klonos** [comment]
Blog post and forum post for feedback have been created for the final 1.18.0 release. Closing this issue in favor of #4876 for the final release.
