### ISSUE TITLE
Backdrop 1.18.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4876]
Scheduled for January 15, 2021 10am - 4pm PT

## Pre-release tasks

- [x] Merge minor release commits @quicksketch
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      - The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section containing **Notes for updating**
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      - [x] Note if updates (update.php) needs to be run, for example:
        - Use the text "The database update script does **not** need to be run."
        - or "It will be necessary to run the update script (located at /update.php) for this release."
    - [x] Include list of major new features
      - This list can be generated from the list on the preview release, but review closed issuses in the milestone
      - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch
- [x] Revert version number back on 1.x branch with minor number increased @quicksketch
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Unpublish preview release on backdropcms.org @jenlampton
- [x] Update the front page download link on b.org @jenlampton 
- [x] Update the roadmap page on b.org @klonos 
- [x] Create a new language template file for the translation server @olafgrabienski (see https://github.com/backdrop-ops/localize.backdropcms.org/issues/27 until this is automated)

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--tugboat.md) @bwpanda
- [ ] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md) @klonos 

### Publicity tasks

- [x] Tweet that a new release is out @stpaultim 
- [x] Publish blog post @celear 
- [x] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## 2 weeks Post-release tasks

- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--pantheon-upstream.md) @herbdool 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--platformsh-template.md) @jenlamoton 
- [x] Send a newsletter to subscribers @bwpanda
- [x] update backdropcms.org to latest version @jenlampton
- [x] update forum.backdropcms.org to latest version @jenlampton

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4877)
* [Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4875)

**Comment by BWPanda** [comment]
@jenlampton I see a task above to email Katie re. putting a note in the PHP Weekly newsletter. I just subscribed to this last week and went looking for previous Backdrop notes in her newsletter. However I could really only find mentions of Backdrop under the "Interesting Projects, Tools and Libraries" section (e.g. http://phpweekly.com/archive/2020-08-20.html). It'd be better to see it listed under the "News and Announcements" section instead, since that's where new releases of other projects are listed (e.g. http://phpweekly.com/archive/2021-01-14.html). Is it possible to ask her to do that for us?

**Comment by jenlampton** [comment]
I think I've seen releases under the News and Announcements section before. Hm, these archives look very different than what lands in my inbox. I wonder if I opted in to a text-only version? Anyway, we can certainly ask :)

**Comment by jenlampton** [comment]
Release notes draft:
---

The Backdrop community is proud to release version 1.18.0 of Backdrop CMS, following our 4-month release cycle.

## New features

- Add setting to menu block for changing breakpoint [#4663](https://github.com/backdrop/backdrop-issues/issues/4663)
- Add a `:link` sub-token for users [#4584](https://github.com/backdrop/backdrop-issues/issues/4584)
- Add webp support [#4509](https://github.com/backdrop/backdrop-issues/issues/4509)
- Provide option to skip deleting config staging files after a config sync [#4447](https://github.com/backdrop/backdrop-issues/issues/4447)
- [UX] Add Phone field to Contact forms [#3047](https://github.com/backdrop/backdrop-issues/issues/3047)
- Add the option to disable translation links [#2910](https://github.com/backdrop/backdrop-issues/issues/2910)

## Miscellaneous changes

- Change the expires header (remove Dries birthday from Backdrop) [#4827](https://github.com/backdrop/backdrop-issues/issues/4827)
- [UX] Change the name of the "Full HTML" text format to "Raw HTML" [#4499](https://github.com/backdrop/backdrop-issues/issues/4499)
- [DX] Consolidate "js-show" and "js-only" classes [#4252](https://github.com/backdrop/backdrop-issues/issues/4252)
- Disable user pictures by default. [#2090](https://github.com/backdrop/backdrop-issues/issues/2090)

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.18.0 is out!

**Comment by BWPanda** [comment]
Tugboat's been updated.

**Comment by jenlampton** [comment]
I got excited and updated the forum site.

**Comment by BWPanda** [comment]
Since there's a task above for me to send out a newsletter in two weeks, I'll use this comment as a place to store my thoughts and ideas for content...

## Main topic

**Backdrop 1.18.0 released**

On the 15th of January, the Backdrop community proudly released [version 1.18.0](https://github.com/backdrop/backdrop/releases/tag/1.18.0) of Backdrop CMS! Some of the new features include:
- Support for the 'WebP' image format
- The ability to customize the menu breakpoint from the user interface
- A new, optional 'Phone' field for contact forms

Check out our [1.18.0 release blog post]() for more details.

## Upcoming events

**Backdrop LIVE - 13th Mar**

We've set a tentative date for the next Backdrop LIVE event: 13th of March 2021. [Get in touch](https://backdropcms.org/support/resources) if you'd like to express an interest in presenting or attending the virtual event, or keep an eye on the [event page](https://backdropcms.org/news/events/backdrop-live-1) for more details coming soon.

## New projects

Some of the new [projects](https://backdropcms.org/add-ons) that have been released this month include:

- [Webform Localization](https://backdropcms.org/project/webform_localization)
- [Slider Field](https://backdropcms.org/project/sliderfield)
- [Grid Field Formatter](https://backdropcms.org/project/grid_field_formatter)
- [Node authorize link](https://backdropcms.org/project/node_authlink)
- [Facet API](https://backdropcms.org/project/facetapi)
- [CKEditor Skins](https://backdropcms.org/project/ckeditor_skins)

[NOTE: Display these in two columns]

## Mentions

People on the web are talking about Backdrop! Here are some recent [mentions](https://backdropcms.org/news/mentions):

- [Finding when a change was made in GitHub](https://panda.id.au/posts/finding-when-a-change-was-made-in-github)
- [Buchungen und Online-Anmeldungen](https://backdrop-cms.de/blog/buchungen-und-online-anmeldungen) (German)
- [Drupal 7's FAQ Field has been ported to Backdrop](https://www.altagrade.com/blog/drupal-7s-faq-field-has-been-ported-backdrop)

## Blog posts

**#states AND/OR/XOR conditionals explained**

If you've ever built or altered a form in Backdrop (or Drupal), you've likely come across `#states` - a form property that allows conditionally changing one form element based on another. PMC member [Greg Netsas](https://backdropcms.org/account/klonos) explains how to use AND, OR & XOR conditionals, with a great little screencast showing them in action:

**https://backdropcms.org/news/states-and-or-xor-conditionals-explained**

## Resources

Connect with the Backdrop community in [Zulip chat](https://backdrop.zulipchat.com/), on the [Backdrop forum](https://forum.backdropcms.org/) or in our [issue queues](https://backdropcms.org/resources/backdrop-cms-github).

Get support or help [contribute to Backdrop](https://backdropcms.org/contribute) anytime, but particularaly during our 'office hours': Wednesdays from 1pm to 4pm PT on [Zulip](https://backdrop.zulipchat.com/).

You can also join or watch our weekly community meetings; Thursdays from 12pm PT. Keep an eye on our [Twitter feed](https://twitter.com/backdropcms) or [Zulip chat](https://backdrop.zulipchat.com/) for the links prior to each meeting.

**Comment by klonos** [comment]
Wikipedia pages updated (and ticked off the list) 👍

**Comment by klonos** [comment]
Roadmap/history pages updated too 👍

**Comment by klonos** [comment]
...I've added assignees to this task, according to the remaining items in the issue summary list (makes it easier to see things assigned to you). Please feel free to unassign/reassign as needed.

**Comment by olafgrabienski** [comment]
> I've added assignees to this task, according to the remaining items in the issue summary list

I've also a task: Create a new language template file for the translation server. I do it usually a couple of days after the release. Not sure where to put it in the task list.

**Comment by klonos** [comment]
Hey @olafgrabienski 👋 ...I think that we should add the task in one or more of the procedures in https://github.com/backdrop/backdrop-issues/tree/master/procedures. Do you do this for pre-releases, or only final minor releases?

**Comment by olafgrabienski** [comment]
@klonos Re procedures, we can expand the "How to" text of this task description: https://github.com/backdrop-ops/localize.backdropcms.org/issues/27

I do this task only for final minor releases. For other releases, we don't provide language files at the moment. There's however an issue to automate the task (unfortunately without recent activity) which should make it easy to cover more releases.

**Comment by klonos** [comment]
OK, I've now added a task for it in this template @olafgrabienski: https://github.com/backdrop/backdrop-issues/blob/master/procedures/issue-template--release--minor.md

I've added it manually to this issue, and it will be added to all minor release task issues from now on 😉 

>There's however an issue to automate the task (unfortunately without recent activity) which should make it easy to cover more releases.

Pinging our automation wizard @BWPanda re that ^^ 😅

**Comment by BWPanda** [comment]
@olafgrabienski Looks like @serundeputy posted a possible solution to the automation problem: https://github.com/backdrop-ops/localize.backdropcms.org/issues/6#issuecomment-464364109 but there was no feedback if that solves the problem or not...

**Comment by olafgrabienski** [comment]
@klonos Thanks for adding the task in the template! For the current release, I've created the new language template file, see https://localize.backdropcms.org/translate/projects/backdropcms/releases.

**Comment by olafgrabienski** [comment]
@BWPanda Thanks for the hint to @serundeputy's script collection, I must have missed or forgot it. I'm not used to use such scripts but will give it a try.

**Comment by BWPanda** [comment]
Newsletter finally sent.

**Comment by klonos** [comment]
b.org is updated to 1.18.1 already 👍 

I've removed assignees that have no remaining sub-tasks assigned to them 😉

**Comment by jenlampton** [comment]
I will do platform to take some responsibility off @herbdool. Docker and composer would be the only other things. Is anyone else able to help with either of those? 

There are pretty good instructions on how to update docker: https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md

I don't know about composer.

**Comment by klonos** [comment]
I can do the Docker image 🤚

**Comment by BWPanda** [comment]
Close this now?

**Comment by klonos** [comment]
Yup 👍🏼 ...in favor of #5022
