### ISSUE TITLE
Backdrop 1.17.5 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4877]
Release scheduled for January 15th, 2021 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 

## See Also

- [Minor Release Checklist](https://github.com/backdrop/backdrop-issues/issues/4876)

**Comment by jenlampton** [comment]
Release notes draft:
---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**
* No changes have been made to the .htaccess, robots.txt or default settings.php files in this release. Updating customized versions of those files is not necessary.
* The database update script does not need to be run.

Changes since 1.17.4

## Bug fixes

- Menu: "Parent link" options only ever shows current language and neutral options [#4857](https://github.com/backdrop/backdrop-issues/issues/4857)
- Path autocomplete AJAX error [#4854](https://github.com/backdrop/backdrop-issues/issues/4854)
- Password strength indicator label has double colon [#4848](https://github.com/backdrop/backdrop-issues/issues/4848)
- Fix layout and views menu items get undeletable but stay visible once created [#4844](https://github.com/backdrop/backdrop-issues/issues/4844)
- Undefined index: settings in theme_has_color_support() [#4842](https://github.com/backdrop/backdrop-issues/issues/4842)
- CKEditor admin display broken for RTL languages [#4832](https://github.com/backdrop/backdrop-issues/issues/4832)
- Autocomplete throbber icon doesn't support RTL languages [#4826](https://github.com/backdrop/backdrop-issues/issues/4826)
- Menu UI: The "Show menu in language" option does not filter by language [#4784](https://github.com/backdrop/backdrop-issues/issues/4784)
- An arbitrary role can accidentally be set as admin when the role that was previously set as admin is deleted [#4783](https://github.com/backdrop/backdrop-issues/issues/4783)
- Complete PHP 7.4 Test Fixes [#4777](https://github.com/backdrop/backdrop-issues/issues/4777)
- Slight style breakage in the "Select versions" step of the Project Installer [#4768](https://github.com/backdrop/backdrop-issues/issues/4768)
- Fix fieldset styling [#4766](https://github.com/backdrop/backdrop-issues/issues/4766)
- 1.17.2 breaks queries when an alternate database prefix is specified [#4745](https://github.com/backdrop/backdrop-issues/issues/4745)
- PHP notices when installing modules that have sub-modules [#4640](https://github.com/backdrop/backdrop-issues/issues/4640)
- Duplicate .drop-lounging CSS in skin.css [#4625](https://github.com/backdrop/backdrop-issues/issues/4625)
- Wrong description in deprecated function `taxonomy_vocabulary_machine_name_load()` [#3874](https://github.com/backdrop/backdrop-issues/issues/3874)
- High precision float numbers (decimals) fail to pass validation [#3792](https://github.com/backdrop/backdrop-issues/issues/3792)
- The 'current_user' context in a Layout does not contain a User entity [#2398](https://github.com/backdrop/backdrop-issues/issues/2398)
- Bartik: Primary navigation menu not adapted to work with SmartMenus. [#2361](https://github.com/backdrop/backdrop-issues/issues/2361)
- [UX] Views: Page settings -> Path is unnecessarily trimmed. [#1309](https://github.com/backdrop/backdrop-issues/issues/1309)

## Documentation updates

- Add our Linux Foundation CII badge [#4464](https://github.com/backdrop/backdrop-issues/issues/4464)

## Miscellaneous changes

- Fix case of File Type descriptions [#4853](https://github.com/backdrop/backdrop-issues/issues/4853)
- Duplicate CSS in system.admin.css [#4843](https://github.com/backdrop/backdrop-issues/issues/4843)
- [UX] Add a "Cancel" link in the role edit form [#4792](https://github.com/backdrop/backdrop-issues/issues/4792)
- Date fields with optional end date: Do not capitalize words in the label of the "Show End Date" checkbox [#4791](https://github.com/backdrop/backdrop-issues/issues/4791)
- Incorrect usage: Less then / More then [#4786](https://github.com/backdrop/backdrop-issues/issues/4786)
- [D8] Enable the "Transliterate prior to creating URL aliases" setting by default for new sites [#4756](https://github.com/backdrop/backdrop-issues/issues/4756)
- Add missing .htaccess rules for mod_php7 [#4752](https://github.com/backdrop/backdrop-issues/issues/4752)
- Fix the code in hook_admin_bar_output_build [#4700](https://github.com/backdrop/backdrop-issues/issues/4700)
- [UX] Better help text for layout path field [#4555](https://github.com/backdrop/backdrop-issues/issues/4555)
- Do not capitalize the word "Date" in the default date formats [#4522](https://github.com/backdrop/backdrop-issues/issues/4522)
- [UX] Improve the description text on the block class field [#4290](https://github.com/backdrop/backdrop-issues/issues/4290)
- [UX] Change `Front page` to `Home page` in core [#2162](https://github.com/backdrop/backdrop-issues/issues/2162)

**Comment by quicksketch** [comment]
Looks good to me @jenlampton.

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.17.5 is out!
