### ISSUE TITLE
Backdrop 1.17.6 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4895]
Release scheduled for **Jan 27, 2021 - 1pm PT - 3pm PT**

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Draft Release notes jenlampton
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 

## See Also

- [Checklist for 1.18.1 release](https://github.com/backdrop/backdrop-issues/issues/4896)

**Comment by jenlampton** [comment]
Release notes draft:

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

* Backdrop core - Critical - Third Party Libraries - Backdrop SA-CORE-2021-001

**Notes for updating**

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does not need to be run.

**Changes since 1.17.5**

* BACKDROP-SA-CORE-2020-08 Archive Tar filename manipulation fix.
* TBD

**Comment by jenlampton** [comment]
Draft SA https://backdropcms.org/security/backdrop-sa-core-2021-001-1

**Comment by quicksketch** [comment]
Tag is cut https://github.com/backdrop/backdrop/releases/tag/1.17.6

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.17.6 is out.
