### ISSUE TITLE
Backdrop 1.18.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4896]
Release scheduled for **Jan 27, 2021 - 1pm PT - 3pm PT**
## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text ""
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A We should [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)

## Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--pantheon-upstream.md) @herbdool 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--platformsh-template.md) @herbdool 
- [ ] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md) @herbdool 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] Update the Security Advisory with CVE @jenlampton 

## Backdrop Website updates

- [x] backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [x] api.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [x] forum.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [x] events.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [x] localize.backdropcms.org @jenlampton 

## See Also

- [Checklist for 1.17.6 release](https://github.com/backdrop/backdrop-issues/issues/4895)

**Comment by jenlampton** [comment]
#Release notes draft:

Security release for Backdrop CMS. This release includes several bug fixes and addresses 1 security vulnerability:

* Backdrop core - Critical - Third Party Libraries - Backdrop SA-CORE-2021-001

**Notes for updating**

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does not need to be run.

**Changes since 1.18.0**

* BACKDROP-SA-CORE-2021-001 Archive Tar Directory Traversal fix.
* TBD 
* TBD 
* TBD 
* TBD

**Comment by jenlampton** [comment]
Draft SA https://backdropcms.org/security/backdrop-sa-core-2021-001-1

**Comment by quicksketch** [comment]
Tag for https://github.com/backdrop/backdrop/releases/tag/1.18.1 is cut

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.18.1 is out

**Comment by BWPanda** [comment]
Tugboat updated

**Comment by klonos** [comment]
The Wikipedia articles have been updated 👍 ...not by me, someone else beat me to it ❤️

**Comment by herbdool** [comment]
I've updated Pantheon. Anyone feel like taking on the Platform.sh and Composer projects?

**Comment by BWPanda** [comment]
Whoever takes over updating Pantheon, I'd like to find a better system, as currently I get a bunch of notifications for each commit that's merged that I was involved in...

**Comment by jenlampton** [comment]
I get them too, but I think this is a new change.  We didn't used to get notifications for merging with an upstream. Maybe something at GitHub?

**Comment by BWPanda** [comment]
How have you been doing it @herbdool? What are the steps?

**Comment by herbdool** [comment]
I'm okay with doing Pantheon. I just didn't want to do Platform, Composer, Docker this time.

Yes, those notifications are new. I make a PR in GitHub.

**Comment by BWPanda** [comment]
@herbdool Ah sorry, I misread Platform.sh as Pantheon 😄

**Comment by BWPanda** [comment]
> I make a PR in GitHub.

Ok, I see: https://github.com/backdrop-ops/backdrop-pantheon/pull/44

In that case, is it possible for you to use the 'Squash & Merge' option instead?
![image](https://user-images.githubusercontent.com/2385329/106206828-d5c11180-6214-11eb-9211-6a6fa8cf5172.png)

**Comment by jenlampton** [comment]
I don't think we want the core commits squashed. Do we?

**Comment by BWPanda** [comment]
> I don't think we want the core commits squashed. Do we?

This is only for the Pantheon repo, core repo still has full history of all commits, etc. if/when that's needed...

**Comment by jenlampton** [comment]
But the pantheon repo *is* core, so it should have all the same commits, right?

**Comment by herbdool** [comment]
I too think we want all the commits. Then we have a better audit trail of what's actually included compared to upstream. I believe this is the same approach Pantheon takes with other upstream repos.
