### ISSUE TITLE
[meta] Finish Entity API integration

### ISSUE THREAD

**Issue by SebCorbin** [backdrop/backdrop-issues#49]
Backdrop was forked around the time that Entities were being converted into real objects (i.e. `comment_save()` now just wraps around `$comment->save()`), but the implementation is incomplete. We should finish the conversion to move entities to real objects to enable generic entity operations for such problems as #142.

Issues that need to be addressed (if backporting from D8) need to be handled in this order, as some earlier ones are required for the later ones:
- [x] [Taxonomy Terms and Vocabularies](https://github.com/backdrop/backdrop-issues/issues/154) March 23, 2012
- [x] [User](https://github.com/backdrop/backdrop-issues/issues/155) April 25, 2012
- [x] [Node](https://github.com/backdrop/backdrop-issues/issues/153) April 26, 2012
- [x] [File](https://github.com/backdrop/backdrop-issues/issues/152) June 3, 2012
