### ISSUE TITLE
[META] Placeholders

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#4958]
- [x] | [[UX][UI] Systematically add a mechanism for HTML5 Placeholders #4956](https://github.com/backdrop/backdrop-issues/issues/4956) -- core already fully supports the use of placeholders via the form API `#attributes` property (and a UI should be left to contrib)
- [x] | [[UX][UI] Replace Image Title and Alt-Text Labels into Input field as HTML5 Placeholders #4957](https://github.com/backdrop/backdrop-issues/issues/4957) - closed - works as designed (left to contrib)
- [x] | [[UX][UI] Move File Display Title Label into Input as HTML5 Placeholder #4959](https://github.com/backdrop/backdrop-issues/issues/4959) - closed - works as designed (left to contrib)
- [ ] | [[D8][UX] Add a "Placeholder" input field to Views Exposed Filters to allow HTML5 Placeholder #4910](https://github.com/backdrop/backdrop-issues/issues/4910)

**Comment by BWPanda** [comment]
Just to clarify, are these proposed changes specific to the Seven admin theme...? Because I feel this sort of thing would be up to individual themes to implement (or not).

**Comment by philsward** [comment]
First, core needs to implement an easy, consistent, accessibility focused way to add placeholders. Then it would be up to the theme to add it.

Sure, placeholders can be added to any theme but that means every contrib and theme developer has to think about adding it. For certain aspects of core, I feel that placeholders should be added by default (regardless of theme) to reduce clutter.

Then there's the issue of consistency. If core handles the implementation, we can get better consistency between contribs and themes.

See the "blocking request" for cores role.

**Comment by BWPanda** [comment]
Hmm, so *my* opinion is that consistency is key. I don't like the idea of having placeholders by default for some fields, while not for others. So for me it's an all-or-nothing thing. Since I believe that this should be up to individual themes, then I don't see this as being something core should handle. It would be weird if core provided 'placeholder' fields everywhere, but they weren't used by the current theme (that'd be a waste of space in the UI), so I think themes can implement placeholders themselves if necessary (using the form field label), and if different text is needed for placeholders, then a contributed module can be installed that provides 'placeholder' fields.

Alternatively, the [Compact Forms](https://github.com/backdrop-contrib/compact_forms) module automatically hides form field labels and displays them as placeholders instead, for specified forms.

**Comment by jenlampton** [comment]
I agree that this is not something core should handle. There are both accessibility issues, and usability issues for using placeholders instead of labels, and providing additional text for both places does not seem like an 80% use-case. There is already complete support for placeholders in core via the `#attributes` property on all form element, so this can certainly happen in contrib right now, with no further changes needed to core.

**Comment by philsward** [comment]
I'll update this to remove the blocking request when I get a chance. As Jen pointed out, core already supports a way for core to add placeholders, provided someone decides to use them over the label.

**Comment by philsward** [comment]
No point in meta any more.
