### ISSUE TITLE
[META] Stay on top of redirect module updates

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5008]
## 7.x-1.0-rc3 2021-Mar-08

**Bug**

- [ ] | #2815099 by andralex, Tolyan4ik, anrikun, pifagor: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes' in
- [ ] | #1441488 by tomsegarra, Dave Reid, tim.plunkett, geek.merlin aka axel.rutz, Chris Matthews, euk, pifagor: Don't call entity_get_info() from inside hook_field_extra_fields()
- [ ] | #3063349 by Aporie, pifagor: Can't save a redirection from admin/config/search/redirect/404
- [ ] | #3013728 by djdevin, pifagor: Fix missing text format notice
- [ ] | #2968111 by tomsegarra, Chris Matthews, pifagor: Cannot create a redirect with a querystring if Clean URLs is off
- [ ] | #2560019 by jenlampton, hass, swhitters, Internet, satter9, Chris Matthews, pifagor: Broken upgrade path from path_redirect to redirect / does not recover
- [ ] | #2631918 by joshi.rohit100, miteshmap, alex_optim, voleger, joachim, Chris2: missing docs for hook_redirect_hash_alter()
- [ ] | #2562079 by danquah, Chris2, pifagor: Notice in redirect_field_extra_fields due to missing initialization
- [ ] | #2763681 by belyj_vladislav, Chris2, voleger, Dave Reid, pifagor, alex_optim: Parameter 1 to hook_redirect_load() expected to be a reference, value given
- [ ] | #2860844 by ChaseOnTheWeb, Chris2, alex_optim, voleger, pifagor: Minor code improvement to field existence check in redirect_fetch_rids_by_path
- [ ] | #2260499 by mrmikedewolf, zestagio, pifagor, Pere Orga, jami, rp7, rkeppner, incrn8, kevinwal: Generate redirects (Duplicate entry for key 'hash')
- [ ] | #1763436 by hanoii, torotil, adognameddog, cgmonroe, SylvainM, ShaunDychko, pifagor, Dave Reid, Pere Orga, vasike, alex_optim: redirect_path_delete() code is commented, not creating redirect on alias delete
- [ ] | #2543606 by das-peter, torotil, masipila, jyraya, gobilo, pifagor, alex_optim, drikc, Mark Schneider: Redirect to files folder on multilanguage website not working
- [ ] | #1551224 by mfb, leewillis77, acy76, Dave Reid, pifagor, kvnm, capellic, ANDiTKO, GinkgoFJG, jaydub, alex_optim, Maury Markowitz, rgchi, sonicthoughts, Pere Orga, torotil: redirect url with string that includes /? strips / upon save
- [ ] | #2789203 by ruudvanoijen, mvwensen, askibinski, pifagor, alex_optim, paulvandenburg: 404 fix pages needs domain filter
- [ ] | #2595199 by joshi.rohit100, daniel_rose, runswithscissors, pifagor, alex_optim: Remove message "action cannot be undone" when bulk Disabling/Enabling redirects
- [ ] | #1712062 by hass, tomsegarra, Dave Reid, pifagor, torotil: Translatable string review
- [ ] | #1817764 by mfernea, Adam Clarey, mariacha1, Pere Orga, Dave Reid, tomsegarra, alex_optim: Does not work with more than 2 query parameters
- [ ] | #2057615 by jyraya, mvc, heykarthikwithu, juampynr, enriquelacoma, pifagor, alex_optim: Increase size of source field to hold long URLs
- [ ] | #2820766 by anton.shloma, pifagor, Stevel, alex_optim: Vulnerability: redirect_goto() leads to the blank page due to translation flow
- [ ] | #2574593 by kala4ek: Fixed watchdog variables in redirect_change_status_multiple().
- [ ] | #2541304 by Dave Reid: Fixed errors in cases where redirect_update_7101() needs to run more than once.
- [ ] | #1961530 by Dave Reid, joelpittet, brianV: Added a limit to how many redirects are purged for each cron run.

**Feature**

- [ ] | #2220061 by Sneakyvv, Pere Orga, Chris2, pifagor: Add permission to restrict access to a user's own redirects only
- [ ] | #2702393 by Dave Reid, Chris2, alex_optim, voleger, pifagor: Allow creating redirects to file URIs
- [ ] | #2315877 by davidgrayston, pifagor, smira, drfuzetto, theapi, alex_optim, DamienMcKenna: Allow to change query string passthrough on a per-redirect basis (D7)
- [ ] | #1301594 by greggles, jfhovinne, mvc, acrosman, joseph.olstad, acrollet, pifagor, aaronbauman, tannerjfco, moskito, Dave Reid, alex_optim: Provide add-redirect command for drush
- [ ] | #2211279 by heddn, Dave Reid, pifagor, Pere Orga, Berdir, ankurj, alex_optim: Alterable redirect_load_by_source db_select
- [ ] | #1116408 by benjifisher, pifagor: Support migrate module: Destination handler class
- [ ] | #2604418 by ChaseOnTheWeb, ckng, tomsegarra, alex_optim, pifagor: Recognize 'status' field in redirect views
- [ ] | #2790205 by markdorison, pifagor, mmatsoo, alex_optim: Provide option to disable deletion of redirects by source path
- [ ] | #1768530 by Drave Robber: Integrate the redirect textfield with the Menu Path Autocomplete (mpac) module if it is available.

**Support**

- [ ] | #2843258 by danilo_formagio, nbouhid, andre.bonon, pifagor, leotorati, alex_optim: Implement support for entity_language function

**Task**

- [ ] | #2908995 by pifagor, donquixote, Neslee Canil Pinto: redirect_get_current_redirect() should use language from url
- [ ] | #2194099 by Vacilando, pifagor, Dave Reid, nicrodgers, JvE, rp7, ciss, alex_optim, danquah: Create database index on the redirect column
- [ ] | #3016519 by jweowu, pifagor, vijaycs85: Refactor redirect_list_form(), relocating call to func_get_args()
- [ ] | #2347687 by drclaw, extralooping, Chris2, alex_optim, pifagor: Use parse_str instead of drupal_get_query_array?
- [ ] | #2828083 by Andriy Khomych, pifagor, ozin, BR0kEN, alex_optim: Fields 'redirect_options', 'source_options' should be BLOB not TEXT
- [ ] | #1525554 by daniel_rose, Pere Orga, alex_optim, pifagor: Provide instructions in the README.txt
