### ISSUE TITLE
Date module commits 7.x-2.11-beta3

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5009]
- [ ] #xx | [9f08df0f](https://cgit.drupalcode.org/drupal/commit/?id=9f08df0f1bdf6f53e04a4514451b6c59aa64029f) | Preparing for further changes.
- [ ] #xx | [68eab4b3](https://cgit.drupalcode.org/drupal/commit/?id=68eab4b3631bbafc13972c144cabd06ead1bc47e) | [Issue #1392472 by Taran2L, jvandooren, podarok, jeff h, FluxSauce, maen, solotandem, nickonom, anrikun, JvE, steinmb, joelpittet: Undefined index: timezone in date.field.inc.](http://drupal.org/node/1392472)
- [ ] #xx | [ffdf64f4](https://cgit.drupalcode.org/drupal/commit/?id=ffdf64f4b6f57d8e08f02c9c9206d8c6d48a3797) | [Issue #3022378 by dev11235, DamienMcKenna, joelpittet: Date with empty "Repeats # Weeks" and "Repeats Every # of Days" validation needed.](http://drupal.org/node/3022378)
- [ ] #xx | [a0b84e77](https://cgit.drupalcode.org/drupal/commit/?id=a0b84e771e18e4911de993d968bdb1b50db859c0) | [Issue #2769057 by id.medion, Chris Matthews, steinmb: Remove unused argument in the function calls field_cache_clear() and field_info_cache_clear().](http://drupal.org/node/2769057)
- [ ] #xx | [2acdeb88](https://cgit.drupalcode.org/drupal/commit/?id=2acdeb88f7df0245bc0f88437d7e9bbad2503a4b) | [Issue #3033104 by DamienMcKenna: Add a LICENSE.txt file.](http://drupal.org/node/3033104)
- [ ] #xx | [a07449c7](https://cgit.drupalcode.org/drupal/commit/?id=a07449c7d1771ce477fae8c380281e731fac84ea) | [Issue #3032391 by herved, steinmb, skylord, DanielVeza: Empty date fields are being displayed.](http://drupal.org/node/3032391)
- [ ] #xx | [9d22ec58](https://cgit.drupalcode.org/drupal/commit/?id=9d22ec585fba079624f08bbaccc371a0447cfa60) | [Issue #3033022 by solotandem, steinmb: Correct reference to granularity setting.](http://drupal.org/node/3033022)
- [ ] #xx | [8193bc2d](https://cgit.drupalcode.org/drupal/commit/?id=8193bc2dd705a7dfcc099e63d61f3043d5107151) | [Issue #2701545 by ron_s, Chris Charlton, Chris Matthews, adci_contributor, DamienMcKenna: Add support for Date Popup Timepicker module.](http://drupal.org/node/2701545)
- [ ] #xx | [c8f7631b](https://cgit.drupalcode.org/drupal/commit/?id=c8f7631bbbe68c00592c5b6eb5873a07ad27da4c) | [Issue #3081547 by bhaskar-chakraborty, DamienMcKenna, vijaycs85: Update 7006 breaks when using the field_encrypt module.](http://drupal.org/node/3081547)
- [ ] #xx | [3bbac59a](https://cgit.drupalcode.org/drupal/commit/?id=3bbac59a4efa63ad73ee1a2c4ef2cf49ced6daa8) | [Issue #3032835 by solotandem, DamienMcKenna, steinmb, John_B: Validate input to date filter handler.](http://drupal.org/node/3032835)

this list generated with 

`git log 7.x-2.11-beta2..7.x-2.11-beta3 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`
