### ISSUE TITLE
Date module commits from 7.x-2.11-rc1

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5010]
- [ ] #xx | [649bbb9a](https://cgit.drupalcode.org/drupal/commit/?id=649bbb9a13f44ca3f4e8b75d871ccbec186d22aa) | Preparing for further changes.
- [ ] #xx | [84514520](https://cgit.drupalcode.org/drupal/commit/?id=84514520b9f0bc73a217e50cd87013499208b2c1) | [Issue #3084897 by steinmb, Chris Matthews: Fix the LICENSE.txt](http://drupal.org/node/3084897)
- [ ] #xx | [78862820](https://cgit.drupalcode.org/drupal/commit/?id=7886282042e13de7ba6748e7e100bb1e6bb690dd) | [Issue #2692215 by DamienMcKenna, stickgrinder, zread: Unconditioned access to non-existent array key in date.theme.](http://drupal.org/node/2692215)
- [ ] #xx | [53551658](https://cgit.drupalcode.org/drupal/commit/?id=5355165865d30ca1eca6f39dc7b714e2b1359e38) | [Issue #3111299 by DamienMcKenna: Test refactoring, split out Date Popup tests, move tests to appropriate submodule.](http://drupal.org/node/3111299)
- [ ] #xx | [9539b0ac](https://cgit.drupalcode.org/drupal/commit/?id=9539b0ac7c43d70759b64c58598726aac83746c6) | [Issue #2457423 by Liam Morland, ckellyirish, mparker17, DamienMcKenna, bmateus, sagannotcarl, katannshaw, Max1, alansaunders92, derekw, alex awg 2015, truman_ru, wylbur, nicrodgers, ninabyte, Michele Wickham, iStryker, dsdeiz, anpolimus, captainack, ashzade, brad.bulger, cameronprince, Chris Matthews, Vali Hutchison, jenlampton, vishal.sheladiya, jshosseini, akolahi: Incorrectly-initialized DateTime object(s) cause PHP warnings in DateTime::format(), other DateObject functions.](http://drupal.org/node/2457423)
- [ ] #xx | [e6660a14](https://cgit.drupalcode.org/drupal/commit/?id=e6660a1451e945e1caad76b8a43510db42f776eb) | [Issue #2595957 by aurelianzaha, DamienMcKenna, hgoto, klausi, pedrogk, FireHawkX, Chris Matthews: Field label not displayed when rendering as regular field and only using year.](http://drupal.org/node/2595957)
- [ ] #xx | [5f49b867](https://cgit.drupalcode.org/drupal/commit/?id=5f49b8670fa1d76101b08082cd3cb12db82e9cb9) | [Issue #2359653 by iamEAP, Sweetchuck, franxo, DamienMcKenna: Validation doesn't take into account translations of AM or PM.](http://drupal.org/node/2359653)
- [ ] #xx | [f40a50c1](https://cgit.drupalcode.org/drupal/commit/?id=f40a50c17f69db1a19cb84f3ffa3a1a1fc2d7263) | [Issue #3096720 by Liam Morland, ebremner: date_is_all_day() returns FALSE when $granularity is not 'hour' or finer.](http://drupal.org/node/3096720)
- [ ] #xx | [a22b02e2](https://cgit.drupalcode.org/drupal/commit/?id=a22b02e20d01db8214441991bbe75b99efff99eb) | [Issue #1257024 by joseph.olstad, maxocub, steinmb, iMiksu, DamienMcKenna, acbramley: Required Date popup field not showing red asterisk.](http://drupal.org/node/1257024)
- [ ] #xx | [dbde2f2a](https://cgit.drupalcode.org/drupal/commit/?id=dbde2f2a629b826cfaa2bd1703f31b162a5e4243) | [Issue #3145639 by Ronino, joelpittet: Curly brace syntax for accessing array elements and string offsets has been deprecated in PHP 7.4.](http://drupal.org/node/3145639)
- [ ] #xx | [7dc3d71a](https://cgit.drupalcode.org/drupal/commit/?id=7dc3d71a37c054955fe355ce9f6515e36fc223a0) | [Issue #2930732 by NuWans, DamienMcKenna: PHP warning on file_exists fail.](http://drupal.org/node/2930732)
- [ ] #xx | [e54adf65](https://cgit.drupalcode.org/drupal/commit/?id=e54adf654fa31d61a5f0f61f17b17ec84b9fb3ac) | [Issue #3161408 by DamienMcKenna, Ronino: Test failure in DateMigrateTestCase.](http://drupal.org/node/3161408)
- [ ] #xx | [e6f6ce35](https://cgit.drupalcode.org/drupal/commit/?id=e6f6ce358b5931cfa5ca980ee03b8e92976dad4b) | [Issue #3163293 by Steven Jones, joseph.olstad: date_update_7007 will fail with different field storage backends.](http://drupal.org/node/3163293)
- [ ] #xx | [13aacdb6](https://cgit.drupalcode.org/drupal/commit/?id=13aacdb691ef7555f7c3507190fdae92cd64ff73) | [Issue #2848963 by joelpittet, DamienMcKenna: date_views_filter_handler_simple::operators call t() a lot.](http://drupal.org/node/2848963)
- [ ] #xx | [65f65b8f](https://cgit.drupalcode.org/drupal/commit/?id=65f65b8f802c475a38b7b007f870c09390d08452) | [Issue #1762612 by moymilo, cafuego, tamahome14, vanshyr, plachance, steinmb: Error "OLD used in query that is not in a rule" in date_api_update_7000 with pgsql.](http://drupal.org/node/1762612)
- [ ] #xx | [f1aa12ee](https://cgit.drupalcode.org/drupal/commit/?id=f1aa12ee9d284bd23f64a78eafd91a040b226416) | [Issue #3168045 by DamienMcKenna: DateFieldTestBase::dateForm extended incorrectly.](http://drupal.org/node/3168045)
- [ ] #xx | [235f03af](https://cgit.drupalcode.org/drupal/commit/?id=235f03af7a089d807cdef4f3a3b318c790b49f87) | [Issue #3168034 by DamienMcKenna: Refactor date_migrate_example to be reusable.](http://drupal.org/node/3168034)
- [ ] #xx | [4f93f903](https://cgit.drupalcode.org/drupal/commit/?id=4f93f9039676c5e8ca21293e42d30884ac3f3ce7) | Releasing v7.x-2.11-rc1.

this list generated with 

`git log 7.x-2.11-beta3..7.x-2.11-rc1 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`
