### ISSUE TITLE
Date module commits from 7.x-2.11

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5011]
- [ ] #xx | [ac7757b8](https://cgit.drupalcode.org/date/commit/?id=ac7757b8a2a891430bbb5590f2b33b8ca3275825) | [Issue #3177831 by DamienMcKenna: Add test coverage for the All Day functionality.](http://drupal.org/node/3177831)
- [ ] #xx | [4a2c2fdd](https://cgit.drupalcode.org/date/commit/?id=4a2c2fdded6568cce8961bbccfa3e7ceeccfdfd3) | [Issue #3197985 by DamienMcKenna: Add unit tests for date_is_all_day().](http://drupal.org/node/3197985)
- [ ] #xx | [01a6744d](https://cgit.drupalcode.org/date/commit/?id=01a6744d91218d1694039e97f15b2482ecc44115) | [Issue #3197985 by DamienMcKenna: Add unit tests for date_is_all_day().](http://drupal.org/node/3197985)
- [ ] #xx | [3d8880c4](https://cgit.drupalcode.org/date/commit/?id=3d8880c42b9fc3d73c6a1c235dc4074380fb8e25) | [Issue #3197985 by DamienMcKenna: Expand unit tests for date_is_all_day().](http://drupal.org/node/3197985)
- [ ] #xx | [19afb865](https://cgit.drupalcode.org/date/commit/?id=19afb865bd7a33c8e3cda42e7d92baf29fc065bb) | [Issue #3197985 by DamienMcKenna: Expand unit tests for date_is_all_day().](http://drupal.org/node/3197985)
- [ ] #xx | [017d0e7c](https://cgit.drupalcode.org/date/commit/?id=017d0e7c5aa8b14533efbb1bbe0315531ea4a127) | [Issue #3197561 by DamienMcKenna: Add functional tests for All Day output.](http://drupal.org/node/3197561)
- [ ] #xx | [8c1b053c](https://cgit.drupalcode.org/date/commit/?id=8c1b053c6dc9e32cb6cccfc430b27fe4a92664c9) | [Issue #3016390 by DamienMcKenna, mr.york, steinmb, joseph.olstad, lily.yan, solideogloria, nagy.balint, micahw156, Kevin Morse: Change in "All day" end-of-day definition broke existing data.](http://drupal.org/node/3016390)
- [ ] #xx | [d86b0679](https://cgit.drupalcode.org/date/commit/?id=d86b0679c7722bda45e47255ee757e765fadedc0) | [Issue #3164305 by DamienMcKenna, FranckyLFS, hughworm, preethy211, joelpittet, lavamind, derekw, leendertdb: Notices in theme_date_display_combination() after upgrading to PHP 7.4.](http://drupal.org/node/d86b0679)
- [ ] #xx | [6542675b](https://cgit.drupalcode.org/date/commit/?id=6542675b0c09df2984c9ddba1bc7584c5fae5f40) | [Issue #2123039 by DamienMcKenna, hgoto, RoSk0, joelpittet, torotil: Default timezone setting mismatch in metadata wrapper integration.](http://drupal.org/node/6542675b)
- [ ] #xx | [782bd4ea](https://cgit.drupalcode.org/date/commit/?id=782bd4eaf13e29ae74acb76eecfbeef1de52db29) | Releasing v7.x-2.11.

this list generated with 

`git log 7.x-2.11-rc1..7.x-2.11 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/date/commit/?id=%H) | [%s](http://drupal.org/node/)"`

(and then manually updated the drupal node IDs)
