### ISSUE TITLE
Commits from token 7.x-1.8 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5013]
## token 7.x-1.8 - 2 March 2021

- [ ] #xx | [6561e21](https://cgit.drupalcode.org/drupal/commit/?id=6561e213c789fa022a410952b89219a5deed7c09) | [Issue #2871343 by Stevel: Fixed failing test.](http://drupal.org/node/2871343)
- [ ] #xx | [9b8f4f6](https://cgit.drupalcode.org/drupal/commit/?id=9b8f4f61d44a1558ab6baef1c1687d6f5321cf4b) | [Issue #2445775 by TR: Require at least core 7.23 to avoid fatal errors with undefined drupal_array_diff_assoc_recursive().](http://drupal.org/node/2445775)
- [ ] #xx | [bea4928](https://cgit.drupalcode.org/drupal/commit/?id=bea4928e059deda192cbeca72544545e24482e40) | [Issue #3192956 by Dave Reid, J-Lee, dwebpoint, Megha_kundar: Fixed PHP 7.4 compatibiliy for the [array:value:*] token.](http://drupal.org/node/3192956)
- [ ] #xx | [b106cef](https://cgit.drupalcode.org/drupal/commit/?id=b106cef3310666b6f05c2ec89c30e0466d0729e8) | [Issue #2327361 by filsterjisah, JesseDP, wroxbox: Fixed possible infinite loop in token_menu_link_load_all_parents().](http://drupal.org/node/2327361)
- [ ] #xx | [dcd9978](https://cgit.drupalcode.org/drupal/commit/?id=dcd99785260f9b868f285ea15b024ca10e7c74d6) | [Issue #2026011 by quicksketch: Pass colgroups and sticky properties from theme_tree_table() to theme_table()](http://drupal.org/node/2026011)

this list generated with 

`git log 7.x-1.7..7.x-1.8  --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"`
