### ISSUE TITLE
Commits from token 7.x-1.7

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5014]
- [ ] https://github.com/backdrop/backdrop/pull/4487 | [d04c7b8](https://git.drupalcode.org/project/token/-/commit/d04c7b83e330f65aa5f6f91858d72f8098651c8a) | [Issue #1821902 by Antonin Brunon, emattias: Fixed palse positives in recursive token check in _token_build_tree() for tokens that had a name of '0' (e.g. entity_token module's delta '0' field tokens).](https://drupal.org/node/1821902)
- [ ] https://github.com/backdrop/backdrop/pull/4488 | [2187bd6](https://git.drupalcode.org/project/token/-/commit/2187bd6a59fbd9378671028ec57024789a13bbe9) | Fixed tokens without a description value were treated as wrong.
- [ ] https://github.com/backdrop/backdrop/pull/4489 | [b189c11](https://git.drupalcode.org/project/token/-/commit/b189c11160e8ef4a517f3e749ac8ebb791c29a99) | Soften token status report messages, split into individual items with different severity values.
- [ ] https://github.com/backdrop/backdrop/pull/4490 | [e6c2702](https://git.drupalcode.org/project/token/-/commit/e6c2702a63877a3eea6b14c8b8d73e087f2b8833) | [Issue #2299039 by Elijah Lynn: Remove unused $sanitize variable from field_tokens().](https://drupal.org/node/2299039)
- [ ] https://github.com/backdrop/backdrop/pull/4491 | [4c39c41](https://git.drupalcode.org/project/token/-/commit/4c39c41c481956b61433c63130c34eae69aaa20b) | [Issue #2485221 by Berdir: Fixed token_pre_render_field_token() parameter should not be passed by reference.](https://drupal.org/node/2485221)
- [ ] N/A??? - see [comment below](https://github.com/backdrop/backdrop-issues/issues/5014#issuecomment-1665075799) | [0a620c8](https://git.drupalcode.org/project/token/-/commit/0a620c8df77dd60f0a54b7c6d02b43107db342a4) | [Issue #2474403 by kfritsche, mariamania, Zekvyrin, B-Prod: Fixed token replacement of field descriptions should not replace i18n_field.module's translations.](https://drupal.org/node/2474403)
- [ ] https://github.com/backdrop/backdrop/pull/4493 | [d9f4e54](https://git.drupalcode.org/project/token/-/commit/d9f4e54356922db0b3c0a746095ce1c05ef26b78) | [Issue #2630378 by hussainweb: Token "cannot contain fewer than one token" error misleading](https://drupal.org/node/2630378)
- [ ] https://github.com/backdrop/backdrop/pull/4493 | [cf53b40](https://git.drupalcode.org/project/token/-/commit/cf53b4089dd7d3821aeb93f237eb7c8d656b878b) | [Issue #2702379 by Dave Reid: Review @todos in token_element_validate()](https://drupal.org/node/2702379)
- [x] N/A - already addressed in a different way in #2697 | [6fa49e9](https://git.drupalcode.org/project/token/-/commit/6fa49e98a450f6df34f9e1ab9abea1721b105085) | [Issue #2825841 by hbemtec: Fixed PHP 7.1 compatibility error: Cannot use string offset as an array in _token_token_tree_format_row().](https://drupal.org/node/2825841)

This list generated with (and then d.org issue links manually added):
`git log 7.x-1.6..7.x-1.7 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://git.drupalcode.org/project/token/-/commit/%H) | [%s](https://drupal.org/node/)"`

**Comment by klonos** [comment]
PRs:
- https://github.com/backdrop/backdrop/pull/4487

**Comment by klonos** [comment]
With re to https://drupal.org/node/2474403 and the respective commit:

```diff
function token_field_widget_form_alter(&$element, &$form_state, $context) {
  if (!empty($element['#description']) && !empty($context['instance']['description'])) {
-    $element['#description'] = filter_xss_admin(token_replace($context['instance']['description']));
+    $instance = $context['instance'];
+    if (module_exists('i18n_field')) {
+      $instance = i18n_string_object_translate('field_instance', $instance);
+    }
+    $element['#description'] = field_filter_xss(token_replace($instance['description']));
  }
}
```

This is with regards to a contrib module, and AFAIK we don't account for contrib in core that way. Also, that function doesn't exist in Backdrop core, and I wasn't able to find any respective/equivalent. Should that issue/commit be marked as N/A then? Is there a way for this to be overridden and fixed in i18n_field?

**Comment by argiepiano** [comment]
@klonos please see my comment in the PR queue (decided to comment there, since this issue contains many PRs)

**Comment by klonos** [comment]
Thanks @argiepiano 🙏🏼 ...yes, this is how we work on these cross-port issues (I mean that we create multiple PRs linked to the same issue, and we review each PR in its thread instead of the issue thread as we'd normally do for other issues). It would be impractical to be opening separate issues for each commit, as there are sometimes dozens of them in each cross-port issue. What we often do is break up the commit history (if we are really behind), and we batch certain versions/tags together, to what seems like a manageable amount of commits.

I've responded in the PR 👍🏼 ...happy to mark it as N/A, however see my comment re code parity when possible (or "harmless" as you said).

**Comment by klonos** [comment]
[6fa49e9](https://git.drupalcode.org/project/token/-/commit/6fa49e98a450f6df34f9e1ab9abea1721b105085) | [Issue #2825841 by hbemtec: Fixed PHP 7.1 compatibility error: Cannot use string offset as an array in _token_token_tree_format_row().](https://drupal.org/node/2825841) is N/A to Backdrop, since we are already initializing the various relevant values in `$defaults` as arrays rather than strings earlier in the `_token_token_tree_format_row()` function. Our code:

```php
  static $defaults = array(
    'id' => '',
    'class' => array(),
    'data' => array(
      'name' => array(),
      'token' => array(),
      'value' => '',
    ),
  );
```

vs. the 7.x code:
```php
  static $defaults = array(
    'id' => '',
    'class' => array(),
    'data' => array(
      'name' => '',
      'token' => '',
      'value' => '',
      'description' => '',
    ),
  );
```

It has been fixed since 1.7.1 (back in May 2017), in #2697 ([commit](https://github.com/backdrop/backdrop/commit/819a951a2b3676fc9b8c80b3e720812bcaf90a07)).

**Comment by klonos** [comment]
...OK, I'm done here. Moving to #5013 next.

Please review each 7.x commit in the respective PR (links in the summary and the sidebar), and remember to leave a comment here when you have added any comment in any of the PRs. Thanks 🙏🏼

**Comment by argiepiano** [comment]
I'd like to suggest that you combine https://github.com/backdrop/backdrop/pull/4488 and https://github.com/backdrop/backdrop/pull/4489 into one PR. They both change some of the same lines.

**Comment by klonos** [comment]
Thanks @argiepiano ...yes, as I mentioned in another comment on the PR, I have already done that in https://github.com/backdrop/backdrop/pull/4493, where I had to merge the changes of 3 commits from 7.x.

**Comment by argiepiano** [comment]
Regarding the [comment above:](https://github.com/backdrop/backdrop-issues/issues/5014#issuecomment-1665075799)

> This is with regards to a contrib module, and AFAIK we don't account for contrib in core that way. Also, that function doesn't exist in Backdrop core, and I wasn't able to find any respective/equivalent. Should that issue/commit be marked as N/A then? Is there a way for this to be overridden and fixed in i18n_field?

The D7 problem was that, on a site with Field Translation enabled, as soon as you enabled Token, the field descriptions were not translated anymore. I've tested enabling Field Translation with Backdrop core (which includes the Token functionality), and this is not happening, so this patch is indeed not needed.

However, there is an unrelated bug that prevents the use of tokens in field descriptions. Tokens are simply not replaced.  Despite an initial replacement done [in this line](https://github.com/backdrop/backdrop/blob/f32837d9a1ae3dcbc3bb0e27274bbd051ed89a95/core/modules/field/field.form.inc#L106), the replacement is later reverted.

**Comment by indigoxela** [comment]
> AFAIK we don't account for contrib in core that way.

@klonos Agreed, this module specific code doesn't belong to core. And seems to be unnecessary, anyway.

**Comment by argiepiano** [comment]
@klonos, wondering if it may be a good idea to create issues for each PR. Right now there is this main issue in `backdrop-issues`, and a bunch of PRs in `backdrop`. By creating issues for each item in the list, we can mark each as "tested" or "WFM", and eventually merge only those that have been reviewed and tested. Right now there is no place to indicate that a specific PR WFM other than putting that in the PR request itself.
