### ISSUE TITLE
Include Admin Menu 7.x-3.0-rc6 updates

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5015]
## admin_menu 7.x-3.0-rc6 - 3 December 2018

- [ ] #xx | [4a5fcf1](https://cgit.drupalcode.org/admin_menu/commit/?id=4a5fcf116c992eef86136a4b460a4dc08898dcc1) | [Issue #725840 by hejazee, samaphp, navid.kashani, Khai Heller, W.M., tsi, sun, RoySegall, zvischutz, bloggz: Fixed drop-down links missing when using a RTL language.](http://drupal.org/node/)
- [ ] #xx | [2f4b8d6](https://cgit.drupalcode.org/admin_menu/commit/?id=2f4b8d617c10ee304cd3bf5b43a32b5b4ef06bc7) | [Issue #2170873 by jojonaloha: Fixed field_ui_admin_menu_map does not properly replace access arguments that map to path arguments.](http://drupal.org/node/)
- [ ] #xx | [67abd3a](https://cgit.drupalcode.org/admin_menu/commit/?id=67abd3a2e42c28167551b5d0e753ca322bc592ce) | [Issue #2378687 by refaktor: Use cache_is_empty() instead of db_table_exists().](http://drupal.org/node/)
- [ ] #xx | [71148b3](https://cgit.drupalcode.org/admin_menu/commit/?id=71148b34816ae3b6bc8b9b7b9b7296ded1f6041f) | [Issue #2929025 by Ayesh, truls1502: [PHP 7.2] each() function is deprecated](http://drupal.org/node/)
- [ ] #xx | [cb85d09](https://cgit.drupalcode.org/admin_menu/commit/?id=cb85d09b411548ab6599ff31ab3a5859b221e509) | [Issue #2502695 by seanbfuller, truls1502: Undefined index map in field_ui_admin_menu_map() when clearing cache](http://drupal.org/node/)
- [ ] #xx | [b74de94](https://cgit.drupalcode.org/admin_menu/commit/?id=b74de9400fbf7745190120813466469082569886) | [Issue #2215945 by joelpittet: Way to hide all "Issue Queue" menu items?](http://drupal.org/node/)
- [ ] #xx | [4ef7579](https://cgit.drupalcode.org/admin_menu/commit/?id=4ef757968af8db9c99a3cd74c73e96fa42f9760d) | [Issue #2419055 by gapple, Saphyel, DYdave, truls1502: JS cache causes menu to break when using fast_404](http://drupal.org/node/)
- [ ] #xx | [c2e60ac](https://cgit.drupalcode.org/admin_menu/commit/?id=c2e60acbfc6dfe1eca90d0d5d43650872c0c11ea) | [Issue #2431015 by hejazee, truls1502: extra borders are visible in admin menu toolbar](http://drupal.org/node/)
- [ ] #xx | [0708e67](https://cgit.drupalcode.org/admin_menu/commit/?id=0708e6773e5c98ddef69d68fa136ad797f373b70) | [Issue #2575645 by kala4ek, truls1502: Mistaken display if custom top menu item don't have a link (<span> instead of <a>)](http://drupal.org/node/)
- [ ] #xx | [c6074e7](https://cgit.drupalcode.org/admin_menu/commit/?id=c6074e7b414adf0de7cd9ea02ece1e75f0398776) | [Issue #2431015 by truls1502: extra borders are visible in admin menu toolbar](http://drupal.org/node/)
- [ ] #xx | [67a9e41](https://cgit.drupalcode.org/admin_menu/commit/?id=67a9e419f4e25b779bf87bc877fb3d6031341b1d) | [Issue #1742844 by jlockhart, nico.knaepen, truls1502: URL Alias not displaying when Admin menu enabled](http://drupal.org/node/)
- [ ] #xx | [1434307](https://cgit.drupalcode.org/admin_menu/commit/?id=1434307817ab0c98dc3adcc319a5b872f2f45911) | [Issue #2297827 by sammuell, truls1502: Link of to user list is not useful](http://drupal.org/node/)
- [ ] #xx | [f83d74c](https://cgit.drupalcode.org/admin_menu/commit/?id=f83d74cc4ae31138638444e03e8e17c4de3ac456) | [Issue #2336459 by mikeytown2: admin_menu_cache_set get's called when not needed](http://drupal.org/node/)
- [ ] #xx | [1a9faf4](https://cgit.drupalcode.org/admin_menu/commit/?id=1a9faf449758697c7dc474cc7c240d0ee987161c) | [Issue #2492947 by Mschudders, kwfinken, nightlife2008, RenatoG, baekelandt: Admin Menu covers content area in IE11](http://drupal.org/node/)
- [ ] #xx | [a45b44b](https://cgit.drupalcode.org/admin_menu/commit/?id=a45b44bc99a86f990a11d6efe1f6008edd1efcf0) | [Issue #2555783 by N.kishorekumar, truls1502: Code formatting](http://drupal.org/node/)
- [ ] #xx | [a813fbf](https://cgit.drupalcode.org/admin_menu/commit/?id=a813fbffab33f12a240c569d72a7fab40e9c9ef7) | [Issue #1950842 by NancyDru: Notice: Undefined index: #description in admin_menu_theme_settings() (line 673 of ../admin_menu/admin_menu.inc](http://drupal.org/node/)
- [ ] #xx | [182488f](https://cgit.drupalcode.org/admin_menu/commit/?id=182488f1722618986da2203d8b0424e4cd7dbd1b) | [Issue #2123625 by ycshen: Invalid url define in hook_menu](http://drupal.org/node/)
- [ ] #xx | [e8821f2](https://cgit.drupalcode.org/admin_menu/commit/?id=e8821f2b73ff7530ebb6195765fda7cf567691de) | [Issue #2616080 by heykarthikwithu: Add @return type and @param values in the comment docblocks](http://drupal.org/node/)
- [ ] #xx | [2dc5a9d](https://cgit.drupalcode.org/admin_menu/commit/?id=2dc5a9d3295fe290d0a8f1814b5b4377cf94d8c0) | [Issue #1950842 by truls1502, Brian Altenhofel: Notice: Undefined index: #description in admin_menu_theme_settings() (line 673 of ../admin_menu/admin_menu.inc](http://drupal.org/node/)
- [ ] #xx | [bbd691b](https://cgit.drupalcode.org/admin_menu/commit/?id=bbd691b58fd7ab7a6816ef00e00906422bb05684) | [Issue #2759001 by azovsky, Ramdas Gaikar, RenatoG: Undefined index: menu in admin_menu_admin_menu_output_alter()](http://drupal.org/node/)
- [ ] #xx | [bc712f7](https://cgit.drupalcode.org/admin_menu/commit/?id=bc712f72c4ce0d1152c86e6d3a7683b48cd0d062) | [Issue #3000355 by RenatoG: Update information on documentation of the project](http://drupal.org/node/)
- [ ] #xx | [52ce43b](https://cgit.drupalcode.org/admin_menu/commit/?id=52ce43b979b23923b3af57629f36643c5d1b6b09) | [Issue #2544682 by hansfn: Translation of '@title cache cleared.'](http://drupal.org/node/)

this list generated with

`git log 7.x-3.0-rc5..7.x-3.0-rc6 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/admin_menu/commit/?id=%H) | [%s](http://drupal.org/node/)"`
