### ISSUE TITLE
Backdrop 1.18.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5022]
Release scheduled for Mar 24th, 2021 4pm - 6pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version
    - This changelog can be generated with `drush rn [oldtag] [newtag]`, but you need to be on the minor version branch, for example, 1.15.x

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org."

## Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--pantheon-upstream.md) @herbdool 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--platformsh-template.md) @serundeputy 
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates

- [x] backdropcms.org @jenlampton 
- [x] api.backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [x] N/A localize.backdropcms.org

**Comment by herbdool** [comment]
I can volunteer for Pantheon as well.

**Comment by jenlampton** [comment]
I'm not sure @serundeputy will have time for platform, so if anyone wants to take that one, go ahead :)

**Comment by jenlampton** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does not need to be run.

# Changes since 1.18.1

## New features

- Provide an API for aria-live region update announcements for accessibility improvements [#4985](https://github.com/backdrop/backdrop-issues/issues/4985)

## Bug fixes

- Fix static caching in `layout_get_path_layout_names()`? [#5017](https://github.com/backdrop/backdrop-issues/issues/5017)
- [RTL] Basis: Draggable tables broken [#5006](https://github.com/backdrop/backdrop-issues/issues/5006)
- Path error in require_once() in views_handler_field_field.inc. [#4990](https://github.com/backdrop/backdrop-issues/issues/4990)
- Syntax error: unexpected '||' (T_BOOLEAN_OR) in user.module [#4982](https://github.com/backdrop/backdrop-issues/issues/4982)
- Seven: old browser quirk workaround causes new trouble with Firefox [#4971](https://github.com/backdrop/backdrop-issues/issues/4971)
- The toggle link for responsive tables never shows [#4965](https://github.com/backdrop/backdrop-issues/issues/4965)
- Variable typo in path.module [#4944](https://github.com/backdrop/backdrop-issues/issues/4944)
- Theme CSS loading in wrong order due to 'every_page_weight' and backdrop_css_alter() [#4942](https://github.com/backdrop/backdrop-issues/issues/4942)
- [UX] Manage blocks interface cannot be used with keyboard navigation [#4941](https://github.com/backdrop/backdrop-issues/issues/4941)
- Search terms: nodes dont appear when using multiple arguments [#4938](https://github.com/backdrop/backdrop-issues/issues/4938)
- Incorrect use of `config_get` in `node.api.php` file  [#4935](https://github.com/backdrop/backdrop-issues/issues/4935)
- Unable to save page after using CKEditor "Maximize" mode [#4933](https://github.com/backdrop/backdrop-issues/issues/4933)
- Color module doesn't support short color hex codes in themes [#4913](https://github.com/backdrop/backdrop-issues/issues/4913)
- Most _config_translatables missing in sites installed before May 2019 and all sites migrated from D7 [#4888](https://github.com/backdrop/backdrop-issues/issues/4888)
- [RTL] Basis: "gray box" shown to the left in vertical tabs [#4835](https://github.com/backdrop/backdrop-issues/issues/4835)
- Language names not translated to their native names [#4511](https://github.com/backdrop/backdrop-issues/issues/4511)
- [UX] Seven <code> tag display not distinct [#1794](https://github.com/backdrop/backdrop-issues/issues/1794)

## Documentation updates

- Improve the documentation for user_save() wrapper [#4973](https://github.com/backdrop/backdrop-issues/issues/4973)

## Miscellaneous changes

- Optimization of `cache_clear_all()` [#4962](https://github.com/backdrop/backdrop-issues/issues/4962)
- Remove backdropGetToken() from file.test [#4954](https://github.com/backdrop/backdrop-issues/issues/4954)
- Fix tiny typo in core/modules/file/file.file.inc file description. [#4939](https://github.com/backdrop/backdrop-issues/issues/4939)
- Replace multiple occurences of `config_get()` in the same core functions with `$config->get` implementation [#4936](https://github.com/backdrop/backdrop-issues/issues/4936)
- Fix the links to non-existent pages in core [#4884](https://github.com/backdrop/backdrop-issues/issues/4884)
- Support install profiles with no version number [#3019](https://github.com/backdrop/backdrop-issues/issues/3019)

**Comment by BWPanda** [comment]
Tugboat updated.

**Comment by BWPanda** [comment]
Lando doesn't require updating AFAIK. It just uses the copy of Backdrop that you already have or that you tell it to download.

**Comment by BWPanda** [comment]
Can this be closed now?

**Comment by quicksketch** [comment]
Yep, thanks @BWPanda.
