### ISSUE TITLE
Drupal 7.65-7.69 commits: crossport or mark as NA

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5042]
- [x] N/A | [d3353e9916](https://cgit.drupalcode.org/drupal/commit/?id=d3353e99162c28a57d1e988875944cde12f7054b) | Back to dev
- [x] N/A | [bf635f9f04](https://cgit.drupalcode.org/drupal/commit/?id=bf635f9f049492700d2b9428086aa6466aaf5497) | [Issue #3035772 by Pol: [Regression] Fix default.settings.php permission](http://drupal.org/node/3035772)
- [x] N/A | [87f903818c](https://cgit.drupalcode.org/drupal/commit/?id=87f903818c782f1a52804531d105e9b3547154b9) | Back to dev.
- [x] https://github.com/backdrop/backdrop/commit/f0424405fb9442e106fde0a8bbf27c7b34e62d2f | [d2f26902ef](https://cgit.drupalcode.org/drupal/commit/?id=d2f26902ef5d6de58caaf2a7c766eb2115b1c17e) | [SA-CORE-2019-006 by effulgentsia, lauriii, larowlan, xjm, greggles, drumm, dtv_rb, samuel.mortenson](https://www.drupal.org/sa-core-2019-006)
- [x] N/A | [9735baff3a](https://cgit.drupalcode.org/drupal/commit/?id=9735baff3afe061f98e568c1d1f83d56f3a0212a) | Drupal 7.66
- [x] N/A | [24532b16cf](https://cgit.drupalcode.org/drupal/commit/?id=24532b16cfdc8878fd2d3b3ec95a5677adae2b02) | Back to dev.
- [x] #3628 | [c8a2662355](https://cgit.drupalcode.org/drupal/commit/?id=c8a2662355c3b36c07b7892bfc2e2b1a5b9c8bee) | [Issue #2684337 by geoffray, Pol, jweowu, Fabianx: Warning: uasort() expects parameter 1 to be array, null given in node_view_multiple()](http://drupal.org/node/2684337)
- [x] https://github.com/backdrop-contrib/statistics/issues/8 | [b71e4eb378](https://cgit.drupalcode.org/drupal/commit/?id=b71e4eb378ed5a7a3680b36b9c396771dd45c75a) | [Issue #3009351 by Pol, mfb, BrianLP: [PHP ≥ 7.2] "session_id(): Cannot change session id"](http://drupal.org/node/3009351)
- [x] https://github.com/backdrop/backdrop/pull/3588 | [85be7c52bb](https://cgit.drupalcode.org/drupal/commit/?id=85be7c52bbb57217418830aebb13fc4885d4493e) | [Issue #1892654 by Pol, willvincent, Fabianx: D7 Backport: theme_table() should take an optional footer variable and produce <tfoot>](http://drupal.org/node/1892654)
- [x] https://github.com/backdrop/backdrop/commit/a2bdc26ee878c2a17237f862558f0be709790b64 | [117ef34685](https://cgit.drupalcode.org/drupal/commit/?id=117ef34685b4fc7d2902564afb1a4f67a4ed484e) | [Issue #2666908 by iamEAP, cilefen: HTTP status 200 returned for ”Additional uncaught exception thrown while handling exception”](http://drupal.org/node/2666908)
- [x] https://github.com/backdrop/backdrop/pull/3589 | [902980e2f6](https://cgit.drupalcode.org/drupal/commit/?id=902980e2f6f2ec1ed7158b4eb7defac54c5ec489) | [Issue #1861604 by hefox, joseph.olstad, Sivaji, mgifford, webchick: Skip module_invoke/module_hook in calling hook_watchdog (excessive function_exist)](http://drupal.org/node/1861604)
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-821484692 & https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-840448121) | [5f67268ed9](https://cgit.drupalcode.org/drupal/commit/?id=5f67268ed94034dbe5df600b6067b1d40e62d73a) | [Issue #3051370 by Pol, Fabianx: Create "scripts" element to align rendering workflow to how "styles" are handled](http://drupal.org/node/)
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-821484692 & https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-840448121) | [77c94ea5eb](https://cgit.drupalcode.org/drupal/commit/?id=77c94ea5eb07a412ee514388667945432a3a784c) | [Revert "Issue #3051370 by Pol, Fabianx: Create "scripts" element to align rendering workflow to how "styles" are handled"](http://drupal.org/node/3051370)
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-821861515 / https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-840454513 & https://github.com/backdrop/backdrop/commit/a62c56aef1a650852fb871d38c70058cfcacb841) | [ff05c001c9](https://cgit.drupalcode.org/drupal/commit/?id=ff05c001c97818abb16eed3e9c634ce55d851f93) | [SA-CORE-2019-007 by Blaklis, oliver.hader, alexpott, mlhess, tim.plunkett, dsnopek, xjm](https://www.drupal.org/sa-core-2019-007)
- [x] N/A | [09a33aa82a](https://cgit.drupalcode.org/drupal/commit/?id=09a33aa82ad15d5179322199f694f1fa7e6fb3e2) | Drupal 7.67
- [x] N/A | [fd9e16e34b](https://cgit.drupalcode.org/drupal/commit/?id=fd9e16e34bf3eb5c4852eecb4d29f434f4951597) | Back to dev.
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-821484692 & https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-840448121) | [15dec4d974](https://cgit.drupalcode.org/drupal/commit/?id=15dec4d9746fac76a28542b58bd5abe2eb8462e0) | [Issue #3051370 by Pol, markcarver, Fabianx: Create "scripts" element to align rendering workflow to how "styles" are handled](http://drupal.org/node/3051370)
- [x] N/A | [8bd7071d34](https://cgit.drupalcode.org/drupal/commit/?id=8bd7071d346902d1bcfb988a0f1cd1a52e8d66cf) | [Issue #3088557: Add mcdruid as provisional Drupal 7 branch maintainer](http://drupal.org/node/3088557)
- [x] N/A (unless we want to change the exception messages to match D7 100%) | [aeef87758f](https://cgit.drupalcode.org/drupal/commit/?id=aeef87758fba47a5092df40e08d194af55aa99c5) | [Issue #3047844 by mfb, jordanwood, Taran2L: Fix test failures on PHP 5.3](http://drupal.org/node/3047844)
- [x] #5047 | [758ed4b4ce](https://cgit.drupalcode.org/drupal/commit/?id=758ed4b4ced00099b8ec78e48ce7ec61e793233f) | [Issue #3047412 by mcdruid, Chi, beckydev, DKAN, alexpott, sammuell, rabbitlair, longwave, greggles, interX: Block web.config in .htaccess (and vice-versa)](http://drupal.org/node/3047412)
- [x] https://github.com/backdrop/backdrop/pull/3596 | [c6f73e2754](https://cgit.drupalcode.org/drupal/commit/?id=c6f73e2754b02321c09c4e770cf852641699135e) | [Issue #3055805 by mcdruid, greggles, Ayesh, Darren Oh, David_Rothstein, sidharrell, pwolanin, mkalkbrenner, Sweetchuck, YesCT: file.inc generated .htaccess does not cover PHP 7](http://drupal.org/node/3055805)
- [x] https://github.com/backdrop/backdrop/pull/3597 | [44fecf2115](https://cgit.drupalcode.org/drupal/commit/?id=44fecf2115fd8d6b2864d7d9abb1fb595f39c7ea) | [Issue #3025335 by mcdruid, mfb, joseph.olstad, Fabianx, kiamlaluno, Pol: [PHP 7.3] Cannot change session id when session is active](http://drupal.org/node/3025335)
- [x] N/A (see https://github.com/backdrop/backdrop-issues/issues/5042#issuecomment-840470879) | [ac4277fede](https://cgit.drupalcode.org/drupal/commit/?id=ac4277fede7f8ee67f5c66197e314edbb936a693) | [Issue #2966335 by mcdruid, dvandijk, David_Rothstein: Avoid DrupalRequestSanitizer not found fatal error when bootstrap phase order is changed](http://drupal.org/node/2966335)
- [x] https://github.com/backdrop/backdrop/pull/3590 | [ff3c4ca5bf](https://cgit.drupalcode.org/drupal/commit/?id=ff3c4ca5bf2f41a877b8ce8c8f27cd48f55c85b4) | [Issue #3059391 by Liam Morland: Use drupal_http_build_query() in drupal_http_request()](http://drupal.org/node/3059391)
- [x] https://github.com/backdrop/backdrop/pull/3598 | [4d080b6fc0](https://cgit.drupalcode.org/drupal/commit/?id=4d080b6fc0771e4222743e047c05c92ecc6b8b9d) | [Issue #2171113 by Pol, wiifm, mw4ll4c3, David_Rothstein, douggreen, Fabianx: Settings returned via ajax are not run through hook_js_alter()](http://drupal.org/node/2171113)
- [x] #5048 | [88de1737a6](https://cgit.drupalcode.org/drupal/commit/?id=88de1737a6dac893d5f2e480dbf5b17263705628) | [Issue #2472025 by stupiddingo, stefanos.petrakis: [D7] Hide toolbar when printing](http://drupal.org/node/2472025)
- [x] ~https://github.com/backdrop/backdrop/pull/3599~ https://github.com/backdrop/backdrop/pull/3624 | [63473379cd](https://cgit.drupalcode.org/drupal/commit/?id=63473379cda3b1d0b08bff61017d13376ae19342) | [Issue #2902430 by stefanos.petrakis, joseph.olstad, SergFromSD, kiamlaluno, Ayesh, mcdruid, alexpott: [PHP 7.1] A non-numeric value encountered in theme_pager()](http://drupal.org/node/2902430)
- [x] N/A | [f5f4841dad](https://cgit.drupalcode.org/drupal/commit/?id=f5f4841dad3f0d99fe00cf6de004f5482c24757b) | [Issue #3088938 by DamienMcKenna, webchick, mcdruid: Update the D7 maintainers list](http://drupal.org/node/3088938)
- [x] N/A | [4c451a7347](https://cgit.drupalcode.org/drupal/commit/?id=4c451a73479e86b72e0e7ecd009c0dfb43f0b4ae) | [Issue #3097342 by mcdruid, Fabianx: Prepare Drupal 7.68 (CHANGELOG.txt)](http://drupal.org/node/3097342)
- [x] N/A | [6f60277f75](https://cgit.drupalcode.org/drupal/commit/?id=6f60277f75ef67188c876d53eaab1984a8bb79f1) | Drupal 7.68
- [x] https://github.com/backdrop/backdrop/commit/ec25d60c71f02218200a817441f235d3e9a3a600 and https://github.com/backdrop/backdrop/commit/1f2722270b3c42464b481fff11ee71ae4fc45e55 | [75689e47e6](https://cgit.drupalcode.org/drupal/commit/?id=75689e47e66de30b11ca26d8018c678c05a028a0) | [SA-CORE-2019-012 by samuel.mortenson, larowlan, pwolanin, Sam152, Jasu_M, David_Rothstein, michieltcs, Ayesh, alexpott, xjm, vijaycs85, mcdruid](https://www.drupal.org/sa-core-2019-012)
- [x] N/A | [2e3449d8b8](https://cgit.drupalcode.org/drupal/commit/?id=2e3449d8b8d15476b6c32f6e8771aad43fc5ca69) | Drupal 7.69

Generated with:
```
git log 7.65..7.69 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"
```

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/3588 will need a change record. It is a crossport of a Drupal 8.4.x backport: https://www.drupal.org/project/drupal/issues/1892654

D7 change record: https://www.drupal.org/node/3098694

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/3590 will also need a change record: https://www.drupal.org/project/drupal/issues/2814031

D7 change record: https://www.drupal.org/node/3098661

**Comment by klonos** [comment]
Can I please have a second pair of eyes on https://git.drupalcode.org/project/drupal/-/commit/5f67268ed94034dbe5df600b6067b1d40e62d73a ...it seems to me that we've inherited all that from D8; but I could be wrong and we might need some of the changes in that commit.

**Comment by klonos** [comment]
Was https://www.drupal.org/sa-core-2019-007 N/A to us? I believe so, but cannot find an announcement for it 🤷🏼

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/3599 was meant to fix http://drupal.org/node/2902430, but it turned out that we were missing the entire `pager.test` file in Backdrop for some reason. Please see PR for additional comments: https://github.com/backdrop/backdrop/pull/3599

**Comment by indigoxela** [comment]
Re "theme_table() should accept an optional 'footer' variable and produce <tfoot>", PR https://github.com/backdrop/backdrop/pull/3588

That's a nice one (tfoot, yay!).

I did a quick local check in a template file with this array:

```
  $data = array(
    'header' => array('foo', 'bar', 'baz'),
    'rows' => array(array('1', '2', '3'), array('4', '5', '6')),
    'footer' => array(array('f1', 'f2', 'f3'), array('f4', 'f5', 'f6')),
    'attributes' => array('class' => array('mycustom-class')),
    'caption' => 'My caption',
  );
  $foo = theme('table', $data);

  print $foo;
```
Works like a charm. @klonos I've left some comments on your PR.

**Comment by indigoxela** [comment]
Re "Skip module_invoke/module_hook in calling hook_watchdog (excessive function_exist)", PR https://github.com/backdrop/backdrop/pull/3589

Code LGTM :+1:

**Comment by indigoxela** [comment]
Re "In backdrop_http_request(), allow passing data as array", PR https://github.com/backdrop/backdrop/pull/3590

Code LGTM :+1:

**Comment by indigoxela** [comment]
Re " Issue 3055805: .htaccess file generated by file.inc doesn't cover PHP 7", PR https://github.com/backdrop/backdrop/pull/3596

Code LGTM :+1: (I was actually surprised that this isn't in B core yet.)

**Comment by indigoxela** [comment]
Re "Create "scripts" element to align rendering workflow to how "styles" are handled"

I agree it's not applicable. The D7 commit introduces function drupal_pre_render_scripts(), but backdrop_pre_render_scripts() already exists, as we inherited it from early D8. Nothing to do for us, I think. Marking as NA.

**Comment by indigoxela** [comment]
Re "SA-CORE-2019-007 by Blaklis, oliver.hader, alexpott, mlhess, tim.plunkett, dsnopek, xjm".

Backdrop took a different approach regarding phar, see [this commit](https://github.com/backdrop/backdrop/commit/a62c56aef1a650852fb871d38c70058cfcacb841). I agree, it's not applicable. But maybe @quicksketch could better explain that.

**Comment by indigoxela** [comment]
Re "Issue #2966335 by mcdruid, dvandijk, David_Rothstein: Avoid DrupalRequestSanitizer not found fatal error when bootstrap phase order is changed".

The problem isn't reproducible with Backdrop, as the Domain Access module hasn't been ported.

But it's not applicable anyway. The fatal error because of a missing include as in D7 can never happen with Backdrop. In our case function _backdrop_bootstrap_sanitize_request() ships with the same file and we don't need to include anything.

**Comment by indigoxela** [comment]
Re backdrop/backdrop#3598 | 4d080b6fc0 | Issue #2171113 by Pol, wiifm, mw4ll4c3, David_Rothstein, douggreen, Fabianx: Settings returned via ajax are not run through hook_js_alter()

I have trouble to reproduce. Somebody else please take over...

**Comment by indigoxela** [comment]
Re  backdrop/backdrop#3599 | 63473379cd | Issue #2902430 by stefanos.petrakis, joseph.olstad, SergFromSD, kiamlaluno, Ayesh, mcdruid, alexpott: [PHP 7.1] A non-numeric value encountered in theme_pager()

Same problem, I've no clue how to reproduce it in Backdrop

**Comment by indigoxela** [comment]
Re backdrop/backdrop#3597 | 44fecf2115 | Issue #3025335 by mcdruid, mfb, joseph.olstad, Fabianx, kiamlaluno, Pol: [PHP 7.3] Cannot change session id when session is active

I belief, this has already been fixed in https://github.com/backdrop/backdrop-issues/issues/3700

**Comment by klonos** [comment]
> I belief, this has already been fixed in #3700

I could be wrong, but https://github.com/backdrop/backdrop/pull/3597 seems like a follow-up + adds tests.

**Comment by indigoxela** [comment]
> backdrop/backdrop#3597 seems like a follow-up + adds tests.

Fair enough, makes sense.

**Comment by quicksketch** [comment]
Thanks to the extraordinary teamwork between @klonos and @indigoxela, every one of these PRs has been reviewed and is ready to go. I did a few minor adjustments:

- https://github.com/backdrop/backdrop-issues/issues/5048 is not yet fixed, but we have a dedicated issue for it, so we can close this main porting issue.
- I made a [change record](https://docs.backdropcms.org/change-records/backdrop_http_request-can-now-accept-options-data-as-an-array) for the [backdrop_http_request issue](https://github.com/backdrop/backdrop/pull/3590)
- I made a [new PR](https://github.com/backdrop/backdrop/pull/3624) for the theme_pager issue and merged that version instead of the original.

Thanks so much! This set of cross-ports is done.
