### ISSUE TITLE
Backdrop 1.17.7 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5055]
Release scheduled for Apr 21, 2021 2pm - 5pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton
  - [x] Include a short, descriptive summary of the release, for example:
    - "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
    - or, "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    - Before the milestone has been closed:
      * clean up issue titles for fixed issues.
    - Once the milestone has been closed:
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
- [x] Draft Security Advisories @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A. [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)

## See Also

- [Checklist for 1.18.3 release](https://github.com/backdrop/backdrop-issues/issues/5056)

**Comment by jenlampton** [comment]
Draft release notes:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

* [Backdrop core - Critical - Cross-site scripting - SA-CORE-2021-002](https://backdropcms.org/security/backdrop-sa-core-2021-002)

## Notes for updating

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

## Changes since 1.17.6

* TBD

**Comment by quicksketch** [comment]
Release tag is cut for 1.17.7: https://github.com/backdrop/backdrop/releases/tag/1.17.7

**Comment by jenlampton** [comment]
Published https://github.com/backdrop/backdrop/releases/tag/1.17.7
