### ISSUE TITLE
Backdrop 1.18.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5056]
Release scheduled for Apr 21, 2021 2pm - 5pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton
- [x] Draft Release notes @jenlampton
  - [x] Include a short, descriptive summary of the release, for example:
    - "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    - Before the milestone has been closed:
      - [x] Re-word issue titles to indicate that the problems have been fixed.
    - Once the milestone has been closed:
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
- [x] Draft Security Advisories @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton
- [x] Update the front page download link on b.org @jenlampton
- [ ] Tweet that a new release is out @stpaultim 
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A. [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--pantheon-upstream.md) @herbdool 
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md)  ?? (needs a volunteer)
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] Update the Security Advisory with CVE @jenlampton 

## Backdrop Website updates

- [x] backdropcms.org (assign to @jenlampton)
- [x] api.backdropcms.org (assign to @jenlampton)
- [x] events.backdropcms.org (assign to @jenlampton)
- [x] forum.backdropcms.org (assign to @jenlampton)
- [x] localize.backdropcms.org (assign to @jenlampton)

## See Also
- [Checklist for previous minor version](https://github.com/backdrop/backdrop-issues/issues/5055)

**Comment by herbdool** [comment]
@jenlampton I'm okay with doing Pantheon and Composer. Platform.sh might be straightforward too. But I'd prefer not to the do the Docker.

**Comment by jenlampton** [comment]
Draft release notes:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

* [Backdrop core - Critical - Cross-site scripting - SA-CORE-2021-002](https://backdropcms.org/security/backdrop-sa-core-2021-002)

## Notes for updating

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

## Changes since 1.18.2

* TBD

**Comment by quicksketch** [comment]
Release notes look good, thanks @jenlampton! You even got that `module_implements()` issue that was just merged about an hour ago. Could you add the issue number links for the non-security issues?

Tag has been cut for https://github.com/backdrop/backdrop/releases/tag/1.18.3

**Comment by jenlampton** [comment]
yep.

**Comment by jenlampton** [comment]
Published https://github.com/backdrop/backdrop/releases/tag/1.18.3

**Comment by BWPanda** [comment]
Tugboat updated.

**Comment by BWPanda** [comment]
Assuming this can be closed now. Feel free to re-open if not.
