### ISSUE TITLE
[META] [UX] The Configuration page (/admin/config) needs some love.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#506]
This can evolve to be a meta issue if it turns that there's a lot of tasks and we need to keep them separate. So far I see these issues that need to be addressed:
- [ ] #978 The page could use an instant search filter (like on the modules page)
- [ ] #979 Add a "Hide/Show descriptions" link like in D7/D8: 
- [ ] TBD The categories and their containing entries should be in parity with whatever grouping we decide for #494. If we want to "automate" this, we should look at implementing something like #508.
- [x] #1178 Add icons to the config sections for better scanability
- [x] #2828 The categories seem to be in random order. They should be in alphabetical order (unless somebody has another suggestion). and ... 
- [x] #2828 (see #2828)| The items under each category seem to be randomly placed as well. They should be listed alphabetically (unless somebody has another suggestion).
- [x] #2828 We use a two-column layout that is not responsive and by default makes the page unnecessarily long on wide screens. Perhaps we should consider using a responsive grid or an accordion or some other solution that wraps the categories under each other in small screens.

**Comment by jenlampton** [comment]
Is it the groupings on this page that are valuable?  Is it the descriptions of each grouping (which may be hidden on mobile?) or do we just come here because of habit?

We already have a responsive drop-down menu with all these links. If someone knows what link they need to click, why would they come to this page first on mobile (needing an extra page load) rather than popping open the menu and navigating there directly?  I'm not sure I see any value in hiding the descriptions. People generally have no problem scrolling, even on mobile.

As far as I recall, the groupings on this page aren't "random" either. Specific ones were put at the top of the page because they were thought to be more important than the other ones -the organization was added after usability tests during early Drupal 7 development. I'm not sure how accurate those assumptions were (or still are), but the page was organized this way for a reason.

One last thought: the way I navigate this page currently is by knowing that the performance settings are half way down on the right hand side. Let's make sure that if we break these habits for people we have a good reason, and a better alternative order :)

**Comment by klonos** [comment]
Good points @jenlampton...

> ...or do we just come here because of habit?

I guess habit for most people, but as you said further down your comment:

> ...Let's make sure that if we break these habits for people we have a good reason,...

**Comment by klonos** [comment]
Here's how this page looks with the Seven admin theme...

D7:

![d7-config_page-seven_theme](https://cloud.githubusercontent.com/assets/2423362/8392059/55522064-1d20-11e5-89b1-410842ffc632.png)

D8:

![d8-config_page-seven_theme](https://cloud.githubusercontent.com/assets/2423362/8392063/611f0376-1d20-11e5-92d4-348cca8fb6a8.png)

Backdrop:

![bd-config_page-seven_theme](https://cloud.githubusercontent.com/assets/2423362/8392065/6d8c60ae-1d20-11e5-9aa9-5b66be1933b7.png)

**Comment by klonos** [comment]
...despite the minor changes, all same all. Here's how the same page looks with the [Adminimal](https://www.drupal.org/project/adminimal_theme) theme (my theme of choice for the backend of my sites):

![d7-config_page-adminimal_theme](https://cloud.githubusercontent.com/assets/2423362/8392081/c31e7552-1d20-11e5-8ecf-2fd2f450047c.png)

**Comment by klonos** [comment]
> ...the way I navigate this page currently is by knowing that the performance settings are half way down on the right hand side. Let's make sure that if we break these habits for people we have a good reason, and a better alternative order :)

I think that the addition of icons in the Adminimal theme does not require people to "know" where to find things - it allows finding them with a visual quick scan. Of course #978 would also greatly help to that end.

**Comment by klonos** [comment]
[Rubik](https://www.drupal.org/project/rubik) is another admin theme that makes use of category icons for the config page among other admin pages. Also notice the search filter (#978) as well as the hide/show descriptions toggle (#979) (though none of them are not "instant" - you have to submit the form):

![d7-config_page-rubik_theme](https://cloud.githubusercontent.com/assets/2423362/8392112/17c03d10-1d22-11e5-9820-55b5e9695853.png)

**Comment by wesruv** [comment]
@klonos++
As usual your screenshots and descriptions are super helpful, thanks for that... again :smile:

**Comment by klonos** [comment]
@wesruv yeah, over the years in the d.org issue queue I've figured that it's easier for people to get the point if you show things with screenies (where applicable of course) + edit them a bit to point specific elements. Same applies to Backdrop GitHub queue I guess. Visual is better.

To the issue at hand... I believe that with the choice of admin theme, something along the lines of Adminimal would suit better (simple, black and white icons instead of the more "radiant" used in Rubic).

**Comment by wesruv** [comment]
So I started working on this, and I'm at a stopping point, realizing now that I've addressed something that's not necessarily on point... but worth showing never the less.

I liked @klonos' (and Adminimal and other sub themes') idea of adding icons to the configuration page to help identification. If this becomes responsive it may effect the location/ordering of some of these elements, so the page would be easier to scan with graphics over just plain text.

After I did that it seemed like I should also be applying these icons to pages in these sections... so I've now taken a ticket that asked for a responsive layout on configuration and made it about iconography across Backdrop config... lol

I'll be working on the layout as well, I'll make sure to get that in a different branch. Here are some screenshots of the work, the icons are mostly from fontawesome, some are modified versions of fontawesome icons so they make more sense next to each other.

### Configuration page
![configuration l backdropdev com](https://cloud.githubusercontent.com/assets/5607236/9841549/1b33cfc2-5a6f-11e5-854c-c656e34fb314.png)

### Performance
![performance l backdropdev com](https://cloud.githubusercontent.com/assets/5607236/9841560/3d8fe97a-5a6f-11e5-9755-524df5dafbf6.png)

### Permissions
![permissions l backdropdev com](https://cloud.githubusercontent.com/assets/5607236/9841567/46f60a94-5a6f-11e5-969a-112e4fe406e9.png)

Let me know what you all think, if this is worth keeping around or not.

**Comment by wesruv** [comment]
Ahh, I guess this ticket is a meta about the config page, never the less... now I made it an admin-theme wide change (maybe) :stuck_out_tongue:

**Comment by klonos** [comment]
Lovin' it!!! :heart: :+1:

Can I please haz iconz on the admin bar menu???

**Comment by Graham-72** [comment]
:+1:

**Comment by klonos** [comment]
I think it's best that we moved to a separate, dedicated issue since this is a meta: #1178

I've copied all my lengthy comments (mainly due to screenshots attached) over to that issue and deleted them from this one. This keeps the meta as clean as possible with less scrolling. Can you guys please do the same and copy your comments there? Thanx.

**Comment by klonos** [comment]
...added the new issue to the list of tasks of this meta.

**Comment by jenlampton** [comment]
I must admit, I do really like the icons. Even in the admin bar. But I'm worried about what happens as contrib adds new categories. Do we have a default "settings" icon that we use for everything that's not defined? Or do we slowly add more icons into core over time as contrib proves categories to be good ones?  Or do we let each category be defined along with an icon?

**Comment by wesruv** [comment]
@jenlampton https://github.com/backdrop/backdrop-issues/issues/1178#issuecomment-141276162

**Comment by wesruv** [comment]
I mocked up what it'd look like in the admin bar, it looks _really_ busy. If we had an 'mega-menu'/'uber-nav' (http://www.smileycat.com/miaow/archives/images/megamenus/vwo.png) it'd work just fine, but with the current dropdown it doesn't work.

**Comment by wesruv** [comment]
I need to check if this ticket is basically done... I remember doing some responsive work on this page, but I can't remember if that was merged.

**Comment by klonos** [comment]
Can't wait to test this on a PR sandbox now that we have that!
