### ISSUE TITLE
[META] Full PHP 8 Support

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5076]
Meta ticket to track complete PHP 8 Support

Issues:

* [x] #5325
* [x] #5312 Layout: Layout Interface Test (LayoutInterfaceTest) 1201 passes, 91 fails, 10 exceptions
* [x] Installer (module): Installer UI tests (InstallerBrowserAdministrationTestCase) 139 passes, 12 fails, 0 exceptions (fixed in https://github.com/backdrop/backdrop-issues/issues/5205)
* [x]  #5319 Upgrade path: Language upgrade test (LanguageUpgradePathTestCase) 12 passes, 13 fails, 5 exceptions
* [x] #5310 Form API: Form element validation (FormsTestCase) 616 passes, 3 fails, 0 exceptions
* [x] #5313 Views Handlers: Filter: in_operator (ViewsHandlerFilterInOperator) 7 passes, 4 fails, 4 exceptions
* [x] #5314 Views Plugins: Cache (ViewsCacheTest) 19 passes, 0 fails, 12 exceptions + Field API: Views fields for Field API (FieldViewsFieldTest) 21 passes, 3 fails, 0 exceptions
* [x] https://github.com/backdrop/backdrop-issues/issues/4772 - Initial PHP 8 support (PDO, Date, Comment, and SimpleTest)
* [x] https://github.com/backdrop/backdrop-issues/issues/5305 Views exposed filter result with checkbox

There are a number of Drupal 7 patches we can pull in directly as PRs.

In the case of cross-ports, just making a PR and providing the link here in this summary should be sufficient. Backdrop-specific problems that need discussion should have their own issue numbers.

**Comment by klonos** [comment]
> There are a number of Drupal 7 patches we can pull in directly as PRs.

Some of them are already linked as PRs in #5042 😉 ...I would like to get those cross-ports out of the way, and then move on to the next chunk please (issue to be created).

**Comment by cellear** [comment]
During the status meeting today, @quicksketch pointed me towards this issue (if I heard right) as a good one to dive into to do a little programming, but...it's not clear to me what I should do.  I fired up a Lando instance with PHP 8.0.3 running 1.20.x-dev, and it seemed to run without errors.  Is there something that needs doing that I could take a swing at?

**Comment by laryn** [comment]
@cellear Do the tests run okay? It might be worth trying to run all the core tests and see if anything crashes.

**Comment by quicksketch** [comment]
For running the tests, this is what I do.

I add a tooling command to the `.lando.yml` file like this (update your local URL as needed):

```
name: backdrop
recipe: backdrop
config:
  webroot: .
  php: '8.0'
tooling:
  run-tests:
    service: appserver
    description: Runs Backdrop SimpleTest tests
    cmd: /app/core/scripts/run-tests.sh --url http://backdrop.lndo.site --force --verbose
```

Then run the testing command with: `lando run-tests --all --cache --concurrency 10`

Certain tests will fail. Finding a test that fails, target running that one specifically, such as `lando run-tests --cache BootstrapPageCacheTestCase`. Make adjustments as needed to get the test running, usually minor syntax changes required by PHP 8. Make a separate PR for each reasonably grouped set of functionality that needs updating.

**Comment by indigoxela** [comment]
A quick idea, why not using my experimental GitHub Actions branch for tests? The advantage: test results are publicly available.
(On my own dev the tests would run painfully slow and nobody else has access to results.)

So I updated/rebased it an switched to php 8. Result: several failures (as expected).

[Link to overview](https://github.com/indigoxela/backdrop/actions/runs/1085021011)

Failed tests:

- Locale: Translation import (LocaleImportFunctionalTest) 133 passes, 2 fails, 0 exceptions
- Field API: Views fields for Field API (FieldViewsFieldTest) 21 passes, 3 fails, 0 exceptions
- Installer (module): Installer UI tests (InstallerBrowserAdministrationTestCase) 139 passes, 12 fails, 0 exceptions
- Database: Transaction tests (DatabaseTransactionTestCase) 74 passes, 0 fails, and 1 exception
- Form API: Form element validation (FormsTestCase) 616 passes, 3 fails, 0 exceptions
- Views Handlers: Filter: in_operator (ViewsHandlerFilterInOperator) 7 passes, 4 fails, 4 exceptions
- Views Plugins: Cache (ViewsCacheTest) 19 passes, 0 fails, 12 exceptions
- Layout: Layout Interface Test (LayoutInterfaceTest) 1201 passes, 91 fails, 10 exceptions

Helpful?

**Comment by quicksketch** [comment]
To help with identifying PHP 8 issues that need to be fixed, I've filed a PR at https://github.com/backdrop/backdrop/pull/3721 that runs GitHub Actions against PHP 8 only. We can use that as a ongoing PR that we update intermittently to check for a complete list of failures on PHP 8.

**Comment by indigoxela** [comment]
Some progress here :smile:

I created individual issues, although it's mostly "only" cross-ports, hope that's OK. Probably because I'm a dedicated user of git blame and find it confusing if the actual issue of a change is unclear.
(I don't find views cross-ports so trivial, btw.)

**Comment by quicksketch** [comment]
Thanks soooo much @indigoxela! All the PRs you filed looked great to me, and thanks @klonos for reviewing them! I've merged all of them.

I filed a PR for the "help wanted" issue at https://github.com/backdrop/backdrop-issues/issues/5312.

We're getting really close here!
