### ISSUE TITLE
Backdrop 1.18.4 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5087]
Release scheduled for May 15th, 2021 5pm - 7pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton
- [x] Review all closed issues in milestone: @jenlampton 
      - Issue titles sould be in complete sentences, ending with a period.
      - Bug fixe issue titles should start with "Fix" and include a complete, but very brief summary of the problem.
      - Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @quicksketch 
- [x] Draft Release notes @jenlampton
  - [x] Include a short, descriptive summary of the release, for example:
    - "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
    - or, "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include change log since last version:
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 

## See Also

- [Checklist for 1.19.0 release](https://github.com/backdrop/backdrop-issues/issues/5088)

**Comment by jenlampton** [comment]
Draft release notes:
---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does not need to be run.

## Changes since 1.18.3

* TBD

**Comment by quicksketch** [comment]
All issues are merged for this release. I cut the release tag at https://github.com/backdrop/backdrop/releases/tag/1.18.4

**Comment by jenlampton** [comment]
Release notes added, and release published: https://github.com/backdrop/backdrop/releases/tag/1.18.4
