### ISSUE TITLE
Backdrop 1.19.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5088]
Scheduled for May 15, 2021 5am - 7pm PT

## Pre-release tasks

- [x] Merge minor release commits @quicksketch 
- [x] Move all unfinished issues to the next minor release milestone @quicksketch 
- [x] Review all closed issues in milestone: @jenlampton 
      - Issue titles sould be in complete sentences, ending with a period.
      - Bug fixe issue titles should start with "Fix" and include a complete, but very brief summary of the problem.
      - Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      - The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section containing **Notes for updating**
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text "The database update script does **not** need to be run."
        * or "It will be necessary to run the update script (located at /update.php) for this release."
    - [x] Include changelog since last version:
        * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
        * Select the most recent time "Release Notes Generator" has been run.
        * Download the `release-notes` artifact attached to the generator.
        * Unzip the file, and copy/pate contents into release notes draft.
        * Re-word issue titles to indicate that the problems have been fixed.
      - This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Pre-release Publicity + documentation tasks 
**(carried over from the preview release issue)**

- [ ] Review issues for new features @jenlampton 
  - [x] Update the issue title (Bugs should start with `Fix` or `Fixed`, new features with `Added` or similar)
  - [x] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [ ] Add a conclusion suitable for blog post + release notes
- [ ] Draft blog post for release on the 15th **needs volunteer**
- [ ] Draft roadmap updates for backdropcms.org @klonos 
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @jenlampton
- [x] Update the roadmap page on b.org @klonos 
- [x] Create a new language template file for the translation server @olafgrabienski 

### Code tasks

- [x] update docs.backdropcms.org to latest version @jenlampton
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--tugboat.md) @bwpanda
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--platformsh-template.md) - @herbdool 
- [ ] Update Composer - @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md) (assign to ??? **needs volunteer**)

### Publicity tasks

- [x] Tweet that a new release is out @jenlampton 
  - Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [ ] Publish blog post **needs volunteer**
- [ ] BLOCKED email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
      * Needs link to blog post
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Code tasks ~ May 29th

- [ ] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--pantheon-upstream.md) @herbdool 

### Publicity tasks ~ May 29th

- [ ] Send a newsletter to subscribers @stpaultim 

### Backdrop Website updates ~ May 29th

- [ ] backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [ ] events.backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton 

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/5087)
* [Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/5078)

**Comment by jenlampton** [comment]
Release notes draft:
---

This release contains several new features as well as a number of bug fixes that have accumulated since the 1.18.3 release. 

**Notes for updating**

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* Running `update.php` should not be necessary when upgrading from 1.18.3 or 1.18.4.

## New features

- Add support for "Relationships" to Layout Contexts [#2134](https://github.com/backdrop/backdrop-issues/issues/2134)
- Introduce "node-by-viewer" and "node-by-anonymous" classes [#4991](https://github.com/backdrop/backdrop-issues/issues/4991)
- Prevent URLs or email addresses turning into links [#1926](https://github.com/backdrop/backdrop-issues/issues/1926)
- [UX] Keep admin_bar sticky at the top of the page by default. [#788](https://github.com/backdrop/backdrop-issues/issues/788)
- PHP 8 Initial Support (PDO, Date, Comment, SimpleTest) [#4772](https://github.com/backdrop/backdrop-issues/issues/4772)
- [UX] Merge all the "Update core/module/theme/layout" pages into a single page. [#2714](https://github.com/backdrop/backdrop-issues/issues/2714)
- [UX] Move the "Add role" to its own form/page, and replace the "Add role" button with a "+ Add role" link (admin UI consistency) [#2742](https://github.com/backdrop/backdrop-issues/issues/2742)

## Bug fixes

- Add support for wildcards in deprecated path redirects [#2833](https://github.com/backdrop/backdrop-issues/issues/2833)

## User experience improvements

- Change Role edit URLs to use the word 'configure' instead. [#4899](https://github.com/backdrop/backdrop-issues/issues/4899)

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.19.0 tag is cut. Release notes looks good. It might be worth noting that although update.php does not need to be run, caches do need to be cleared.

**Comment by jenlampton** [comment]
Release notes added, and release published:
https://github.com/backdrop/backdrop/releases/tag/1.19.0

**Comment by klonos** [comment]
@jenlampton I don't have permissions to edit the release notes, can you please consider making the following changes:

- The current text for "Add support for a 'nolink' class..." has a "within" without specifying what the thing within is. Can we change that to something like: `Text filters: Add support for a 'nolink' class, to prevent URLs and email addresses from being converted to links.`
- the issue number in `follow up to 2134` needs to be linkified
- the issue number in `follow up to 4981` needs to be linkified

**Comment by jenlampton** [comment]
I didn't link the follow up issue numbers because they are linked above,
and I didn't want people clicking on them thinking those were the links for
the issue. I will make the other changes though :)

**Comment by BWPanda** [comment]
Tugboat has been updated. Note that I've updated the process so that Tugboat always points to the latest release now, so the steps to update Tugboat demos have been greatly reduced: https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md (i.e. no more editing the Tugboat repo, making a new tag, creating a new base preview, updating BackdropCMS.org).

**Comment by klonos** [comment]
Wow! Thanks for simplifying that so much @BWPanda 🙏🏼

**Comment by jenlampton** [comment]
> The current text for "Add support for a 'nolink' class..." has a "within" without specifying what the thing within is.

This is grammatically correct. When there isn't anything after the "within" it points backwards to what came before. In `A donut box, with delicious items within.` the meaning is the same as repeating "within the donut box".

**Comment by klonos** [comment]
> ...the meaning is the same as repeating "within the donut box".

Yes, I'm aware of this, but the text was previously:

> Add support for a 'nolink' class to prevent URLs and email addresses within (what?) from being converted to links.

^^ see? That's what did not make sense to me.

**Comment by jenlampton** [comment]
It works just like the donut box, only in this case it's within the `nolink` class.

**Comment by BWPanda** [comment]
How about:

> Allow disabling the automatic linking of URLs and email addresses by wrapping them in a 'nolink' class.

**Comment by jenlampton** [comment]
Titles for new features are supposed to start with "Add" or "Added", but I much prefer the rest of this. Maybe...

> Added optional automatic linking of URLs and email addresses by wrapping them in a 'nolink' class.

**Comment by BWPanda** [comment]
> Added ability to disable the automatic linking of URLs and email addresses by wrapping them in a 'nolink' class.

**Comment by jenlampton** [comment]
Winner!

**Comment by olafgrabienski** [comment]
Created the 1.19 language template file for the translation server.

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop/backdrop-issues/issues/5105
