### ISSUE TITLE
Drupal 7.70-7.75 commits: crossport or mark as NA

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5091]
- [x] N/A | [8833480c8c](https://cgit.drupalcode.org/drupal/commit/?id=8833480c8c818860f0162c5112e26a782be6b036) | Back to dev
- [x] N/A | [97bd4f7203](https://cgit.drupalcode.org/drupal/commit/?id=97bd4f7203e0fda6309f0a7aa4b107c48a908985) | Back to dev.
- [ ] #xx | [edb77684bd](https://cgit.drupalcode.org/drupal/commit/?id=edb77684bd5868fce3fd4415e3be0c8471d2be52) | [Issue #3084935 by kiamlaluno, Taran2L, mcdruid, atheia, Liam Morland: element_children() and DrupalRequestSanitizer::stripDangerousValues() should not use integers as an array](http://drupal.org/node/)
- [ ] #xx | [b20c7a939a](https://cgit.drupalcode.org/drupal/commit/?id=b20c7a939aff7b750482d60f3a49f9f94d4519cb) | [Issue #3084943 by longwave, Taran2L: Pass parameters as implode($glue, $pieces); reverse order is deprecated](http://drupal.org/node/)
- [ ] #xx | [398945d6db](https://cgit.drupalcode.org/drupal/commit/?id=398945d6dbf7013b70d8c7c8bf88f1a1e1920341) | [Issue #3084955 by kiamlaluno, mcdruid, Taran2L: Invalid characters passed for attempted conversion, these have been ignored in _color_unpack()](http://drupal.org/node/)
- [ ] #xx | [ae921e89b1](https://cgit.drupalcode.org/drupal/commit/?id=ae921e89b1059ea25caba37f2e7309d54eec6a1e) | [Issue #3084961 by mcdruid, Taran2L: Trying to access array offset on value of type null in multiple places in pager.inc](http://drupal.org/node/)
- [ ] #xx | [22801c7517](https://cgit.drupalcode.org/drupal/commit/?id=22801c75179c71764bfd9c7f189f01bf4940cca5) | [Revert "Issue #3084935 by kiamlaluno, Taran2L, mcdruid, atheia, Liam Morland: element_children() and DrupalRequestSanitizer::stripDangerousValues() should not use integers as an array"](http://drupal.org/node/)
- [ ] #xx | [dc2c0c3257](https://cgit.drupalcode.org/drupal/commit/?id=dc2c0c3257e60c27766e4f53ea4ba310c4713a88) | [Issue #3119875 by mcdruid, Pere Orga, Jasu_M, Heine, Fabianx, David_Rothstein, alexpott, cashwilliams, tim.plunkett, xjm, pwolanin, larowlan, drumm, dsnopek: Add tests for DrupalRequestSanitizer to Drupal 7](http://drupal.org/node/)
- [ ] #xx | [175c09b9a2](https://cgit.drupalcode.org/drupal/commit/?id=175c09b9a2fc8cb3a8e0c3d0b2054d01ec6494b2) | [Issue #3084935 by mcdruid, kiamlaluno, Taran2L, atheia, Liam Morland: Trying to access array offset on value of type int in element_children() and DrupalRequestSanitizer::stripDangerousValues()](http://drupal.org/node/)
- [ ] #xx | [23b14e9dfc](https://cgit.drupalcode.org/drupal/commit/?id=23b14e9dfc87bff0429a2d2e6470475e48de4d30) | [Issue #3084980 by mcdruid, Taran2L: Trying to access array offset on value of type null in path_delete()](http://drupal.org/node/)
- [ ] #xx | [8b0048c67f](https://cgit.drupalcode.org/drupal/commit/?id=8b0048c67f59d63286472c61f8795edf8c5e8511) | [Issue #3085088 by mcdruid, Taran2L: menu_get_item() might return FALSE; calling code should take account of this](http://drupal.org/node/)
- [ ] #xx | [942c3944d8](https://cgit.drupalcode.org/drupal/commit/?id=942c3944d85020d8aa9576d75417d38087860015) | [Issue #3084965 by mcdruid, Taran2L, Fabianx: Trying to access array offset on value of type bool in search_excerpt()](http://drupal.org/node/)
- [ ] #xx | [6c656d75e3](https://cgit.drupalcode.org/drupal/commit/?id=6c656d75e3011848372decee371546422d7ca15a) | [Issue #3084945 by Taran2L, mcdruid, kiamlaluno: Trying to access array offset on value of type null in _batch_finished()](http://drupal.org/node/)
- [ ] #xx | [460ff5dc3c](https://cgit.drupalcode.org/drupal/commit/?id=460ff5dc3c577d6139b37bc3467ab5b742371626) | [Issue #3084953 by Taran2L, kiamlaluno: Trying to access array offset on value of type null in _drupal_build_css_path()](http://drupal.org/node/)
- [ ] #xx | [230c34e7b8](https://cgit.drupalcode.org/drupal/commit/?id=230c34e7b88d1e2e8f14adf16b7901ba6cae4348) | [Issue #3126140 by joseph.olstad, Taran2L, longwave, mcdruid, Ayesh, Fabianx, MustangGB: PHP 7.4 notice in run-tests.sh](http://drupal.org/node/)
- [ ] #xx | [e8318811e9](https://cgit.drupalcode.org/drupal/commit/?id=e8318811e96510a88354ac3563d430fe412bc7a8) | [Issue #3118301 by jacob.embree, joachim: Curly brace syntax for accessing array elements and string offsets has been deprecated in PHP 7.4](http://drupal.org/node/)
- [ ] #xx | [78234c808f](https://cgit.drupalcode.org/drupal/commit/?id=78234c808f1efa11df99da03db5e11b4241c6b6d) | [Issue #3085163 by mcdruid, Taran2L, Steven Jones: Comment module causes PHP 7.4 Notices on uninstall](http://drupal.org/node/)
- [ ] #xx | [9c181e3915](https://cgit.drupalcode.org/drupal/commit/?id=9c181e39151a03df7d76fca35c2c22f03905c6c5) | [Issue #3126133 by Taran2L: NumberFieldTestCase uses non-existent formatter number_float](http://drupal.org/node/)
- [ ] #xx | [30c906a120](https://cgit.drupalcode.org/drupal/commit/?id=30c906a1204ecbec3123044b3837741bd636e23c) | [Issue #3126138 by Taran2L: taxonomy_update_7004() uses non-existent widget select](http://drupal.org/node/)
- [ ] #xx | [d647c02a70](https://cgit.drupalcode.org/drupal/commit/?id=d647c02a7023aac8793521c8adb118c11585b94b) | [Issue #3125824 by Taran2L, mcdruid: Trying to access array offset on value of type null in forum_get_topics()](http://drupal.org/node/)
- [ ] #xx | [4dafac8677](https://cgit.drupalcode.org/drupal/commit/?id=4dafac867732b6e6ffdac3f4e2e54612026208f8) | [Issue #3085151 by Taran2L, amoebanath, kiamlaluno, Steven Jones, nishantghetiya, izmeez, mcdruid, Fabianx: field_ui_display_overview_form() expects to always get an array from field_info_formatter_types()](http://drupal.org/node/)
- [ ] #xx | [aea09872a3](https://cgit.drupalcode.org/drupal/commit/?id=aea09872a3db16ee4606865d0cf52f45b90d1a5e) | [Issue #3087121 by Taran2L, kiamlaluno, mcdruid, klausi, Fabianx, Steven Jones, MustangGB: SystemValidTokenTest is failing on PHP 7.4 when drupal_hmac_base64() is called incorrectly](http://drupal.org/node/)
- [x] N/A | [36289d8ef8](https://cgit.drupalcode.org/drupal/commit/?id=36289d8ef8d753698254610213f6cad0fd0ff9e8) | Back to dev.
- [ ] #xx | [7430460c2c](https://cgit.drupalcode.org/drupal/commit/?id=7430460c2c55e4ac60b421b1790f1fe200eba79f) | [Issue #3085148 by Taran2L, mcdruid, kiamlaluno: Fix field_test_field_attach_delete_bundle()](http://drupal.org/node/)
- [ ] #xx | [9ed3f679ef](https://cgit.drupalcode.org/drupal/commit/?id=9ed3f679efd39ac7ced073c7916184087507299a) | [Issue #2788565 by lhuria94, shashikant_chauhan, sjerdo, ravikk-drupal, joachim, longwave: sample code for callback_filter_process() and callback_filter_prepare() should not include deprecated regex option](http://drupal.org/node/)
- [ ] #xx | [b79f40a8c6](https://cgit.drupalcode.org/drupal/commit/?id=b79f40a8c6795aa51a81ba68799c5f1b5a1fb279) | [Issue #3085098 by longwave, Taran2L, sjerdo, Dinesh18, oliver.hader: PHP Phar Stream Wrapper should be updated (PHP7.4 support, drop fileinfo dependency)](http://drupal.org/node/)
- [ ] #xx | [18d4dd381d](https://cgit.drupalcode.org/drupal/commit/?id=18d4dd381d4e7300f6100d9ee2bb0f75009f56a7) | [Issue #3126312 by joseph.olstad, ravikk-drupal, mcdruid, mohangathala, jungle, Taran2L, Fabianx: Since PHP7 func_get_args() no longer reports the original value as passed to a parameter, so call it early](http://drupal.org/node/)
- [ ] #xx | [4e87afee1e](https://cgit.drupalcode.org/drupal/commit/?id=4e87afee1ea3aa5379b1726b53015545fcaa7d66) | [Issue #3143016 by dsnopek, mcdruid, effulgentsia, philltran, Fabianx, lauriii: Chrome 83 cancels jquery.form ajax requests over https](http://drupal.org/node/)
- [x] N/A | [4558afc32e](https://cgit.drupalcode.org/drupal/commit/?id=4558afc32ea3f76b4d5fe5a1dbf74c1b14c5d8c3) | [Drupal 7.71](https://www.drupal.org/project/drupal/releases/7.71)
- [ ] #xx | [f0027e05b4](https://cgit.drupalcode.org/drupal/commit/?id=f0027e05b4787bc49f102295c4662db550e9b461) | [SA-CORE-2020-004 by samuel.mortenson, DorTumarkin, greggles, xjm, larowlan, webchick, pwolanin, dawehner, mcdruid, alexpott, dsnopek](https://www.drupal.org/sa-core-2020-004)
- [x] N/A | [91f479be93](https://cgit.drupalcode.org/drupal/commit/?id=91f479be9314b0a87ab8643dc7021da911d4e81e) | [Drupal 7.72](https://www.drupal.org/project/drupal/releases/7.72)
- [ ] #xx | [cd3721550d](https://cgit.drupalcode.org/drupal/commit/?id=cd3721550d988240ef6e682bd1cae2939c6e9e5a) | [SA-CORE-2020-007 by samuel.mortenson, nod_, larowlan, dsnopek, catch, effulgentsia, mcdruid](https://www.drupal.org/sa-core-2020-007)
- [x] N/A | [cbd404ebdd](https://cgit.drupalcode.org/drupal/commit/?id=cbd404ebdd22df0fc819f356895bd946db4e7fe9) | [Drupal 7.73](https://www.drupal.org/project/drupal/releases/7.73)
- [ ] #xx | [0263ea89cf](https://cgit.drupalcode.org/drupal/commit/?id=0263ea89cfff630262b8c0bc6d9c629c42aa7a84) | [SA-CORE-2020-012 by ufku, mrf, fgm, samuel.mortenson, dww, Heine, mlhess, David_Rothstein, pwolanin, xjm, fgm, stefan.r, dsnopek, rickmanelius, David Strauss, tedbow, alexpott, dww, larowlan, kim.pepper, Wim Leers, quicksketch, mcdruid, Fabianx, effulgentsia, drumm, pandaski, Mixologic](https://www.drupal.org/sa-core-2020-012)
- [x] N/A | [f941729699](https://cgit.drupalcode.org/drupal/commit/?id=f941729699e7f49901b30f3aaa71449e44a984c0) | [Drupal 7.74](https://www.drupal.org/project/drupal/releases/7.74)
- [ ] #xx | [6435c5fabb](https://cgit.drupalcode.org/drupal/commit/?id=6435c5fabba53d2275c4ce7c889ad2bb1d49dff7) | [SA-CORE-2020-013 by luke.stewart, xjm, larowlan, mcdruid, drumm, mlhess](https://www.drupal.org/sa-core-2020-013)
- [x] N/A | [98b9dd73fb](https://cgit.drupalcode.org/drupal/commit/?id=98b9dd73fb606159242c98a57aa9068d8fa3328d) | [Drupal 7.75](https://www.drupal.org/project/drupal/releases/7.75)

Generated with:

```
git log 7.70..7.75 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://cgit.drupalcode.org/drupal/commit/?id=%H) | [%s](http://drupal.org/node/)"
```

**Comment by klonos** [comment]
[Issue #3119875: Add tests for DrupalRequestSanitizer to Drupal 7](http://drupal.org/node/3119875) has basically added https://git.drupalcode.org/project/drupal/-/blob/7.x/includes/request-sanitizer.inc with [dc2c0c3257](https://cgit.drupalcode.org/drupal/commit/?id=dc2c0c3257e60c27766e4f53ea4ba310c4713a88), which is meant to be the same as the tests we've added with https://github.com/backdrop/backdrop/commit/ae93eccb2aafb58e887ec5acf4c46b53b6963f67#diff-4fa64da2406497325271e58ee7eb243dfbef3ec876715b8953859490ae357242R2507.

At first look, it seems that our tests might be slightly less, but I could be wrong about it. @quicksketch or anyone else should confirm.

**Comment by klonos** [comment]
I think that https://git.drupalcode.org/project/drupal/commit/23b14e9dfc87bff0429a2d2e6470475e48de4d30 is N/A to Backdrop. We have  https://github.com/backdrop/backdrop/commit/62a34fcfd736d43395b59e2fd59f830c63601241in place since 2016 + tests for it, and no problems reported.

I could be wrong though, so need someone to double-check and confirm.

**Comment by klonos** [comment]
@bugfolder this is the list :)

**Comment by quicksketch** [comment]
De-milestoning this as it's been bumped many times.
