### ISSUE TITLE
Backdrop 1.18.5 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5104]
Release scheduled for May 26, 2021 3pm - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
    * or, "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] N/A Include changelog since last version:
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [ ] [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) - (Drupal?)

## See Also

- [Checklist for 1.19.1 release](https://github.com/backdrop/backdrop-issues/issues/5105)

**Comment by jenlampton** [comment]
Draft release notes:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

This release fixes a security vulnerability. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

* Backdrop core - Moderately critical - Cross Site Scripting - [SA-BACKDROP-CORE-2021-003]()

No other fixes are included.

**Important update information**
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Comment by jenlampton** [comment]
SA draft: https://backdropcms.org/security/backdrop-sa-core-2021-003

**Comment by jenlampton** [comment]
Release is out https://github.com/backdrop/backdrop/releases/tag/1.18.5
