### ISSUE TITLE
Backdrop 1.19.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5105]
Release scheduled for May 26, 2021 3pm - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  - Issue titles should include a complete, but very brief summary of the problem.
  - Issue titles sould be in complete sentences, ending with a period.
  - Bug issue titles should start with `Fix` or `Fixed`,
  - New fearure issue titles should start with `Add` or `Added`.
  - Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
    - or, "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      - Use the text "The database update script does **not** need to be run."
      - or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] N/A/Include changelog since last version:
- [x] Draft Security Advisories 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org."
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) - CKE?

## Immediate Post-release tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--pantheon-upstream.md) @herbdool 
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/master/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [ ] Update the Security Advisory with CVE @jenlampton 

## Backdrop Website updates

- [x] backdropcms.org @jenlampton 
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 
- [x] N/A localize.backdropcms.org @jenlampton 

## See Also

- [Checklist for previous minor version](https://github.com/backdrop/backdrop-issues/issues/5104)

**Comment by jenlampton** [comment]
Draft release notes:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

This release fixes a security vulnerability. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

* Backdrop core - Moderately critical - Cross Site Scripting - [SA-BACKDROP-CORE-2021-003]()

No other fixes are included.

**Important update information**
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Comment by jenlampton** [comment]
SA draft: https://backdropcms.org/security/backdrop-sa-core-2021-003

**Comment by quicksketch** [comment]
Release notes and SA look great.

Tag is cut at https://github.com/backdrop/backdrop/releases/tag/1.19.1

**Comment by jenlampton** [comment]
Release is out: https://github.com/backdrop/backdrop/releases/tag/1.18.5

**Comment by jenlampton** [comment]
Release is out: https://github.com/backdrop/backdrop/releases/tag/1.19.1

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop/backdrop-issues/issues/5133
