### ISSUE TITLE
Backdrop 1.19.2 Release Checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5133]
Release scheduled for July 21, 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (assign to klonos / jenlampton / stpaultim )
  - Issue titles should include a complete, but very brief summary of the problem.
  - Issue titles sould be in complete sentences, ending with a period.
  - Bug issue titles should start with `Fix` or `Fixed`,
  - New feature issue titles should start with `Add` or `Added`.
  - Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (assign to quicksketch / serundeputy / herbdool / bwpanda)
- [x] Draft Release notes (assign to jenlampton / herbdool / serundeputy / quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
        * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
        * or, "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
        * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text "The database update script does **not** need to be run."
        * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
        * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
        * Select the most recent time "Release Notes Generator" has been run.
        * Download the `release-notes` artifact attached to the generator.
        * Unzip the file, and copy/pate contents into release notes draft.
        * Remove any square bracets in the titles, and move those issues to their own section.

- [x] Draft Security Advisories (assign to stpaultim / klonos / jenlampton / serundeputy / herbdool / quicksketch)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (assign to jenlampton / herbdool / serundeputy / quicksketch)
- [x] Publish Security Advisories on b.org (assign to stpaultim / klonos / jenlampton / herbdool / serundeputy / quicksketch)
- [x] Mark the release node on b.org as a security release (assign to stpaultim / klonos / jenlampton / herbdool / serundeputy / quicksketch)
- [x] ~[Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)~ - Not needed. CVE exists.
- [x] Update the front page download link on b.org @jenlampton
- [x] Tweet that a new release is out @jenlampton
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

- [x] ~Update the Security Advisory with CVE~ CVE was previously included

## Backdrop Website updates

- [x] backdropcms.org @jenlampton
- [x] docs.backdropcms.org @jenlampton
- [x] events.backdropcms.org @jenlampton
- [x] forum.backdropcms.org @jenlampton
- [x] localize.backdropcms.org @jenlampton

## See Also

- 1.18.6 Release: https://github.com/backdrop/backdrop-issues/issues/5134

**Comment by quicksketch** [comment]
Release notes draft

# Backdrop 1.19.2

Security release for Backdrop CMS. This release fixes a security vulnerability. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

Backdrop core - Critical - Third Party Libraries - SA-BACKDROP-CORE-2021-004

This release also contains a number of small bug fixes and improvements.

## Bug fixes

- Views exposed grouped filter of numeric field doesn't show "value" input fields [#5127](https://github.com/backdrop/backdrop-issues/issues/5127)
- Remove trailing slashes from robots.txt [#5122](https://github.com/backdrop/backdrop-issues/issues/5122)
- Change `admin/people` dropbutton operation from "Cancel" to "Cancel account" [#5118](https://github.com/backdrop/backdrop-issues/issues/5118)
- Potential regression for contrib (backup_migrate) caused by initial php 8 support [#5094](https://github.com/backdrop/backdrop-issues/issues/5094)
- Trying to sort NULL array in field_ui_widget_type_options() [#5037](https://github.com/backdrop/backdrop-issues/issues/5037)
- Disable Brotli for pre-compressed CSS and JS [#4748](https://github.com/backdrop/backdrop-issues/issues/4748)

## Documentation updates

- Better documentation for dependencies when enabling, disabling or uninstalling modules [#4872](https://github.com/backdrop/backdrop-issues/issues/4872)
- Documentation for adding keys along with fields is confusing. [#3759](https://github.com/backdrop/backdrop-issues/issues/3759)

## Miscellaneous changes

- [A11Y] Dashboard: incorrect semantic structure in heading tags on the "Welcome to Backdrop" block [#5038](https://github.com/backdrop/backdrop-issues/issues/5038)
- Update Copyright information in License section of README.md [#5029](https://github.com/backdrop/backdrop-issues/issues/5029)
- Rename 'Enable' buttons for display modes [#4890](https://github.com/backdrop/backdrop-issues/issues/4890)
- Change page title name to `Configuration Manager` [#4711](https://github.com/backdrop/backdrop-issues/issues/4711)
- [UX] Automatically clear caches when making changes to the "Who can register accounts?" setting. [#4500](https://github.com/backdrop/backdrop-issues/issues/4500)

**Comment by quicksketch** [comment]
Security Advisory: https://backdropcms.org/security/backdrop-sa-core-2021-004

**Comment by quicksketch** [comment]
The https://github.com/backdrop/backdrop/releases/tag/1.19.2 release is out as well as the security announcement.

**Comment by jenlampton** [comment]
All backdrop sites have been updated to 1.19.2.

**Comment by jenlampton** [comment]
Thank you @herbdool for taking care of our other remote updates :)

**Comment by BWPanda** [comment]
Tugboat updated. Had an issue with updating existing demo sites, raised a ticket with Tugboat in Slack (https://tugboatqa.slack.com/archives/G0151KXPWTF/p1626926449000100). Otherwise new demo sites work fine.

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop/backdrop-issues/issues/5148
