### ISSUE TITLE
Backdrop 1.18.6 Release Checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5134]
Release scheduled for July 21, 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Draft Release notes (assign to jenlampton / herbdool / serundeputy / quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
        * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
        * or, "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
        - [ ] Note if any changes were made to files outside the `core` directory, for example:
          * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
        - [ ] Note if updates (update.php) needs to be run, for example:
          * Use the text "The database update script does **not** need to be run."
          * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
        * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
        * Select the most recent time "Release Notes Generator" has been run.
        * Download the `release-notes` artifact attached to the generator.
        * Unzip the file, and copy/pate contents into release notes draft.
        * Remove any square bracets in the titles, and move those issues to their own section.

- [x] Draft Security Advisories (assign to stpaultim / klonos / jenlampton / serundeputy / herbdool / quicksketch)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (assign to jenlampton / herbdool / serundeputy / quicksketch)
- [x] Publish Security Advisories on b.org (assign to stpaultim / klonos / jenlampton / herbdool / serundeputy / quicksketch)
- [x] Mark the release node on b.org as a security release (assign to stpaultim / klonos / jenlampton / herbdool / serundeputy / quicksketch)
- [x] ~[Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)~ - Not needed. CVE exists.

**Comment by quicksketch** [comment]
The 1.18.6 Release is finished: https://github.com/backdrop/backdrop/releases/tag/1.18.6

We'll continue with the 1.19.2 release in https://github.com/backdrop/backdrop-issues/issues/5133
