### ISSUE TITLE
Backdrop 1.18.7 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5147]
Release scheduled for Aug 12th, 20xx 10am - 12noon PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] N/A Include changelog since last version:
      * "No other changes are included in this release."
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number  @quicksketch 
- [x] Tag for release, and push tag to GitHub  @quicksketch 
- [x] Revert version number back  @quicksketch 
- [ ] Create release notes on GitHub, and publish release @jenlampton 
- [ ] Publish Security Advisories on b.org @jenlampton 
- [ ] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)

## See Also

- [Checklist for 1.19.3 release](https://github.com/backdrop/backdrop-issues/issues/5148)

**Comment by jenlampton** [comment]
Release notes draft:
---

Security release for Backdrop CMS. This release fixes a security vulnerability in a 3rd party library. Sites are urged to upgrade immediately after reading the notes below, and the security announcement:

Backdrop core - Moderately Critical - Third Party Libraries - [SA-BACKDROP-CORE-2021-004](https://backdropcms.org/security/backdrop-sa-core-2021-005)

No other changes are included in this release.

**Important update information**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Comment by quicksketch** [comment]
> Backdrop core - Moderately Critical - Third Party Libraries - SA-BACKDROP-CORE-2021-004

Should be "SA-BACKDROP-CORE-2021-005"

The 1.18.7 tag is cut https://github.com/backdrop/backdrop/releases/tag/1.18.7

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.18.7 is out
