### ISSUE TITLE
Backdrop 1.19.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5148]
Release scheduled for Aug 12th, 2021 10am - 12noon PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone (already there)
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
      * or, "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) - (assign to jenlampton / quicksketch)
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer (@herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [ ] Update the Wikipedia articles @klonos
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] Update the Security Advisory with CVE 

## Backdrop Website updates

- [x] backdropcms.org @jenlampton 
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 
- [x] N/A localize.backdropcms.org

## See Also

- [Checklist for 1.18.7 release](https://github.com/backdrop/backdrop-issues/issues/5147)

**Comment by jenlampton** [comment]
Draft release notes:
---

Security release for Backdrop CMS. This release fixes a security vulnerability in a third party library. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

Backdrop core - Moderately Critical - Third Party Libraries - [SA-BACKDROP-CORE-2021-004](https://backdropcms.org/security/backdrop-sa-core-2021-005)

**Important update information**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

This release also contains a number of small bug fixes and improvements.

TBD

**Comment by findlabnet** [comment]
The database update script does <s>**not**</s> need to be run.
`1 pending update  
system module   
1075 - Set a default value for the "Permissions-Policy: interest-cohort" header. This will make it so that the Google Federated Learning of Cohorts (FLoC) feature that gathers user data without cookies is blocked by default, unless overridden in settings.php. For more information, see the change record at: https:docs.backdropcms.orgchange-recordsheader-added-by-default-to-disable-floc`

**Comment by BWPanda** [comment]
Tugboat updated

**Comment by jenlampton** [comment]
I've updated the release notes, thank you @findlabnet !

**Comment by jenlampton** [comment]
All release tasks have been done with the exception of the Docker update (which we have no maintainer for) and the wikipedia articles, which @klonos can do at any time. Closing ticket!
