### ISSUE TITLE
[META] Core responsive tasks

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#516]
Backdrop aims to be easy to be responsive at install, thanks to Layouts module and responsive tables etc. This should enable any contrib theme to work responsively reasonably well whether as admin theme or site theme. 
This issue is to highlight some areas in core which are not yet reponsified. Most of this is due to tables that havent been made responsive yet. Some others like views, color, and vertical tabs will need some heavier work:

Related issue: #517 Recommendation to move layout CSS from Seven to system.admin.css.
- [x] **Cannot reproduce?** Screenshots on themes page at admin/appearance need max-width
- [x] **Fixed previously** Textarea and textfields need max-width
- [x] #515 Vertical tabs are not responsive
- [x] #671 (???) Local task tabs not responsive
- [ ] Admin bar goes off screen when multiple submenus
- [x] #506 Admin/config needs some love
- [x] #953 Bartik settings page (color module settings) admin/appearance/settings/bartik
- [ ] #2540 Permissions table not responsive.
- [ ] Manage fields table not responsive admin/structure/types/manage/node_type/fields
- [ ] Manage display table not responsive admin/structure/types/manage/node_type/display
- [x] https://github.com/backdrop/backdrop/pull/1138 Views listings table not responsive admin/structure/views
- [x] https://github.com/backdrop/backdrop/pull/1138 Add view admin/structure/views/add
- [x] https://github.com/backdrop/backdrop/pull/1138 View edit pages admin/structure/views/view/view_name
- [ ] Roles table not responsive admin/config/people/roles
- [ ] People fields table not responsive admin/config/people/manage.
- [ ] Date and time formats table not responsive admin/config/regional/date-time
- [ ] Views plugins table not responsive admin/reports/views-plugins
- [ ] Site status page table not responsive admin/reports/status

**Comment by wesruv** [comment]
this++

**Comment by wesruv** [comment]
Whoever wants to help with this, just grab stuff and make a ticket for it. Check it off as a ticket is made and link the ticket here.

**Comment by wesruv** [comment]
I'm taking #506 and #515

**Comment by wesruv** [comment]
Addressed Views UI Here:
https://github.com/backdrop/backdrop/pull/1138

**Comment by wesruv** [comment]
I'm not sure if these are plausible with the current design:
- Manage fields table not responsive admin/structure/types/manage/node_type/fields
- Manage display table not responsive admin/structure/types/manage/node_type/display
- People fields table not responsive admin/config/people/manage.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1138 to address 3 items in the Views UI (checked off in summary). Great job @wesruv!

For more difficult issues like that one we should have sub-issues rather than discussing everything in the PR. Let's make sub-issues for other tasks that don't have them yet once they are started.
