### ISSUE TITLE
[META][UX] Use the words Name / Title / Label / Admin Label consistently in core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5192]
Most admin tables use "Name" for the column header of the things, besides:

   - layouts (`admin/structure/layouts`), where the column header is "Path and layout"
   - things that use the name of the thing as the header:
     - layout templates (`admin/structure/layouts/settings`), where the header is "Template"
     - menus (`admin/structure/menu`), where the header is "Title"
     - blocks (`admin/structure/block`), where the header is "Block"
     - manage displays (`admin/structure/types/manage/%/display`), where the header is "Display modes" (why the plural here?)
   - things that use the name of the thing + the word "name":
     - vocabularies (`admin/structure/taxonomy`), where the header is "Vocabulary name"
     - image styles (`admin/config/media/image-styles`), where the header is "Style name"

   So, should we have the table header be:
   - plain "Name" everywhere (besides layouts - since its a special case, with the table having multiple headers)
   - the actual name of the thing ("Menu", "Block", "Content type", "View", etc.)
   - a combination of the name of the thing + the word "name" ("Menu name", "Block name", "Content type name", "View name", etc.)

## Things we should change:

 - [ ] Change Menu `Title` to `Menu name`
 - [ ] Change Block `Admin label` to `Block name`
 - [ ] Change Display mode `Display mode label` to `Display mode name`

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/3402

**Comment by jenlampton** [comment]
> a combination of the name of the thing + the word "name" ("Menu name", "Block name", "Content type name", "View name", etc.)

@klonos, based on your examples above, my preference would be to have the column header be the the type of thing plus the word "Name" (assuming the thing has a name and not a title, etc)

It might also be worth looking at the edit forms for the things and seeing what we call the Name/Title there:

* Layouts: `Layout name`
* Layout Templates: `Template name`
* Menus: `Title`
* Block: `Display title` and `Admin label`
* Display mode: `Display mode label`
