### ISSUE TITLE
Backdrop 1.20.0-preview Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5196]
Scheduled for January/May/September 2nd, 2021 6-8pm PT

## Pre-release tasks

- [x] If this is the Jan 1 pre-release, then make sure to update the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file.
- [x] Merge commits (@quicksketch)
- [x] Create a new minor release milestone (@quicksketch)
- [x] Move all unfinished issues to the next minor release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (assign to klonos / jenlampton / stpaultim )
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    - This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [ ] Review issues for new features (assign to @jenlampton / @klonos / @cellear)
  - [ ] Add a conclusion suitable for blog post + release notes
  - [ ] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [ ] Add `Needs change record` label if the the issue contains an API change.
  - [ ] Add `Needs translation` label if the the issue contains string translations.
- [ ] Draft blog post for release on the 15th (assign to stpaultim / tomgrandy / klonos / jenlampton)
- [ ] Draft roadmap updates for backdropcms.org (assign to stpaultim / klonos / jenlampton)
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub (@quicksketch)

## Post-release Publicity + documentation tasks

- [ ] Tweet that a preview release is out (@stpaultim)
- [ ] Publish roadmap updates for backdropcms.org (assign to stpaultim / klonos / jenlampton)

**Comment by quicksketch** [comment]
Release notes draft

This is a preview release of Backdrop 1.20. Please use this version if you would like to help us test the features the new version of Backdrop prior to the official release on September 15, 2021.

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

It will be necessary to run the update script (located at `/core/update.php`) for this release.

## New features

- [A11Y] Add the HTML details element to core form API [#324])https://github.com/backdrop/backdrop-issues/issues/324)
- [META] Telemetry: (anonymously) collect useful data [#285](https://github.com/backdrop/backdrop-issues/issues/285)
- [UX] Better Taxonomy permissions [#382](https://github.com/backdrop/backdrop-issues/issues/382)
- [UX][DX] Provide the ability to make messages dismissible [#4571](https://github.com/backdrop/backdrop-issues/issues/4571)
- [UX] Add filename filter for media library dialog [#3293](https://github.com/backdrop/backdrop-issues/issues/3293)

## Bug fixes

- Module config in /config is not synced on install [#3224](https://github.com/backdrop/backdrop-issues/issues/3224)

## Miscellaneous changes

- Move node preview layout code into node module via new hook in layout module [#5067](https://github.com/backdrop/backdrop-issues/issues/5067)
- Replace the icon for "Structure" in the admin bar [#4427](https://github.com/backdrop/backdrop-issues/issues/4427)

**Comment by klonos** [comment]
Closing, in favor of #5229
