### ISSUE TITLE
Backdrop 1.19.4 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5228]
Release scheduled for September 15, 2021 1pm - 4pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] ~Update the front page download link on b.org~
- [x] ~Tweet that a new release is out~

## See Also

- [Checklist for 1.20.0 release](https://github.com/backdrop/backdrop-issues/issues/5229)

**Comment by quicksketch** [comment]
Release notes draft
---

This is a maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script (/core/update.php) **does** need to be run.

## Bug fixes

- Render function in `views_handler_field_file_filemime` passes bad info to `file_icon_url()` [#5227](https://github.com/backdrop/backdrop-issues/issues/5227)
- Views: initial setting "Use a pager" ignored [#5224](https://github.com/backdrop/backdrop-issues/issues/5224)
- Simpletest FilterEditorLinkValidateTestCase silently broken on PHP 5.3 [#5215](https://github.com/backdrop/backdrop-issues/issues/5215)
- Spelling mistake: langauges [#5211](https://github.com/backdrop/backdrop-issues/issues/5211)
- Random failures or timeouts in BatchProcessingTestCase (race condition in all batch processing) [#5205](https://github.com/backdrop/backdrop-issues/issues/5205)
- Example in help text for current-page `args` tokens is wrong [#5194](https://github.com/backdrop/backdrop-issues/issues/5194)
- Random failures in CommentInterfaceTest - Link with label 1 new comment not found. [#5189](https://github.com/backdrop/backdrop-issues/issues/5189)
- Database update fails when Backdrop is set to another language than English and the string "Apply pending updates" has a translation [#5168](https://github.com/backdrop/backdrop-issues/issues/5168)
- [UX] Config import should list all invalid configs, not just the first one [#5146](https://github.com/backdrop/backdrop-issues/issues/5146)
- [UX] Button colors inconsistent when Basis used as admin theme [#5130](https://github.com/backdrop/backdrop-issues/issues/5130)
- BootstrapPageCacheTestCase failing in mod_proxy Apache environments  [#5126](https://github.com/backdrop/backdrop-issues/issues/5126)
- Wrong url to update.php if language prefix in use [#5092](https://github.com/backdrop/backdrop-issues/issues/5092)
- Field UI: (Almost) empty page titles on display settings pages for user and comment [#4901](https://github.com/backdrop/backdrop-issues/issues/4901)
- Unable to save link to node with non-ascii characters in title when transliteration is off [#4630](https://github.com/backdrop/backdrop-issues/issues/4630)
- Non standard property “zoom” [CSS] [#4276](https://github.com/backdrop/backdrop-issues/issues/4276)
- Symlink to document root causing several update and install issues [#3008](https://github.com/backdrop/backdrop-issues/issues/3008)
- Random test failure: Locale: Translation import (LocaleImportFunctionalTest) [#2611](https://github.com/backdrop/backdrop-issues/issues/2611)

## Miscellaneous changes

- Initialise the return array in path_get_info() [#5137](https://github.com/backdrop/backdrop-issues/issues/5137)
- [UX] Provide more guidance on password strength required [#5095](https://github.com/backdrop/backdrop-issues/issues/5095)
- [A11Y] Use Backdrop.announce() when using Block drag and drop rearrangement [#5021](https://github.com/backdrop/backdrop-issues/issues/5021)
- [A11Y] Backdrop Admin Bar Menu Search Input Field - Accessibility Suggestion [#4997](https://github.com/backdrop/backdrop-issues/issues/4997)
- Basis: Remove underline from Delete button [#4206](https://github.com/backdrop/backdrop-issues/issues/4206)
- [A11Y]  Remove 'navigation' role from 'nav' elements [#4032](https://github.com/backdrop/backdrop-issues/issues/4032)
- [D8][UX] Update the dated icons for sorting tables [#3906](https://github.com/backdrop/backdrop-issues/issues/3906)
- Remove search block default title [#3476](https://github.com/backdrop/backdrop-issues/issues/3476)
- [UX][DX] Improve the message about theme color.module support. [#3458](https://github.com/backdrop/backdrop-issues/issues/3458)
- [UX] Remove ordering/weight from the vocabularies listing page & style the page consistently with the Views listing page [#2029](https://github.com/backdrop/backdrop-issues/issues/2029)
- [UX] Add a 'Save and add terms' button to the 'Add vocabulary' form. [#999](https://github.com/backdrop/backdrop-issues/issues/999)

**Comment by quicksketch** [comment]
The release is now out: https://github.com/backdrop/backdrop/releases/tag/1.19.4

We're dual-releasing this and 1.20.0 at the same time. We'll be continuing that release over in https://github.com/backdrop/backdrop-issues/issues/5229.
