### ISSUE TITLE
Backdrop 1.20.0 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5229]
Scheduled for September 15, 2021 1pm - 3pm PT

## Pre-release tasks

- [x] Merge minor release commits (@quicksketch)
- [x] Move all unfinished issues to the next bug-fix release milestone (@quicksketch)
- [x] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@jenlampton)
- [x] Draft Release notes (@jenlampton)
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      - The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section containing **Notes for updating**
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text "The database update script does **not** need to be run."
        * or "It will be necessary to run the update script (located at /update.php) for this release."
    - [x] Include changelog since last version:
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub (@quicksketch)
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Update the roadmap page on b.org @jenlampton 
- [x] Create a new language template file for the translation server (@olafgrabienski)

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) (assign to serundeputy / jenlampton)
- [ ] Update Composer (assign to quicksketch / serundeputy / herbdool)
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer needed)
- [x] update docs.backdropcms.org to latest version @jenlampton

### Publicity tasks

- [x] Tweet that a new release is out (@stpaultim)
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [ ] Publish blog post (@stpaultim)
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter (assign to stpaultim / tomgrandy / klonos / jenlampton)
- [x] Update the Wikipedia articles (assign to stpaultim / klonos / jenlampton)
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

### Backdrop Website updates

- [x] docs.backdropcms.org @jenlampton 
- [ ] events.backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton 

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Code tasks

- [ ] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) (@herbdool)

### Publicity tasks

- [ ] Send a newsletter to subscribers (assign to @bwpanda / stpaultim / jenlampton)

### Backdrop Website updates

- [ ] backdropcms.org (assign to @jenlampton / @bwpanda / ??)

See Also
---------
* https://github.com/backdrop/backdrop-issues/issues/5228

**Comment by quicksketch** [comment]
The tag is cut and ready for release notes: https://github.com/backdrop/backdrop/releases/tag/1.20.0

**Comment by jenlampton** [comment]
ok, all change records are added, issues are closed and I'm closing the milestone now!

**Comment by jenlampton** [comment]
Release notes draft
---

The Backdrop community is proud to release version 1.20.0 of Backdrop CMS, following our 4-month release cycle.

This release contains several new features, user experience improvements, and a few bug fixes for these recent improvements.


**Notes for updating**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script (/core/update.php) **does** need to be run.

**Changes since 1.19.4**

## New features

- Add the ability to make messages dismissible [#4571](https://github.com/backdrop/backdrop-issues/issues/4571)
- Standardize Label and `machine name` usage in admin listings [#3402](https://github.com/backdrop/backdrop-issues/issues/3402)
- Add Better Taxonomy permissions [#382](https://github.com/backdrop/backdrop-issues/issues/382)
- Add the HTML details element to core form API [#324](https://github.com/backdrop/backdrop-issues/issues/324)
- Add a Telemetry module to (anonymously) collect useful data [#285](https://github.com/backdrop/backdrop-issues/issues/285)

## User Experience Improvements

- Add a new icon for "Structure" in the admin bar [#4427](https://github.com/backdrop/backdrop-issues/issues/4427)
- Add a summary text next to the CKEditor formatting options link, showing the active format [#3595](https://github.com/backdrop/backdrop-issues/issues/3595)
- Add an exposed filename filter for the media library [#3293](https://github.com/backdrop/backdrop-issues/issues/3293)

## Bug fixes

- Fixed: Missing update description for system_update_1076() [#5203](https://github.com/backdrop/backdrop-issues/issues/5203)
- Fixed: Shorthand [] for array() breaking PHP 5.3 tests [#5200](https://github.com/backdrop/backdrop-issues/issues/5200)
- Fixed: Insufficient access to Taxonomy Block on Dashboard [#5198](https://github.com/backdrop/backdrop-issues/issues/5198)
- Fixed: Module config is not automatically synced on install [#3224](https://github.com/backdrop/backdrop-issues/issues/3224)
- Remove the option for configuring the admin theme to always be the same as the default theme. [#4461](https://github.com/backdrop/backdrop-issues/issues/4461)

## Miscellaneous changes

- Added: GitHub Actions for automated tests [#4753](https://github.com/backdrop/backdrop-issues/issues/4753)
- Fixed: Node preview layout code should live in node module via hook_layout_layouts_alter() [#5067](https://github.com/backdrop/backdrop-issues/issues/5067)

**Comment by klonos** [comment]
Noting that I've updated the version template in https://en.wikipedia.org/wiki/Template:BackdropCMS_version but the changes have not propagated immediately to https://en.wikipedia.org/wiki/Backdrop_CMS and https://en.wikipedia.org/wiki/List_of_content_management_systems as they used to in the past. I'll check again tomorrow.

**Comment by olafgrabienski** [comment]
Created a new language template file for the translation server. (And deleted template files for really old Backdrop versions.)

**Comment by BWPanda** [comment]
I'm assuming this can be closed now. Feel free to re-open if not.
