### ISSUE TITLE
[META] Telemetry follow-up issues

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5231]
This issue is a follow-up to https://github.com/backdrop/backdrop-issues/issues/285 where Telemetry module was added to core. 🎉 

Things we should still do:
- [x] #5253 | Enable telemetry module on new installs (1.21)
- [x] #5253 | Add easy opt-out to disable telemetry module
- [x] #5253 | Add Admin Dashboard block to telemetry module
- [ ] Add checkbox to enable Telemetry module to the installer

Additional Metrics we should be collecting:
- [x] #5423 | Web Server Type
- [ ] #4533 | Initial version of Backdrop when it is being installed (needed for https://github.com/backdrop/backdrop-issues/issues/4512 )
- [ ] Whether the site was a previous D6/7 upgrade
- [x] #3206 | Multisite or not (needed for https://github.com/backdrop/backdrop-issues/issues/3205)
- [ ] #5184 | Multilingual or not (how many/which languages are enabled, which one is set as the default)
- [x] #5187 | Name of Install profile in use (needed for #3205)
- [ ] #5186 | enabled/admin/default theme (needed for #131)
- [ ] Number of block displays vs page displays for views (needed for #2978) 
- [ ] #5183 | [DX][D9] Telemetry: gather Server Timing performance metrics
- [ ] Site size metrics (number of user accounts, number of nodes, number of managed files etc.)
- [ ] #5256 | Telemetry report: Link to the "Telemetry" tab of each project in backdropcms.org
- [ ] #6725 | Track Update module usage in Telemetry
- [ ] enabled core modules
- [ ] enabled sub-modules (not just packages) [d.o issue 1](https://www.drupal.org/node/1036780) | [d.o issue2](https://www.drupal.org/node/1627676) | [d.o issue 3](https://www.drupal.org/node/1274766) Needed for the following:
  * Contextual links module: #1409
  * Contact module: #3023
- [ ] #6747 | Database prefixes or not

Related issues: 
- [ ] #3168 | Separate checking for updates from collecting anonymous data
