### ISSUE TITLE
[META] - Issues Related to Recipes

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5240]
**Description of the need**

With the fix of https://github.com/backdrop/backdrop-issues/issues/3224, we are moving closer towards developing the preconditions for "recipes" to become a more useful tool in Backdrop. 

See: 
* https://github.com/backdrop/backdrop-issues/issues/3763
* https://backdropcms.org/news/config-recipes-a-possible-path-forward

This is intended as a META issue to track other issues that are blocking the progress of "recipes" and/or are directly related to the advancement of "recipes."

- [ ] https://github.com/backdrop/backdrop-issues/issues/1238
- [ ] https://github.com/backdrop/backdrop-issues/issues/4188
- [ ] https://github.com/backdrop/backdrop-issues/issues/4217
- [x] https://github.com/backdrop/backdrop-issues/issues/5163
- [ ] https://github.com/backdrop/backdrop-issues/issues/5173
- [ ] https://github.com/backdrop/backdrop-issues/issues/5174

**Comment by klonos** [comment]
Thanks for putting this list together @stpaultim 👍🏼
