### ISSUE TITLE
Backdrop 1.20.1 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5267]
Release scheduled for October 1, 2021 10am - 1pm PT

## Pre-release tasks

- [x] Merge commits
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (assign to klonos / jenlampton / stpaultim )
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number bac (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Update the front page download link on b.org (assign to stpaultim / klonos / jenlampton / serundeputy / herbdool / quicksketch)
- [ ] Tweet that a new release is out (assign to stpaultim / jimbirch / jenlampton / quicksketch)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) (assign to herbdool / serundeputy / quicksketch)
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) (assign to serundeputy / jenlampton)
- [x] Update Composer (assign to quicksketch / serundeputy / herbdool)
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [ ] Update the Wikipedia articles (assign to stpaultim / klonos / jenlampton)
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates

- [ ] backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [ ] docs.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [ ] events.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [ ] forum.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [ ] localize.backdropcms.org (assign to @jenlampton / @bwpanda / ??)

**Comment by quicksketch** [comment]
We're starting this release now and should have it out shortly. I've reviewed the RTBC queue for remaining easy fixes. I've gone ahead and closed the milestone and will be prepping the release.

Here are the release notes as generated by the GitHub Actions workflow:

---


## Bug fixes

- Syntax error in file.test prevents File tests from running. [#5293](https://github.com/backdrop/backdrop-issues/issues/5293)
- PHP warning on upgrade from Drupal 7 in system_get_date_formats() [#5288](https://github.com/backdrop/backdrop-issues/issues/5288)
- Broken html at custom blocks admin page [#5251](https://github.com/backdrop/backdrop-issues/issues/5251)
- GHA tests: Fix failure output [#5236](https://github.com/backdrop/backdrop-issues/issues/5236)
- The help text in "String contains" field in "User interface translation" says that search is case-sensitive, when it's not [#4677](https://github.com/backdrop/backdrop-issues/issues/4677)
- Views: Incorrect filter group OR behavior, LEFT JOIN changed to INNER JOIN [#3415](https://github.com/backdrop/backdrop-issues/issues/3415)

## Miscellaneous changes

- Upgrade from ubuntu-18.04 to ubuntu-20.04 for GitHub Actions [#5209](https://github.com/backdrop/backdrop-issues/issues/5209)
- [UX] Add a 'Save and set permissions' button to the 'Add role' form [#5208](https://github.com/backdrop/backdrop-issues/issues/5208)
- [UX] Highlight "New" Dashboard Notifications [#5098](https://github.com/backdrop/backdrop-issues/issues/5098)

**Comment by BWPanda** [comment]
Assuming this can be closed now. Feel free to re-open if not.
