### ISSUE TITLE
[Meta] Install issues

### ISSUE THREAD

**Issue by oadaeh** [backdrop/backdrop-issues#531]
There are several installation issues, and I ran into many of them attempting to install the latest preview. I wanted to group them together, and so I'm creating this meta issue. In my testing of the preview release, I was not able to get a working installation of Backdrop going. I think it may be because I attempted to install it in a subdirectory (actually, two levels deep), but in my attempts to find the solution, I kept running into many installation issues.
- [x] Almost every time I ran through the installation, the database configuration page loaded twice, requiring it to be filled in twice (https://github.com/backdrop/backdrop-issues/issues/579).
- [x] I would some times get this message after an installation finished or thought it was finished: 'The requested page "/backdrop/backdrop-1.0.0-preview/" could not be found.'
- [ ] I would sometimes get this message during an installation: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop_1.cache_filter' doesn't exist", or a similar message regarding the watchdog table (https://github.com/backdrop/backdrop-issues/issues/590)
- [x] If files are not writeable, the installation has to be restarted (https://github.com/backdrop/backdrop-issues/issues/433 and https://github.com/backdrop/backdrop-issues/issues/572).
- [x] DB settings specified on reinstall (https://github.com/backdrop/backdrop-issues/issues/413).
- [x] After the installatoin reached it's conclusion, I would have three files/config_\* directories are created during install (I think this might be related: https://github.com/backdrop/backdrop-issues/issues/470).
- [x] Backdrop allows installation when the config directory is not empty (https://github.com/backdrop/backdrop-issues/issues/421)

I got these while testing about two weeks ago, and my first priority was to try to come up with steps to reliably reproduce them, but I kept running into road blocks or difficulties reproducing them until I finally ran out of time.

There are also other installation issues that I did not run into, but that have issues recorded for them.

**Comment by quicksketch** [comment]
Thanks @oadaeh, knowing these problems can happen all at once to a single person really indicates we need to work on the error handling in the installer. I changed your description to include checkboxes so we can try to knock these off one at a time.

> Almost every time I ran through the installation, the database configuration page loaded twice, requiring it to be filled in twice.

I've never encountered that. Has this been reproducible for you?

> After the installatoin reached it's conclusion, I would have three files/config_* directories are created during install (I think this might be related: #470).

Yep, #470 should fix that.

A lot of our problems derive from not being comprehensive with our "clean state" check. We really shouldn't allow an installation to proceed unless both A) the database is empty and B) the config directory is empty. Fixing this (probably as part of https://github.com/backdrop/backdrop-issues/issues/413) will probably solve a lot of related problems.

**Comment by BWPanda** [comment]
> Almost every time I ran through the installation, the database configuration page loaded twice, requiring it to be filled in twice.

> I would some times get this message after an installation finished or thought it was finished: 'The requested page "/backdrop/backdrop-1.0.0-preview/" could not be found.'

I encountered a similar (though maybe not the same) problem a while ago: https://github.com/backdrop/backdrop-issues/issues/439
Issue turned out to be (I think) Firefox's auto-filling of the database credentials fields...

**Comment by oadaeh** [comment]
To Nate:
> > Almost every time I ran through the installation, the database configuration page
> > loaded twice, requiring it to be filled in twice.
> 
> I've never encountered that. Has this been reproducible for you?

I said Almost, but that's because I couldn't remember a time when it didn't happen.  The reality is that I think it happened every time, but there might have been one or two times in the twenty or so attempts when it didn't happen. I think this was also in another issue posted by klonos a few months ago that I was never able to pin down.

> > After the installatoin reached it's conclusion, I would have three files/config_* 
> > directories are created during install (I think this might be related: #470).
> 
> Yep, #470 should fix that.

I wanted to add that I read through that issue, because I too thought it was the fix, but the code referenced in that issue is no longer the same as it is now. I went through the code that is there now and tweaked it in various places, attempting to correct or at least change the behavior, but I still ended up with three directories, so I thought it was being caused by something else that I wasn't seeing.

To BWPanda:
> > Almost every time I ran through the installation, the database configuration page
> > loaded twice, requiring it to be filled in twice.
> > 
> > I would some times get this message after an installation finished or thought it
> > was finished: 'The requested page "/backdrop/backdrop-1.0.0-preview/" could
> > not be found.'
> 
> I encountered a similar (though maybe not the same) problem a while ago: #439
> Issue turned out to be (I think) Firefox's auto-filling of the database credentials fields...

I also saw your report there, but I don't think my issue is not related to yours, because I do not have that Firefox feature enabled. I consider it a potential security risk.

In general:
I also want to add that by the time I was done, I had created a script that wiped out the files (not just files/config_*, but the entire install base) and database of one installation and setup a new, blank file set and database for the next installation, so that I was starting at the same spot and with a clean slate every time.

**Comment by jtphelan** [comment]
I'm having install issues as well. I get a similar error to @oadaeh 

    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.watchdog' doesn't exist

then if I click continue to error page I get these.

    Warning: Invalid argument supplied for foreach() in field_read_instances() (line 739 of /home/backdrop/public_html/core/modules/field/field.crud.inc).
    Warning: Invalid argument supplied for foreach() in _node_types_build() (line 659 of /home/backdrop/public_html/core/modules/node/node.module).
    Warning: array_map(): Argument #2 should be an array in ConfigFileStorage->listAll() (line 1003 of /home/backdrop/public_html/core/includes/config.inc).
    Warning: Invalid argument supplied for foreach() in field_read_fields() (line 331 of /home/backdrop/public_html/core/modules/field/field.crud.inc).

If I go and create the table manually it works but then I get errors like this about ConfigFileStorage

    Warning: array_map(): Argument #2 should be an array in ConfigFileStorage->listAll() (line 1003 of /home/backdrop/public_html/core/includes/config.inc).
    Warning: Invalid argument supplied for foreach() in field_read_fields() (line 331 of /home/backdrop/public_html/core/modules/field/field.crud.inc).

**Comment by leewillis77** [comment]
Hi, 

I'm experiencing these two errors on install consistently. Happy to help debug if there's any particular info you need:

* Almost every time I ran through the installation, the database configuration page loaded twice, requiring it to be filled in twice.
* I would some times get this message after successfully entering DB details the second time. 'The requested page "/" could not be found.' I have to go "back" in my browser to be able to continue.

**Comment by quicksketch** [comment]
I've got a branch in progress to fix a number of these issues, but it's going to take me a while before I can file a PR. Assigning this to myself in the mean time.

**Comment by jenlampton** [comment]
Thanks everyone for all the feedback!  I've also noticed that our install process seems to have gotten a lot more brittle in the last few weeks, and @quicksketch is working on making it more robust.

For the time being here are some things everyone should check before installing to avoid the issues:
- make sure you have an (empty) database created before running the installer
- make sure you have a (writable) files directory, with no config_whatever directories within.
- make sure you have checked out the latest version of settings.php before running the installer
- make sure you are running PHP 5.3.2 or later

Every time you want to reinstall there are three things you need to do
* drop your current database / create a new empty one
* git checkout settings.php (or copy in a clean version from download)
* delete all config from /files/config_whatevs

This third step I sometimes forget since it was not necessary in Durpal-land. The second step will assure that you remove your old database (and config directory) info, as well as pull in any recent changes.

**Comment by leewillis77** [comment]
Hi Jen; 

Thanks for the feedback. I was already re-setting settings.php and clearing out the database. I've run a couple of test installs with the additional step of clearing out files/config_* and still see the same issues - just thought I'd let you know that those steps don't resolve the issues I'm seeing.

**Comment by jtphelan** [comment]
FYI - My errors were on a fresh, first time install.

**Comment by quicksketch** [comment]
> I would some times get this message after an installation finished or thought it was finished: 'The requested page "/backdrop/backdrop-1.0.0-preview/" could not be found.'

I filed a PR at https://github.com/backdrop/backdrop/pull/659 that addresses this one and 2 others (#413 and #470). This problem had been caused by the profile name getting lost during installation. Then if the "standard" profile wasn't installed, the node module was getting excluded and then the homepage (`/node`) wouldn't be found. This has been corrected in the PR by catching an Exception when the config system isn't yet available.

**Comment by jenlampton** [comment]
I'm going to to a bunch of testing on the new installer over at https://github.com/backdrop/backdrop/pull/659 and see if I can reproduce any of the above. 

I would love it if @jtphelan, @leewillis77 and @oadaeh could help do some more testing too, since I'm not sure I have a similar enough set-up to catch all the same issues.

**Comment by jenlampton** [comment]
Scenario 6: Standard install procedure (on shared hosting)
Start with empty database, default settings.php file and everything writable.

haha

```Your PHP installation is too old. Backdrop CMS requires at least PHP 5.3.2. See the system requirements page for more information.```

- [x] Correctly notified of PHP version too old.

**Comment by quicksketch** [comment]
Okay, we've merged in https://github.com/backdrop/backdrop/pull/659 which *significantly* improves the error and exception handling to take users through the installation process without so much trouble.

The only two situations that aren't for sure resolved are two items from this meta:

> Almost every time I ran through the installation, the database configuration page loaded twice, requiring it to be filled in twice.

I think this one is fixed by specifying the hash_salt option earlier in the install process, but I never experienced this one in the first place.

> I would sometimes get this message during an installation: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop_1.cache_filter' doesn't exist"

I encountered an error similar to this during my testing, but I couldn't reproduce it after the other fixes were in place. Could you try re-installing @oadaeh and let us know if you encounter any of these problems (or new ones) during installation? @jenlampton's testing was pretty thorough and my testing indicates its much, much more robust than before. Thanks!

**Comment by leewillis77** [comment]
Hi. 

I've pulled in the latest code from the main repo (Looks like these fixes were merged in there?). Unfortunately I'm still experiencing issues with being asked for database credentials twice and white screens though. Here's a walkthrough of an install on my laptop (Ubuntu 14.10).

* Drop database "backdrop"
* Create database "backdrop"
* git checkout -- settings.php
* sudo rm -fr files/config*
* Open "http://backdrop/" in a browser
* Redirected to "http://backdrop/core/install.php"
* Choose language "English", and hit Save and Continue
* Sent to "http://backdrop/core/install.php?langcode=en&profile=standard" and asked for DB details
* Enter DB details (Database name, username and password - everything else left as default) and hit Save and Continue
* Sent to "http://backdrop/core/install.php?langcode=en&profile=standard&op=start&id=1", and asked for Database details again
* Enter DB details again (Database name, username and password - everything else left as default) and hit Save and Continue
* Sent to "http://backdrop/core/install.php?langcode=en&profile=standard&op=start&id=1" and get a white screen
* Press "Back" in my browser (Chrome), and get the "Installing Backdrop CMS" screen. Modules are installed successfully.
* Fill in resulting details form and hit Save and Continue
* Backdrop installed, I'm logged in and I get the "Welcome to backdrop" screen.

**Comment by juanolalla** [comment]
I'm experiencing the same as @leewillis77, If everyone is experiencing this, users just can't install backdrop. I've opened this issue https://github.com/backdrop/backdrop-issues/issues/579

**Comment by BWPanda** [comment]
@leewillis77: I did pretty much everything you did with the only major difference being that I deleted the entire `/files/`directory (not just the config directory). I entered the DB credentials once and it worked fine for me...

**Comment by leewillis77** [comment]
@BWPanda I can confirm that deleting the entire files folder rather than just the config_* subdirectories resolves the issue for me. 

So - clearing out this way fails:
`$ rm -fr files/config*`

Clearing out this way works - I no longer get asked for DB details first, or receive white pages.
`$ rm -fr files`

**Comment by juanolalla** [comment]
Have you tried with a new fresh installation? It isn't working for me, as a explain in #579

**Comment by juanolalla** [comment]
The first point "Almost every time I ran through the installation, the database configuration page loaded twice, requiring it to be filled in twice." that I'm also experiencing with Backdrop and Drupal 7 installers, could be for some local issue, as in https://www.drupal.org/node/779482

**Comment by juanolalla** [comment]
I've found the solution for the first issue point, at least in my case, disabling opcache as in https://www.drupal.org/node/332730#comment-8962563 make it work.

**Comment by quicksketch** [comment]
Thanks @juanolalla and @leewillis77 for your testing information! We tried out a large number of situations with the latest changes (a shared host, CentOS Linode, Pantheon, local MAMP, and Bitnami) but clearly we haven't solved all the issues. It sounds like this is probably the same issue as Drupal 7 that @juanolalla linked to. I'll read through that and see if the fix is applicable to us as well.

**Comment by quicksketch** [comment]
I merged in backdrop/backdrop#666 which should fix the remaining issue with PHP 5.5 and the Zend OPcache. I also submitted an updated patch to d.o for the same issue: https://www.drupal.org/node/779482#comment-9515729

That only leaves the `"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop_1.cache_filter' doesn't exist"` problem, which I believe was fixed in the first round of changes but we haven't been able to confirm.

**Comment by leewillis77** [comment]
Just to confirm, that the latest checkout works flawlessly for me - thanks!

**Comment by quicksketch** [comment]
Awesome!! Glad to hear, since we cut the final release. LOL

https://github.com/backdrop/backdrop/releases/tag/v1.0.0

:smile:

**Comment by quicksketch** [comment]
We haven't had any additional reported issues on install, and the one remaining issue hasn't been confirmed. Let's close this issue as fixed and make new issues as we come across them. Thanks!

**Comment by olafgrabienski** [comment]
Updated the issue description to mention #590 also there.
