### ISSUE TITLE
[META] Theme handling woes

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5317]
This is a list of issues that we should address with the way Backdrop handles themes:

- [ ]  #131 | [UX] Make only one theme "active" at a time
- [ ] #2548 | [META][DX] Bring consistency to certain functions that handle modules and themes and also add missing respective layout functions.
  - [ ] #2337 | [DX][BC] Deprecate module_exists() and add a project_exists() function
- [ ] #3924 | Installer: "Requirements problem" for missing projects assumes only modules
- [ ] #3926 | Allow install profiles to define dependencies other than modules
- [ ] #4459 | [UX][DX] Either remove the notion of "disabled" themes, or properly handle them
- [ ] #4829 | Allow themes to be installed, uninstalled, and updated (treat them like modules)
- [x] #5315 | [DX] Fix function description for system_theme_settings()
- [ ] #5316 | [D8][DX] Allow themes to declare dependencies on modules and layout templates
