### ISSUE TITLE
[META] Make sure that permissions for things that are removed are not left behind

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5351]
In Drupal 9.3.x with the introduction of https://www.drupal.org/node/3055548 such permissions are being cleaned up automatically, because permissions are allowed to specify dependencies. Since we don't have that in Backdrop, we should make sure that we clean up such permissions when the things that have added them are being removed:

- [ ] #5350 | When a content type is deleted, make sure that the respective permissions are also removed from roles
- [ ] ??? | When a text format is deleted, make sure that the respective permissions are also removed from roles
- [ ] ??? | When a vocabulary is deleted, make sure that the respective permissions are also removed from roles

**Comment by philsward** [comment]
Might add "entities" as a generic to encompass contrib.

Ideally, core should handle this for contrib instead of expecting contrib to handle it on its own. (There should probably be a flag to allow contrib the option to handle it on its own)

**Comment by klonos** [comment]
I hear you @philsward, and yes, ideally core should be able to handle this, but we simply do not have the facility for this. We need dependency permissions for that, and that would be an API change/breakage I believe (so not possible in Backdrop 1.x unfortunately). We can plan for this to become a thing in Backdrop 2.x (separate issue though please), but in the meantime we'd have to do it "manually" for both core and contrib 🤷🏼
