### ISSUE TITLE
Backdrop 1.20.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5359]
Release scheduled for Nov 18th, 2021 -- 1pm - 4pm PT

## Pre-release tasks

- [x] Merge commits @laryn
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version: 
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number (??)
- [x] Tag for release, and push tag to GitHub (??)
- [x] Revert version number back (??)
- [x] Create release notes on GitHub, and publish release @jenlampton
- [x] Publish Security Advisories on b.org @jenlampton
- [x] Mark the release node on b.org as a security release @jenlampton
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)
- [x] Update the front page download link on b.org @jenlampton
- [ ] Tweet that a new release is out @jenlampton
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) ??
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] N/A/ Update the Security Advisory with CVE 

## Backdrop Website updates

- [ ] backdropcms.org @jenlampton 
- [ ] docs.backdropcms.org @jenlampton 
- [ ] events.backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton 
- [x] N/A localize.backdropcms.org (localize is D7 and there is no D7 update)

## See Also

- [Checklist for 1.19.5 release](https://github.com/backdrop/backdrop-issues/issues/5360)

**Comment by jenlampton** [comment]
**Draft release notes:**

Security release for Backdrop CMS. This release fixes a security vulnerability in a third party library. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

Backdrop core - Moderately Critical - Third Party Libraries - SA-BACKDROP-CORE-2021-005

**Important update information**

* The database update script does **not** need to be run
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

This release also contains a number of small bug fixes and improvements:

## Bug fixes

- Fixed: Update cache flush doesn't work [#5326](https://github.com/backdrop/backdrop-issues/issues/5326)
- Fixed style issues with Flexible layout template UI and make it more consistent with the layout/blocks UI [#5149](https://github.com/backdrop/backdrop-issues/issues/5149)
- Fixed: PHP 8: Database: Transaction test failure [#5325](https://github.com/backdrop/backdrop-issues/issues/5325)
- Fixed: PHP 8: Broken test locale_get_plural() - ArgumentCountError in intval() [#5319](https://github.com/backdrop/backdrop-issues/issues/5319)
- Fixed: PHP 8: Views Plugins: Cache / Views fields for Field API [#5314](https://github.com/backdrop/backdrop-issues/issues/5314)
- Fixed: PHP 8: Views Handlers: Filter: in_operator - Array to string conversion [#5313](https://github.com/backdrop/backdrop-issues/issues/5313)
- Fixed: PHP 8: Layout interface broken - Unknown named parameter $id [#5312](https://github.com/backdrop/backdrop-issues/issues/5312)
- Fixed: Save button missing from theme settings form [#5308](https://github.com/backdrop/backdrop-issues/issues/5308)
- Fixed: PHP 8: Get views exposed filters with checkbox working [#5305](https://github.com/backdrop/backdrop-issues/issues/5305)
- Fixed Date Theme automated test fails from 23:00 to 23:59 UTC [#5303](https://github.com/backdrop/backdrop-issues/issues/5303)
- Fixed Context validation error on Configure Layout page (and empty page output on cancel) [#5065](https://github.com/backdrop/backdrop-issues/issues/5065)
- Fixed performance on the Modules listing page /admin/modules [#5046](https://github.com/backdrop/backdrop-issues/issues/5046)
- Fixed Random test failures with PathPatternBulkUpdateTestCase [#4862](https://github.com/backdrop/backdrop-issues/issues/4862)
- Fixed: PHP 8: Fix test failures in Form element validation [#5310](https://github.com/backdrop/backdrop-issues/issues/5310)
- Fixed: Form cache test not properly ported from Drupal [#5304](https://github.com/backdrop/backdrop-issues/issues/5304)

## Documentation updates

- Update documentation for theme() to state direct usage is acceptable [#5232](https://github.com/backdrop/backdrop-issues/issues/5232)

## Miscellaneous changes

- Full PHP 8 Support [#5076](https://github.com/backdrop/backdrop-issues/issues/5076)
- Added 1Password to the list of projects that support us [#5324](https://github.com/backdrop/backdrop-issues/issues/5324)
- Added backwards-compatible wrapper views_ui_build_form_url() [#5323](https://github.com/backdrop/backdrop-issues/issues/5323)
- Added the ability to clone a views display while changing the display plugin [#5246](https://github.com/backdrop/backdrop-issues/issues/5246)

**Comment by jenlampton** [comment]
draft SA: https://backdropcms.org/security/backdrop-sa-core-2021-006

**Comment by quicksketch** [comment]
Thanks @jenlampton! I published the SA and pushed out the releases: https://github.com/backdrop/backdrop/releases/tag/1.20.2

Thanks @laryn for making the git tags and cutting the release! Everything looked great to me. :100: 

Still a lot of follow-up tasks here to be done (updating sites/services, etc).

**Comment by BWPanda** [comment]
Assuming this can be closed now. Feel free to re-open if not.
