### ISSUE TITLE
Backdrop 1.19.5 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5360]
Release scheduled for Nov 18th, 2021 -- 1pm - 4pm PT

## Pre-release tasks

- [ ] Merge commits (??)
- [ ] Create the next bugfix milestone @jenlampton 
- [ ] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [ ] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [ ] Close the milestone @jenlampton 
- [ ] Draft Release notes @jenlampton 
  - [ ] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [ ] Include a section containing **Notes for updating**
    - [ ] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [ ] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [ ] Include changelog since last version: 
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [ ] Draft Security Advisories @jenlampton 

## Release tasks

- [ ] Update bootstrap.inc with version number (??)
- [ ] Tag for release, and push tag to GitHub (??)
- [ ] Revert version number back (??)
- [ ] Create release notes on GitHub, and publish release @jenlampton
- [ ] Mark the release node on b.org as a security release @jenlampton

## See Also

- [Checklist for 1.20.1 release](https://github.com/backdrop/backdrop-issues/issues/5359)

**Comment by quicksketch** [comment]
Release is out and marked as security release: https://github.com/backdrop/backdrop/releases/tag/1.19.5

**Comment by jenlampton** [comment]
**Draft release notes:**

Security release for Backdrop CMS. This release fixes a security vulnerability in a third party library. Sites are urged to upgrade immediately after reading the notes below and the security announcement:

Backdrop core - Moderately Critical - Third Party Libraries - SA-BACKDROP-CORE-2021-006

## Important update information

* The database update script does **not** need to be run
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
