### ISSUE TITLE
Backdrop 1.20.3 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5382]
Release scheduled for December 3, 2021 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (assign to klonos / jenlampton / stpaultim )
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Update the front page download link on b.org (@quicksketch)
- [x] Tweet that a new release is out (@stpaultim)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) (@herbdool)
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) (assign to serundeputy / jenlampton)
- [x] Update Composer (assign to quicksketch / serundeputy / herbdool)
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [x] Update the Wikipedia articles (assign to stpaultim / klonos / jenlampton)
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates

- [x] backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [x] docs.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [ ] events.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [x] forum.backdropcms.org (assign to @jenlampton / @bwpanda / ??)
- [x] N/A localize.backdropcms.org (assign to @jenlampton / @bwpanda / ??)

**Comment by quicksketch** [comment]
Still working on checkbox #1 :zany_face: Lot's of PRs are RTBC and I'm working through them.

**Comment by quicksketch** [comment]
Release notes draft:

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

## Important update information

* The database update script does **not** need to be run
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

## Bug fixes

- Field name is blank in error message "__ field is required" when a required field set to 2 or more [#5377](https://github.com/backdrop/backdrop-issues/issues/5377)
- Notice: Undefined index: file_field_file_table in file_view_file() (line 3441 of /app/core/modules/file/file.module). [#5371](https://github.com/backdrop/backdrop-issues/issues/5371)
- Fix errors in views_style_jump_menu.inc caused by null absolute element [#5366](https://github.com/backdrop/backdrop-issues/issues/5366)
- Flexible layouts: "Row" label/indicator rendered in the frontend [#5343](https://github.com/backdrop/backdrop-issues/issues/5343)
- PHP7.4 and empty entity_keys for taxonomy term result in notices [#5290](https://github.com/backdrop/backdrop-issues/issues/5290)
- [DX] Form API: Adding `#attributes` to fields of type `container` breaks `#states` [#5157](https://github.com/backdrop/backdrop-issues/issues/5157)
- Project Installer UI: Sub-modules that are hidden should not be shown [#5054](https://github.com/backdrop/backdrop-issues/issues/5054)
- [UX] When adding a new Text (short) field, the textfield widget should be the default [#4717](https://github.com/backdrop/backdrop-issues/issues/4717)
- [UX] Modal popups jump to the top of the page when opened [#4342](https://github.com/backdrop/backdrop-issues/issues/4342)
- Views UI: Fix "Replacement patterns" visibility for Global: Custom Text [#1928](https://github.com/backdrop/backdrop-issues/issues/1928)
- Views writes log to watchdog about files[]  - update for new autoloader [#1559](https://github.com/backdrop/backdrop-issues/issues/1559)

## Miscellaneous changes

- Add Views handler for term aliased path [#5338](https://github.com/backdrop/backdrop-issues/issues/5338)
- Remove all implementations of hook_help() [#3758](https://github.com/backdrop/backdrop-issues/issues/3758)

**Comment by quicksketch** [comment]
Release is now out: https://github.com/backdrop/backdrop/releases/tag/1.20.3

**Comment by klonos** [comment]
Thanks @quicksketch 🙏🏼 ...nice set of bug fixes! 🙂

**Comment by BWPanda** [comment]
Tugboat done.

**Comment by stpaultim** [comment]
Sent Tweet on Dec 3rd - https://twitter.com/backdropcms/status/1467008649033920513

**Comment by BWPanda** [comment]
Apparently I don't have write access to the Events repo, so here's a PR: https://github.com/backdrop-ops/events.backdropcms.org/pull/22

**Comment by BWPanda** [comment]
Also, why's Localise listed as a step to update? It's not even running Backdrop...!

**Comment by olafgrabienski** [comment]
> Also, why's Localise listed as a step to update?  It's not even running Backdrop

Probably somebody wasn't aware and put the site in a template for release checklists. I guess it's fine to just remove it from the template.

**Comment by bugfolder** [comment]
Jen mentioned when 1.20.2 was released that it was cruft in the template.

**Comment by BWPanda** [comment]
OK, templates updated to remove Localise.

**Comment by jenlampton** [comment]
Localize is necessary in the templates because most updates coincide with
Drupal updates, and localize was often overlooked.

The person who copies a template into an issue will remove the items that
are not needed for that specific release while assigning each task to
someone.

**Comment by bugfolder** [comment]
@jenlampton, sorry, I guess I misinterpreted your comment.

**Comment by BWPanda** [comment]
Oops, sorry. Can't see a way to revert commits in the GH interface (https://github.com/backdrop/backdrop-issues/commits/main/procedures), so might need to revert them manually later (unless someone wants to beat me to it)...

**Comment by jenlampton** [comment]
It's no problem, thanks for taking the initiative and working to make
things better! I appreciate everything you have been working on recently :)

**Comment by jenlampton** [comment]
I found the two commits with "Remove Localise site (not Backdrop)" and reverted them :)

**Comment by herbdool** [comment]
We can probably close this?
