### ISSUE TITLE
[META][UX] Improve the admin/config/system/cron page

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5421]
Before:
<img width=70% src="https://user-images.githubusercontent.com/2423362/147513084-3eb71dde-55a5-45ae-924f-eaba11027cd6.png">

After:
<img width=70% src="https://user-images.githubusercontent.com/2423362/147513492-217315c4-f4f7-41d7-b71f-93f47393ac73.png">

Suggested improvements:
- [ ] Move the "Last run" indication to the top of the page, and make it be a status/warning/error, based on the same logic as the "Cron maintenance tasks" entry in `admin/reports/status` (see if we can reduce code and translatable string duplication along the way).
- [ ] #5413 | Improve clarity of help information on the cron settings page.
- [ ] Distinctly list the various methods to run cron (separate fieldsets, along with help text as needed).
- [ ] Convert the "Never" option in the "Run cron every" dropdown into a separate checkbox that enables/disables the feature - in other words, make it so that this bit in our [documentation page](https://backdropcms.org/cron) is not needed:
   > ## Disabling "automated cron"
   > For performance reasons, or if you want to ensure that cron can only ever run from an external trigger, it may be desirable to disable the automated cron system.
   > 
   > You can disable it by setting the "Run cron every" value to "Never" (e.g., at Administration > Configuration > System > Cron (admin/config/system/cron).
- [ ] Convert the hard-coded options in the "Run cron every" dropdown into a "natural language" set of settings (number field + dropdown for selecting minutes/hours/days/weeks)

**Comment by indigoxela** [comment]
> Move the "Last run" indication to the top of the page, and make it be a status/warning/error...

@klonos I'm aware that you tend to make everything a message, but I'm not sure if that's the right thing here. For me messages are something that happen *in response to an action* (form submission, save settings...). Static information should IMO *not* be messages.

One of my pet peeves for example is that annoying "This theme supports custom color palettes..." on admin/appearance/settings/XXX when the color module's disabled.

But maybe it's just me and everyone else agrees that messages should also be used for static information? :wink:

**Comment by olafgrabienski** [comment]
> For me messages are something that happen in response to an action (form submission, save settings...). Static information should IMO not be messages.

I agree, at least most of the times. And in cases where a 'static' message makes sense, the `info` type seems more appropriate to me.

**Comment by kiamlaluno** [comment]
I agree with @indigoxela: IMO, a message should be used when an action is required from the user or to show a message after a user action.

I would not use a message to show the last time cron tasks have been executed, except in the case (on a different page) I would need to tell to the users too much time is passed since last time cron tasks have executed and it's necessary to run them. In that case, the message would contain a link to run them.
  
In this case, the message just shows the last time cron tasks have been and it doesn't contain a link to run them because the *Run cron* button is shown right on the top of that page.
I would just show the information in the page content, in the same way *To run cron from outside the site […]* is shown.

**Comment by bugfolder** [comment]
> IMO, a message should be used when an action is required from the user or to show a message after a user action...I would just show the information in the page content.

Agreed. PR is updated accordingly.

**Comment by olafgrabienski** [comment]
@bugfolder The updated PR works for me (tested in the sandbox).

One minor question: in the Automatic cron section, the input for the number of minutes, hours, days or weeks (id `edit-cron-interval-num`) is quite wide and looks a bit strange to me. I was wondering if we can reduce the width to something around `100px` which should leave enough space for common values. I'm however also fine to proceed without changing the width.

**Comment by bugfolder** [comment]
This is interesting. We should be able to set the width in characters using the [`#size` property](https://docs.backdropcms.org/form_api#size), as we do with `textfield`. This sets the `size` attribute of the `<input>` tag, which the browser then (supposedly) uses. However, both Safari and Chrome seem to ignore this attribute for `<input type="number" ...>` tags, but it does set the field size for `<input type="text" ...>`.

We could force-override the width with something like this:

```
#edit-cron-interval-num {
  max-width: 5em;
}
```

(Using em rather than px to be friendlier to themes that use a different font size). Since we've already got some custom CSS for this form, that seems reasonable. PR updated.

**Comment by jenlampton** [comment]
It looks like this PR needs to be rebased (so changing to NW) but I'm also leaving some feedback about the interface changes that should be addressed.

**Comment by quicksketch** [comment]
I like these changes but the config variable names changing makes me nervous. A broken cron could wreck havoc on a site. I think it should be possible to maintain the same config keys and only update the UI, though it will require some logic when showing the form and submitting the values. We could store a value like `-1` or `0` for entirely disabling cron. And storing the cron threshold in seconds is fine; we can convert that into minutes/seconds/hours in the UI..

**Comment by jenlampton** [comment]
I created an alternate PR at https://github.com/backdrop/backdrop/pull/4511 that removes the need for an update hook -- meaning this could get in after code-freeze. But I found another problem. Formatting the Automatic cron setting as a sentence wasn't done in a way that was translatable, or accessable. 

The cleanest way to fix translations is to have that whole sentence be translated together, with the form elements as placeholders. Something like this:
```
t('If the last cron run was more than !number !unit ago, run cron on the next page request.'); Where the rendered elements are passed into those placeholders. 
```

The cleanest way to fix accessability issues would be for each element to have each form element have a label that is screen-reader only, or (second-best) an aria-attribute that would announce the label when the screen reader encounters the element. 

I'm going to see how much work it would be to clean that up.

**Comment by jenlampton** [comment]
Okay, I have a version of the markup that's both translatable and accessible in a new PR at https://github.com/backdrop/backdrop/pull/4512 -- but this one doesn't work yet :) The form elements, when rendered this way do not end up in the `$form` array as passed along to the submit handler. So I still have more work to do. Unfortunately, I'm tired tonight and my brain is no longer working :( 
I do still think it might be possible to get this in to 1.26.0, maybe?
