### ISSUE TITLE
[META][UX] Improve the roles management page

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5429]
- [ ] #4504 | [UX] Describe ability to re-order roles
- [ ] ??? | [UX] Describe why/how the anonymous and authenticated roles are "special"
- [ ] ??? | Automatically place new roles between "Authenticated" and whichever role has been selected for the admin role
- [ ] ...
