### ISSUE TITLE
Backdrop 1.21.0-preview Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5436]
Scheduled for January 4th, 2022 5pm-6pm PT

## Pre-release tasks

- [x] If this is the Jan 1 pre-release, then make sure to update the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file.
- [x] Merge commits @quicksketch 
- [x] Create a new minor release milestone @quicksketch 
- [x] Move all unfinished issues to the next minor release milestone @quicksketch 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    - This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [x] Review issues for new features @jenlampton 
  - [x] Add a conclusion suitable for blog post + release notes
  - [x] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [x] Add `Needs change record` label if the the issue contains an API change.
  - [x] Add `Needs translation` label if the the issue contains string translations.
- [ ] Draft blog post for release on the 15th @cellear 
- [ ] Draft roadmap updates for backdropcms.org @klonos 
- [x] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (e.g. `1.10.0-preview`) @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Note: New incremented branch for development is usually created on release day
- [x] Revert version number back on 1.x branch with the same minor number (e.g. `1.10.x-dev`) @quicsketch 
- [x] Create release notes on GitHub **Important: Check "This is a pre-release" checkbox when creating release** @jenlampton 

## Post-release Publicity + documentation tasks

- [x] Tweet that a preview release is out @stpaultim 
- [ ] Publish roadmap updates for backdropcms.org @klonos

**Comment by quicksketch** [comment]
Preview release tag has been cut: https://github.com/backdrop/backdrop/releases/tag/1.21.0-preview

**Comment by jenlampton** [comment]
Release notes draft:

---

This is the preview release of Backdrop 1.21.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January 15th, 2022.

**Notes for updating**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- It will be necessary to run the update script (located at `/core/update.php`) for this release.

## New features

- Add crop anchor point for Scale and Crop image effect. [#5080](https://github.com/backdrop/backdrop-issues/issues/5080)
- Add additional CSS classes on regions in Flexible layout templates. [#5044](https://github.com/backdrop/backdrop-issues/issues/5044)
- Add a "negate" option to the  visibility condition for roles. [#4689](https://github.com/backdrop/backdrop-issues/issues/4689)
- Add settings for which parts of the book navigation to display. [#5430](https://github.com/backdrop/backdrop-issues/issues/5430)
- Add filters for ClassName to the Interface for listing available tests. [#5257](https://github.com/backdrop/backdrop-issues/issues/5257)

## User Experience improvements

- Add Date format tokens for date fields. [#2069](https://github.com/backdrop/backdrop-issues/issues/2069)
- Place breadcrumbs above the page title for new installs. [#4113](https://github.com/backdrop/backdrop-issues/issues/4113)
- Add an 'empty' option to theme_item_list() [#5380](https://github.com/backdrop/backdrop-issues/issues/5380)
- Remove all instances of "please contact an administrator" from messaging [#4802](https://github.com/backdrop/backdrop-issues/issues/4802)
- Separate help text for publishing options [#3122](https://github.com/backdrop/backdrop-issues/issues/3122)

## Developer Experience improvements

- Add entity_view() into core [#1739](https://github.com/backdrop/backdrop-issues/issues/1739)
- Provide a helper function to prevent a layout from wrapping around content. [#1728](https://github.com/backdrop/backdrop-issues/issues/1728)

## Bug fixes

- [UX] Remove `item` from text on the `Add another item` button. [#5235](https://github.com/backdrop/backdrop-issues/issues/5235)

## Miscellaneous changes

- Update jQuery UI to 1.13.0 [#5401](https://github.com/backdrop/backdrop-issues/issues/5401)
- Optimize menu_navigation_links_rebuild() [#5389](https://github.com/backdrop/backdrop-issues/issues/5389)
- Remove Zen.CI from the core repository. [#5197](https://github.com/backdrop/backdrop-issues/issues/5197)
- Enable telemetry module on new installs [#5253](https://github.com/backdrop/backdrop-issues/issues/5253)

**Comment by domaingood** [comment]
Nice job! localization on core
