### ISSUE TITLE
Backdrop 1.20.4 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5456]
Release scheduled for January 15, 2022 12pm - 2pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [x] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] ~Update the front page download link on b.org~
- [x] ~Tweet that a new release is out~
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## See Also

- [Checklist for 1.21.0 release]()

**Comment by quicksketch** [comment]
Release notes draft

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

The database update script does not need to be run.

## New features

- [DX] Telemetry: Add Web Server (Apache/nginx/etc) [#5423](https://github.com/backdrop/backdrop-issues/issues/5423)

## Bug fixes

- [A11Y] Seven/Basis/Bartik: "required" asterisk does not have enough contrast [#5425](https://github.com/backdrop/backdrop-issues/issues/5425)
- [DX] Simpletest doesn't handle empty or malformed .tests.info files well [#5415](https://github.com/backdrop/backdrop-issues/issues/5415)
- [UX] Use '#type'=>'help' rather than wrapping '#markup' in '<p>' [#5412](https://github.com/backdrop/backdrop-issues/issues/5412)
- Search form: style the "Search" and "Advanced search" buttons as proper actions buttons. [#5387](https://github.com/backdrop/backdrop-issues/issues/5387)
- [UX] Permissions matrix cut off on Permissions tab of Create Content page [#5384](https://github.com/backdrop/backdrop-issues/issues/5384)
- Improve system_transliterate_machine_name() [#5365](https://github.com/backdrop/backdrop-issues/issues/5365)
- D7 upgrades: cache_entity_* tables causing issues unless dropped before running update.php [#5340](https://github.com/backdrop/backdrop-issues/issues/5340)
- node--type templates are not used when nodes are placed using the "existing content" block. [#5311](https://github.com/backdrop/backdrop-issues/issues/5311)
- simpletest reference to undefined property originalLanguageDefault [#4679](https://github.com/backdrop/backdrop-issues/issues/4679)
- User login form throws SQL error when two usernames or passwords sent in POST [#4240](https://github.com/backdrop/backdrop-issues/issues/4240)
- Nested dependencies causing UX issues in Project Installer [#4120](https://github.com/backdrop/backdrop-issues/issues/4120)
- [UX] Views: No success message when clicking "Save and exit" if creating a page display [#3848](https://github.com/backdrop/backdrop-issues/issues/3848)
- [UX] "Add another item" buttons are hard to distinguish from the field label [#3520](https://github.com/backdrop/backdrop-issues/issues/3520)
- [UX] Layout and Block visibility conditions: add validation when entering entity IDs to ensure that only numbers are allowed. [#2668](https://github.com/backdrop/backdrop-issues/issues/2668)
- Notice: Undefined index: quantity in views_plugin_pager_full->options_form() (line 90 of views_plugin_pager_full.inc). [#1435](https://github.com/backdrop/backdrop-issues/issues/1435)
- User URL alias not applied to admin user out of the box. [#1417](https://github.com/backdrop/backdrop-issues/issues/1417)

## Documentation updates

- Misleading/obsolete function description for theme_html_tag() [#5452](https://github.com/backdrop/backdrop-issues/issues/5452)
- Document that the `cancel-url` and `one-time-login-url` user tokens only work when sending out the admin notification emails [#5445](https://github.com/backdrop/backdrop-issues/issues/5445)
- Fix comment block on theme_get_setting() [#451](https://github.com/backdrop/backdrop-issues/issues/451)
- [UX] Describe ability to re-order roles [#4504](https://github.com/backdrop/backdrop-issues/issues/4504)

## Miscellaneous changes

- [UX][DX] Improvements to the Configure Layout page [#5399](https://github.com/backdrop/backdrop-issues/issues/5399)
- Typos in README.md [#5119](https://github.com/backdrop/backdrop-issues/issues/5119)
- [UX] Layout listing: Add help text, to explain how the order and grouping in that page works [#4868](https://github.com/backdrop/backdrop-issues/issues/4868)
- Backdrop tableDrag cookie missing sameSite attribute, causes console warnings [#4718](https://github.com/backdrop/backdrop-issues/issues/4718)

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.20.4 tag is cut. I'll hold off on publishing the release until someone reviews the release notes and we're ready with 1.21.0.

**Comment by jenlampton** [comment]
Release notes draft (changelog is differnt after editing all issues in the milestone)

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating:**

* It **will** be necessary to run the update script (located at `/core/update.php`) for this release.
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**changelog since last version:**

## New features

- [DX] Collect Telemetry data on Web Server. [#5423](https://github.com/backdrop/backdrop-issues/issues/5423)

## Bug fixes

- [A11Y] Fixed: Increase contrast for "required" asterisk in all core themes. [#5425](https://github.com/backdrop/backdrop-issues/issues/5425)
- [DX] Fixed: Simpletest doesn't handle empty or malformed `.tests.info` files well. [#5415](https://github.com/backdrop/backdrop-issues/issues/5415)
- [UX] Fixed: Move "Search" buttons into "Actions" group to inherit action button styles. [#5387](https://github.com/backdrop/backdrop-issues/issues/5387)
- [UX] Permissions matrix should scroll horizontally when too wide for vertical tab. [#5384](https://github.com/backdrop/backdrop-issues/issues/5384)
- [DX]: Fixed: Add default value for options in `system_transliterate_machine_name()`. [#5365](https://github.com/backdrop/backdrop-issues/issues/5365)
- Dependencies version check not working for modules that use three digits (e.g. 1.0.14) [#5356](https://github.com/backdrop/backdrop-issues/issues/5356)
- Fixed: `cache_entity_*` tables must be dropped before running `update.php` when upgrading from Drupal 7. [#5340](https://github.com/backdrop/backdrop-issues/issues/5340)
- Fixed: `node--type` templates are not used when placed via the "existing content" block. [#5311](https://github.com/backdrop/backdrop-issues/issues/5311)
- Fixed: Add sameSite attribute to Backdrop tableDrag cookie. [#4718](https://github.com/backdrop/backdrop-issues/issues/4718)
- Fixed: Undefined property `originalLanguageDefault` in simpletest. [#4679](https://github.com/backdrop/backdrop-issues/issues/4679)
- Fixed: Login form throws SQL error when two usernames or passwords are sent in POST. [#4240](https://github.com/backdrop/backdrop-issues/issues/4240)
- Fixed blocked dependencies in Project Installer. [#4120](https://github.com/backdrop/backdrop-issues/issues/4120)
- [UX] Fixed: No success message after clicking "Save and exit" when creating a Views page display. [#3848](https://github.com/backdrop/backdrop-issues/issues/3848)
- Fixed: Prevent flickering on formatting options fieldset during expand/collapse animation. [#3596](https://github.com/backdrop/backdrop-issues/issues/3596)
- [UX] Fixed: Make "Add another item" buttons easier to distinguish from the field label. [#3520](https://github.com/backdrop/backdrop-issues/issues/3520)
- [UX] Fixed: Add numeric validation on entity IDs for visibility conditions. [#2668](https://github.com/backdrop/backdrop-issues/issues/2668)
- Fixed: Prevent PHP Notice: Undefined index: quantity in `views_plugin_pager_full->options_form()`. [#1435](https://github.com/backdrop/backdrop-issues/issues/1435)
- Fixed: Create a URL alias for the first user account. [#1417](https://github.com/backdrop/backdrop-issues/issues/1417)

## Miscellaneous changes

- Fixed: Improve description for `theme_head_tag()` function. [#5452](https://github.com/backdrop/backdrop-issues/issues/5452)
- [UX] Improve descriptions for the "dangerous" tokens `cancel-url` and `one-time-login-url`. [#5445](https://github.com/backdrop/backdrop-issues/issues/5445)
- [UX] Switch to using `'#type'=>'help'` instead of wrapping `#markup` in `<p>`. [#5412](https://github.com/backdrop/backdrop-issues/issues/5412)
- [UX][DX] Improve the description for the Path field on the configure layout page. [#5399](https://github.com/backdrop/backdrop-issues/issues/5399)
- Fixed: Typos in README.md [#5119](https://github.com/backdrop/backdrop-issues/issues/5119)
- [UX] Add help text on the Layout listing page to explain order and grouping. [#4868](https://github.com/backdrop/backdrop-issues/issues/4868)
- [UX] Add help text to the roles listing that explains how the order is used. [#4504](https://github.com/backdrop/backdrop-issues/issues/4504)
- Fixed: Remove mention of global theme settings from docblock on `theme_get_setting()`. [#451](https://github.com/backdrop/backdrop-issues/issues/451)

**Comment by jenlampton** [comment]
Release is out! 🎉
