### ISSUE TITLE
Backdrop 1.21.0 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5457]
Scheduled for January 15, 2022 1 - 4pm PT

## Pre-release tasks

- [x] If this is the Jan 15 release, ensure that the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file has been updated to reflect the new/current year.
- [x] Merge minor release commits (@quicksketch)
- [x] Move all unfinished issues to the next bug-fix release milestone (@quicksketch)
- [x] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@jenlampton)
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      - The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section containing **Notes for updating**
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text "The database update script does **not** need to be run."
        * or "It will be necessary to run the update script (located at /update.php) for this release."
    - [x] Include changelog since last version:
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub (@quicksketch)
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@jenlampton)
- [x] Unpublish preview release on backdropcms.org (assign to stpaultim / klonos / jenlampton / serundeputy / herbdool / quicksketch)
- [x] Update the front page download link on b.org @jenlampton

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @BWPanda 
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) (@herbdool)
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) ??? -- volunteer needed
- [x] Create a new language template file for the translation server - @olafgrabienski 

### Publicity tasks

- [ ] Add a notification to the dashboard @stpaultim
- [ ] Tweet that a new release is out @stpaultim
  * Use text like "We're thrilled to announce Backdrop version 1.21.0. This is the xxth new feature release of #BackdropCMS. https://backdropcms.org"
- [x] Publish blog post @stpaultim
- [x] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [x] Update the Wikipedia articles@klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [ ] Update the roadmap page on b.org @klonos

### Backdrop Website updates

- [x] docs.backdropcms.org @jenlampton
- [x] events.backdropcms.org @jenlampton 

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Code tasks

- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) (@herbdool)

### Publicity tasks

- [ ] Send a newsletter to subscribers @stpaultim 

### Backdrop Website updates

- [x] forum.backdropcms.org @jenlampton 
- [x] backdropcms.org @jenlampton 

See Also
---------
* [1.20.4 Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/5456)

**Comment by quicksketch** [comment]
Tag is cut https://github.com/backdrop/backdrop/releases/tag/1.21.0

**Comment by jenlampton** [comment]
Draft release notes:
---

The Backdrop community is proud to release version 1.21.0 of Backdrop CMS, following our 4-month release cycle.

**Notes for updating**

- **It will be necessary to run the update script** (located at `/core/update.php`) for this release.
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

## New features

- Add crop anchor point for Scale and Crop image effect. [#5080](https://github.com/backdrop/backdrop-issues/issues/5080)
- Add additional CSS classes on regions in Flexible layout templates. [#5044](https://github.com/backdrop/backdrop-issues/issues/5044)
- Add a "negate" option to the  visibility condition for roles. [#4689](https://github.com/backdrop/backdrop-issues/issues/4689)
- Add settings for which parts of the book navigation to display. [#5430](https://github.com/backdrop/backdrop-issues/issues/5430)
- Add filters for ClassName to the Interface for listing available tests. [#5257](https://github.com/backdrop/backdrop-issues/issues/5257)

## User Experience improvements

- Separate help text for publishing options [#3122](https://github.com/backdrop/backdrop-issues/issues/3122)
- Place breadcrumbs above the page title for new installs. [#4113](https://github.com/backdrop/backdrop-issues/issues/4113)
- Add Date format tokens for date fields. [#2069](https://github.com/backdrop/backdrop-issues/issues/2069)
- Add an 'empty' option to theme_item_list() [#5380](https://github.com/backdrop/backdrop-issues/issues/5380)
- Remove all instances of "please contact an administrator" from messaging [#4802](https://github.com/backdrop/backdrop-issues/issues/4802)
- Remove `item` from text on the `Add another item` button. [#5235](https://github.com/backdrop/backdrop-issues/issues/5235)

## Developer Experience improvements

- Add entity_view() into core [#1739](https://github.com/backdrop/backdrop-issues/issues/1739)
- Provide a helper function to prevent a layout from wrapping around content. [#1728](https://github.com/backdrop/backdrop-issues/issues/1728)

## Miscellaneous changes

- Update jQuery UI to 1.13.0 [#5401](https://github.com/backdrop/backdrop-issues/issues/5401)
- Optimize menu_navigation_links_rebuild() [#5389](https://github.com/backdrop/backdrop-issues/issues/5389)
- Remove Zen.CI from the core repository. [#5197](https://github.com/backdrop/backdrop-issues/issues/5197)
- Enable telemetry module on new installs [#5253](https://github.com/backdrop/backdrop-issues/issues/5253)

**Comment by herbdool** [comment]
I'm not clear on why updating Platform.sh and backdrop-composer are immediate but Pantheon requires waiting. Can we just do them all immediately or wait with all?

**Comment by olafgrabienski** [comment]
Language file updated, see **1.21.x** column on https://localize.backdropcms.org/translate/downloads.

**Comment by jenlampton** [comment]
b.org and the forum site have been updated to 1.21.1
