### ISSUE TITLE
Backdrop 1.21.1 Release Checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5468]
Release scheduled for January 21, 2022 4pm-5pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @quicksketch 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (`update.php`) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at `/core/update.php`) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @stpaultim 
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.21.1: https://backdropcms.org that fixes a regression in Menu Item Links."

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop Website updates

- [x] N/A backdropcms.org 
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [x] N/A forum.backdropcms.org 
- [x] localize.backdropcms.org @jenlampton

**Comment by quicksketch** [comment]
Tag is cut: https://github.com/backdrop/backdrop/releases/tag/1.21.1

**Comment by jenlampton** [comment]
Draft release notes:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only

**Notes for Updating**

* It will be necessary to run the update script (located at `/core/update.php`) for this release.
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

#Changes since 1.21.0

## Bug fixes

- Fixed: duplicate Menu Links REGRESSION in 1.21  [#5460](https://github.com/backdrop/backdrop-issues/issues/5460)

## Usability Improvements

- Fixed: Use the text "User accounts" in new token description text. [#5459](https://github.com/backdrop/backdrop-issues/issues/5459)

**Comment by stpaultim** [comment]
Tweet sent.

**Comment by jenlampton** [comment]
I've updated all the relevant sites. That's everything other than the Wikipedia entries, I think this issue can be closed! 🎉

**Comment by bugfolder** [comment]
> I've updated all the relevant sites.

https://backdropcms.org/admin/reports/status is still reporting that b.org is on version 1.20.0 and showing a warning.

https://forum.backdropcms.org/admin/reports/status is reporting that it's on 1.20.3.

Should these be updated?

**Comment by jenlampton** [comment]
Not until we're sure there won't be another release. We usually wait 2
weeks before updating our more important sites.

**Comment by bugfolder** [comment]
Ah, gotcha. Since docs.b.org and events.b.org are already updated, I guess that makes them the "less important" sites 😉.

**Comment by jenlampton** [comment]
Yeah, they have fewer authenticated users.
