### ISSUE TITLE
Backdrop 1.21.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5513]
Release scheduled for MM DD, 2022 11am - 1pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @klonos  
- [x] Move all unfinished issues to the next bugfix release milestone @klonos 
- [x] Review all closed issues in milestone: @klonos 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @klonos 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @klonos see https://www.drupal.org/sa-core-2022-003

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @klonos 
- [x] Mark the release node on b.org as a security release @klonos 
- [x] [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) - (assign to jenlampton / quicksketch)
- [x] Update the front page download link on b.org @klonos 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [ ] Update the Security Advisory with CVE (assign to jenlampton / quicksketch)

## Backdrop Website updates

- [x] backdropcms.org @jenlampton 
- [ ] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton 
- [ ] localize.backdropcms.org @jenlampton 

## See Also

- [Checklist for 1.20.5 release](https://github.com/backdrop/backdrop-issues/issues/5514)

**Comment by quicksketch** [comment]
The tag for https://github.com/backdrop/backdrop/releases/tag/1.21.2 is now cut.

**Comment by jenlampton** [comment]
Release notes draft:

---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

* [BACKDROP-SA-CORE-2022-001](https://backdropcms.org/security/backdrop-sa-core-2022-001)

**Notes for updating:**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Changes since version 1.xx.x** are listed below.

@todo

**Comment by quicksketch** [comment]
Update.php _does_ need to be run this release, due to https://github.com/backdrop/backdrop-issues/issues/5035.

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.21.2 is out!

**Comment by klonos** [comment]
Closing this in favor of #5527.
