### ISSUE TITLE
Backdrop 1.20.5 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5514]
Release scheduled for MM DD, 2022 11am - 1pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 

## See Also

- [Checklist for 1.21.2 release](https://github.com/backdrop/backdrop-issues/issues/5513)

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.20.5 is cut.

No changes other than the security patch.

**Comment by klonos** [comment]
I've marked as a security release in b.org 👍🏼

**Comment by jenlampton** [comment]
hold onto those horses...  :)

**Comment by jenlampton** [comment]
Release notes draft:

---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

* [BACKDROP-SA-CORE-2022-001](https://backdropcms.org/security/backdrop-sa-core-2022-001)

**Notes for updating:**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Changes since version 1.xx.x** are listed below.

@todo

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.20.5 is out!
