### ISSUE TITLE
Backdrop 1.20.6 Release checklist

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5526]
Release scheduled for MM DD, 2022 11am - 1pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Mark the release node on b.org as a security release @klonos

## See Also

- [Checklist for 1.21.3 release](https://github.com/backdrop/backdrop-issues/issues/5513)

**Comment by jenlampton** [comment]
Draft release notes:

---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:
* CVE-2022-24590 (@todo - needs link to SA)

**Notes for updating**
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Comment by quicksketch** [comment]
Release notes look good. This is a security-only release for 1.20.x.

The tag is cut and ready for release at https://github.com/backdrop/backdrop/releases/tag/1.20.6

**Comment by jenlampton** [comment]
SA needs review: https://backdropcms.org/security/backdrop-sa-core-2022-002

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.20.6 is out 🎉
