### ISSUE TITLE
Backdrop 1.21.3 Release checklist

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5527]
Release scheduled for MM DD, 2022 11am - 1pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @klonos  
- [x] Move all unfinished issues to the next bugfix release milestone @klonos 
- [x] Review all closed issues in milestone: @klonos 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [ ] Close the milestone @klonos 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @klonos (no d.o issue for reference)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @klonos 
- [x] Mark the release node on b.org as a security release @klonos 
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) - (assign to jenlampton / quicksketch)
- [x] Update the front page download link on b.org @klonos 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool 
- [x] Update Composer @herbdool 
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) @Wylbur 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems
- [x] Update the Security Advisory with CVE (assign to jenlampton / quicksketch)

## Backdrop Website updates

- [x] backdropcms.org @jenlampton 
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 

## See Also

- [Checklist for 1.20.6 release](https://github.com/backdrop/backdrop-issues/issues/5526)

**Comment by quicksketch** [comment]
With today's release being security-focused, I've merged the (only) PR for release. I think we're ready to close the 1.21.3 milestone and transfer issues to 1.21.4.

**Comment by jenlampton** [comment]
Copying draft release notes from 1.20 lssue:

---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:
* CVE-2022-24590 (@todo - needs link to SA)

**Notes for updating**
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Comment by quicksketch** [comment]
We should also include https://github.com/backdrop/backdrop-issues/issues/5498 in the release notes (the only other commit for this release).

Tag is cut and ready for release at https://github.com/backdrop/backdrop/releases/tag/1.21.3

**Comment by jenlampton** [comment]
Draft SA could use a review: https://backdropcms.org/security/backdrop-sa-core-2022-002

**Comment by laryn** [comment]
Since this SA is released after the fix is out, would it be more appropriate to change "Backdrop CMS doesn't sufficiently sanitize data..." to "Previous versions of Backdrop CMS did not sufficiently sanitize data..."?

**Comment by jenlampton** [comment]
@laryn the SA and the release will come out at the same time (neither are out yet). The CVE was out before the SA and the fix (which is unusual).

**Comment by laryn** [comment]
Okay, fair enough -- my point still stands though. The SA was not out before the fix so using the past tense regarding the vulnerability still makes sense to me. But it's just a suggestion, I realize there's a history and tradition of how to write these...

**Comment by jenlampton** [comment]
> The SA was not out before the fix

No, neither the SA or the fix are out yet. They will both come out at the same time (in a few minutes).

**Comment by quicksketch** [comment]
I agree that the verbiage on security announcements are confusing. However, they've always been written in present tense. I suppose because they are "announcements" they're meant to be read at the time of release? Perhaps we can discuss this a general pattern for them and consider switching them to past tense. I frequently read them well after the release for reference, and by that time the security issue has been long resolved. The present-tense phrasing always gives me pause while I have to find the applicable version number and the date of the announcement.

**Comment by laryn** [comment]
I was just trying to give the draft SA a review, not open a can of worms. 😓

**Comment by quicksketch** [comment]
I made minor updates to the SA including adding Tim as a coordinator and rephrasing. (I left the verb tense alone however).

**Comment by jenlampton** [comment]
Oh! was Tim involved? Sorry if I missed that :)

**Comment by jenlampton** [comment]
I've also edited and removed the question marks from the release numbers. Are we ready to release?

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.21.3 is out! 🎉

**Comment by jenlampton** [comment]
all b.org sites updated.

**Comment by klonos** [comment]
Closing in favor of #5546
