### ISSUE TITLE
Backdrop 1.20.7 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5547]
Release scheduled for Mar 16, 2022 2pm - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @jenlampton (see other issue)

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @jenlampton (see other issue)
- [x] Mark the release node on b.org as a security release @jenlampton 

## See Also

- [Checklist for 1.21.4 release](https://github.com/backdrop/backdrop-issues/issues/5546)

**Comment by jenlampton** [comment]
Draft release notes:

---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:
- SA-BACKDROP-CORE (link me)

**Notes for updating**
* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

**Comment by jenlampton** [comment]
SA and release notes ready for review.

**Comment by jenlampton** [comment]
release is out: https://github.com/backdrop/backdrop/releases/tag/1.20.7
