### ISSUE TITLE
Backdrop 1.21.5 Release Checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5616]
Release scheduled for May 15, 2022 4pm - 6pm PT

## Pre-release tasks

- [x] Merge commits (BWPanda)
- [x] Create the next bugfix milestone (BWPanda)
- [x] Move all unfinished issues to the next bugfix release milestone ( BWPanda)
- [x] Review all closed issues in milestone:  (herbdool)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (herbdool)
- [x] Draft Release notes (herbdool)
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks  (assign to BWPanda/herbdool)

- [x] Update bootstrap.inc with version number
- [x] Tag for release, and push tag to GitHub
- [x] Revert version number back
- [x] Create release notes on GitHub, and publish release
- [x] ~Update the front page download link on b.org~ (see 1.22.0 release)
- [x] ~Tweet that a new release is out~ (see 1.22.0 release)

## See Also

- https://github.com/backdrop/backdrop-issues/issues/5617

**Comment by herbdool** [comment]
Done and done!
