### ISSUE TITLE
Backdrop 1.22.0 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5617]
Scheduled for May 15, 2022 4am - 6pm PT

## Pre-release tasks

- [x] Merge minor release commits (BWPanda)
- [x] Move all unfinished issues to the next bug-fix release milestone (BWPanda)
- [x] Review all closed issues in milestone: (laryn)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (laryn)
- [x] Draft Release notes (laryn)
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks (herbdool)

- [x] Update bootstrap.inc with version number
- [x] Tag for release, and push tag to GitHub
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`)
- [x] Create release notes on GitHub, and publish release (herbdool)
- [x] Unpublish preview release on backdropcms.org (stpaultim)
- [x] Update the front page download link on b.org (stpaultim)
- [x] Update the roadmap page on b.org (stpaultim)
- [x] Create a new language template file for the translation server (@olafgrabienski - see https://github.com/backdrop-ops/localize.backdropcms.org/issues/27 until this is automated)

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @BWPanda
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) (assign to serundeputy / jenlampton)
- [x] Update Composer (assign to quicksketch / serundeputy / herbdool)
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer neeed)
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) (@herbdool)
- [x] update docs.backdropcms.org to latest version @jenlampton

### Publicity tasks

- [x] Add a notification to the dashboard (@stpaultim)
- [x] Tweet that a new release is out (@stpaultim)
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [x] Publish blog post (@stpaultim)
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter (assign to stpaultim / tomgrandy / klonos / jenlampton)
- [x] Update the Wikipedia articles (stpaultim)
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

### Backdrop Website updates

- [x] docs.backdropcms.org (assign to @jenlampton / @bwpanda / @bugfolder)
- [x] events.backdropcms.org (assign to @jenlampton / @bwpanda / @bugfolder)

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Publicity tasks

- [x] Send a newsletter to subscribers (assign to @bwpanda / stpaultim / jenlampton)

### Backdrop Website updates

- [x] backdropcms.org (assign to @jenlampton / @bwpanda / @bugfolder)
- [x] forum.backdropcms.org (assign to @jenlampton / @bwpanda / @bugfolder)

See Also
---------
* https://github.com/backdrop/backdrop-issues/issues/5616

**Comment by laryn** [comment]
Draft release notes:

---------

## New features

- Add a new cropped image style specifically for cards. [#5607](https://github.com/backdrop/backdrop-issues/issues/5607)
- Add the ability to enable Backdrop-only required modules during an upgrade from Drupal 7. [#5499](https://github.com/backdrop/backdrop-issues/issues/5499)
- Add a warning flag in the Status report if there are duplicate copies of a module. [#5464](https://github.com/backdrop/backdrop-issues/issues/5464)
- Add various UI improvements in the Book module. [#5331](https://github.com/backdrop/backdrop-issues/issues/5331)
- Add a link in the module browser to each module's BackdropCMS.org project page. [#5003](https://github.com/backdrop/backdrop-issues/issues/5003)
- Provide "Cards" by default – a new hidden-path content type. [#4903](https://github.com/backdrop/backdrop-issues/issues/4903)
- Configure default date formats based on timezone/country. [#4645](https://github.com/backdrop/backdrop-issues/issues/4645)
- Add a setting to specify which Views display(s) get created by default. [#2978](https://github.com/backdrop/backdrop-issues/issues/2978)
- Add a new component to the Admin Bar with information about the current page. [#2626](https://github.com/backdrop/backdrop-issues/issues/2626)
- Allow blocks to be disabled in Layouts. [#1936](https://github.com/backdrop/backdrop-issues/issues/1936)

## Bug fixes

- Fix incorrect links to GitHub in module browser for core modules. [#5623](https://github.com/backdrop/backdrop-issues/issues/5623)
- Fix views-related tests after recent changes for default Cards functionality. [#5615](https://github.com/backdrop/backdrop-issues/issues/5615)
- Fix default sort order for front page card view. [#5608](https://github.com/backdrop/backdrop-issues/issues/5608)
- Fix extraneous gray stripe left over when removing Cards grid. [#5599](https://github.com/backdrop/backdrop-issues/issues/5599)
- Fix output buffer notices. [#5594](https://github.com/backdrop/backdrop-issues/issues/5594)

## Miscellaneous changes

- Add new screenshot for Basis which includes the new Cards content. [#5621](https://github.com/backdrop/backdrop-issues/issues/5621)
- Remove unnecessary path pattern for Cards. [#5597](https://github.com/backdrop/backdrop-issues/issues/5597)
- Add description text to the 'Administer custom blocks' permission. [#5544](https://github.com/backdrop/backdrop-issues/issues/5544)
- Drop support for PHP versions less than 5.6. [#3992](https://github.com/backdrop/backdrop-issues/issues/3992)
- Separate "Administer comments and comment settings" into two distinct permissions. [#336](https://github.com/backdrop/backdrop-issues/issues/336)

**Comment by quicksketch** [comment]
Great work folks! I'm super appreciative to @stpaultim, @herbdool, @laryn, and @BWPanda for coordinating and creating both the 1.22.0 and the 1.21.4 release!

**Comment by jenlampton** [comment]
I've updated the docs site and the events site to 1.22.0.

**Comment by jenlampton** [comment]
I've updated the main site and the forum site to 1.22.0.
