### ISSUE TITLE
Backdrop 1.22.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5691]
Release scheduled for July 20, 2022 3pm - 5pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
      * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) - (assign to jenlampton / quicksketch)
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

- [x] N/A Update the Security Advisory with CVE 
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [x] N/A  Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool
- [x] Update Composer @herbdool
- [x] N/A  Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) (assign to ??? -- volunteer needed)
- [x] N/A Update the Wikipedia articles @klonos 
  - [x] N/A  https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] N/A  https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [x] backdropcms.org @jenlampton 
- [x] beta.backdropcms.org @jenlampton 
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 
- [ ] localize.backdropcms.org @jenlampton 

See also: Backdrop 1.21.6 Release checklist

## See Also

- [Checklist for 1.xx.x release](https://github.com/backdrop/backdrop-issues/issues/5692)

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.22.1 tag is cut!

**Comment by jenlampton** [comment]
Draft release notes:

---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:

* Backdrop core - Moderately critical - Information Disclosure - BACKDROP-SA-CORE-2022-004

**Important information**

Following this release, Backdrop will assume by default that custom stream wrappers (like [S3 File System](https://github.com/backdrop-contrib/s3fs), among others) should be private by default so that Backdrop will manage downloads and access control. If a module intentionally wishes to serve files with no access checking or management by Backdrop, the module should implement `hook_file_download()`.

Since various contributed stream wrapper modules might not be able to update immediately for this security release, site owners may also specify which stream wrappers should be treated as public stream wrappers (with no access control). If content from a stream wrapper on your site stops working after this update, you can add the following line to `settings.php`:

```
$conf['file_additional_public_schemes'] = array('example');
```

…where `example` is replaced by the name of the affected stream wrapper. (For example, s3 or https.) The name of the stream wrapper will depend on the affected module and its configuration.

If you encounter this problem, please also verify or submit an issue in the module's queue to implement `hook_file_download()` for this security advisory.

**Notes for updating**

- **It will be necessary to run the update script** (located at `/core/update.php`) for this release.
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**Changes since version 1.22.0** are listed below.

[TODO]

**Comment by quicksketch** [comment]
Looks great. :+1:

**Comment by jenlampton** [comment]
We heard from @indigoxela that there was an issue with this release (thank you!) so I've started on https://github.com/backdrop/backdrop-issues/issues/5693. 

For anyone who still has tasks on this list, please hold off until later today, there will be another release.
