### ISSUE TITLE
Backdrop 1.22.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5693]
Release scheduled for July 21, 2022 3pm - 5pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
      * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [ ] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @herbdool 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool (or quicksketch)
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) @wylbur
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [ ] backdropcms.org @jenlampton 
- [ ] beta.backdropcms.org @jenlampton 
- [ ] docs.backdropcms.org @jenlampton 
- [ ] events.backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton 
- [x] N/A localize.backdropcms.org @jenlampton 

## See Also

- N/A there does not need to be another release for 1.21.x

**Comment by jenlampton** [comment]
Draft release notes:

---


Maintenance release for Backdrop CMS. This update contains a single bug fix introduced in 1.22.1.

**Notes for updating**

 - The database update script does **not** need to be run.
 - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**Changes since version 1.xx.x** are listed below.

- [Fixed: Update hook in 1.22.1 mistakenly recommends removing entity reference.](https://github.com/backdrop/backdrop-issues/issues/5694)

**Comment by quicksketch** [comment]
Thanks @jenlampton! I added a bit more description to the release notes. The 3 small PRs we have for this release are all merged and the tag is now ready: https://github.com/backdrop/backdrop/releases/tag/1.22.2

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.22.2 is out!
