### ISSUE TITLE
[D10][PS] CSS and JavaScript aggregation performance improvements

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5718]
This issue is to explore if the same issue as described in [Stampedes and cold cache performance issues with css/js aggregation](https://www.drupal.org/project/drupal/issues/1014086) exists in Backdrop, and if we could benefit by implementing the same/equivalent changes.

> ## Problem/Motivation
> 
> Our current logic for building CSS and Javascript aggregates relies on creating the aggregates from within the page being requested, this leads to a number of issues:
> 
> 1. When there are no aggregates on disk, the page response has to create the files on disk before it can be served. This adds hundreds of millisecond or seconds to uncached page requests. Additionally, each aggregate is created in sequence. So if you have 30 requests in a second, and the pages they're requesting have the same ten aggregates on, each individual aggregate needs to be created, one by one, before any of those 30 pages can actually serve any HTML at all. This can take hundreds of milliseconds or seconds, which can lead to 503s on cache clears.
> 
> 2. Filenames have to be tracked in state - this means additional queries (and sometimes writing back to state) on every HTML request. When this issue was originally opened, filenames were tracked in variables which was a much bigger issue, now it's a minor one, but still adds to general post-cache-clear churn.
> 
> 3. Because it's expensive already, it makes it difficult to add on-the-fly js minification and similar, since that would further degrade cold cache performance.

...

> ## Before
> 1. HTML request.
> 2. Check if the file exists on disk
> 3. Build the aggregate and write it back to disk if it doesn't, link from the head tag.
> 4. Back to step #2 for each CSS and JS aggregate potentially a dozen times.
> 5. Serve the HTML page to the browser.
> 6. Browser requests files that already exist on disk.

> ## After
> 1. HTML request
> 2. Generate just a filename as part of the head tag (no filesystem access, no writes to database)
> 3. Serve the HTML page to the browser.
> 4. Browser requests the asset URLs. If they don't exist, they're created and served from PHP. If they do they're served from the filesystem. This allows multiple aggregates to be generated simultaneously by separate HTTP requests, all without blocking any HTML being served.

**Comment by klonos** [comment]
...noting that that D10 issue has several follow-up/related issues that may also apply to us:
- [ ] [Add stampede protection for css and js aggregation](https://www.drupal.org/project/drupal/issues/886488) (against D7 core at the time of writing)
- [ ] [Support brotli compression of assets](https://www.drupal.org/project/drupal/issues/3184242) - related issues on our end: #4748 / #4743
- [ ] [Rewrite rules for gzipped CSS and JavaScript aggregates cause lots of lstats for files that will never exist](https://www.drupal.org/project/drupal/issues/1040534)
- [ ] [Aggregation creates two extra aggregates when it encounters {media: screen} in a library declaration](https://www.drupal.org/project/drupal/issues/2695871)
- [ ] [Make css/js optimized assets path configurable](https://www.drupal.org/project/drupal/issues/3027639)
- [ ] [Remove the aggregate stale file threshold and state entry](https://www.drupal.org/project/drupal/issues/3301573)
- [ ] [Compress aggregate URL query strings if they're over 950 chars](https://www.drupal.org/project/drupal/issues/3303067)
