### ISSUE TITLE
Backdrop 1.23.0-preview Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5757]
Scheduled for September 2, 2022 2pm - 4pm PT

## Pre-release tasks

- [x] If this is the Jan 1 pre-release, then make sure to update the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file.
- [x] Merge commits (@quicksketch)
- [x] Create a new minor release milestone (@quicksketch)
- [x] Move all unfinished issues to the next minor release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (assign to klonos / jenlampton / stpaultim )
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    - This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [ ] Review issues for new features (assign to @jenlampton / @klonos / @cellear)
  - [ ] Add a conclusion suitable for blog post + release notes
  - [ ] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [ ] Add `Needs change record` label if the the issue contains an API change.
  - [ ] Add `Needs translation` label if the the issue contains string translations.
- [ ] Draft blog post for release on the 15th (assign to stpaultim / tomgrandy / klonos / jenlampton)
- [ ] Update list of modules included in backdrop core (assign to bugfolder / klonos / jenlampton)
- [ ] Draft roadmap updates for backdropcms.org (assign to stpaultim / klonos / jenlampton)
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (e.g. `1.10.0-preview`) (@quicksketch)
- [x] Tag for release, and push tag to GitHub(@quicksketch)
- [x] Note: New incremented branch for development is usually created on release day
- [x] Revert version number back on 1.x branch with the same minor number (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub **Important: Check "This is a pre-release" checkbox when creating release** (@quicksketch)

## Website updates
- [ ] beta.backdropcms.org (assign to @jenlampton / @bwpanda / @bugfolder)

## Post-release Publicity + documentation tasks

- [x] Tweet that a preview release is out (assign to stpaultim / jimbirch / jenlampton / quicksketch)
- [ ] Publish roadmap updates for backdropcms.org (assign to stpaultim / klonos / jenlampton)

**Comment by quicksketch** [comment]
Preview release is now out! https://github.com/backdrop/backdrop/releases/tag/1.23.0-preview

Release notes can be found on the release page. I also wrote up a change record for the `File::uri()` change, since we did not yet have one: https://docs.backdropcms.org/change-records/file-uri-now-returns-path-to-file-entity-page-not-the-file-path

**Comment by quicksketch** [comment]
Today is release day so we can close out this issue and continue in https://github.com/backdrop/backdrop-issues/issues/5781.
