### ISSUE TITLE
Drupal 7.92 commits: crossport or mark as NA

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5770]
Another long todo list.

1. Pick one that applies to Backdrop
2. Create an issue and replace the `#xx` below with the number
3. Create a PR related to that issue

- [x] #5805 | [5b004ccafa](https://git.drupalcode.org/project/drupal/-/commit/5b004ccafa9808316fb8a8a3d75cc53cf596c0cc) | [Issue #3004215 by arifkhn46: Method DatabaseCondition::__toString() must return a string value](https://drupal.org/node/3004215)
- [x] #5806 [13472d3c46](https://git.drupalcode.org/project/drupal/-/commit/13472d3c4617283446956f7c0de9749023cca16a) | [Issue #2574003 by poker10, stBorchert: Table alias missing in query condition in taxonomy_select_nodes()](https://drupal.org/node/2574003)
- [ ] #xx | [2464f1139a](https://git.drupalcode.org/project/drupal/-/commit/2464f1139a91264d614c1926cdfc28f90fcb0541) | [Issue #3276848 by DamienMcKenna: run-tests.sh gives "Deprecated: str_replace(): Passing null to parameter" with PHP 8.0](https://drupal.org/node/3276848)
- [x] #5727 | [9fd49e3601](https://git.drupalcode.org/project/drupal/-/commit/9fd49e3601152489c626374e3e0bc941ee17506b) | [Issue #3299271 by poker10: [D7 PHP 8.1] strlen(): Passing null to parameter #1 ($string) of type string is deprecated in drupal_random_bytes()](https://drupal.org/node/3299271)
- [ ] #xx | [cfb8a71b4e](https://git.drupalcode.org/project/drupal/-/commit/cfb8a71b4ef9e0a7c8fbc0a4500aad649b0adef8) | [Issue #2772107 by poker10, cgv, eojthebrave, q0rban, daffie, johnnydarkko, drewish, David_Rothstein, cbergmann: UNION queries don't support ORDER BY clauses](https://drupal.org/node/2772107)
- [x] #5807 [32020ecb18](https://git.drupalcode.org/project/drupal/-/commit/32020ecb1850b8a593e185fc97437b7df75f4d11) | [Issue #2021571 by rszrama: Preview of menu machine name is inaccurate on while adding a menu](https://drupal.org/node/2021571)
- [x] NA | [782debf10d](https://git.drupalcode.org/project/drupal/-/commit/782debf10dd38e1e09cfdc75ad1414b67a6c3fec) | [Issue #3064734 by sjerdo, geoffreyr, karan_mudi: DatabaseStatementPrefetch::current PHP function array_unshift() are used incorrectly](https://drupal.org/node/3064734)
- [x] #5815 [ee2a2c7fa4](https://git.drupalcode.org/project/drupal/-/commit/ee2a2c7fa4c5548e2b26ff5441c0ad530d20fd59) | [Issue #3000191 by poker10, drunken monkey: Complex cloned query dependent on __toString() call](https://drupal.org/node/3000191)
- [x] NA | [f83b9368bf](https://git.drupalcode.org/project/drupal/-/commit/f83b9368bf36a42082b7c79b4e847df926058556) | [Issue #3273723 by djdevin, loopy1492, swim: fopen() error in stream_wrappers.inc on PHP 8](https://drupal.org/node/3273723)
- [ ] #xx | [64aa5028b9](https://git.drupalcode.org/project/drupal/-/commit/64aa5028b9d13213ba33815794767a4f35b15cb9) | [Issue #2649926 by SeanA, poker10, walangitan: [D7] Field UX: machine name disappears](https://drupal.org/node/2649926)
- [ ] #xx | [b03b6139d5](https://git.drupalcode.org/project/drupal/-/commit/b03b6139d503373203e5e2bc1787f4a52435f1fe) | [Issue #2926150 by MrHaroldA, BarisW: D7 Remove the open_basedir requirement check](https://drupal.org/node/2926150)
- [ ] #xx | [ee6e664594](https://git.drupalcode.org/project/drupal/-/commit/ee6e664594eda6335243d5fa8a3e8133e3554b67) | [Issue #1994292 by David_Rothstein: LanguageInterface::TYPE_URL (D8) and LANGUAGE_TYPE_URL (D7) have no name or description](https://drupal.org/node/1994292)
- [ ] #xx | [cc05facbd2](https://git.drupalcode.org/project/drupal/-/commit/cc05facbd2542e049fd1b4df1d0f02f2596c6520) | [Issue #873722 by ezheidtmann, aaron.r.carlton, catch, poker10, MaskyS, damiankloip, naxoc: 'autocreate' == 0](https://drupal.org/node/873722)
- [ ] #xx | [c32d02fe1a](https://git.drupalcode.org/project/drupal/-/commit/c32d02fe1ae3e2089d46269bf7cdc62cca93a2e5) | [Issue #920840 by nagba, poker10, hefox, Dave Reid: Broken images displayed and PHP notices when file/image field values are missing](https://drupal.org/node/920840)
- [ ] #xx | [e354dcb57b](https://git.drupalcode.org/project/drupal/-/commit/e354dcb57bcf77889a367665999e63d73ca7315b) | [Issue #2644276 by poker10, pashupathi nath gajawada, henryhu: Mixed case taxonomy terms not loaded from the internal entity cache](https://drupal.org/node/2644276)
- [x] #6852  | [11082e251b](https://git.drupalcode.org/project/drupal/-/commit/11082e251bea7cde0fc6a0d7779354782f98341e) | [Issue #2582069 by plach, poker10, Nephele: [D7] Unable to use Condition objects with joins](https://drupal.org/node/2582069)
- [ ] #xx | [c63d29bd2d](https://git.drupalcode.org/project/drupal/-/commit/c63d29bd2d327119d605621c75459681850da580) | [Issue #2218647 by poker10, swim, Patil_kunal27: [D7] Undefined property: stdClass::$nid in node_tokens()](https://drupal.org/node/2218647)
- [ ] #xx | [bf07341ed6](https://git.drupalcode.org/project/drupal/-/commit/bf07341ed6754fc0e4adb50f53953a3e23563c79) | [Issue #1530486 by poker10, chimericdream: [D7] list_field_validate() doesn't seem to accommodate select lists with <optgroup>](https://drupal.org/node/1530486)
- [ ] #xx | [aaddb71b74](https://git.drupalcode.org/project/drupal/-/commit/aaddb71b7428c6733616011fa01e31083785f029) | [Issue #2679983 by poker10, ChaseOnTheWeb: Specified role weights not preserved in admin](https://drupal.org/node/2679983)
- [ ] #xx | [047ef12141](https://git.drupalcode.org/project/drupal/-/commit/047ef1214170ea061cad9291ce728cf100c4853b) | [Issue #3006007 by marco: Don't try to load the user picture if it's not set](https://drupal.org/node/3006007)
- [ ] #xx | [f5a073a49b](https://git.drupalcode.org/project/drupal/-/commit/f5a073a49b85e974b6ccde898857509b6f363f56) | [Issue #2474943 by douggreen, poker10, Fabianx, donaldinou: system_list('bootstrap') returns numeric keys instead of module names](https://drupal.org/node/2474943)
- [ ] #xx | [6fbeaa6b35](https://git.drupalcode.org/project/drupal/-/commit/6fbeaa6b35ce5e90b5c04c2cb7867ea1109a0963) | [Issue #2669254 by Marty2081, poker10: PDOException when calling locale_add_language() with $enabled = FALSE](https://drupal.org/node/2669254)
- [ ] #xx | [40d1dbb9f4](https://git.drupalcode.org/project/drupal/-/commit/40d1dbb9f4050f4386e39513e1d2a27ef08fbefb) | [Issue #3138348 by poker10, awset, mikeytown2: system_batch_page() should call drupal_exit() after drupal_access_denied()](https://drupal.org/node/3138348)
- [ ] #xx | [6d7d36463c](https://git.drupalcode.org/project/drupal/-/commit/6d7d36463c2c44a14fee0ac53d8051b82a055580) | [Issue #2884171 by mcdruid, Seth Snyder: The drupal_render() function could use a bit more protection](https://drupal.org/node/2884171)
- [ ] #xx | [e8872374e8](https://git.drupalcode.org/project/drupal/-/commit/e8872374e8a1653769f793c6b99f0a650fe45ce7) | [Issue #2779833 by iryston, amar.deokar, poker10: Fix Drupal 7 .htaccess to protect .orig and .save files from view](https://drupal.org/node/2779833)
- [ ] #xx | [b14885a783](https://git.drupalcode.org/project/drupal/-/commit/b14885a7832caf143d4b0eb2739340e2d576e444) | [Issue #1160764 by ianthomas_uk, Désiré, poker10, Dave Reid, SebCorbin, agentrickard: URL alias load is inconsistent if there are more then one alias](https://drupal.org/node/1160764)
- [ ] #xx | [b807051feb](https://git.drupalcode.org/project/drupal/-/commit/b807051febe48e5ace6795f414304e82593fb445) | [Issue #1327224 by Berdir, johnv, ryan.gibson, poker10, chris.leversuch, nyirocsaba, edb, bkosborne, vikashsoni, xjm, andypost, alexpott: Access denied to taxonomy term image](https://drupal.org/node/1327224)
- [x] #5969 | [9b89fa9c19](https://git.drupalcode.org/project/drupal/-/commit/9b89fa9c190e69f7d15d974f8707e4bda8b28499) | [Issue #2990723 by poker10, tatarbj, DamienMcKenna: Security improvement for l() function](https://drupal.org/node/2990723)
- [x] NA (but see related #5968) | [d07ae5de14](https://git.drupalcode.org/project/drupal/-/commit/d07ae5de14e43f8be8987691e75de92d7dc6dfc1) | [Issue #2594955 by poker10, predy, David_Rothstein: [D7] Duplicate HTML IDs are created for file_managed_file fields](https://drupal.org/node/2594955)
- [x] #5963 | | [e15ccfbf6a](https://git.drupalcode.org/project/drupal/-/commit/e15ccfbf6a56f071f66eff9183a5a9f9dcf666dd) | [Issue #3293649 by mcdruid: drupal_http_request() fails to strip Cookie or Authorization headers on HTTP downgrade](https://drupal.org/node/3293649)
- [x] #5960 | [6af33a4](https://git.drupalcode.org/project/drupal/-/commit/6af33a4) | [Back port: Incorrect handling of file upload limit exceeded - file widget disappears](https://www.drupal.org/project/drupal/issues/2749245)
- [x] #5958 | [fb78f2db65](https://git.drupalcode.org/project/drupal/-/commit/fb78f2db65929076d35c5876d2c34faa8c6fb111) | [Issue #702778 by Pasqualle, poker10, mcdruid, Fabianx: Multiple pagers on the same page](https://drupal.org/node/702778)

Generated with:
```
git log  7.91..7.92 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://git.drupalcode.org/project/drupal/-/commit/%H) | [%s](https://drupal.org/node/)"
```

**Comment by laryn** [comment]
(FYI I edited the text to add all the node ids to the drupal.org links)

**Comment by argiepiano** [comment]
I used to be able to edit the original post to mark issues as "NA", but I can't do it anymore. It looks like my access level has been changed? Can someone please restore my edit access? @klonos perhaps?

I was going to mark  3273723 as NA, since it has already been solved in Backdrop.

**Comment by kiamlaluno** [comment]
I cannot edit the issue summary either. The second point listed there (*Create an issue and replace the #xx below with the number*) should be removed, if only specific users can edit the issue summary.

**Comment by klonos** [comment]
@argiepiano I've adjusted some things. Can you please check now?
