### ISSUE TITLE
Backdrop 1.23.0 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5781]
Scheduled for September 15, 2022 4pm-6pm PT

## Pre-release tasks

- [x] Merge minor release commits (@quicksketch)
- [x] Move all unfinished issues to the next bug-fix release milestone @quicksketch 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`)  @quicksketch
- [x] Create release notes on GitHub, and publish release @jenlampton
- [x] Unpublish preview release on backdropcms.org @jenlampton
- [x] Update the front page download link on b.org @stpaultim 
- [x] Create a new language template file for the translation server (assign to @olafgrabienski - see https://github.com/backdrop-ops/localize.backdropcms.org/issues/27 for automation)

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @wylbur 
- [x] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [x] Update [Pantheon](https://github.com/backdrop-ops/backdrop-pantheon) @herbdool 
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) @wylbur

### Publicity tasks

- [x] Tweet that a new release is out @stpaultim 
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [x] Publish blog post @stpaultim 
- [x] Update list of modules included in backdrop core @jenlampton 
- [x] Update the roadmap page on b.org @stpaultim 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton
- [x] Update the Wikipedia articles @klonos 
  * [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  * [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

### Backdrop Website updates

- [x] beta.backdropcms.org -- if not done with preview @bugfolder 
- [x] docs.backdropcms.org  @jenlampton 
- [x] events.backdropcms.org @jenlampton

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Publicity tasks

- [ ] Send a newsletter to subscribers (assign to @bwpanda / stpaultim / jenlampton)
- [x] Add a notification to the dashboard @stpaultim 

### Backdrop Website updates

- [ ] backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] forum.backdropcms.org @jenlampton (or bwpanda / bugfolder)

See Also
---------
* [1.22.3 Release Checklist](https://github.com/backdrop/backdrop-issues/issues/5782)
* [1.23.0-preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/5757)

**Comment by herbdool** [comment]
I can probably do Composer and Pantheon tomorrow morning

**Comment by quicksketch** [comment]
Tag is cut for release: https://github.com/backdrop/backdrop/releases/tag/1.23.0

**Comment by jenlampton** [comment]
## Draft release notes:

The Backdrop community is proud to release version 1.23.0 of Backdrop CMS, following our 4-month release cycle.

**Notes for updating**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- **It will be necessary to run the update script** (located at /update.php) for this release.
- This release includes an API Change. While we try hard to maintain compatibility as much as possible between releases, this change was needed to facilitate the inclusion of Entity Reference module in core. Please see the change record [File::uri() Now Returns Path to File Entity Page, Not the File Path](https://docs.backdropcms.org/change-records/file-uri-now-returns-path-to-file-entity-page-not-the-file-path) for more information.

**Changes since version 1.22.3 are listed below.**

## New features

- Added: entity reference module in core. [#1301](https://github.com/backdrop/backdrop-issues/issues/1301)
- Added: Setting to allow the comment title to be hidden. [#4569](https://github.com/backdrop/backdrop-issues/issues/4569)
- Added new Date field widget to utilize HTML5 #date input type. [#4255](https://github.com/backdrop/backdrop-issues/issues/4255)
- Added a "Taxonomy term: Depth" Visibility condition for blocks and layouts. [#2955](https://github.com/backdrop/backdrop-issues/issues/2955)

## API Changes

- Fixed: File::uri() is not consistent with other Entity types. [#2300](https://github.com/backdrop/backdrop-issues/issues/2300)

## API Enhancements

- Allow forms to set custom validation error messages on required fields [#5348](https://github.com/backdrop/backdrop-issues/issues/5348)
- Added config->getData() to match config->setData(). [#3902](https://github.com/backdrop/backdrop-issues/issues/3902)
- Add a 'bundle cache' property to support enabling/disabling entity caching on a per-bundle basis. [#5632](https://github.com/backdrop/backdrop-issues/issues/5632)

## Documentation updates

-ytgh Include the `NOT` operator in documentation for `backdrop_process_states()`. [#4228](https://github.com/backdrop/backdrop-issues/issues/4228)

## User Experience Improvements

- Added vertical tabs to clean up the user account edit form. [#3872](https://github.com/backdrop/backdrop-issues/issues/3872)
- Fixed: Don't convert fieldset to vertical tab if there is only one in the group. [#5747](https://github.com/backdrop/backdrop-issues/issues/5747)

## Miscellaneous changes

- Fixed: Standardize on the spelling of "email" across all interfaces. [#4521](https://github.com/backdrop/backdrop-issues/issues/4521)
- Fixed: Remove blank lines before `@file` docblocks. [#4824](https://github.com/backdrop/backdrop-issues/issues/4824)

## Bug fixes

- Fixed: `testCommentInterface()` tests broken due to typo in recent commit. [#5764](https://github.com/backdrop/backdrop-issues/issues/5764)
- Fixed: Include some cross-ports from the Entity reference contrib module. [#5665](https://github.com/backdrop/backdrop-issues/issues/5665)
- Fixed: Remove the dependency on specific system module version from entityreference module. [#5734](https://github.com/backdrop/backdrop-issues/issues/5734)

**Comment by herbdool** [comment]
Oops someone removed Pantheon from the list. I've added it back. Does someone else want to do Platform?

**Comment by olafgrabienski** [comment]
I've just created a new language template file for the translation server.

**Comment by Wylbur** [comment]
@herbdool I could also do Pantheon if you want.  I could also do Platform.sh. 

Are you available tomorrow during Office Hours and we could run through that together the first time?  I assume there is some documentation too.

**Comment by Wylbur** [comment]
@herbdool I went ahead and tried the Platform.sh update, and have created a issue and pull request.  Will update this when I have feedback/success.

**Comment by herbdool** [comment]
@Wylbur awesome! Note that it can take them quite a while to merge those PRs. Luckily it doesn't prevent folks from updating their own site.

**Comment by Wylbur** [comment]
> @herbdool I went ahead and tried the Platform.sh update, and have created a issue and pull request. Will update this when I have feedback/success. [platformsh/template-builder#668](https://github.com/platformsh/template-builder/issues/668) [platformsh/template-builder#669](https://github.com/platformsh/template-builder/pull/669)

Updates are complete.
