### ISSUE TITLE
Backdrop 1.23.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5873]
Release scheduled for Dec 2nd, 2022 1pm - 4pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Update the front page download link on b.org @stpaultim 
- [x] Tweet that a new release is out @stpaultim 
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [ ] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @wylbur
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @wylbur
- [x] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) @wylbur
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [ ] backdropcms.org @jenlampton
- [ ] beta.backdropcms.org @jenlampton
- [ ] docs.backdropcms.org @jenlampton 
- [ ] events.backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton

**Comment by jenlampton** [comment]
Release notes:
---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**
* **It will be necessary to run the update script** (located at /core/update.php) for this release.
* - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**Changes since version 1.xx.x** are listed below.

## Bug fixes

- Fixed: Views query/distinct settings issues when setting "This page (override)" in PHP8. [#5854](https://github.com/backdrop/backdrop-issues/issues/5854)
- Fixed: Exports of flexible templates throw PHP 8 error when System language is not English. [#5853](https://github.com/backdrop/backdrop-issues/issues/5853)
- Fixed: `node_cron_last` state is stored as a string. Similar dates are stored as integer. [#5849](https://github.com/backdrop/backdrop-issues/issues/5849)
- Fixed: HTML5 date field widget produces a fatal error on a Paragraph. [#5847](https://github.com/backdrop/backdrop-issues/issues/5847)
- Fixed: Files lose permanent status when in edited in CKEditor link dialog. [#5843](https://github.com/backdrop/backdrop-issues/issues/5843)
- Fixed: misspelling of dialog's "resizable" JS setting option in `system_token_output()`. [#5842](https://github.com/backdrop/backdrop-issues/issues/5842)
- Fixed: Token browser disappears below viewport when resized. [#5841](https://github.com/backdrop/backdrop-issues/issues/5841)
- Fixed: Existing Image library popup does not show all images. [#5835](https://github.com/backdrop/backdrop-issues/issues/5835)
- Fixed: Deprecated function: `preg_replace()`: Passing null to parameter #3.  [#58[32](https://github.com/backdrop/backdrop-issues/actions/runs/3605900272/jobs/6076716041#step:4:33)](https://github.com/backdrop/backdrop-issues/issues/5832)
- Fixed: Upgrade from Drupal 7 should respect UTF8-MB4 variable. [#5818](https://github.com/backdrop/backdrop-issues/issues/5818)
- Fixed: Layouts and Taxonomy Term view context conflict. [#5809](https://github.com/backdrop/backdrop-issues/issues/5809)
- Fixed: Preview of menu machine name is inaccurate while adding a menu. [#5807](https://github.com/backdrop/backdrop-issues/issues/5807)
- Fixed: Table alias missing in query condition in `taxonomy_select_nodes()`. [#5806](https://github.com/backdrop/backdrop-issues/issues/5806)
- Fixed: Method `DatabaseCondition::__toString()` must return a string value. [#5805](https://github.com/backdrop/backdrop-issues/issues/5805)
- Fixed: Some tests throw stat failed exceptions. [#5799](https://github.com/backdrop/backdrop-issues/issues/5799)
- GitHub Actions: Apache setup failure in the php 5.6 runners. [#5790](https://github.com/backdrop/backdrop-issues/issues/5790)
- Fixed: File Access Checks Fail if no Type is defined. [#5777](https://github.com/backdrop/backdrop-issues/issues/5777)
- Fixed: Forms `user_register_form` and `user_pass` hard-code the page title. [#5731](https://github.com/backdrop/backdrop-issues/issues/5731)
- Fixed: `node_type_delete()` doesn't check the value returned from `node_type_get_type()`. [#5726](https://github.com/backdrop/backdrop-issues/issues/5726)
- Fixed: `_views_tokenized_clean_css_identifier()` should clean the complete class. [#5561](https://github.com/backdrop/backdrop-issues/issues/5561)
- Fixed: Possible Drupal 7 upgrade regression caused by `user/1` path alias update hook. [#5497](https://github.com/backdrop/backdrop-issues/issues/5497)
- Fixed: Language field can't be moved around reliably (terms). [#5060](https://github.com/backdrop/backdrop-issues/issues/5060)

## User Experience Improvements

- Improve field block labels when copying the Layout title from a block. [#5704](https://github.com/backdrop/backdrop-issues/issues/5704)
- Added "Flush all caches > Views" to admin bar. [#5737](https://github.com/backdrop/backdrop-issues/issues/5737)
- Add welcome message to help people find the Dashboard. [#5624](https://github.com/backdrop/backdrop-issues/issues/5624)
- File Type configuration form improvements. [#4014](https://github.com/backdrop/backdrop-issues/issues/4014)

## Documentation updates

- Update all documentation URLs in core. [#5706](https://github.com/backdrop/backdrop-issues/issues/5706)
- Fixed minor spelling mistake in views plugins documentation. [#5772](https://github.com/backdrop/backdrop-issues/issues/5772)
- Remove `$settings` from docblock for `hook_block_view_MODULE_DELTA_alter()`. [#5827](https://github.com/backdrop/backdrop-issues/issues/5827)
- Remove the reference to the files property from` image.inc` documentation. [#5717](https://github.com/backdrop/backdrop-issues/issues/5717)

## Miscellaneous changes

- Remove the messages about the GD toolkit being installed or the missing GD extension from `image_gd_settings()`. [#5723](https://github.com/backdrop/backdrop-issues/issues/5723)
- Place all term tokens together in `taxonomy_token_info()`. [#5709](https://github.com/backdrop/backdrop-issues/issues/5709)

**Comment by quicksketch** [comment]
Looks good to me @jenlampton. Ready to publish!

**Comment by stpaultim** [comment]
Yes, looks good to me as well.

**Comment by jenlampton** [comment]
> Ready to publish!

I guess that means there is a tag somewhere? going to have a look-see...

**Comment by jenlampton** [comment]
okay - release is out! https://github.com/backdrop/backdrop/releases/tag/1.23.1

**Comment by Wylbur** [comment]
Pull request has been created at docker-library/official-images
https://github.com/docker-library/official-images/pull/13684

**Comment by BWPanda** [comment]
Can we close this now?
