### ISSUE TITLE
Backdrop 1.24.0-preview Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5908]
Scheduled for January 3rd, 2023 4pm - 6pm PT

## Pre-release tasks

- [x] If this is the Jan 1 pre-release, then make sure to update the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file. @quicksketch
- [x] Merge commits @quicksketch
- [x] Create a new minor release milestone @jenlampton 
- [x] Move all unfinished issues to the next minor release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [ ] Review issues for new features @jenlampton 
  - [ ] Add a conclusion suitable for blog post + release notes
  - [x] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [x] Add `Needs change record` label if the the issue contains an API change.
  - [x] Add `Needs translation` label if the the issue contains string translations.
- [ ] Draft blog post for release on the 15th @klonos / @stpaultim ??
- [ ] Draft roadmap updates for backdropcms.org @klonos 
- [x] Update list of modules included in backdrop core @klonos 
- [ ] Update list of modules included in backdrop_upgrade_status module @jenlampton
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (e.g. `1.10.0-preview`) @quicksketch
- [x] Tag for release, and push tag to GitHub @quicksketch
      * Note: New incremented branch for development is usually created on release day
- [x] Revert version number back on 1.x branch with the same minor number (e.g. `1.10.x-dev`) @quicksketch
- [x] Create release notes on GitHub **Important: Check "This is a pre-release" checkbox when creating release** @jenlampton 

## Website updates
- [ ] beta.backdropcms.org @bugfolder ??

## Post-release Publicity + documentation tasks

- [ ] Tweet that a preview release is out @stpaultim 
- [ ] Publish roadmap updates for backdropcms.org @klonos 

See Also
---------
* [Minor Release Checklist]()

**Comment by quicksketch** [comment]
All commits are in for `1.24.0-preview` and we're ready to make the release.

**Comment by jenlampton** [comment]
Release notes draft:

---

This is the preview release of Backdrop 1.24.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January 15th, 2023.

**Notes for updating**
  - **It will be necessary to run the update script** (located at /core/update.php) for this release.
  - No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**Changes since version 1.23.1** are listed below.
TBD

**Comment by klonos** [comment]
@jenlampton we did have changes in .htaccess: #5906

**Comment by quicksketch** [comment]
The tag is cut at https://github.com/backdrop/backdrop/releases/tag/1.24.0-preview. Be sure to mark pre-release when making the release!

**Comment by jenlampton** [comment]
Thank you @klonos and @quicksketch!

**Comment by quicksketch** [comment]
Final release checklist: https://github.com/backdrop/backdrop-issues/issues/5939
