### ISSUE TITLE
Backdrop 1.23.2 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5938]
Release scheduled for January 15, 2023 2pm - 6pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (assign to klonos / jenlampton / stpaultim )
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)

## See Also

- [Checklist for 1.24.0 release](https://github.com/backdrop/backdrop-issues/issues/5939)

**Comment by quicksketch** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

* The `.htaccess` files have been modified to include support for PHP 8. This includes the .htaccess files in the project root, in the files directory, and the private files directory. (See #5906)
* No changes have been made to the robots.txt or default settings.php files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

## Bug fixes

- PHP 8: Fix .htaccess PHP overrides [#5906](https://github.com/backdrop/backdrop-issues/issues/5906)
- PHP 8: Fix Deprecated function: mb_strlen(): Passing null to parameter 1 ($string) of type string is deprecated in mb_strlen() (line 479 of ../unicode.inc) [#5890](https://github.com/backdrop/backdrop-issues/issues/5890)
- PHP 8.1: Fix Deprecated function: `preg_replace()`: Passing null to parameter 3 in `system_requirements()` [#5925](https://github.com/backdrop/backdrop-issues/issues/5925)
- PHP 8.1: Fix backdrop_is_cli() detection [#5872](https://github.com/backdrop/backdrop-issues/issues/5872)
- Fix Notice: Undefined index: position in views_plugin_display_block->options_form() (line 296 of ../views_plugin_display_block.inc).  [#5882](https://github.com/backdrop/backdrop-issues/issues/5882)
- Fix multiple image browsers in CKEditor's insert image functionality [#5867](https://github.com/backdrop/backdrop-issues/issues/5867)
- Fix typo in Redirect module: it's "update", not "upadte" [#5826](https://github.com/backdrop/backdrop-issues/issues/5826)
- Fix Creation of table `backdrop_install_test` fails upon installation without a pre-created database  [#5817](https://github.com/backdrop/backdrop-issues/issues/5817)
- Fix creation of database during installation fails [#5816](https://github.com/backdrop/backdrop-issues/issues/5816)
- Fix Simpletest semi-silently ignoring wrong file paths in .tests.info file [#5491](https://github.com/backdrop/backdrop-issues/issues/5491)

## Miscellaneous changes

- User edit/create form: render the "Account settings" fieldset as non-collapsible if it is the only one [#5783](https://github.com/backdrop/backdrop-issues/issues/5783)
- Add Requirements check for `max_input_vars` to status report [#5771](https://github.com/backdrop/backdrop-issues/issues/5771)
- Link to the Layouts admin page from the Custom blocks admin page. [#1360](https://github.com/backdrop/backdrop-issues/issues/1360)
- Switch pull request sandboxes to PHP 8.1 [#5926](https://github.com/backdrop/backdrop-issues/issues/5926)
- Fix indentation in `layout_list_page()` in layout.admin.inc [#5888](https://github.com/backdrop/backdrop-issues/issues/5888)
- Switch to Checkout V3 in GitHub Actions to prevent node.js nagging [#5880](https://github.com/backdrop/backdrop-issues/issues/5880)
- Switch to using `random_bytes()` where available (built into php7) [#5813](https://github.com/backdrop/backdrop-issues/issues/5813)

**Comment by quicksketch** [comment]
Release for 1.23.2 is out at https://github.com/backdrop/backdrop/releases/tag/1.23.2

1.24.0 still to be released. See https://github.com/backdrop/backdrop-issues/issues/5939
