### ISSUE TITLE
Backdrop 1.24.0 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5939]
Scheduled for January 15, 2023 2pm - 6pm PT

## Pre-release tasks

- [x] If this is the Jan 15 release, ensure that the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file has been updated to reflect the new/current year.
- [x] Merge minor release commits (@quicksketch)
- [x] Move all unfinished issues to the next bug-fix release milestone (@jenlampton)
- [x] Review all closed issues in milestone:  (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone  (@jenlampton)
- [x] Draft Release notes  (@jenlampton)
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issues in the milestone
    - [ ] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub (@quicksketch)
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@jenlampton)
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Create a new language template file for the translation server @olafgrabienski 

### Publicity tasks

- [ ] Tweet that a new release is out @stpaultim 
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [ ] Publish blog post @cellear @stpaultim 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [ ] Update the roadmap page on b.org @klonos 
- [x] Update list of modules included in backdrop core @jenlampton
- [ ] Update list of modules included in backdrop_upgrade_status module @jenlampton 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systemshttps://en.wikipedia.org/wiki/List_of_content_management_systems

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @laryn 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool
- [x] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) @wylbur

### Backdrop Website updates

- [ ] beta.backdropcms.org -- if not done with preview @bugfolder 
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Publicity tasks

- [ ] Add a notification to the dashboard @stpaultim 
- [ ] Send a newsletter to subscribers @stpaultim 

### Backdrop Website updates

- [ ] backdropcms.org @jenlampton 
- [ ] forum.backdropcms.org @jenlampton 

See Also
---------
* [1.23.2 Release Checklist](https://github.com/backdrop/backdrop-issues/issues/5938)
* [1.24.0-Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/5908)

**Comment by jenlampton** [comment]
Release notes draft:

---

This is the preview release of Backdrop 1.24.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January 15th, 2023.

## Notes for updating

- The `.htaccess` file has been modified to include settings for PHP 8. (See #5906)
- No changes have been made to the `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
-  **It will be necessary to run the update script** (located at /core/update.php) for this release.

**Changes since version 1.23.1** are listed below.**

## New features

- Add a views field handler for project properties from the database. [#5820](https://github.com/backdrop/backdrop-issues/issues/5820)
- Add descriptions for user roles. [#5748](https://github.com/backdrop/backdrop-issues/issues/5748)
- Add a configuration option for database log message length. [#5553](https://github.com/backdrop/backdrop-issues/issues/5553)
- Make File::access consistent with other entity classes. [#5480](https://github.com/backdrop/backdrop-issues/issues/5480)
- Add "Rebuild search index" process to replace "Invalidate search index". [#4182](https://github.com/backdrop/backdrop-issues/issues/4182)
- Add a "Back to site" button into the Admin Bar. [#2709](https://github.com/backdrop/backdrop-issues/issues/2709)
- Add an instant search filter to the permissions page. [#980](https://github.com/backdrop/backdrop-issues/issues/980)

## Bug fixes

- Instant search filter for the permissions page doesn't reset on role-specific pages [#5909](https://github.com/backdrop/backdrop-issues/issues/5909)

**Comment by quicksketch** [comment]
@jenlampton Could you copy the `.htaccess` update notice from the [1.23.2 release](https://github.com/backdrop/backdrop/releases/tag/1.23.2)? This update is unusual in that it affects 3 `.htaccess` files, not just the one in the root.

> This is the preview release of Backdrop 1.24.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January 15th, 2023.

This description should be updated for an official release.

I think the "Bug Fix" can be removed from the release notes, since the bug only existed in a non-released version.

**Comment by jenlampton** [comment]
done, done and done.

**Comment by quicksketch** [comment]
Tag is cut: https://github.com/backdrop/backdrop/releases/tag/1.24.0

**Comment by jenlampton** [comment]
Release is out: https://github.com/backdrop/backdrop/releases/tag/1.24.0
And I updated the docs site to 1.24.0 just to make sure it wouldn't explode.

**Comment by laryn** [comment]
Pantheon is updated.

**Comment by olafgrabienski** [comment]
I've just created the new language template file for https://localize.backdropcms.org.

> - [ ] Create a new language template file for the translation server

^^ Can someone untick the bullet in the issue description for me? I don't seem to have the permissions.

**Comment by klonos** [comment]
I've updated the Tugboat demo base images 👍🏼

**Comment by BWPanda** [comment]
How long do we leave this issue open?
