### ISSUE TITLE
[UX][META] Redesign the "Search settings" form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5979]
This form is very lengthy and there's many set-and-forget settings that could be "hidden" inside collapsed fieldsets, which would simplify it. Here's what the form currently looks like vs. where I would like us to eventually get to:
![image](https://user-images.githubusercontent.com/2423362/218952207-19865373-4920-4d43-88db-67f2cc527acf.png)

Proposed changes:
- [ ] #3385 | "Search items" fieldset: instead of having a dual checkboxes/radios set of options for the available items and which one is the default (which can get very lengthy as more search items are added), we should implement the same UI as in the `admin/config/regional/language` page for enabled/default language.
- [ ] ??? | "Log all searches" checkbox: move at the bottom of the form (before the submit button), and lose the wrapping fieldset. This setting is rarely used, and only when debugging; otherwise it simply receives way too much unnecessary prominence as it is currently.
- [ ] ??? | "Content settings" fieldset: wrap the "Content rankings" section in a fieldset, and have it collapsed by default. This is another set of settings that will not be updated very frequently once search settings have been tweaked for the site. A default value is provided for the influence setting of each factor anyway, which will work just fine form most simple sites.
- [ ] #5975 | "Indexing" fieldset:
  - provide a progress bar for the current index status
  - move the cron settings and various other indexing settings into collapsed-by-default fieldsets.

**Comment by klonos** [comment]
...an alternative/additional idea is to move the indexing status and "Rebuild search index" section into a separate form.

**Comment by klonos** [comment]
Here's what the same form looks like in D10 (for comparison/inspiration/ideas):
![image](https://user-images.githubusercontent.com/2423362/219005216-c7f6739a-6238-4ba7-b3e4-f533390baeae.png)

## Indexing status fieldset
- This has been moved to the top of the form. I guess that makes sense, since reindexing the site and seeking status must be the most common, potentially on-going task once the search settings have been tweaked for a site.
- The fieldset has been renamed to "Indexing progress". I personally like it equally the same as "Indexing status".
- The help text in that fieldset reads as follows:
  > Only items in the index will appear in search results. To build and maintain the index, a correctly configured [cron maintenance task]() is required.
  - The link points to `admin/config/system/cron` instead of the site status page - something that I have already implemented in the PoC PR for #5975 (along with proper access checks - there were none before).
  - In the PR for #5975, I have used this text:
    > The search index is being systematically updated during cron runs. Searching will continue to work, but unindexed content will be missing from the search results. You can manually trigger the indexing of remaining items below.

## Cron settings
- In the PR for #5975 I have already moved that setting to a separate fieldset called "Cron indexing settings" (which I am now proposing to keep collapsed by default). The main reasoning behind it was to distinguish cron-based reindexing from the manual reindexing (which I also moved to a separate fieldset).
- In D10 they have renamed this fieldset to "Indexing throttle", but I believe that we should be including the word "cron" in the fieldset label, as otherwise it might be mistaken for a throttle that applies to the batch for the manual reindexing (although separate fieldsets help distinguish those).

## General indexing settings
(word length, simple CJK handling, and transliteration)
- The fieldset that holds these settings in D10 is called "Default indexing settings", whereas in #5975 I have called it "Indexing settings". I think that the addition of the word "default" helps in D10, because in D10 there is the notion of other search pages and search page types - this does not apply to Backdrop.
- D10 includes the help text "The default settings should be appropriate for the majority of sites.", which I find helpful for D10, but not applicable in Backdrop (same reason as in the bullet point above).

## Logging checkbox
- This has been moved towards the bottom of the page in D10. I have done the same in the PR for #5975 with the difference that:
  - I have moved it to the very bottom of the form.
  - I have removed the fieldset around it, since I found it to be giving this rarely used option unnecessary prominence.

**Comment by klonos** [comment]
...in D10 the respective "Content settings" fieldset (provided by the Node module) and the settings for it have been moved to a separate form, which is tied to the "Content" search page (type):
<img src="https://user-images.githubusercontent.com/2423362/219013524-696c6acc-59f7-4dbe-bed8-d7c172b5b503.png" width=50%>

I find this to be a much bigger change, so if we think that the way it's done in D10 is better, then there's much more/deeper refactoring to be done in the internals of the search module, rather than just tweaks in the configuration form (so a separate issue would be in order I believe).
