### ISSUE TITLE
[META] The great coding standards restoration

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#6004]
Now that we run `phpcs` against all core PRs, we should fix all existing coding issues in core to avoid getting so many warnings/errors. This issue (inspired by https://github.com/backdrop/backdrop-issues/issues/3213) will list all files/modules/etc. in core and will have PRs against groups of them to make reviewing easier.

## By directory

- [x] `core/includes/a*`: https://github.com/backdrop/backdrop/pull/4369
- [ ] `core/includes/b*`: https://github.com/backdrop/backdrop/pull/4370
- [ ] `core/includes/c*`
- [x] `core/includes/database/*`: https://github.com/backdrop/backdrop/pull/4915
- [ ] `core/includes/d*`
- [ ] `core/includes/e*`
- [ ] `core/includes/f*`
- [ ] `core/includes/[g-i]*`
- [ ] `core/includes/[l-m]*`
- [ ] `core/includes/p*`
- [ ] `core/includes/[s-t]*`
- [ ] `core/includes/transliteration*`
- [ ] `core/includes/u*`
- [ ] `core/modules/admin_bar`
- [ ] `core/modules/block`
- [ ] `core/modules/book`
- [ ] `core/modules/ckeditor`
- [ ] `core/modules/color`
- [ ] `core/modules/comment`
- [ ] `core/modules/comment/views`
- [ ] `core/modules/config`
- [ ] `core/modules/contact`
- [ ] `core/modules/contextual`
- [ ] `core/modules/dashboard`
- [ ] `core/modules/date`
- [ ] `core/modules/date/views`
- [ ] `core/modules/[dblog,email]`
- [ ] `core/modules/entity`
- [ ] `core/modules/entityreference`
- [ ] `core/modules/field_ui`
- [ ] `core/modules/field`
- [ ] `core/modules/field/modules`
- [ ] `core/modules/field/[tests,views]`
- [ ] `core/modules/file`
- [ ] `core/modules/file/views`
- [ ] `core/modules/filter`
- [ ] `core/modules/image`
- [ ] `core/modules/installer`
- [ ] `core/modules/language`
- [ ] `core/modules/layout`
- [ ] `core/modules/layout/includes`
- [ ] `core/modules/layout/plugins`
- [ ] `core/modules/layout/[templates,tests]`
- [ ] `core/modules/link`
- [ ] `core/modules/locale`
- [ ] `core/modules/local/views`
- [ ] `core/modules/menu`
- [ ] `core/modules/node`
- [ ] `core/modules/node/views`
- [ ] `core/modules/path`
- [ ] `core/modules/redirect`
- [ ] `core/modules/search`
- [ ] `core/modules/search/[templates,tests,views]`
- [ ] `core/modules/simpletest`
- [ ] `core/modules/simpletest/tests/[a-b]*`
- [ ] `core/modules/simpletest/tests/c*`
- [ ] `core/modules/simpletest/tests/d*`
- [ ] `core/modules/simpletest/tests/[e-f]*`
- [ ] `core/modules/simpletest/tests/[g-m]*`
- [ ] `core/modules/simpletest/tests/[n-s]*`
- [ ] `core/modules/simpletest/tests/t*`
- [ ] `core/modules/simpletest/tests/u*`
- [ ] `core/modules/syslog`
- [ ] `core/modules/system`
- [ ] `core/modules/system.system.[a-m]*`
- [ ] `core/modules/system.system.[n-z]*`
- [ ] `core/modules/taxonomy`
- [ ] `core/modules/taxonomy/views`
- [ ] `core/modules/telemetry`
- [ ] `core/modules/translation`
- [ ] `core/modules/update`
- [ ] `core/modules/user`
- [ ] `core/modules/user/tests`
- [ ] `core/modules/user/views`
- [ ] `core/modules/views_ui`
- [ ] `core/modules/views`
- [ ] `core/modules/views/handlers/views_handler_a*`
- [ ] `core/modules/views/handlers/views_handler_field*`
- [ ] `core/modules/views/handlers/views_handler_filter*`
- [ ] `core/modules/views/handlers/views_handler_[r-s]*`
- [ ] `core/modules/views/includes`
- [ ] `core/modules/views/plugins/views_plugin_a*`
- [ ] `core/modules/views/plugins/views_plugin_[c-d]*`
- [ ] `core/modules/views/plugins/views_plugin_[e-q]*`
- [ ] `core/modules/views/plugins/views_plugin_[r-s]*`
- [ ] `core/modules/views/templates`
- [ ] `core/modules/views/tests`
- [ ] `core/modules/views/tests/[handlers,plugins,styles]`
- [ ] `core/profiles`
- [ ] `core/themes`
- [ ] `[misc.]`

## By topic

- [ ] SimpleTest method scope https://github.com/backdrop/backdrop/pull/4962
- [x] CSpell https://github.com/backdrop/backdrop-issues/issues/6302

Anyone wanting to make a PR should:
- Setup their local with `phpcs` installed and Backdrop's [Coding Standards](https://github.com/backdrop-ops/phpcs/) repo one directory above Backdrop core (I personally use Lando)
- Run `phpcs` from Backdrop's root directory like so: `phpcs --basepath=. --standard=../phpcs/Backdrop core/includes/a*` (change the last bit to match whatever group of files you're targeting)
- Create their PR with the following description: `For https://github.com/backdrop/backdrop-issues/issues/6004` (avoiding any keywords that automatically link the PR to this issue and therefore result in closing this issue when the PR is merged)
- Edit this issue to add a link to your PR next to the appropriate item above

**Comment by BWPanda** [comment]
One down, a zillion to go!

**Comment by argiepiano** [comment]
This is solved by adding a visibility qualifier in the method declaration such as public, protected or private.

**Comment by bugfolder** [comment]
If the function was previously implicitly `public`, then it would seem that when visibility is made explicit, it should also be `public` in the interest of backward compatibility.

Some functions might warrant a change in visibility to `private` or `protected`, but since that would have B/C implications, it should be raised in a separate issue to discuss the implications, and shouldn't be a blocker for this issue.

**Comment by quicksketch** [comment]
I took a stab at cleaning up the `core/includes/database` directory, since the database system is both one of the most complicated and difficult systems in Backdrop, and also the more poorly documented. Big swaths of functions don't include docblocks. I did not get `phpcs` passing 100%, since adding `array` type hints to parent classes and interfaces can break child classes. I also avoided a few places where conforming to code style might result in different behavior. Still, it's hundreds of code style corrections.

See https://github.com/backdrop/backdrop/pull/4915

**Comment by indigoxela** [comment]
Although it looked like a huge task, https://github.com/backdrop/backdrop/pull/4915 seems to move fast. Some more "but this can also be null" comments :wink:, but I'm done now with review. (And phpcs found some indentation issues.)

**Comment by indigoxela** [comment]
Tentatively marking https://github.com/backdrop/backdrop/pull/4915 as RTBC - phpcs checks pass. There are still some open comments re method removal/addition, but consensus seems to be, that these changes are harmless.

@quicksketch many thanks for sacrificing your weekend to improve the database abstraction layer documentation. :+1:

**Comment by quicksketch** [comment]
Thank you @indigoxela! I think the changes are low-risk. I merged into 1.x and cherry-picked into 1.29.x, so https://github.com/backdrop/backdrop/pull/4915 changes will be in 1.29.3

**Comment by quicksketch** [comment]
One of the most frequent PHPCS issues we get is scoping on SimpleTest methods, and that frequently confuses contributors who don't know whether tests should be public/protected/private. I tackled specifically that issue with a find/replace, updating 1883 methods (gulp) that did not have scoping on them.

PR ready for review at https://github.com/backdrop/backdrop/pull/4962.

**Comment by quicksketch** [comment]
>  They do not look like they can be combined. Is one preferred over the other?

They're total alternatives to each other, only one could be used. I think https://github.com/backdrop/backdrop/pull/4963 might be the more technically correct solution, but it might not be backwards-compatible. We need to do some testing to see if it would break any other tests (such as those in contrib). If that's the case, then we'd need to go with https://github.com/backdrop/backdrop/pull/4962, since an unspecified method like `function foo()` is considered the same as `public function foo()`.

**Comment by herbdool** [comment]
I've got a PR for `core/includes/a*` to replace the previous one where the original repo was deleted: https://github.com/backdrop/backdrop/pull/5167.

For some reason I cannot update the original issue body text. I have permission to do this for any other issue in core, but not this one.

**Comment by herbdool** [comment]
PR for `core/includes/b*`: https://github.com/backdrop/backdrop/pull/5168. Replaces: https://github.com/backdrop/backdrop/pull/4370

**Comment by quicksketch** [comment]
Merged core/includes/a* https://github.com/backdrop/backdrop/pull/5167 into 1.x and 1.32.x. Thanks @herbdool!

**Comment by quicksketch** [comment]
> For some reason I cannot update the original issue body text. I have permission to do this for any other issue in core, but not this one.

Strange, I cannot either. Maybe this is some kind of safety thing for deleted accounts? @BWPanda opened this issue. I can still check boxes off, I just can't edit the summary.

**Comment by indigoxela** [comment]
Hey @quicksketch and @herbdool can we please pause here and try to get https://github.com/backdrop/backdrop-issues/issues/7008 in first? 🥺 

The latest commit (besides causing a conflict) introduced yet another "deprecated" nagging.
I belief, getting full PHP 8.5 support is more urgent than coding standards. And with PHP 8.5 we'd immediately see such problems in functional test runs.

**Comment by quicksketch** [comment]
Ofcourse @indigoxela! Good call!

**Comment by herbdool** [comment]
This PR for `core/includes/c*` can wait, though I've confirmed it doesn't currently touch any of the files currently in the PHP 8.5 support PR: https://github.com/backdrop/backdrop/pull/5170.

**Comment by indigoxela** [comment]
> I've confirmed it doesn't currently touch any of the files currently in the PHP 8.5 support PR...

What triggered my comment here was, that the previous merge introduced another "deprecated implicit null" problem that wasn't there before. Not so much the merge conflict, which was trivial. However, the merge conflict was about a doc block I set correctly in my PR, but was misleading in the merged PR here. 😉

Please don't get me wrong, I'm really excited about the activity here. But let's try to not cause additional work elsewhere. 😆

**Comment by indigoxela** [comment]
Looking at https://github.com/backdrop/backdrop/pull/5168 (core/includes/b*)

Locally, after applying the patch I still get:

```
FILE: core/includes/bootstrap.inc
------------------------------------------------------------------------------
FOUND 5 ERRORS AND 11 WARNINGS AFFECTING 16 LINES
------------------------------------------------------------------------------
  454 | WARNING | [ ] Type hint "array" missing for $data
  871 | WARNING | [x] There must be no blank line following an inline comment
  946 | ERROR   | [x] Expected 1 space(s) after FOREACH keyword; 0 found
 1201 | WARNING | [ ] Function variable_initialize() has been deprecated
 1470 | WARNING | [ ] Line exceeds 80 characters; contains 87 characters
 1788 | WARNING | [ ] Missing parameter comment
 1810 | WARNING | [ ] Missing parameter comment
 2543 | ERROR   | [x] Parameter comment must end with a full stop
 2831 | WARNING | [ ] Missing parameter comment
 2837 | WARNING | [ ] Type hint "array" missing for $arrays
 3040 | ERROR   | [x] Newline required after opening brace
 3366 | WARNING | [ ] Line exceeds 80 characters; contains 90 characters
 3367 | WARNING | [ ] Function variable_initialize() has been deprecated
 3533 | WARNING | [ ] Missing parameter comment
 3843 | ERROR   | [x] Newline required after opening brace
 4537 | ERROR   | [x] Newline required after opening brace
------------------------------------------------------------------------------
PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------
```
So this PR seems incomplete and needs work. (Note that our phpcs action won't nag on anything not changed in the current PR.)

But another question comes to my mind: what exactly is the attempt here? Because fixing doc blocks, comments and indent is a (relatively) harmless task, but adding type hints in actual function params has a potential for disruptive changes for contrib/custom code. Especially in central files like bootstrap.inc.

The changes in the b* PR go beyond what our (defined) coding standards currently require - by adding type hints for string and int. Should our coding standard change?
Example: core/includes/backup.inc *passes* without any changes - with our current ruleset.

**Comment by indigoxela** [comment]
Looking at https://github.com/backdrop/backdrop/pull/5170 (core/includes/c*).

Still lots of failures when running phpcs, too many to post here. So that one also seems incomplete, if the task here is to comply with our own standard.

**Comment by herbdool** [comment]
@indigoxela looks like running phpcs locally produces different errors compared to here. I'll look at it later. 

According to https://docs.backdropcms.org/php-standards#type-hinting, type hinting should be used wherever possible. It mentions not doing it for int and string to maintain BC for PHP < 7. But since the minimum version is now greater than 7.0 we might want to update that text. 

I think we include those type hints unless we believe it will cause failures in contrib. That's the intent of the docs in my opinion but let's see what @quicksketch thinks too.

**Comment by indigoxela** [comment]
> looks like running phpcs locally produces different errors compared to here.

It doesn't. Just make sure you have the right ruleset in lastest version: https://github.com/backdrop-ops/phpcs (tag 1.2.0)

The result is from my local, using the latest ruleset.

> But since the minimum version is now greater than 7.0 we might want to update that text.

If we do that, we should also update the ruleset accordingly - that's why I asked. But we have to be extremely careful in that case, as newly added type hints do have a potential for breaking changes. And the hints must be 100% correct, which makes review a lot harder.

> That's the intent of the docs in my opinion

I don't agree on that. The initial purpose of this issue (opened back in 2023) was to prevent all those warnings in PR action runs - but we fixed that problem differently in the meantime. By a custom action, which doesn't nag on unrelated code.

I do agree that we should fix doc blocks. To make developer life easier. But they must be correct. A wrong doc block isn't any better than no doc block (param and return) hints at all.

**Comment by indigoxela** [comment]
Note that includes/a* (PR already merged) still show some errors:

```
phpcs core/includes/a*

FILE: core/includes/ajax.inc
-------------------------------------------------------------------------------
FOUND 1 ERROR AND 4 WARNINGS AFFECTING 5 LINES
-------------------------------------------------------------------------------
  717 | ERROR   | [x] Parameter comment must end with a full stop
 1029 | WARNING | [ ] Expected type hint "array"; found "?array" for $settings
 1062 | WARNING | [ ] Expected type hint "array"; found "?array" for $settings
 1095 | WARNING | [ ] Expected type hint "array"; found "?array" for $settings
 1128 | WARNING | [ ] Expected type hint "array"; found "?array" for $settings
-------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
-------------------------------------------------------------------------------
```
That's because the type hint and the doc block differ. The doc block states `@param array $settings`, but the type hint indicates that it should have been `array|null`.

**Comment by indigoxela** [comment]
A quick thought, why your local results seem to differ @herbdool: our action uses the [latest version of phpcs](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases) and locally I have almost the latest. So maybe quickly check yours with `phpcs --version`. I don't think that this leads to totally different results, though.

**Comment by herbdool** [comment]
@indigoxela I was talking about the phpcs tests on github, such as https://github.com/backdrop/backdrop/actions/runs/19970716170/job/57274479536?pr=5168. Right now it's passing so I don't know what's going on.

**Comment by indigoxela** [comment]
> I was talking about the phpcs tests on github, ...

That your a* PR didn't fail, indicates in fact a bug in our action.

That unrelated failures (in unchanged code) didn't show up - that's exactly how the action's supposed to work. It suppresses phpcs nagging on unrelated and unchanged code.

So, you didn't run phpcs locally at all?

**Comment by herbdool** [comment]
I hadn't run phpcs locally. Though since you pointed out the failures I dusted it off and ran it locally too.

**Comment by herbdool** [comment]
If it makes it easier to review and get this merged I could remove the `string` and `int`. It will still be a big improvement.

**Comment by indigoxela** [comment]
> If it makes it easier to review and get this merged I could remove the string and int.

That's not actually my decision. 😉 I only had questions (and concerns).

> It will still be a big improvement.

Yes, for sure it will. Even if we really only do the minimal step (fix only _actual_ coding standard nagging).
Even the "minimal step" will take quite some time and effort, looking at this huge task list.

**Comment by herbdool** [comment]
@indigoxela it might not be your "decision" but being a reviewer matters and we try to come to consensus in core development.

My aim is to try to do most of the files in `/includes/*` for now. It'll help to greatly reduce the amount of nagging in my IDE.

**Comment by indigoxela** [comment]
> My aim is to try to do most of the files in /includes/* for now. It'll help to greatly reduce the amount of nagging in my IDE.

Sounds like a plan. 🤝
For backwards compatibility reasons it might not be possible to completely fix all nagging in your IDE, though.
But as mentioned earlier - any improvement of legacy code doc blocks is great progress. And other things like proper indentation improve code readability.

**Comment by herbdool** [comment]
PR for `includes/d*` https://github.com/backdrop/backdrop/pull/5173

**Comment by herbdool** [comment]
PR for `core/includes/e*` https://github.com/backdrop/backdrop/pull/5174

**Comment by indigoxela** [comment]
Wow, you keep going @herbdool 😁 I wonder, how we can keep the review and merge process manageable... The issue description itself isn't editable anymore due to a GitHub quirk. And commenting here might cause too much confusion...
I'll try to keep per-PR discussions on the individual PRs - what do you think?

Starting with b* now.

**Comment by indigoxela** [comment]
BTW @herbdool do you have phpcbf installed as well? It's able to do *simple* tasks for you - like adding a fullstop or comment... That tool's provided by the same repo: https://github.com/PHPCSStandards/PHP_CodeSniffer/releases

**Comment by indigoxela** [comment]
Several comments added to PR "b*". (BTW I don't think, I can review in the same tempo as you add PRs @herbdool 😆)

**Comment by indigoxela** [comment]
core/includes/b* is RTBC now: https://github.com/backdrop/backdrop/pull/5168

**Comment by indigoxela** [comment]
Started with reviewing core/includes/c*, but need a pause - common.inc with hundreds of lines changed in its 9250 lines of code is a bit of a challenge to review.

Edit: review finalized, just some comments to consider.

Edit 2: I think, [core/includes/c*](https://github.com/backdrop/backdrop/pull/5170) is ready to go now. RTBC 👍

**Comment by indigoxela** [comment]
I started looking at [includes/d*](https://github.com/backdrop/backdrop/pull/5173), but am far from done.

Edit: some final tweaks and we're done with `d*`, some open questions, also...

**Comment by herbdool** [comment]
I've created a sub-issue for `core/includes/*` and "moved" the PRs to it: https://github.com/backdrop/backdrop-issues/issues/7031. This is necessary since we can no longer edit this issue body.

**Comment by quicksketch** [comment]
Thanks @herbdool. It seems no one is allowed to edit this issue any more, including repo admins. Let's close this issue permanently and move over to your new issue at https://github.com/backdrop/backdrop-issues/issues/7031.
