### ISSUE TITLE
Backdrop 1.24.1 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6029]
Release scheduled for Mar 15, 2023 11am - 4pm PT

## Pre-release tasks

- [x] Merge commits @herbdool @bwpanda
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
    * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @herbdool / @bwpanda
- [x] Tag for release, and push tag to GitHub @herbdool / @bwpanda
- [x] Revert version number back @herbdool / @bwpanda
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md)
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @stpaultim  / @jenlampton 
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--tugboat.md) @bwpanda | @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--pantheon-upstream.md) @laryn 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--platformsh-template.md) @herbdool 
- [x] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool 
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/blob/main/procedures/update--docker-image.md) @wylbur
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [x] backdropcms.org @jenlampton
- [x] beta.backdropcms.org @bugfolder 
- [x] docs.backdropcms.org @jenlampton
- [x] events.backdropcms.org @jenlampton
- [x] forum.backdropcms.org @jenlampton 
- [x] localize.backdropcms.org @jenlampton 

## See also 

[Backdrop 1.23.3 Release checklist](https://github.com/backdrop/backdrop-issues/issues/6030)

**Comment by jenlampton** [comment]
I draft SA has been posed: https://backdropcms.org/security/backdrop-sa-core-2023-004

**Comment by jenlampton** [comment]
Release notes draft:

---
 
This is a security release for Backdrop CMS. This release fixes 1 security vulnerability:
* [BACKDROP-SA-CORE-2023-004](https://backdropcms.org/security/backdrop-sa-core-2023-004)

This release also includes a handful of bug fixes and other improvements. See the complete list below.

**Notes for updating**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Changes since version 1.24.0** are listed below.

## Bug fixes

- Fixed: On a localized site, the Default image is not removable unless in the default language. [#6003](https://github.com/backdrop/backdrop-issues/issues/6003)
- Fix numerous spelling errors in documentation. [#5987](https://github.com/backdrop/backdrop-issues/issues/5987)
- Fixed: PHP `Error: Class name must be a valid object or a string in entity_get_controller()`.  [#5953](https://github.com/backdrop/backdrop-issues/issues/5953)
- Fixed: Node layout is not being used when viewing a node revision. [#5915](https://github.com/backdrop/backdrop-issues/issues/5915)
- Fixed: Adding URL redirects from node form causes a PHP warning. [#5878](https://github.com/backdrop/backdrop-issues/issues/5878)
- Fixed: During Drupal 7 upgrade switch to the standard installation profile if previous profile is not available. [#2518](https://github.com/backdrop/backdrop-issues/issues/2518)

## User experience improvements

- Increase the size of the token browser modal to prevent "more" link wrapping.  [#1038](https://github.com/backdrop/backdrop-issues/issues/1038)
- Disambiguate "Layouts" vs "Layout templates" in the admin interface. [#3607](https://github.com/backdrop/backdrop-issues/issues/3607)

## Documentation updates

- Cleanup the documentation in the `diff.inc` file. [#6026](https://github.com/backdrop/backdrop-issues/issues/6026)
- Add a link to the `$_SESSIONS` documentation from the documentation in `sessions.inc`. [#5998](https://github.com/backdrop/backdrop-issues/issues/5998)
- Add documentation for the global `$conf`. [#5902](https://github.com/backdrop/backdrop-issues/issues/5902)
- Update documentation for `node_load_multiple(FALSE)`. [#5889](https://github.com/backdrop/backdrop-issues/issues/5889)
- Add documentation to explain the use of `t()` around the ellipsis for `truncate_utf8()`. [#4545](https://github.com/backdrop/backdrop-issues/issues/4545)

## Miscellaneous changes

- Provide a method to get the pager's element ID. [#5958](https://github.com/backdrop/backdrop-issues/issues/5958)
- Remove the unnecessary return statements from `hook_form_FORM_ID_alter()` implementations in System module. [#5994](https://github.com/backdrop/backdrop-issues/issues/5994)
- Remove the username from the message displayed when accessing another account's password reset URL. [#5971](https://github.com/backdrop/backdrop-issues/issues/5971)
- Bring entity reference module up to date with Drupal 7.x-1.6 release. [#5952](https://github.com/backdrop/backdrop-issues/issues/5952)
- Use the testing profile for `CommentViewsHandlerArgumentUserUidTest`. [#5839](https://github.com/backdrop/backdrop-issues/issues/5839)
- Remove the 'article' role attribute from 'article' html elements. [#4033](https://github.com/backdrop/backdrop-issues/issues/4033)

**Comment by quicksketch** [comment]
Release notes look good and @herbdool made the 1.24.1 release at https://github.com/backdrop/backdrop/releases/tag/1.24.1. We look ready to release.

**Comment by jenlampton** [comment]
https://backdropcms.org/security/backdrop-sa-core-2023-004 is published.

**Comment by jenlampton** [comment]
1.24.1 is out https://github.com/backdrop/backdrop/releases/tag/1.24.1

**Comment by jenlampton** [comment]
All backdrop sites (except beta) are updated to 1.24.1.

**Comment by laryn** [comment]
Pantheon upstream is updated.

**Comment by Wylbur** [comment]
Docker update was completed a few days ago.  Sorry, I thought I posted that earlier.
