### ISSUE TITLE
Backdrop 1.23.4 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6068]
Release scheduled for April 19, 2023 11:30am - 1:30pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
    * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 

## See Also

- [Checklist for 1.24.2 release](https://github.com/backdrop/backdrop-issues/issues/6069)

**Comment by jenlampton** [comment]
Release notes draft:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:
* [Backdrop core - Moderately critical - Access bypass - BACKDROP-SA-CORE-2023-005](https://backdropcms.org/security/backdrop-sa-core-2023-005)

**Notes for updating**
- This release does modify the `settings.php` file located outside the `core` directory. Updating your customized copy of this file is recommended, but not necessary. To update, copy the new section on`file_not_normalized_schemes` [from our file](https://github.com/backdrop/backdrop/blob/1.x/settings.php#L474) to yours.
- The database update script does **not** need to be run.

**Comment by quicksketch** [comment]
Those release notes look good, I made a minor edit.

The tag is cut and ready to go at https://github.com/backdrop/backdrop/releases/tag/1.23.4

**Comment by jenlampton** [comment]
Release is out.
