### ISSUE TITLE
Backdrop 1.24.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6069]
Release scheduled for April 19, 2023 11:30am - 1:30pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Create the next bugfix milestone @jenlampton 
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
    * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @jenlampton 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Publish Security Advisories on b.org @jenlampton 
- [x] Mark the release node on b.org as a security release @jenlampton 
- [x] N/A [Request a CVE](https://github.com/backdrop/backdrop-issues/blob/master/procedures/security--request-cve.md) - (assign to jenlampton / quicksketch)
- [x] Update the front page download link on b.org @jenlampton 
- [x] Tweet that a new release is out @jenlampton 
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @bwpanda 
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool 
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [x] backdropcms.org @jenlampton
- [x] beta.backdropcms.org @bugfolder 
- [x] docs.backdropcms.org @jenlampton
- [x] events.backdropcms.org @jenlampton
- [x] forum.backdropcms.org @jenlampton
- [x] localize.backdropcms.org @jenlampton 

## See Also

- [Checklist for 1.23.4 release](https://github.com/backdrop/backdrop-issues/issues/6068)

**Comment by jenlampton** [comment]
SA is drafted: https://backdropcms.org/security/backdrop-sa-core-2023-005

**Comment by jenlampton** [comment]
Release notes draft:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:
* [Backdrop core - Moderately critical - Access bypass - BACKDROP-SA-CORE-2023-005](https://backdropcms.org/security/backdrop-sa-core-2023-005)

This release also includes a handful of bug fixes and other improvements.

**Notes for updating**
- This release does modify the `settings.php` file located outside the `core` directory. Updating your customized copy of this file is recommended, but not necessary. To update, copy the new section on`file_not_normalized_schemes` [from our file](https://github.com/backdrop/backdrop/blob/1.x/settings.php#L474) to yours.
- **It will be necessary to run the update script** (located at `/core/update.php`) for this release.

**Changes since version 1.24.3** are listed below.

**Comment by quicksketch** [comment]
Tag for https://github.com/backdrop/backdrop/releases/tag/1.24.2 is ready to go.

**Comment by jenlampton** [comment]
Release is out: https://github.com/backdrop/backdrop/releases/tag/1.24.2

**Comment by bugfolder** [comment]
> Changes since version 1.24.3 are listed below.

You mean 1.24.1, right?

**Comment by jenlampton** [comment]
yes! thank you. Fixing now :)

**Comment by jenlampton** [comment]
All sites except beta have the security update, and a new release of the borg theme. but now I'm tired so I'm going to take a little break.

**Comment by laryn** [comment]
Pantheon upstream has been updated.

**Comment by bugfolder** [comment]
beta has the security update and the new release of the borg theme.

**Comment by Wylbur** [comment]
Docker has been updated.

**Comment by klonos** [comment]
Closing this old task.
