### ISSUE TITLE
Backdrop 1.25.0-preview Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6102]
Scheduled for May 2nd, 2023 5pm - 10pm PT

## Pre-release tasks

- [x] N/A If this is the Jan 1 pre-release, then make sure to update the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file.
- [x] Merge commits  @quicksketch
- [x] Create a new minor release milestone
- [x] Move all unfinished issues to the next minor release milestone 
- [ ] Review all closed issues in milestone: @jenlampton
  - [x] Issue titles should include a complete, but very brief summary of the problem.
  - [x] Issue titles should be in complete sentences, ending with a period.
  - [x] Bug issue titles should start with `Fix` or `Fixed`,
  - [x] New feature issue titles should start with `Add` or `Added`.
  - [ ] Each issue should have accurate labels, especially the "type - " labels.
- [ ] Draft Release notes @jenlampton
  - [x] Include a short, descriptive summary of the release, for example:
    * This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on May 15th, 2023.
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [ ] Review issues for new features 
  - [ ] Add a conclusion suitable for blog post + release notes @cellear @klonos @stpaultim ??
  - [x] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated) @jenlampton
  - [x] Add `Needs change record` label if the the issue contains an API change. @jenlampton
  - [x] Add `Needs translation` label if the the issue contains string translations. @jenlampton
- [ ] Draft blog post for release on the 15th @cellear 
- [ ] Draft roadmap updates for backdropcms.org @klonos 
- [ ] Update list of modules included in backdrop core @klonos 
- [ ] Update list of modules included in backdrop_upgrade_status module @jenlampton
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (e.g. `1.10.0-preview`) @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Note: New incremented branch for development is usually created on release day
- [x] Revert version number back on 1.x branch with the same minor number (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub **Important: Check "This is a pre-release" checkbox when creating release** @jenlampton 

## Website updates
- [ ] beta.backdropcms.org @bugfolder / @jenlampton 

## Post-release Publicity + documentation tasks

- [ ] Tweet that a preview release is out @stpaultim 
- [ ] Publish roadmap updates for backdropcms.org @klonos

**Comment by quicksketch** [comment]
The tag is cut and ready: https://github.com/backdrop/backdrop/releases/tag/1.25.0-preview

**Comment by jenlampton** [comment]
Release notes draft:
---

This is the preview release of Backdrop 1.25.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on May 15th, 2023.

**Notes for updating**
- **It will be necessary to run the update script** (located at /`core/update.php`) for this release.
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**Changes since version 1.24.2** are listed below.

## New features

- ALT attributes should be enabled by default on new fields and have an option to set ALT as required. [#3006](https://github.com/backdrop/backdrop-issues/issues/3006)
- Add a mini pager option to Search module results.  [#6083](https://github.com/backdrop/backdrop-issues/issues/6083)
- Add a language switcher to the admin bar when locale is enabled. [#5983](https://github.com/backdrop/backdrop-issues/issues/5983)
- Add context from Layouts to be passed into to Views blocks. [#5995](https://github.com/backdrop/backdrop-issues/issues/5995)
- Add an option to change parent link behavior for responsive dropdown menus. [#2370](https://github.com/backdrop/backdrop-issues/issues/2370)
- Add webP support to all image and file fields (including hero block). [#4937](https://github.com/backdrop/backdrop-issues/issues/4937)

## User Experience Improvements

- Add the option to limit text formats for each field instance. [#2615](https://github.com/backdrop/backdrop-issues/issues/2615)
- When a new content type is created, automatically assign permissions to the "Editor" role. [#5885](https://github.com/backdrop/backdrop-issues/issues/5885)
- Add proper indentation to taxonomy checkboxes/radios to denote child terms. [#3292](https://github.com/backdrop/backdrop-issues/issues/3292)

## Bug fixes

- Fixed: Ensure that layout conditions have all required contexts. [#4594](https://github.com/backdrop/backdrop-issues/issues/4594)
- Add a backward-compatible fallback for `image_TOOLKIT_supported_extensions()`. [#6092](https://github.com/backdrop/backdrop-issues/issues/6092)

## Miscellaneous changes

- Add more words to the CSpell dictionary to avoid false positives. [#6047](https://github.com/backdrop/backdrop-issues/issues/6047)
- Allow theme JavaScript to specify header/footer scope. [#5677](https://github.com/backdrop/backdrop-issues/issues/5677)
- Add a `changed` (last updated/last modified) property to the `User` object. [#5944](https://github.com/backdrop/backdrop-issues/issues/5944)
- Add `#indentation` property to FAPI elements. [#5999](https://github.com/backdrop/backdrop-issues/issues/5999)
- Follow-up to #6028: Cleanup & optimization of the `#indentation` FAPI property. [#6028](https://github.com/backdrop/backdrop-issues/issues/6028)
- Follow-up to #6028: Fixed indentation issues appearing on some forms. [#6090](https://github.com/backdrop/backdrop-issues/issues/6090)

**Comment by quicksketch** [comment]
I re-titled https://github.com/backdrop/backdrop-issues/issues/3006 to `Allow "alt" attribute field to be required on image uploads` since that's what the issue ultimately became (rather than making it required by default).

`webP` should be `WebP`

I'd consider "Add the option to limit text formats for each field instance." a feature, not a UX improvement (which would improve existing functionality).

I think `Add a backward-compatible fallback for image_TOOLKIT_supported_extensions()` can be removed, since it was a bug fix to a feature that hasn't been released yet. Or post it as a follow-up to https://github.com/backdrop/backdrop-issues/issues/4937.

**Comment by jenlampton** [comment]
I think I got all those changes in.

**Comment by jenlampton** [comment]
Pre-release is out! https://github.com/backdrop/backdrop/releases/tag/1.25.0-preview

**Comment by klonos** [comment]
@jenlampton I don't have access to edit/tweak the release notes directly, so if you agree with the following changes on the last two bullet points and have the time for it:
```
  - Follow-up to #5999: Cleanup & optimization of the `#indentation` FAPI property. #6028
  - Follow-up to #5999: Fixed a CSS-class-conflict-related regression with the `#indentation` FAPI property. #6090
```

So:
- linkigy the "5999" bit in "Follow-up to 5999:"
- reword the second bulletpoint to mention that it was a regression fix
- add indentation to the bullet points (pun 😅), so that they are nested under the "parent" bullet point above them

**Comment by quicksketch** [comment]
1.25.0 official release checklist: https://github.com/backdrop/backdrop-issues/issues/6115

Let's incorporate @klonos's feedback into the final release notes.

**Comment by jenlampton** [comment]
> linkigy the "5999" bit in "Follow-up to 5999:"

I had these linked originally, but it broke the formatting and it was easiest to just remove the links, so I did. I'll try harder to get them linked today!

**Comment by jenlampton** [comment]
Was this the regression fix?

Add the option to limit text formats for each field instance. [#2615](https://github.com/backdrop/backdrop-issues/issues/2615)

**Comment by quicksketch** [comment]
> Was this the regression fix?
> 
> Add the option to limit text formats for each field instance. [#2615](https://github.com/backdrop/backdrop-issues/issues/2615)

No, that's a new feature. I'm not sure which item he meant was a regression fix.

**Comment by jenlampton** [comment]
I think it was the second follow-up to 5999, since he reworded it as re regression in his example :)
