### ISSUE TITLE
Backdrop 1.25.0 Release Checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6115]
## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create a new minor release (@quicksketch)
- [x] Create the next minor milestone (@quicksketch)
- [x] Move all unfinished issues to the next major release milestone (@jenlampton)
- [x] Review all closed issues in milestone:  (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch 
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Create a new language template file for the translation server @olafgrabienski - see https://github.com/backdrop-ops/localize.backdropcms.org/issues/27 until this is automated)

### Publicity tasks

- [ ] Tweet that a new release is out @stpaultim 
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [ ] Publish blog post @cellear 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @stpaultim ? @klonos ?
- [ ] Update the roadmap page on b.org @klonos 
- [x] Update list of modules included in backdrop core @jenlampton 
- [x] Update list of modules included in backdrop_upgrade_status module @jenlampton 
- [x] Update the Wikipedia articles @klonos 
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur

### Backdrop Website updates

- [ ] beta.backdropcms.org -- if not done with preview @jenlampton 
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Publicity tasks

- [ ] Add a notification to the dashboard @stpaultim 
- [ ] Send a newsletter to subscribers @cellear 

### Backdrop Website updates

- [ ] backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 

See Also
---------
* [Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6102)

**Comment by quicksketch** [comment]
Note that because we only have a _single_ commit to the 1.24.x branch, I'm inclined to not make a 1.24.3 release. The only commit is 67a21032761d722310d6eafd69074ab5cb4fd7bb from #6081, which is a performance improvement. With no significant difference from 1.24.2, I don't think we need to create 1.24.3. If a security release is created, that one fix will be bundled with it.

**Comment by quicksketch** [comment]
The tag is cut at https://github.com/backdrop/backdrop/releases/tag/1.25.0

**Comment by jenlampton** [comment]
release is out https://github.com/backdrop/backdrop/releases/tag/1.25.0

**Comment by laryn** [comment]
Pantheon is updated. https://github.com/backdrop-ops/backdrop-pantheon

**Comment by klonos** [comment]
Tugboat demos have been updated 👍🏼

**Comment by olafgrabienski** [comment]
Created new language template file for the translation server. √
(Can someone tick the respective checkbox in the issue description?)

**Comment by klonos** [comment]
Updated the wikipedia articles 👍🏼

**Comment by Wylbur** [comment]
Marking this as closed/outdated.
