### ISSUE TITLE
Backdrop 1.25.1 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6138]
Release scheduled for June 7, 2023 1pm - 4pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [x] Review all closed issues in milestone:  (@quicksketch)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone  (@quicksketch)
- [x] Draft Release notes  (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back  (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Update the front page download link on b.org (@quicksketch)
- [ ] Tweet that a new release is out (@stpaultim)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @bwpanda | @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) (assign to herbdool, jenlampton)
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool (or quicksketch)
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [x] Update the Wikipedia articles (assign to stpaultim / klonos)
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [x] backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [x] beta.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [x] docs.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [x] events.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [x] forum.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [x] localize.backdropcms.org @jenlampton (or bwpanda / bugfolder)

This is a stand-alone release.

**Comment by quicksketch** [comment]
Release notes draft:

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for Updating**

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

**Changes since version 1.25.0** are listed below.

## Bug fixes

- Fix regression: double encoding of option values [#6126](https://github.com/backdrop/backdrop-issues/issues/6126)
- Fix PR sandboxes provisioned with PHP 7.2 instead of 8.1 [#6133](https://github.com/backdrop/backdrop-issues/issues/6133)
- Fix install.sh with PHP 8.1 causes deprecation notices [#6087](https://github.com/backdrop/backdrop-issues/issues/6087)
- Fix "Back to site" link does not respect selected language [#6080](https://github.com/backdrop/backdrop-issues/issues/6080)
- Fix fatal error when submitting a form that has a hidden date field and uses the HTML5 Date widget [#6027](https://github.com/backdrop/backdrop-issues/issues/6027)
- Restore definitions of variables $v_version and $v_magic in Archive_Tar [#3492](https://github.com/backdrop/backdrop-issues/issues/3492)

## Miscellaneous changes

- Replace "Users'" in contact module permissions [#6112](https://github.com/backdrop/backdrop-issues/issues/6112)

**Comment by klonos** [comment]
Tugboat demos updated 👍🏼

**Comment by klonos** [comment]
...Wikipedia articles also updated 👍🏼

**Comment by Wylbur** [comment]
Backdrop-docker pull request created. 
https://github.com/docker-library/official-images/pull/14800

**Comment by klonos** [comment]
@Wylbur for next time, can you please remove Geoff from the list of contacts that are notified? And feel free to add yourself there if you like 😉

**Comment by laryn** [comment]
Pantheon upstream is updated.

**Comment by bugfolder** [comment]
All *.b.org sites are updated.

**Comment by laryn** [comment]
Closing as outdated.
