### ISSUE TITLE
Backdrop 1.25.2 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6224]
Release scheduled for September 15, 2023 4pm - 6pm PT

Note this release accompanies Backdrop 1.26.0.

## Pre-release tasks

- [x] Merge commits (@quicksketch / @laryn)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] ~Update the front page download link on b.org~
- [x] ~Tweet that a new release is out~

## See Also

- [Checklist for 1.26.0 release](https://github.com/backdrop/backdrop-issues/issues/6225)

**Comment by quicksketch** [comment]
Release notes draft:

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**It will be necessary to run the update script** (located at /core/update.php) for this release.

## Bug fixes

- PHP 8.2 support for taxonomy vocabularies [#6197](https://github.com/backdrop/backdrop-issues/issues/6197)
- PHP 8.1 Views: Exposed Items Per Page of "All" causes error [#6167](https://github.com/backdrop/backdrop-issues/issues/6167)
- Hidden date field saves null values when editing an existing node, producing notices [#6198](https://github.com/backdrop/backdrop-issues/issues/6198)
- Telemetry UI doesn't show the module name as specified [#6222](https://github.com/backdrop/backdrop-issues/issues/6222)
- Appearance page operations links are missing classes [#6205](https://github.com/backdrop/backdrop-issues/issues/6205)
- Token in field descriptions not working unless in fields that handle multiple values [#6196](https://github.com/backdrop/backdrop-issues/issues/6196)
- Views dropbuttons have bad widths and text alignment in Basis theme [#6180](https://github.com/backdrop/backdrop-issues/issues/6180)
- Remove periods from the labels of radios and checkboxes in the "Account settings" form [#6177](https://github.com/backdrop/backdrop-issues/issues/6177)
- `installer_browser_install_button_form()` assigns a string to `$form['#attributes']['class']`  [#6168](https://github.com/backdrop/backdrop-issues/issues/6168)
- Form API element type `password_confirm` wipes out all preset attributes from the form element [#6157](https://github.com/backdrop/backdrop-issues/issues/6157)
- User login form should not use spellcheck or autocorrect [#6153](https://github.com/backdrop/backdrop-issues/issues/6153)
- Typo in the help text for the "Show as expanded" option for menu items: hierarchial -> hierarchical [#6151](https://github.com/backdrop/backdrop-issues/issues/6151)
- number.module is enforcing a maximum value even if one is not specified [#6137](https://github.com/backdrop/backdrop-issues/issues/6137)
- Views dialogs are rendered partially off-screen and submit buttons are unreachable  [#6076](https://github.com/backdrop/backdrop-issues/issues/6076)
- Color Module cannot save colors if uppercase hex codes used in theme's color.inc [#6057](https://github.com/backdrop/backdrop-issues/issues/6057)
- Plural formulas are wiped out upon D7 upgrade [#6051](https://github.com/backdrop/backdrop-issues/issues/6051)
- Filter Reset for Modules and Permissions doesn't clear url search query [#5955](https://github.com/backdrop/backdrop-issues/issues/5955)
- Reordering fails with more than 100 items in a menu [#5400](https://github.com/backdrop/backdrop-issues/issues/5400)
- Click menu gets confused when multiple menus on a page [#4488](https://github.com/backdrop/backdrop-issues/issues/4488)
- Misleading description for 'Trimmed limit' setting on long text fields [#3828](https://github.com/backdrop/backdrop-issues/issues/3828)
- Document `Node` passed into theme_username as 'account'. [#1275](https://github.com/backdrop/backdrop-issues/issues/1275)
- Replace "Drupal" with "Backdrop" in admin-tabs.css [#6218](https://github.com/backdrop/backdrop-issues/issues/6218)

## Miscellaneous changes

- Do not return `TRUE` from `backdrop_session_regenerate()` [#6019](https://github.com/backdrop/backdrop-issues/issues/6019)
- Make Backdrop core compatible with PHP 8.2 [#5927](https://github.com/backdrop/backdrop-issues/issues/5927)
- Update jQuery UI to the latest versions [#5705](https://github.com/backdrop/backdrop-issues/issues/5705)

**Comment by quicksketch** [comment]
[Release is cut for 1.25.2](https://github.com/backdrop/backdrop/releases/tag/1.25.2)! Now on to 1.26.0 in https://github.com/backdrop/backdrop-issues/issues/6225
