### ISSUE TITLE
Backdrop 1.26.0 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6225]
Scheduled for September 15, 2023 4pm - 6pm PT

## Pre-release tasks

- [x] Merge minor release commits (@quicksketch / @laryn)
- [x] Move all unfinished issues to the next bug-fix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub (@quicksketch)
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Unpublish preview release on backdropcms.org (@quicksketch)
- [x] Update the front page download link on b.org (@quicksketch)
- [x] Create a new language template file for the translation server (@olafgrabienski)

### Publicity tasks

- [ ] Tweet that a new release is out (@stpaultim)
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [ ] Publish blog post (@cellear)
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter (assign to stpaultim / klonos / jenlampton)
- [ ] Update the roadmap page on b.org (@klonos / @jenlampton)
- [ ] Update list of modules included in backdrop core (@jenlampton)
- [ ] Update list of modules included in backdrop_upgrade_status module (@jenlampton)
- [x] Update the Wikipedia articles (@klonos)
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

### Code tasks

- [ ] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @bwpanda | @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @laryn 
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur

### Backdrop Website updates

- [ ] beta.backdropcms.org -- if not done with preview (assign to bugfolder / jenlampton / bwpanda)
- [ ] docs.backdropcms.org (assign to jenlampton / bwpanda / bugfolder)
- [ ] events.backdropcms.org (assign to jenlampton / bwpanda / bugfolder)

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Publicity tasks

- [ ] Add a notification to the dashboard (assign to stpaultim / klonos / jenlampton)
- [ ] Send a newsletter to subscribers (assign to bwpanda / stpaultim / jenlampton)

### Backdrop Website updates

- [ ] backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] forum.backdropcms.org @jenlampton (or bwpanda / bugfolder)

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6224)
* [Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6216)

**Comment by quicksketch** [comment]
# Release Notes Draft

The Backdrop community is proud to release version 1.26.0 of Backdrop CMS, following our 4-month release cycle.

Backdrop 1.26.0 has an emphasis on updating our 3rd party libraries. In particular jQuery (and most jQuery-dependent libraries) are caught up to the latest versions. Backdrop is also preparing for the inclusion of CKEditor 5, which is currently still in development as a contributed module.

Backdrop 1.26.0 also fully updates core to be PHP 8.2 compatible.

**Notes for updating**

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**It will be necessary to run the update script** (located at `/core/update.php`) for this release.

Changes since version 1.25.2 are listed below.

## New features

- Allow Link fields to be restricted to only internal or external URLs [#5678](https://github.com/backdrop/backdrop-issues/issues/5678)
- Allow themes to have `config` folders [#6122](https://github.com/backdrop/backdrop-issues/issues/6122)
- Add `user_role_has_permission()` function [#6186](https://github.com/backdrop/backdrop-issues/issues/6186)

## Miscellaneous changes

- Add jQuery v3.x and make it the default for new installations (with a fallback to v1.x for existing sites) [#3106](https://github.com/backdrop/backdrop-issues/issues/3106)
- Update to jQuery 3.7.1 [#6211](https://github.com/backdrop/backdrop-issues/issues/6211)
- Update jQuery related libraries in core to their latest version, where possible [#6185](https://github.com/backdrop/backdrop-
issues/issues/6185)
- Fork jQuery.once() to maintain compatibility with future versions of jQuery [#6195](https://github.com/backdrop/backdrop-issues/issues/6195)
- Replace deprecated jQuery methods used in core scripts [#6149](https://github.com/backdrop/backdrop-issues/issues/6149)
- Update the telemetry module to report the CKEditor versions [#6214](https://github.com/backdrop/backdrop-issues/issues/6214)
- Show CKEditor in the site status report page. [#3360](https://github.com/backdrop/backdrop-issues/issues/3360)
- Remove interest-cohort header [#6199](https://github.com/backdrop/backdrop-issues/issues/6199)

This release also includes all the fixes from 1.25.2 (also released today). See the [1.25.2 release notes](https://github.com/backdrop/backdrop/releases/tag/1.25.2) for the list of additional fixes.

**Comment by jenlampton** [comment]
release notes lgtm!

**Comment by quicksketch** [comment]
The release is out! https://github.com/backdrop/backdrop/releases/tag/1.26.0

**Comment by laryn** [comment]
I've updated the Pantheon upstream.

**Comment by olafgrabienski** [comment]
I've created a new language template file for the [translation server](https://localize.backdropcms.org/).

**Comment by laryn** [comment]
Closing as outdated.
