### ISSUE TITLE
[META] Include all D7 Entity Cache module updates

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6232]
Version included in core: [entitycache 7.x-1.5](https://www.drupal.org/project/entitycache/releases/7.x-1.5)

Updates needed:
* [entitycache 7.x-1.6](https://www.drupal.org/project/entitycache/releases/7.x-1.6)
  - [ ] #2341355 by alexmoreno, parasolx, greggles, mcdruid, hussainweb: Notice: Trying to get property of non-object in   - [ ] entitycache_user_logout
  - [ ] #3376606 by mcdruid: EntityCacheControllerHelper::entityCacheLoad may generate entity queries with different case sensitivity to core
  - [ ] #2441965 by Elin Yordanov, lord_of_freaks, joelpittet, dineshw, vijaycs85, DuaelFr, izus, marie.pinet, catch, MustangGB,   - [ ] TechnoTim2010, malcomio: Broken updates due to Classes living in .module files
  - [ ] #3002960 by solideogloria: fixed typo in lamdbaba
  - [ ] #2981629 by MPetrovic, smaz: create_function is deprecated in PHP 7.2
  - [ ] #3021963 by plach: Add a way to clear only static cache
  - [ ] #2044291 by czigor, anbarasan.r, Fabianx, ericduran, Elijah Lynn, Dave Reid: Add drupal_alter() to entityCacheGet & entityCacheSet &   - [ ] resetEntityCache
  - [ ] #2441965 by pc-wurm, lord_of_freaks, joelpittet, DuaelFr, vijaycs85: Broken updates due to Classes living in .module files
  - [ ] #2619270 by joelpittet: Parse error: syntax error, unexpected T_STATIC
* [entitycache 7.x-1.7](https://www.drupal.org/project/entitycache/releases/7.x-1.7)
   - [ ] Fixes [SA-CONTRIB-2023-046](https://www.drupal.org/sa-contrib-2023-046).

Resources:
* Added to Backdrop in version 1.16.0 on May 15, 2020
* [Backdrop Change record](https://docs.backdropcms.org/change-records/entity-caching-added-to-core)
* [All D7 releases](https://www.drupal.org/project/entitycache/releases?version=7)

**Comment by argiepiano** [comment]
I'm looking at [#2341355](https://git.drupalcode.org/project/entitycache/-/commit/3dd2318c8e1a7db10386249fb6be8ad6774d5c8a). That fix doesn't apply to Backdrop, since clearing the user entity cache is already done in core. 

- For canceling a user, the entity_user cache is cleared by `EntityDatabaseStorageController::delete()`, which invokes the method `resetCache()`
- For log in, the entity_user cache clearing is done in `user_login_finalize()` 
- For log out, clearing happens in `user_logout()`.
