### ISSUE TITLE
Backdrop 1.26.1 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6253]
Release scheduled for October 6, 2023 2pm - 4pm PT

This is a non-security, bug-fix release.

## Pre-release tasks

- [x] Merge commits (@quicksketch/@laryn)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square bracets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Update the front page download link on b.org (@quicksketch)
- [ ] Tweet/Toot that a new release is out (@stpaultim)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @bwpanda | @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) (assign to herbdool, jenlampton)
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool (or quicksketch)
- [x] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [x] Update the Wikipedia articles (assign to stpaultim / klonos)
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [x] backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] beta.backdropcms.org @bugfolder
- [ ] docs.backdropcms.org @jenlampton
- [ ] events.backdropcms.org @jenlampton
- [ ] forum.backdropcms.org @jenlampton
- [ ] localize.backdropcms.org @jenlampton

**Comment by quicksketch** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only. In particular this release fixes a regression where the Installer module was unable to install or update modules when running on a Windows file system.

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**Changes since version 1.26.0**

The database update script does **not** need to be run.

## Bug fixes

- Regression on Windows: Backdrop 1.26.0 release GUI install module Error: File Transfer failed [#6226](https://github.com/backdrop/backdrop-issues/issues/6226)
- The node author name does not change upon editing the user account name. [#6243](https://github.com/backdrop/backdrop-issues/issues/6243)
- Image browser attached to field doesn't work if field is in a modal [#6236](https://github.com/backdrop/backdrop-issues/issues/6236)
- PHP 8.1 Deprecated function Notice when passing NULL to trim() [#6235](https://github.com/backdrop/backdrop-issues/issues/6235)
- User name views autocomplete filter always shows the same description [#6170](https://github.com/backdrop/backdrop-issues/issues/6170)
- On /admin/config/people/login, the default value for the "Identify users attempting to log in, using" field is not shown [#6162](https://github.com/backdrop/backdrop-issues/issues/6162)
- Permissions for the Contact module shown on /admin/config/people/permissions do not match the permissions shown on /admin/structure/contact/settings [#6117](https://github.com/backdrop/backdrop-issues/issues/6117)
- Security improvement for l() function [#5969](https://github.com/backdrop/backdrop-issues/issues/5969)
- Incorrect handling of file upload PHP limit exceeded  [#5960](https://github.com/backdrop/backdrop-issues/issues/5960)
- CKEditor Link Continuously Adds Base URL [#5886](https://github.com/backdrop/backdrop-issues/issues/5886)
- Nested contextual links triggers sometimes unreachable [#5273](https://github.com/backdrop/backdrop-issues/issues/5273)
- Improve display of Bartik's main menu sub-links [#726](https://github.com/backdrop/backdrop-issues/issues/726)
- Fix Bartik Fieldset bottom margin [#6221](https://github.com/backdrop/backdrop-issues/issues/6221)
- text_summary() should output valid HTML and Unicode text [#308](https://github.com/backdrop/backdrop-issues/issues/308)
- The theme_file_formatter_table() should use format_plural() [#5877](https://github.com/backdrop/backdrop-issues/issues/5877)

## Usability Improvements

- Make optional description fields show/hide via `#states`. [#1895](https://github.com/backdrop/backdrop-issues/issues/1895)
- Change the page title for the detailed view of a log entry to "Log entry details"... [#1684](https://github.com/backdrop/backdrop-issues/issues/1684)
- Breadcrumb separator should be marked as decorative [#6034](https://github.com/backdrop/backdrop-issues/issues/6034)

## Miscellaneous changes

- Telemetry: Gather data to determine if multisites are popular or not [#3206](https://github.com/backdrop/backdrop-issues/issues/3206)
- Document why you can't count on module functions in update hooks [#6233](https://github.com/backdrop/backdrop-issues/issues/6233)

**Comment by klonos** [comment]
Tugboat and Wikipedia articles updated 👍🏼

**Comment by findlabnet** [comment]
>The database update script does not need to be run. 

?

![image](https://github.com/backdrop/backdrop-issues/assets/11479969/90259890-51ea-4924-bc12-56fedf2a426f)

**Comment by klonos** [comment]
Good catch @findlabnet 👍🏼 ...this is from https://github.com/backdrop/backdrop/commit/47ec84f92572bdec0d5cf3f022257a1c737c4e25#diff-17883baf5f2ff17d6ff22210dc400dbf07ed40fbca71b0093d8528f31de8cee9R2363

@backdrop/core-committers or anyone with permissions to edit releases, can we please fix that?

**Comment by quicksketch** [comment]
Thanks @findlabnet. I missed that update hook. Release notes corrected.

**Comment by laryn** [comment]
I've updated Pantheon's upstream.

**Comment by Wylbur** [comment]
Docker image pull request created:
https://github.com/docker-library/official-images/pull/15543

**Comment by klonos** [comment]
@Wylbur perhaps I got this wrong, but in the PR, shouldn't the commit hash be the same as the commit for the target release/tag? In the PR I see that as `GitCommit: 95902d6610b2474ca88ff8faae40ed30e7d3318a` for 1.26.1, whereas if I check https://github.com/backdrop/backdrop/releases/tag/1.26.1 I see that the short-version commit indicated there is `8c4fe1d`, with `8c4fe1df75f900866381286e8c4e31f31e1ee69f` being the long/proper hash for it. Am I missing something? 🤔

**Comment by yosifkit** [comment]
@klonos , the `GitCommit` in the official images PR points the `backdrop-ops/backdrop-docker` repo not `backdrop/backdrop`: https://github.com/backdrop-ops/backdrop-docker/commit/95902d6610b2474ca88ff8faae40ed30e7d3318a

**Comment by klonos** [comment]
🤦🏼 👍🏼

**Comment by Wylbur** [comment]
Docker image is updated!

**Comment by klonos** [comment]
1.27.2 and 1.28.0 are out. Closing this.
