### ISSUE TITLE
Backdrop 1.26.2 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6315]
Release scheduled for December 1, 2023 10am - 4pm PT

This is a bug-fix only release.

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone:
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Update the front page download link on b.org (@quicksketch)
- [ ] Tweet that a new release is out (@stpaultim)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) (assign to herbdool, jenlampton)
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [x] Update the Wikipedia articles (assign to @klonos)
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [ ] backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] beta.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] docs.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] events.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] forum.backdropcms.org @jenlampton (or bwpanda / bugfolder)
- [ ] localize.backdropcms.org @jenlampton (or bwpanda / bugfolder)

**Comment by quicksketch** [comment]
The release is out! https://github.com/backdrop/backdrop/releases/tag/1.26.2

**Comment by klonos** [comment]
Tugboat demos and Wikipedia article updated 👍🏼
