### ISSUE TITLE
Backdrop 1.26.4 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6368]
Release scheduled for January 15, 2024 4pm - 6pm PT

This is a bug-fix release that accompanies the minor 1.27.0 release. Post release tasks are tracked in the 1.27.0 issue.

## Pre-release tasks

- [x] Merge commits
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone  (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] ~Update the front page download link on b.org~
- [x] ~Tweet that a new release is out~

## See Also

- [Checklist for 1.27.0 release](https://github.com/backdrop/backdrop-issues/issues/6369)

**Comment by quicksketch** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary. The database update script does **not** need to be run.

## New features

- Add hook_field_schema_alter() [#6208](https://github.com/backdrop/backdrop-issues/issues/6208)

## Bug fixes

- Creating menu items can trigger resource-intensive rebuilding module and field data when it's not needed [#6353](https://github.com/backdrop/backdrop-issues/issues/6353)
- Config sync doesn't see reordering of elements in JSON file as a change [#6348](https://github.com/backdrop/backdrop-issues/issues/6348)
- Semicolons in CSS import statements break compressed CSS files [#6337](https://github.com/backdrop/backdrop-issues/issues/6337)

## Documentation updates

- Change the reference to _db_process_field() in the documentation comment for DatabaseSchema_mysql::createFieldSql() [#6361](https://github.com/backdrop/backdrop-issues/issues/6361)
- Correct the documentation for system_configure_date_formats_form() [#6358](https://github.com/backdrop/backdrop-issues/issues/6358)
- Use different short descriptions for hook_config_create() and hook_config_update() [#6321](https://github.com/backdrop/backdrop-issues/issues/6321)
- Correct the documentation comment for field_config_update_validate() [#6319](https://github.com/backdrop/backdrop-issues/issues/6319)
- Correct the documentation comment for field_config_delete() which is a hook_config_delete() implementation [#6318](https://github.com/backdrop/backdrop-issues/issues/6318)

## Miscellaneous changes

- *Always* include the "View: [view_name]: [block_display_name]" as the default admin label for blocks provided by views. [#1889](https://github.com/backdrop/backdrop-issues/issues/1889)
- Mark some Comment permissions as restricted [#5554](https://github.com/backdrop/backdrop-issues/issues/5554)
- Add back admin bar links to manage display sub-pages [#2450](https://github.com/backdrop/backdrop-issues/issues/2450)
- Appearance page: Denote the theme selected as admin theme (same as we do for the default theme). [#1105](https://github.com/backdrop/backdrop-issues/issues/1105)

**Comment by quicksketch** [comment]
The 1.26.4 release is out! https://github.com/backdrop/backdrop/releases/tag/1.26.4 

We'll switch over to getting the 1.27.0 release out next: https://github.com/backdrop/backdrop-issues/issues/6368
