### ISSUE TITLE
Backdrop 1.27.0 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6369]
Scheduled for January 15, 2024 4pm - 8pm PT

## Pre-release tasks

- [x] If this is the Jan 15 release, ensure that the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file has been updated to reflect the new/current year.
- [x] Merge minor release commits (@quicksketch)
- [x] Move all unfinished issues to the next bug-fix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles sould be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New fearure issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@quicksketch)
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub (@quicksketch)
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch)
- [x] Unpublish preview release on backdropcms.org (@quicksketch)
- [x] Update the front page download link on b.org (@quicksketch)
- [x] Create a new language template file for the translation server (@olafgrabienski  - see https://github.com/backdrop-ops/localize.backdropcms.org/issues/27 until this is automated)

### Publicity tasks

- [ ] Tweet that a new release is out (@stpaultim)
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [x] Publish blog post (@cellear)
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter (@stpaultim)
- [ ] Update the roadmap page on b.org (@klonos)
- [ ] Update list of modules included in backdrop core (@bugfolder / @klonos)
- [ ] Update list of modules included in backdrop_upgrade_status module (@jenlampton)
- [x] Update the Wikipedia articles (@klonos)
  - [x] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @bwpanda | @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @laryn
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [x] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur

### Backdrop Website updates

- [ ] beta.backdropcms.org -- if not done with preview (@bugfolder)
- [x] docs.backdropcms.org (@jenlampton)
- [x] events.backdropcms.org (@jenlampton)

## 2-week Post-release tasks

These should be done after the first bug-fix release or 14 days -- whichever
comes sooner.

### Publicity tasks

- [ ] Add a notification to the dashboard (assign to stpaultim / klonos / jenlampton)
- [ ] Send a newsletter to subscribers (assign to stpaultim / jenlampton)

### Backdrop Website updates

- [ ] backdropcms.org @jenlampton (or bugfolder)
- [ ] forum.backdropcms.org @jenlampton (or bugfolder)

See Also
---------
* [1.26.4 Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6368)

**Comment by quicksketch** [comment]
The Backdrop community is proud to release version 1.27.0 of Backdrop CMS, following our 4-month release cycle.

Backdrop 1.27.0 includes a major upgrade to CKEditor, updating from CKEditor 4 to CKEditor 5. While existing sites can continue to use CKEditor 4, it's recommended to transition to CKEditor 5 as soon as possible. CKEditor 4 is still included in Backdrop 1.27.0 and existing sites are not automatically updated. See the [upgrading to CKEditor 5 blog post for more information](https://backdropcms.org/news/upgrade-from-ckeditor-4-to-5).

Another major compatibility change includes fully dropping support for Internet Explorer (all versions). [Microsoft officially stopped supporting Internet Explorer in 2021](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549). Microsoft Edge and other browsers are not affected by this change.

## Notes for updating

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

It **will** be necessary to run the update script (located at `/core/update.php`) for this release.

## Change records

* [CKEditor 4 to CKEditor 5 Upgrade Changes](https://docs.backdropcms.org/change-records/ckeditor5-upgrade)
* [Internet Explorer Conditional Comments Deprecated (browsers property)](https://docs.backdropcms.org/change-records/internet-explorer-conditional-comments-deprecated-browsers-property)

## New features

- All-new CKEditor 5 module! [#4122](https://github.com/backdrop/backdrop-issues/issues/4122)
- Better reporting for CKEditor 4 vs 5 in Telemetry [#6342](https://github.com/backdrop/backdrop-issues/issues/6342)
- Make mobile menu toggle text configurable [#6264](https://github.com/backdrop/backdrop-issues/issues/6264)
- Add a 'User account: compare' visibility rule [#4029](https://github.com/backdrop/backdrop-issues/issues/4029)
- Allow 'Content: Link' views field to just output URL [#3419](https://github.com/backdrop/backdrop-issues/issues/3419)
- Rename text format "Filtered HTML" label to "Basic" [#1188](https://github.com/backdrop/backdrop-issues/issues/1188)
- Provide an easy way to specify attributes for the wrapper div in the output of `theme_item_list()` [#6148](https://github.com/backdrop/backdrop-issues/issues/6148)

## Bug fixes

(These fixes were made between 1.27.0-preview and the 1.27.0 release.)

- CKEditor 5 - Can not open image dialog if image filters are disabled [#6366](https://github.com/backdrop/backdrop-issues/issues/6366)
- CKEditor 5 - Multivalue textfields break layout [#6364](https://github.com/backdrop/backdrop-issues/issues/6364)
- CKEditor 5 - Unable to type in editor area without Headings button [#6363](https://github.com/backdrop/backdrop-issues/issues/6363)
- CKEditor 5 - Problem creating links [#6359](https://github.com/backdrop/backdrop-issues/issues/6359)
- CKEditor 5 dialogs from within a Backdrop (jquery.ui) dialog not working [#6351](https://github.com/backdrop/backdrop-issues/issues/6351)
- When Body uses CKEditor 5, additional Body entry fields are added to the form when clicking "Add another" for a different field [#6347](https://github.com/backdrop/backdrop-issues/issues/6347)

## Miscellaneous changes

- Remove IE-specific code/libraries [#214](https://github.com/backdrop/backdrop-issues/issues/214)
- Remove -moz-border-radius and -webkit-border-radius from core files [#6265](https://github.com/backdrop/backdrop-issues/issues/6265)
- Remove grippie; use CSS "resize" property [#340](https://github.com/backdrop/backdrop-issues/issues/340)
- Rename "cketoolbar" config key to just "toolbar" [#6352](https://github.com/backdrop/backdrop-issues/issues/6352)
- Merge ckeditor5.compat.js from CKEditor 5 to into CKEditor 4 module [#6341](https://github.com/backdrop/backdrop-issues/issues/6341)
- Enable CKEditor 5 out of the box [#6340](https://github.com/backdrop/backdrop-issues/issues/6340)
- Add status report message informing about CKEditor 5 upgrade [#6346](https://github.com/backdrop/backdrop-issues/issues/6346)

**Comment by jenlampton** [comment]
The events site is updated (and I updated the theme too so the newsletter signup in the footer looks nice)

**Comment by laryn** [comment]
The Pantheon upstream is updated.

**Comment by olafgrabienski** [comment]
The new language template file for the translation server is created.

**Comment by quicksketch** [comment]
I tried to update the demo sandboxes but I don't seem to understand how the update process works. I think the repository is at https://github.com/backdrop-ops/tugboat-demos, but I don't know how to update it. @klonos (or @BWPanda), could you help provide some insight?

**Comment by klonos** [comment]
I'm on it @quicksketch ...I usually just follow the instructions we already have in https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat and that's all it takes.

**Comment by klonos** [comment]
...all done! 😉 

Moving on to update the Wikipedia pages next...

**Comment by klonos** [comment]
...I've updated the Wikipedia template, however the 2 articles where it's being used have not been updated yet. All the previous times I've done that before would also update the the 2 articles instantly. Perhaps there's some delay before the changes propagate now. I'll check again later.

**Comment by quicksketch** [comment]
Ah thanks, I didn't think to check the wiki. Would you be willing to update the README in the tugboat-demos with a link to the wiki for future reference? @klonos

**Comment by klonos** [comment]
@quicksketch there's a link to the Wiki in the respective task in the issue summary (and that's in the template we use for the release tasks, so it's always there) 😉 

Wikipedia articles updates to reflect 1.27.0 btw.

**Comment by klonos** [comment]
@quicksketch I don't have permissions in the tugboat-demos repo (can I please?), so here's a PR instead: https://github.com/backdrop-ops/tugboat-demos/pull/7

**Comment by quicksketch** [comment]
Super, thanks @klonos! I made you an admin on the repository.

**Comment by laryn** [comment]
Closing as outdated.
