### ISSUE TITLE
Backdrop 1.27.1 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6414]
Release scheduled for March 7, 2024 4pm - 6pm PT

This release is a stand-alone bug fix release, so there is only 1.27.1 and no need for a 1.26.x release.

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [x] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch)
- [x] Draft Release notes (@jenlampton)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release (@quicksketch )
- [x] Update the front page download link on b.org (@jenlampton)
- [ ] Tweet that a new release is out (@stpaultim)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.17.1: https://backdropcms.org." or

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [ ] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @laryn
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool 
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool 
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [ ] Update the Wikipedia articles @klonos
  - [ ] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [ ] backdropcms.org @jenlampton
- [ ] beta.backdropcms.org @bugfolder 
- [x] docs.backdropcms.org @jenlampton
- [x] events.backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 
- [x] localize.backdropcms.org @jenlampton

**Comment by quicksketch** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for Updating**

No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary. The database update script does **not** need to be run.

Release notes draft:

## Bug fixes

- Putting a link on an image with a caption will remove the alignment on the figure tag [#6384](https://github.com/backdrop/backdrop-issues/issues/6384)
- PHP notice after update from 1.26.3 to 1.27.0 [#6372](https://github.com/backdrop/backdrop-issues/issues/6372)
- Line Break Filter adds extra `<br>` tags within headings [#6371](https://github.com/backdrop/backdrop-issues/issues/6371)
- DatabaseConnection_mysql::$utf8mb4Supported is never initialized [#6370](https://github.com/backdrop/backdrop-issues/issues/6370)
- The Testing module implements a hook that is not invoked by Backdrop [#6350](https://github.com/backdrop/backdrop-issues/issues/6350)

- Pageless Node titles still link to the node page even when access is denied [#5181](https://github.com/backdrop/backdrop-issues/issues/5181)
- Views: exposed filter with autosubmit and AJAX loses keyboard focus [#3166](https://github.com/backdrop/backdrop-issues/issues/3166)

## User Experience changes
- Add "Translate" link to contextual content links [#6410](https://github.com/backdrop/backdrop-issues/issues/6410)
- "Create new revision by default" doesn't seem to enable revisions [#6103](https://github.com/backdrop/backdrop-issues/issues/6103)
- Add the complete file path to the manage file form [#4175](https://github.com/backdrop/backdrop-issues/issues/4175)

## Miscellaneous changes

- Rename default Contact category from "Website feedback" to "General" [#4703](https://github.com/backdrop/backdrop-issues/issues/4703)

**Comment by jenlampton** [comment]
I've updated the issue titles in the notes to match the new names in the milestone.

**Comment by laryn** [comment]
Is the form hardening issue listed here?

**Comment by laryn** [comment]
I updated the Pantheon upstream.

**Comment by klonos** [comment]
1.27.2 and 1.28.0 are out. Closing this.
