### ISSUE TITLE
Backdrop 1.28.0-preview Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6500]
Scheduled for May 2, 2024 10am - 4pm PT

Feature freeze ends _tonight_ May 1, 2024. This is the issue to track the creation of Backdrop 1.28.0-preview, which will come out tomorrow May 2, 2024.

## Pre-release tasks

- [x] Merge commits
- [x] Create a new minor release milestone (@quicksketch)
- [x] Move all unfinished issues to the next minor release milestone (@quicksketch)
- [x] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [ ] Review issues for new features (@stpaultim / @cellear)
  - [ ] Add a conclusion suitable for blog post + release notes
  - [ ] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [ ] Add `Needs change record` label if the the issue contains an API change.
  - [ ] Add `Needs translation` label if the the issue contains string translations.
- [ ] Draft blog post for release on the 15th (assign to stpaultim / tomgrandy / klonos / jenlampton)
- [ ] Draft roadmap updates for backdropcms.org (assign to stpaultim / klonos / jenlampton)
- [ ] Update list of modules included in backdrop core (assign to bugfolder / klonos / jenlampton)
- [ ] Update list of modules included in backdrop_upgrade_status module (assign to jenlampton)
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (e.g. `1.10.0-preview`) (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Note: New incremented branch for development is usually created on release day
- [x] Revert version number back on 1.x branch with the same minor number (e.g. `1.10.x-dev`)  (@quicksketch)
- [x] Create release notes on GitHub **Important: Check "This is a pre-release" checkbox when creating release**  (@quicksketch)

## Post-release Publicity + documentation tasks

- [ ] Tweet that a preview release is out @stpaultim 
- [ ] Publish roadmap updates for backdropcms.org @klonos

**Comment by quicksketch** [comment]
Release notes draft:

---

This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on May 15th, 2024.

This preview release includes several major new features, including a new icon system that bundles the [Phosphor Icon Collection](https://phosphoricons.com/), in both "regular" and "filled" variants. The new icon system is used in the admin bar, dashboard, and admin landing pages. The new icons will start being used throughout core in the next few minor releases. They're also available for contrib developers and themers to use through the new Icon API. Additional documentation and change records are being worked on for the release. In the mean time, see issue [#364](https://github.com/backdrop/backdrop-issues/issues/364).

Uploading SVG images is now supported directly in image field uploads. SVGs also are integrated into the image library and image style systems.

For sites that run on specialized hosting platforms (such as Pantheon, Acquia, or AWS), Backdrop 1.28.0 now allows your site to store configuration in the database instead of on the file system. This may be beneficial on systems where the file system is not as fast or reliable as database access. It also may help work with existing tools for creating backups, as the configuration will be backed up as part of the database instead of needing to be backed-up separately. Initial benchmarking has indicated database configuration is slightly slower than hosting configuration on a local SSD. Performance will vary based on your hosting configuration. More information about converting sites from file configuration to database configuration will be available as we approach the 1.28.0 release.

There are also dozens over other small bugs and user experience issues that are included in this release. See the [1.27.2 milestone](https://github.com/backdrop/backdrop-issues/issues?q=is%3Aissue+milestone%3A1.27.2+is%3Aclosed) for issues that have been fixed in this release that will be bundled into both 1.28.0 and 1.27.2 when they are released.

This release _does_ modify the `settings.php` file located outside the `core` directory. Updating your customized copy of this file is optional. If you would like to update your copy of settings.php to include the new documentation on using different config storage systems, copy the new section on `Configuration Storage` [from the latest version](https://github.com/backdrop/backdrop/blob/1.x/settings.php#L18) to your copy.

No changes have been made to the `.htaccess` or `robots.txt` files. Updating customized versions of those files is not necessary.

## New features
- Add an icon library to core [#364](https://github.com/backdrop/backdrop-issues/issues/364)
- Support uploading and viewing SVGs in the Image Library [#5541](https://github.com/backdrop/backdrop-issues/issues/5541)
- Make config storage swappable (store config in the database) [#2277](https://github.com/backdrop/backdrop-issues/issues/2277)
- Provide an easy way to get ready-to copy/paste debugging information [#5791](https://github.com/backdrop/backdrop-issues/issues/5791)

## Miscellaneous changes
- Editors should have permission to manage files [#4961](https://github.com/backdrop/backdrop-issues/issues/4961)
- Restore theme_node_preview() for theming and compatibility [#6129](https://github.com/backdrop/backdrop-issues/issues/6129)

**Comment by quicksketch** [comment]
Thanks @izmeez. Changes made in the final release notes: https://github.com/backdrop/backdrop/releases/tag/1.28.0-preview

**Comment by quicksketch** [comment]
We're now working on the final release so this issue can be closed. See https://github.com/backdrop/backdrop-issues/issues/6547
