### ISSUE TITLE
Backdrop 1.27.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6546]
Release scheduled for May 15, 2024 4pm PT - 8pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create the next bugfix milestone @quicksketch
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 

## See Also
- [1.28.0 Minor Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6547)

**Comment by jenlampton** [comment]
For notes

## Bug Fixes

- Fixed: JavaScript formatPlural regular expression for '`@count`' not working properly. [#6525](https://github.com/backdrop/backdrop-issues/issues/6525)
- Fix broken link in the layout templates installation success message. [#6474](https://github.com/backdrop/backdrop-issues/issues/6474)
- Fixed: Pasting from Google Docs in CKEditor 5 in Chrome makes everything bold. [#6472](https://github.com/backdrop/backdrop-issues/issues/6472)
- Fixed: All PRs failing `ImageStylesPathAndUrlUnitTest`. [#6459](https://github.com/backdrop/backdrop-issues/issues/6459)
- Fixed: `DatabaseSchema_mysql::fieldExists()` does not escape the column name. [#6450](https://github.com/backdrop/backdrop-issues/issues/6450)
- Fixed: Empty search results gives error re mini pager. [#6437](https://github.com/backdrop/backdrop-issues/issues/6437)
- Fixed: Remove use of constant "LOG_LOCAL0" in `system_update_1017()`. [#6432](https://github.com/backdrop/backdrop-issues/issues/6432)
- Fixed: url filter extended settings are lost when saving the form without changes. [#6431](https://github.com/backdrop/backdrop-issues/issues/6431)
- Fixed: Summary text exists, but is empty when using CKeditor5.  [#6423](https://github.com/backdrop/backdrop-issues/issues/6423)
- Fixed: Nonexistent HTML5Shiv library still being added. [#6419](https://github.com/backdrop/backdrop-issues/issues/6419)
- Fixed: Wrong display of some float values in Views. [#6412](https://github.com/backdrop/backdrop-issues/issues/6412)
- Fixed: Flush the layout cache when switching the node_admin_theme option. [#6374](https://github.com/backdrop/backdrop-issues/issues/6374)
- Fixed: `<` gets encoded to `&lt;` by libxml >v2.9.14, causing broken HTML in generated summaries. [#6327](https://github.com/backdrop/backdrop-issues/issues/6327)
- Fixed: Functional tests: LayoutUpgradePathTest fails too often in GHA. [#6293](https://github.com/backdrop/backdrop-issues/issues/6293)
- Fixed: Fatal error when submit an empty required date field with popup widget. [#6275](https://github.com/backdrop/backdrop-issues/issues/6275)
- Fixed: Remove MySQL 5.0 hacks. [#6120](https://github.com/backdrop/backdrop-issues/issues/6120)
- Fixed: array to string conversion in `views_arg_load()`. [#5869](https://github.com/backdrop/backdrop-issues/issues/5869)
- Fixed: An additional empty value gets saved for Multi-value Long Text fields. [#5153](https://github.com/backdrop/backdrop-issues/issues/5153)


## Documentation updates

- Fixed: Remove missed instance of "white-listed". [#6465](https://github.com/backdrop/backdrop-issues/issues/6465)

## Security Improvements

- [Security] Fixed: Strengthen one-time login links. [#6420](https://github.com/backdrop/backdrop-issues/issues/6420)
- [Security] backdrop_http_request() fails to strip Cookie or Authorization headers on HTTP downgrade [#5963](https://github.com/backdrop/backdrop-issues/issues/5963)

## User Experience Improvements

- Fixed: Reduce Update Status module's red messages on `admin/*` pages. [#5083](https://github.com/backdrop/backdrop-issues/issues/5083)
- Fixed: Add better help text for Date fields. [#4249](https://github.com/backdrop/backdrop-issues/issues/4249)
- Fixed: Set the default value for "Layout template" to what is in use on the default layout. [#6479](https://github.com/backdrop/backdrop-issues/issues/6479)
- Fixed: Do not link an email address if the domain name does not contain a TLD. [#6448](https://github.com/backdrop/backdrop-issues/issues/6448)
- Fixed: Hide the email verification checkbox when only admins can create accounts. [#3170](https://github.com/backdrop/backdrop-issues/issues/3170)
- Fixed: Add a cancel link in the views UI. [#2516](https://github.com/backdrop/backdrop-issues/issues/2516)
- Fixed: Provide views definitions for the `uid` column in the `file_managed` table. [#6440](https://github.com/backdrop/backdrop-issues/issues/6440)
- Fixed: Use consistent styles for details summaries and fieldset legends in Seven theme. [#5509](https://github.com/backdrop/backdrop-issues/issues/5509)


## Miscellaneous changes

- Update Archive_Tar to release 1.5.0. [#6446](https://github.com/backdrop/backdrop-issues/issues/6446)
- Add a JSON delivery callback for Entity Reference autocomplete. [#6486](https://github.com/backdrop/backdrop-issues/issues/6486)
- Add jQuery version usage to telemetry data. [#6537](https://github.com/backdrop/backdrop-issues/issues/6537)
- Add Drupal compatibility layer status to telemetry data. [#6443](https://github.com/backdrop/backdrop-issues/issues/6443)
- Ignore the contents of `core/modules/ckeditor5/lib/ckeditor5` directory for CSpell. [#6536](https://github.com/backdrop/backdrop-issues/issues/6536)
- Ignore the `LICENSE.md` and `LICENSE.txt` files for CSpell [#6530](https://github.com/backdrop/backdrop-issues/issues/6530)

**Comment by jenlampton** [comment]
Release notes are ready for review.

**Comment by klonos** [comment]
Just a quick look for now ...this needs to be removed, as it was closed as a duplicate:
`Ignore the LICENSE.md and LICENSE.txt files for CSpell #6530`

**Comment by quicksketch** [comment]
Thanks @klonos removed and updated.

**Comment by quicksketch** [comment]
Release is out! https://github.com/backdrop/backdrop/releases/tag/1.27.2

We're also working on 1.28.0, it will be out shortly: https://github.com/backdrop/backdrop-issues/issues/6547
