### ISSUE TITLE
Backdrop 1.28.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6547]
Scheduled for May 15, 2024 4pm PT - 8pm PT

## Pre-release tasks

- [x] N/A If this is the Jan 15 release, ensure that the end year in the "All Backdrop code is Copyright..." section towards the bottom of the README.md file has been updated to reflect the new/current year.
- [x] Merge final commits @quicksketch 
- [x] Move all unfinished issues to the next bug-fix release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x`) @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased @quicksketch 
- [x] Revert version number back on new minor number branch @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Create a new language template file for the translation server @olaf - see https://github.com/backdrop-ops/localize.backdropcms.org/issues/27 until this is automated

### Publicity tasks

- [ ] Tweet that a new release is out @stpaultim 
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
- [x] Publish blog post @jenlampton 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @stpaultim 
- [ ] Update the roadmap page on b.org @klonos 
- [x] Update list of modules included in backdrop core @jenlampton 
- [x] Update list of modules included in backdrop_upgrade_status module @ jenlampton
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

### Code tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [ ] Update [Amezmo](https://github.com/sdubois/backdrop-amezmo) @jenlampton 

### Backdrop Website updates

- [ ] beta.backdropcms.org @bugfolder
- [ ] docs.backdropcms.org @jenlampton
- [ ] events.backdropcms.org @jenlampton
- [ ] localize.backdropcms.org @jenlampton

## 2-week Post-release tasks

- [ ] backdropcms.org @jenlampton
- [ ] forum.backdropcms.org @jenlampton

### Publicity tasks

- [ ] Add a notification to the dashboard @stpaultim 
- [ ] Send a newsletter to subscribers @stpaultim 

See Also
---------
* [1.27.2 Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6546)
* [Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6500)

**Comment by jenlampton** [comment]
Release notes draft:

This is the preview release of Backdrop 1.28.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on May 15th, 2024.

This preview release includes several major new features, including a new icon system that bundles the [Phosphor Icon Collection](https://phosphoricons.com/), in both "regular" and "filled" variants. The new icon system is used in the admin bar, dashboard, and admin landing pages. The new icons will start being used throughout core in the next few minor releases. They're also available for contrib developers and themers to use through the new Icon API. Additional documentation and change records are being worked on for the release. In the mean time, see issue [#364](https://github.com/backdrop/backdrop-issues/issues/364).

Uploading SVG images is now supported directly in image field uploads. SVGs also are integrated into the image library and image style systems.

For sites that run on specialized hosting platforms (such as Pantheon, Acquia, or AWS), Backdrop 1.28.0 now allows your site to store configuration in the database instead of on the file system. This may be beneficial on systems where the file system is not as fast or reliable as database access. It also may help work with existing tools for creating backups, as the configuration will be backed up as part of the database instead of needing to be backed-up separately. Initial benchmarking has indicated database configuration is slightly slower than hosting configuration on a local SSD. Performance will vary based on your hosting configuration. More information about converting sites from file configuration to database configuration will be available as we approach the 1.28.0 release.

**Notes for updating**

* **It will be necessary to run the update script** (located at /core/update.php) for this release.
* No changes have been made to the `.htaccess` or `robots.txt` files. Updating customized versions of those files is not necessary.
* This release _does_ modify the `settings.php` file located outside the `core` directory. Updating your customized copy of this file is optional. If you would like to update your copy of settings.php to include the new documentation on using different config storage systems, copy the new section on `Configuration Storage` [from the latest version](https://github.com/backdrop/backdrop/blob/1.x/settings.php#L18) to your copy.


## New features
- Add an icon library to core [#364](https://github.com/backdrop/backdrop-issues/issues/364)
- Support uploading and viewing SVGs in the Image Library [#5541](https://github.com/backdrop/backdrop-issues/issues/5541)
- Make config storage swappable (store config in the database) [#2277](https://github.com/backdrop/backdrop-issues/issues/2277)
- Provide an easy way to get ready-to copy/paste debugging information [#5791](https://github.com/backdrop/backdrop-issues/issues/5791)

## Miscellaneous changes
- Editors should have permission to manage files [#4961](https://github.com/backdrop/backdrop-issues/issues/4961)
- Restore theme_node_preview() for theming and compatibility [#6129](https://github.com/backdrop/backdrop-issues/issues/6129)

**Comment by quicksketch** [comment]
Tag is cut, ready for release: https://github.com/backdrop/backdrop/releases/tag/1.28.0

**Comment by jenlampton** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.28.0 Release out! 🎉

**Comment by jenlampton** [comment]
I've added SVG Image to the list of modules in backdrop core: 
https://docs.backdropcms.org/documentation/features-added-to-core

**Comment by klonos** [comment]
Does our Icon API also count as a partial implementation of https://www.drupal.org/project/icon as well?

**Comment by quicksketch** [comment]
I would say yes. It doesn't provide every possible sub-module (icon_field or icon_filter), but it does provide the API for displaying icons and supporting other icon sets.

**Comment by laryn** [comment]
I've updated the Pantheon upstream.

**Comment by klonos** [comment]
Demo sandboxes have been updated as well. Tested and working too 👍🏼

**Comment by olafgrabienski** [comment]
I've created a new language template file for the translation server.

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop/backdrop-issues/issues/6624
