### ISSUE TITLE
[META] Replace legacy icons with Icon API SVGs

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6548]
I'm copying list list of old or outdated images from [the Icon API issue](https://github.com/backdrop/backdrop-issues/issues/364) so it's not lost when that issue is closed.

## Current icons we can/should replace with new icon font icons

- [ ] #xx | Message icons (Success, Alert, Warning, etc)
- [ ] #xx | Help icon Form API 'help' element
- [ ] #xx | Watchdog message icons
- [ ] #6962 | Contextual link cog icons
- [ ] #xx | Status report page icons
- [ ] #xx | Available updates page icons
- [ ] #xx | RSS feed icon
- [ ] #6493 | Tabledrag icons
- [ ] #6524 | Spinning throbber
- [ ] #6615 | Views UI icons

Places where we should use CSS instead:

- [x] #6779| Table header sort indicators (these could be CSS?)
- [ ] #xx | Menus: collapsed / expanded / leaf / tree (these could be CSS?)
- [ ] #xx |  Dropbutton icons (these could be drawn with CSS?)
- [ ] #6995 | Help icon in filter tips

Completed or unnecessary

- [x] #xx | Admin bar icons
- [x] #xx | Admin "Configuration" page
- [x] #xx | Dashboard
- ~[x] #xx | grippie (could, arguably, be removed)~

**Comment by indigoxela** [comment]
> I could make a PR with my changes to help others, but saw that you are thinking of using CSS instead. How does that work? Do you still want a PR to use SVGs?

Hi @NormPlum :wave:,  I'm not sure, who you'd like to specifically ask, but in general: yes PRs are welcome. You'd create an extra issue for your topic (table headers), and mention this meta issue (and someone would update this issue's description to link back to your issue).

I'm not sure, why this should be CSS. Maybe that's not really decided, yet. :shrug: There are multiple ways to use the [Icon API](https://docs.backdropcms.org/documentation/icon-api). Start with how you think, it should work.

**Comment by NormPlum** [comment]
'Watchdog message icons' is above list is covered by https://github.com/backdrop/backdrop/pull/5126
