### ISSUE TITLE
Backdrop 1.28.1 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6624]
Release scheduled for June 23, 2024 6pm - 8pm PT

## Pre-release tasks

- [x] Merge commits
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone (@quicksketch/@jenlampton)
- [x] Draft Release notes (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks

(@quicksketch)

- [x] Update bootstrap.inc with version number
- [x] Tag for release, and push tag to GitHub
- [x] Revert version number back
- [x] Create release notes on GitHub, and publish release
- [x] Update the front page download link on b.org
- [ ] Tweet that a new release is out (@stpaultim)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.28.1: https://backdropcms.org."

## Immediate Post-release tasks

If this release does NOT accompany a minor release:
- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) (assign to herbdool / jenlampton)
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool (or quicksketch)
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [ ] Update the Wikipedia articles (assign to stpaultim / klonos)
  - [ ] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [ ] backdropcms.org @jenlampton (or bugfolder)
- [ ] beta.backdropcms.org @jenlampton (or bugfolder)
- [ ] docs.backdropcms.org @jenlampton (or bugfolder)
- [ ] events.backdropcms.org @jenlampton (or bugfolder)
- [ ] forum.backdropcms.org @jenlampton (or bugfolder)
- [ ] localize.backdropcms.org @jenlampton (or bugfolder)

**Comment by quicksketch** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**

This release includes changes to `robots.txt`! It is recommended that you copy the new lines from Backdrop core's [robots.txt file](https://github.com/backdrop/backdrop/blob/1.x/robots.txt), or replace the `robots.txt` file with the one from this release if you have made no customizations to that file.

No changes have been made to the `.htaccess` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.

**It will be necessary to run the update script** (located at /core/update.php) for this release.

## User Experience Improvements
- Admin bar: Add an option to move "Add new X" to the bottom of each fly-out menu [#4586](https://github.com/backdrop/backdrop-issues/issues/4586)
- Running cron via the Admin Bar should stay on same page [#3973](https://github.com/backdrop/backdrop-issues/issues/3973)
## Miscellaneous changes
- Indicate what backend is used for config storage in the status page [#6520](https://github.com/backdrop/backdrop-issues/issues/6520)
- Views "Add fields" modal: Split item title/category/description into separate columns, and streamline JS used [#6355](https://github.com/backdrop/backdrop-issues/issues/6355)
- Rephrase "database updates" so that it is clear that they also perform config updates [#5630](https://github.com/backdrop/backdrop-issues/issues/5630)
- Clear the "5 failed login attempts" security message when a user resets their own password [#6425](https://github.com/backdrop/backdrop-issues/issues/6425)

## Bug fixes
- Regression: new way to set font-size and admin bar height cause problems in themes [#6526](https://github.com/backdrop/backdrop-issues/issues/6526)
- `DOMDocument::prepend()` that's used in `image_add_svg_attributes()` does not work on PHP5 or PHP7 [#6577](https://github.com/backdrop/backdrop-issues/issues/6577)
- CKEditor: Creating a node with an inline image does not activate CKEditor 5 [#6591](https://github.com/backdrop/backdrop-issues/issues/6591)
- Customized management menu doesn't get default icons after 1.28 upgrade [#6609](https://github.com/backdrop/backdrop-issues/issues/6609)
- Bartik Theme: Values for header color gradient are not applied [#6606](https://github.com/backdrop/backdrop-issues/issues/6606)
- Views argument handler views_handler_argument_file_type advertised to views in file_views_data() isn't actually defined [#6614](https://github.com/backdrop/backdrop-issues/issues/6614)
- Improve translation of strings within `file_display_form()` [#6581](https://github.com/backdrop/backdrop-issues/issues/6581)
- Remove unnecessary formatter options from `file_display_form()` that display only a link [#6580](https://github.com/backdrop/backdrop-issues/issues/6580)
- Allow more SVG elements in `theme_icon()`. [#6576](https://github.com/backdrop/backdrop-issues/issues/6576)
- Remove use of `element_sort` from core function. [#6565](https://github.com/backdrop/backdrop-issues/issues/6565)
- Update documentation for `MENU_CALLBACK` constant [#6518](https://github.com/backdrop/backdrop-issues/issues/6518)
- Update deprecated jQuery 3.7 methods [#6248](https://github.com/backdrop/backdrop-issues/issues/6248)
- D7 upgrades: Crash due to different column name in url_alias table - `language` vs `langcode` (in specific MySQL/MariaDB versions) [#5496](https://github.com/backdrop/backdrop-issues/issues/5496)

**Comment by quicksketch** [comment]
Release it out https://github.com/backdrop/backdrop/releases/tag/1.28.1!

I updated the homepage of backdropcms.org as well.

**Comment by klonos** [comment]
@quicksketch (or any other @backdrop/core-committers) there's a regression for which I've filed a quick PR in #4809. ...while it's not too late, would it be OK to delete the tag and the release and re-create it, or too late and will have to wait for 1.28.2? (the regression is rather obvious in the admin UI)

**Comment by quicksketch** [comment]
We shouldn't remake the tag or release. If necessary, we can make 1.28.2. But let's continue over in the issue that caused the regression.

**Comment by klonos** [comment]
Tugboat demo images updated 👍🏼 ...however, I cannot update the Wikipedia articles at the moment, as my IP is being blocked 🤷🏼 🤔

**Comment by laryn** [comment]
I've updated the Pantheon upstream to 1.28.1.

**Comment by laryn** [comment]
Closing as outdated.
