### ISSUE TITLE
Backdrop 1.28.2 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6642]
Release scheduled for July 3, 2024 3pm - 5pm PT

## Pre-release tasks

- [x] Merge commits @laryn 
- [x] Create the next bugfix milestone @jenlampton  
- [x] Move all unfinished issues to the next bugfix release milestone @jenlampton  
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
    * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories @jenlampton 

## Release tasks

Assigned to quicksketch / herbdool / laryn / hosef

- [x] Update bootstrap.inc with version number @laryn 
- [x] Tag for release, and push tag to GitHub @laryn
- [x] Revert version number back @laryn
- [x] Create release notes on GitHub, and publish release @jenlampton
- [x] Publish Security Advisories on b.org @klonos 
- [x] Mark the release node on b.org as a security release @klonos 
- [ ] [Request a CVE](https://github.com/backdrop/backdrop-issues/wiki/Security:-Request-CVE) - @jenlampton 
- [x] Update the front page download link on b.org @klonos 
- [ ] Tweet that a new release is out @stpaultim 
  - Use text like "There is a security release out for #BackdropCMS today, please update when you can. Backdrop core - Critical - Third-party libraries - BACKDROP-SA-CORE-2021-001"

## Immediate Post-release tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [x] backdropcms.org @jenlampton 
- [x] beta.backdropcms.org @bugfolder
- [x] docs.backdropcms.org @jenlampton 
- [x] events.backdropcms.org @jenlampton 
- [x] forum.backdropcms.org @jenlampton 
- [x] localize.backdropcms.org @jenlampton 

## See Also

- [Checklist for 1.27.3 release]()

**Comment by jenlampton** [comment]
Release notes draft:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability
- Link to SA @todo 

# Notes for updating
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- **It will be necessary to run the update script** (located at /core/update.php) for this release.

# Other changes since version 1.28.1 are listed below.

## Bug fixes

- Fixed: telemetry_cron should wait for the interval rather than running with every cron run. [#66[32](https://github.com/backdrop/backdrop-issues/actions/runs/9785517098/job/27018695629#step:4:33)](https://github.com/backdrop/backdrop-issues/issues/6632)
- Fixed: Field aliases break the Views "Add Field" functionality. [#6630](https://github.com/backdrop/backdrop-issues/issues/6630)

## User experience improvements
- Restore missing help text from Admin Bar settings. [#6640](https://github.com/backdrop/backdrop-issues/issues/6640)

## Miscellaneous changes

- Add a "Drupal 7 upgrade" state. [#66[33](https://github.com/backdrop/backdrop-issues/actions/runs/9785517098/job/27018695629#step:4:34)](https://github.com/backdrop/backdrop-issues/issues/6633)

**Comment by argiepiano** [comment]
The release notes include a link to the wrong issue. Issue 66 (php 4?) instead of Issue 6632.

**Comment by klonos** [comment]
Thanks for picking that @argiepiano 🙏🏼 ...fixed.

@jenlampton #6640 wasn't a UX improvement - it was a bug (regression) fix. I've amended that.

**Comment by jenlampton** [comment]
I've added a link to the SA into the release notes. Starting on notes for 1.27.3 now :)

**Comment by jenlampton** [comment]
The 1.28.2 release is cut! 🎉 
https://github.com/backdrop/backdrop/releases/tag/1.28.2

**Comment by findlabnet** [comment]
>It will be necessary to run the update script

But I do not see a call for an update.

**Comment by laryn** [comment]
I've updated the Pantheon upstream.

**Comment by klonos** [comment]
> But I do not see a call for an update.

That's correct @findlabnet 👍🏼 ...if I compare https://github.com/backdrop/backdrop/compare/1.28.1...1.28.2 there's no indication of any update hook.

Unfortunately, I do not have edit access for releases, so it will need to be done either by one of our @backdrop/core-committers or @jenlampton.

**Comment by quicksketch** [comment]
@findlabnet Thanks, I fixed the release description!

**Comment by quicksketch** [comment]
Thank you @laryn, @jenlampton, @klonos, and @argiepiano for coordinating today's release!

**Comment by laryn** [comment]
Closing for https://github.com/backdrop/backdrop-issues/issues/6757
