### ISSUE TITLE
Backdrop 1.27.3 Release checklist 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6643]
Release scheduled for July 3, 2024 3pm - 5pm PT

## Pre-release tasks

- [x] Merge commits @laryn 
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
    * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
  - [x] N/A Include a section heading `**Changes since version 1.xx.x** are listed below.`

## Release tasks

- [x] Update bootstrap.inc with version number @laryn 
- [x] Tag for release, and push tag to GitHub @laryn
- [x] Revert version number back @laryn
- [x] Create release notes on GitHub, and publish release @jenlampton
- [x] Mark the release node on b.org as a security release @klonos 

## See Also

- [Checklist for 1.28.2 release](https://github.com/backdrop/backdrop-issues/issues/6642)

**Comment by jenlampton** [comment]
@klonos this is for the 1.27.3 release. I think you are getting this confused with the 1.28.2 issue https://github.com/backdrop/backdrop-issues/issues/6642

**Comment by klonos** [comment]
I'm confusing this with the new milestone 1.28.3 that we'll need to create (to move remaining issues to it). Sorry.

**Comment by jenlampton** [comment]
Release notes draft:
---

Security release for Backdrop CMS. This release fixes 1 security vulnerability:
- [BACKDROP-SA-CORE-2024-001](https://backdropcms.org/security/backdrop-sa-core-2024-001)

## Notes for updating
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- The database update script does **not** need to be run.

**Comment by klonos** [comment]
Notes look good 👍🏼

**Comment by jenlampton** [comment]
The 1.27.3 release is cut! 🎉 
https://github.com/backdrop/backdrop/releases/tag/1.27.3

**Comment by klonos** [comment]
All tasks done here 👍🏼 ...closing.
