### ISSUE TITLE
Backdrop 1.29.0-preview Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6702]
Scheduled for September 3rd, 2024 1pm - 10pm PT

## Pre-release tasks

- [x] Merge commits @quackers8me 
- [x] Create a new minor release milestone @jenlampton 
- [x] Move all unfinished issues to the next minor release milestone @jenlampton 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [ ] Review issues for new features (assign to @jenlampton / @klonos / @cellear)
  - [ ] Add a conclusion suitable for blog post + release notes
  - [x] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [x] Add `Needs change record` label if the the issue contains an API change.
  - [x] N/A Add `Needs translation` label if the the issue contains string translations. - does anyone use this?
- [ ] Draft blog post for release on the 15th @cellear ?
- [ ] Draft roadmap updates for backdropcms.org @klonos 
- [x] N/A? Update list of [modules included in backdrop core](https://docs.backdropcms.org/documentation/features-added-to-core)
- [x] N/A Update list of modules included in backdrop_upgrade_status module @ jenlampton
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (e.g. `1.10.0-preview`)  @quicksketch @herbdool @laryn @hosef
- [x] Tag for release, and push tag to GitHub @quicksketch @herbdool @laryn @hosef
      - Note: New incremented branch for development is usually created on release day
- [x] Revert version number back on 1.x branch with the same minor number (e.g. `1.10.x-dev`) @quicksketch @herbdool @laryn @hosef
- [x] Create release notes on GitHub **Important: Check "This is a pre-release" checkbox when creating release** 

## Website updates (optional)

- [ ] beta.backdropcms.org @bugfolder 

## Post-release Publicity + documentation tasks

- [ ] Tweet that a preview release is out @stpaultim 
- [ ] Publish roadmap updates for backdropcms.org @klonos

**Comment by jenlampton** [comment]
@herbdool @laryn @hosef do any of you want to create the preview release tomorrow? If not we'll leave the window from 1pm-10pm and @quicksketch can do it then :)

**Comment by jenlampton** [comment]
Release notes draft:

---

This is the preview release of Backdrop 1.29.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on September 15th, 2024.

**Notes for updating**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
**It will be necessary to run the update script** (located at /core/update.php) for this release.

**Changes since version 1.28.2** are listed below.

## New features

- Add the ability to install in a specific language. [#6660](https://github.com/backdrop/backdrop-issues/issues/6660)
- Add new file type icon views field handler. [#6588](https://github.com/backdrop/backdrop-issues/issues/6588)
- Add a visibility condition for 200/403/404 response codes. [#6016](https://github.com/backdrop/backdrop-issues/issues/6016)
- Add layout configuration options to the content type admin area. [#2894](https://github.com/backdrop/backdrop-issues/issues/2894)

## Usability Improvements

- Display visibility conditions for menu items on the layout overview page.  [#1929](https://github.com/backdrop/backdrop-issues/issues/1929)

## Miscellaneous changes

- Update jQuery UI to 1.14 [#6677](https://github.com/backdrop/backdrop-issues/issues/6677)
- Update CKEditor 5 to v[42](https://github.com/backdrop/backdrop-issues/actions/runs/10692550812/job/29641177325#step:4:43).0.2 [#6481](https://github.com/backdrop/backdrop-issues/issues/6481)
- Update jquery.ui.touch-punch.js to latest version [#6696](https://github.com/backdrop/backdrop-issues/issues/6696)

**Comment by quicksketch** [comment]
1.29.0 release will be coming out today.
