### ISSUE TITLE
 Backdrop 1.28.3 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6712]
Scheduled for September 15, 2024 4:30pm - 10pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Move all unfinished issues to the next bug-fix release milestone @quicksketch 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Draft Release notes @jenlampton 
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Revert version number back @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] N/A Update the front page download link on b.org 
- [x] N/A Tweet that a new release is out

## Immediate Post-release tasks

See minor release checklist.

## See Also

- [Checklist for 1.29.0 release](https://github.com/backdrop/backdrop-issues/issues/6713)

**Comment by jenlampton** [comment]
Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."

**Notes for updating**

* No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
* The database update script does **not** need to be run.

**Changes since version 1.xx.x**

TBD

**Comment by quicksketch** [comment]
All commits are now in for 1.28.3 and old issues bumped to 1.29.1.

**Comment by quicksketch** [comment]
We're all done here and ready to proceed with 1.29.0 at https://github.com/backdrop/backdrop-issues/issues/6713

**Comment by jenlampton** [comment]
1.28.3 is out https://github.com/backdrop/backdrop/releases/tag/1.28.3
