### ISSUE TITLE
Backdrop 1.29.0 Release checklist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6713]
Scheduled for September 15, 2024 4:30pm - 10pm PT

## Pre-release tasks

- [x] Merge commits @quicksketch 
- [x] Move all unfinished issues to the next bug-fix release milestone @quicksketch 
- [x] Review all closed issues in milestone: @jenlampton 
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone @jenlampton 
- [x] Draft Release notes @jenlampton 
  - [x] Copy Preview release release notes, update as follows
    - [x] Include a short, descriptive summary of the release, for example:
      * The Backdrop community is proud to release version 1.xx of Backdrop CMS, following our 4-month release cycle.
    - [x] Include a section heading `**Notes for updating**`
      - [x] Note if any changes were made to files outside the `core` directory, for example:
        * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
        * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
      - [x] Note if updates (update.php) needs to be run, for example:
        * Use the text `The database update script does **not** need to be run.`
        * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
    - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
      * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.
      * Note: This list can also be copied from the list on the preview release, but review closed issuses in the milestone
    - [x] Verify the list above matches all changes since the most recent bug-fix release

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch 
- [x] Tag for release, and push tag to GitHub @quicksketch 
- [x] Branch for new minor number (e.g. `1.10.x`) and push to GitHub @quicksketch 
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) @quicksketch  
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`) @quicksketch 
- [x] Create release notes on GitHub, and publish release @jenlampton 
- [x] Unpublish preview release on backdropcms.org @jenlampton 
- [x] Update the front page download link on b.org @jenlampton 
- [x] Create a new language template file for the translation server @olafgrabienski 

### Publicity tasks

- [x] Tweet that a new release is out @stpaultim
  * Use text like "We're thrilled to announce Backdrop version 1.18.0. This is the 19th new feature release of #BackdropCMS. https://backdropcms.org"
  - [x] Mastodon post. @stpaultim
  - [x] LinkedIn Post. @stpaultim or @yorkshire-pudding 
  - [x] Facebook Post @stpaultim
- [x] Publish blog post @cellear 
- [ ] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton 
- [ ] Update the roadmap page on b.org @klonos 
- [x] N/A Update list of modules included in backdrop core @jenlampton 
- [x] N/A Update list of modules included in backdrop_upgrade_status module @jenlampton
- [ ] Update the Wikipedia articles @klonos 
  - [ ] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

### Code tasks

- [ ] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [ ] Update [Composer](https://github.com/backdrop-ops/backdrop-composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [ ] Update [Amezmo](https://github.com/sdubois/backdrop-amezmo) @jenlampton
- [ ] Update [DrupalForge](https://github.com/backdrop/backdrop-issues/wiki/Update:-Drupal-Forge-(devpanel)-Template) @izmeez

### Backdrop Website updates

- [ ] beta.backdropcms.org @bugfolder 
- [x] docs.backdropcms.org @jenlampton
- [x] events.backdropcms.org @jenlampton
- [x] localize.backdropcms.org @jenlampton

## 2-week Post-release tasks (Sept 30th)

- [ ] backdropcms.org @jenlampton
- [ ] forum.backdropcms.org @jenlampton
Note for forum, after deploy also disable + uninstall `X Autoload` and `Libraries` modules

### Publicity tasks

- [x] Add a notification to the dashboard @stpaultim 
- [x] Send a newsletter to subscribers @stpaultim @bugfolder 

See Also
---------
* [Bug-Fix Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6712)
* [Preview Release Checklist](https://github.com/backdrop/backdrop-issues/issues/6702)

**Comment by jenlampton** [comment]
Release notes draft:

---

The Backdrop community is proud to release version 1.29 of Backdrop CMS, following our 4-month release cycle.

**Notes for updating**

- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- **It will be necessary to run the update script** (located at `/core/update.php`) for this release.

**Changes since version 1.28.3** are listed below.

## New features

- Automatically download translation files at install time. [#6660](https://github.com/backdrop/backdrop-issues/issues/6660)
- Add layout configuration options to the content type admin area. [#2894](https://github.com/backdrop/backdrop-issues/issues/2894)
- Add a visibility condition for 200/403/404 response codes. [#6016](https://github.com/backdrop/backdrop-issues/issues/6016)
- Add new file type icon views field handler. [#6588](https://github.com/backdrop/backdrop-issues/issues/6588)

## Usability Improvements

- Display conditions for menu items on the layout overview page.  [#1929](https://github.com/backdrop/backdrop-issues/issues/1929)

## Miscellaneous changes

- Update jQuery UI to 1.14 [#6677](https://github.com/backdrop/backdrop-issues/issues/6677)
- Update CKEditor 5 to v42.0.2 [#6481](https://github.com/backdrop/backdrop-issues/issues/6481)
- Update jquery.ui.touch-punch.js to latest version [#6696](https://github.com/backdrop/backdrop-issues/issues/6696)

**Comment by jenlampton** [comment]
I'm really tired, so I'm going to wait till tomorrow to start updating sites.

**Comment by jenlampton** [comment]
@izmeez thank you so much for volunteering to maintain that :) I've [added a new checkbox](https://github.com/backdrop/backdrop-issues/commit/fe52c706435181be53b84c95f99045f042edd340) for all release templates.

**Comment by olafgrabienski** [comment]
I've created a new language template file for the [translation server](https://localize.backdropcms.org).

**Comment by laryn** [comment]
I've updated the Pantheon upstream.

**Comment by stpaultim** [comment]
@jenlampton Where is the template for this checklist (or do you just copy from previous release?)?

I added some checkbox for other social media outlets, would like to get them in the template.

**Comment by jenlampton** [comment]
@stpaultim all the templates for these issues are in this `backdrop-issues` repo:
https://github.com/backdrop/backdrop-issues/tree/main/templates

**Comment by laryn** [comment]
Closing for https://github.com/backdrop/backdrop-issues/issues/6757
