### ISSUE TITLE
Backdrop 1.29.1 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6726]
Release scheduled for October 6, 2024 4pm - 8pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [ ] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone  (@quicksketch)
- [x] Draft Release notes  (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only."
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
      * Note: you can use this command to see if any install files were changed:
      `ls -1 core/modules/*/*.install | while read filename; do echo "$(git log -1 --pretty="format:%ad %f" --date=format:"%F %R" -- $filename)" $filename; done|sort`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.

## Release tasks

- [x] Update bootstrap.inc with version number  (@quicksketch)
- [x] Tag for release, and push tag to GitHub  (@quicksketch)
- [x] Revert version number back  (@quicksketch)
- [x] Create release notes on GitHub, and publish release  (@quicksketch)
- [x] Update the front page download link on b.org  (@quicksketch)
- [ ] Tweet that a new release is out (@stpaultim)
  - Use text like "There is a bug-fix release out for #BackdropCMS today, version 1.27.2: https://backdropcms.org."

## Immediate Post-release tasks

- [x] Update [Tugboat](https://github.com/backdrop/backdrop-issues/wiki/Update:-Tugboat) @klonos
- [ ] Update [Composer](https://github.com/backdrop/backdrop-issues/wiki/Update:-Composer) @herbdool
- [ ] Update [Docker](https://github.com/backdrop/backdrop-issues/wiki/Update:-Docker-Image) @wylbur
- [x] Update [Pantheon](https://github.com/backdrop/backdrop-issues/wiki/Update:-Pantheon-Upstream) @herbdool
- [ ] Update [Platform.sh](https://github.com/backdrop/backdrop-issues/wiki/Update:-Platform.sh-Template) @herbdool
- [ ] Update [Amezmo](https://github.com/backdrop/backdrop-issues/wiki/Update:-Amezmo) @jenlampton
- [x] Update [DrupalForge](https://github.com/backdrop/backdrop-issues/wiki/Update:-Drupal-Forge-(devpanel)-Template) @izmeez
- [ ] Update the Wikipedia articles @klonos
  - [ ] https://en.wikipedia.org/w/index.php?title=Template:BackdropCMS_version&action=edit - 
    * Auto applied to:
      * https://en.wikipedia.org/wiki/Backdrop_CMS
      * https://en.wikipedia.org/wiki/List_of_content_management_systems

## Backdrop's Website updates

- [ ] backdropcms.org @jenlampton (or bugfolder)
- [ ] beta.backdropcms.org @bugfolder (or jenlampton)
- [ ] docs.backdropcms.org @jenlampton (or bugfolder)
- [ ] events.backdropcms.org @jenlampton (or bugfolder)
- [ ] forum.backdropcms.org @jenlampton (or bugfolder)
- [ ] localize.backdropcms.org @jenlampton (or bugfolder)

**Comment by quicksketch** [comment]
Release notes draft:

---

Maintenance release for Backdrop CMS. This update contains bug fixes and usability improvements only.

**Notes for updating**

* The default `.htaccess` file has been modified for clarity. It functionally identical, but site owners may optionally choose to update their `.htaccess` files for consistency with core. See [#6646](https://github.com/backdrop/backdrop-issues/issues/6646).
* No changes have been made to the `robots.txt` or the default `settings.php` file in this release. Updating customized versions of those files is not necessary.
* The database update script **does** need to be run.

**Changes since version 1.29.0**

## Bug fixes

- Automatic translation downloading not available during installation [#6717](https://github.com/backdrop/backdrop-issues/issues/6717)
- After upgrading from D7 two internal search menu links lose their parents resulting in wrong page titles [#5674](https://github.com/backdrop/backdrop-issues/issues/5674)
- Fix watchdog string typo in views_plugin_display::init() [#6721](https://github.com/backdrop/backdrop-issues/issues/6721)

## Miscellaneous changes

- Change the cryptic value of `A1209600` for `ExpiresDefault` to a human-readable one in `.htaccess` [#6646](https://github.com/backdrop/backdrop-issues/issues/6646)

**Comment by quicksketch** [comment]
The new release is now out!

https://github.com/backdrop/backdrop/releases/tag/1.29.1

**Comment by laryn** [comment]
Closing for https://github.com/backdrop/backdrop-issues/issues/6757
