### ISSUE TITLE
Backdrop 1.28.4 Release checklist

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6756]
Release scheduled for November 20, 2024 10am - 4pm PT

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [x] Review all closed issues in milestone: (@jenlampton)
  * Issue titles should include a complete, but very brief summary of the problem.
  * Issue titles should be in complete sentences, ending with a period.
  * Bug issue titles should start with `Fix` or `Fixed`,
  * New feature issue titles should start with `Add` or `Added`.
  * Each issue should have accurate labels, especially the "type - " labels.
- [x] Close the milestone  (@quicksketch)
- [x] Draft Release notes  (@quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    * "Security release for Backdrop CMS. This release fixes 1 security vulnerability:"
    * Include a list of SA's for commits to this release
  - [x] Include a section heading `**Notes for updating**`
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * ``- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.``
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.18.0) for updates to `.htaccess`
      * See [this example](https://github.com/backdrop/backdrop/releases/tag/1.16.0) or [this example](https://github.com/backdrop/backdrop/releases/tag/1.14.0) for updates to `settings.php`
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text `The database update script does **not** need to be run.`
      * or `**It will be necessary to run the update script** (located at /core/update.php) for this release.`
      * Note: you can use this command to see if any install files were changed:
      `ls -1 core/modules/*/*.install | while read filename; do echo "$(git log -1 --pretty="format:%ad %f" --date=format:"%F %R" -- $filename)" $filename; done|sort`
  - [x] Include a section heading `**Changes since version 1.xx.x** are listed below.`
    * Navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
    * Select the most recent time "Release Notes Generator" has been run.
    * Download the `release-notes` artifact attached to the generator.
    * Unzip the file, and copy/pate contents into release notes draft.
    * Remove any square brackets in the titles, and move those issues to their own section.
- [x] Draft Security Advisories  (@jenlampton)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub, and publish release  (@quicksketch)
- [x] Publish Security Advisories on b.org (@jenlampton)
- [x] Mark the release node on b.org as a security release (@quicksketch)
- [ ] [Request a CVE](https://github.com/backdrop/backdrop-issues/wiki/Security:-Request-CVE) - (@jenlampton)

## See Also

- [Checklist for 1.29.2 release]()

**Comment by quicksketch** [comment]
Release notes draft:

---

Security release for Backdrop CMS. This release fixes 2 security vulnerabilities:

- [BACKDROP-SA-CORE-2024-002](https://backdropcms.org/security/backdrop-sa-core-2024-002)
- [BACKDROP-SA-CORE-2024-002](https://backdropcms.org/security/backdrop-sa-core-2024-003)

## Notes for updating
- No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
- It is not necessary to run the update script (located at /core/update.php) for this release.

This release contains the security fixes only and no other changes.

---

**Comment by quicksketch** [comment]
The tag is cut for 1.28.4: https://github.com/backdrop/backdrop/releases/tag/1.28.4

This is ready for release once we also have the 1.29.2 release ready. See https://github.com/backdrop/backdrop-issues/issues/6757

**Comment by jenlampton** [comment]
All tasks complete, closing.
