### ISSUE TITLE
[META] Port Drupal 7.36 Issues to Backdrop

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#843]
Drupal 7.36 came out yesterday and includes a fair number of fixes. We should do a git log and check the history since 7.35 and ensure we have all the applicable changes. This is the first bug fixing release of Drupal in a few months I believe. Let's use this issue as a meta list.

Drupal 7.36 release notes are at https://www.drupal.org/drupal-7.36-release-notes.
- [x] <a href="https://www.drupal.org/node/2305017">#2305017</a>&nbsp;by David_Rothstein, slashrsm, marcingy: Add a &#39;file_public_schema&#39; variable to allow bypassing file download access checks in managed file upload fields
- [x] <a href="https://www.drupal.org/node/1946240">#1946240</a>&nbsp;by hampercm, eiriksm, David_Rothstein, rpayanm, rszrama, Yaron Tal, dgtlife, madhusudanmca, er.pushpinderrana, Cottser: Remove the hardcoded 0 index in theme_status_messages()
- [x] <a href="https://www.drupal.org/node/2432619">#2432619</a>&nbsp;by vbouchet, jhodgdon, joachim: block_load() should state it&#39;s not suitable for general consumption | N/A
- [x] <a href="https://www.drupal.org/node/1201452">#1201452</a>&nbsp;by mgifford, Heine, ircmaxell: Improve security on newer versions of PHP by setting an additional charset DSN parameter when connecting to MySQL via PDO | https://github.com/backdrop/backdrop/pull/807
- [x] <a href="https://www.drupal.org/node/1828530">#1828530</a>&nbsp;by cam8001: Remove unused $default_method variable in user_cancel_confirm_form() | N/A
- [x] <a href="https://www.drupal.org/node/2386037">#2386037</a>&nbsp;by gobinathm: Incorrect foreign key tables in users.install | N/A
- [x] <a href="https://www.drupal.org/node/2462223">#2462223</a>&nbsp;by helmo: Typo in comment in node_access_test.module
- [x] <a href="https://www.drupal.org/node/2283717">#2283717</a>&nbsp;by joshi.rohit100, amitgoyal, g3r4, er.pushpinderrana: Remove user_access function calls on hook_permission functions so the Permissions page consistently links to other admin pages for all users | https://github.com/backdrop/backdrop/pull/813
- [x] <a href="https://www.drupal.org/node/1018618">#1018618</a>&nbsp;by manfer, joshi.rohit100: Wrong assertions in block.test
- [x] <a href="https://www.drupal.org/node/2453321">#2453321</a>&nbsp;by TravisCarden: Typo in @see reference: drupal_decode_exception() should be _drupal_decode_exception()
- [x] <a href="https://www.drupal.org/node/2453311">#2453311</a>&nbsp;by TravisCarden: Fix a couple more &quot;the the&quot;s in the codebase
- [x] <a href="https://www.drupal.org/node/713462">#713462</a>&nbsp;by jwilson3, Paul B, casey,&nbsp;<a href="mailto:sivaji@knackforge.com">sivaji@knackforge.com</a>, dcam: Content added via drupal_add_region_content() is not added to pages | N/A
- [x] <a href="https://www.drupal.org/node/1934498">#1934498</a>&nbsp;by attiks, David_Rothstein, KhaledBlah, tstoeckler, julien_acti, helmo, effulgentsia, Jelle_S, jcisio: Allow the image style &#39;itok&#39; token to be suppressed in image derivative URLs | #34
- [x] <a href="https://www.drupal.org/node/1441950">#1441950</a>&nbsp;by hefox: Node types removed from hook_node_info with base = &#39;node_content&#39; cannot be deleted | N/A
- [x] <a href="https://www.drupal.org/node/1883058">#1883058</a>&nbsp;by cilefen, aendrew: Default Drupal &quot;drop&quot; favicon needs a retina-quality version | N/A
- [x] <a href="https://www.drupal.org/node/2342243">#2342243</a>&nbsp;by martin107, serundeputy: Rename a variable in theme_system_modules_fieldset() to avoid colliding index variable names in a nested foreach loop
- [x] <a href="https://www.drupal.org/node/2371759">#2371759</a>&nbsp;by Valentine94, angel.angelio: The docblock for user_help() should read &quot;Implements hook_help().&quot; | N/A
- [x] <a href="https://www.drupal.org/node/2428915">#2428915</a>&nbsp;by pfrenssen: Remove mention of non-existing function in conf_path() documentation | N/A
- [x] <a href="https://www.drupal.org/node/779482">#779482</a>&nbsp;by mikeytown2, sun, dalin, cam8001, segi, alexpott, Boobaa, Sweetchuck, jbrown, quicksketch: Installation failure when opcode cache is enabled | #579
- [x] <a href="https://www.drupal.org/node/2170453">#2170453</a>&nbsp;by Darren Oh, mikeryan, Fabianx: Ignore case in code registry lookups | N/A
- [x] <a href="https://www.drupal.org/node/1404050">#1404050</a>&nbsp;by JamesOakley, David_Rothstein: system_update_7061 breaks private files by leaving one too many forward slashes in protocol of migrated URIs | N/A
- [x] <a href="https://www.drupal.org/node/1882774">#1882774</a>&nbsp;by David_Rothstein, iva2k: User pictures are lost when system_update_7061 merges files into {file_managed}. | N/A
- [x] <a href="https://www.drupal.org/node/2293767">#2293767</a>&nbsp;by tstoeckler: Allow PSR-4 test classes to be used in Drupal 7. | N/A
- [x] <a href="https://www.drupal.org/node/1904528">#1904528</a>&nbsp;by Heine, GoddamnNoise: Language switcher (User interface text) Block generates invalid XHTML+RDFa 1.0
  - moot?
- [x] <a href="https://www.drupal.org/node/1081902">#1081902</a>&nbsp;by zealfire: DrupalEntityControllerInterface::load - doc needs to clarify $conditions
  - Has [PR](https://github.com/backdrop/backdrop/pull/867)
- [x] <a href="https://www.drupal.org/node/2407175">#2407175</a>&nbsp;by zealfire: Documentation error in default.settings.php | N/A
- [x] <a href="https://www.drupal.org/node/2392543">#2392543</a>&nbsp;by awm: Fix documentation for hook_taxonomy_term_view_alter
  - @serundeputy thinks this is `moot`; if someone can confirm check it off list.
- [x] <a href="https://www.drupal.org/node/2411227">#2411227</a>&nbsp;by chx: Remove chx from the Drupal 7 MAINTAINERS.txt file. | N/A
- [x] <a href="https://www.drupal.org/node/2377879">#2377879</a>&nbsp;by er.pushpinderrana, yakoub: hook_user_view documentation has incorrect piece
  - has `PR`
- [x] <a href="https://www.drupal.org/node/2382801">#2382801</a>&nbsp;by er.pushpinderrana, Liam Morland: Improve documentation for module_exists()
- [x] <a href="https://www.drupal.org/node/2383491">#2383491</a>&nbsp;by er.pushpinderrana, Sweetchuck: Inaccurate documentation - hook_image_toolkits()
- [x] <a href="https://www.drupal.org/node/2380143">#2380143</a>&nbsp;by Lendude, pwolanin: Contact forms set an incorrect name and e-mail address on the global user object after the form is submitted.

**Comment by serundeputy** [comment]
- [x] [#2342243] (https://www.drupal.org/node/2342243)  ~ I believe is all set; I only see one instance of `theme_system_modules_fieldset()` and there is no nested foreach in that function in `system.theme.inc`

**Comment by serundeputy** [comment]
- [ ] [#1201452] (https://www.drupal.org/node/1201452) does not seem to be accounted for.  Make a new branch and submit PR?

**Comment by docwilmot** [comment]
Added list as checkbox list

**Comment by quicksketch** [comment]
> #1201452 does not seem to be accounted for. Make a new branch and submit PR?

Sure, we can port it right away or wait for 7.37 (or whatever bug fix version is next) to incorporate it in another meta like this one.

**Comment by serundeputy** [comment]
- [ ] #2386037 by gobinathm: Incorrect foreign key tables in users.install
Looks like backdrop does not have a `role` table, but rather a `users_roles` and schema seems fine in `user.install`
@quicksketch / @docwilmot / @jenlampton  can someone confirm #2386037 is moot for backdrop?

**Comment by serundeputy** [comment]
- [ ] #2371759 by Valentine94, angel.angelio: The docblock for user_help() should read "Implements hook_help()."

I see no instance of `user_help()` in `user.module` or in `backdrop/`.  
I believe #231759 is moot for backdrop.  Can anyone confirm and check the boxes?

**Comment by quicksketch** [comment]
>  I believe #231759 is moot for backdrop. Can anyone confirm and check the boxes?

Yes, moot. We don't have hook_help() in Backdrop. :smile:

> #2386037 by gobinathm: Incorrect foreign key tables in users.install Looks like backdrop does not have a role table

Yep, also moot. Our roles are managed in config, so we have no role table.

**Comment by serundeputy** [comment]
- [ ] #2283717 by joshi.rohit100, amitgoyal, g3r4, er.pushpinderrana: Remove user_access function calls on hook_permission functions so the Permissions page consistently links to other admin pages for all users

PR: https://github.com/backdrop/backdrop/pull/813 ; 
- [x] Travis passed.

**Comment by serundeputy** [comment]
- [ ] #1946240 by hampercm, eiriksm, David_Rothstein, rpayanm, rszrama, Yaron Tal, dgtlife, madhusudanmca, er.pushpinderrana, Cottser: Remove the hardcoded 0 index in theme_status_messages()

PR: https://github.com/backdrop/backdrop/pull/820

- [x] Travis passed.

**Comment by pablo-romero** [comment]
- [ ] #2462223 by helmo: Typo in comment in node_access_test.module

Has PR: backdrop/backdrop#821

Also, this one does not apply to Backdrop:
- [ ] #2411227 by chx: Remove chx from the Drupal 7 MAINTAINERS.txt file.

**Comment by serundeputy** [comment]
- [ ] #2305017 by David_Rothstein, slashrsm, marcingy: Add a 'file_public_schema' variable to allow bypassing file download access checks in managed file upload fields

PR: https://github.com/backdrop/backdrop/pull/824
  - [ ] Travis passed.

This works a bit differently in backdrop, but the OP on the dupal issue #2305017 was a reproducible bug; I believe the PR allows for the editing of taxonomy terms with image fields to retain the image.

**Comment by pablo-romero** [comment]
- [ ] Issue #843: Drupal 7.36 meta #1018618 by manfer, joshi.rohit100: Wrong assertions in block.test

PR: backdrop/backdrop#827

**Comment by pablo-romero** [comment]
- [ ] #2453321 by TravisCarden: Typo in @see reference: drupal_decode_exception() should be _drupal_decode_exception()

Also checked this one, and it's already fixed in Backdrop.

**Comment by serundeputy** [comment]
- [ ] #1018618 by manfer, joshi.rohit100: Wrong assertions in block.test
  PR: https://github.com/backdrop/backdrop/pull/832

- [ ] Travis passed.

**Comment by quicksketch** [comment]
Thanks guys! @serundeputy, that last PR (https://github.com/backdrop/backdrop/pull/832) overlapped with @pablo-romero's PR (https://github.com/backdrop/backdrop/pull/827), so that's why it's closed and not showing as merged.

**Comment by serundeputy** [comment]
(thumbsup);

**Comment by pablo-romero** [comment]
- [ ] #2382801 by er.pushpinderrana, Liam Morland: Improve documentation for module_exists()

PR: backdrop/backdrop#836

**Comment by pablo-romero** [comment]
- [ ] #2383491 by er.pushpinderrana, Sweetchuck: Inaccurate documentation - hook_image_toolkits()

PR: backdrop/backdrop#845

**Comment by serundeputy** [comment]
- [ ] #2380143 by Lendude, pwolanin: Contact forms set an incorrect name and e-mail address on the global user object after the form is submitted.

PR: https://github.com/backdrop/backdrop/pull/847

- [ ] Travis passed.

**Comment by quicksketch** [comment]
I marked a few more issues N/A.

>  #1883058 by cilefen, aendrew: Default Drupal "drop" favicon needs a retina-quality version

For those curious, [our favicon](https://raw.githubusercontent.com/backdrop/backdrop/1.x/core/misc/favicon.ico) includes 16x16, 32x32, and 64x64 pixel varieties. :smile:

**Comment by pablo-romero** [comment]
- [ ] #2453311 by TravisCarden: Fix a couple more "the the"s in the codebase

PR: backdrop/backdrop#849

**Comment by serundeputy** [comment]
- [ ]  #2377879 by er.pushpinderrana, yakoub: hook_user_view documentation has incorrect piece

PR: https://github.com/backdrop/backdrop/pull/860

**Comment by serundeputy** [comment]
- [ ] #2392543 by awm: Fix documentation for hook_taxonomy_term_view_alter

Mooty moot; someone confirm and check the box here and in OP list please.
lines 259 to 261 in `taxonomy.api.php`
```php
 *
 * @param $build
 *   A renderable array representing the taxonomy term content.
```

**Comment by serundeputy** [comment]
#2208649 by joachim, er.pushpinderrana: document queue worker callback
This one was committed, but then directly followed by an - oops - https://www.drupal.org/node/2208649#comment-9396989https://www.drupal.org/node/2208649#comment-9396989

Does Backdrop wait for the final or work with the committed patch?

**Comment by quicksketch** [comment]
> This one was committed, but then directly followed by an - oops

We usually wait for the final version if necessary, especially if the "oops" caused regressions. If it gets messy and we need a chain of patches, it's best to separate out that into it's own issue.

**Comment by pablo-romero** [comment]
- [ ] #1081902 by zealfire: DrupalEntityControllerInterface::load - doc needs to clarify $conditions

This one is now in Entity module.

PR: backdrop/backdrop#867

**Comment by pablo-romero** [comment]
- [ ] #1904528 by Heine, GoddamnNoise: Language switcher (User interface text) Block generates invalid XHTML+RDFa 1.0

I've also been checking out this one and I think we should not apply it, since Bartik is already using HTML in BD (not XHTML) and RDF Module is gone.

**Comment by pablo-romero** [comment]
@serundeputy:

I've taken a look into **#1734716**. In Drupal, `$element['#id'] . '-ajax-wrapper'` is replaced with `$original_id . '-ajax-wrapper'`. Note that `$original_id` is added/declared above:

```php
// Append the '-upload' to the #id so the field label's 'for' attribute
// corresponds with the file element.
$original_id = $element['#id'];
$element['#id'] .= '-upload';
```

This is done to make the ID of the element include the *-upload* suffix (for accessibility). Since `$element['#id']` now includes the `'-upload'` part, you also need to change:
```php
$element['#id'] . '-upload' => $extension_list
```
to:
```php
$element['#id'] => $extension_list
```
(to avoid iteration *-upload-upload*).

It looks like a good addition to me, maybe someone else can confirm.

**Comment by pablo-romero** [comment]
- [ ] #2439287 by jmsv23, jonathan_hunt: Fix typo in inline docs for field_sql_storage_field_storage_write().

PR: backdrop/backdrop#873

**Comment by pablo-romero** [comment]
- [ ] #495930 by fietserwin: Translated strings not correctly marked in the administrative interface when the default language is not English

This one might also be related to #886. However, some of the changes are now affected by the new *Translate English* feature in Backdrop (conditional `if (!locale_translate_english())`).

Sent a PR so that you can check it out: backdrop/backdrop#874

**Comment by jenlampton** [comment]
I'm a little confused on the status of things here.  Are all the issues with [x] already merged into Backdrop?

**Comment by quicksketch** [comment]
Yes, I've been checking boxes as they get merged in. Sorry the cross-linking between PRs and the checkboxes isn't great.

**Comment by jenlampton** [comment]
I'm going to go through and pull out the remaining issues that have not yet been merged, and add them to https://github.com/backdrop/backdrop-issues/issues/918 so we can close this issue.

**Comment by jenlampton** [comment]
Okay, all remaining commits from this issue moved to https://github.com/backdrop/backdrop-issues/issues/918.
