### ISSUE TITLE
[META] Port Drupal 7.36 and 7.37 issues to Backdrop

### ISSUE THREAD

**Issue by pablo-romero** [backdrop/backdrop-issues#918]
## Remaining issues from Drupal 7.36
- [x] | N/A | [de8762b](http://drupalcode.org/project/drupal.git/commit/de8762b201863542b1867737997a45c7100b8f2f) | [Issue #2380143 by Lendude, pwolanin: Contact forms set an incorrect name and e-mail address on the global user object after the form is submitted.](http://drupal.org/node/2380143)
- [x] | https://github.com/backdrop/backdrop/pull/905 | [76e3d53](http://drupalcode.org/project/drupal.git/commit/76e3d53c1f55564e3d01d6a3b5f3d2d5550ee858) | [Issue #2208649 by joachim, er.pushpinderrana: document queue worker callback](http://drupal.org/node/2208649)
- [x] | N/A | [f1e15c1](http://drupalcode.org/project/drupal.git/commit/f1e15c1d6579f5d656b5792746b230a67e533168) | [Issue #2411227 by chx: Remove chx from the Drupal 7 MAINTAINERS.txt file.](http://drupal.org/node/2411227)
- [x] | N/A | [dc36565](http://drupalcode.org/project/drupal.git/commit/dc3656528f68188e996826ca79c6415e0e38df64) | [Issue #2392543 by awm: Fix documentation for hook_taxonomy_term_view_alter](http://drupal.org/node/2392543)
- [x] | N/A | [4d1840e](http://drupalcode.org/project/drupal.git/commit/4d1840e620bfb6e619c0cdd05e61e8a25252f491) | [Issue #2407175 by zealfire: Documentation error in default.settings.php](http://drupal.org/node/2407175)
- [x] | https://github.com/backdrop/backdrop/pull/905 | [26d794f](http://drupalcode.org/project/drupal.git/commit/26d794fac95c9bfbdffe24cd9028d7e338717159) | [Issue #1904528 by Heine, GoddamnNoise: Language switcher (User interface text) Block generates invalid XHTML+RDFa 1.0](http://drupal.org/node/1904528)
- [x] | https://github.com/backdrop/backdrop/pull/905 | [c202196](http://drupalcode.org/project/drupal.git/commit/c202196bbb677d36d4244e0eaa3ca2ab223b024f) | [Issue #2439287 by jmsv23, jonathan_hunt: Fix typo in inline docs for field_sql_storage_field_storage_write().](http://drupal.org/node/2439287)
- [x] | https://github.com/backdrop/backdrop/pull/905 | [ac0f69f](http://drupalcode.org/project/drupal.git/commit/ac0f69f1dab60057909a8091a522afbdc7c86910) | [Issue #1303412 by nod_, droplet, Valentine94, KarenS, sahuni: Cannot drag in or out of 'Hidden' on the 'Manage Display' page under certain circumstances](http://drupal.org/node/1303412)
- [x] | N/A | [2ace190](http://drupalcode.org/project/drupal.git/commit/2ace1905b59b779a87e3ad1a125d5bb52193aa61) | [Issue #1882774 by David_Rothstein, iva2k: User pictures are lost when system_update_7061 merges files into {file_managed}.](http://drupal.org/node/1882774)
- [x] | N/A | [9dafd62](http://drupalcode.org/project/drupal.git/commit/9dafd622f00485a1889bfd22bcf1291e2aed647b) | [Issue #1404050 by JamesOakley, David_Rothstein: system_update_7061 breaks private files by leaving one too many forward slashes in protocol of migrated URIs](http://drupal.org/node/1404050)
- [x] | N/A | [be97f50](http://drupalcode.org/project/drupal.git/commit/be97f50fba4c7c87b4332d30cf8e0f612b89bdb5) | [Issue #779482 by mikeytown2, sun, dalin, cam8001, segi, alexpott, Boobaa, Sweetchuck, jbrown, quicksketch: Installation failure when opcode cache is enabled](http://drupal.org/node/779482)
- [x] | https://github.com/backdrop/backdrop/pull/905 | [5a17a54](http://drupalcode.org/project/drupal.git/commit/5a17a54c48e59a2798dd68a8d1e939149523dab9) | [Issue #2394517 by opdavies: Add a function to check if a user has a certain role](http://drupal.org/node/2394517)
- [x] | N/A | [b386d92](http://drupalcode.org/project/drupal.git/commit/b386d9211922a466485ba2e2ac83bbce2d3f7db5) | [Issue #2371759 by Valentine94, angel.angelio: The docblock for user_help() should read "Implements hook_help()."](http://drupal.org/node/2371759)
- [x] | N/A | [cedcc04](http://drupalcode.org/project/drupal.git/commit/cedcc04cf8d0432e8a57f3d965a604601252af5f) | [Issue #2342243 by martin107, serundeputy: Rename a variable in theme_system_modules_fieldset() to avoid colliding index variable names in a nested foreach loop](http://drupal.org/node/2342243)
- [x] | N/A | [d67fd28](http://drupalcode.org/project/drupal.git/commit/d67fd28f14c9a5e4e596a75749b4e6fb4c80da3d) | [Issue #1441950 by hefox: Node types removed from hook_node_info with base = 'node_content' cannot be deleted](http://drupal.org/node/1441950)
- [x] | N/A | [c0f687e](http://drupalcode.org/project/drupal.git/commit/c0f687ed41e2bd171b422485ef2362eddb2ce918) | [Issue #2001308 by stefan.r, David_Rothstein, marthinal, helmo: Node preview removes file values from node edit form for non-displayed items](http://drupal.org/node/2001308)

The command for generating this list was: 
`git log b44056d2.. --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"`
## Drupal 7.37
- [x] | https://github.com/backdrop/backdrop/pull/919 | [8f08dc9](http://drupalcode.org/project/drupal.git/commit/8f08dc9d13f43651fc8c298253891036c2ea8e8f) | [Issue #2392221 by joegraduate, er.pushpinderrana, zealfire, ClientGuy: install_run_task() and install_tasks() don't document the task structure](http://drupal.org/node/2392221)
- [x] | https://github.com/backdrop/backdrop/pull/920 | [e091df1](http://drupalcode.org/project/drupal.git/commit/e091df1aa7cfa5341984f3dc323610053e73fa88) | [Issue #1684930 by amontero, David_Rothstein, joshi.rohit100, jthorson, dcam, rpayanm, jackbravo, yoroy: Add description to "administer filters" permission](http://drupal.org/node/1684930)
- [x] | See https://github.com/backdrop/backdrop-issues/issues/159 | [2a3cf92](http://drupalcode.org/project/drupal.git/commit/2a3cf926af6259f85096b83522fbb890f51eb0fa) | [Issue #667058 by greggles, DamienMcKenna, cweagans, travelertt, Dave Reid, tstoeckler, geerlingguy: Add a sites/all/libraries folder and encourage people to use it properly](http://drupal.org/node/667058)
- [x] | https://github.com/backdrop/backdrop/pull/922 | [39762b7](http://drupalcode.org/project/drupal.git/commit/39762b7135c10cd392061cafba504c2e7d8e2a3d) | [Issue #2356983 by bzrudi71, Dave Reid, jaredsmith: SystemQueue::claimItem() sometimes returns items in the wrong order (resolves locale test failures on PostgreSQL)](http://drupal.org/node/2356983)
- [x] | https://github.com/backdrop/backdrop/pull/924 | [00e7efc](http://drupalcode.org/project/drupal.git/commit/00e7efc01bcd6d5698bc2faabc1003bc5dd999b4) | [Issue #2014851 by hlieberman, Wim Leers, bradjones1, markcarver: Drupal CSS preprocessing breaks protocol-relative paths](http://drupal.org/node/2014851)
- [x] | https://github.com/backdrop/backdrop/pull/923 | [b85b146](http://drupalcode.org/project/drupal.git/commit/b85b146a170ebcaf33e6a4b1923c3be6cb3f9cc2) | [Issue #2457743 by skein: translation_remove_from_set() runs unnecessary queries to fetch and update every single node with tnid 0](http://drupal.org/node/2457743)
- [x] | https://github.com/backdrop/backdrop/pull/925 | [27a7201](http://drupalcode.org/project/drupal.git/commit/27a72017bda3f3ead65b24de9f0997a0242d3554) | [Issue #2399657 by klausi: Add session hijacking test cases for SA-CORE-2014-006](http://drupal.org/node/2399657)
- [x] | https://github.com/backdrop/backdrop/pull/928 | [a3f85f1](http://drupalcode.org/project/drupal.git/commit/a3f85f1bd90a0ba3bf0143193b131859573892da) | [Issue #2386903 by pfrenssen, dcam: Fixed DOMDocument::importNode() warning due to IDs already being defined when running tests](http://drupal.org/node/2386903)
- [x] | https://github.com/backdrop/backdrop/pull/929 | [1a17a80](http://drupalcode.org/project/drupal.git/commit/1a17a804581a92d4fec9e3b9bf8dc63eee404653) | [Issue #2428399 by joshi.rohit100, SkidNCrashwell, Sagar Ramgade, er.pushpinderrana, Dom.: Default empty option label text different in documentation than in reality](http://drupal.org/node/2428399)
- [x] | https://github.com/backdrop/backdrop/pull/933 | [edf23f2](http://drupalcode.org/project/drupal.git/commit/edf23f2041761ad55d3cd38057f757bc68acfa5a) | [Issue #2208649 by areke, David_Rothstein, joachim, er.pushpinderrana, TravisCarden: Followup fixes to the documentation of the queue worker callback](http://drupal.org/node/2208649)
- [x] | N/A | [ebc5d85](http://drupalcode.org/project/drupal.git/commit/ebc5d852d5386e0aebbc4a816242dced46b3946e) | [Issue #1003788 by stefan.r, Alan D., JimmyAx, Josh Waihi, john_brown, twistor, bellHead, bzrudi71, pwolanin, gaas, wiifm, robhardwick, gngn: PostgreSQL PDOException: Invalid text representation when attempting to load an entity with a string or non-scalar ID](https://www.drupal.org/node/1003788)
- [x] | https://github.com/backdrop/backdrop/pull/939 | [880152a](http://drupalcode.org/project/drupal.git/commit/880152ae12536fde3975c4581494064532c4fbb1) | [Issue #1812056 by chx, byrond: Allow hook_field_schema() implementations to specify indexes for fields based on a column prefix (field sql storage test failing on various MySQL engines due to indexing unbound text fields)](http://drupal.org/node/1812056)
- [x] | https://github.com/backdrop/backdrop/pull/913 | [254424d](http://drupalcode.org/project/drupal.git/commit/254424dcfa2a165be18fec2917f6fbd22fbd9970) | [Issue #2315255 by Dave Reid, Devin Carlson: Allow custom HTML tags with a dash in the name to pass through filter_xss() when specified in the list of allowed tags](http://drupal.org/node/2315255)
- [x] | https://github.com/backdrop/backdrop/pull/930 | [992c346](http://drupalcode.org/project/drupal.git/commit/992c34675ab5910d8d93cd2a1a2ed28aaffe35d9) | [Issue #1055150 by Devin Carlson, rootwork, yoroy, brianV, JimmyAx: Time zone description is confusing on user register form](http://drupal.org/node/1055150)
- [x] | https://github.com/backdrop/backdrop/pull/931 | [a4b517f](http://drupalcode.org/project/drupal.git/commit/a4b517fd01e41842b26a1f0329824faae39bcce1) | [Issue #2331151 by David_Rothstein, Devin Carlson: Remove leftover code in testFileValidateSize() which runs the tests as a specific user](http://drupal.org/node/2331151)
- [x] | N/A | [494c442](http://drupalcode.org/project/drupal.git/commit/494c442e2d91c4816eccac30d29e3f4c8a0c0232) | [Issue #2364047 by JvE, dcam: Fix missing file definitions in hook_theme() in the Update Manager module](http://drupal.org/node/2364047)
- [x] | N/A | [d479272](http://drupalcode.org/project/drupal.git/commit/d479272463262506658efad773b347d9c67f8a30) | [Issue #1863290 by woprrr, vomiand, dcam, vegantriathlete: poll_node_info() has unused 'has_body' attribute that is left over from Drupal 6](http://drupal.org/node/1863290)
- [x] | N/A | [8717a8d](http://drupalcode.org/project/drupal.git/commit/8717a8da35fc5911947dfbea484e848df4a2cf01) | [Issue #2465159 by David_Rothstein, NancyDru: Fixed a regression in Drupal 7.36 which caused certain kinds of content types to become disabled if they were defined by a no-longer-enabled module.](http://drupal.org/node/2465159)

The command for generating this list was: 
`git log bd6bc619.. --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"`

**Comment by jenlampton** [comment]
I updated this issue to match what I put in the other one (two issues here are NA - and the formatting ;)

**Comment by quicksketch** [comment]
Woohoo! Looks like we've got all of 7.36 and 7.37 merged now! We should make a new bug fixing release shortly.

The only issue not completed yet is:

#159 | 2a3cf92 | Issue #667058 by greggles, DamienMcKenna, cweagans, travelertt, Dave Reid, tstoeckler, geerlingguy: Add a sites/all/libraries folder and encourage people to use it properly.

We have a stand-alone issue for improving our libraries support, we'll tackle that issue more comprehensively there.
