### ISSUE TITLE
[META] Port Drupal 7.37 Issues to Backdrop

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#936]
Below is a list of all the commits for Drupal 7.37.  Let's make sure these same fixes are included in Backdrop, where necessary.

- [ ] | #xx | [8f08dc9](http://drupalcode.org/project/drupal.git/commit/8f08dc9d13f43651fc8c298253891036c2ea8e8f) | [Issue #2392221 by joegraduate, er.pushpinderrana, zealfire, ClientGuy: install_run_task() and install_tasks() don't document the task structure](http://drupal.org/node/2392221)
- [ ] | #xx | [e091df1](http://drupalcode.org/project/drupal.git/commit/e091df1aa7cfa5341984f3dc323610053e73fa88) | [Issue #1684930 by amontero, David_Rothstein, joshi.rohit100, jthorson, dcam, rpayanm, jackbravo, yoroy: Add description to "administer filters" permission](http://drupal.org/node/1684930)
- [ ] | #xx | [2a3cf92](http://drupalcode.org/project/drupal.git/commit/2a3cf926af6259f85096b83522fbb890f51eb0fa) | [Issue #667058 by greggles, DamienMcKenna, cweagans, travelertt, Dave Reid, tstoeckler, geerlingguy: Add a sites/all/libraries folder and encourage people to use it properly](http://drupal.org/node/667058)
- [ ] | #xx | [39762b7](http://drupalcode.org/project/drupal.git/commit/39762b7135c10cd392061cafba504c2e7d8e2a3d) | [Issue #2356983 by bzrudi71, Dave Reid, jaredsmith: SystemQueue::claimItem() sometimes returns items in the wrong order (resolves locale test failures on PostgreSQL)](http://drupal.org/node/2356983)
- [ ] | #xx | [00e7efc](http://drupalcode.org/project/drupal.git/commit/00e7efc01bcd6d5698bc2faabc1003bc5dd999b4) | [Issue #2014851 by hlieberman, Wim Leers, bradjones1, markcarver: Drupal CSS preprocessing breaks protocol-relative paths](http://drupal.org/node/2014851)
- [ ] | #xx | [b85b146](http://drupalcode.org/project/drupal.git/commit/b85b146a170ebcaf33e6a4b1923c3be6cb3f9cc2) | [Issue #2457743 by skein: translation_remove_from_set() runs unnecessary queries to fetch and update every single node with tnid 0](http://drupal.org/node/2457743)
- [ ] | #xx | [27a7201](http://drupalcode.org/project/drupal.git/commit/27a72017bda3f3ead65b24de9f0997a0242d3554) | [Issue #2399657 by klausi: Add session hijacking test cases for SA-CORE-2014-006](http://drupal.org/node/2399657)
- [ ] | #xx | [a3f85f1](http://drupalcode.org/project/drupal.git/commit/a3f85f1bd90a0ba3bf0143193b131859573892da) | [Issue #2386903 by pfrenssen, dcam: Fixed DOMDocument::importNode() warning due to IDs already being defined when running tests](http://drupal.org/node/2386903)
- [ ] | #xx | [1a17a80](http://drupalcode.org/project/drupal.git/commit/1a17a804581a92d4fec9e3b9bf8dc63eee404653) | [Issue #2428399 by joshi.rohit100, SkidNCrashwell, Sagar Ramgade, er.pushpinderrana, Dom.: Default empty option label text different in documentation than in reality](http://drupal.org/node/2428399)
- [ ] | #xx | [edf23f2](http://drupalcode.org/project/drupal.git/commit/edf23f2041761ad55d3cd38057f757bc68acfa5a) | [Issue #2208649 by areke, David_Rothstein, joachim, er.pushpinderrana, TravisCarden: Followup fixes to the documentation of the queue worker callback](http://drupal.org/node/2208649)
- [x] | N/A | [ebc5d85](http://drupalcode.org/project/drupal.git/commit/ebc5d852d5386e0aebbc4a816242dced46b3946e) | [Issue #1003788 by stefan.r, Alan D., JimmyAx, Josh Waihi, john_brown, twistor, bellHead, bzrudi71, pwolanin, gaas, wiifm, robhardwick, gngn: PostgreSQL PDOException: Invalid text representation when attempting to load an entity with a string or non-scalar ID](https://www.drupal.org/node/1003788)
- [ ] | #xx | [880152a](http://drupalcode.org/project/drupal.git/commit/880152ae12536fde3975c4581494064532c4fbb1) | [Issue #1812056 by chx, byrond: Allow hook_field_schema() implementations to specify indexes for fields based on a column prefix (field sql storage test failing on various MySQL engines due to indexing unbound text fields)](http://drupal.org/node/1003788)
- [ ] | #xx | [254424d](http://drupalcode.org/project/drupal.git/commit/254424dcfa2a165be18fec2917f6fbd22fbd9970) | [Issue #2315255 by Dave Reid, Devin Carlson: Allow custom HTML tags with a dash in the name to pass through filter_xss() when specified in the list of allowed tags](http://drupal.org/node/2315255)
- [ ] | #xx | [992c346](http://drupalcode.org/project/drupal.git/commit/992c34675ab5910d8d93cd2a1a2ed28aaffe35d9) | [Issue #1055150 by Devin Carlson, rootwork, yoroy, brianV, JimmyAx: Time zone description is confusing on user register form](http://drupal.org/node/1055150)
- [ ] | #xx | [a4b517f](http://drupalcode.org/project/drupal.git/commit/a4b517fd01e41842b26a1f0329824faae39bcce1) | [Issue #2331151 by David_Rothstein, Devin Carlson: Remove leftover code in testFileValidateSize() which runs the tests as a specific user](http://drupal.org/node/2331151)
- [ ] | #xx | [494c442](http://drupalcode.org/project/drupal.git/commit/494c442e2d91c4816eccac30d29e3f4c8a0c0232) | [Issue #2364047 by JvE, dcam: Fix missing file definitions in hook_theme() in the Update Manager module](http://drupal.org/node/2364047)
- [x] | N/A | [d479272](http://drupalcode.org/project/drupal.git/commit/d479272463262506658efad773b347d9c67f8a30) | [Issue #1863290 by woprrr, vomiand, dcam, vegantriathlete: poll_node_info() has unused 'has_body' attribute that is left over from Drupal 6](http://drupal.org/node/1863290)
- [ ] | #xx | [8717a8d](http://drupalcode.org/project/drupal.git/commit/8717a8da35fc5911947dfbea484e848df4a2cf01) | [Issue #2465159 by David_Rothstein, NancyDru: Fixed a regression in Drupal 7.36 which caused certain kinds of content types to become disabled if they were defined by a no-longer-enabled module.](http://drupal.org/node/2465159)

The command for generating this list was: 
`git log bd6bc619.. --reverse --no-merges --pretty=format:"- [ ] | #xx | [%h](http://drupalcode.org/project/drupal.git/commit/%H) | [%s](http://drupal.org/node/)"`

**Comment by serundeputy** [comment]
dupe?
@jenlampton I believe https://github.com/backdrop/backdrop-issues/issues/918 already opened a meta.

should we close one?
super cool `git` command :bow:

**Comment by jenlampton** [comment]
Yes, not sure how I missed that one!
